### ISSUE TITLE
PowerShell task fails spuriously

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-tasks#10061]
PowerShell reports a failure when the script is `java -version`, even though that command exits normally. This doesn't happen when `script` is used instead of `powershell`, but to replace `powershell` with `script` in this use case, I'd need a function that could convert a Windows file path to a Linux one before passing it in as an environment variable.

An example error log with debug, and a couple of attempted workarounds, is: https://dev.azure.com/polymorpheus/BetterRandom/_build/results?buildId=280&view=logs&jobId=fae54436-6833-56e9-6b4c-aed871c1fe9e&taskId=ddfefad7-207d-5bca-8264-ac51e91969f1&lineStart=1&lineEnd=102&colStart=1&colEnd=1

The commit being built was https://github.com/Pr0methean/BetterRandom/commit/1e563a21507aa8634f5d170837a137e883ddd5a3. Here's the failing task from that build (Microsoft-hosted Windows 2019):
```
      - powershell: 'java -version; exit 0'
        displayName: Log Java Version
        env:
          JAVA_HOME: $(JAVA_HOME)
        ignoreLASTEXITCODE: true 
```
This is lines 176-180 of https://github.com/Pr0methean/BetterRandom/blob/1e563a21507aa8634f5d170837a137e883ddd5a3/azure.yml.
