### ISSUE TITLE
Multiple VSBuild targets not working in testing Issue #6975

### ISSUE THREAD

**Issue by gtalton** [microsoft/azure-pipelines-tasks#10077]
In reviewing the closed issue [MsBuild task should support a list of given solutions #6975](https://github.com/Microsoft/azure-pipelines-tasks/issues/6975#event-1975863867), I was happy to find that there was a way to submit multiple identified solutions to a VSBuild@1 Pipeline task if I delimited the solution file paths with a semicolon ';' character. 

However in testing I find this is not true. I first tested a positive case with one solution file and that worked, when I then set the solution to a simple dual solution delimited with semicolon. I get an error. 
```
- task: VSBuild@1
  inputs:
    solution: 'D:\a\1\s\a\a.sln;D:\a\1\s\b\b.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

Renders this error output: 

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: D:\a\1\s\a\a.sln;D:\a\1\s\b\b.sln
##[error]Process 'msbuild.exe' exited with code '1'.
```

Is this, in fact, possible?  Is there any way to iterate over a list of solution paths?
