### ISSUE TITLE
Python Script V0: ##[error]The given path was not to a file: 'D:\a\1\s

### ISSUE THREAD

**Issue by brcrista** [microsoft/azure-pipelines-tasks#10187]
Here's the YAML snippet for v0.147 of the task:

```yaml
- task: PythonScript@0
  inputs:
    #scriptSource: 'filePath' # Options: filePath, inline
    #scriptPath: # Required when scriptSource == FilePath
    #script: # Required when scriptSource == Inline
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
```

In YAML, if you specify `script` but don't specify `inline`, you'll get a confusing error:
`##[error]The given path was not to a file: 'D:\a\1\s'.`

Currently, the correct way to use the task in YAML is to specify `scriptSource: inline`, but the error does not make this clear.

This is some YAML-unfriendliness left over from the task being made for classic editor.  If `script` is set, the task should infer `inline`.
