### ISSUE TITLE
Matrix Strategy in template

### ISSUE THREAD

**Issue by ladislas** [microsoft/azure-pipelines-tasks#10182]
Hi there! 

I've been playing with Azure Pipelines templates and I was wondering if it was possible to mix templates and matrix.

I've tried passing the matrix as a parameter to the template, either directly or through a `each` mapping. I've also tried adding `strategy` to `- template` in the `azure-pipelines.yml` but it does not work either.

Is this even possible?
And if not, is this something you'll consider adding?

Thanks a lot!
Best,  
-- Ladislas

**Comment by ladislas** [comment]
anyone?

**Comment by vtbassmatt** [comment]
Option 1:

```yaml
# azure-pipelines.yml
jobs:
- template: template.yml

# template.yml
jobs:
- job: foo
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      one:
        num: one
      two:
        num: two
  steps:
  - script: echo The number is $(num)
```

Option 2:

```yaml
# azure-pipelines.yml
jobs:
- template: template.yml
  parameters:
    theMatrix:
      one:
        num: one
      two:
        num: two

# template.yml
parameters:
  theMatrix: {}

jobs:
- job: foo
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix: ${{ parameters.theMatrix  }}
  steps:
  - script: echo The number is $(num)
```
