### ISSUE TITLE
PublishCodeCoverageResults@1 uploads to the artifacts with spaces which is not supported by deploy stages

### ISSUE THREAD

**Issue by Gimly** [microsoft/azure-pipelines-tasks#10336]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults@1

## Environment
- Server - Azure Pipelines
- Agent - Hosted Ubuntu 1604

## Issue Description

I'm using the new multi stage yaml build configuration and there seems to be an issue with the PublishCodeCoverageResults@1 task because it's uploading the of the code coverage report with a name containing spaces, which is not supported.

Here's the error I'm getting in the deploy task:

```
Job Job1: Step Download_Code Coverage Report_51440 has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.
```

## Troubleshooting

Here's my azure-pipelines.yml file for reference:

```yml
trigger: 
- master

stages:
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'npm install and build'

    - script: |
        ng lint --format stylish
      displayName: 'Lint TypeScript files'

    - script: |
        ng test --watch=false --code-coverage
      displayName: 'Run unit tests with code coverage'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage Angular results'
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'testsResults/unitTests/coverage/cobertura-coverage.xml'
        reportDirectory: 'testsResults/unitTests/coverage/'
        failIfCoverageEmpty: true

    - task: PublishTestResults@2
      displayName: 'Publish unit tests results'
      condition: succeededOrFailed()
      inputs:
        searchFolder: $(System.DefaultWorkingDirectory)
        testRunTitle: MyApp
        testResultsFormat: JUnit
        testResultsFiles: "**/TESTS*.xml"

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'dist/'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: 'MyApp'
      displayName: Publish build artifacts

- stage: Deploy
  jobs:
  - deployment:
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying !
```
