### ISSUE TITLE
Merge coverage reports from multiple runs

### ISSUE THREAD

**Issue by pkuczynski** [microsoft/azure-pipelines-tasks#10353]
## Required Information

*Type*: bug
**Enter Task Name**: PublishCodeCoverageResults@1  

## Environment

- Server - Azure Pipelines

## Issue Description

Task PublishCodeCoverageResults@1 supports reports from multiple files, but the summary just shows the first match. 

### Task logs

The behavior for a task configured with a wildcard path for the coverage file is a little inconsistent:

```
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/packages/*/build/coverage/coverage.cobertura.xml
```

In this example, there are few coverage.cobertura.xml files from separate test runs. Unfortunately, I receive warning:

```
##[warning]Multiple file or directory matches were found. Using the first match: ```

Ideally, the summary would show the coverage for each assembly separately. Because I'm working in a monorepo and would like to trace multiple folders separately.

A similar issue has been reported in https://github.com/MicrosoftDocs/vsts-docs/issues/4135

**Comment by mhamilton723** [comment]
+1 on this issue!

**Comment by pderaaij** [comment]
This would be a great addition when working with a monorepo.

**Comment by pkuczynski** [comment]
Not that I know of :(

**Comment by juliocr-ciandt** [comment]
+1

**Comment by boyanio** [comment]
I use a custom script to merge all reports into a single one. In this [gist](https://gist.github.com/boyanio/36b9d6d9b32fae761250f7bd4fd6cbb4) you can see an example using [istanbul](https://istanbul.js.org/)

**Comment by avilde** [comment]
I use `jest-junit` and `cobertura` reports both from front-end (create react app, jest) and back-end (.NET Core 3.0) but there is no merge option for both reports.
What a pity.

+1

**Comment by jhonnymertz** [comment]
Is there any update on this issue? I'm working on a monorepo and the fact that it cannot collect all the coverage reports limits the usage of this information in dashboards, for example. All the existing widgets to report code coverage in ADO dashboards rely on this data...

**Comment by MisinformedDNA** [comment]
To get around this, we can merge all the files using ReportGenerator. This is what worked for me:

1. (Optional) If the code coverage is coming from different jobs, publish the coverage files as artifacts and then have a later job download all the artifacts

2. Create a report from all coverage files and publish
```yaml
- task: reportgenerator@4
  inputs:
    reports: **/coverage.cobertura.xml;artifact/**/cobertura-coverage.xml
    targetdir: $(Pipeline.Workspace)/coveragereport

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "Cobertura"
    summaryFileLocation: $(Pipeline.Workspace)/coveragereport/Cobertura.xml
```

This has worked well for me.

**Comment by andreujuanc** [comment]
Work around is good and all, but in some orgs, it can take quite a while until you get a marketplace extension approved, if at all.
100% should be handled by Azure Pipelines and not some random extension.

**Comment by drdamour** [comment]
fwiw it looks like this might have been fixed with the v2 of this task at https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV2/task.json with https://github.com/microsoft/azure-pipelines-tasks/pull/11144 but it hasn't been published to devops...not sure why was also asked in #13257

**Comment by drdamour** [comment]
@MisinformedDNA where's that reportgenerator task come from?

**Comment by MisinformedDNA** [comment]
@drdamour https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

**Comment by ByteDev** [comment]
Using reportgenerator in the way described above doesn't fully work for me. I get the following warning from the `PublishCodeCoverageResults@1` task: `[warning]No code coverage results were found to publish.`.

However, if i set `summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'` then everything works but I'm back to getting the misleading warning: `Multiple file or directory matches were found. Using the first match...`.

**Comment by MisinformedDNA** [comment]
My guess is that something either is in the wrong place or is looking in the wrong place.

Can you share your YAML?

**Comment by msrinivascharan** [comment]
I have a project with three different modules, two Java and one Python. all three modules generate Cobertura based code coverage reports. I am able to merge all three into one using @danielpalme "ReportGenerator" extension. able to apply gating condition using merged coverage report. Please refer [this](https://github.com/coverlet-coverage/coverlet/issues/474).

**Comment by mike-bagheri** [comment]
While the `reportgenerator` can merge the results, one has to specify the `reporttypes`

`- task: DotNetCoreCLI@2
            displayName: 'Create code coverage report'
            inputs:
              command: custom
              custom: tool
              arguments: 'run reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)\CodeCoverage -reporttypes:HtmlInline_AzurePipelines;Cobertura'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage report'
            inputs:
              codeCoverageTool: 'cobertura'
              summaryFileLocation: '$(Build.SourcesDirectory)\CodeCoverage\*cobertura.xml'`

**Comment by jack4it** [comment]
> The `reportgenerator` can merge the results, and then I had to specify the `reporttypes` and include `Cobertura` to make it work
> 
> ```
> - task: DotNetCoreCLI@2
>   displayName: 'Create code coverage report'
>     inputs:
>       command: custom
>       custom: tool
>       arguments: 'run reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)\CodeCoverage -reporttypes:HtmlInline_AzurePipelines;Cobertura'
> 
> - task: PublishCodeCoverageResults@1
>   displayName: 'Publish code coverage report'
>     inputs:
>       codeCoverageTool: 'cobertura'
>        summaryFileLocation: '$(Build.SourcesDirectory)\CodeCoverage\*cobertura.xml'
> ```

In my case, I had to add the `reportDirectory` param as well

```
          - task: PublishCodeCoverageResults@1
            displayName: Publish code coverage results
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(System.DefaultWorkingDirectory)/testresults/coverage/reports/Cobertura.xml"
              reportDirectory: "$(System.DefaultWorkingDirectory)/testresults/coverage/reports/"
```

**Comment by svdHero** [comment]
Hi there,

when I try to use the workaround above as in:
```yaml
    pool:
      vmImage: ubuntu-20.04

    variables:
      disable.coverage.autogenerate: 'false' # for report generator

    steps:
    # more tasks here...

    - task: DotNetCoreCLI@2
      displayName: 'Install ReportGenerator'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global dotnet-reportgenerator-globaltool --version 4.8.12'

    - task: DotNetCoreCLI@2
      displayName: 'Merge code coverage files'
      inputs:
        command: custom
        custom: tool
        arguments: 'run reportgenerator -reports:$(Build.SourcesDirectory)/build_reports/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/build_reports/code_coverage -reporttypes:HtmlInline_AzurePipelines;Cobertura'

```
I get the error message
```
Cannot find a tool in the manifest file that has a command named 'reportgenerator'.
```
Any ideas what's wrong here? @mike-bagheri and @jack4it , how did you guys install `reportgenerator`? I'd appreciate any advice. Thank you so much in advance.

**Comment by mike-bagheri** [comment]
> Hi there,
> 
> when I try to use the workaround above as in:
> 
> ```yaml
>     pool:
>       vmImage: ubuntu-20.04
> 
>     variables:
>       disable.coverage.autogenerate: 'false' # for report generator
> 
>     steps:
>     # more tasks here...
> 
>     - task: DotNetCoreCLI@2
>       displayName: 'Install ReportGenerator'
>       inputs:
>         command: custom
>         custom: tool
>         arguments: 'install --global dotnet-reportgenerator-globaltool --version 4.8.12'
> 
>     - task: DotNetCoreCLI@2
>       displayName: 'Merge code coverage files'
>       inputs:
>         command: custom
>         custom: tool
>         arguments: 'run reportgenerator -reports:$(Build.SourcesDirectory)/build_reports/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/build_reports/code_coverage -reporttypes:HtmlInline_AzurePipelines;Cobertura'
> ```
> 
> I get the error message
> 
> ```
> Cannot find a tool in the manifest file that has a command named 'reportgenerator'.
> ```
> 
> Any ideas what's wrong here? @mike-bagheri and @jack4it , how did you guys install `reportgenerator`? I'd appreciate any advice. Thank you so much in advance.

From the extension in Azure DevOps, installed this

![image](https://user-images.githubusercontent.com/36276893/134214801-01654ed3-8305-4c2d-b0f8-19f465fd12c5.png)

**Comment by danielpalme** [comment]
There a two options:

- You can use the [global tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool):
```
dotnet new tool-manifest
dotnet tool install --global dotnet-reportgenerator-globaltool
reportgenerator -reports:...
```
- You can install the [Azure DevOps extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator)
```yaml
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: ReportGenerator
      inputs:
        reports: 'coverage.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
        sourcedirs: '' # Optional directories which contain the corresponding source code (separated by semicolon). The source directories are used if coverage report contains classes without path information.
        historydir: '' # Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.
        plugins: '' # Optional plugin files for custom reports or custom history storage (separated by semicolon).
        assemblyfilters: '+*' # Optional list of assemblies that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        classfilters: '+*' # Optional list of classes that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        filefilters: '+*' # Optional list of files that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
        title: '' # Optional title.
        tag: '$(build.buildnumber)_#$(build.buildid)' # Optional tag or build version.
        customSettings: '' # Optional custom settings (separated by semicolon). See: https://github.com/danielpalme/ReportGenerator/wiki/Settings.
```

**Comment by svdHero** [comment]
Thank you @danielpalme , but when I do a
```
dotnet new tool-manifest
dotnet tool install --global dotnet-reportgenerator-globaltool
reportgenerator -reports:...
```
I get a different pipeline error saying
```
Cannot find a tool in the manifest file that has a command named 'reportgenerator'.
```
Any idea what's wrong here?

I will also go and try your AzureDevops Extension.

**Comment by danielpalme** [comment]
@svdHero 
I just tried it myself, the following works for me:

```yaml
- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool --version 4.8.12'

- script: reportgenerator "-reports:$(Build.SourcesDirectory)/build_reports/**/coverage.cobertura.xml"" -targetdir:$(Build.SourcesDirectory)/build_reports/code_coverage" -reporttypes:HtmlInline_AzurePipelines;Cobertura
  displayName: Merge code coverage files
```

**Comment by drdamour** [comment]
Bamp/not stale

**Comment by james1301** [comment]
@acesiddhu is there an update on this?

**Comment by purijatin** [comment]
This is a pain point. We have a repo that has java, python and dotnet modules. And cumbersome to merge all of them to a single report.

**Comment by inloox-konrad** [comment]
We've now run into this as well. The doc at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops clearly states that "Multiple summary files will be merged into a single report.", but that is patently untrue. At the least the doc should be fixed to reflect the reality thay this feature is not yet included. Finding this out the hard way is time-consuming.

**Comment by aolszowka** [comment]
Keeping the issue alive; as mentioned by others still no fix, and based on this comment https://github.com/microsoft/azure-pipelines-tasks/issues/15160#issuecomment-902632589 doesn't seem like there is a plan to merge in the v2 version of this task which does have a combiner?

The suggested workaround of using ReportGenerator (https://github.com/danielpalme/ReportGenerator) does work but is a bit of a hack in the sense that the last user of `PublishCodeCoverageResults` is the winner. This can be difficult if you have a complicated pipeline that leverages templates and requires a significant amount of coordination.

**Comment by abatishchev** [comment]
Same here. Only 1 out of many tests projects is included into the results.

I tried adding an additional task mentioned on [Stack Overflow](https://stackoverflow.com/a/68919752):

```yaml
- task: reportgenerator@4
  displayName: 'Merge code coverage reports'
  inputs:
    reports: '$(Agent.TempDirectory)\TestResults\**\coverage.cobertura.xml'
    targetdir: '$(Agent.TempDirectory)\TestResults\Merged\'
    reporttypes: Cobertura
    verbosity: Verbose
```

but `reportgenerator` is not and can't be installed to my ADO project.

**Comment by danielpalme** [comment]
> but `reportgenerator` is not and can't be installed to my ADO project.

You have to hit the "Get it free" button on this website: https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

Then the task should be available (you should use reportgenerator@**5**)

**Comment by abatishchev** [comment]
> You have to hit the "Get it free" button on this website:

Unfortunately I can't, my company's policy prohibits installing third-party extensions. Technically there is a process but it's near-impossible to get through.

I'm trying to work it around by install it as a global tool and run directly. But so far it doesn't make any difference: all tasks succeed, build succeeds, code coverage report stays the same.

I have multiple test projects which I run simultaneously by passing `*.Tests.csproj`. Is the resulting code coverage results file's name unique?

**Comment by danielpalme** [comment]
This should work 
```
disable.coverage.autogenerate: 'true'

...

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  condition: always()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)\TestResults\Merged\Cobertura.xml'
    reportDirectory: '$(Agent.TempDirectory)\TestResults\Merged'
```

The environment variable "disable.coverage.autogenerate" is important, otherwise PublishCodeCoverageResults will regenerate the coverage HTML report.

**Comment by abatishchev** [comment]
hi @danielpalme, thank you for your help! unfortunately I'm still unable to get it working.

What worked: the format has changed and it looks much nicer:

![image](https://user-images.githubusercontent.com/351644/212968456-751dde25-3e5a-4af1-828f-400ad243eac5.png)

However it still shows only the first test project's results.

My YAML:

```yml
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '**\*Tests.csproj'
    arguments: '--no-build --no-restore --configuration ${{ parameters.configuration }} --settings $(RepoRoot)\.runsettings --blame --collect "Code coverage" --logger "trx" --results-directory $(Agent.TempDirectory)\TestResults\ /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Agent.TempDirectory)\TestResults\'
    publishTestResults: false


- task: DotNetCoreCLI@2
  displayName: 'Install reportgenerator'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool'

- task: PowerShell@2
  displayName: 'Merge code coverage reports'
  inputs:
    targetType: inline
    script: |
      Write-Host '##vso[task.setVariable variable=disable.coverage.autogenerate;isSecret=false]true'

      $source = '$(Agent.TempDirectory)\TestResults\**\coverage.cobertura.xml'
      $target = '$(Agent.TempDirectory)\TestResults\Merged\'

      & reportgenerator.exe -reports:$source -targetdir:$target -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  condition: always()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)\TestResults\Merged\**\*.xml'
    reportDirectory: '$(Agent.TempDirectory)\TestResults\Merged'
```

Can you please take a look and see if I've missed anything?

```

**Comment by aolszowka** [comment]
@abatishchev You beat me to the punch I was just going to reply to say that you can install the tool manually via Dotnet-Tool and merge it, you've got it and your solution looks more or less like what we use internally. However as I mentioned above:

The suggested workaround of using ReportGenerator (https://github.com/danielpalme/ReportGenerator) does work but is a bit of a hack in the sense that the last user of PublishCodeCoverageResults is the winner. This can be difficult if you have a complicated pipeline that leverages templates and requires a significant amount of coordination.

Be careful!

**Comment by danielpalme** [comment]
> Can you please take a look and see if I've missed anything?

I hope. Could you please add the following argument to reportgenerator.exe: `-verbosity:verbose`
Then you could check the output of that task.

For every coverage file that gets processed the following line should appear in the messages:
`Loading report '%%PATH%%' x/y in memory`

Do several coverage files get processed?
- If yes: Great, then we can investigate `PublishCodeCoverageResults`
- If no: Then we have to check how many coverage file do exist after the "Run tests" task

**Comment by danielpalme** [comment]
In most of my projects I use the package [coverlet.collector](https://www.nuget.org/packages/coverlet.collector)

Then I run the tests with the following command (only important arguments added here):
dotnet test --collect:"XPlat Code Coverage"

This results in cobertura file in each test project in a subfolder named `TestResults\%%GUID%%\coverage.cobertura.xml`

Then I pass all cobertura files to ReportGenerator with the following argument:

`-reports:*Tests\TestResults\*\coverage.cobertura.xml`

**Comment by abatishchev** [comment]
I've changed the "run tests" to this:

```
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '**\*Tests.csproj'
    arguments: '--no-build --no-restore --configuration ${{ parameters.configuration }} --settings $(RepoRoot)\.runsettings --blame --collect "XPlat Code Coverage" --logger "trx" --results-directory $(Agent.TempDirectory)\TestResults\ /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Agent.TempDirectory)\TestResults\'
    publishTestResults: false
```

i.e. only from `--collect "Code coverage"` to `--collect "XPlat Code Coverage"` and it made no difference:

```
Results File: C:\__w\_temp\TestResults\ContainerAdministrator_AED0B744811A_2023-01-17_23_46_43.trx

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 81 ms - AzureThrottle.ConfigurationTests.dll (net6.0)

Calculating coverage result...
  Generating report 'C:\__w\_temp\TestResults\coverage.net6.0.cobertura.xml'
```
