### ISSUE TITLE
Azure PowerShell v4 does not allow dynamic task variable for "Azure Subscription" input

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-pipelines-tasks#10376]
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: AzurePowershellV4

## Environment
- Azure Pipelines - private - Hosted Windows 2019 with VS2019
    
## Issue Description

The "Azure Subscription" task input does not accept task variables that are **late-bound**, i.e. that are set to variables such as `$(AzureSubscription)`, AND are set during the pipeline by a preceding task.

The preceding task could be a simple PowerShell task that updates this variable:
```
Write-Host "##vso[task.setvariable variable=AzureSubscription]NameAsAppearsInDropdown"
```

The pipeline fails immediately on creation, and does not even attempt to execute any tasks, including the AzurePowershellV4 task.

### Task logs

```
##[Error 1]
Exception Message: The pipeline is not valid. Job Phase_1: Step AzurePowerShell input ConnectedServiceNameARM references service connection $(AzureSubscription) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)
Exception Stack Trace:    at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidatePipelineProcess(IVssRequestContext requestContext, Guid scopeIdentifier, Int32 definitionId, Guid planId, PipelineEnvironment environment, PipelineProcess pipeline, BuildOptions options) in D:\v2.0\P1\_work\1\s\DistributedTask\Sdk\Server\TaskHub.cs:line 5256
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidateProcess(IVssRequestContext requestContext, Guid scopeIdentifier, TaskOrchestrationOwner definition, Guid planId, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions options) in D:\v2.0\P1\_work\1\s\DistributedTask\Sdk\Server\TaskHub.cs:line 5172
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.CreatePlan(IVssRequestContext requestContext, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String& pipelineInitializationLog) in D:\v2.0\P1\_work\1\s\DistributedTask\Sdk\Server\TaskHub.cs:line 252
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.RunPlan(IVssRequestContext requestContext, TaskAgentPoolReference pool, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String& pipelineInitializationLog) in D:\v2.0\P1\_work\1\s\DistributedTask\Sdk\Server\TaskHub.cs:line 1324
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.DistributedTask.PipelineOrchestrator.StartDeployment(AutomationEngineInput input) in D:\v2.0\P1\_work\1\s\ReleaseManagement\Service\ReleaseManagement2\Server\DistributedTask\PipelineOrchestrator.cs:line 79
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in D:\v2.0\P1\_work\1\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 222 
```

## Troubleshooting
The AzurePowerShellV4 task DOES accept task variables ONLY when the variable is defined in the release, so that the initial value is known at the time the release is created.

**Comment by Lovakumar** [comment]
@JoeGaggler this feature isn't supported today. Usage of service endpoints (Azure Subscription is one of kind) in release/build definition is controlled by some permissions. At the time of saving a release/build definition service validates that the author (whoever is saving the definition) has appropriate permissions on the endpoint. If we support variable replacements for service endpoint input then service can't validate that the author has required permissions or not and it might become a security issue.

**Comment by JoeBrockhaus** [comment]
@Lovakumar That makes sense to a degree, though it seems dubious the permissions couldn't be assessed at runtime, failing the pipeline just the same.  

Is there a proposed workaround for dealing with this?
---
The first thought that comes to mind is a YAML Template. 
Should this work?

- Multiple Steps which share an `Azure Subscription` Connection can be defined & used within a Template: <br/>
  `template.yml`
  ```yaml
  parameters: 
    AzureSubscription: ''
  ...
  steps:
  - task: AzureAppServiceManage@0
    inputs:
      Action: 'Stop Azure App Service'
      azureSubscription: ${{ parameters.AzureSubscription }}
      ...
  - task: AzureRmWebAppDeployment@4
    inputs:
      azureSubscription: ${{ parameters.AzureSubscription }}
      ...
  ```
- Then from the parent pipeline: <br/>
  `azure-pipelines.yml`
  ```yaml
  ...
  - ${{ if eq(variables['someCondition'], 'firstFixedValue') }}
    - template: template.yml
      parameters:
        AzureSubscription: 'Connection Name 1'
        ...
  - ${{ if eq(variables['someCondition'], 'secondFixedValue') }}
    - template: template.yml
      parameters:
        AzureSubscription: 'Connection Name 2'
        ...
  ```

This is still an approximation of a dynamic solution .. but unless you are building pipelines that build DevOps Projects + Connections (!!), then a fixed number of Connections must exist. Therefore, so long as this works, 'wrapping' your Connection-consuming Tasks into a Template & using appropriate conditions to map the fixed set of Connections to those Tasks .. is at least better than copying all those Tasks.

**Comment by Lovakumar** [comment]
@JoeBrockhaus YAML pipelines use different security mechanism. User can authorize service connections for a YAML pipeline - there is no save time validation. Hence YAML templates would work for you.

**Comment by JoeGaggler** [comment]
@Lovakumar I tried to use YAML templates as in the example from @JoeBrockhaus but it failed with the same error:

<img width="752" alt="yaml-azure-variable-security" src="https://user-images.githubusercontent.com/27233871/58732060-07d1fe80-83b6-11e9-8676-0fe1604ab581.PNG">

**Comment by JoeGaggler** [comment]
My apologies. My pipeline was referencing `azureSubscription` both using the `${{ }}` syntax and the `$()` syntax. This is working for me when I used to correct syntax for all references.

**Comment by Lovakumar** [comment]
Closing this issue as per previous comment.

**Comment by MisinformedDNA** [comment]
@JoeGaggler @Lovakumar  So what's the correct syntax? Here's a snippet of my YAML

```yaml
- pwsh: Write-Host "##vso[task.setvariable variable=AzureSubscription;]SP-Blah"
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(AzureSubscription)
    ScriptType: InlineScript
    Inline: |
      Get-AzResource -ResourceGroupName $(ResourceGroupName)
    azurePowerShellVersion: LatestVersion
```

And I get the same error as above:

![image](https://user-images.githubusercontent.com/1784452/61761754-48863c80-ad95-11e9-91b1-fc3cb7a3b89a.png)

**Comment by Lovakumar** [comment]
@MisinformedDNA run time variables aren't supported for service connection OR azure subscription. In your code sample, you are referring to AzureSubscription variable which will get initialized at the run time (but not at save time). Your syntax is correct but you need to set AzureSubscription variable as part of variables.

**Comment by MisinformedDNA** [comment]
@Lovakumar So run-time variables aren't supported but parameters are? And what if the parameters originated from a run-time variable in a parent template?

**Comment by Lovakumar** [comment]
@MisinformedDNA parameters can refer to variables and those variables should have a value at save time itself (i.e. ultimately value of azure subscription should be known at the time of save).

**Comment by MisinformedDNA** [comment]
@JoeGaggler @Lovakumar I tried @JoeBrockhaus's [solution](https://github.com/microsoft/azure-pipelines-tasks/issues/10376#issuecomment-494579580), but where are those variables (i.e. `variables['someCondition']` defined? If I define them in YAML, it completely misses the point for dynamically selecting a template. If I set them in the definition (UI), then they resolve to `null` ([see also](https://github.com/MicrosoftDocs/vsts-docs/issues/4591)). How do I make this work?

**Comment by kaushikmaji** [comment]
In my case, I resolved it by using condition( ) function at job level which is evaluated at runtime based upon runtime variables. Which meant I had to write similar replica for jobs, but I templated repeating tasks within those jobs, thus reducing overall line of code repetition.


```
trigger:
- master

variables:
- name: buildConfiguration
  value: 'Release'
- name: azureUatServiceConnection
  value: 'azure_sp_connection'
- name: azureProdServiceConnection
  value: 'azure_sp_connection'

stages:
- stage: 'Build'
  displayName: 'Publish Artifacts'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo Build Task!
      displayName: 'Run a one-line script'

    - task: CopyFiles@2
      inputs:
        SourceFolder: ''
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'reporoot'
        publishLocation: 'Container'

- stage: 'Provision'
  displayName: 'Anything per your environment'
  jobs: 
  - deployment: 'RoleAssignmentUat'
    condition: and(succeeded(), eq(variables.environment, 'uat'))  # This is runtime evaluation
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: 'Release'
    environment: roleassignment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: reporoot
            patterns: '**/*'
          - template: pipeline_template/template.yml  # Template reference for repeating task             
            parameters:
              azure_service_connection: '${{ variables.azureUatServiceConnection }}' # This is compile time
              roleassignments: '$(roleassignments)'
              
  - deployment: 'RoleAssignmentProd'
    condition: and(succeeded(), eq(variables.environment, 'prod')) # This is runtime evaluation
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: 'Release'
    environment: roleassignment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: reporoot
            patterns: '**/*'
          - template: pipeline_template/template.yml  # Template reference for repeating task            
            parameters:
              azure_service_connection: '${{ variables.azureProdServiceConnection }}' # This is compile time
              roleassignments: '$(roleassignments)'

```
