### ISSUE TITLE
gradle build task

### ISSUE THREAD

**Issue by ZombieD** [microsoft/azure-pipelines-tasks#10426]
Hello!

I have a problem with the gradle build task. It's search for the sdk on the wrong location as you can see:

```
* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory 'C:\Users\ZombieD\Downloads\AzureDevopsAgent\_work\2\s\D:AndroidSDK' does not exist.
```
My android sdk is at D:\AndroidSDK but the task extends this path with the SystemWorkingDirectory.

I have a local propeties generator script before this task:
```
- bash: |
     #!/bin/bash
     
     echo "sdk.dir=$(AndroidSdkLocation)" > local.properties
  displayName: 'Generate local.properties'
```
It's works fine and create a valid local.properties file. I have tried to sepcify ANDROID_SDK_ROOT at the agent's capabilities but nothing changed...

**Comment by ZombieD** [comment]
My gradle build task looks like this: 
```
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
  displayName: 'gradlew build'
```
