### ISSUE TITLE
DotNetCoreInstaller@0 downloads x64 SDK on ARM64

### ISSUE THREAD

**Issue by directhex** [microsoft/azure-pipelines-tasks#10421]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreInstaller@0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
https://dev.azure.com/dnceng/public/_build/results?buildId=194269

- Agent - Hosted or Private: 
    
Private agent, Ubuntu 16.04 ARM64

## Issue Description

`Detected platform (Primary): linux-arm64` -> `dotnet-install: Payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.203/dotnet-sdk-2.2.203-linux-x64.tar.gz`

That's not right.

YAML is:

```
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.203'
    displayName: Install .NET Core 2.2 latest
    condition: or(eq(variables['poolname'], 'Hosted VS2017'),startsWith(variables['poolname'], 'Xamarin-ARM64'))
```
