### ISSUE TITLE
Secret objects shows in log when baking kubernetes manifests

### ISSUE THREAD

**Issue by gsimoes** [microsoft/azure-pipelines-tasks#10442]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: KubernetesManifest  

## Environment
- Server - Azure Pipelines
- Agent - Private, docker agent tag ubuntu-16.04-docker-18.06.1-ce-standard
    
## Issue Description
When using the KubernetesManifest task with the bake action using a helm chart, secrets created by the helm chart are shown in the logs.

```yaml
 - task: KubernetesManifest@0
    name: bake
    displayName: bake web app
    inputs:
      action: bake
      helmChart: my-chart
      overrideFiles: values.yaml
```

Is it possible to hide secret objects or have an option to hide the rendered objects?
