### ISSUE TITLE
Uploading a folder to blob using AzureFileCopyV2

### ISSUE THREAD

**Issue by SefaOray** [microsoft/azure-pipelines-tasks#10523]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureFileCopyV2

## Environment
- Azure Pipelines
    
- Agent - Hosted or Private: 
Hosted agent from the pool called Hosted.

## Issue Description

I'm unable to upload a folder to Azure Blob storage using this task. This task includes default Pattern parameter if source is a file but it is still added when my source is pointing to a folder. 

I also tried pointing to one upper folder as source and adding source folder name in Pattern parameter, same error.

Task yaml

```
steps:
- task: AzureFileCopy@2
  displayName: 'Copy Deployment Templates'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/_Artifact/drop/Infrastructure.Azure/SharedTemplates'
    azureSubscription: '$(AzureSubscription)'
    Destination: AzureBlob
    storage: '$(ARMArtifactsStorageContainer)'
    ContainerName: armartifacts
    BlobPrefix: SharedTemplates

```

### Error logs

> Error parsing source location "D:\a\r1\a\_Artifact\drop\Infrastructure.Azure\SharedTemplates": Failed to enumerate directory D:\a\r1\a\_Artifact\drop\Infrastructure.Azure\SharedTemplates\ with file pattern *. The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
