### ISSUE TITLE
Provide a concrete worked example for Publish Code Coverage Results Task + JaCoCo

### ISSUE THREAD

**Issue by haokanga** [microsoft/azure-pipelines-tasks#10559]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Lack of Documentation 

**Enter Task Name**: Publish Code Coverage Results task  
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops
list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

One concrete worked example is far more helpful than a schema-only documentation. Please kindly add worked examples for JaCoCo (and cobertura)

For example:

```yaml
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
      summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml # e.g., instead of $(System.DefaultWorkingDirectory)/target/site/jacoco/index.xml 
```
