### ISSUE TITLE
KubernetesManifest : Pull image for a Job from a private registry

### ISSUE THREAD

**Issue by alanta** [microsoft/azure-pipelines-tasks#10580]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: KubernetesManifest

## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: **not allowed to post this info**

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: **Hosted Ubuntu 1604**

## Issue Description

When deploying a [Job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) to Kubernetes (AKS) using the KubernetesManifest task, the imagePullSecret provided on the task is not applied to the job manifest. This causes image pull to fail for the job when using a private registry like Azure Container Registry. This works fine for other types of k8s resources.

Note that the task finishes and deploys all the resources but the job pod fails to start due to a 401 on image pull.

![afbeelding](https://user-images.githubusercontent.com/73225/58964613-801e3280-87af-11e9-81e9-070c63a4a530.png)

After digging into the sources for the task, I suspect the issue is in [KubernetesManifestV0/src/models/constants.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesManifestV0/src/models/constants.ts) line 14, which does not list job as a recognized workload type.

The job manifest looks like this:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: content-migrations-job
spec:
  template:
    spec:
      containers:
        - name: content-migrations
          image: highgrounddev.azurecr.io/content-mock-migrations:0.1.0-ci0029
          imagePullPolicy: IfNotPresent
          env:
          - name: Logging__LogLevel__Default
            value: Information
          - name: Database__Provider
            valueFrom:
              configMapKeyRef:
                name: content-mock-db-config
                key: provider
          - name: Database__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: content-mock-db-config
                key: connectionstring
      restartPolicy: Never
```
The pipeline stage looks like this:

```yaml
- stage: DeployToTest
  displayName: 'Deploy to Test'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # only deploy from master!
  jobs:
  - deployment: Deploy
    displayName: Deploy to Test
    pool:
      vmImage: $(vmImageName)
    environment: 'test.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'Test-akslabmvv-default-1558072887705'
              namespace: 'default'
              command: 'delete'
              arguments: '--ignore-not-found=true  jobs/content-migrations-job'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'

          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'Test-akslabmvv-default-1558072887705'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: 'pullsecret'
              dockerRegistryEndpoint: '$(containerRegistry)'

          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'Test-akslabmvv-default-1558072887705'
              namespace: 'default'
              manifests: '$(System.ArtifactsDirectory)/manifests/*.yaml'
              containers: '$[ dependencies.Build.outputs[''Build.setvarStep.fullImageName''] ]'
              imagePullSecrets: 'pullsecret'
```
### Task logs
[deploy-stage-logs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3257733/deploy-stage-logs.txt)

### Error logs

There was no error, though perhaps there should be since the job failed to start.
