### ISSUE TITLE
[Feature Request] AzureFunctionApp Management Group Service Connector Support

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-pipelines-tasks#10594]
## Required Information

**Question, Bug, or Feature?**  
Feature

**Enter Task Name**: AzureFunctionApp

## Issue Description

The AzureFunctionApp should support the Management Group service connector option, so that one service connection can be used to deploy to multiple subscriptions.

Azure Function App names have to be globally unique so it should by default search all connected subscriptions in the management group for the "appName", but an optional azureSubscriptionId parameter should be supplied so that a specific subscription can be specified if required.

In the unexpected case of an appname duplicate result, it should error and indicate to the user that they should set azureSubscriptionId to the specific subscription they want.

**Comment by iamalexmang** [comment]
Team, is there an update on this?
Azure Resource Group Deployment task supports this as does the Azure CLI (granted, the latter only supports it with some caveats for now).

**Comment by kmkumaran** [comment]
@N-Usha - Can you review the request.

**Comment by iamalexmang** [comment]
In case anyone else is wondering, the way I'm working around it is by using the Azure CLI task instead.
Effectively something along these lines:

```
          - task: AzureCLI@2          
            displayName: 'Deploy Azure Function'
            inputs:
              azureSubscription: ${{parameters.armConnection}}
              subscriptionId: '${{parameters.subscriptionId}}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription ${{parameters.subscriptionId}}
                az functionapp deployment source config-zip -g '${{parameters.resourceGroupName}}' -n $(funcAppName) --src $(Build.ArtifactStagingDirectory)/api/api-$(Build.BuildId).zip                    
```

The task above is effectively logging in the SP by using the `--allow-no-subscription` parameter and the, via the inline script, configuring the active subscription context to allow for the Function App deployment to go through.
Regretfully, this is rendering the task useless, which is why I'd appreciate an enhancement in regard to management group scoped service connections.
