### ISSUE TITLE
Matrix variables with DownloadSecureFile, InstallAppleCertificate, InstallAppleProvisioningProfile

### ISSUE THREAD

**Issue by EdwardBlair** [microsoft/azure-pipelines-tasks#10603]
```yaml
jobs:
- job: TestJob
  pool:
    vmImage: 'macos-latest'
  strategy:
    maxParallel: 1
    matrix:
      A:
        ProvisioningProfile: 'A.mobileprovision'
      B:
        ProvisioningProfile: 'B.mobileprovision'
  variables:
    AppleCertificate: 'cert.p12'
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: '$(ProvisioningProfile)'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: '$(AppleCertificate)'
```

Fails with

```
The pipeline is not valid. Job TestJob: Step DownloadSecureFile1 input secureFile references secure file $(ProvisioningProfile) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job TestJob: Step DownloadSecureFile2 input secureFile references secure file $(AppleCertificate) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

Replacing the tasks with
```yaml
  steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: $(AppleCertificate)
      certPwd: $(AppleCertificatePassword)
  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Apple provisioning profile'
    name: 'installProvisioningProfile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: $(ProvisioningProfile)
```

Fails similarly, however

```yaml
  steps:
  - bash: echo $(ProvisioningProfile)
  - bash: echo $(AppleCertificate)
```

Works fine
