### ISSUE TITLE
UseRubyVersion fails with "kernel_require.rb:54:in `require': cannot load such file -- openssl (LoadError)"

### ISSUE THREAD

**Issue by jmoody** [microsoft/azure-pipelines-tasks#10623]
*Type*: Bug

**Enter Task Name**: UseRubyVersion

## Environment

- Server - Azure Pipelines

* josmoo@microsoft.com
* https://msmobilecenter.visualstudio.com/Mobile-Center/_build?definitionId=3447&_a=summary
* https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=662122

- Agent - Hosted macOS 

```
pool:
  vmImage: 'macOS-10.14'
```

## Issue Description

The UseRubyVersion task succeeds, but the ruby that is installed in not usable.  Attempts to execute ruby or gem commands fail with:

```
Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- openssl (LoadError)
	from /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:278:in `rescue in fetch_path'
	from /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:253:in `fetch_path'
	from /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/lib/ruby/2.6.0/rubygems/source.rb:87:in `dependency_resolver_set'
```

I tried with both >= 2.6 and >= 2.5.

If I skip the UseRubyVersion task and use the pre-installed ruby, I don't encounter this error.

Here is a sample yaml file that reproduces the issue (requires a project that contains a Gemfile).

```
trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: UseRubyVersion@0
  inputs:
	    versionSpec: '>= 2.6'

- script: ruby -v
  displayName: "ruby version"

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: "install bundler and gems"
```

This will fail on the `bundle install` step.
