### ISSUE TITLE
UseRubyVersion >= 2.6 does not install the latest ruby 2.6 version

### ISSUE THREAD

**Issue by jmoody** [microsoft/azure-pipelines-tasks#10624]
*Type*: Bug

**Enter Task Name**: UseRubyVersion

## Environment

* Azure Pipelines
* josmoo@microsoft.com
* https://msmobilecenter.visualstudio.com/Mobile-Center/_build?definitionId=3447&_a=summary
* https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=662122
* Agent - Hosted macOS 

```
pool:
  vmImage: 'macOS-10.14'
```

## Issue Description

UseRubyVersion >= 2.6 installs ruby 2.6.2 and I expected to see ruby 2.6.3. 

```
pool:
  vmImage: 'macOS-10.14'
steps:

- task: UseRubyVersion@0
  inputs:
	    versionSpec: '>= 2.6'

- script: ruby -v
  displayName: "ruby version"
==>

Found tool in cache: Ruby 2.6.2 x64
[command]/usr/bin/sudo ln -sf /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/bin/ruby /usr/bin/ruby
ln: /usr/bin/ruby: Operation not permitted
Prepending PATH environment variable with directory: /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/bin
```

The pre-installed version of ruby is 2.6.3.

```
pool:
  vmImage: 'macOS-10.14'
steps:
- script: ruby -v
  displayName: "ruby version"
==>
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```
