### ISSUE TITLE
no matching key exchange method found.

### ISSUE THREAD

**Issue by zdavatz** [microsoft/azure-pipelines-tasks#10642]
I am trying to copy my build Artifacts to my Linux Server using azure-piplines and this task:
```
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'pillbox'
    sourceFolder: '$(build.artifactstagingdirectory)'
    contents: 'AmiKoWindows/bin/Release/Amiko-Installer/Amiko-Installer.msi'
    targetFolder: '/home/ftp/Amiko_Desitin_Win7.msi'
```
The SSH Copy-Job always fails. My SSH log on the receiving end says:
```
Jun 12 16:02:15 [sshd] Unable to negotiate with 137.135.130.50 port 1984: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1 [preauth]
```
I use `Ed25519` which is the most recommended public-key algorithm available [today](https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54).

any thoughts on when Azure-Pipeline-Tasks may support that? The offered key exchange methods seem a bit outdated AFAICT.

You can find the build here: https://dev.azure.com/ywesee/AmiKo_Csharp/_build/results?buildId=33

This may be related: #8818, https://github.com/MicrosoftDocs/vsts-docs/issues/3169
