### ISSUE TITLE
use variable in the SSH build task command

### ISSUE THREAD

**Issue by NicoNBW** [microsoft/azure-pipelines-tasks#10681]
Is it possible to use **Variables** when calling a command or Inline command in SSH Task?
From what I had tested it's not working. Exemple of step I would like to use:
```
steps:
- task: SSH@0
  inputs:
    sshEndpoint: endpoint
    runOptions: 'commands'
    commands: |
      docker-compose -f $DOCKERFILE pull
      docker-compose -f $DOCKERFILE up -d
  env:
    DOCKERFILE: $(File)
```

Please take a look at it. thank you
