### ISSUE TITLE
Add Apache Maven Release Plugin support

### ISSUE THREAD

**Issue by cbismuth** [microsoft/azure-pipelines-tasks#10723]
`Contributor` permission has been granted to the `Project Collection Build Service Accounts` account, but the `GenericContribute` permission still seems to be required to make the Apache Maven Release Plugin work.

Here is the Apache Maven SCM configuration over HTTPS:

```xml
    <scm>
        <url>https://dev.azure.com/tf1-data/Samples/_git/sample-java-lib</url>
        <connection>scm:git:https://tf1-data@dev.azure.com/tf1-data/Samples/_git/sample-java-lib</connection>
        <developerConnection>scm:git:https://tf1-data@dev.azure.com/tf1-data/Samples/_git/sample-java-lib</developerConnection>
        <tag>HEAD</tag>
    </scm>
```

And here is the output when trying to get it over HTTPS:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project sample-java-lib: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: 001f# service=git-receive-pack
[ERROR] remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\fdfa0603-e108-4188-89b8-eea93d2b3fa9', scope 'repository'.
[ERROR] remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\fdfa0603-e108-4188-89b8-eea93d2b3fa9', scope 'repository'.
[ERROR] fatal: unable to access 'https://tf1-data@dev.azure.com/tf1-data/Samples/_git/sample-java-lib/': The requested URL returned error: 403
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Here is the Apache Maven SCM configuration over SSH:

```xml
    <scm>
        <url>https://dev.azure.com/tf1-data/Samples/_git/sample-java-lib</url>
        <connection>scm:git:git@ssh.dev.azure.com:v3/tf1-data/Samples/sample-java-lib</connection>
        <developerConnection>scm:git:git@ssh.dev.azure.com:v3/tf1-data/Samples/sample-java-lib</developerConnection>
        <tag>HEAD</tag>
    </scm>
```

And here is the output when trying to get it over SSH:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project sample-java-lib: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] Host key verification failed.
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Here is how permissions are setup:

![image](https://user-images.githubusercontent.com/21545602/59941230-f633c200-945c-11e9-94e1-8b0838bdd85e.png)

Finally, to give you a complete overview of this issue, here is below our pipeline in the `azure-pipelines.yml` descriptor:

```yaml
name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  jdkVersionOption: '1.8'
  jdkArchitectureOption: 'x64'

jobs:
- job: Build
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'mavenSettings'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: mavenSettings
      TargetFolder: '$(Build.SourcesDirectory)'
  - checkout: self
    persistCredentials: true
    clean: true
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx128m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: false
      goals: '--settings $(Agent.TempDirectory)/mavenSettings clean test-compile'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx128m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: '--settings $(Agent.TempDirectory)/mavenSettings test'
- job: Release
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'mavenSettings'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: mavenSettings
      TargetFolder: '$(Build.SourcesDirectory)'
  - checkout: self
    persistCredentials: true
    clean: true
  - bash: 'git config user.email devops@tf1.fr && git config user.name "Azure DevOps" && git status'
  - bash: 'git checkout $(Build.SourceBranchName)'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx128m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: false
      goals: '--batch-mode --settings $(Agent.TempDirectory)/mavenSettings release:clean'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx128m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: '--batch-mode --settings $(Agent.TempDirectory)/mavenSettings release:prepare -DnextVersion=$(Date:yyyyMMdd)$(Rev:.r) -DdevelopementVersion=$(Date:yyyyMMdd)-SNAPSHOT'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx128m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: false
      goals: '--batch-mode --settings $(Agent.TempDirectory)/mavenSettings release:perform'
```

I'm ready to help with more details, thanks.

**Comment by cbismuth** [comment]
Here is the output when trying to get it over SSH:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project sample-java-lib: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] Host key verification failed.
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by cbismuth** [comment]
As far as I can see in logs, Git operations are triggered with `http.extraheader` additional switch:

```bash
##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --progress --no-recurse-submodules origin
```

I'll try to make Maven do the same.

**Comment by cbismuth** [comment]
This YAML additional bash task didn't make it:

```yaml
  - bash: 'git config --global --add http.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"'
```

**Comment by cbismuth** [comment]
The post-checkout task does clear authorization:

```
##[command]git config --unset-all http.https://tf1-data@dev.azure.com/tf1-data/Samples/_git/sample-java-lib.extraheader
```

And the checkout task in the second job is skipped, I'll try to figure out why.

**Comment by cbismuth** [comment]
I've removed the `clean: true` from the first job checkout task, and the the checkout task in the second task is not skipped.

**Comment by cbismuth** [comment]
Git operations support over HTTPS can be granted with this configuration below:

![image](https://user-images.githubusercontent.com/21545602/60689327-8ee62b00-9ebc-11e9-9f51-03b193da0809.png)

But the two Apache Maven Release Plugin commits makes the release process loop over and over.

**Comment by cbismuth** [comment]
I finally got to make it work, here is a YAML snippet below.

```yaml
name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  jdkVersionOption: 1.8
  jdkArchitectureOption: x64
  mavenOptions: -Xmx128m

jobs:
- job: Build
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: mavenSettings
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: mavenSettings
      TargetFolder: $(Build.SourcesDirectory)
  - checkout: self
    persistCredentials: true
  - task: Maven@3
    inputs:
      mavenPomFile: pom.xml
      mavenOptions: $(mavenOptions)
      javaHomeOption: JDKVersion
      jdkVersionOption: $(jdkVersionOption)
      jdkArchitectureOption: $(jdkArchitectureOption)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: --settings $(Agent.TempDirectory)/mavenSettings package
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: JaCoCo
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/**/site/jacoco/
      additionalCodeCoverageFiles: $(System.DefaultWorkingDirectory)/**/target/jacoco.exec
- job: Release
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: mavenSettings
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.TempDirectory)
        Contents: mavenSettings
        TargetFolder: $(Build.SourcesDirectory)
    - checkout: self
      persistCredentials: true
      clean: true
    - bash: git config user.email teamdatacrm@tf1.fr && git config user.name "Azure DevOps" && git status
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: $(mavenOptions)
        javaHomeOption: JDKVersion
        jdkVersionOption: $(jdkVersionOption)
        jdkArchitectureOption: $(jdkArchitectureOption)
        publishJUnitResults: false
        goals: --batch-mode --settings $(Agent.TempDirectory)/mavenSettings release:clean
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: $(mavenOptions)
        javaHomeOption: JDKVersion
        jdkVersionOption: $(jdkVersionOption)
        jdkArchitectureOption: $(jdkArchitectureOption)
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: --batch-mode --settings $(Agent.TempDirectory)/mavenSettings -DpushChanges=false -Dtag=$(Build.BuildNumber) -DreleaseVersion=$(Build.BuildNumber) -DdevelopmentVersion=1.0.0-SNAPSHOT release:prepare
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: $(mavenOptions)
        javaHomeOption: JDKVersion
        jdkVersionOption: $(jdkVersionOption)
        jdkArchitectureOption: $(jdkArchitectureOption)
        publishJUnitResults: false
        goals: --batch-mode --settings $(Agent.TempDirectory)/mavenSettings -DlocalCheckout=true release:perform
    - bash: git push origin $(Build.BuildNumber)
```
