### ISSUE TITLE
Using the BAKE command, and using the overrides to configure the helm chart. Any override that contains a ':' as the value, is truncated from that character onward.

### ISSUE THREAD

**Issue by adrianrbezzina** [microsoft/azure-pipelines-tasks#10732]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifestV0

## Environment

Azure Pipelines

## Issue Description

Using the BAKE command, and using the *overrides* to configure the helm chart. Any override that contains a ':' as the value, is truncated from that character onward.

E.g.

If the variable *AZUREAPPCONFIGURATION* contains a ':' then everything to the right of this is truncated. This makes it difficult to configure variables like connectionstrings, etc.

_Pipeline Variable:_

AZUREAPPCONFIGURATION = "Endpoint=https://settings.azconfig.io"

_Task Configuration:_
```yaml
- task: KubernetesManifest@0
  name: bake
  displayName: Bake K8s manifests from Helm chart
  inputs:
    action: bake
    releaseName: SampleForPiplines-$(Build.BuildId)
    helmChart: $(System.ArtifactsDirectory)/SampleForPiplines/helm/default
    overrides: |
      env.connectionStrings__AzureAppConfiguration:"$(AZUREAPPCONFIGURATION)"
```

Here is a link to the implementation:

https://github.com/microsoft/azure-pipelines-tasks/blob/b9fb9c8948349ebaa3ddebcc84d23388f9ba0985/Tasks/KubernetesManifestV0/src/actions/bake.ts#L38-L41

### Task logs

AZUREAPPCONFIGURATION = "Endpoint=https://settings.azconfig.io"

```
sr/local/bin/helm template /home/vsts/work/1/a/SampleForPiplines/helm/default --namespace default --set env.connectionStrings__AzureAppConfiguration="Endpoint=https
```

## Troubleshooting

N/A

### Error logs

N/A
