### ISSUE TITLE
Azure CLI failOnStandardError does not work in Azure YAML pipelines

### ISSUE THREAD

**Issue by tedsluis** [microsoft/azure-pipelines-tasks#10754]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure pipelines

- Agent - Hosted or Private: 
Both Hosted and Private agents

## Issue Description

I am using the AzureCLI task for quite sometime in Azure Devops release pipelines. Now I am moving over to Azure YAML pipelines. I noticed that "failOnStandardError" parameter does not work in a YAML pipeline (on Linux using Bash and Windows using Batch code):
```yaml
- stage: 'Test'
  jobs:
  - job: 'Test'
    pool:
      name: Build-Azure-Linux
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        failOnStandardError: false
        inlineScript: |
                echo "test exit with error."
                exit 99
```
I my opinion this Azure pipeline should not fail due to the `exit 99`, since I have add the `failOnStandardError: false` parameter.

Not only this task fails, the pipeline it self failed. I would expect that the pipeline would finish successful. 

### Task logs

Debug logging Azure Pipeline:
```
##[debug]   set
##[debug]   --subscription
##[debug]addSpnToEnvironment=true
##[debug] **** auth scheme = ServicePrincipal
##[debug]exec tool: /bin/bash
##[debug]arguments:
##[debug]   /home/vsts/agent1/_work/_temp/azureclitaskscript1561467211035.sh
##[debug]test exit with error.
##[debug]rc:99
##[debug]success:false
##[debug]task result: Failed
##[error]Script failed with error: Error: /bin/bash failed with return code: 99
##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: Error: /bin/bash failed with return code: 99
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with error: Error: /bin/bash failed with return code: 99
##[debug]which 'az'
##[debug]found: '/usr/bin/az'
##[debug]/usr/bin/az arg:  account clear
##[debug]exec tool: /usr/bin/az
##[debug]arguments:
##[debug]   account
##[debug]   clear
sr/bin/az account clear
Finishing: AzureCLI
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Test: "Script failed with error: Error: /bin/bash failed with return code: 99"

**Comment by hiyadav** [comment]
Hey @tedsluis 

**_failOnStandardError_**: this input is used for determining whether the task should fail if the script file/inline script prints data to STDERR stream.
(the below inline bash script is redirecting stdout stream to stderr stream)
 
_failOnStandardError: false_
        inlineScript: |
                echo "test exit with error." 1>&2;

The above will pass even though output was printed in STDERR stream, as _failOnStandardError: false_

But the below will not pass as _failOnStandardError: true_
_failOnStandardError: true_
        inlineScript: |
                echo "test exit with error." 1>&2;

The task uses exit code to determine if the script passed. When exit code is 0, the script execution is considered successful and for non-zero exit codes the execution is considered unsuccessful. Thus your script fails due to _exit code = 99_.

And to keep the pipeline running even after task fails, you can use
- task: AzureCLI@1
  **_continueOnError: true_**

**Comment by tedsluis** [comment]
Hi @hiyadav, 

Thanks for your reply.
You're right about the *failOnStandardError:* parameter. It does not prevent the pipeline from failing.

I tried the parameter *continueOnError: true*, but that one does not seem to have any effect. 
```yaml
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        failOnStandardError: false
        continueOnError: true
        inlineScript: |
                echo "test exit with error."
                exit 99
```
The logging and error messages are exactly the same as without this parameter. 

I would expect to have this *continueOnError:* parameter listed in the [list of parameters](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1#parameters-of-the-task) and I can find that parameter in the code of the task. Or this is a generic parameter for all Azure Devops pipeline tasks? In my Azure Devops Release pipelines this option works, but in my Azure YAML pipelines it does not work. What could be the case?
