### ISSUE TITLE
Download Pipeline Artifact from a different pipeline set to 'latest' fails if a build is in progress

### ISSUE THREAD

**Issue by kdubau** [microsoft/azure-pipelines-tasks#10766]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Download Pipeline Artifact

Version 1.1.3

## Environment
- Server - Azure Pipelines

- Agent - Doesn't matter

## Issue Description

If you use this task, to download artifacts from another build, and set it to "Latest from a branch" then is will fail if the other build definition has an in progress build for said branch.

```
- task: DownloadPipelineArtifact@1
  displayName: 'Download Pipeline Artifacts'
  inputs:
    buildType: specific
    project: ***
    pipeline: 11312
    buildVersionToDownload: latestFromBranch
    branchName: '$(SourceBranch)'
    artifactName: drop
    targetPath: '$(Directory)'
```

This causes failures because in an active repo, almost always there is some in progress build.

The task should imply download artifacts from "Latest **successfully completed**" build.

### Task logs

```2019-06-26T18:18:21.3253197Z ##[error]Artifact drop was not found for build 2802094.```

..which is because at the time, that build was in progress and didn't upload an artifact yet.
