### ISSUE TITLE
DownloadBuildArtifacts BuildNumber is not formatted number

### ISSUE THREAD

**Issue by codejnki** [microsoft/azure-pipelines-tasks#10816]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifacts@0
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadBuildArtifactsV0

## Environment
Azure Pipelines
Private: 
Ubuntu 1604    

## Issue Description

When referencing the build number output variable from the `DownloadBuildArtifacts@0` task when pointed to a `specific` build, the build number is an integer, not the build's formatted number.

Example pipeline which publishes artifact

```yaml
name: $(Date:yyyy.MM.dd)-r$(Rev:rr)

trigger:
  branches:
    include:
      - master

steps:
  - task: PublishBuildArtifacts@1
    displayName: Publish script
    inputs:
      PathtoPublish: scripts
      ArtifactName: upgrade-scripts
```
Build Number Generated: `2019.07.03-r04`

Example pipeline which downloads the artifact

```yaml
variables:
- name: poolName
  value: Our Ubuntu 1604 Agent Pool

stages:
- stage: Integration
  jobs:
    - deployment: deploy_integration
      pool:
        name: ${{ variables.poolName }}
      environment: integration
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'specific'
                project: 'Sandbox'
                pipeline: 'test-build'
                buildVersionToDownload: 'latest'
                downloadType: 'single'
                artifactName: 'upgrade-scripts'
              name: 'TEST'
            - bash: echo $(TEST.BuildNumber)
```

Expected Output: 
```
  | Starting: Bash |  
  | ============================================================================== |  
  | Task         : Bash |  
  | Description  : Run a Bash script on macOS, Linux, or Windows |  
  | Version      : 3.151.1 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash |  
  | ============================================================================== |  
  | Generating script. |  
  | Script contents: |  
  | echo 2019.07.03-r04 |  
  | ========================== Starting Command Output =========================== |  
  | in/bash --noprofile --norc /datadrive/agent_work/_temp/43a77ea1-7dcc-4ec2-bb92-982990c87c62.sh |  
  | 2019.07.03-r04 |  
  | Finishing: Bash|
```

Actual Output:
```
  | Starting: Bash |  
  | ============================================================================== |  
  | Task         : Bash |  
  | Description  : Run a Bash script on macOS, Linux, or Windows |  
  | Version      : 3.151.1 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash |  
  | ============================================================================== |  
  | Generating script. |  
  | Script contents: |  
  | echo 38442 |  
  | ========================== Starting Command Output =========================== |  
  | in/bash --noprofile --norc /datadrive/agent_work/_temp/43a77ea1-7dcc-4ec2-bb92-982990c87c62.sh |  
  | 38442 |  
  | Finishing: Bash|
```

I would expect the build number produced in the output variable to match the formatted number as defined in the original build that produced the artifact.
