### ISSUE TITLE
Pipeline variable is not working for a special case

### ISSUE THREAD

**Issue by feroz-ahmmed** [microsoft/azure-pipelines-tasks#10813]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: KubernetesManifest

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Agent - Hosted: 
    
    - Hosted Ubuntu 1604

## Issue Description
Pipeline variable is not working for providing job environment. It remains `$(Environment)` after deployment

``` yaml
jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImage)
    environment: $(Environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'charts'
              downloadPath: '$(System.ArtifactsDirectory)/charts'

          - task: KubernetesManifest@0
            displayName: bake
            name: bake
            inputs:
              action: bake
              helmChart: '$(System.ArtifactsDirectory)/charts'
              releaseName: $(Release_Name)
              overrides: |
                image.tag:$(Build.BuildId)
                buildID:"1"
               
          - task: KubernetesManifest@0
            displayName: deploy
            name: deploy
            inputs:
              kubernetesServiceConnection: $(AKS_Namespace_SC)
              action: deploy
              namespace: $(k8sNamespace)
              manifests: $(bake.manifestsBundle)
              containers: |
                $(containerRegistry)/$(ServiceNameOnContainer):$(Build.BuildId)
```

![](https://i.imgur.com/HIz7eF6.png)

**Comment by kmkumaran** [comment]
@feroz-ahmmed - The support to expand $(environment) kind of variables within the deployment job has been added recently. This support will be available in upcoming deployment. @chshrikh - to keep this thread posted about deployment roll-out status.

**Comment by chshrikh** [comment]
@feroz-ahmmed - where are you defining variable - Environment ?

**Comment by chshrikh** [comment]
we are in process to roll out the feature for supporting the environment name as variable, one need to define the environment name variable at global level in yaml file, you yaml may look like this -

`variables:
 Environment: 'Prod-Environment'
jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImage)
    environment: $(Environment)
    strategy:
      runOnce:........`

I will keep you posted once feature is rolled out

**Comment by feroz-ahmmed** [comment]
I have defined a variable group from the Library section of DevOps. Also referenced the variable group in my yaml. I can confirm other variables other than `Environment` are working as expected.

**Comment by feroz-ahmmed** [comment]
@chshrikh , One thing that I also needed to tell you. I am referencing the variable group from the main yaml of my pipeline but I am using `$(Environment)` inside a template which was referenced from main yaml. For example -

service-ci.yaml
``` yaml
variables:
  - group: My Environment Variables

stages:
- stage: Stage
  jobs:
  - template: template.yaml
```

template.yaml
``` yaml
jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImage)
    environment: $(Environment)
```

**Comment by chshrikh** [comment]
@feroz-ahmmed  this should work fine

**Comment by feroz-ahmmed** [comment]
hey @chshrikh , this problem is solved for me today. However I ran into another problem with `KubernetesManifest` task for `deploy` command. I am not sure if this error has anything to do with this fix.
`##[error]No manifest file(s) matching %s was found.`
Until today my pipeline was deploying to aks just fine.

**Comment by chshrikh** [comment]
@feroz-ahmmed thanks for confirmation, @nishubansal could you please check KubernetesManifest task issue

**Comment by feroz-ahmmed** [comment]
Here's my deployment job yaml - 
``` yaml
jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImage)
    environment: $(DeployEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'charts'
              downloadPath: '$(System.ArtifactsDirectory)/charts'

          - task: KubernetesManifest@0
            displayName: bake
            name: bake
            inputs:
              action: bake
              helmChart: '$(System.ArtifactsDirectory)/charts'
              releaseName: $(Release_Name)
              overrideFiles: |
                $(System.ArtifactsDirectory)/charts/values.$(DeployEnvironmentIdentifier).yaml
              overrides: |
                image.tag:$(Build.BuildId)
                buildID:"1"
               
          - task: KubernetesManifest@0
            displayName: deploy
            name: deploy
            inputs:
              kubernetesServiceConnection: $(AKS_Namespace_SC)
              action: deploy
              namespace: $(k8sNamespace)
              manifests: $(bake.manifestsBundle)
              containers: |
                $(containerRegistry)/$(ServiceNameOnContainer):$(Build.BuildId)
```
