### ISSUE TITLE
Docker Compose on Hosted Ubuntu Agent access denied in mount volume

### ISSUE THREAD

**Issue by flmarins** [microsoft/azure-pipelines-tasks#10822]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question, Bug

**Enter Task Name**: Run a Docker Compose command

list here (V# not needed):  DockerComposeV0

## Environment
- Server - Azure Pipelines
- Agent - Hosted: 
    - Hosted Ubuntu 1604

## Issue Description

One of my container has a mounted bind volume to export the results of a script, however when trying to save the file it receives access denied. 
Is there any way to properly mount a volume on a hosted agent and publish it files as artifacts

my docker compose file: 
```
version: '3'

services: 

  testdb:
      build: './sqldocker'
      ports: 
        - "1400:1433"
      container_name: 'sqltest'

  app:
      environment: 
        - ConnectionStrings:EPOS_SQLDB=Server=testdb,1433;Initial Catalog=RefCaisseDb;Integrated Security=False;Persist Security Info=False;User ID=sa;Password=Passw0rd;Connection Timeout=30;;MultipleActiveResultSets=False;
        - ASPNETCORE_ENVIRONMENT=SecurityCheck
      build: './Elior.ReferentielCaisse'
      ports:
      - "443:443"
      - "8080:80"
      depends_on:
        - testdb
  zap:
    image: owasp/zap2docker-weekly
    command: zap-api-scan.py -t http://app/swagger/v1/swagger.json -f openapi -r exportreport.html
    volumes: 
      - ./:/zap/wrk/
    container_name: 'owaspzapcheck'
    depends_on:
      - app
      - testdb
```

![image](https://user-images.githubusercontent.com/13965067/60627250-bfab5f00-9ded-11e9-9344-8e8eb22d8ebf.png)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Error from my bash script task outputing container log
```

2019-07-03 21:47:50,201 I/O error(13): Permission denied
Traceback (most recent call last):
  File "/zap/zap-api-scan.py", line 512, in main
    write_report(base_dir + report_html, zap.core.htmlreport())
  File "/zap/zap_common.py", line 501, in write_report
    with open(file_path, mode='wb') as f:
IOError: [Errno 13] Permission denied: '/zap/wrk/exportreport.html'
```
