### ISSUE TITLE
DotNetCoreCLI - Pack missing doc & wierd usage

### ISSUE THREAD

**Issue by Herve-M** [microsoft/azure-pipelines-tasks#10831]
## Note  
This could be related to issue #9789

## Required Information
**Question, Feature?**  
*Type*: Feature  / Cleaning
**Enter Task Name**: DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines    
- Agent - Hosted

## Issue Description
DotNetCoreCLI@2 provide a documented way for packing, who is _I think_ mispelling / hard to get into / easier to get lost.

Like: 
```yaml
- task: DotNetCoreCLI@2
  displayName: 'Pack - Manager'
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/src/CM/CM.csproj'
    includesymbols: true
    includesource: true
    nobuild: true
    verbosityPack: 'normal'
    outputDir: '$(Build.StagingDirectory)'
```
`projects` won't be used during `pack` cmd and will be override by `searchPatternPack` who is _required_ but has a default. And it seem to have one alias [`packagesToPack`](https://github.com/microsoft/azure-pipelines-tasks/blob/94206c8e95afe6a50ca671869157d0c19c144cd4/Tasks/DotNetCoreCLIV2/task.json#L328) who is not set or documented.

**Comment by Trolldemorted** [comment]
I just lost several hours because of this bug. Could you emit a warning if `projects` is used in combination with `pack` and link to this issue @sachinma ?

**Comment by Trolldemorted** [comment]
Was this fixed in the meanwhile?

**Comment by Trolldemorted** [comment]
Was this fixed in the meanwhile?

**Comment by Trolldemorted** [comment]
Was this fixed in the meanwhile?

**Comment by dferretti** [comment]
Also I think there are differences between `projects` and `searchPatternPack` - I am able to pass a multiline string to `projects` for a restore or build command, but not pack. For example I am trying to build a reusable template to restore/build/pack like this:
```yaml
parameters:
- name: projects
  type: string
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: ${{ parameters.projects }} # other options omitted
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: ${{ parameters.projects }}
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    searchPatternPack: ${{ parameters.projects }}
```
however, if I try to use this template with a multiline string, only restore and build succeed:
```yaml
variables:
  projects: |
    some/project/A.csproj
    other/project/B.csproj
- template: my-template
  parameters:
    projects: $(projects)
```
Those 2 projects will be found by the restore and build tasks and work fine, but the pack task seems to use different logic for discovering projects and requires a `;` separated string instead of newline. So it will fail saying `No files matched the search pattern`
