### ISSUE TITLE
Environment variables in DockerCompose task

### ISSUE THREAD

**Issue by scabana** [microsoft/azure-pipelines-tasks#10836]
## Required Information

*Type*: Feature

**Enter Task Name**: DockerCompose

## Issue Description

When using the DockerCompose task, environement variables (or build pipeline variables) are not accessible in the .yml files, for example: 

##### Task 1: bash

```bash
echo "##vso[task.setvariable variable=SomeCustomBuildPipelineVariable]SomeValue"
```

##### Task 2: DockerCompose

```yml
version: '2.2'

services:
  someService:
    environment:
      - SomeCustomBuildPipelineVariable
```

$SomeCustomBuildPipelineVariable is empty in the someService container.

This seems to have been resolved in the Docker task in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/8640/commits/1aa9766d3a45f7428da149d75ec5acb9903693a2
