### ISSUE TITLE
Relative file path specified in cache key should get resolved against $(System.DefaultWorkingDirectory)

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-tasks#10858]
## Required Information

**Question, Bug, or Feature?**  Bug

**Enter Task Name**: Cache

## Environment

Hosted

## Issue Description

The `Cache` task `key` input expects a newline-delimited list of file names or strings. For file paths the hash of the file is calculated. However, currently, file paths must be absolute, otherwise the task treats the "file name" as a string.

### Current (incorrect) behavior

```yaml
steps:
- task: Cache@0
  inputs:
    key: azure-pipelines.yml
    path: somefolder
```

This incorrectly results in "azure-pipelines.yml" being treated like a regular string

```
Information, Using the following fingerprint argument (azure-pipelines.yml) as a string value.
```

### Expected (correct) behavior

Providing the full path to the file works:

```yaml
steps:
- task: Cache@0
  inputs:
    key: $(Build.SourcesDirectory)/azure-pipelines.yml
    path: somefolder
```

```
Information, Using the following fingerprint argument (/mnt/a/1/s/azure-pipelines.yml) as a file.
```

If the provided file path is not absolute, it should be resolved against `$(System.DefaultWorkingDirectory)`.
