### ISSUE TITLE
Azure Powershell Task V4 logs warnings for missing localization strings

### ISSUE THREAD

**Issue by joostvanwollingen** [microsoft/azure-pipelines-tasks#10854]
## Required Information

*Type*: Bug
**Enter Task Name**: Azure Powershell V4  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV4

## Environment
- Server: Azure Pipelines 
- Agent: Hosted Ubuntu 1604

## Issue Description
When running any Azure Powershell V4 task there are 2 warnings in the logs, about missing localisation strings for `GeneratingScript` and `JS_FormattedCommand`. These warnings clutter the log. 

The keys seem to be missing from the [resources files](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzurePowerShellV4/Strings/resources.resjson/):  For example for the [`en-US` locale](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzurePowerShellV4/Strings/resources.resjson/en-US/resources.resjson).

Usages of these strings occur (at least) on:
- https://github.com/microsoft/azure-pipelines-tasks/blob/15367c4a0ce66815f551a12cd9c74e076f6d3aea/Tasks/AzurePowerShellV4/azurepowershell.ts#L58
- https://github.com/microsoft/azure-pipelines-tasks/blob/15367c4a0ce66815f551a12cd9c74e076f6d3aea/Tasks/AzurePowerShellV4/azurepowershell.ts#L71

### Task logs
```
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 4.0.13
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
==============================================================================
##[warning]Can\'t find loc string for key: GeneratingScript
GeneratingScript
##[warning]Can\'t find loc string for key: JS_FormattedCommand
JS_FormattedCommand . '/home/vsts/work/1/s/my_script.ps1' 
```

![image](https://user-images.githubusercontent.com/2583184/60818045-27222f80-a19d-11e9-99f2-cf7bf44d438f.png)

**Comment by rajatagrawal-dev** [comment]
@joostvanwollingen  I don't see the issue happening with the latest version of the task (v4.154.4). Please check if you have this latest version. Please let us know if you have the latest version are still seeing these warnings.
Meanwhile we will see if there are any gaps here.

**Comment by joostvanwollingen** [comment]
Still see this occurring on a hosted agent running task v4.153.3. Not sure how I can run with v4.154.4?

```
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 4.154.3
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613749)
==============================================================================
##[warning]Can\'t find loc string for key: GeneratingScript
GeneratingScript
##[warning]Can\'t find loc string for key: JS_FormattedCommand
```

Task as defined in the YAML:

```
- task: AzurePowerShell@4
  displayName: "Validate user input"
  inputs:
    azureSubscription: 'MySubscriptionName'
    ScriptType: 'FilePath'
    ScriptPath: 'scripts/validate_input_parameters.ps1'
    ScriptArguments: '-projectName "$(PROJECT_NAME)" -processType $(PROCESS_TYPE) -adGroup $(AD_GROUP) -accessToken $(System.AccessToken)'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
```
