### ISSUE TITLE
Kubernetes Manifest task can't deploy baked files

### ISSUE THREAD

**Issue by waterfoul** [microsoft/azure-pipelines-tasks#10869]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest

## Environment
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  fishandrichardson, IT Dev Internal Projects, ApplicationInsightsInjestor, 5556

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description

If you use bake, then deploy with the manifests set to "$(bake.manifestsBundle)" you get the error below

### Task logs

[logs_5560.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3377528/logs_5560.zip)

### Error logs

##[error]No manifest file(s) matching %s was found.

**Comment by ds-ms** [comment]
Are you still facing this issue?

**Comment by benc-uk** [comment]
Same issue here. I'm getting `##[error]No manifest file(s) matching %s was found.`

My tasks are
```
        - task: KubernetesManifest@0
          displayName: Bake manifests from Helm chart
          inputs:
            action: bake
            renderType: helm2
            releaseName: '${{ parameters.envName }}-$(Build.BuildId)'
            helmChart: kubernetes/helm/smilr
            overrides: |
              registryPrefix:$(acr-name).azurecr.io/
              dataApi.imageTag:$(image-tag)
              frontend.imageTag:$(image-tag)
              mongo.usePersistence:false

        - task: KubernetesManifest@0
          displayName: Deploy manifests
          inputs:
            kubernetesServiceConnection: $(aks-connection)
            namespace: ${{ parameters.envName }}
            manifests: $(bake.manifestsBundle)
```

**Comment by benc-uk** [comment]
I checked the variables and `bake.manifestsBundle` is never available or set 

When I switch on debug logging I see
```
2019-07-17T15:18:24.7355821Z ##[debug]agent.tempDirectory=/home/vsts/work/_temp
2019-07-17T15:18:24.7356579Z ##[debug]set manifestsBundle=/home/vsts/work/_temp/baked-template-9f32b95b-10e7-4f2f-8420-5499275ddb2b.yaml
2019-07-17T15:18:24.7382783Z ##[debug]Processed: ##vso[task.setvariable variable=manifestsBundle;issecret=false;]/home/vsts/work/_temp/baked-template-9f32b95b-10e7-4f2f-8420-5499275ddb2b.yaml
```

Is this going to be fixed, because the task simply doesn't work right now

**Comment by ds-ms** [comment]
Setting `manifestsBundle` variable suffices here because it is [an output variable](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesManifestV0/task.json#L309)

We're currently investigating the root cause of the issue, from the logs it looks like the `bake.manifestsBundle` didn't get extracted. 

@benc-uk What's the agent version? 

@ericsciple Is there any known issue with the agent?

**Comment by benc-uk** [comment]
I tried this
```
        - task: KubernetesManifest@0
          displayName: Deploy manifests
          inputs:
            kubernetesServiceConnection: $(aks-connection)
            namespace: ${{ parameters.envName }}
            manifests: $(manifestsBundle)
```

It got the same error :(

Current agent version: **2.154.1**
Task version **0.154.5**

**Comment by benc-uk** [comment]
I've found a work around. I ran `printenv` in my pipeline and spotted was being `KUBERNETESMANIFEST_MANIFESTSBUNDLE` set as an environmental variable. So to use it in the KubernetesManifest task I set/copy it to another variable called `manifests` and use that,

It's a cludge but seems to work

```
        - bash: echo "##vso[task.setvariable variable=manifests]$KUBERNETESMANIFEST_MANIFESTSBUNDLE"

        - task: KubernetesManifest@0
          displayName: Deploy manifests
          inputs:
            kubernetesServiceConnection: $(aks-connection)
            namespace: ${{ parameters.envName }}
            manifests: $(manifests)
```

**Comment by ds-ms** [comment]
I just noticed, your yaml is missing `name: bake` parameter in the task usage. 
```yaml
        - task: KubernetesManifest@0
          displayName: Bake manifests from Helm chart
          name: 'bake' # <== This parameter adds reference
          inputs:
            action: bake
            renderType: helm2
            releaseName: '${{ parameters.envName }}-$(Build.BuildId)'
            helmChart: kubernetes/helm/smilr
            overrides: |
              registryPrefix:$(acr-name).azurecr.io/
              dataApi.imageTag:$(image-tag)
              frontend.imageTag:$(image-tag)
              mongo.usePersistence:false
```
