### ISSUE TITLE
preferTriggeringPipeline in DownloadPipelineArtifactV2 is not working with Build Triggers

### ISSUE THREAD

**Issue by olandese** [microsoft/azure-pipelines-tasks#10892]
I have created 3 yml pipelines, **A**, **B** and **C**.

Pipelines **A** en **B** only publish an artifact.
Pipeline **C** downloads the artifacts coming from the **master branch** of **A** and **B** using twice DownloadPipelineArtifactV2 . In this steps I have added the **preferTriggeringPipeline** property and set it to **true**.

Like: 

```
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'dbcb95d9-1f61-4ec9-b3a6-5c6f2fdb5158'
          definition: '20'
          preferTriggeringPipeline: true
          buildVersionToDownload: 'latestFromBranch'
          branchName: 'refs/heads/master'
          targetPath: '$(Pipeline.Workspace)'
```

In the pipeline settings of **C** I have set up the Build Trigger to be triggered from the builds of **A (master)** en **B (master)** and also **B** for **feature branches (feature/*)**

After triggering a build for pipeline **B** for a **feature branch** I was expecting that the run of pipeline **C** the _**artifact of the feature branch**_ of pipeline **B** was downloaded.
But pipeline **C** still downloads the master build from **B**.

**Comment by bryanmacfarlane** [comment]
Note that the template asked for task name to route to the right team.  Manually routing

**Comment by fadnavistanmay** [comment]
Hi @olandese - Where are you seeing this issue, in the build or release? Did you add triggers on your release - based on the artifact?

**Comment by fadnavistanmay** [comment]
Are you adding branch filters here - 
![image](https://user-images.githubusercontent.com/43892780/61568982-22316b80-aa3a-11e9-981e-d459eb3482e0.png)

or, selecting the branch while setting up the artifact in the release? 
![image](https://user-images.githubusercontent.com/43892780/61569008-38d7c280-aa3a-11e9-9b9d-70dabff32599.png)

**Comment by MisinformedDNA** [comment]
@compuguru Your fix might be fine for classic pipelines, but there is still a gap for YAML builds. For example:

Let's say we have two pipelines. One with stages "StageA" and "StageB" and the other with "StageBOnly". "StageB" and "StageBOnly" both have all their jobs in a template "TemplateB".

NOTE: In my case, StageA is the build stage and StageB/StageBOnly are the deploy stages, with the latter allowing us to deploy without building again.

Let's also assume that "StageA" publishes the artifact we need.

If we run the first pipeline, StageB can download the artifact with 

```yaml
- download: current
```

However, if we run the second pipeline, "StageBOnly" needs to download the artifact from the latest master (and we move to the full syntax):

```yaml
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'XXXX'
    definition: 'YYY'
    preferTriggeringPipeline: true
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    artifactName: $(artifact)
    targetPath: '$(Pipeline.Workspace)'
```

In order to meet both cases, either 1) StageA needs to have "triggered" StageB or 2) we need new `buildType` value like `currentOrSpecific` or `currentPreferred` or 3) a new property called `preferCurrentPipeline`.

Thoughts?

**Comment by fadnavistanmay** [comment]
@willsmythe - for visibility

**Comment by olandese** [comment]
Hello @fadnavistanmay fadnavistanmay, 

sorry for my late answer, I was on holiday.

I am doing everything in YAML pipelines. 

I setup the build triggers like this: 

![image](https://user-images.githubusercontent.com/1708128/63094633-45800580-bf69-11e9-99f6-a17806ae132b.png)

To get there, open the YAML Pipeline -> Edit -> Click the 3 dots on upper right -> Triggers.

I will explain the situation again:

I have 3 repos: 

- repo1
- repo2
- repo3

**Repo3** has 2 completition triggers: **from Repo1 and Repo2** (both from master)
Both Repo1 and Repo2 are publishing artifacts.

The YAML of **repo3** has the following step:

```
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'a95e6385-0c29-429a-b82d-cd77390c5903'
    definition: '25'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'specific'
    pipelineId: '236'
    artifactName: 'repo1-20190815.7'
    targetPath: '$(Pipeline.Workspace)'
```
**As you see in the task setup I am asking to download an artifact from repo1 (pipeline 25) from a specific build (pipeline 236)** with artifact name repo1-20190815.7
I have also setup **_specificBuildWithTriggering: true_**.

I expect the following: 

- When a **repo1** build is successfully done, repo3 will be triggered to start. **THIS WORKS**.
- When a **repo2** build is successfully done, repo3 will be triggered to start. **THIS WORKS**.
- When I manually run a **repo3** build the artifact from the specified build (repo1-20190815.7) will be downloaded. **THIS WORKS**
- Because I setup **specificBuildWithTriggering: true**, I am expecting when a new **repo1** build runs, then repo3 will download the **latest** artifact from repo1. **THIS IS NOT SO**
- Because I setup **specificBuildWithTriggering: true**, I am expecting when a new **repo2** build runs, then repo3 will download the **latest** artifact from repo1. **THIS IS NOT SO**

From the [Download Pipeline artifact source](https://github.com/microsoft/azure-pipelines-tasks/blob/7bbed64d8c3058256065bb0e4dfbf6d0e2b70c34/Tasks/DownloadPipelineArtifactV2/task.json#L75) there's this description:

> If checked, this build task will try to download artifacts from the triggering build. If there is no triggering build from the specified pipeline, it will download artifacts from the build specified in the options below.
