### ISSUE TITLE
[DotNetCoreCLIV2] Can't define runtimeIdentifier to use for restore

### ISSUE THREAD

**Issue by kvpt** [microsoft/azure-pipelines-tasks#10896]
## Required Information

**Bug, or Feature ?**  

**Task Name**: DotNetCoreCLIV2

## Environment
AzureDevOps
Agent : Hosted Windows 2019

## Issue Description
I need to specify the RuntimeIdentifier used by the restore command.
In Build or Publish command it's possible to pass it by using the parameter "Arguments".
But this parameter is not used by restore command (Indicated in the documentation).
So I tried to use the custom command as a workaround but it doesn't handle Azure Artefact authentication like the restore command does so i'm blocked.
So the "Restore" command need to be able to handle the "Arguments" parameter.

**Comment by hiyadav** [comment]
Assigned to @infin8x for considering the bug for restore command in DotNetCoreCLIV2 task.

**Comment by jmyersmsft** [comment]
We are currently building a new strategy for authentication to Azure Artifacts from Azure Pipelines. There will be a set of tasks that just configure authentication, allowing you to call tools like `dotnet` directly from any part of the build, including the various script tasks.

We do not intend to add new packaging features to the existing all-in-one tasks at this time, but if you wish to contribute, we will consider small, targeted pull requests

As a workaround, if you're using a dotnet SDK with NuGet 5.x (see the [NuGet 5.0 release notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-rtm)), you can use [artifacts-credprovider with an environment variable](https://github.com/microsoft/artifacts-credprovider#environment-variables) to set up authentication for an arbitrary script command. Use the `$(System.AccessToken)` build variable to get the password. For pipelines built from the designer UI, you need to go into the phase settings and check "Allow scripts to access OAuth token". For pipelines described in YAML, you should be able to use a block like the following:

```yaml
- powershell: dotnet restore -r win-x64
    env:
        - VSS_NUGET_URI_PREFIXES: https://myazuredevopsorg.pkgs.visualstudio.com/;https://pkgs.dev.azure.com/myazuredevopsorg/
        - VSS_NUGET_ACCESSTOKEN: $(System.AccessToken)
```
