### ISSUE TITLE
Cache task is slow and unreliable

### ISSUE THREAD

**Issue by wichert** [microsoft/azure-pipelines-tasks#10935]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta@0

## Environment
- Server: Azure Pipelines
- Agent: Hosted macOS-10.14
    
## Issue Description

The cache unfortunately appears to be slow and unreliable. I just tried it with a project that uses a fair bit of node_modules. On the first test:

* With empty cache, installing all packages using yarn took 54 seconds
* Saving the cache took 106 seconds
* Loading the cache in the next build failed after 121 seconds with `[error]One or more errors occurred. (Service Unavailable) (Service Unavailable)` after downloading 359Mb of of 497Mb (72%)

On a second test:

* Loading the cache succeeded in 54 seconds 
* Yarn install time with loaded cache: 18 seconds

Which means the overall build time is still 16 seconds longer than without a cache.

### Task logs
```
##[section]Starting: Cache Yarn packages
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Information, Using the following fingerprint argument (yarn) as a string value.
Information, Using the following fingerprint argument (Darwin) as a string value.
Information, Using the following fingerprint argument (/Users/vsts/agent/2.154.3/work/1/s/yarn.lock) as a file.
Information, Using the following fingerprint argument (/Users/vsts/agent/2.154.3/work/1/s/crypho.core/yarn.lock) as a string value.
Information, Using the following fingerprint argument (/Users/vsts/agent/2.154.3/work/1/s/crypho.core/xmpp.js/yarn.lock) as a string value.
Information, Generated fingerprint: BAB1179CEC7C8D8463877AD0B78C37BE3C65AA9B4145C2D55E60DF463EE811B200
Information, Getting a pipeline cache artifact with the following fingerprint: BAB1179CEC7C8D8463877AD0B78C37BE3C65AA9B4145C2D55E60DF463EE811B200
Information, There is a cache hit.
Manifest ID is: 2491EB794C0F22AE55A93EA7DC512F7ED56FF030F0BB539D9FDFA6D4CE53084302
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 2443ef72-699d-4368-b62b-c83b27983069
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 0.0 MB out of 497.5 MB (0%).
Information, Downloaded 2.4 MB out of 497.5 MB (0%).
Information, Downloaded 20.8 MB out of 497.5 MB (4%).
Information, Downloaded 35.2 MB out of 497.5 MB (7%).
Information, Downloaded 58.3 MB out of 497.5 MB (12%).
Information, Downloaded 131.3 MB out of 497.5 MB (26%).
Information, Downloaded 244.7 MB out of 497.5 MB (49%).
Information, Downloaded 249.7 MB out of 497.5 MB (50%).
Information, Downloaded 254.8 MB out of 497.5 MB (51%).
Information, Downloaded 315.3 MB out of 497.5 MB (63%).
Information, Downloaded 317.3 MB out of 497.5 MB (64%).
Information, Downloaded 354.5 MB out of 497.5 MB (71%).
Information, Downloaded 354.5 MB out of 497.5 MB (71%).
Information, Downloaded 359.7 MB out of 497.5 MB (72%).
##[error]One or more errors occurred. (Service Unavailable) (Service Unavailable)
##[section]Finishing: Cache Yarn packages
```

**Comment by johnterickson** [comment]
Thanks for reporting! The moment of your cache retrieval coincided with load on that scale unit quadrupling in load.  Our automatic scaleout trigger, but had some lag. We'll see what tweaks we can make to make this better.

Can you confirm you are not seeing this consistently?

**Comment by johnterickson** [comment]
Possibly the same as https://github.com/microsoft/azure-pipelines-tasks/issues/10917

**Comment by wichert** [comment]
I haven't seen the _Serve Unavailable_ error anymore. The performance seems to vary a bit. From what I gather you are currently uploading files separately? If so uploading a tarball with fast compression might help a lot when you have lots of small files.

**Comment by johnterickson** [comment]
👍 https://github.com/microsoft/azure-pipelines-tasks/issues/10925 and

**Comment by johnterickson** [comment]
@wichert Given the tarball is in #10925 and the service issue was remedied in #10917 , is this issue in a good place to close?

**Comment by wichert** [comment]
Yes, I think so. If I hit this again we can always revisit.

**Comment by douglasjunior** [comment]
For me, `yarn install` without cache takes `30s` on average.

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1512341/163871708-24252381-86ff-40cb-89bb-e251baea2090.png">

```yml
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: yarn
        displayName: Yarn install

      - script: yarn lint
        displayName: Run linting
```

And with Cache takes `30s` + `30s` on average.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1512341/163871945-92bc1f76-8d3b-4a88-8492-f955a369b95c.png">

```yml
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

# ....

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn
        displayName: Yarn install

      - script: yarn lint
        displayName: Run linting
```

I followed the [cache documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsyarn). Am I doing something wrong?
