### ISSUE TITLE
Azure CLI task does not support line breaks with \

### ISSUE THREAD

**Issue by LoboHacks** [microsoft/azure-pipelines-tasks#10946]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI  

## Environment
- Server - Azure Pipelines
- Agent - Hosted or Private: Hosted
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description

The AzureCLI Task does not support in-command line breaks with \ .
Broken:
```
  - task: AzureCLI@1
    displayName: Create Resource Group test-rg
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: inlineScript
      inlineScript: |
        az group create \
          --name test-rg \
          --location westeurope
```
Works:
```
  - task: AzureCLI@1
    displayName: Create Resource Group test-rg
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: inlineScript
      inlineScript: |
        az group create --name test-rg --location westeurope
```
