### ISSUE TITLE
AddBuildTag - fails when there're special characters in the build tag

### ISSUE THREAD

**Issue by nkolev92** [microsoft/azure-pipelines-tasks#10972]
We set build tags with the name of the author and branch to improve the discoverability. 

https://github.com/NuGet/NuGet.Client/blob/99ba88baac37e1c2b912f64a004bce6b5bc58db5/build/vsts_build.yaml#L56-L57

This doesn't work when the author's name has special characters: 

For example: `ö`

Note that the content is escaped:

```yaml
  - task: PowerShell@1
    displayName: "Add Build Tags"
    inputs:
      scriptType: "inlineScript"
      inlineScript: |
        Write-Host "##vso[build.addbuildtag]${env:BUILD_SOURCEVERSIONAUTHOR}"
        Write-Host "##vso[build.addbuildtag]${env:BUILD_SOURCEBRANCHNAME}"
```
