### ISSUE TITLE
"workingDirectory" parameter seems to be ignored for DotNetCoreCLI@2  "dotnet restore" task

### ISSUE THREAD

**Issue by stevewillcock** [microsoft/azure-pipelines-tasks#10996]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines
    
## Issue Description

Running build (for example) with the following configuration specifying a workingDirectory works as expected:

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: 'src'
```

but running restore with the following similar configuration fails to find a project / solution file

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    workingDirectory: 'src'
```
This fails with:

```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

It seems as if the restore task is ignoring the workingDirectory parameter

### Task logs

```
[command]"C:\Program Files\dotnet\dotnet.exe" restore --configfile d:\a\1\Nuget\tempNuGet_31.config --verbosity Detailed
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
##[error]Packages failed to restore
##[section]Finishing: DotNetCoreCLI

```

### Error logs

```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by hiyadav** [comment]
Hey @stevewillcock 

You're correct, the restore, pack and push commands don't honour `workingDirectory` input. Which is causing this issue, you can however use `projects` input to give paths to projects or wildcards.

This seems to be in accordance to this issue, hence referencing: #9789

**Comment by stevewillcock** [comment]
Ah, thanks for the clarification. It would be good to clear up the documentation around this (unless I missed something already in the docs). If adding / rationalising these features takes a while then documentation would prevent wasted time wondering why things didn't work :)

Thanks!

**Comment by ggirard07** [comment]
I am currently seeing the same behavior for `build` command.
The value of `workingDirectory` is being ignored and default back to the value of `System.DefaultWorkingDirectory`.

This is critical with the introduction of multi-checkout where we have sources in multiple path and `projects` needs to remain a generic wildcard (like `**/*`) in order to go through the list of checked-out repositories.  
The only solution I currently see is to move away from the `DotNetCoreCLI` task and rely only on some PowerShell script with the native .Net Core CLI...

**Comment by MarkKharitonov** [comment]
Is there any ETA on this?

**Comment by NickDarvey** [comment]
...?

**Comment by bishal-pdMSFT** [comment]
@ggirard07 if I understand correctly, you want to build all projects (`**/*.csproj`) in the sub-tree of a particular directory. For that you can use an appropriate minimatch pattern which will match all csproj files under a directory. I believe something like "**/<directory-name>/**/*.csproj"

**Comment by MarkKharitonov** [comment]
The minimatch pattern is not adequate when order matters. Which in case of projects can be resolved if they belong to the same solution (in which case - why build projects and not the solution)?
However, in my case I need to build solutions and there is no way to specify order with minimatch. Using it produces wrong order, actually.

**Comment by bishal-pdMSFT** [comment]
That's interesting @MarkKharitonov. I am afraid this scenario is something the task might not been thought for.
Can you not have a number of tasks one after another in right order? Or do you have huge number of solutions?

**Comment by MarkKharitonov** [comment]
Just 6. I am using a YAML template which is given an array of solutions and it iterates over them invoking the task for each solution individually. While doing it we need to pass workingDirectory, which is not respected. So, we modify the path given to the **projects** parameter. Which in turn fails if the path starts with a dot. But this is another issue - https://github.com/microsoft/azure-pipelines-tasks/issues/12717

**Comment by ggirard07** [comment]
@bishal-pdMSFT The step is part of a template we use for every repo checked-out with [the multi-repo checkout principle](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops).
In that case we cannot hard-code path relative to `System.DefaultWorkingDirectory` because we need each step in the template to be contextualized to the current repo root, which is `$(Agent.BuildDirectory)/{repo-alias}`.
The easiest solution in that case is to pass the current repo path as a parameter to the template, then use this parameter either to populate the `workspaceDirectory` anywhere it is supported, which apparently is not the case of the `DotNetCoreCLI` task.

**Comment by MarkKharitonov** [comment]
Is it that hard to fix?

**Comment by mihai-cindea** [comment]
Bump.
Hit this on a multi repository pipeline for `pack`. Any plans to fix it any time soon?

**Comment by vany0114** [comment]
Here is my workaround if it can help anyone, while this issue gets fixed. I'm using a variable which contains the relative path to the project/solution I want to build, e.g. `src/service1`, `src/service2`
 
```
- task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        projects: '$(codeBase)/**/*.csproj'
        includeNuGetOrg: true

- task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        command: test
        projects: '$(codeBase)/**/*tests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
```

**Comment by NickDarvey** [comment]
quack

**Comment by adamsmithkld** [comment]
For what it's worth, this burned me too.

**Comment by kmadof** [comment]
If it is not possible to fix it can we at least get a warning that we use parameter which is not supported for specific commands?

**Comment by sofcal** [comment]
Is there any update on this ticket? If the workingDirectory is not going to be honoured, then the documentation available should at least be updated to specify: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

`
workingDirectoryWorking Directory | Current working directory where the script is run. Empty is the root of the repo (build) or artifacts (release), which is $(System.DefaultWorkingDirectory)
`

**Comment by mortenbock** [comment]
Seems to also be ignore when running custom commands.

I'm trying to run the swagger cli tool, and it needs to be in the correct folder to work correctly.

**Comment by moody78** [comment]
Try adding publishWebProjects: false. Otherwise it is looking for a web project and building that instead of the path you're trying to configure

**Comment by danbirle** [comment]
> That's interesting @MarkKharitonov. I am afraid this scenario is something the task might not been thought for. Can you not have a number of tasks one after another in right order? Or do you have huge number of solutions?

another scenario :/ i'm running a ps1 script for a node project. can that work in any way with `projects` ?

**Comment by ChristoWolf** [comment]
Issue is still relevant.

**Comment by MisinformedDNA** [comment]
If you specify `workingDirectory` and `projects`, `workingDirectory` is ignored.

```
- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: build
    projects: src/**/*.csproj
    arguments: '-p:Version=$(Build.BuildNumber) --configuration $(BuildConfiguration) --output $(Build.BinariesDirectory)'
    workingDirectory: ${{ parameters.workingDirectory }}
```

My scenario was creating a pipeline template that assumes a specific and consistent directory structure.

**Comment by robmaas** [comment]
Yawn, yet another task where the `custom` option actually works a lot better than the build-in commands..

The following works for `restore`, `build`, `test` and will automatically restore/build/test any projects in `$(some-directory)` as you would expect (and how the cli behaves).

```yaml
- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: custom
    custom: 'restore'
    workingDirectory: $(some-directory)
```

**Comment by xania** [comment]
publish command is also suffering, please help

```yaml
  - task: DotNetCoreCLI@2
    displayName: "Publish project"
    inputs:
      command: "publish"
      workingDirectory: $(Build.SourcesDirectory)/identity
      arguments: "-c $(buildConfiguration)"
      outputDir: $(Build.ArtifactStagingDirectory)
```
