### ISSUE TITLE
Cache miss on first run under a new branch_name?

### ISSUE THREAD

**Issue by mafonso** [microsoft/azure-pipelines-tasks#11005]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question (Bug?)

**Enter Task Name**: CacheBeta@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
        
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

Hosted Ubuntu 1604

## Issue Description

Invoking Cache task as:

```
        - task: CacheBeta@0
          inputs:
            key: |
              $(Build.SourcesDirectory)/Gemfile.lock
            path: $(BUNDLE_PATH)
            cacheHitVar: CACHE_RESTORED
          displayName: Cache bundle
```

On every new branch the first run will always be a cache miss (for the same fingerprint).
This means that subsequent runs for the same branch will benefit from the cache restore, as expected.

However if we let's say branch the very same code to a new branch name and trigger a new run, even if the fingerprint is the same, the first run will be a cache miss. 

Steps to reproduce:

- push a branch to trigger a build and let it either have a cache hit or cache miss, depending.
- push some change to that same branch outside the `key` scope. (e.g. add a newline to some  file) and observe the cache will bit a hit.
- branch to a new branch from the same code base as the previous step, and make another change (add or remove another newline) and push the new branch.
- the first run on this branch will be a cache miss. (expecting it to be a hit since the fingerprint is the same)

Is this the intended behaviour? Is there a way to cache across any run in the project?
