### ISSUE TITLE
DotNetCoreInstaller doesn't work properly if installationPath contains other versions of .NET Core

### ISSUE THREAD

**Issue by max-lobanov** [microsoft/azure-pipelines-tasks#11004]
## Required Information

**Type:**  Bug
**Task:** DotNetCoreInstaller

## Environment
- Azure Pipelines
- Hosted agent

## Issue Description
The task doesn't switch dotnet version if `installationPath` points to the directory with pre-cached net core versions.

## Repro steps
```
steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 2.2.104'
  inputs:
    version: 2.2.104
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.1.502'
  inputs:
    version: 2.1.502
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
- script: |
   dotnet --version
  displayName: 'Show dotnet version'
```
This script will show version `2.2.104` instead of expected `2.1.502`.

## Details
The first step downloads and caches version to `$(Agent.ToolsDirectory)/dotnet`.
The second step downloads and caches version to the same folder.
It produces the following folder structure:
```
/Users/vsts/hostedtoolcache/dotnet
├── LICENSE.txt
├── ThirdPartyNotices.txt
├── dotnet
├── host
│   └── fxr
├── sdk
|   ├── 2.1.502
|   ├── 2.1.502.complete
│   ├── 2.2.104
│   ├── 2.2.104.complete
│   └── NuGetFallbackFolder
└── shared
├── Microsoft.AspNetCore.All
├── Microsoft.AspNetCore.App
└── Microsoft.NETCore.App
```

Issue comes from [this line](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts#L33). Task adds `installationPath` (`/Users/vsts/hostedtoolcache/dotnet`) to `PATH`. So `dotnet` uses the latest version of sdk from this folder.

### Expected bahavior
Task should switch .NET Core version correctly if we point to the folder with pre-cached packages.

### Our scenario
We need to pre-cache a bunch of .NET Core versions on image and then switch between them. For now the task doesn't work for us because if we set `installationPath` to our directory with a few .NET Core versions, the highest will be used always

### Error logs

No errors in console
