### ISSUE TITLE
NuGetCommand task does not respect allowPackageConflicts flag

### ISSUE THREAD

**Issue by TheBlueSky** [microsoft/azure-pipelines-tasks#11017]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: NuGetCommandV2

## Environment
Azure Pipelines

## Issue Description

I have the following `azure-pipelines.yml` file:

```yaml
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: './src/TheBlueSky.DotNet.Tools.SwiftHash.csproj'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet connection for dotnet-hash'
    allowPackageConflicts: true
```

Whenever the build is triggered and the version number is not changed; e.g., modifying the ReadMe file, the build fails because there is an already published NuGet package with this version, although I set `allowPackageConflicts` to true.

### Error logs

`The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (A package with ID 'TheBlueSky.DotNet.Tools.SwiftHash' and version '1.0.1' already exists and cannot be modified.).`

**Comment by magleaso** [comment]
Are you using this task to publish to an Azure DevOps Feed?

**Comment by TheBlueSky** [comment]
No, I'm publishing to NuGet.org

**Comment by magleaso** [comment]
Can I see your full logs with system.debug set to true?

**Comment by TheBlueSky** [comment]
Where do I set system.debug? Is it by creating a variable named `system.debug`?

**Comment by magleaso** [comment]
Yep!

**Comment by TheBlueSky** [comment]
@magleaso, here are the logs from the build.

[log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3473733/7.txt)

**Comment by magleaso** [comment]
This parameter is only usable for internal feeds. For external sources like NuGet.org, the task uses vstsnugetpush.exe which does not support this parameter. On our side, we will update the task's yaml documentation to make this clear, and add a warning message to the task output. We are working on new auth tasks now that will enable this scenario per #10857

**Comment by TheBlueSky** [comment]
Thanks for clarifying. I have 2 questions:

1. Any idea about the approximate time when the work to enable #10857 is ready?
1. Is there a workaround that I can use in the meantime?

**Comment by magleaso** [comment]
It should be quite soon. We started rolling it out this week. 

For a workaround, NuGet recently added support for this flag to the official client. You can try using the NuGet tool installer to retrieve a supported NuGet version (the -SkipDuplicate flag is available in >=5.1), then use the NuGet custom task to run your command with the flag. I'm not sure whether auth will work in this scenario. If auth doesn't work, then the only thing to do is wait for the new auth task.

**Comment by TheBlueSky** [comment]
All right, thanks a lot.

**Comment by TheBlueSky** [comment]
I tried the new NuGetAuthenticate task but wasn't able to make it work (https://github.com/microsoft/azure-pipelines-tasks/issues/10857#issuecomment-526940179).

So, I decided to use nuget.exe directly; i.e., `nuget push MyProject.*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $(nuget.apikey) -SkipDuplicate`, but that also failed with `File does not exist (MyProject.*.nupkg)` error.

Where is the *.nupkg file located and how to specify it without the need to mention the version number?

**Comment by magleaso** [comment]
I can't tell you that, it depends on where you put the nupkg. You will need to specify a specific version by filename

**Comment by magleaso** [comment]
Edit: looks like you found a solution on the other thread. Sorry for the initial confusion

**Comment by TheBlueSky** [comment]
@magleaso; no worries, also I should've updated this issue to mention I found the solution.

As a summary, neither `NuGetCommand` nor `NugetAuthenticate` will help in a case like mine and there is no plan to make them support my scenario.

As an alternative, I used NuGet command line tool:

```yaml
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
- script: nuget push $(Build.ArtifactStagingDirectory)\$(projectName).*.nupkg -Source $(nugetSource) -ApiKey $(nuget.apikey) -SkipDuplicate -NoSymbols
  displayName: 'Push to NuGet.org'
```

Note that due to a bug in NuGet command line tool, `-NoSymbols` is necessary to prevent the tool from trying to find and  push the symbols package.
