### ISSUE TITLE
Pipeline Caching -  Cache Task fails with "No Files Found" 

### ISSUE THREAD

**Issue by stefangordon** [microsoft/azure-pipelines-tasks#11045]
Cache Task was working well for a day, then started failing the build with "no files found"

I have retained a public build here where you can see the task on linux and windows:
https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=3513

![image](https://user-images.githubusercontent.com/4087345/62257674-69fdae80-b3bb-11e9-9aae-50de9fadf760.png)

**Comment by lukka** [comment]
same behavior for me [here](https://dev.azure.com/CppBuild/CppBuildTasks/_build/results?buildId=753&view=results), on win/macos/linux hosted agents

**Comment by PhucNgo1711** [comment]
I'm running into the same issue too. On all Windows, Linux, and macOS platforms.
https://dev.azure.com/PhucNgo1711/CaPTk/_build/results?buildId=390

**Comment by tymtam2** [comment]
I'm running into the same issue too. It never worked for me.

Build output
```
Starting: Cache NuGet packages
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `nuget | packages.lock.json`...
##[error]No files found.
Finishing: Cache NuGet packages
```

My configuration
```
variables:
  NUGET_PACKAGES: '$(Pipeline.Workspace)/.nuget/packages'

steps:
- task: CacheBeta@0
  displayName: 'Cache NuGet packages'
  inputs:
    key: 'nuget | packages.lock.json'
    path: '$(NUGET_PACKAGES)'
  continueOnError: true

```
