### ISSUE TITLE
CopyFilesOverSSH fails to get host from service connection

### ISSUE THREAD

**Issue by wichert** [microsoft/azure-pipelines-tasks#11059]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFilesOverSSH  

## Environment
- Server - Azure Pipelines
- Account name: Crypho AS
- Project name: Crypho
- Build definition name: Desktop release
- Agent: Hosted Ubuntu 16.04

## Issue Description
We have a fairly basic upload tasks:

```yaml
      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: desktop-upload-to-website
          sourceFolder: $(System.DefaultWorkingDirectory)/dist
          contents: '*.dmg'
          targetFolder: ~/website/en/downloads/desktop
          cleanTargetFolder: false
          overwrite: false
        displayName: Upload dist image
```

This take always fails with an error:

```
Starting: Upload dist image
==============================================================================
Task         : Copy files over SSH
Description  : Copy files or build artifacts to a remote machine over SSH
Version      : 0.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh
==============================================================================
##[error]Error: Endpoint data parameter 40b35072-4594-444d-a2b2-076bab5f4425 not present: host
Finishing: Upload dist image
```

This feels like a naming mismatch. If I look at the endpoint definition using the `az` cli it looks like this:

```yaml
  {
    "administratorsGroup": null,
    "authorization": {
      "parameters": {
        "username": "crypho"
      },
      "scheme": "UsernamePassword"
    },
    "createdBy": { },
    "data": {
      "hostName": "our-hostname,
      "portNumber": "22",
      "privateKey": "….."
    },
    "description": null,
    "groupScopeId": null,
    "id": "40b35072-4594-444d-a2b2-076bab5f4425",
    "isReady": true,
    "isShared": false,
    "name": "desktop-upload-to-website",
    "operationStatus": null,
    "owner": "Library",
    "readersGroup": null,
    "serviceEndpointProjectReferences": null,
    "type": "ssh",
    "url": "ssh://our-hostname"
  }
```

Notice how the hostname is stored under `data.hostName`. The [task implementation](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesOverSSHV0/copyfilesoverssh.ts#L110) is trying to read a different key:

```typescript
const hostname: string = tl.getEndpointDataParameter(sshEndpoint, 'host', false);
```

I suspect that this `host` versus `hostName` inconsistency is triggering this error.
