### ISSUE TITLE
Request file transform with regex replace

### ISSUE THREAD

**Issue by tehho** [microsoft/azure-pipelines-tasks#11075]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: File Transform

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: General pipeline with yaml pipeline
- Agent - Hosted or Private: Any

## Issue Description
Whould like a File transform with regex replace.
Right now we are using #{(\w+)} as a target for our variables in yaml for kubernetes.
The option to only use xml or json is a little limited.

## Example
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper-kube-aspnetcore
  labels:
    app.kubernetes.io/name: helper-kube-aspnetcore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helper-kube-aspnetcore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helper-kube-aspnetcore
    spec:
      containers:
      - name: helper-kube-aspnetcore
        image: #{DockerRepo}.azurecr.io/helper/aspnetcore:#{DockerTag}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: #{PORT}
```

### Task logs

404 format not found.
No but no logs since not supported.
