### ISSUE TITLE
Area PipelineCaching: reading from cache with `trigger: tags:` or equivalent?

### ISSUE THREAD

**Issue by aryairani** [microsoft/azure-pipelines-tasks#11074]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
I think that I'm getting cache misses because scopes are more restrictive than I want.  Is there a way I can write a cache in one git-tagged commit, and read it from a subsequent, different git-tagged commit?

**Enter Task Name**: CacheBeta

## Environment
- Server - Azure Pipelines
  - account: arya.irani@gmail.com
  - team project name: unison-build
  - build definition name: aryairani.unison
  - build number: 13, 14

- Agent - Hosted
  - Ubuntu 1604; macOS High Sierra

## Issue Description

My task builds 3.5gb of dependencies that I would like to cache between builds.  I have the pipeline set to trigger and create a new Github Release whenever a new tag of the form `release/*` is pushed:
```yaml
trigger:
  tags:
    include:
    - release/*
```
and I have the cache keyed to the build settings:
```yaml
- task: CacheBeta@0
# https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/
  inputs:
    path: $(Build.SourcesDirectory)/.stack-root
    key: |
      $(Agent.OS)
      $(Build.SourcesDirectory)/stack.yaml
      $(Build.SourcesDirectory)/parser-typechecker/unison-parser-typechecker.cabal
      $(Build.SourcesDirectory)/yaks/haskeline/haskeline.cabal
      $(Build.SourcesDirectory)/yaks/easytest/easytest.cabal
```

So when I pushed my next tag and got a cache miss, I was disappointed to realize (or at least believe) that my previously cached content was scoped to the release tag (`refs/tags/release/azure11`):
```
Total Content: 3,616.5 MB
Information, Creating a pipeline cache artifact with the following fingerprint: `Linux|YnTkbcx6XSG5w8QKnjsxURlWjg91XNCoHe0OQfxlha0=|YoewAmsrDBw/pljm4YjHwNqV/T8XgY/OG+QN8UiCySI=|jiOTJL7zJgxLuyzdsCC7iJED5GYWOYGqicTS7n/7f8Y=|xG6NWZKsMyMlH4PpmBhXoIjpgZ6ulcLhTyXEnh44h00=`
Information, Cache item created.
Information, Saved under the following scope: 2;075e5862-c0ba-4c75-ac29-34f9d3ccc1f3;refs/tags/release/azure11;aryairani/unison
Saved item.
```
and thus [as I understand it](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#cache-isolation-and-security), I couldn't help but get a cache miss when I pushed the next tag (`refs/tags/release/azure12`), `buildId=15`, even though the key fingerprint matches, as intended:
```
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `Linux|YnTkbcx6XSG5w8QKnjsxURlWjg91XNCoHe0OQfxlha0=|YoewAmsrDBw/pljm4YjHwNqV/T8XgY/OG+QN8UiCySI=|jiOTJL7zJgxLuyzdsCC7iJED5GYWOYGqicTS7n/7f8Y=|xG6NWZKsMyMlH4PpmBhXoIjpgZ6ulcLhTyXEnh44h00=`
Information, There is a cache miss.
```

Is there a way I can trigger only for `release/` tags, but have a cache that follows me from one tag to the next?
