### ISSUE TITLE
DownloadPipelineArtifact does not expand all variables

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#11095]
**Bug**  
*Type*: YAML variables

**Enter Task Name**: DownloadPipelineArtifact 

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted: 
    
## Issue Description

Given the following YAML, the first download step in `jobB` fails due to the variable not being expanded, but the second one expands and succeeds. I would expect them both to succeed.

```yaml
variables:
  system.debug: true
jobs:
  - job: jobA
    variables:
      artifactName: qwe
    steps:
      - publish: $(System.DefaultWorkingDirectory)
        artifact: $(artifactName)
  - job: jobB
    dependsOn: jobA
    variables:
      artifactName: $[dependencies.jobA.outputs['outputVars.artifactName']]
    steps:
      - download: current
        artifact: $[dependencies.jobA.outputs['outputVars.artifactName']]
        continueOnError: true
      - download: current
        artifact: $(artifactName)
        continueOnError: true
```
![image](https://user-images.githubusercontent.com/1784452/62740856-8c687b00-b9fe-11e9-9e47-28b92eded548.png)

### Task logs

[logs_208.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3483875/logs_208.zip)

### Error logs
```
##[error]Artifact $[dependencies.jobA.outputs[&#39;outputVars.artifactName&#39;]] was not found for build 208.
```
