### ISSUE TITLE
Task: DotNetCoreCLI@2 nuget pack unexpectedly issuing multiple commands

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/azure-pipelines-tasks#11103]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCli@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

> Account name: innovian
> Team project name: Platform
> Build definition name: Utilities.ResourceNameBuilder
> Build number: 20190810.5

- Agent - Hosted or Private:  Hosted

Agent queue name: Hosted Agent

## Issue Description
Task display name: "Nuget package pack"

Here is the YAML I'm using:
```
- task: DotNetCoreCLI@2
  displayName: "Nuget package pack"
  inputs:
    command: 'pack'
    packagesToPack: '**/Utilities.ResourceNameBuilder.csproj'
    includesymbols: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'

- task: DotNetCoreCLI@2
  displayName: 'Nuget package push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'xyz'
```

I'm aiming to include the symbols and only publish the one project (specifically stated since I also have a unit test project in the solution).

I'm showing that there are two pushes performed: one for the packed target and one for the symbols. If I run this via the NuGetCommand@2, my YAML looks like the following:

```
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Utilities.ResourceNameBuilder.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    includeSymbols: true
```

And it includes only the single push as I'd expect and runs without an error. Running as-is with the .NET Core CLI yields an error as seen in the logs below.

### Task logs

> [section]Starting: Nuget package push
> ==============================================================================
> Task         : .NET Core
> Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
> Version      : 2.155.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
> ==============================================================================
> [command]C:\windows\system32\chcp.com 65001
> Active code page: 65001
> SYSTEMVSSCONNECTION exists true
> SYSTEMVSSCONNECTION exists true
> SYSTEMVSSCONNECTION exists true
> Saving NuGet.config to a temporary config file.
> Saving NuGet.config to a temporary config file.
> [command]"C:\Program Files\dotnet\dotnet.exe" nuget push d:\a\1\a\Utilities.ResourceNameBuilder.1.0.0-CI-20190810-234741.nupkg --source https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v3/index.json --api-key VSTS
> info : Pushing Utilities.ResourceNameBuilder.1.0.0-CI-20190810-234741.nupkg to 'https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/'...
> info :   PUT https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/
> info :   Accepted https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/ 1049ms
> info : Your package was pushed.
> [command]"C:\Program Files\dotnet\dotnet.exe" nuget push d:\a\1\a\Utilities.ResourceNameBuilder.1.0.0-CI-20190810-234741.symbols.nupkg --source https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v3/index.json --api-key VSTS
> info : Pushing Utilities.ResourceNameBuilder.1.0.0-CI-20190810-234741.symbols.nupkg to 'https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/'...
> info :   PUT https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/
> info :   Conflict https://pkgs.dev.azure.com/innovian/_packaging/xyz/nuget/v2/ 219ms
> error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'Utilities.ResourceNameBuilder 1.0.0-CI-20190810-234741'. (DevOps Activity ID: A5D45BB8-133C-4368-B2B8-B7B68D04DF0E)).
> [error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
> [error]Packages failed to publish
> [section]Finishing: Nuget package push

Removed hashes at line starts to keep them from being interpreted as Github markup.
