### ISSUE TITLE
Pipeline Caching: intermittent internal errors

### ISSUE THREAD

**Issue by ncw** [microsoft/azure-pipelines-tasks#11128]
## Required Information

*Type*: Bug
**Task Name**: `CacheBeta@0`

## Environment
- Server - Azure Pipelines

Example build: https://dev.azure.com/rclone/rclone/_build/results?buildId=139

![image](https://user-images.githubusercontent.com/536803/63089369-8e2ac500-bf4f-11e9-8912-c17c61371f0a.png)

## Issue Description

The `CacheBeta@` task gives intermittent errors

```
  - task: CacheBeta@0
    inputs:
      key: go-build-cache | "$(Agent.JobName)"
      path: $(GOCACHE)
    continueOnError: true
    displayName: Cache go build
    condition: ne( variables['GOCACHE'], '' )
```

Full [azure-pipelines.yml](https://github.com/rclone/rclone/blob/712f7e38f73d237e2554aa98cd5d0bfdb396d4c9/azure-pipelines.yml#L117-L123)

### Error logs

```
##[section]Starting: Cache go build
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `go-build-cache | "Job go1.10"`...
Resolved to `go-build-cache|"Job go1.10"`.
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `go-build-cache|"Job go1.10"`
##[error]TF400898: An Internal Error Occurred. Activity Id: 8d9509a5-d387-4702-bce6-46fa96be112b.
##[section]Finishing: Cache go build
```
