### ISSUE TITLE
Service Connection with Management Group Scope 

### ISSUE THREAD

**Issue by jreed14** [microsoft/azure-pipelines-tasks#11151]
When using an Azure DevOps Service Connection that is scoped for a Management Group I'm not able to use the Azure CLI task. It appears part of the out of box task (excluding any commands or scripts specified) on the Azure CLI step is to:

1. Set Active Cloud
2. az login with service principal associated with the service connection
3. Perform an az account set to a subscription

Step #3 fails when service connections is scoped for a management group because there is no subscription specified.  It runs:

> az account set --subscription <undefined>

The whole pipeline fails before even getting to specified code or script in the CLI task.

**Comment by bishal-pdMSFT** [comment]
@jreed14 Management group scope service connection is not supported for Azure CLI task currently, and I am not aware of any immediate plan to add this support. But this is something we should do.

@pulkitaggarwl to add this to backlog and plan.

**Comment by bhicks329** [comment]
@bishal-pdMSFT - What would be the recommended alternative approach until this is hopefully implemented?

**Comment by bishal-pdMSFT** [comment]
@bhicks329 no good alternative other than using a Subscription/Resource group scoped service connection.
Another option would be to use bash/powershell task and login using a script.

**Comment by Lutando** [comment]
This is a pretty big problem to have with no workaround.

So I have only one option. Use multiple service connections that are scoped to the subscription. This is quite a loss of agility for what management groups provide big orgs

**Comment by thepaulmacca** [comment]
I've just come across this page due to me noticing that this doesn't work for ARM service connections scoped to a Management Group either (unless i'm missing something, but it works if i scope it to an individual subscription)

I'm currently trying to learn how Management Groups work to improve governance across Dev/Prod subscriptions, and this is a bit of an issue when we're being advised to use Management Groups to improve governance, but then they don't work in scenarios like this

**Comment by andrenelnz** [comment]
I've also confirmed this is still an issue. Has this issue been added to the backlog since February and if so could you please provide an update on the status here? Having this feature would mean a lot to us as well.

**Comment by bishal-pdMSFT** [comment]
@pulkitaggarwl can you please take a look here?

**Comment by bishal-pdMSFT** [comment]
By the way if you specify a valid subscriptionId input then it should just work even if service connection is that management group scope.
Currently the task only works in subscription context and hence it is a required input.

**Comment by jsco2t** [comment]
> By the way if you specify a valid subscriptionId input then it should just work even if service connection is that management group scope.
> Currently the task only works in subscription context and hence it is a required input.

Hi @bishal-pdMSFT I tried passing a `subscriptionId` on input to the AzureCLI pipeline task - but I am still not seeing any impact.

Here is what I am trying:
```
- task: AzureCLI@2
    displayName: Create Resource Group
      inputs:
        azureSubscription: "$(AZServiceConnection)"
        subscriptionId: '$(SubscriptionId)' <----------------- tried this
        subscriptionName: '$(SubscriptionId)' <------------------ and this
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "[INFO] Creating something in Azure!"
```

Is there something I am doing wrong here? Or maybe I'm not following your work-around?

**Comment by cysecops** [comment]
FYI the azure resource group deployment (ARM Template) supports management groups is you use version 3 (preview). Still waiting on CLI support

**Comment by bishal-pdMSFT** [comment]
Thanks to @mbrancato a [PR ](https://github.com/microsoft/azure-pipelines-tasks/pull/12516) is out for adding this support. Please see if the PR is sufficient to handle this issue.

**Comment by iamalexmang** [comment]
@bishal-pdMSFT is there an update to this?
What is the current possible way (preview or otherwise) to use a management group scoped service connection in an Azure CLI task? PR !12516 is currently merged to master. Based on the commits for this PR, the `--allow-no-subscription` parameter is used, but I'm failing on understanding which is the right input parameter to properly log in.

**Comment by iamalexmang** [comment]
In case anyone else is wondering, the way I'm working around it is by using the Azure CLI task instead.
Effectively something along these lines:

```
          - task: AzureCLI@2          
            displayName: 'Deploy Azure Function'
            inputs:
              azureSubscription: ${{parameters.armConnection}}
              subscriptionId: '${{parameters.subscriptionId}}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription ${{parameters.subscriptionId}}
                az functionapp deployment source config-zip -g '${{parameters.resourceGroupName}}' -n $(funcAppName) --src $(Build.ArtifactStagingDirectory)/api/api-$(Build.BuildId).zip                    
```

The task above is effectively logging in the SP by using the `--allow-no-subscription` parameter and the, via the inline script, configuring the active subscription context to allow for the Function App deployment to go through.
Regretfully, this is rendering the task useless, which is why I'd appreciate an enhancement in regard to management group scoped service connections.
