### ISSUE TITLE
 Azure File copy WinRM cannot complete the operation. 

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#11158]
Hi,

Not sure what I am doing wrong...

2019-08-13T14:47:17.3599547Z ##[debug]System.Management.Automation.RuntimeException: The remote session query failed for xxx.xxx.xxx.xxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet.  ---> System.InvalidOperationException: <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859046" Machine="fv-az130"><f:Message>WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. </f:Message></f:WSManFault>
2019-08-13T14:47:17.3613064Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2019-08-13T14:47:17.3625879Z ##[debug]   --- End of inner exception stack trace ---
2019-08-13T14:47:17.3680330Z ##[error]The remote session query failed for xxx.xxxx.xxxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. 
2

**Comment by chshrikh** [comment]
@greengumby could see if you select the option of "Enable Copy Prerequisites" option in task and re-run it

![image](https://user-images.githubusercontent.com/11972852/63401612-94102280-c3f5-11e9-9312-f39cc36b2313.png)

**Comment by greengumby** [comment]
Hi,

Yes, Enable Copy Prerequisites is already selected.

Thanks

[cid:image002.jpg@01D55818.D7E2EBD0]
Jeremy Martin | Software Development Manager
T +61 8 9211 8675 | M +61 448 811 535
Level 6, 130 Stirling Street, Perth WA 6000 | www.snowdengroup.com
FOLLOW SNOWDEN ON LINKEDIN<https://www.linkedin.com/company/snowden?trk=nmp_rec_act_company_photo>

**Comment by greengumby** [comment]
Any more information on this or alternatives? Currently I cannot copy my artifacts to my Azure VM's for testing.

Thanks

**Comment by coin8086** [comment]
I have the same issue and here's my yaml snippet:

```yaml
    - task: AzureFileCopy@3
      inputs:
        SourcePath: '$(Pipeline.Workspace)/SomeArtifact'
        azureSubscription: $(Subscription)
        resourceGroup: $(ResourceGroup)
        storage: $(StorageAccount)
        Destination: 'AzureVMs'
        ResourceFilteringMethod: machineNames
        MachineNames: $(TargetHosts)
        vmsAdminUserName: $(TargetHosts.AdminUserName)
        vmsAdminPassword: $(TargetHosts.AdminPassword)
        TargetPath: $(TargetHosts.Path)
        CleanTargetBeforeCopy: true
        enableCopyPrerequisites: true
      displayName: 'Deploy to $(TargetHosts)'
```

And here's the error for that:

```
The remote session query failed for xxx.xxx.xxx.xxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. 
```

Please help!
