### ISSUE TITLE
Image tag is missing during docker build step if containerRegistry input is not specified.

### ISSUE THREAD

**Issue by jikuma** [microsoft/azure-pipelines-tasks#11179]
If we do not specify container registry input docker build command skips repository input to. I want to build a local docker image for tests and hence I do not need to specify containerRegistry.

**task input**

```
  - task: Docker@2
    displayName: build
    inputs:
      repository: terrapintest
      command: build
      Dockerfile: '$(Build.SourcesDirectory)/tests/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
       $(Build.BuildNumber)
       latest
```

The docker command which gets created during execution is 

```
[command]/usr/bin/docker build -f /data/agent/_work/38/s/tests/Dockerfile --label com.visualstudio.devdiv.image.system.teamfoundationcollectionuri=https://devdiv.visualstudio.com/ --label com.visualstudio.devdiv.image.system.teamproject=DevDiv --label com.visualstudio.devdiv.image.build.repository.name=Terrapin --label com.visualstudio.devdiv.image.build.sourceversion=ac1838a57e1f4408818f5bf746d9dba3e44c3736 --label com.visualstudio.devdiv.image.build.repository.uri=https://devdiv.visualstudio.com/DevDiv/_git/Terrapin --label com.visualstudio.devdiv.image.build.sourcebranchname=merge --label com.visualstudio.devdiv.image.build.definitionname=Terrapin - Validation --label com.visualstudio.devdiv.image.build.buildnumber=20190821.1 --label com.visualstudio.devdiv.image.build.builduri=vstfs:///Build/Build/2964724 /data/agent/_work/38/s
Sending build context to Docker daemon  4.543MB
```

You can see that -t input is missing from the command.
