### ISSUE TITLE
Pipeline Caching - Cache beta returns cache miss in second run for cached maven repository

### ISSUE THREAD

**Issue by codingforus** [microsoft/azure-pipelines-tasks#11171]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Question

**Enter Task Name**: CacheBeta

## Environment
- Server - Azure Pipelines - Multi-stage
- Agent - Hosted agent, windows latest

### Hosted agent (windows-latest) doesn't restore cache of first run

Due to long build times because of downloading dependencies in every run in a multi-staged pipeline with a Maven task by the Hosted agent (windows-latest) I've added a CacheBeta0 task before the Maven task. The first run I'm getting a 'cache miss' returned in the logging of CacheBeta which is fine. In the second run, same pipeline, I get a cache miss as well.

I've noticed a difference between the two runs. In the first run (run 68) I can see a different fingerprint than the second run (run 69).

Resolved to `maven|CEEJK/V73bJrjkEbHrGyeK9+......................... >> build run 68

Resolved to `maven|Faj/wAFWKoDiKvbSHA7y0S................... >> build run 69

**Screenshot of second run (run 69)**

![image](https://user-images.githubusercontent.com/54352485/63417644-f707b680-c401-11e9-8d47-27d9221470d0.png)

Why do I get a cache miss, even in the second run?

### azure-build-template.yml (partially provided)

```
jobs:
- job: BuildApplication
  variables:
    MAVEN_CACHE_FOLDER: '$(Pipeline.Workspace)/.m2/repository'
    MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  pool: 
    vmImage: 'windows-latest'
  
  steps:

  - task: CacheBeta@0
    inputs:
      key: maven | **/pom.xml
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo
  
  - task: Maven@3
    displayName: 'Maven pom.xml'
    inputs:
      mavenPomFile: '${{ parameters.Layers }}/${{ parameters.Service }}/pom.xml'
      goals: 'clean package'
      options: '-s "${{ parameters.Layers }}/${{ parameters.Service }}/target/settings.xml" -e -DskipTests'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenOptions: '$(MAVEN_OPTS)'
      mavenAuthenticateFeed: true
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

```
