### ISSUE TITLE
If you choose select-xamarin-sdk.sh 6_0_0 in macOS-latest please make sure to install additionally DotNetCore >2.2.104

### ISSUE THREAD

**Issue by Jurabek** [microsoft/azure-pipelines-tasks#11198]
Currently, if you select `Mono 6.0.0` on `macOS-10.14` image your Xamarin.iOS builds are failing, because the latest image used `DotNetCore 2.2.104` by default which is not compatible with `Mono 6.0.0` 

in my case, these two tasks are solved my issue 
```yaml
- task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.301'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.301'
 ...
- task: XamariniOS@2
```
