### ISSUE TITLE
 KubernetesManifest bake not correctly processing override values

### ISSUE THREAD

**Issue by nralbers** [microsoft/azure-pipelines-tasks#11212]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: KubernetesManifest@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: bpsordina/Server Monitoring/ remedyforce-lookup-api/#20190826.1,#20190826.2

## Issue Description

The bake manifest action does not appear to be using the override values when generating a manifest file from the helm template. Running the helm template command locally and supplying the command line parameters generated by the build task does.

Buildserver command line from logs:
```
/usr/local/bin/helm template /home/vsts/work/1/s/helmchart --namespace default --set 'image.repository=ordinamonitoring.azurecr.io/remedyforce-lookup-api' --set 'image.tag=v1.0.12'
```
Resulting manifest is still on the defaults (downloaded using Publish):
```
spec:
      containers:
        - name: remedyforce-lookup-api
          image: "remedyforce-lookup-api:latest"
```
When running this locally:
```
helm template helmchart --namespace default --set 'image.repository=ordinamonitoring.azurecr.io/remedyforce-lookup-api' --set 'image.tag=v1.0.12'
```
I get the correct output.
```
    spec:
      containers:
        - name: remedyforce-lookup-api
          image: "ordinamonitoring.azurecr.io/remedyforce-lookup-api:v1.0.12"
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
