### ISSUE TITLE
NuGetCommand@2 push doesn't work with public Azure Artifact feeds

### ISSUE THREAD

**Issue by ctyar** [microsoft/azure-pipelines-tasks#11258]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommand@2

## Environment
- Server - Azure Pipelines or TFS on-premises?
   Azure Pipelines: https://dev.azure.com/ctyar/pingct/_build/results?buildId=48&view=results

- Agent - Hosted or Private: 
Hosted

## Issue Description
In branch `ci-test` I have a deployment task as follow:
```
- task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
              publishVstsFeed: 'kaya'
```
This task is working with a normal Azure Artifacts feed but fails with a public feed.

Successful build: https://dev.azure.com/ctyar/pingct/_build/results?buildId=49&view=results
Failing build: https://dev.azure.com/ctyar/pingct/_build/results?buildId=48&view=results

### Task logs
[logs_48.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3563818/logs_48.zip)

### Error logs
```
"The nuget command failed with exit code(1) and error(Unable to load the service index for source https://ctyar.pkgs.visualstudio.com/_packaging/github/nuget/v3/index.json. Response status code does not indicate success: 404 (Not Found - The feed with ID 'github' doesn't exist. 
```
