### ISSUE TITLE
Azure DevOps Cannot Build Basic React App

### ISSUE THREAD

**Issue by tsujp** [microsoft/azure-pipelines-tasks#11264]
Entering this information will route you directly to the right team and expedite traction.

**Bug**  
`Cannot find file './components/App' in './src'.`

**Enter Task Name**:
```yaml
trigger:
  branches:
    include:
      - master

stages:
- stage: build
  displayName: build
  jobs:
    - job: appbuild
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: 'npm install'
        workingDirectory: '$(Build.SourcesDirectory)'
        displayName: 'npm install'
      - script: 'npm run build'
        workingDirectory: '$(Build.SourcesDirectory)'
        displayName: 'npm run build'
```

## Environment
Hosted Azure Pipelines.

## Issue Description
I can build this app without problem locally and on other platforms, but on Azure it fails

```
> frontend@0.1.0 build /home/vsts/work/1/s
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/index.tsx
Cannot find file './components/App' in './src'.
```
