### ISSUE TITLE
GitHubRelease task with multiple artifacts across matrix

### ISSUE THREAD

**Issue by reitermarkus** [microsoft/azure-pipelines-tasks#11260]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: GithubRelease

## Environment

- Server: Azure Pipelines
- Agent: Hosted

## Issue Description

I'm trying to create a release with multiple artifacts for different platforms. Now if i use the `create` action it only works for the first artifact. If I use `edit`, I'm not sure how I am supposed to set the tag name to the same as it would be with `auto`. Obviously setting it in a previous step with

```
echo "##vso[task.setvariable variable=tag;isOutput=true]${tag}"
```

doesn't work since it is expanded before runtime.

Is there a way to do this? What is the reason the `edit` action cannot also automatically detect the tag?

**Comment by reitermarkus** [comment]
I didn't know `isOutput=true` changes the variable name to `stepName.variableName`. It's working fine without it:


```yaml
steps:
  - bash: echo "##vso[task.setvariable variable=TAG]${BUILD_SOURCEBRANCH##refs/tags/}"
    displayName: Set TAG variable
    condition: startswith(variables['Build.SourceBranch'], 'refs/tags/')
  - task: GithubRelease@0
    displayName: Create GitHub Release
    inputs:
      githubConnection: reitermarkus
      assets: $(Build.ArtifactStagingDirectory)/*.tar.gz
      assetUploadMode: replace
      action: edit
      tag: $(TAG)
```

My second question remains, however: What is the reason (if any) the `edit` action can/should not automatically detect the tag?
