### ISSUE TITLE
ShellScriptV2 cwd not working

### ISSUE THREAD

**Issue by weidongxu-microsoft** [microsoft/azure-pipelines-tasks#11271]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ShellScriptV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=101715&view=results
https://github.com/Azure/azure-sdk-for-java/blob/repo_restructure/eng/pipelines/mgmt.yml

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
```
      - task: ShellScript@2
        displayName: 'call mvn for each mgmt sdk individually'
        inputs:
          scriptPath: "$(System.DefaultWorkingDirectory)/eng/pipelines/scripts/mgmt_sdk_compiler.sh"
          cwd: "$(System.DefaultWorkingDirectory)"
          failOnStandardError: true
          args: "$(JavaVersion) $(MavenGoals)"
```

From sh output:
```
#### CWD : 
/home/vsts/work/1/s/eng/pipelines/scripts
```

Still in sub directory instead of project root.

Compare
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ShellScriptV2/shellscript.ts
and
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/BashV3/bash.ts

It seems `cwd` not set into `bash.exec` option in shellscript.ts.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
