### ISSUE TITLE
Can NuGetCommand Always get latest version of packages?

### ISSUE THREAD

**Issue by wpatter6** [microsoft/azure-pipelines-tasks#11270]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGetCommand

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - account name: william.patterson@flyfrontier.com, 
    - team project name: flyfrontier
    - build definition name/build number: 66114

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name: 'windows-latest'

## Issue Description

Is it possible to force a certain package to always restore the latest version?  We have a private nuget feed in our project that I'd like to run tests against, so any time that package is updated, I'd like a build process to restore the latest version and run tests.  Attached are the logs of the various settings I have tried.

### Task logs
[logs_66105.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3572078/logs_66105.zip)
[logs_66108.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3572079/logs_66108.zip)
[logs_66109.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3572080/logs_66109.zip)
[logs_66114.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3572081/logs_66114.zip)

**Comment by wpatter6** [comment]
So I was able to get this to work using a custom command.  Not terribly verbose so I think this is good enough.

```
- task: NuGetCommand@2
  displayName: 'Update package to Latest'
  inputs:
    command: 'custom'
    arguments: 'update path/to/packages.config -Id Package.To.Update -Source https://pkgs.dev.azure.com/path/to/feed/nuget/v3/index.json'
    noCache: true
```
