### ISSUE TITLE
Azure YAML dayOfTheWeek

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11298]
Hi,

In my build pipeline, i want to do a certain task only on the weekends as it takes time & resource. I explored the conditions, pipeline and build variables documentation, but it was not clear to me if there is a way I can get this.

I am looking for something like:
condition: dayOfBuildTrigger()=='Saturday'

Can I do something like this?

Thanks,

**Comment by RoopeshNair** [comment]
No there are no predefined conditions available to achieve this. You could set an [output variable ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?tabs=yaml%2Cbatch&view=azure-devops#use-output-variables-from-tasks)using custom script and use it evaluate in a condition. 

Alternatively you can use a scheduled trigger using cron syntax such that it will fire only on certain day

```yaml
schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - releases/*
  always: true
```

**Comment by saxenark** [comment]
@RoopeshNair : can you please suggest a small snippet on how to do this for a single task within a pipeline?

**Comment by RoopeshNair** [comment]
Hope this helps

```yaml
jobs:

# Set an output variable from job A
- job: A
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - powershell: |
      $DayoftheWeek = (Get-Date).DayOfWeek
      echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]$DayoftheWeek"
    name: setvarStep

# Map the variable into job B
- job: B
  dependsOn: A
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]  
  steps:
  - script: echo $(myVarFromJobA)
    name: echovar
    condition: and(succeeded(), eq(variables['myVarFromJobA'], 'Saturday'))
```
