### ISSUE TITLE
IISWebAppManagementOnMachineGroup@0 inputs

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11299]
Hi,

I am using the IISWebAppManagementOnMachineGroup@0 task in my pipeline to create a website during the continuous deployment stage:

**I use a self hosted on-prem machine for my deployment.
My application is based on ASP.Net core 2.2**

My requirement is to have my website directly under the "Sites" node in IIS on a windows server. I can't find documentation enough to understand what values to provide for

```
              ParentWebsiteNameForVD: 
              VirtualPathForVD: 
              ParentWebsiteNameForApplication: 
              VirtualPathForApplication:
              AppPoolNameForApplication:
```
Here is my yaml for the build pipeline

```
- stage: ContinuousDeployment
  jobs:
  - deployment: ContinuousDeployment
    displayName: Continuous Deployment
    pool: MyDeploymentPool
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Manage IISWebsite'
            inputs:
              WebsiteName: MyWebSite
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"AllUnassigned","port":"44394","hostname":"","sslThumbprint":"","sniFlag":false}]}'               AppPoolNameForWebsite: MyAppPool              
              AppPoolName: 'MyAppPool'              
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\MyWebSite'
              AddBinding: true
              CreateOrUpdateAppPoolForWebsite: true
              ParentWebsiteNameForVD: ?????
              VirtualPathForVD: ?????
              ParentWebsiteNameForApplication: ?????
              VirtualPathForApplication: ?????
              AppPoolNameForApplication: ?????
```

My questions:
1. Am I proceeding correctly to deploy my ASP.Net Core 2.2 application on-prem?
2. What values do I provide for the inputs marked with ?????

Thanks,
