### ISSUE TITLE
can't access deployment agent pool in my build pipeline

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11300]
Hi,

I am having the following deployment agent pool.

![image](https://user-images.githubusercontent.com/2850526/64413201-b15c1680-d0ae-11e9-8ea2-d1436e3c8c57.png)

But, I can't access this pool in my build multi stage pipeline during the deployment stage and get an error like so:

![image](https://user-images.githubusercontent.com/2850526/64416919-b2447680-d0b5-11e9-9e69-60aab8bd626e.png)

Clicking on Authorize, gives me a brief pop up with the following message:

2 resource(s) could not be authorized due to insufficient permissions or missing resources.

PS: I am the admin for the project and the organization. 

PS: I am able to access this pool in a normal Release pipeline (creating the release definition outside of YAML).

What am I missing?

Thanks,

**Comment by chshrikh** [comment]
@saxenark currently deployment pools are not supported in YML pipelines. We are in process to add the support of deployment group in YML. Meanwhile you may check ["Deployment Job" with "Environment"](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#deployment-job) if it can help for deployment scenario

**Comment by saxenark** [comment]
@chshrikh 
Thanks for the note. But, from the link referenced, it still seems that the grammar requires a pool name to be specified. How do I specify my onprem pool name?

**Comment by saxenark** [comment]
> @chshrikh
> Thanks for the note. But, from the link referenced, it still seems that the grammar requires a pool name to be specified. How do I specify my onprem pool name?

Oh ok. I get it now. Deployment pools are not supported but Agent pools are. Correct?

**Comment by cawoodm** [comment]
Hang on, if we deploy to an agent pool doesn't that mean it will only deploy to one of the servers in the agent pool?

**Comment by RoopeshNair** [comment]
@cawoodm  - You can use agent pools to deploy to your targets. "Deployment Groups" or multi-machine deployment as in release pipelines are not supported yet. We are working on enabling it in YAML pipeline. Let us know if you still have queries

**Comment by saxenark** [comment]
@RoopeshNair : That's exactly what I tried once again and got the following error

![image](https://user-images.githubusercontent.com/2850526/67932108-53006f80-fbe9-11e9-895b-60cbb243c67a.png)

```
- stage: Deploy
  jobs:  
  - deployment: DoDeploy
    pool: blahblah
    environment: OnPremDevDeployment
    strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'PublishApp'
                displayName: 'downloading build artifact "PublishApp"'
```
When I try to authorize, it fails with the error

2 resource(s) could not be authorized due to insufficient permissions or missing resources.
Here's how my environment looks like (I think this might be the issue)

![image](https://user-images.githubusercontent.com/2850526/67932264-893def00-fbe9-11e9-9178-6279f28557fd.png)

Note that my deploy stage is on-prem where I plan to download the artifacts from build stage and deploy.

What am I missing?

**Comment by cawoodm** [comment]
I discovered you can't use `deployment` but have to use `job` for some strange reason...

```
# Deploy Apache Configuration on all DEV servers
#  This pipeline is triggered when code is committed to develop

trigger:
- develop

jobs:
- job: deploy_apache_dev
  displayName: Deploy Apache on all DEV Servers
  strategy:
    matrix:
      Dev1:
        AGENT_NAME: 'server1'
      Dev2:
        AGENT_NAME: 'server2'
  pool:
    name: MYAGENTPOOL
    demands:
      - agent.name -equals $(AGENT_NAME)
  steps:
  - powershell: .\deploy.ps1
    displayName: Deployment (deploy.ps1)
  - powershell: .\tests\ApacheTests.ps1 -Verbose
    displayName: Tests (ApacheTests.ps1)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit.xml'
```
