### ISSUE TITLE
File Transform (JSON) same name different shape across files

### ISSUE THREAD

**Issue by staff0rd** [microsoft/azure-pipelines-tasks#11344]
**Question, Bug, or Feature?**  
*Type*: Question/Feature
**Enter Task Name**: FileTransform
## Environment
Azure Pipelines
    
- staff0rd/5
- Hosted/ubuntu-latest

## Issue Description

A tfx extension for Azure Pipelines requires a manifest.json with a `version: "1.0.0"` format and a taskName/task.json with a `version: { Major: 1, Minor: 0, Patch: 0}` format.

I can define the following;
```yaml
variables:
- group: my-group
- name: version.Major
  value: 1
- name: version.Minor
  value: 1
- name: version.Patch
  value: $(Build.BuildId)
- name: version
  value: $(Build.BuildNumber)
```
But the result after running FileTransform is:
**EXPECTED**: manifest.json has `version: "1.0.0"` and task.json has `version: { Major: 1, Minor: 0, Patch: 0}`
**ACTUAL**:  manifest.json has `version: "1.0.0"` and task.json has `version: "1.0.0"` 

[Example yaml](https://github.com/staff0rd/tfx-cloudflare-purge/blob/87a062d98d2ff68efa7b82a5a139a9ac4ff05a08/azure-pipelines.yml)
