### ISSUE TITLE
Pip install package xxx and the package is not usable?! 

### ISSUE THREAD

**Issue by tarunaroraonline** [microsoft/azure-pipelines-tasks#11368]
**BUG**  
What's wrong with this pipeline? 

**PowerShell@2**

## Environment 
- Server - Azure Pipelines

- Agent - Hosted : 
    
    - If using Hosted agent, provide agent queue name: windows-latest

### Code...  

``` yaml 
name: 0.1.$(DayOfYear)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - README.MD

stages:
- stage: build
  jobs:
  - job: build_a_package
    pool: 
      vmImage: 'windows-latest'
    steps:

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          python --version
          pip install --upgrade pip
          pip install --upgrade setuptools
          
          pip install python-lambda

    - script: |
        lambda --help 
        
        cd $(Build.Repository.LocalPath)
        
        lambda build
      displayName: 'test'
``` 

The package install's fine as per the logs below, but is never recognized in the following steps. Why... Works locally and works just fine in other container images, but just doesn't work in the Azure pipeline using windows-latest 

``` cmd

Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\a5f2143a-ddd0-41a8-a664-641a528d8d32.ps1'"
Python 3.6.8
Requirement already up-to-date: pip in c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages (19.2.3)
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
Successfully installed setuptools-41.2.0
Collecting python-lambda
  Downloading https://files.pythonhosted.org/packages/60/72/003bd5f91bd50d1b1431f9850c2ea439a4ada9198842236033275733651f/python_lambda-3.2.6-py2.py3-none-any.whl
Collecting PyYAML (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/76/da/60f8d638d81d64db4ed3c279c22eb3a1eebfcde6130fee678940e603b930/PyYAML-5.1.2-cp36-cp36m-win_amd64.whl (214kB)
Collecting click (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting boto3 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/7a/2d/023459434edb679dea2c1547a75a5cb64d6c5c93ab601d664fde88c0bd83/boto3-1.9.231-py2.py3-none-any.whl (128kB)
Collecting botocore<1.13.0,>=1.12.231 (from boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/b1/18/90fa120b459ef691a19d2972790834b7eaf843e944d99d798005cb14e8fa/botocore-1.12.231-py2.py3-none-any.whl (5.7MB)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl (70kB)
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<1.13.0,>=1.12.231->boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Collecting docutils<0.16,>=0.10 (from botocore<1.13.0,>=1.12.231->boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
Collecting urllib3<1.26,>=1.20; python_version >= "3.4" (from botocore<1.13.0,>=1.12.231->boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.13.0,>=1.12.231->boto3->python-lambda)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: PyYAML, click, six, python-dateutil, jmespath, docutils, urllib3, botocore, s3transfer, boto3, python-lambda
Successfully installed PyYAML-5.1.2 boto3-1.9.231 botocore-1.12.231 click-7.0 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.0 python-lambda-3.2.6 s3transfer-0.2.1 six-1.12.0 urllib3-1.25.3
Finishing: PowerShell

Starting: test
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\2a3f3cd6-5829-446b-8d2b-efb7ecca9446.cmd""
'lambda' is not recognized as an internal or external command,
operable program or batch file.
'lambda' is not recognized as an internal or external command,
operable program or batch file.

```

Tarun
