### ISSUE TITLE
Scheduler Syntax for pipeline

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11363]
Hi,

I have the following as part of my build pipeline. I notice that whenever a developer creates a new branch this pipeline is triggered irrespective of the date/time.

Q1. Why is this pipeline triggered whenever a new branch is created from MyDev?
Q2. What is the syntax to exclude all other branches other than MyDev. I tried the below but that does not work. Note I do not have any release branches such as release\* as mentioned in the documentation. Instead for now I have branches like Developer1Branch, Bug2Branch, RandomBranch1 etc and so on and so forth with no consistent naming patterns.

       exclude:
       - * 

```
schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday Costly Scan
  branches:
    include:
    - MyDev
  always: false
```

Thanks,
