### ISSUE TITLE
Task: DotNetCoreCLI@2 nuget pack error No value was found for the provided environment variable.

### ISSUE THREAD

**Issue by Daniel127** [microsoft/azure-pipelines-tasks#11406]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question, Bug?

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Daniel Quiñones, Daniel127, CI-Release, #20190924.5

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

## Issue Description

I try pack a Nuget, the task build and generate the Nuget (I see that in the log), but task fail and stop the pipeline.

I don't know what is the environment variable that task mention.

Here is the YAML I'm using:

``` yml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: Bash@3
  inputs:
    filePath: '.azure/workflows/configure-variables-release.sh'
    failOnStderr: true

# Install .NET Core SDK
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.x'
- task: DotNetCoreInstaller@1
  inputs:
    version: '3.0.x'

# SonarCloud Prepare Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Daniel127'
    organization: 'daniel127'
    scannerMode: 'MSBuild'
    projectKey: 'semanticui-razor-components'
    projectName: 'Semantic UI Razor Components'

# Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

# SonarCloud analyze and publish results
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/QD.Components.Semantic.csproj'
    configuration: '$(buildConfiguration)'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(packageVersion)'
    verbosityPack: 'Diagnostic'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
```
Here the bash script

``` sh
#!/bin/bash
function check_version() {
  if [[ $1 =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
    echo "$1"
  else
    echo ""
  fi
}

echo "Configuring package version"

commitId=$BUILD_SOURCEVERSION

gitTagVersion="$(git describe --exact-match $commitId --abbrev=0 --tags --first-parent)"
appVersion=${gitTagVersion:1}
echo "Git version: $gitTagVersion"
echo "App version: $appVersion"

if [[ ! $(check_version ${appVersion}) ]]; then
  exit 1;
fi

echo "##vso[task.setvariable variable=packageVersion]$appVersion"
echo "Finished"
```
### Task logs

https://dev.azure.com/Daniel127/Semantic%20UI%20Razor%20Components/_build/results?buildId=134&view=results

### Error logs

> ##[error]No value was found for the provided environment variable.

**Comment by dikhakha** [comment]
@Daniel127 It looks like the task is failing due to this line:
`versionEnvVar: '$(packageVersion)'`
The environment variable 'packageVersion' is not set correctly in the script or is empty. Can you please check if it is being set by the script ? Also, I am not able to access the task logs you have shared. You can give me read permission or share the debug logs here. Set 'system.debug' = true in pipeline variables to get debug logs.

**Comment by Daniel127** [comment]
@dikhakha , The variable 'packageVersion' is set correctly in the script, and the Nuget package is created but task fail

Here the log
[logs_134.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3659351/logs_134.zip)

Recently i changed the YML for this, and now it's working, but i don't know how the Nuget has the correct version

``` yml
# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: Bash@3
  inputs:
    filePath: '.azure/workflows/configure-variables-release.sh'
    failOnStderr: true

# Install .NET Core SDK
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.x'
- task: DotNetCoreInstaller@1
  inputs:
    version: '3.0.x'

# SonarCloud Prepare Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Daniel127'
    organization: 'daniel127'
    scannerMode: 'MSBuild'
    projectKey: 'semanticui-razor-components'
    projectName: 'Semantic UI Razor Components'

# Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

# SonarCloud analyze and publish results
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/QD.Components.Semantic.csproj'
    configuration: '$(buildConfiguration)'
    packDirectory: '$(Pipeline.Workspace)/nuget'
    nobuild: true
    versioningScheme: 'off'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/nuget'
    artifact: 'Package'
```
