### ISSUE TITLE
dotnet restore task fails if DOTNET_SKIP_FIRST_TIME_EXPERIENCE is set

### ISSUE THREAD

**Issue by stevenvolckaert** [microsoft/azure-pipelines-tasks#11449]
## Required Information

- **Type:** Bug
- **Task Name:** `CacheBeta@0`

## Environment

- **Server:** Azure Pipelines
- **Account name**: `skarabeecomnv`
- **Team project name**: `Korfine.Net`
- **Build definition:** `rent-assist` (definition ID 36)
- **Agent**: Hosted (VM image `windows-2019`)
- **.NET Core SDK used:** 2.2.402

## Issue Description

The pipeline works, including the `CacheBeta@0` task, but if we set the `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` environment variable to `true`, the `dotnet restore` command (task `DotNetCoreCLI@2`) that follows the `CacheBeta` task fails with the following error message:

```
error NU1403: The package runtime.native.System.IO.Compression.4.3.0 sha512 validation failed. The package is different than the last restore. [d:\a\1\s\services\src\Kdc.RentAssist.CoreService\Kdc.RentAssist.CoreService.csproj]
```

**Of course, we can simply set `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` to `false`, but the point is that the `dotnet restore` command then takes around 80 seconds longer to run.** This is why I want to disable the _first time experience_.

My project (`Kdc.RentAssist.CoreService`), a ASP.NET Core 2.2 app, but has no direct dependencies to `System.IO.Compression`.

A [Google search](https://www.google.com/search?q="nu1403"+runtime.native.System.IO.Compression) reveals very little.

Observe the following table:

| Build ID | Commit ID |  `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` | `CacheBeta@0` | Build status |
|-----|-----|-----|-----|-----|
| [2829](https://dev.azure.com/skarabeecomnv/Korfine.Net/_build/results?buildId=2829) | `9b730f2e` | `false` | Enabled | Success |
| [2830](https://dev.azure.com/skarabeecomnv/Korfine.Net/_build/results?buildId=2830) | `9b730f2e` | **`true`** | Enabled | **FAILED** |
| [2831](https://dev.azure.com/skarabeecomnv/Korfine.Net/_build/results?buildId=2831) | `23b6dd38` | `true` | Disabled | Success |
| [2832](https://dev.azure.com/skarabeecomnv/Korfine.Net/_build/results?buildId=2832) | `23b6dd38` | `false` | Disabled | Success |

Perhaps we've configured something wrong in the pipeline? Below the pipeline definition:

```
# Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  AzureSubscription: '<classified>'
  ClientArtifactName: '$(Build.DefinitionName)-client_$(Build.BuildNumber)'
  ClientRootDirectory: '$(Build.SourcesDirectory)/clients'
  CoreServiceArtifactName: '$(Build.DefinitionName)-core-service_$(Build.BuildNumber)'
  CoreServiceProjectName: 'Kdc.RentAssist.CoreService'
  ServicesRootDirectory: '$(Build.SourcesDirectory)/services'
  ToolsRootDirectory: '$(Build.SourcesDirectory)/tools'

# Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  batch: 'true'
  branches:
    include:
      - 'refs/heads/master'
      - 'refs/heads/feature/v1.0.0'

# Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages
stages:

# STAGE 1 (BUILD) #####################################################################################################

- stage: 'build'
  displayName: 'Build'

  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
 
  # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
  jobs:

# STAGE 1 (BUILD) / JOB 1 (BUILD CLIENTS) #############################################################################

# <job definition omitted for brevity>

# STAGE 1 (BUILD) / JOB 2 (BUILD SERVICES) ############################################################################

  - job: 'build_services'
    displayName: 'Build services'

    pool:
      vmImage: windows-2019

    variables:
      DotNetCoreSdkVersion: 2.2.402
      NUGET_PACKAGES: '$(Pipeline.Workspace)/.nuget/packages'
      ProjectsToBuild: '$(ServicesRootDirectory)/**/*.csproj'
      ProjectsToPack: '$(ServicesRootDirectory)/src/**/$(CoreServiceProjectName).Clients.csproj'
      ProjectsToPublish: '$(ServicesRootDirectory)/src/**/$(CoreServiceProjectName).csproj'
      ProjectsToRestore: '$(ServicesRootDirectory)/**/*.csproj'
      ProjectsToTest: '$(ServicesRootDirectory)/test/**/*[Tt]ests.csproj'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks
    steps:

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#checkout
    - checkout: self
      fetchDepth: 1
      lfs: true
      submodules: true

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell
    - task: PowerShell@2
      displayName: 'Add commit hash and tag to build number'
      inputs:
        targetType: filePath
        filePath: '$(ToolsRootDirectory)/Update-BuildNumber.ps1'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell
    - task: PowerShell@2
      displayName: 'Log environment variables'
      inputs:
        filePath: '$(ToolsRootDirectory)/Write-EnvironmentVariables.ps1'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell
    - task: PowerShell@2
      displayName: 'Overwrite attribute ''BuildNumber'' of appsettings.json'
      inputs:
        arguments: '-JsonFile "$(ServicesRootDirectory)/src/$(CoreServiceProjectName)/appsettings.json" -Attribute "BuildNumber" -Value "$(Build.BuildNumber)"'
        filePath: '$(ToolsRootDirectory)\Update-JsonAttribute.ps1'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK $(DotNetCoreSdkVersion)'
      inputs:
        version: $(DotNetCoreSdkVersion)

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/caching#netnuget
    - task: CacheBeta@0
      displayName: 'Cache NuGet packages'
      condition: and(succeeded(), eq(variables['IsNuGetPackageCacheEnabled'], 'true'))
      inputs:
        key: 'NuGet | $(ServicesRootDirectory)/**/packages.lock.json'
        path: $(NUGET_PACKAGES)

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore $(ProjectsToRestore)'
      inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: '$(ServicesRootDirectory)/NuGet.Config'
        projects: '$(ProjectsToRestore)'
    
    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(ProjectsToBuild) ($(BuildConfiguration))'
      inputs:
        arguments: '--configuration $(BuildConfiguration) --no-restore'
        projects: '$(ProjectsToBuild)'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test $(ProjectsToTest) ($(BuildConfiguration))'
      inputs:
        arguments: '--configuration $(BuildConfiguration) --no-restore --no-build'      
        command: test
        projects: '$(ProjectsToTest)'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack $(ProjectsToPack)'
      enabled: false
      inputs:
        command: pack
        nobuild: true
        packagesToPack: '$(ProjectsToPack)'

    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet nuget push'
      enabled: false
      condition: and(succeeded(), eq(variables['IsNuGetPackagePushEnabled'], 'true'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/v'), startsWith(variables['Build.SourceBranch'], 'refs/tags/v')))
      inputs:
        command: push
        publishVstsFeed: '01f2ce0b-5c9b-4b02-aec9-35790101bb53'
    
    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish $(ProjectsToPublish)'
      inputs:
        arguments: '--configuration $(BuildConfiguration) --output "$(Build.ArtifactStagingDirectory)/CoreService" --no-restore'
        command: publish
        projects: '$(ProjectsToPublish)'
        publishWebProjects: false
   
    # Docs @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish core service pipeline artifact'
      inputs:
        artifact: '$(CoreServiceArtifactName)'
        targetPath: '$(Build.ArtifactStagingDirectory)/CoreService'
```

### Task logs

- [logs_2830.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3662949/logs_2830.zip)
