### ISSUE TITLE
KubernetesManifest container substitution regex is not correct in all cases

### ISSUE THREAD

**Issue by rauljmz** [microsoft/azure-pipelines-tasks#11517]
The image substution supplied in the `containers` input parameter is not done correctly if the deployment file is using the syntax:

```yaml
  spec:
      containers:
      - image: foo/my-image:tag
```

As the regular expression in 
https://github.com/microsoft/azure-pipelines-tasks/blob/7e19e00ddb6f0e7f306bd9bf1dc8732c1d7ba0e1/Tasks/KubernetesManifestV0/src/utils/utilities.ts#L120 is only looking for *spaces* before the keyword `image`.
