### ISSUE TITLE
[Feature Request] XCode5 Legacy Build System

### ISSUE THREAD

**Issue by mercuriete** [microsoft/azure-pipelines-tasks#11527]
**FEATURE REQUEST**

Starting from XCode 10, the legacy build system is deprecated and the New build system is the default.

So I want a new checkbox or property called:
UseModernBuildSystem: false

and it should behave like adding a new argument to xcode command
```-UseModernBuildSystem=0```
or
```-UseModernBuildSystem=NO```

**Actual yaml**
```
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'something.xcworkspace'
    scheme: 'Something'
    packageApp: false
    args: '-UseModernBuildSystem=0'
```

**Proposed yaml**

```
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'something.xcworkspace'
    scheme: 'Something'
    packageApp: false
    useModernBuildSystem: false
```
