### ISSUE TITLE
Allow DownloadPipelineArtifact to find project by name

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-pipelines-tasks#11546]
*Type*: feature

**Enter Task Name**: DownloadPipelineArtifact

## Issue Description

When downloading pipeline artifacts from a different pipeline than `current`, the `project` input requires the project GUID as its value. While the GUID is completely unambiguous, it is **very unintuitive** compared to the project name:
* The help text does not mention that the GUID is necessary, it implies that the project name could be used.
* The GUID is not easy to obtain (or code review) without using the designer UI.
* When targeting another pipeline in the same project, this input is redundant, and should be optional.

### Example
```yaml
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: '1c6c3d8a-ab77-4a23-b12d-e1a3519068a5'
    pipeline: '889'
    runVersion: 'latestFromBranch'
```

## Other
Similarly it would be favorable to be able to use a name for the  `pipeline` instead of the number; however the `pipeline` is much easier to work with, since it's a relatively small integer, and it shows up in the URL when viewing the target pipeline.

**Comment by jahsu-MSFT** [comment]
https://github.com/microsoft/azure-pipelines-agent/pull/2635

**Comment by jahsu-MSFT** [comment]
@JoeGaggler Thanks for the feedback. The changes for using project name should be released in 1-2 weeks. 
For using a name for pipeline, it should already be available in the latest agent version. 
Thanks,

**Comment by richardgavel** [comment]
@jahsu-MSFT Your comment "for using a name for a pipeline, it should already be available in the latest agent version" does match this result I'm getting:

##[debug]   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.GetpipelineIdAsync(AgentTaskPluginExecutionContext context, String buildPipelineDefinition, String buildVersionToDownload, String project, String[] tagFilters, String branchName)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Download artifact - xxx-environment

**Comment by sturlath** [comment]
Just wanted to add that you can get the project id by writing it out with System.TeamProjectId

```
- powershell: |      
      Write-Host "Project GUID": $(System.TeamProjectId)
      Write-Host "System.DefinitionId": $(System.DefinitionId)
      Write-Host "System.DefinitionName": $(System.DefinitionName)
```

I added System.DefinitionId also because you can use it in e.g. in DownloadPipelineArtifact@2 for pipeline but note that you can also just use pipeline: 'your_build_pipe_name'

```
- task: DownloadPipelineArtifact@2
  displayName: "Download the WebApp artifact from the Build pipeline"
  inputs:
    source: specific 
    project: 'project GUID'
    pipeline: 'your_build_pipe_name' 
    buildVersionToDownload: latest
    artifact: '$(Artifact_AppName)'
    path: $(folder_to_publish_to)
```

This hopefully saves somebody time!
