### ISSUE TITLE
Artifacts from SucceededWithIssues pipeline fail to download using DownloadPipelineArtifactV2 

### ISSUE THREAD

**Issue by braca** [microsoft/azure-pipelines-tasks#11556]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifactV2

## Environment
- Server - Azure Pipelines
    
- Agent - Private
**Agent queue name:** Default
OS of the machine running the agent and the agent version: Windows, agent version 2.158.0

## Issue Description

When I use `DownloadPipelineArtifact@2` in my multi-stage yaml pipeline to download an artifact from a previous pipeline, it works well, if the previous Pipeline status is `Succeeded`. 
If for some reason, the pipeline status is `SucceededWithIssues` the task will fail.

The issue seems to be in the plugin (https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs)  line (253 and 257) as it's using `BuildResult.Succeeded` to filter builds.

### Yaml

```
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'ProjectId'
          definition: '4'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          tags: '1.0.0'
          artifactName: 'release'
          targetPath: '$(Pipeline.Workspace)\test'
```
