### ISSUE TITLE
Azure yaml if then else for conditions

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11665]
Hi,

At the moment, I have two conditions in my yaml. I want to add more conditions e.g.
('Saturday' and 'ScheduledBuild') and so on. I am unable to find a clean way of having additional conditions without repeating myself with the previous conditions.

```
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*MyTests/*.csproj'
        arguments: '--verbosity minimal --configuration $(buildConfiguration) --no-build --logger:trx --filter TestCategory!=LongRunningTests --settings $(DefaultUTSettings) /p:AltCover=true /p:AltCoverForce=true /p:AltCoverAssemblyFilter=NUnit /p:AltCoverCobertura="$(CodeCoverageResultsDir)/altcover.cobertura.xml"'
        publishTestResults: true
      continueOnError: true
      displayName: 'dotnet test'
      condition: not(and(succeeded(), eq(variables['DayOfWeek'], 'Sunday'), eq(variables['IsScheduledBuild'], 'True')))
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*MyTests/*.csproj'
        arguments: '--verbosity minimal --configuration $(buildConfiguration) --no-build --logger:trx --settings $(FullViewsComparisonTestUTSettings) /p:AltCover=true /p:AltCoverForce=true /p:AltCoverAssemblyFilter=NUnit /p:AltCoverCobertura="$(CodeCoverageResultsDir)/altcover.cobertura.xml"'
      continueOnError: true
      displayName: 'dotnet test'
      condition: and(succeeded(), eq(variables['DayOfWeek'], 'Sunday'), eq(variables['IsScheduledBuild'], 'True'))
```

As an example, suppose I want to add a condition for 'ScheduledBuild' other than Sunday, do something else with dotnet test. How do I do it without repeating myself in a complicated way?

```
condition: and(succeeded(), eq(variables['DayOfWeek'], 'Sunday'), 
condition: and(succeeded(), ne(variables['DayOfWeek'], 'Sunday'), 

condition:? <this is the tricky part which I can't understand>. An else condition here would be very helpful.
```

Thanks,
Anubhav.
