### ISSUE TITLE
errorActionPreference not working 

### ISSUE THREAD

**Issue by winstonhenke** [microsoft/azure-pipelines-tasks#11671]
## Required Information

*Type*: Bug

**Enter Task Name**: AzurePowerShell@4
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV4

## Environment
- Server - Azure Pipelines 
- Agent - Hosted
    - Azure Pipelines - Image: VS2017

## Issue Description

 errorActionPreference not working

I'm passing `errorActionPreference: stop` into my task but
`write-host "error preference is: $errorActionPreference"`
is reporting
`error preference is: Continue`
Version : 4.159.3

Full task definition...
```yml
- task: AzurePowerShell@4
  displayName: 'Run Script'
  inputs:
    azureSubscription: '$(azureSubscription)'
    ScriptPath: '$(Pipeline.Workspace)/$(artifactName)/myScript.ps1'
    ScriptArguments: '
                      -location $(location)
                      -resourceGroupName $(resourceGroupName)'
    errorActionPreference: stop
    azurePowerShellVersion: 'OtherVersion'
    preferredAzurePowerShellVersion: '2.6.0'
```

And then the very first line in my script I have
`write-host "error preference is: $errorActionPreference"`
that prints `error preference is: Continue`
