### ISSUE TITLE
Wishlist: Make cache key elements explicit

### ISSUE THREAD

**Issue by autarch** [microsoft/azure-pipelines-tasks#11682]
*Type*: Feature
*Task Name*: CacheBeta@1

## Environment
Azure Pipelines - but this is a feature wishlist item, not a bug,
Hosted agent

## Issue Description

The current method of specifying a cache key has several issues.

First, it's very easy to generate invalid YAML with it, just by wanting to put literal strings first:

```yaml
key: "v1" | some-file.txt
```

This is invalid because parsers see the double quote and assume that they value will be entirely quoted. There is a disgusting workaround, of course:

```yaml
key: '"v1" | some-file.txt'
```

But this is a real eyesore!

The other issue is that we have to guess whether the task will interpret any given element as a path or not.

I propose a more explicit system for specifying the key where each key element is an array element:

```yaml
key:
  - literal: v1
  - path: some-file.txt
  - literal: some-file-name
```

This is entirely unambiguous and doesn't require any odd double-quoting. As a bonus, this makes it trivial to introduce new types of key elements in the future if that is ever needed.

**Comment by johnterickson** [comment]
Great feedback @autarch !

Where it gets trick is with restore keys - which there are multiple of.  In some of our earlier iterations, we tried this, but we couldn't get a good array of arrays in YAML that we liked.  Do you have some ideas there?

**Comment by autarch** [comment]
Ah, that's a good point. YAML makes this so hideous, unfortunately. I think it might be acceptable to either accept a single array or a map of arrays, where the map keys are names (that are ignored):

```yaml
restoreKeys:
  yarn-by-os:
    - literal: yarn
    - literal: $(Agent.OS)
  yarn-shared:
    - literal: yarn
```

This seems better than the truly heinous array of arrays in YAML:

```yaml
restoreKeys:
- - literal: os
- - literal: yarn
```

Have I mentioned that I _really_ don't like YAML?
