### ISSUE TITLE
CacheBeta@1 cannot find directory that definitely exists

### ISSUE THREAD

**Issue by autarch** [microsoft/azure-pipelines-tasks#11683]
## Required Information

*Type*: Bug
*Task Name*: CacheBeta@1

## Environment

*Server*: Azure Pipelines
*Agent*: Hosted

## Issue Description

I had a cache task set up as following:

```yaml
- task: CacheBeta@1
  displayName: Define build dependencies cache
  inputs:
    key: '"v1" | "build-deps" | $(CI_WORKSPACE_DIRECTORY)/cache/tools-perl-version | $(CI_WORKSPACE_DIRECTORY)/cache/build-deps-cpanfile'
    path: /usr/local/perl5/perlbrew/perls/tools-perl/lib/site_perl
```

The `path` definitely exists on disk.

However, I got an error when the job tried to save the cache contents.

### Task logs

Attached

### Error logs

`tar: /usr/local/perl5/perlbrew/perls/tools-perl/lib/site_perl: Cannot open: No such file or directory`

[logs_50.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3801768/logs_50.zip)
