### ISSUE TITLE
Questions: about ##vs artifact.upload and artifact.associate

### ISSUE THREAD

**Issue by JohnTortugo** [microsoft/azure-pipelines-tasks#11689]
Can I use `##vso[artifact.upload ...]` to upload several artifacts to different subfolders of a container? I.e., I want to create an structure like below:

```
| ParentArtifactsFolder
  --------> FolderA
            --------------> File1.txt
            --------------> File2.txt
            --------------> File3.txt

  --------> FolderB
             --------------> File4.txt
             --------------> File5.txt
```

I want to upload these files at different moments and they will come from different source directories. Moreover, I want later to download _all_ artifacts by referring to `ParentArtifactsFolder`. Is this possible today? I've played a lot with the YAML below but didn't get it do what I wanted:

```YAML
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- script: |
    touch file1.txt file2.txt file3.txt file4.txt file5.txt
    
    dire=`pwd`
    
    echo "##vso[artifact.upload containerfolder=ParentArtifactsFolder/sub1;artifactname=ParentArtifactsFolder]${dire}/file1.txt"
    echo "##vso[artifact.upload containerfolder=ParentArtifactsFolder/sub2;artifactname=ParentArtifactsFolder]${dire}/file2.txt"
    echo "##vso[artifact.upload containerfolder=ParentArtifactsFolder/sub1;artifactname=ParentArtifactsFolder]${dire}/file3.txt"
    echo "##vso[artifact.upload containerfolder=ParentArtifactsFolder/sub2;artifactname=ParentArtifactsFolder]${dire}/file4.txt"
    echo "##vso[artifact.upload containerfolder=ParentArtifactsFolder/sub1;artifactname=ParentArtifactsFolder]${dire}/file5.txt"
  displayName: 'Run a multi-line script'

- task: DownloadBuildArtifacts@0
  displayName: Download ParentArtifactsFolder
  inputs:
    buildType: current
    artifactName: ParentArtifactsFolder
```

Also, what's the difference between `artifact.upload` and `artifact.associate` ?

## Required Information

**Question, Bug, or Feature?**  Question

**Enter Task Name**: ##vso[artifact.upload]

**Account name, team project name, build definition number:** dnceng / internal / 648
