### ISSUE TITLE
[BUG] Passing azure_subscription variable to AzureIoTEdge@2 deployment task fails in template validation step

### ISSUE THREAD

**Issue by DoychinDoychev** [microsoft/azure-pipelines-tasks#11699]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdge@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Environment is Azure Pipelines.

Account: https://dev.azure.com/applegreen-intouch
Team Project Name: IoT Edge
Build Definition Name Number: #20191106.1

- Agent - Hosted or Private: 
    The agent is hosted, it is the only agent,but i'm not sure of the name.
    
## Issue Description
I have an issue in my `AzureIoTEdge@2`. Passing `azureSubscription` as a variable $(azure_subscription) give me an error. The pipeline completely refused to start. 

[here is a screenshot](https://drive.google.com/file/d/1kgX1c6mNwf0QwGkcXHpgtJ8I5zWyR2Nf/view?usp=sharing "screenshot")

```yaml
...
stages:
- stage: DEV
  displayName: DEV
  jobs:
  - deployment: DeploymentJob 
    displayName: Deployment Job 
    variables:
    - group: DEV
    - name: deployment_id
      value: '$(Environment.Name)_$(System.StageName)_$(Build.BuildNumber)_$(Build.BuildId)'
    - name: target_condition
      value: 'tags.environment=''DEV'''
    - name: iot_hub_name
      value: 'AP-DEV'
    - name: azure_subscription     #NOTICE THIS VARIABLE
      value: 'DEV Environment Resource Group' # NOTICE ITS VALUE
    continueOnError: 'false'  
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 10 
    cancelTimeoutInMinutes: 10 
    environment: 'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
...
...
          - task: AzureIoTEdge@2
            displayName: 'Azure IoT Edge - Deploy to IoT Edge devices'
            inputs:
              action: 'Deploy to IoT Edge devices'
              azureSubscription: 'DEV Environment Resource Group'   # THIS WAY IT WORKS
              azureSubscription: $(azure_subscription)   # THIS WAY IT DOESN'T WORK
              iothubname: $(iot_hub_name)
              deploymentid: $(deployment_id)
              deviceOption: 'Multiple Devices'
              targetcondition: $(target_condition)
```
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
There was a resource authorization issue: "The pipeline is not valid. Job DeploymentJob: Step input azureSubscription references service connection $(azure_subscription) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Authorize resources
```
