### ISSUE TITLE
Azure IoT Edge: Failed to fetch container registry authentication token

### ISSUE THREAD

**Issue by charlie-haley** [microsoft/azure-pipelines-tasks#11714]
## Required Information

I'm trying to deploy an Azure IoT Edge module through Azure Pipelines. I've set up my build steps as below but it's returning an error message on the `Push module images` step

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdge  

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description
Below is a copy of my pipeline. I have a service connection set up under the name `containerregistry` 

![image](https://user-images.githubusercontent.com/27928201/68438643-af9cf500-01bc-11ea-82b0-7ee04bf821e0.png)
```yaml
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureIoTEdge@2
  inputs:
    action: 'Build module images'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'arm32v7'
- task: AzureIoTEdge@2
  inputs:
    action: 'Push module images'
    containerregistrytype: 'Generic Container Registry'
    dockerRegistryConnection: 'containerregistry'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'arm32v7'
    fillRegistryCredential: 'true'
```

### Task logs

```
##[section]Starting: AzureIoTEdge
==============================================================================
Task         : Azure IoT Edge
Description  : Build and deploy an Azure IoT Edge image
Version      : 2.3.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
==============================================================================
Pushing module images...
29177abd-9970-4ff3-a171-cf8cb6824915 exists true
##[error]Error: Failed to fetch container registry authentication token, please check you container registry setting in build task. The username for container registry is 
##[section]Finishing: AzureIoTEdge
```

### Error logs

```
[error]Error: Failed to fetch container registry authentication token, please check you container registry setting in build task. The username for container registry is 
```

**Comment by charlie-haley** [comment]
This is also the response I get when I choose the Azure Container Registry option. (which I am using) it falsely indicates a success even though nothing has been pushed to the registry.

```
##[section]Starting: AzureIoTEdge
==============================================================================
Task         : Azure IoT Edge
Description  : Build and deploy an Azure IoT Edge image
Version      : 2.3.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
==============================================================================
Pushing module images...
/home/vsts/work/1/s /home/vsts/work/1/s
iotedgedev already installed with version: version 2.1.0

[command]/usr/local/bin/iotedgedev push --no-build --file /home/vsts/work/1/s/deployment.template.json --platform arm32v7

=======================================
======== ENVIRONMENT VARIABLES ========
=======================================

.env file not found on disk. Without a file on disk, you must specify all Environment Variables at the system level. (/home/vsts/work/1/s/.env)
Validating deployment template /home/vsts/work/1/s/deployment.template.json
Validating schema of deployment template.
Deployment template schema validation passed.
Expanding image placeholders
Converting createOptions
Deleting template schema version
Expanding 'deployment.template.json' to 'config/deployment.arm32v7.json'
Validating generated deployment manifest config/deployment.arm32v7.json
Validating schema of deployment manifest.
Deployment manifest schema validation passed.
Start validating createOptions for all modules.
Validating createOptions for module edgeAgent
No settings or createOptions property found in module edgeAgent. Skip createOptions validation.
Validating createOptions for module edgeHub
No settings or createOptions property found in module edgeHub. Skip createOptions validation.
Validating createOptions for module webapp
No settings or createOptions property found in module webapp. Skip createOptions validation.
Validation for all createOptions passed.
The generated deployment file located in the path: /home/vsts/work/1/a/deployment.arm32v7.json
Expanding registry credentials in deployment file...
Finished pushing module images
##[section]Finishing: AzureIoTEdge
```

**Comment by robbertvanhove** [comment]
I got the same problem. @prativen @blackchoey any progress on this issue so far?

**Comment by grizzljt** [comment]
I'm seeing the same issue from ubuntu 18.04 with both via a YAML pipeline with the defaultPlatform of arm32v7 and a classic pipeline with the defaultPlatform of amd64.

**Comment by blackchoey** [comment]
Hi everyone, please use `Azure Container Registry` instead of `Generic Container Registry` as Container registry type in the `Push module images` task. This provides same experience.
The `Generic Container Registry` aims to provide a way to let you use docker registry other than Azure Container Registry. For example, you want to push the image to docker hub. We will provide better error message for this in the future.
Please let us know if you have additional questions on this.

**Comment by blackchoey** [comment]
@charlie-haley Can you share a sample of deployment.template.json and folder structure for your project? Something in your deployment.template.json should be inconsistent with your folder structure, so the task failed to figure out images need to be pushed (just imagine there's a dummy module in your project, which won't be built in your pipeline). I can share how to adjust the deployment.template.json or your folder structure.

**Comment by alevincenzi** [comment]
Hello.
i am experiencing a similar issue. Do you have any update?

We run the task that generates a manifest
```
pool:
  vmImage: 'ubuntu-latest'
....
- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Generate manifest'
  inputs:
    action: 'Generate deployment manifest'
    templateFilePath: 'EdgeSolution/deployment.template.json'
    defaultPlatform: 'amd64'
    deploymentManifestOutputPath: '$(Build.ArtifactStagingDirectory)/newdeployment.json'
    validateGeneratedDeploymentManifest: 'true'
```
and the `deployment.template.json` has the following section
```
...
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "myiotcontainerthatdoesnotexist": {
                "username": "$CONTAINER_REGISTRY_USERNAME_myiotcontainerthatdoesnotexist",
                "password": "$CONTAINER_REGISTRY_PASSWORD_myiotcontainerthatdoesnotexist",
                "address": "myiotcontainerthatdoesnotexist.azurecr.io"
              }
            }
          }
        },
...
```
The pipeline has the two variables:
![image](https://user-images.githubusercontent.com/8089061/91051690-bfd57200-e620-11ea-9d0d-98477c654363.png)

but at the end the file `newdeployment.json` remains unchanged.

I expect the task to replace the placeholders for username and password in the template and generate a new file. Isn't it?

This is what i deduce reading this doc (step 10):
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd#configure-continuous-deployment

The log of the task says: 
```

Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
==============================================================================
Start generating deployment manifest...
/home/vsts/work/1/s/EdgeSolution /home/vsts/work/1/s
iotedgedev already installed with version: version 2.1.5

/usr/local/bin/iotedgedev genconfig --file /home/vsts/work/1/s/EdgeSolution/deployment.template.json --platform amd64 --fail-on-validation-error
/usr/local/lib/python2.7/dist-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,

=======================================
======== ENVIRONMENT VARIABLES ========
=======================================

.env file not found on disk. Without a file on disk, you must specify all Environment Variables at the system level. (/home/vsts/work/1/s/EdgeSolution/.env)
Expanding image placeholders
Converting createOptions
Deleting template schema version
Expanding 'deployment.template.json' to '/home/vsts/work/1/a/newdeployment.json'
Validating generated deployment manifest /home/vsts/work/1/a/newdeployment.json
Validating schema of deployment manifest.
Deployment manifest schema validation passed.
....
```

I tried to use te syntax `${VAR}` in the template but that does not fix it.

Can you please help?
