### ISSUE TITLE
Need a displayName for a task

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-tasks#11833]
It seems currently impossible to provide a readable description to a task. This would be helpful - at the moment we just see e.g. "PowerShell".

Formerly we were using the `powershell` step...
```
  - powershell: |
      .\build.ps1 -AppName ${{parameters.appname}} -Agent $env:AGENT_NAME
    displayName: 'Build: Create DEV environment (Win)'
```
...but this only works on Windows so we switched to a double step...
```
  - powershell: |
      .\build.ps1 -AppName ${{parameters.appname}} -Agent $env:AGENT_NAME
    displayName: 'Build: Create DEV environment (Win)'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - pwsh: |
      .\build.ps1 -AppName ${{parameters.appname}} -Agent $env:AGENT_NAME
    displayName: 'Build: Create DEV environment (Linux)'
    condition: eq( variables['Agent.OS'], 'Linux' )
```
...which is ugly so we switched to the `PowerShell@2` task:
```
  - task: PowerShell@2
    inputs:
      filePath: ./ci/build.ps1
      arguments: -AppName ${{parameters.appname}} -Agent $env:AGENT_NAME
```
Which is gravy but now we see only "PowerShell" instead of "Build Step":
![image](https://user-images.githubusercontent.com/498834/69446504-db8baf00-0d54-11ea-8ea5-ee8fc9fdccd2.png)

**Comment by damccorm** [comment]
You should still be able to use displayName. So it would be:
```
  - task: PowerShell@2
    inputs:
      filePath: ./ci/build.ps1
      arguments: -AppName ${{parameters.appname}} -Agent $env:AGENT_NAME
    displayName: 'Build: Create DEV environment'
```
