### ISSUE TITLE
Publish test results using 'dotnet test' (DotNetCoreCLIV2) is not working behind corporate proxy

### ISSUE THREAD

**Issue by satano** [microsoft/azure-pipelines-tasks#11831]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLIV2

## Environment

- Server - Azure Pipelines
- Agent - Private:
  - Current agent version: 2.160.1
  - Agent runs as a service
  - Windows 10 Enterprise (1903)
  - Latest Visual Studio Community is installed on the machine (currently version 16.3.10)
  - The machine is behind corporate proxy (proxy is not authenticated)

## Issue Description

We run our tests using `DotNetCoreCLIV2` task.

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*test*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore --no-build'
```

The tests are executed correctly and the execution is fast. Then the task is trying to publish test results back to DevOps and this is failing with error:

```
Failed to upload file MLEARNING$_MLEARNING_2019-11-22_08_51_48.trx to Blob Transfer exception with errorcode Unknown, exception message Microsoft.WindowsAzure.Storage.DataMovement.TransferException: The transfer failed.
```

The build as a whole is not failing. but it takes too long time. Probably because of timeouts. Test step lasts about **17 minutes**, instead of usual **30 - 40 seconds**. This is not a problem with our proxy, because all the other tasks are working correctly (downloading source code, publishing artifacts...). Only publishing the test results is not working. And it used to work couple of days ago - the only thing we know about that has chaged is update of Visual Studio to the latest version on that build machine.

It seems to be the same bug as #11292 but with different task.

### Task logs

[8_Test.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3879468/8_Test.txt)

## Workaround

We have found a workaround for now. The solution is to use two steps. But just using one step/task is preferable.

1. `dotnet test` without publishing test results
2. Explicit publish of test results ([PublishTestResults@2](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results)).

```yml
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*test*.csproj'
    publishTestResults: false
    arguments: '--configuration $(buildConfiguration) --no-restore --no-build --logger trx --results-directory "$(Agent.TempDirectory)"'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Agent.TempDirectory)'
```

**Comment by ShreyasRmsft** [comment]
@satano adding @navin22 to help look into this.

**Comment by JustinPealing** [comment]
I worked around this by disabling the "Publish test results and code coverage" option on the .NET Core task and adding a separate Publish Test Results task

**Comment by pauldoom** [comment]
YAML workaround: Users with timeouts using the PublishTestResults@2, you can disable the upload (*which is not required since the agent processes the results locally) with "publishRunAttachments: false"

Example:
```
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test-results/*test*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publish test results'
    publishRunAttachments: false
```
