### ISSUE TITLE
Deploying using AzureFunctionApp@1 erases custom domains and SSL bindings !

### ISSUE THREAD

**Issue by zmarty** [microsoft/azure-pipelines-tasks#11901]
*Type*: Bug

**Enter Task Name**: AzureFunctionApp@1  

## Environment
Azure Pipeline: https://msasg.visualstudio.com/Bing_UX/_build?definitionId=11429&_a=summary
Agent: Hosted

## Issue Description

When we use AzureFunctionApp@1 to deploy an Azure Function app, any custom domain or SSL binding previously set using Azure portal gets erased. This is a big problem, as the app then stops accepting https traffic from that custom domain.

Relevant snippet from our pipeline yml:
```
  - task: AzureFunctionApp@1
    displayName: 'Azure functions app deploy'
    inputs:
      azureSubscription: ${{ parameters.serviceConnectionName }}
      appType: 'functionApp'
      appName: ${{ parameters.appName }}
      appSettings: ${{ parameters.appSettings }}
      package: '$(Pipeline.Workspace)/${{ parameters.artifactName }}Zip/${{ parameters.artifactName }}.zip'
      deploymentMethod: 'runFromPackage'
```
