### ISSUE TITLE
Kubernetes deployment container env variables

### ISSUE THREAD

**Issue by rauntska** [microsoft/azure-pipelines-tasks#11945]
Hi,

Im using the KubernetesManifestV0 task to deploy my container from devops to aks.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops

However im wondering if there's any possibility to use the variables defined in Devops->Pipelines->Library to set the "env" variables for the container im deploying?

Im using multiple environments so it would be awesome to not have to define the "env" variables in the manifest.yml file. 

BR,
Rauno

**Comment by shigupt202** [comment]
@rauntska There's no direct way to use externally defined variables as the 'env' variables in the manifest file. You can, however, use configMaps to replace your env variables. 
For example, you can create a config map like this:
![configMap](https://user-images.githubusercontent.com/57620559/70610253-43813700-1c29-11ea-8537-a37f210ba1dd.PNG)

Then set  _var_ to the value of your env variable. In the manifest file, you can assign the env variable to the value defined in the config map `special-config`.
In case you have a lot of env variables, you can define them all in the data section of config map and then use it's reference in envFrom section in the manifest file like this:
`containers:
    - name: -
      image: -
      envFrom:
      - configMapRef:
          name: special-config`

**Comment by rauntska** [comment]
Thanks, That worked just as a wanted. Now i can make environment specific variable groups in devops and use there to create the configmaps. :)

**Comment by brechtvhb** [comment]
How did you manage to get the deveops variables in the config map?

**Comment by shigupt202** [comment]
@brechtvhb You can use the arguments section of ConfigMaps (in KubernetesV1 task) to set the variables in config map. Please refer to the example given in previous comment.

**Comment by brechtvhb** [comment]
That's still a cumbersome task if you have a lot of environment variables and variable groups.

**Comment by shigupt202** [comment]
I'm not really aware of how service fabric does this. Would it be possible for you to share a snippet or an example of how environment variables are pushed to the container in service fabric?

**Comment by brechtvhb** [comment]
In service fabric it realy nothing more than a setting in the yaml definition. The task takes care of all the rest:

        - task: ServiceFabricDeploy@1
          inputs:
            overrideApplicationParameter: true
            overridePublishProfileSettings: true

**Comment by brechtvhb** [comment]
It would be nice if there was an option in the kubernetes task that would do the same.

Read out all env variables and map them to the configmap automagically.

**Comment by shigupt202** [comment]
Thanks for the feedback. Let me discuss with the team and PM's about the feasibility of adding this feature in the task. 
For the time being, as a workaround you can use command line task in your pipeline to write all the environment variables into a file and then use that as a config map.

**Comment by georgez4** [comment]
@brechtvhb @rauntska 

Currently using the following script running it with an Azure CLI release task to create a file I can feed to kubectl create configmap with --from-env-file flag:

`az pipelines variable-group variable list --id {variable-group-id} --organization {your-devops-organization} --project {your-devops-project} -o json | jq -r 'to_entries | map("\(.key)=\(.value.value)") | .[] ' > configmap.txt`

Tasks as YAML:

```
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: '{service-connection}'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az pipelines variable-group variable list --id {variable-group-id} --organization {your-devops-organization} --project {your-devops-project} -o json | jq -r 'to_entries | map("\(.key)=\(.value.value)") | .[] ' > configmap.txt
```

```
- task: Kubernetes@1
  displayName: 'create configmap'
  inputs:
    kubernetesServiceEndpoint: '{service-connection}'
    namespace: '{namespace}'
    configMapName: '{configmap-name}'
    forceUpdateConfigMap: true
    configMapArguments: '--from-env-file=./configmap.txt'
```
