### ISSUE TITLE
KubernetesManifest error on final increment of canary

### ISSUE THREAD

**Issue by yelob** [microsoft/azure-pipelines-tasks#11954]
*Type*: Bug

**Enter Task Name**: KubernetesManifest  

## Environment
- Server - Azure Pipelines

## Issue Description

When using the task with the canary strategy, the final step is to make the canary the new stable version. The process tries to patch the spec.selector for the deployment:

originally created canary deployment yaml:
```
{
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "metadata": {
        "name": "my-service-canary",
        "namespace": "myservice",
        "labels": {
            "app": "my-service",
            "chart": "my-service-0.0.1",
            "azure-pipelines/version": "canary"
        },
        "annotations": {
            "azure-pipelines/version": "canary"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "my-service",
                "azure-pipelines/version": "canary"
            }
        },
        <snip>
```

attempted stable deployment yaml:
```
{
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "metadata": {
        "name": "my-service",
        "namespace": "myservice",
        "labels": {
            "app": "my-service",
            "chart": "my-service-0.0.1",
            "azure-pipelines/version": "stable"
        },
        "annotations": {
            "azure-pipelines/version": "stable"
        }
    },
    "spec": {
        "replicas": 2,
        "selector": {
            "matchLabels": {
                "app": "my-service",
                "azure-pipelines/version": "stable"
            }
        },
        <snip>
```

This results in the error:
>The Deployment "my-service" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"my-service", "azure-pipelines/version":"stable"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

According to the Kubernetes team (https://github.com/kubernetes/kubernetes/issues/50808), the spec.selector is immutable after creation, so I don't believe this task should be adding/modifying that selector as part of the canary rolllout process.

### Task logs

Can be uploaded upon request.

**Comment by vithati** [comment]
I think you are using SMI canary deployment, it works if you are doing deploying using SMI canary from starting. If you have already existing deployment (deployed with some other way) and if you are trying to use canary deployment with SMI then it will fail.

**Comment by yelob** [comment]
No, this is without an existing deployment. It fails with an actual readable error if a deployment already exists.

**Comment by vithati** [comment]
@yelob , If you apply same deployment yaml file, K8S don't throw any error. Can you delete existing deployment and try once again. if still you are able to repo, can you share the steps you have tried.

**Comment by yelob** [comment]
I’ve tried it several times, first deleting the existing deployment. If the
deployment exists, a different error occurs. I can upload logs and yaml
files after I scrub out some specifics.

**Comment by yelob** [comment]
Here's a sample pipeline that fails:
```
stages:
- stage: mystage
  displayName: 'Deploy Canary'
  jobs:
  - deployment: deploy
    pool:
      vmImage: ubuntu-latest
    environment: foo.myservice
    strategy:
      canary:
        increments: [10,20]
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: 'Bake manifest'
            name: bake
            inputs:
              action: bake
              namespace: 'myservice'
              helmChart: '$(Build.ArtifactStagingDirectory)/deploy/my-service-0.0.1.tgz'
              releaseName: 'my-service'
          - task: KubernetesManifest@0
            displayName: 'Deploy manifest'
            inputs:
              action: $(strategy.action)
              strategy: $(strategy.name)
              percentage: $(strategy.increment)
              trafficSplitMethod: smi
              baselineAndCanaryReplicas: 1
              kubernetesServiceConnection: 'my-kubernetes'
              namespace: 'myservice'
              manifests: $(bake.manifestsBundle)
```
