### ISSUE TITLE
HelmDeploy@0 upgrade ignores chartVersion

### ISSUE THREAD

**Issue by StiviiK** [microsoft/azure-pipelines-tasks#11952]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0 upgrade

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure DevOps Pipelines

- Agent - Hosted or Private: 
    `Hosted ubuntu-latest`

## Issue Description
```
- task: HelmDeploy@0
  displayName: 'helm upgrade elasticsearch'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: ***
    azureResourceGroup: ***
    kubernetesCluster: ***
    command: 'upgrade'
    chartType: 'Name'
    chartName: elastic/elasticsearch
    chartVersion: 7.4.1
    # chartVersion gets for some reason ignored, so we need to add it manually to the args
    namespace: '***'
    releaseName: '***'
```
Using this task the version gets not set in the helm upgrade command:
`/opt/hostedtoolcache/helm/2.9.1/x64/linux-amd64/helm upgrade --namespace *** --install --wait -f /home/vsts/work/1/helmvalues/elasticsearch.yaml -f /home/vsts/work/1/helmvalues/elasticsearch-dev.yaml *** elastic/elasticsearch`

I have to add manually `arguments: '--version 7.4.1'` that i can specify the version.
