### ISSUE TITLE
NuGet Pack does not respect PackageId

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#12013]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommand

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetCommandV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted, windows-2019 
    
## Issue Description

When I use the NuGetCommand task to pack a library, the "PackageId" specified in the CSPROJ file is ignored. Here's part of my CSPROJ file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.0.5</Version>
    <PackageId>Project.Sdk</PackageId>
  </PropertyGroup>
</Project>
```

And here is my YAML for the task:

```yaml
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: ./src/ProjectService/ProjectService.csproj
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
```

And in the logs, I can see that instead of Project.Sdk being generated, ProjectService is being generated:

> Successfully created package 'd:\a\1\a\ProjectService.0.1.0-CI-20191219-163945.nupkg'

However, if I just use the dotnet CLI with:

```script
dotnet pack ./src/ProjectService/ProjectService.csproj --output $(nugetPackagePath)
```

I get the expected package id:

> Successfully created package 'D:\a\1\s\$(nugetPackagePath)\Project.Sdk.0.0.5.nupkg'

NOTE: NuGet 4.9.1 is installed before each of these commands.

NOTE: Versions are expected to be different, but package id should be the same.
[Include task name(s), screenshots and any other relevant details]

Why is the NuGet task not respecting the package id?

### Task logs

[logs_304.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3984722/logs_304.zip)

### Error logs

From Nuget task:
> Successfully created package 'd:\a\1\a\ProjectService.0.1.0-CI-20191219-163945.nupkg'

From dotnet CLI:
> Successfully created package 'D:\a\1\s\$(nugetPackagePath)\Project.Sdk.0.0.5.nupkg'
