### ISSUE TITLE
[bug] using variables as azureSubscription in AzureFileCopy V3

### ISSUE THREAD

**Issue by NewFuture** [microsoft/azure-pipelines-tasks#12036]
**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: AzureFileCopy (V3)

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines  

- Agent - Hosted or Private: 
    
     - Host

## Issue Description

like this job when using variables as subscriptions the  `azureSubscription: "$(AZURE_SUBSCRIPTION)" `
```yaml
jobs:
  - deployment: web_deployment
    pool:
      vmImage: "windows-2019"
    variables:
      AZURE_SUBSCRIPTION: test-subscription
      x_containerName: $[coalesce(variables.CONTAINER_NAME,'$web')]
    environment: deploy
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: echo '$(x_containerName) $(AZURE_SUBSCRIPTION)'
            - task: AzureFileCopy@3
              inputs:
                azureSubscription: "$(AZURE_SUBSCRIPTION)" 
                containerName: $(x_containerName) # the container name default is $web
                storage: "test" # the storage
                destination: AzureBlob
                sourcePath: "$(Agent.BuildDirectory)/" #
```
it can not run then job with flow errors:

> There was a resource authorization issue: "The pipeline is not valid. Job web_deployment: Step input azureSubscription references service connection dg-website which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

related bug #11699
