### ISSUE TITLE
K8sManifest deploy: container substitution failes if containers share a folder

### ISSUE THREAD

**Issue by jebbench** [microsoft/azure-pipelines-tasks#12064]
# Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest

## Issue Description

When trying to substitute container images that share a common folder only one of the o,ages is substituted.

Deployment spec
```
    spec:
      containers:
      - name: untaggedinsamefoldera
        image: myacr.azurecr.io/folder/image-a
      - name: untaggedinsamefolderb
        image: myacr.azurecr.io/folder/image-b
```

Containers argument
```
myacr.azurecr.io/folder/image-a:1
myacr.azurecr.io/folder/image-b:2
```

Results:
```
    spec:
      containers:
      - name: untaggedinsamefoldera
        image: myacr.azurecr.io/folder/image-a:1
      - name: untaggedinsamefolderb
        image: myacr.azurecr.io/folder/image-b
```
