### ISSUE TITLE
Error in post-job step of CacheV2 task: `tar: Write error`

### ISSUE THREAD

**Issue by jneira** [microsoft/azure-pipelines-tasks#12070]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheV2 (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2)

## Environment
- Server - Azure Pipelines
     - Account name: jneira
     - Team project name: haskell-ide-engine
     - Build id:  364
     - url: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=364

- Agent - Hosted
    
    -  agent queue name: Azure Pipelines (https://dev.azure.com/jneira/haskell-ide-engine/_settings/agentqueues?queueId=9&view=jobs)

## Issue Description

Using the task CacheV2 i am getting an error in the post-job step of the second cache task:

```
Starting: Cache stack-root
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - stack-root          [string]
 - "Windows_NT"        [string]
 - d:\a\1\s/stack.yaml [file] --> A36170C42F95BB5B54EB3ED47CDFDD110801237EC9410F0B65AD176752DCDC2C
Resolved to: stack-root|"Windows_NT"|ep4NXRcF25ln+PeSP5yC62KFSYaP2HvMqy4uPimsKek=
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 0a36ff58-accb-4715-80ed-551d85485bff
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `stack-root|"Windows_NT"|ep4NXRcF25ln+PeSP5yC62KFSYaP2HvMqy4uPimsKek=`
Information, There is a cache miss.
tar: Write error
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 0a36ff58-accb-4715-80ed-551d85485bff
##[error]Process returned non-zero exit code: 1
Finishing: Cache stack-root
```

I am getting the error for all windows agents but one and no for linux or macos
* Although i am not using the task in the same way, linux ans macos only have one cache task
* Succeful windows task: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=364&view=logs&j=55d4a0cb-39cd-5101-a452-19070a43f034
* One of the failing windows tasks: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=364&view=logs&j=6b49165d-7ec7-52d3-31d2-92d638226258

### Troubleshooting

Originally i was using CacheBetaV0 with the same results: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=350&view=logs&j=6b49165d-7ec7-52d3-31d2-92d638226258&t=401983aa-046f-4f7f-832c-c52347c4d01e

The same configuration (with CacheBetaV0) was succesful in older builds, for example: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=323

### Error logs

```
tar: Write error
```

**Comment by jneira** [comment]
Hi, i've run the same commit in debug mode: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=365

The debug log of the post-job step of the CacheV2 task is:
```
##[debug]Starting 'tar' with arguments '-h -v -cf "95aa7f96e8174421aeee1d3f8fde35bb_archive.tar" -C "C:\sr" .'...
a .
a ./config.yaml
a ./pantry
a ./setup-exe-cache
a ./setup-exe-src
a ./snapshots
a ./stack.sqlite3
a ./stack.sqlite3.pantry-write-lock

.....(lot of files added)...
a ./setup-exe-cache/x86_64-windows
a ./setup-exe-cache/x86_64-windows/Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe
a ./setup-exe-cache/x86_64-windows/Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe
a ./pantry/hackage
a ./pantry/pantry.sqlite3tar: Write error
```
¿So it seems adding the file `./pantry/pantry.sqlite3` is causing the error?

**Comment by jneira** [comment]
I've tested locally thesame command in a msys64 bash session in my local windows system:
```
tar -h -v -cf "test.tar" "D:\sr"
...
D:\\sr/stack.sqlite3
D:\\sr/stack.sqlite3.pantry-write-lock
D:\\sr/templates/
D:\\sr/templates/new-template.hsfiles
D:\\sr/templates/new-template.hsfiles.etag
```
being `D:\sr` similar to the stored in the agent under `C:\sr` (same tree, including `./pantry/pantry.sqlite3`) and the tar command finished succesfully

**Comment by jneira** [comment]
i've got to workaround the issue changing the configuration from
```yaml
- task: Cache@2
   inputs:
     key: '"stack-root" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
     path: $(STACK_ROOT)
  displayName: "Cache stack-root"
- task: Cache@2
   inputs:
     key: '"stack-work" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
     path: .stack-work
  displayName: "Cache stack-work"
```

to 

```yaml
- task: Cache@2
    inputs:
      key: '"stack-root" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache stack-root"
- bash: |
    mkdir -p $STACK_ROOT
    tar -xzf .azure-cache/stack-root.tar.gz -C /
    mkdir -p .stack-work
    tar -xzf .azure-cache/stack-work.tar.gz
  displayName: "Unpack cache"
#more steps
- bash: |
      mkdir -p .azure-cache
      tar -czf .azure-cache/stack-root.tar.gz $(cygpath $STACK_ROOT)
      tar -czf .azure-cache/stack-work.tar.gz .stack-work
  displayName: "Pack cache"
```
Although it is no ideal to have to do the packaging manually with the scripts.
