### ISSUE TITLE
[UseDotNet] `cp: copyFileSync: could not write to dest file (code=ETXTBSY):/opt/hostedtoolcache/dotnet/dotnet`

### ISSUE THREAD

**Issue by ElvenSpellmaker** [microsoft/azure-pipelines-tasks#12082]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: `UseDotNet@2`

## Environment
- Server - Azure Pipelines.

- Agent - Hosted or Private: 
    
    - `ubuntu-18.04`

## Issue Description

We need two different SDK versions, the application is compiled with 2.1.x and the tests are ran under 3.1.x.

We have two uses of the `UseDotNet` SDK and on the second install it seems to think the file is busy and so `warn`s.
```
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: ${{ parameters.dotnet_core_version }}
        displayName: 'Use .NET Core SDK ${{ parameters.dotnet_core_version }}'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration ${{ parameters.build_type }}'
          workingDirectory: ${{ parameters.build_path }}
        displayName: 'Build'

      # IF `test_path` is set
      - ${{ if ne(parameters['test_path'], '') }}:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: ${{ parameters.test_dotnet_core_version }}
            displayName: 'Use .NET Core SDK ${{ parameters.test_dotnet_core_version }}'
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
cp: copyFileSync: could not write to dest file (code=ETXTBSY):/opt/hostedtoolcache/dotnet/dotnet

##[warning]Failed to copy root files into installation path: /opt/hostedtoolcache/dotnet. Error: Error: Failed cp: cp: copyFileSync: could not write to dest file (code=ETXTBSY):/opt/hostedtoolcache/dotnet/dotnet
```

**Comment by hiyadav** [comment]
Hey @ElvenSpellmaker 

Is this issue always happening or consistently ? And does the task warns and then succeeds ? 
Can you tell us the agent configuration, if it is hosted or private, and what os.type

**Comment by ElvenSpellmaker** [comment]
Hey @hiyadav, it's every build, the build succeeds but the warning is always there:
![image](https://user-images.githubusercontent.com/2286713/71984409-b11c8500-3220-11ea-9e59-06ac8a0278e9.png)

> if it is hosted or private, and what os.type
Sure, as mentioned in the issue above:
![image](https://user-images.githubusercontent.com/2286713/71984474-d0b3ad80-3220-11ea-88bb-9a1f498bf1d4.png)

**Comment by hiyadav** [comment]
@ElvenSpellmaker thanks for the details. 

This is happening, as executing some commands dotnet.exe is not exiting,and is kept running for some reason. Hence, when we install a new sdk/runtime, we aren't able to replace the dotnet.exe file due to it still being in use. However, everything else is replaced and the SDK/runtime files are installed.
I doubt we can kill the process to replace the dotnet.exe as it might be getting used by another project/agent in private agent case.

**Comment by ElvenSpellmaker** [comment]
@hiyadav Are the hosted agents running multiple builds from multiple users? Aren't they sandboxed from each other?

For more info this never happens on the first call to the task in the pipeline, but a subsequent call (such as installing another framework to run tests) generates this error.

**Comment by hiyadav** [comment]
@ElvenSpellmaker 

Yeah the hosted agents are sandboxed and run only one job at a time. The last explanation was for private agents, because of which we cannot choose to kill the dotnet.exe process and install.

As expected this will happen only after some commands of dotnet have already been run. After that the dotnet.exe file sometimes keep running (for reason that .NET Core team shall know).

Hence, when you try to install another version of .NET core, the task isn't able to replace dotnet.exe file.
I'll try to find, why the dotnet.exe kept running. Are you experiencing this for all projects where you try to install sdk twice or a particular case/project where this is happening ?

**Comment by ElvenSpellmaker** [comment]
@hiyadav Ahhh excellent, I got a bit worried there that they were running together then haha!

This seems to happen on a build where we run multiple instances of this task. The first one always succeeds in all, but the second one doesn't like it.

Here's a snippet of the file, when `test_path` is set it runs another `UseDotNet@2` task as the tests are under `3.1.x` but the project is currently still `2.1.x`.

```yml
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: ${{ parameters.dotnet_core_version }}
        displayName: 'Use .NET Core SDK ${{ parameters.dotnet_core_version }}'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration ${{ parameters.build_type }}'
          workingDirectory: ${{ parameters.build_path }}
        displayName: 'Build'

      # IF `test_path` is set
      - ${{ if ne(parameters['test_path'], '') }}:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: ${{ parameters.test_dotnet_core_version }}
            displayName: 'Use .NET Core SDK ${{ parameters.test_dotnet_core_version }}'

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              projects: ${{ parameters.test_path }}
              arguments: -c ${{ parameters.build_type }} --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true
            displayName: Run Tests (${{ parameters.test_path }})
```
