### ISSUE TITLE
Cannot bind argument to parameter 'Text' because it is an empty string.

### ISSUE THREAD

**Issue by Phiph** [microsoft/azure-pipelines-tasks#12081]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: here  

list here (V# not needed):  ServiceFabricComposeDeployV0
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines ?
    
   
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

    Account name: AccessArchitecture
    Team project name: ArchitectureTeam
    Release 21
    url: https://dev.azure.com/AccessArchitecture/ArchitectureTeam/_releaseProgress?_a=release-environment-logs&releaseId=21&environmentId=21

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

  Agent name: 'Hosted Agent'
 Agent machine name: 'fv-az10'

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

When deploying my Docker Compose file via dev ops I'm getting an error : [error]Cannot bind argument to parameter 'Text' because it is an empty string.

I've tried making my compose file as basic as possible to reduce variance, and even resorted to a single container deployment

Docker compose : 

```
version: '3.4'

services:
  sql.database:
    container_name: sql-server-db
    image: microsoft/mssql-server-windows-express
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"

networks:
  default:
    external:
      name: nat
```

### Task logs

 
[ReleaseLogs_21.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4026001/ReleaseLogs_21.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
