### ISSUE TITLE
HelmDeploy@0 unknown flag: --wait with helm v3.0.2

### ISSUE THREAD

**Issue by thijslimmen** [microsoft/azure-pipelines-tasks#12094]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Image: ubuntu-latest
Agent: Hosted Agent

## Issue Description

HelmDeploy@0 not working with the latest version of Helm 3.0.2. error `unknown flag: --wait`

Current azure-pipelines.yaml:

``` 
variables: 
  vmImageName: 'ubuntu-latest' 

 stages: 
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: HelmInstaller@1
      displayName: Helm installer
      inputs: 
        helmVersionToInstall: latest
    - task: HelmDeploy@0
      displayName: Helm init
      inputs:
        command: init
        connectionType: 'None'
        upgradetiller: false
        waitForExecution: false
        arguments: --client-only
```

## Troubleshooting
Run the given yaml in the pipeline

### Error logs

```Starting: Helm init

Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.162.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/helm-deploy
==============================================================================
/opt/hostedtoolcache/helm/3.0.2/x64/linux-amd64/helm init --wait --client-only
Error: unknown flag: --wait

[error]Error: unknown flag: --wait

Finishing: Helm init
```
