### ISSUE TITLE
[XamariniOS] missing methods when building with XamariniOS task

### ISSUE THREAD

**Issue by bruzkovsky** [microsoft/azure-pipelines-tasks#12099]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XamariniOSV2

## Environment

- Azure Pipelines

- Agent - Private
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

OS.Version: macOS Mojave 10.14.4
Agent.Version: 2.163.1

## Issue Description

When running a XamariniOS release build on the private host in Azure Pipelines, the resulting app does not start. It shows the splash screen for ~15 seconds until it gets killed by the iOS system. When performing a "manual" archive process on the same machine via VisualStudio "Pair to Mac.." feature, the app is running normally.

After some investigation, we found that one of our .dlls in the "Pipelines Package" is different from the "Manual Package". It seems that some kind of optimization happened on this .dll, as you can see in the following screenshots, that a method implementation is missing (exactly the part that would show the first screen of the app):

![dll from Pipelines Package](https://user-images.githubusercontent.com/10390959/71981659-1c675680-3223-11ea-905f-681dcce21d9e.png)
dll from "Pipelines Package" -> missing

![image](https://user-images.githubusercontent.com/10390959/71981729-415bc980-3223-11ea-8f48-c62dd1c97557.png)
dll from "Manual Package" -> correct

task settings:
```
- task: XamariniOS@2
  inputs:
    solutionFile: '$(projectPath)/$(projectFile)'
    configuration: '$(buildConfiguration)'
    clean: true
    packageApp: true
    # This value is set by the InstallAppleCertificate task
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    # This value is set by the InstallAppleProvisioningProfile task
    signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
    # create a binary log for MSBuild Log Viewer
    args: '/bl'
```

### Task logs

here is the binary log:

[msbuild.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4035486/msbuild.zip)

and also in text format:

[log_12_422.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4035504/log_12_422.zip)

### Logs from manual build

here are the logs from the manual build, which produces a working app:

[msbuild_manual.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4054881/msbuild_manual.zip)
