### ISSUE TITLE
Caching NPM modules

### ISSUE THREAD

**Issue by jayoungers** [microsoft/azure-pipelines-tasks#12121]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Cache@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted or Private: 
    
    - windows-2019

## Issue Description

I'm attempting to add Cache@2 to our pipeline, and everything appears to be succeeding as far as I can tell (both the Cache task and post-job:Cache task); however, either the cache is not saving anything or it's not being used.

Here's the relevant configuration:

```yaml
pool:
  name: Azure Pipelines
variables:
  npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x

- task: Cache@2
  displayName: 'Cache npm'
  inputs:
    key: 'npm | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/WebGui/package-lock.json'
    path: '$(npm_config_cache)'
    restoreKeys: |
     npm | "$(Agent.OS)"
     npm

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: ci
    workingDir: WebGui
    verbose: false
```

Is there something obvious I'm missing in terms of ordering, or another setting?

The cache hits and downloads 129.6mb of data (although looking locally at my application node_modules folder, it's at 373mb), but the `npm ci` (or `npm install`) task takes about the same amount of time prior to the cache step being added: around 5 minutes

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
