### ISSUE TITLE
NuGetToolInstallerV1 cannot download preview releases

### ISSUE THREAD

**Issue by krokofant** [microsoft/azure-pipelines-tasks#12169]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetToolInstallerV1

## Environment
Azure Pipeline - Microsoft-hosted agent
Running on the windows pool `windows-2019`

## Issue Description
Trying to install the nuget preview with NuGetToolInstallerV1 to workaround an issue with nuget and the credentials manager (https://github.com/microsoft/artifacts-credprovider/issues/91)

Task definition
```yml
- task: NuGetToolInstaller@1
      inputs:
        versionSpec: '5.5.0-preview1'
        checkLatest: true
```

This was tried with and without the checkLatest flag.

According to the docs here [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops) it should find available version listed in [this json file](https://dist.nuget.org/tools.json) but it seems it cannot find it.

### Task logs
```
##[section]Starting: NuGetToolInstaller
==============================================================================
Task         : NuGet tool installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 1.161.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/nuget
==============================================================================
##[error]No version was found which matches the input 5.5.0-preview1
ERR:Tool install failed: NuGet
##[error]The available versions are: 5.4.0; 5.3.1; 5.3.0; 5.2.0; 5.1.0; 5.0.2; 5.0.0; 4.9.4; 4.9.3; 4.9.2; 4.9.1; 4.8.2; 4.8.1; 4.7.3; 4.7.2; 4.7.1; 4.7.0; 4.6.4; 4.6.3; 4.6.2; 4.6.1; 4.6.0; 4.6.0-preview3; 4.5.3; 4.5.2; 4.5.1; 4.5.0; 4.4.3; 4.4.2; 4.4.1; 4.4.0; 4.4.0-preview3; 4.3.1; 4.3.0; 4.3.0-preview3; 4.3.0-preview1; 4.1.0; 4.0.0; 3.5.0; 3.4.4; 3.3.0; 3.2.0; 2.8.6
##[section]Finishing: NuGetToolInstaller

```
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by krokofant** [comment]
It seems that you can't download preview builds https://github.com/microsoft/azure-pipelines-tasks/blob/37aa86e212597cf797a3fa48cc12bf8a3a3da8f7/Tasks/Common/packaging-common/nuget/NuGetToolGetter.ts#L148
```typescript
let nugetVersions: INuGetVersionInfo[] = (await rest.get<INuGetVersionInfo[]>(versionsUrl, GetRestClientOptions())).result;
    // x.stage is the string representation of the enum, NuGetReleaseStage.Value = number, NuGetReleaseStage[NuGetReleaseStage.Value] = string, NuGetReleaseStage[x.stage] = number
    let releasedVersions: INuGetVersionInfo[] = nugetVersions.filter(x => x.stage.toString() !== NuGetReleaseStage[NuGetReleaseStage.EarlyAccessPreview]);
    let versionStringsFromDist: string[] = releasedVersions.map(x => x.version);

    let version: string = toolLib.evaluateVersions(versionStringsFromDist, versionSpec);
    if (!version)
    {
        taskLib.error(taskLib.loc("Error_NoVersionWasFoundWhichMatches", versionSpec));
        taskLib.error(taskLib.loc("Info_AvailableVersions", releasedVersions.map(x => x.version).join("; ")));
        throw new Error(taskLib.loc("Error_NuGetToolInstallerFailer", NUGET_TOOL_NAME));
    }
```

**Comment by GuillaumeSE** [comment]
this issue still exist any workaround for this?

**Comment by krokofant** [comment]
@GuillaumeSE Currently we download the executable and store it locally for each build.
```yaml
        - pwsh: |
            Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v5.5.0-preview1/nuget.exe" -OutFile .\.nuget\nuget.exe
          displayName: 'Install latest NuGet'
```

Changing the file I linked above is a pretty small thing but I don't know if removing the preview exclusion is an acceptable change.

Ping @jotaylo @magleaso

**Comment by GuillaumeSE** [comment]
@krokofant thank you for your tip!
I just saw that https://dist.nuget.org/tools.json have been updated with 5.5.0 as Release and now my CI can use it.
But I still face the an issue related there:
https://developercommunity.visualstudio.com/content/problem/953357/nuget-restore-step-is-failing-with-new-msbuild-ver.html

**Comment by krokofant** [comment]
@GuillaumeSE Well, then I can remove my workround 😁 

I always have a dedicated task for restoring the packages directly with nuget which does seem to work.

So before building with the VSBuild task:
```yaml
        - pwsh: |
            Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v5.5.0-preview1/nuget.exe" -OutFile .\.nuget\nuget.exe
          displayName: 'Install latest NuGet'
        - task: NuGetAuthenticate@0
        - pwsh: |
            .\.nuget\nuget.exe restore
          displayName: Restore packages
```
