### ISSUE TITLE
Build pipeline can't find any output files

### ISSUE THREAD

**Issue by LeonidasFettikus** [microsoft/azure-pipelines-tasks#12160]
I set up the following build pipeline:

```
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: '$(build.sourcesdirectory)\MySolution\MyProject\MyProject.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(project)'

- task: MSBuild@1
  inputs:
    solution: '$(project)'
    msbuildArguments: /r
    configuration: $(BuildConfiguration)

- task: CopyFiles@2
  inputs:
    contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'MyWebsite'
```

The pipeline works until I try to copy the files to the actual artifacts directory so it can be used for release pipelines. The problem is, I have no idea where the ouput folder actually is. My copy files task is copying 0 files to the artifacts staging directory so my publish task can't find any files to publish. This is annoying as I wasted 2 days on this and there is no documentation on what all those "d:\a\d\s" folders are.

Can anybody please tell me what am I missing here?
