### ISSUE TITLE
Pipeline caching cannot be used on pre-existing directories

### ISSUE THREAD

**Issue by jonhoo** [microsoft/azure-pipelines-tasks#12179]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `Cache@2`

## Environment
- Server - Azure Pipelines @ `jonhoo/jonhoo`, [definition 15](https://dev.azure.com/jonhoo/jonhoo/_build?definitionId=15&_a=summary)
- Agent - Hosted

## Issue Description

I want to cache a compiled file stored in a system-managed directory. For example:

```yaml
steps:
  - task: Cache@2
    inputs:
      key: cargo-deny | $(Agent.OS)
      path: /usr/share/rust/.cargo/bin
      cacheHitVar: CACHE_RESTORED
  - script: cargo install cargo-deny
    displayName: install cargo-deny
    condition: ne(variables.CACHE_RESTORED, 'true')
```

`cargo install` installs the requested program as `/usr/share/rust/.cargo/bin/cargo-deny`. The directory `/usr/share/rust/.cargo/bin` is managed by the system, with the permissions:

```
drwxrwxrwx+ 2 root root 4096 Jan 20 20:11 bin
```

It is also not empty by default, but instead includes some pre-installed (`root`-owned) files. Storing the cache works just fine with the task definition above, but restoring the cache does not. It errors ([log](https://dev.azure.com/jonhoo/jonhoo/_build/results?buildId=359&view=logs&j=cd5d91b1-209d-59f2-f6df-ac82a1bfa66b&t=3e2f3f7d-d7e9-534c-ceee-f79fb6772d42)) with:

```
Information, Downloaded 0.0 MB out of 40.5 MB (0%).
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
```

This is presumably because the restore operation attempts to overwrite the entire `bin` directory, which it does not have permissions to do.

I attempted to set `path` to just the one file I would like to cache (`bin/cargo-deny`), but this fails when trying to store the cache ([log](https://dev.azure.com/jonhoo/jonhoo/_build/results?buildId=362&view=logs&j=7fca7664-303d-57bd-3c0e-d74ef7cdeb09&t=537df50c-51ee-4989-a110-51c3fb2157e0)) with

```
##[error]Please specify path to a directory, File path is not allowed. /usr/share/rust/.cargo/bin/cargo-deny is a file.
```

My current workaround is to prefix the cache task with
```yaml
 - script: sudo rm -r /usr/share/rust/.cargo/bin
```
But that does not feel like it should be necessary?
