### ISSUE TITLE
Unable to specify managementgroupid in AzureResourceManagerTemplateDeployment@3

### ISSUE THREAD

**Issue by yesoreyeram** [microsoft/azure-pipelines-tasks#12186]
I am trying to deploy policies at management group level using azure devops AzureResourceManagerTemplateDeployment@3 task . But the task always deploys to root tenant management group. not the sub group. I couldn't find a documentation which speicifies where to specify `managementGroupId`

```

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: Management Group
              azureResourceManagerConnection: myspn_service_connection
              location: North Europe
              templateLocation: Linked artifact
              managementGroupId: mymgmtgroup-nonprod
              csmFile: $(System.DefaultWorkingDirectory)/arm-templates/policies_definition_managent_group_level.json
              deploymentMode: 'Incremental'
```
