### ISSUE TITLE
Java Tool Installer fails with bogus error

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#12200]
*Type*: **Bug**
**Enter Task Name**: **Java Tool Installer**

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: **Dev17.M153.3**

- Agent - **Private**
    
Property | Value
-- | --
Agent.Version | 2.153.1
Agent.OS | Windows_NT

## Issue Description

Java Tool Installer succeeds on the first build, subsequent builds fail:
```
##[section]Starting: JavaToolInstaller
==============================================================================
Task         : Java tool installer
Description  : Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME
Version      : 0.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/java-tool-installer
==============================================================================
Retrieving the JDK from local path.
Creating destination folder: C:\java
##[error]UNKNOWN: unknown error, stat '\\devstatic\ToolInstallationsForAzureDevOps\server-jre-8u231-windows-x64.tar.gz'
##[error]UNKNOWN: unknown error, stat '\\devstatic\ToolInstallationsForAzureDevOps\server-jre-8u231-windows-x64.tar.gz'
##[section]Finishing: JavaToolInstaller
```

### Task logs

[logs_684527.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4107057/logs_684527.zip)
[Build 1.0.20023.18-Main.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4107058/Build.1.0.20023.18-Main.zip)

**Comment by MarkKharitonov** [comment]
To make clear - the very first build using the task passes. The rest fail.

**Comment by sdobrodeev** [comment]
Hi @MarkKharitonov! I tried to reproduce this. Partially successful, but the error message is different from what is contained in the description. Could you please provide the content of your azure-pipelines.yml file? It was also noticed that such an error message occurs when there is no access to the source archive with Java. Could you make sure that the file is available at the task execution moment?

**Comment by MarkKharitonov** [comment]
I have worked around the problem by copying the zip file locally. The code I finally use is this:
```
steps:
- task: CopyFiles@2
  displayName: 'Copy JRE zip'
  name: CopyJREZip
  inputs:
    SourceFolder: '\\$(fileShareServer)\ToolInstallationsForAzureDevOps'
    Contents: 'server-jre-8u231-windows-x64.tar.gz'
    TargetFolder: '$(TEMP)'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '$(TEMP)\server-jre-8u231-windows-x64.tar.gz'
    jdkDestinationDirectory: '$(Build.ArtifactStagingDirectory)\java'
    cleanDestinationDirectory: false
```
I do not have cycles to investigate it any further.
