### ISSUE TITLE
Test Fails but vsTest task passes

### ISSUE THREAD

**Issue by abhikmitra** [microsoft/azure-pipelines-tasks#12210]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2  

## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Internal Microsoft. 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: VS2019

## Issue Description
So , I am running my unit tests in parallel Strategy (4 workers). Even when multiple test fails , the overall job still passes and the build shows successful. Here is the config
Job Configuration
```
  strategy:
    parallel: 4
```
Task configuration
```yaml
- task: VSTest@2
  displayName: 'Integration Test'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: $(TestAssembly)
    testAssembly: $(TestAssembly)
    runInParallel: True
    runSettingsFile: $(RunSettingsFileEnterprise)
    testFiltercriteria: '${{ parameters.testFilter }}'
    codeCoverageEnabled: True
    vsTestVersion: 'latest'
    rerunFailedTests: false
    rerunFailedTestCasesMaxLimit: 10
    rerunMaxAttempts: 3
    #distributionBatchType: 'basedOnExecutionTime'
    #batchingBasedOnExecutionTimeOption: 'autoBatchSize'
    continueOnError: false
```
Now if I remove strategy: parallel from the job ,  the same task starts to fail on failures. By the way in both cases , in the Test run Explorer , the failed tests are properly bubbled. I can see my passed and failed tests.

### Task logs

In the case ,where the task fails but job Succeeds
![image](https://user-images.githubusercontent.com/4750072/73117883-58642080-3f72-11ea-9adf-3be4660c9c5a.png)

In the case ,where the task fails but job also fails , parallelization disabled
![image](https://user-images.githubusercontent.com/4750072/73117901-a9741480-3f72-11ea-9b8c-7199b745bc1e.png)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
