### ISSUE TITLE
KubernetesManifest multi-container image replacment

### ISSUE THREAD

**Issue by kdelorey** [microsoft/azure-pipelines-tasks#12238]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest@0

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Ubuntu-18.04 2.164.6

## Issue Description

Recently the KubeManifest@0 task seems to have broken in regards to container image replacement. It seems to be specifically related to having more than one image that needs to be replaced.

```
- task: KubernetesManifest@0
  displayName: Deploy Something
  inputs:
    namespace: default
    manifests: ./TheDeploymentFolder/*.yaml
    containers: |
      whatever.azurecr.io/somerepo/A:$(tag)
      whatever.azurecr.io/somerepo/B:$(tag)
```

Using the example above, the deploy will replace reference to container A with container B.
