### ISSUE TITLE
File transform task: config hierarchy delimiter is fixed '.'

### ISSUE THREAD

**Issue by majorimi** [microsoft/azure-pipelines-tasks#12235]
I'm trying to use **File transform task in Azure Pipelines**. And I'm **providing variables from Azure App Configurations.** By using AzureAppConfiguration@2 task to fetch config values dynamically.
It works fine however I'm facing issues with hierarchical config values. In order to use App Configurations in .NET Core Apps I need to use delimiters (colon ":"). E.g. **Settings:User:Id** In this case my .NET Core App works fine.
The problem is in Azure Pipelines variables also loaded with ":". However according the documentation it must be (dot "."). So File transform task fails..
If I change my variables in App Configurations to use "." delimiters File transform works. However my .NET Core App will fail...

But I would like to use my configs in both DevOps and .NET Core as well. One very bad solution is to duplicate my Keys and Values... But it is not maintainable.

Best thing would be to add a parameter which allows us to specify a delimiter for hierarchical parameters. E.g.: "jsonDelimiter"

```
 - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/src/'
        xmlTransformationRules: 
        * jsonDelimiter: ":"
        jsonTargetFiles: |
          appsettings.json
```
