### ISSUE TITLE
HelmDeploy@0 should not require a service connection parameter

### ISSUE THREAD

**Issue by ResDiaryLewis** [microsoft/azure-pipelines-tasks#12231]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

The `HelmDeploy` task requires both a `connectionType` and `kubernetesServiceEndpoint` when these are not always necessary. For example, in a pull request linting build:

```yaml
    - task: HelmInstaller@1
      displayName: Helm installer
      inputs:
        helmVersionToInstall: "$(helmVersion)"

    - task: HelmDeploy@0
      displayName: Helm init
      inputs:
        command: init
        connectionType: $(kubernetesConnectionType)
        kubernetesServiceEndpoint: $(kubernetesClusterName)
        arguments: --client-only

    - task: HelmDeploy@0
      displayName: Helm dependency build
      inputs:
        command: dependency
        connectionType: $(kubernetesConnectionType)
        kubernetesServiceEndpoint: $(kubernetesClusterName)
        arguments: build charts/$(helmChartName)

    - task: HelmDeploy@0
      displayName: Helm lint
      inputs:
        command: lint
        connectionType: $(kubernetesConnectionType)
        kubernetesServiceEndpoint: $(kubernetesClusterName)
        arguments: charts/$(helmChartName)
```

We want to:

- Install Helm locally
- Initialise it as client-only _(no Tiller component)_
- Build the dependencies
- Lint the chart

But I need to hook the pipeline into a Kubernetes cluster as a service connection, this connection is verified even when the task won't use it.

**Comment by vithati** [comment]
@ResDiaryLewis , You can specify connectionType: None. It will validate connection type.

**Comment by ResDiaryLewis** [comment]
@vithati I'll give that a shot then, sounds like exactly what we need. Cheers 👍
I think this is worth documenting [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops) too.

**Comment by ResDiaryLewis** [comment]
@vithati I've just tried it like this:

```yaml
    - task: HelmInstaller@1
      displayName: Helm installer
      inputs:
        helmVersionToInstall: "$(helmVersion)"

    - task: HelmDeploy@0
      displayName: Helm init
      inputs:
        command: init
        connectionType: None
        kubernetesServiceEndpoint: None
        arguments: --client-only

    - task: HelmDeploy@0
      displayName: Helm dependency build
      inputs:
        command: dependency
        connectionType: None
        kubernetesServiceEndpoint: None
        arguments: build charts/$(helmChartName)

    - task: HelmDeploy@0
      displayName: Helm lint
      inputs:
        command: lint
        connectionType: None
        kubernetesServiceEndpoint: None
        arguments: charts/$(helmChartName)
```

and received this error:

```txt
There was a resource authorization issue: "The pipeline is not valid. Job Build: Step HelmDeploy1 input kubernetesServiceEndpoint references service connection None which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Build: Step HelmDeploy2 input kubernetesServiceEndpoint references service connection None which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
```
