### ISSUE TITLE
Xcode@5 Code Signing Error when building a project with embedded framework that does not support manual signing

### ISSUE THREAD

**Issue by ericallam** [microsoft/azure-pipelines-tasks#12263]
## Required Information

*Type*: Bug
**Task Name**: Xcode@5  

## Environment

All

## Issue Description

`Xcode@5` fails to build an Xcode project that has multiple targets that have mixed signing needs, resulting in a Code Signing Error with this format:

```
<Framework> does not support provisioning profiles. <Framework> does not support provisioning profiles, but provisioning profile <Provisioning Profile Name> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
```

In my case, I am trying to build an Xcode project produced by Unity 2019.3, which includes a new `UnityFramework` that does not support manual code signing.

According to the [Unity Documentation](https://docs.unity3d.com/2019.3/Documentation/Manual/StructureOfXcodeProject.html), a new set of command line arguments for `xcodebuild` are to be used to target manual code signing to the main `Unity-iPhone` target only, and leave `UnityFramework` to be able to signed automatically.

Using `PROVISIONING_PROFILE_APP` and `PROVISIONING_PROFILE_SPECIFIER_APP` instead of `PROVISIONING_PROFILE` and `PROVISIONING_PROFILE_SPECIFIER` in the `xcodebuild` command fixes this issue.

Adding a "Custom Provisioning Profile Argument Suffix" parameter to `Xcode` under the Signing action would allow this issue to be fixed. See [this blob post](https://lyricsboy.github.io/2016/11/30/xcode-8-automatic-signing-ci/) for more information about how the suffixes are used in building Xcode projects with multiple targets.

**Comment by fortunacio** [comment]
Hi @ericallam did u find any solution?

**Comment by fortunacio** [comment]
I manage to solve this by creating a custom task to provide "Custom Provisioning Profile Argument Suffix" to the Xcode Build task. If anyone wants the task let me know so I can share it. 

Cheers.

**Comment by Paul-ICS** [comment]
Hi @fortunacio,
I'm getting the same problem as this with my Ionic project, could you share what you did to make it sign and build?
Thanks,
Paul

**Comment by fortunacio** [comment]
Yes, of course, can you give me the name of your organization so I share
the task?

**Comment by Paul-ICS** [comment]
My DevOps org is called: ics-development

Thanks, 
Paul

**Comment by fortunacio** [comment]
Done. if u are using YAML pipeline u need to replace the Xcode@5 task for
the new one
(Wololo.build-release-wololo-task.custom-build-release-task.WololoBuild@0)
which has exactly the same functionality but with a new input
(provisioningProfileSuffix) so for use it u need to fill the suffix under
input task section, eg (provisioningProfileSuffix: APP).
if u are using the classic visual editor u can find the extension under the
Utility tab and the provisioningProfileSuffix option under Advance options
of the task.
 Cheers, Federico.

**Comment by Paul-ICS** [comment]
Just a quick update, we tried your task and specified the suffix of APP, but it didn't seem to make any difference to the build. I also tried it locally and couldn't get xcodebuild to do anything with PROVISIONING_PROFILE_APP. It did the same as if it wasn't specified.

Anyway, we found that using the original Xcode build task and specifying an argument of "CODE_SIGNING_ALLOWED=No" made it all build and sign correctly.

Thanks for you help.

**Comment by pandey-laxman** [comment]
@Paul-ICS can you please be more specific about where you specified **"CODE_SIGNING_ALLOWED=No"** . is it in task: Xcode@5 ? on somewhere in xcode project.
I have some embedded framework for those getting below error. 

**error: Domain does not support provisioning profiles. Domain does not support provisioning profiles, but provisioning profile xxxxx has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Domain' from project 'xxxxx')**

Can you please provide more details to fix this issue? 
I have been spent hours to fix this issue but still no luck.

**Comment by Paul-ICS** [comment]
@pandey-laxman, sorry missed this email!

It needs to go in the arguments field in the Xcode task.
This is how my Xcode task looks (in yaml):
```
          - task: Xcode@5
            inputs:
              actions: 'build'
              xcWorkspacePath: '**/myproj.xcworkspace'
              scheme: 'myproj'
              xcodeVersion: 'specifyPath'
              xcodeDeveloperDir: '/Applications/Xcode_11.1.app'
              packageApp: true
              exportPath: 'output/$(SDK)/$(BuildConfiguration)'
              exportOptions: 'plist'
              exportOptionsPlist: 'pipelines/export.debug.plist'
              signingOption: 'manual'
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
              args: 'CODE_SIGNING_ALLOWED=No'
```

**Comment by pandey-laxman** [comment]
@Paul-ICS  Thank you very much, Now I am getting different error couldn't find path for **exportOptionsPlist: 'pipelines/export.debug.plist'**.

**Comment by imzahahs** [comment]
Does anyone know why "CODE_SIGNING_ALLOWED=No" works? I can't find any docs regarding this. (I used this for automating iOS builds for Unity 2020 via Jenkins).

**Comment by craigktreasure** [comment]
For me, `CODE_SIGNING_ALLOWED=No` allowed my build to complete, but I couldn't use the resulting app because it wasn't signed. So, I don't believe that's a good solution.

**Comment by EvilCreamsicle** [comment]
> I manage to solve this by creating a custom task to provide "Custom Provisioning Profile Argument Suffix" to the Xcode Build task. If anyone wants the task let me know so I can share it.
> 
> Cheers.
@fortunacio 
I would like this custom task, if it is still available. Please and thank you.

**Comment by fortunacio** [comment]
@EvilCreamsicle Yes, for sure, can you give me the name of your organization?

**Comment by EvilCreamsicle** [comment]
> @EvilCreamsicle Yes, for sure, can you give me the name of your organization?

my organization is 'powerley-development',
Thanks

**Comment by datran-msft** [comment]
We are currently hitting this issue with Unity 2019 too. 

We signed manually on Unity 2018 as automatic signing is not an option for us, but updating to Unity 2019 is causing the `<Framework> does not support provisioning profiles.` 

Setting `CODE_SIGNING_ALLOWED=No` doesn't address the issue since we still need to sign it.

Is there a workaround? Is there a task we can use that has supports for the suffixes?
Thanks

**Comment by kmikkel** [comment]
We ran into this problem too after upgrading from Unity 2018 to Unity 2020. Haven't found a workaround yet.

**Comment by kmikkel** [comment]
I have been struggling with this issue. Here are my findings (pretty much the same conclusion as in the original post).

When running this Xcode task:
```
- task: Xcode@5
  displayName: 'Xcode build Unity-iPhone'
  inputs:
    xcWorkspacePath: 'iOSBuild/Unity-iPhone.xcworkspace'
    scheme: 'Unity-iPhone'
    sdk: 'iphoneos'
    packageApp: true
    archivePath: iOSBuild
    exportPath: $(Build.ArtifactStagingDirectory)/ios
    signingOption: 'manual'
    signingIdentity: '<SigningIdentity>'
    args: 'PROVISIONING_PROFILE_APP=<ProvisioningProfileUuid> PROVISIONING_PROFILE_SPECIFIER_APP=<ProvisioningProfileName>'
    useXcpretty: false
  condition: succeeded()
```

it generates this xcodebuild command, adding empty entries for PROVISIONING_PROFILE and PROVISIONING_PROFILE_SPECIFIER:

`
/usr/bin/xcodebuild -sdk iphoneos -configuration $(Configuration) -workspace /Users/runner/work/1/s/iOSBuild/Unity-iPhone.xcworkspace -scheme Unity-iPhone build PROVISIONING_PROFILE_APP=<ProvisioningProfileUuid> PROVISIONING_PROFILE_SPECIFIER_APP=<ProvisioningProfileName> CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=<SigningIdentity> PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=
`

The empty entries makes the xcodebuild command fail with the error reported in the initial post. 
So if the Xcode task could generate a xcodebuild command without adding the empty entries the problem could be fixed.

**Comment by eirikwah** [comment]
Although workarounds are described above, it would be nice is this issue would be fixed in this official repo. Are there any updates? Is this issue prioritized, and/or will it be?

**Comment by sewerow** [comment]
Are there any updates. I have the same problems. And I need to implement custom scripts, no other options doesn't fit

**Comment by trevorbye** [comment]
Wish msft had more customer empathy with this kind of thing. Yes, this task isn't specific to Unity, but it _is_ specific to xcode, and Unity is a common framework to build in xcode. I agree it probably doesn't warrant an implementation change on your side, but even mentioning something in your docs about how to work around this would be helpful because it is still an issue, rather than simply saying "not our problem".

The original solution of using `PROVISIONING_PROFILE_APP` and `PROVISIONING_PROFILE_SPECIFIER_APP` here worked for me, and everything builds/signs successfully. I ended up just using a bash script because at the end of the day this task is really only useful for learning what `xcodebuild` runs under the hood... because even passing manual args doesn't work correctly as you can see above in some other replies. 

Here is the relevant section of the pipeline to show more explicitly how to work around this. See [this doc on signing](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops#signing-and-provisioning) if you need context on how to use/setup the `InstallAppleCertificate@2` and `InstallAppleProvisioningProfile@1` tasks.

```yaml
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(certFileInSecureLibrary)'
    certPwd: '$(cert_password)'
    keychain: temp
    deleteCert: true
 
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(yourProfileFile)'
    removeProfile: true

- task: Bash@3
  inputs:
    targetType: inline
    script: >
      /usr/bin/xcodebuild
      -sdk iphoneos
      -configuration Release
      -project $(xcodeRoot)/Unity-iPhone.xcodeproj
      -scheme Unity-iPhone
      build
      CODE_SIGN_STYLE=Manual
      CODE_SIGN_IDENTITY='$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      PROVISIONING_PROFILE_APP=$(APPLE_PROV_PROFILE_UUID)
      PROVISIONING_PROFILE_SPECIFIER_APP=your-provisioning-profile-name
      CONFIGURATION_BUILD_DIR=$(xcodeRoot)/build-output/
```

In this example, the variable `$(xcodeRoot)` is set to `$(Pipeline.Workspace)/s` because in our case we aren't cloning a repo in this job, we pull down the Unity xcode project files from a preceding job that runs on a windows VM, and manually put it in the dir where AzDo normally expects your repo root to be e.g. `/Users/runner/work/1/s/`.

Additionally, because we were building the xcode project files on a windows box, there is one other task we needed. There are two shell scripts in the xcode project root that were getting permission denied errors, so you can simply just add a bash task to chmod them first before running your `xcodebuild` script:

```yaml
- task: Bash@3
  displayName: 'chmod shell scripts in xcode project root'
  inputs:
    targetType: inline
    script: |
      chmod +x $(xcodeRoot)/MapFileParser.sh
      chmod +x $(xcodeRoot)/process_symbols.sh
```

**Comment by rafek** [comment]
@trevorbye I did exactly as you advised - with the only difference that I'm building `.xcworkspace` rather than .`xcodeproj`: 

```
- task: Bash@3
  inputs:
    targetType: inline
    script: >
      /usr/bin/xcodebuild
      -sdk iphoneos
      -configuration Release
      -workspace $(Build.BinariesDirectory)/Unity-iPhone.xcworkspace
      -scheme Unity-iPhone
      build
      CODE_SIGN_STYLE=Manual
      CODE_SIGN_IDENTITY='$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      PROVISIONING_PROFILE_APP='$(APPLE_PROV_PROFILE_UUID)'
      PROVISIONING_PROFILE_SPECIFIER_APP=my-prov-profile-name
      CONFIGURATION_BUILD_DIR=$(Build.BinariesDirectory)/build_output
```

and it still tries to `CodeSign` UnityFramework.

**Comment by trevorbye** [comment]
> @trevorbye I did exactly as you advised - with the only difference that I'm building `.xcworkspace` rather than .`xcodeproj`:
> 
> ```
> - task: Bash@3
>   inputs:
>     targetType: inline
>     script: >
>       /usr/bin/xcodebuild
>       -sdk iphoneos
>       -configuration Release
>       -workspace $(Build.BinariesDirectory)/Unity-iPhone.xcworkspace
>       -scheme Unity-iPhone
>       build
>       CODE_SIGN_STYLE=Manual
>       CODE_SIGN_IDENTITY='$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
>       PROVISIONING_PROFILE_APP='$(APPLE_PROV_PROFILE_UUID)'
>       PROVISIONING_PROFILE_SPECIFIER_APP=my-prov-profile-name
>       CONFIGURATION_BUILD_DIR=$(Build.BinariesDirectory)/build_output
> ```
> 
> and it still tries to `CodeSign` UnityFramework.

I realized that what I posted did not end up as the final solution. Instead of building in one step, you need to do two separate bash scripts invoking xcodebuild; one creates an archive, and the next exports that archive. you also need to create an exportoptions.plist file to reference as well. here is what the relevant parts of the pipeline look like:

```
variables:
  plistBuddy: '/usr/libexec/PlistBuddy' # default macos utility for building plist files
  exportOptions: '$(Pipeline.Workspace)/exportOptions.plist'
  xcodeBundleId: 'com.yourpackagename.foo'
  appleProvProfileName: 'name-of-provisioning-profile' # this is just the string name you give the profile when you create it
  appleTeamId: 'your-apple-team-ID' # this value isn't secret e.g. it's useless on it's own, can find in app store connect

  - job: buildXcode
    pool:
      vmImage: 'macOS-latest'
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: 'Get XCode project files'
      name: xCodeProjectFiles
      inputs:
        source: current
        artifact: 'iOS_XCodeProject_BuildArtifact'
        path: $(xcodeRoot)/

    - task: Bash@3
      displayName: 'chmod shell scripts in xcode project root'
      inputs:
        targetType: inline
        script: |
          chmod +x $(xcodeRoot)/MapFileParser.sh
          chmod +x $(xcodeRoot)/process_symbols.sh

    # automatically fetches cert from library>secure files and installs in temp keystore
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '$(yourCertFileLocationRef)'
        certPwd: '$(yourCertFilePasswordRef)'
        keychain: temp
        deleteCert: true
    
    # automatically fetches profile from library>secure files
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: '$(yourProvProfileFile)'
        removeProfile: true

    - task: Bash@3
      displayName: 'Build exportOptions.plist file'
      inputs:
        targetType: inline
        script: |
          $(plistBuddy) -c "Add :compileBitcode bool false" $(exportOptions)
          $(plistBuddy) -c "Add :method string app-store" $(exportOptions)
          $(plistBuddy) -c "Add :provisioningProfiles dict" $(exportOptions)
          $(plistBuddy) -c "Add :provisioningProfiles:$(xcodeBundleId) string $(appleProvProfileName)" $(exportOptions)
          $(plistBuddy) -c "Add :signingCertificate string $(APPLE_CERTIFICATE_SIGNING_IDENTITY)" $(exportOptions)
          $(plistBuddy) -c "Add :signingStyle string manual" $(exportOptions)
          $(plistBuddy) -c "Add :stripSwiftSymbols bool true" $(exportOptions)
          $(plistBuddy) -c "Add :teamID string $(appleTeamId)" $(exportOptions)
          $(plistBuddy) -c "Add :thinning string &lt;none&gt;" $(exportOptions)

    - task: PublishPipelineArtifact@1
      displayName: 'Publish exportOptions.plist'
      condition: succeeded()
      inputs:
        targetPath: $(exportOptions)
        artifactName: ExportOptions_Plist

    - task: Bash@3
      displayName: 'Build Xcode Archive'
      inputs:
        targetType: inline
        script: >
          /usr/bin/xcodebuild
          -project $(xcodeRoot)/Unity-iPhone.xcodeproj
          -scheme Unity-iPhone
          -sdk iphoneos
          -configuration Release
          archive
          -archivePath $(xcodeRoot)/build-output/someFileName.xcarchive
          PROVISIONING_PROFILE_APP=$(APPLE_PROV_PROFILE_UUID)
          CODE_SIGN_IDENTITY='$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'

    - task: Bash@3
      displayName: 'Export Xcode Archive'
      inputs:
        targetType: inline
        script: >
          /usr/bin/xcodebuild
          -exportArchive
          -archivePath $(xcodeRoot)/build-output/someFileName.xcarchive
          -exportOptionsPlist $(exportOptions)
          -exportPath $(xcodeRoot)/build-output/

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Output Artifacts'
      condition: succeeded()
      inputs:
        targetPath: $(xcodeRoot)/build-output/
        artifactName: iOS_BuildArtifacts
```

this should result in an `.ipa` package in the dir where the last step publishes the build artifacts. hopefully this helps! will update my original comment to point to this one.
