### ISSUE TITLE
Git lfs/clean is not being respected per-job or through the resources element

### ISSUE THREAD

**Issue by TabithaLarkin** [microsoft/azure-pipelines-tasks#12301]
## Required Information

*Type*: Bug

**Task Name**: checkout/resources

## Environment
- Server - Azure Pipelines

Name: xceptor
Project: Xceptor
build id: 44504

- Agent (Private):

Version: 2.164.7
OS: Windows

## Issue Description
Setting either the resources section on git checkouts isn't respected.

```yml
resources:
- repo: self
  lfs: true
  clean: false
```

The above still does a clean on each of the jobs in the pipeline.

Setting the checkout step for each job seems to work for the clean (albeit seemingly inconsistently), but the lfs flag doesn't seem to be picked up correctly if you specify that.

```yml
- checkout: self
  clean: false
  lfs: true
```

This means that we're currently stuck having to enable lfs in the resources section and ignore the benefits of being able to set clean to false on our self-hosted agents.

### Task logs

[logs_44504.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4159968/logs_44504.zip)
