### ISSUE TITLE
The pwsh task breaks with multi-repo checkout

### ISSUE THREAD

**Issue by mitchdenny** [microsoft/azure-pipelines-tasks#12328]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell

## Environment
- Server - Azure Pipelines
- Agent - Hosted
    
## Issue Description

When using the **pwsh** task on with the multi-repo checkout feature I experience the following issues:

1. On Windows 2019 image, I get the error "##[error]Container path not found: 'd:\a\1\s'"
2. On Ubuntu 16.04 image, I get the error "##[error]No such file or directory"

For #1, the issue can be worked around by setting the workingDirectory. I haven't found a workaround for #2 yet.

**Comment by vtbassmatt** [comment]
@jtpetty @stephenmichaelf @jpricket FYI. Not sure who wants to take a crack at this one.

**Comment by jtpetty** [comment]
@mitchdenny  - This is quite possibly fixed in the latest agent, 2.164.8. Can you try that agent version? We are in the process of rolling this version out to all customers so you may not have gotten it automatically yet.

**Comment by mitchdenny** [comment]
Sorry the ```.8``` build doesn't fix it: 

Agent for this job:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=257527&view=logs&j=f80576d6-31b7-560d-8b9f-83fe28ca8786&t=88947367-a263-4838-a380-bd518b2c8198&l=4

Failure:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=257527&view=logs&j=f80576d6-31b7-560d-8b9f-83fe28ca8786&t=7ed5dfc6-5bd8-5180-ee3c-c917ed9782c4&l=9

Let me know if you don't have access, since we are in the MS tenant I can give you access.

**Comment by jtpetty** [comment]
@mitchdenny - Ok, for multi-repo checkouts, I think that it is expected that you have to explicitly
set the working directory since we do not create an "s" directory in this scenario. @jpricket - Please correct me if I am wrong with that statement.

I am curious why setting the working directory to either one of the repos you are populating or to the work directory itself does not fix the problem for both Windows and Ubuntu.

Can you set the work directory and rerun the Ubuntu pipeline with debug enabled and send me a link?

**Comment by mitchdenny** [comment]
Here is the repro on Ubuntu where even if I have a workingDirectory defined it still bombs out: 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=260112&view=logs&j=2e98f527-e589-587d-26d2-07597fe3ed5e&t=0f9c5414-019b-525a-288c-48b8db156974&l=9

FWIW, I don't think I should have to specify a working directory. There should always be some reasonable default. In the case of multi-checkout I would expect that to be Pipeline.Workspace/Agent.BuildDirectory. I thought that was the direction things where heading fro a consistency perspective anyway.

**Comment by mitchdenny** [comment]
THe snippet for the above build failure is:

```yaml
  - stage: AgentProblemRepro
    dependsOn: ${{parameters.DependsOn}}
    jobs:
      - job: PwshOnUbuntu
        steps:
          - checkout: azure-sdk-build-tools
            path: azure-sdk-build-tools
          - pwsh: |
              Write-Host Hello world
            workingDirectory: $(Agent.BuildDirectory)
```
