### ISSUE TITLE
Directory create permission denied to build

### ISSUE THREAD

**Issue by phatcher** [microsoft/azure-pipelines-tasks#12331]
# Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Bug*

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted: 

## Issue Description

I have a build pipeline on 'ubuntu-latest' which has a couple of tasks to restore then build a .NET Core solution

```
- task: DotNetCoreCLI@2
   inputs:
    command: 'restore'
    projects: $(projectPattern)
    feedsToUse: 'select'
    vstsFeed: $(nugetFeed)
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(projectPattern)
    arguments: '-c $(buildConfiguration) -p:Version=$(GitVersion.NugetVersionV2)'
```
This is a stable project and the last CI build ran in late November.  When it was run recently, the second task failed complaining about copying files

### Task logs

```
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/usr/bin/dotnet build /home/vsts/work/1/s/src/Foo.Api.Test/Foo.Api.Test.csproj -c Release -p:Version=0.2.3
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 522.08 ms for /home/vsts/work/1/s/src/Foo.Api.Test/Foo.Api.Test.csproj.
  Restore completed in 522.08 ms for /home/vsts/work/1/s/src/Foo.Api/Foo.Api.csproj.
  Restore completed in 93.92 ms for /home/vsts/work/1/s/src/Foo/Foo.csproj.
/usr/share/dotnet/sdk/3.0.102/Microsoft.Common.CurrentVersion.targets(1124,5): warning MSB3191: Unable to create directory "/build/Release/Foo.Api.Test/netcoreapp3.0/". Access to the path '/build/Release/Foo.Api.Test/netcoreapp3.0/' is denied. [/home/vsts/work/1/s/src/Foo.Api.Test/Foo.Api.Test.csproj]
```
The previous successful execution was using 2.158.1, so I was wondering if this was something to do with it or the upgrade to .NET Core 3.1 on the build agents?
