### ISSUE TITLE
Add `buildingTag` to task `Condition`

### ISSUE THREAD

**Issue by dakimaz** [microsoft/azure-pipelines-tasks#12383]
When specifying a `task` you can give it a `condition` for when to execute the `task`.

It would be very nice if `condition` would have a `buildingTag` so the given task only executes when the pipeline is building from a git tag commit.

Example:

```
  - task: ArtifactoryConan@1
    displayName: 'Conan Upload'
    condition: buildingTag
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      conanCommand: 'Upload'
      patternOrReference: 'package_pattern*'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
```
