### ISSUE TITLE
ACR DockerV2 not login in

### ISSUE THREAD

**Issue by Poil** [microsoft/azure-pipelines-tasks#12399]
## Required Information

*Type*: Bug

**Enter Task Name**: Docker@2

list here (V# not needed):  Docker

## Issue Description
With DockerV1, we can use a "Azure Resource Manager/Service Principal" to read and publish to an ACR registry. like that
```
              inputs:
                containerregistrytype: Azure Container Registry
                azureSubscriptionEndpoint: $(SERVICE_CONNECTION_NAME)
                azureContainerRegistry: $(ACR_NAME).azurecr.io
                imageName: $(DOCKER_IMAGE_NAME):$(Build.BuildNumber)
                includeLatestTag: true
```

In V2, we need to declare a Docker Registry service connection for the ACR
```
              inputs:
                containerRegistry: $(ACR_NAME) # Not working need $(ACR_SERVICE_CONNECTION_NAME)
                repository: $(DOCKER_IMAGE_NAME)
                azureSubscriptionEndpoint: $(SERVICE_CONNECTION_NAME)
                tags: |
                   $(Build.BuildNumber)
                   latest
```
Best regards,
Benjamin DUPUIS
