### ISSUE TITLE
AzureFunctionAppV1 constantly fails for Function App on Linux

### ISSUE THREAD

**Issue by kamil-mrzyglod** [microsoft/azure-pipelines-tasks#12429]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionAppV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines
    
    - thecloudtheory, LicznikNET, LicznikNET(20200226.1)

- Agent - Hosted or Private: 
    
    - Hosted, Azure Pipelines

## Issue Description

Most of the time(let's say 8/10 tries), when I try to deploy Azure Functions V3, I end up with code deployed but the overall build failed due to Zip Deploy error I cannot debug. I'm deploying my code using the following task description:
```
- task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'M'
              appType: 'functionAppLinux'
              appName: 'liczniknetvnext-dev-euw-functionapp'
              package: '$(Pipeline.Workspace)/functions/bin/Release/netcoreapp3.0/publish'
              runtimeStack: 'DOCKER|mcr.microsoft.com/azure-functions/dotnet:3.0-appservice'
```

### Task logs

Logs attached.

### Error logs

##[error]Failed to deploy web package to App Service.
##[error]To debug further please check Kudu stack trace URL : https://$liczniknetvnext-dev-euw-functionapp:***@liczniknetvnext-dev-euw-functionapp.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4261263/logs.zip)
