### ISSUE TITLE
Kubernetes@1 - Support for admin credentials?

### ISSUE THREAD

**Issue by heoelri** [microsoft/azure-pipelines-tasks#12427]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Kubernetes@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

We've a Kubernetes Cluster with RBAC enabled and Azure AD Integration. We're now trying to apply a Kubernetes manifest using a `Kubernetes@1` task:

```YAML
- task: Kubernetes@1 # Deploy Azure Container Insights Configuration (for Live Monitoring)
  displayName: 'Kubernetes - Configure Container Insights'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(serviceConnection)
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: 'kubecluster-aks-$(environment)'
    command: 'apply'
    arguments: '-f $(Pipeline.Workspace)/$(armArtifactName)/k8sconfig/aks.monitoring.yaml'
  enabled: true
```

We're aware that all kubectl tasks that are executed as a non-admin are now requiring an interactive login. And this is what happens next:

```
Starting: Kubernetes - Configure Container Insights
==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.164.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/kubernetes
==============================================================================
Prepending PATH environment variable with directory: /opt/hostedtoolcache/kubectl/1.15.7/x64
/opt/hostedtoolcache/kubectl/1.15.7/x64/kubectl apply -f /home/vsts/work/1/artifact/k8sconfig/aks.monitoring.yaml -o json
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XYZXYZXYZ to authenticate.
```

Is there a way to force `Kubernetes@1` to use the admin credentials to override rbac?

I'd prefer using the native `Kubernetes@1` task instead of doing it manually with e.g. `AzureCLI@1`.
