### ISSUE TITLE
Nodetool fails with 7zr.exe failed with return code: 3221225781

### ISSUE THREAD

**Issue by jrr** [microsoft/azure-pipelines-tasks#12446]
Nodetool is failing in my job running on Windows Docker.

**Nodetool**: 0.160.0 
**Node.js**: v12.16.1
**Container**: `mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809`

Output:
```
Downloading: https://nodejs.org/dist/v12.16.1/node-v12.16.1-win-x64.7z
Extracting archive
C:\__w\_tasks\NodeTool_31c75bbb-bcdf-4706-8d7c-4da6a1959bc2\0.160.0\7zr.exe x -bb1 -bd -sccUTF-8 C:\__w\_temp\4271bb50-8be1-45f3-8433-17c6da3ecddb
##[error]C:\__w\_tasks\NodeTool_31c75bbb-bcdf-4706-8d7c-4da6a1959bc2\0.160.0\7zr.exe failed with return code: 3221225781
```

Googling around, it seems like maybe the nanoserver-1809 docker image is missing some necessary runtime libraries for `7zr.exe` ([link](https://stackoverflow.com/questions/53431448/a-dockerized-c-windows-console-application-exited-with-code-3221225781)).

I'm using official [.NET Docker Images](https://hub.docker.com/_/microsoft-dotnet-core-sdk/); are there other recommended images for use in Azure Pipelines?

Here's the top of my yaml:

```yaml
strategy:
  matrix:
    linux:
      vmImageName: "ubuntu-16.04"
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    windows:
      vmImageName: "windows-2019"
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809

pool:
  vmImage: $(vmImageName)

container: $[ variables['containerImage'] ]

variables:
  node_version: 12

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
```

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**: bug

**Enter Task Name**: NodeToolV0

## Environment
- Server - Azure Pipelines
    
I'm willing to share the account / project / build information privately with a Microsoft employee if that'd be helpful.

_- Agent - Hosted or Private:_

**Hosted**
    
_- If using Hosted agent, provide agent queue name:_

I'm not sure how to check the "queue name". Is this output sufficient?:

```
Pool: <a class='is-link' href='/(redacted)/a7be138b-8ee7-4628-bd16-53eb9fb690c2/_settings/agentqueues?poolId=&queueId=2693'>Azure Pipelines</a>
Image: windows-2019
Agent: Hosted Agent
Started: Today at 10:40 PM
Duration: 1m 32s
```

I'm skipping the rest of the issue template, as I strongly suspect this is more about the interaction of `NodeTool` and the `nanoserver-1809`-based Docker image. I'll gather more details if it'd help!
