### ISSUE TITLE
Can´t publich code coverage resuslts

### ISSUE THREAD

**Issue by Q-efx** [microsoft/azure-pipelines-tasks#12467]
## Note  

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question or bug

**Enter Task Name**: 
DotNetCoreCLI@2 (test)
PublishCodeCoverageResults@1

## Environment
Azure Pipelines

- Agent - Hosted or Private: 
Hosted 

## Issue Description
Trying to publish code coverage. The file gets created, but can´t be published.

### Task logs
YAML
```
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET'
      inputs:
        command: test
        projects: '**/DevOpsDemo.E2ETest/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:threshold=80 /p:thresholdType=line /p:thresholdStat=total --logger trx --collect:"XPlat Code Coverage" '
      condition: succeededOrFailed()
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '**/coverage.cobertura.xml'
        pathToSources: 'DevOpsDemo'
        failIfCoverageEmpty: true
```
Files get created:
```
Results File: d:\a\_temp\VssAdministrator_fv-az28_2020-03-03_09_53_50.trx
Attachments:
  d:\a\_temp\5d6b79a4-2d51-4972-957b-a105c4d600cd\coverage.cobertura.xml
```
When I try to publish the code coverage:
`##[error]No code coverage results were found to publish.`
