### ISSUE TITLE
NuGet.Build.Tasks.Pack.targets(198,5): error : The filename, directory name, or volume label syntax is incorrect. : 

### ISSUE THREAD

**Issue by captmomo** [microsoft/azure-pipelines-tasks#12488]
`
C:\Program Files\dotnet\sdk\3.1.101\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error : The filename, directory name, or volume label syntax is incorrect. : 'D:\a\1\s\'d:\a\1\a'' [D:\a\1\s\ArcOps\ArcOps.csproj]`

```
trigger:
 branches:
   exclude:
     - master

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) 

pool:
  vmImage: 'windows-latest'

variables:
  majorMinorVersion: 1.0
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  projectName: 'ArcOps'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Authenticate with Azure DevOps NuGet'
  inputs:
    command: custom
    arguments: sources update -Name "Test" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile ./NuGet.Config
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ArcOps.sln'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet pack "ArcOps/ArcOps.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack    
- script: dotnet pack "ArcOps.AspNetCore/ArcOps.AspNetCore.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack    
- script: dotnet pack "ArcOps.AutoMapper/ArcOps.AutoMapper.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack   
- script: dotnet pack "ArcOps.Log4Net/ArcOps.Castle.Log4Net.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack   
- script: dotnet pack "ArcOps/ArcOps.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack    
- script: dotnet pack "ArcOps.Web/ArcOps.Web.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack    
- script: dotnet pack "ArcOps.Web.Common/ArcOps.Web.Common.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack   
- script: dotnet pack "ArcOps.Web.Mvc/ArcOps.Web.Mvc.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack  

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true`
```
I cant seem to pack my packages. Please advise. Thanks.
It fails on this step

```
- script: dotnet pack "ArcOps/ArcOps.csproj" --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)' /p:Version=$(majorMinorVersion).$(semanticVersion) # $(rev:r)
  displayName: pack 
```
