### ISSUE TITLE
[ExtractFiles]: Do not delete archives if they are in destinationFolder and searched in archiveFilePatterns

### ISSUE THREAD

**Issue by Saibamen** [microsoft/azure-pipelines-tasks#12505]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ExtractFiles

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Do not delete archives if they are in destinationFolder and searched in archiveFilePatterns

```
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/X/Y/Z/.TestIntegrationData.zip'
    destinationFolder: 'X/Y/Z'
    cleanDestinationFolder: true
```

### Task logs

IMHO not needed full debug logs. Please see below.

### Error logs

```
Searching for: **\X\Y\Z\.TestIntegrationData.zip under directory: d:\a\1\s
Found: 1 files to extract:
d:\a\1\s\X\Y\Z\.TestIntegrationData.zip
Cleaning destination folder before extraction: d:\a\1\s\X\Y\Z
Creating destination folder: d:\a\1\s\X\Y\Z
Error: ENOENT: no such file or directory, stat 'd:\a\1\s\X\Y\Z\.TestIntegrationData.zip'
```
