### ISSUE TITLE
Copy-Item fails with MI_RESULT_FAILED

### ISSUE THREAD

**Issue by fniko** [microsoft/azure-pipelines-tasks#12535]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: [PowerShellV2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShellV2)  

## Environment
- Server - **Azure Pipelines**
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - **Private**: 
      - **Host**: Ubuntu 18.04.4 LTS
      - Docker image: filipniko/powershell:v1 (based on **mcr.microsoft.com/powershell**)

## Issue Description

I am able to establish session from my container to target remote server, however Copy-Item does not work:
```
Starting a command on the remote server failed with the following error message : MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting Help topic.
```
Task definition:
```
stages:
  - stage: deploy
    displayName: Upload and restart
    jobs:
      - deployment: deploy
        container: filipniko/powershell:v1
        displayName: Upload and restart
        strategy:
          runOnce:
            deploy:
              steps:
                ...
                - task: PowerShell@2
                  displayName: 'Upload package to destination server'
                  inputs:
                    targetType: inline
                    script: |
                      $USERNAME = $env:username
                      echo $USERNAME
                      $PASSWORD = $env:password | ConvertTo-SecureString -AsPlainText -Force
                      echo $PASSWORD
                      $CRED = new-object -typename System.Management.Automation.PSCredential -argumentlist $USERNAME, $PASSWORD
                      $SESSION = New-PSSession -ComputerName $env:destination -Credential $CRED -Authentication Negotiate
                      Copy-Item -Path '$(System.ArtifactsDirectory)\OfflinePage.zip' -Destination 'C:\' -ToSession $SESSION
                  env:
                    username: $(SERVER_ADMIN_LOGIN)
                    password: $(SERVER_ADMIN_PASSWORD)
                    destination: $(DESTINATION_SERVER)
```

Note:
- The file is present, I checked using `Test-Path $(System.ArtifactsDirectory)\OfflinePage.zip -PathType Leaf` returns `True`
- The task was tested on Windows based agent where it runs OK
- Maybe using `$(System.ArtifactsDirectory)` causes the issue?

### Task logs / Error logs

https://pastebin.com/9JjURR6v

## Troubleshooting
Setup of the remote host
- target is Windows Server 2019 or Windows Server 2012 R2
- user is admin with full permissions on the target server
- WinRM is enabled with wildcard to permit all machines to connect (used for tests)
```
Enable-PSRemoting –Force
Set-Item WSMan:\localhost\Client\TrustedHosts -Force -Value *
Set-Service WinRM -StartMode Automatic
Restart-Service -Force WinRM
```

I tried to spin up a container on the agent I use with the same image I use in the pipeline and tried to execute the task and it passed successfully!

```
docker run -it filipniko/powershell:v1 /bin/bash
PS /> $USERNAME = 'admin'
PS /> echo $USERNAME
admin
PS /> $PASSWORD = 'password' | ConvertTo-SecureString -AsPlainText -Force
PS /> echo $PASSWORD
System.Security.SecureString
PS /> $CRED = new-object -typename System.Management.Automation.PSCredential -argumentlist $USERNAME, $PASSWORD
PS /> $SESSION = New-PSSession -ComputerName 10.0.0.1 -Credential $CRED -Authentication Negotiate
PS /> Copy-Item -Path 'OfflinePage.zip' -Destination 'C:\' -ToSession $SESSION         
```
And I can observe the file on the destination server!

I also tried another custom image based on clean Ubuntu, so ti uses latest Powershell available, with no results... 
```
FROM ubuntu:18.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

# Base of the image
RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libunwind8 \
        netcat \
        wget

# Get and install Powershell and necessary packages
RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& apt-get update \
&& apt-get install powershell \
        netbase \
        gss-ntlmssp

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
```
