### ISSUE TITLE
GitHubReleaseV1: No files found matching 'path'. Nothing to upload.

### ISSUE THREAD

**Issue by BrunoBlanes** [microsoft/azure-pipelines-tasks#12533]
## Required Information
Type: **Question**
Task Name: **GitHubReleaseV1**

## Environment
- Server - Azure Pipelines  
    - Account name: BrunoBlanes
    - Team project name: CRM

- Agent - Private: 
    - Build number: #20200313.31

|Name | Value|
|-- | --|
|Agent.OS | Windows_NT|
|Agent.OSArchitecture | X64|
|Agent.OSVersion | 10.0.19555|
|Agent.Version | 2.165.1|

## Issue Description
Why is it that, even though I checked the path and there is a .msixuppload file and another folder full of contents, this task still returns with `No files found matching 'C:\agent\_work\4\a\AppxPackages\/*'. Nothing to upload.`? Am I doing something wrong here?

### Pipeline
```
- task: GitHubRelease@1
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: '$(gitConnection)'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: gitTag
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
    assets: $(Build.ArtifactStagingDirectory)\AppxPackages\/*
```
### Task Result
```
Starting: Create GitHub Release
==============================================================================
Task         : GitHub Release
Description  : Create, edit, or delete a GitHub release
Version      : 1.160.2
Author       : Microsoft Corporation
Help         : https://aka.ms/AA5vv5o
==============================================================================
0db16545-6557-4177-9873-73325ad47670 exists true
Searching for tags associated with target commit: d0b0b5dfc57304499d5cf7c82878dffa0849aa0e
Found a tag for target commit: d0b0b5dfc57304499d5cf7c82878dffa0849aa0e
Computing changes made in this release...
Fetching the latest published release...
Found the latest published release: https://github.com/BrunoBlanes/CRM/releases/tag/v0.1.5-alpha
Fetching the list of commits since the last published release...
Found the list of changes.
No issues are linked to commits in the specified commit Diff.
Release notes file: C:\agent\_work\4\s is a directory and not a file.
Creating a release for tag: v0.1.7-alpha
Uploading assets...
Searching for file(s) matching 'C:\agent\_work\4\a\AppxPackages\/*'.
No files found matching 'C:\agent\_work\4\a\AppxPackages\/*'. Nothing to upload.
All assets uploaded successfully.
Release created successfully at https://github.com/BrunoBlanes/CRM/releases/tag/v0.1.7-alpha
Finishing: Create GitHub Release
```
