### ISSUE TITLE
AzureFileCopy to VM copies temp container

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/azure-pipelines-tasks#12542]
Task: AzureFileCopy V4 

Environment: Azure pipeline in windows-latest pool

Bug: When destination is VM, AzureFileCopy creates a temporary intermediary blob container, as stated in the documentation, but the _container_ is copied to the VM, instead of the specified source file.

```
- task: AzureFileCopy@4
  displayName: 'Copy secure file to VM'
  inputs:
    sourcePath: $(myfile.secureFilePath)
    azureSubscription: $(subscriptionName)
    storage: $(storageAccount)
    destination: 'AzureVMs'
    resourceGroup: $(resourceGroup)
    resourceFilteringMethod: 'machineNames'
    machineNames: 'MyVM'
    vmsAdminUserName: 'username'
    vmsAdminPassword: '****'
    targetPath: 'Downloads'
    enableCopyPrerequisites: true
```
Expected:

C:\Users\username\Documents\Downloads\myfile.txt

Actual:

C:\Users\username\Documents\Downloads\92293b49-0de6-400b-8b75-7a9c72bfd512\myfile.txt

Tried specifying blob prefix, container name, and adding a wildcard to sourcePath, same result.
