### ISSUE TITLE
AzureCLIV2 doesn't display output of Write-Error

### ISSUE THREAD

**Issue by qetza** [microsoft/azure-pipelines-tasks#12550]
When using the AzureCLI task with powershell core (and maybe powershell) the output of `Write-Error` cmdlet is not displayed as it is done with other powershell tasks.

```yaml
- task: AzureCLI@2
  displayName: Write-Error
  inputs:
    azureSubscription: '$(ServiceConnection.AzureSubscription)'
    scriptType: pscore
    scriptLocation: inlineScript
    failOnStandardError: true
    inlineScript: Write-Error "oops"
```

The previous task execution should display the error message in red `##[error]oops` but instead only the following error is displayed:

```
##[error]Script failed with error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1
```
This is a big issue as any error output in the executed script is masked.

The current workaround i found is to use a try/catch and manually logs the error:
```yaml
- task: AzureCLI@2
  displayName: Write-Error
  inputs:
    azureSubscription: '$(ServiceConnection.AzureSubscription)'
    scriptType: pscore
    scriptLocation: inlineScript
    failOnStandardError: true
    inlineScript: |
      try
      { 
        Write-Error "oops"
      }
      catch
      {
        Write-Host "##vso[task.logissue type=error]${_}"
        exit 1
      }
```

The AzureCLI task should support powershell cmdlets `Write-Debug`, `Write-Verbose`, `Write-Warning` and `Write-Error` by displaying them in the logs with the correct log level.
