### ISSUE TITLE
dotnet nuget push "SkipDuplicate" option for org feed

### ISSUE THREAD

**Issue by Styxxy** [microsoft/azure-pipelines-tasks#12562]
## Required Information
**Type**: Feature
**Enter Task Name**: DotNetCoreCLI

## Issue Description
When using the DotNetCoreCLI task, command "nuget push", it is not possible to specify "SkipDuplicates". This option does seem to exist on the cli itself and in the Nuget task.

![dotnetcorecli](https://user-images.githubusercontent.com/1635825/77255373-34b61180-6c67-11ea-9ef9-2ab909016a1c.png)

![nuget](https://user-images.githubusercontent.com/1635825/77255378-40a1d380-6c67-11ea-805d-90e5ec37ad60.png)

In YAML terms:
```yaml
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    packagesToPush: '$(System.DefaultWorkingDirectory)/_testpackage/drop/**/*.nupkg'
    publishVstsFeed: 'testfeedguid'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'testfeedguid'
    allowPackageConflicts: true
```
