### ISSUE TITLE
System.PullRequest.TargetBranch Exposes Branch Name Instead of Refspec 

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/azure-pipelines-tasks#12588]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: N/A

## Environment
Hosted VSTS.
See https://dev.azure.com/ms/react-native-windows/

## Issue Description

[Documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) suggests that the `System.PullRequest.TargetBranch` variable is in the form of a refspec. E.g. `refs/heads/origin/master`. When using this variable in our jobs, triggered from Github PRs to the react-native-windows repository, the variable shows up as just `master`. This is actually more convenient for us, but ultimately diverges from what is documented.

A similar variable, `Build.SourceBranch` is documented to be a refspec as well, with a variant `Build.SourceBranchName` returning just the branch. Maybe this pattern of "Name for non-refspec" should be used here?

### Task logs

See run here: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=70349&view=logs&j=d1d6f0bf-8fba-5a08-054d-b7f8f3ed7bef&t=4b6175b7-fe6f-5e40-8a60-8c81dd81a5b4

This task:

```yaml
 - task: CmdLine@2
        displayName: Check for change files
        inputs:
          script: node ./node_modules/beachball/bin/beachball.js check --branch origin/$(System.PullRequest.TargetBranch) --changehint "Run `yarn change` from root of repo to generate a change file."
```

ends up running:
```
node ./node_modules/beachball/bin/beachball.js check --branch origin/master --changehint "Run `yarn change` from root of repo to generate a change file."
```
