### ISSUE TITLE
Cove coverage target in python using coverage tool

### ISSUE THREAD

**Issue by anandchugh** [microsoft/azure-pipelines-tasks#12598]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: How to set code coverage target in python using coverage tool.

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
org name: india-dev-crew-bangalore
project name: DataKhoj
build :https://dev.azure.com/india-dev-crew-bangalore/DataKhoj/_build/results?buildId=546&view=results

## Issue Description

Is there a way that we can add target % code coverage. For example can we mention code coverage to be 80% and if coverage is below 80% build should fail.

**Comment by matthewfcarlson** [comment]
I'd also like this. I'd like to have a comment on github of the coverage

**Comment by anandchugh** [comment]
Used this task to check for code coverage
```

 - task: BuildQualityChecks@6
      displayName: 'Code coverage check'
      inputs:
        checkCoverage: true
        coverageFailOption: 'fixed'
        coverageType: 'lines'
        coverageThreshold: 80
```
