### ISSUE TITLE
Code coverage target in Java Maven task

### ISSUE THREAD

**Issue by anandchugh** [microsoft/azure-pipelines-tasks#12596]
**Question, Bug, or Feature?**  
*Type*:  Question

**Enter Task Name**: Code coverage target in Java Maven task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
 
## Issue Description
Here is my maven task to execute build and code coverage. 
 ```
 - task: Maven@3
        displayName: Maven Build
        inputs:
          mavenPomFile: '$(System.DefaultWorkingDirectory)/$(SourceDirectory)/pom.xml'
          goals: 'package'
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          publishJUnitResults: true
          codeCoverageToolOption: JaCoCo
          codeCoverageClassFilesDirectories: $(SourceDirectory)/target/classes,$(SourceDirectory)/target/test-classes
          codeCoverageSourceDirectories: $(SourceDirectory)/src/main/java,$(SourceDirectory)/src/test
```
Is there a way that we can add target % code coverage. For example can we mention code coverage to be 80% and if coverage is below 80% build should fail.
