### ISSUE TITLE
Gradle v2 Jacoco code coverage is broken

### ISSUE THREAD

**Issue by websolut** [microsoft/azure-pipelines-tasks#12593]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle v2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
Pipeline: https://dev.azure.com/sis-cat-com/sis2-ws-all/_build/results?buildId=24337&view=results

- Agent - Hosted : 
Windows 2019

## Issue Description

When running a gradle.build with enabled code coverage the following error is thrown for jacoco:

Build file 'D:\a\1\s\build.gradle' line: 215

* What went wrong:
A problem occurred evaluating root project '*****'.
> Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension.

**Comment by melakonda** [comment]
I am seeing the same issue.. anyone has solution for this. Please update

**Comment by chevarria** [comment]
I'm having the same problem. Please update

**Comment by macromania** [comment]
I have just tried this task on Azure Pipelines and getting the same error.

pipeline:

```yml
pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: '$(System.DefaultWorkingDirectory)/XXXXX/gradlew'
      workingDirectory: '$(System.DefaultWorkingDirectory)/XXXXX/'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      sonarQubeRunAnalysis: false

```

the error message from build logs

```
BUILD SUCCESSFUL

.....


Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension.

```

**Comment by ryyaeg** [comment]
I have also confirmed that this Issue will reproduce.

- This issue occurs when using Gradle 6.0 or higher and JDK 11.
- It does not occur with Gradle 5.6.4 or lower and with JDK 1.8.
- Therefore, this Issue is a Gradle and JDK version-dependent issue.

The following repositories do not generate an Issue, but the image of the code coverage is broken.
https://github.com/ryyaeg/pipelines-java

**Comment by luigi2004** [comment]
This is a gradle 6.0 issue append was removed and the task directly setting it

**Comment by kingwang-git** [comment]
> * This issue occurs when using Gradle 6.0 or higher and JDK 11.

I am seeing the same issue on Gradle 6.0.1 and jdk 8 (OpenJDK).
Still believe this is Azure-related as we only hit the issue when running on DevOps pipeline.
Is there a work around?

**Comment by ekaterina-tatanova** [comment]
@kingwang-git It seems to be related to Gradle update. As mentioned [here](https://docs.gradle.org/current/userguide/upgrading_version_5.html#other_deprecated_behaviors_and_apis), the 'append' property on JacocoTaskExtension has been removed. Could you please share build.gradle and gradle.properties files of your project to make sure that there's no issue with Gradle version?

**Comment by therottman** [comment]
I'm having the same issue.

One workaround is to remove `codeCoverageToolOption` from the Gradle@2 task and add a new task after:
```
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'
```
