### ISSUE TITLE
Declaration of variable with bash command substitution

### ISSUE THREAD

**Issue by DorShamay** [microsoft/azure-pipelines-tasks#12594]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Bash Task v3.x

list here (V# not needed):  

## Environment
- Server - Azure Pipelines

    - Using azure pipeline but on Private aspect so i'll explain on Issue Description

- Agent - Private
    
    - Ubuntu 18.04

## Issue Description

I'm trying to use the date command on bash to format the output of the command to specific need.
When doing so I'm declaring a normal variable at first and then trying to echo it (for test purposes)
and its doing well, but when echoing the declaration of the variable from here:
- echo "##vso[task.setvariable variable=datebuild;]$datetime"

It doesn't work.

![image](https://user-images.githubusercontent.com/33579173/77848368-e2c43d00-71cc-11ea-8bcb-07cc8e614f63.png)

**Comment by DorShamay** [comment]
The question is open for 7 days now, can someone help please?

**Comment by anton-erofeev** [comment]
Hello, @DorShamay !
` echo "##vso[task.setvariable variable=datebuild]$datetime"` this line does not update the environment of the current script. [(Documentation: Set variables in scripts)](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-scripts)
Therefore, if you want to use it, you should define this variable in a separate task, before using this script. 
For example:
```
task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      datetime=$(date +%Y%m%d_%H%M%S)
      echo "##vso[task.setvariable variable=datebuild]$datetime"
      
task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $DATEBUILD
```
      
Also note that the variable name contains only uppercase letters. (This script sets the value for "datebuild", but uses "DATEBUILD" as variable name to print it)

Please let me know if it solved your issue.
