### ISSUE TITLE
Code coverage page not showing icons

### ISSUE THREAD

**Issue by anandchugh** [microsoft/azure-pipelines-tasks#12597]
![codecoverage](https://user-images.githubusercontent.com/3197424/77853794-a95af400-7203-11ea-81bf-17fe08ec0ccc.PNG)
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Code coverage page not showing icons

## Environment
- Server - Azure Pipelines or TFS on-premises? Azire Pipelines
    
- Agent - Hosted or Private:  Hosted
    
 ## Issue Description

Code coverage page is not able to load the icons.

Here is the task to create code coverage
```
  - task: Maven@3
        displayName: Maven Build
        inputs:
          mavenPomFile: '$(System.DefaultWorkingDirectory)/$(SourceDirectory)/pom.xml'
          goals: 'package'
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          publishJUnitResults: true
          codeCoverageToolOption: JaCoCo
          codeCoverageClassFilesDirectories: $(SourceDirectory)/target/classes,$(SourceDirectory)/target/test-classes
          codeCoverageSourceDirectories: $(SourceDirectory)/src/main/java,$(SourceDirectory)/src/test
```

### Error logs

Attached is the screenshot of error.
