### ISSUE TITLE
InstallSSHKey@0 doesn't read variables configured for a specific stage

### ISSUE THREAD

**Issue by muellermatthias** [microsoft/azure-pipelines-tasks#12645]
## Required Information

**Type**: Bug

**Task Name**: InstallSSHKey@0  

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

I'm using the InstallSSHKey task in my pipeline. The public key and the name of the secure file are stored in variables. The pipeline stopped working when I moved the variables configuration to the stage, where the task should be executed. It shows this error:

`There was a resource authorization issue: "The pipeline is not valid. Job job: Step InstallSSHKey input sshKeySecureFile references secure file $(sshKeySecureFile) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."` and a button "Authorize resources".

This is a simplified example of my original pipeline:

```yaml
pool:
  vmImage: Ubuntu 16.04
variables:
  sshKeySecureFile: "sshKeyFile"
  sshPublicKey: <public key>

stages:
- stage: stage
  jobs:
  - job: job
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: <knownHostEntry>
        sshPublicKey: $(sshPublicKey)
        sshKeySecureFile: $(sshKeySecureFile)
```
Replace the <> parts with some real values if you want to test the pipeline.

This is my new version:
```yaml
pool:
  vmImage: Ubuntu 16.04

stages:
- stage: stage
  variables:
    sshKeySecureFile: "sshKeyFile"
    sshPublicKey: <public key>
  jobs:
  - job: job
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: <knownHostEntry>
        sshPublicKey: $(sshPublicKey)
        sshKeySecureFile: $(sshKeySecureFile)
```
The ssh key and the variable values are fine because the worked before I moved the variable configuration.
When I execute other tasks than InstallSSHKey, the pipeline runs successfully and the tasks read the variables.
I want to highlight that in the error message the variable isn't replaced with "sshKeyFile". That's why I assume that the task doesn't/can't read variables configured in a stage.
