### ISSUE TITLE
Command Options Escaped

### ISSUE THREAD

**Issue by Phrayzur** [microsoft/azure-pipelines-tasks#12651]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GradleV2

## Environment
Azure Pipelines
Agent - Hosted

## Issue Description

I have a task description:

```
- task: Gradle@2
            displayName: 'Publish jar to artifacts feed'
            inputs:
              gradleWrapperFile: 'modules/IntegrationShared/ServerIntegration/gradlew.bat'
              workingDirectory: 'modules/IntegrationShared/ServerIntegration'
              options: -PazurePAT=$(azurePAT)
              tasks: 'publish'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              sonarQubeRunAnalysis: false
```

I would expect the command ran from this to be:

`gradlew.bat -PazurePAT=abcdef publish`

however, instead I get:

`C:\windows\system32\cmd.exe /D /S /C "d:\a\1\s\modules\IntegrationShared\ServerIntegration\gradlew.bat "-PazurePAT=" options: "'-PazurePAT=abcdef'" publish"`

Notice the escaping quotation marks as well as the rogue `options`. Because of this I then get:

`Project 'options' not found in root project 'ServerIntegration'.`
