### ISSUE TITLE
Question: regarding artifacts reuse across multiple stages

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/azure-pipelines-tasks#12661]
Hey Guys, 
I have a question regarding artifacts across multiple stage. 
Please see my pseudo pipeline code bellow. 

- I am using artifacts that are defined under resources.
- In stage DeployToUAT, it will be downloaded automatically (since it's deloyment job).
- Let's say DeployToProd  will be executed after a week due to approval process.
- Which version of Release pipeline,  DeployToProd  will download? then same one as it as was downloaded in first stage DeployToUAT or the latest version that exist on the time of run.  
- Both stages are executed on different self-hosted agents 

```
resources:
  pipelines:
    - pipeline: Release
      source: Release_CI

stages:
  - stage: DeployToUAT
    jobs:  
    - deployment: deployObjects
      pool:
        name: 'lab'
        demands: 
          - Agent.Name -equals UATAgent
      workspace:
        clean: all
      environment:
        name: UAT
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              clean: true  
            - template: deploymentStepsTemplate.yml
              parameters:
                instanceName: 'UAT'

- stage: DeployToProd    
    jobs:               
      - deployment: deployObjects
        pool:
          name: 'prod'
          demands: 
            - Agent.Name -equals ProdAgent
        environment:
          name: Prod
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
                clean: true  
              - template: deploymentStepsTemplate.yml
                parameters:
                  instanceName: 'PROD'
                  deployFob: $(deployFob)
```
