### ISSUE TITLE
Unable to set secure file to download based on pipeline variables

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tasks#12673]
## Required Information

- **Type**: Bug
- **Task Name**: DownloadSecureFile  

## Environment

- **Server**: Azure Pipelines
- **Agent**: Hosted

## Issue Description

We'd like to store credentials for different environments in different secure files. For example, we might have:

- `creds-a.env`
- `creds-b.env`
- `creds-c.env`

Based on the context of the current YAML pipeline, we can determine whether we're deploying to `a`, `b`, or `c`. It's important to note that we don't have this at the very start of the pipeline and it's not something we can hardcode or ask for; it's a runtime evaluation.

I'll put some pseudocode here, but the pipeline looks sort of like:

```yaml
- task: Bash@3
  inputs:
    targetType: inline
    script: |
      # Figure out the target environment, then write a variable for later use.
      echo "##vso[task.setvariable variable=target;]a"
- task: DownloadSecureFile@1
   name: credentials
   inputs:
     secureFile: creds-$(target).env
```

Unfortunately, it [appears `DownloadSecureFile` runs before the job](https://github.com/microsoft/azure-pipelines-tasks/blob/91ed11388bfa1462fd999a7849c3c8b5db08eccb/Tasks/DownloadSecureFileV1/task.json#L50) which means we can't affect the filename by running analysis in the pipeline like this.

It's not obvious that a job placed explicitly at a particular location in the pipeline is going to try to do work before the point at which it appears; and it seems like a defect that we're unable to use secure files in a more flexible way.
