### ISSUE TITLE
Pushing to external feed is broken

### ISSUE THREAD

**Issue by admin-simeon** [microsoft/azure-pipelines-tasks#12680]
*Type*: Bug

**Pushing to external nuget feeds is broken**

## Environment

Azure DevOps hosted agent

## Issue Description

Can't get around the error trying to push to nuget.org. No good/working documentation anywhere by Microsoft on how to do this.

```
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
Pushing *****beta.nupkg to 'https://www.nuget.org/api/v2/package'...
```

## Steps to reproduce:

- Add a service connection to nuget.org
  - Name it nuget.org
  - Use API Key authentication OR username/password and set the API key as the password (both are broken)

- Add a pipeline with the following step after a build that produces packages:
```
pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: nuget.org

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    arguments: '--configuration $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)'
    packagesToPack: '*.sln'

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifacts
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  condition: always()
```

- Get error

Also tried many variations of the above steps - all are broken. It's very frustrating to me something so basic doesn't work.

### When using basic authentication and NuGet task...same error:
```
- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: nuget.org
- task: NuGetCommand@2
  displayName: Deploy
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
```

when using NuGet task with API key authentication...same error 

running dotnet nuget push with the same api key specified from a local command line works:
```
dotnet nuget push -s https://api.nuget.org/v3/index.json -k *** out\***.nupkg
```

### Task logs

Here is a full task output

```

C:\windows\system32\chcp.com 65001
Active code page: 65001
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
ea085994***2338***4f80***bed1***5acbedf79880 exists true
Using authentication information for the following URI: https://api.nuget.org/v3/index.json
C:\hostedtoolcache\windows\dotnet\dotnet.exe nuget push d:\a\1\a\I******beta.nupkg ***source https://api.nuget.org/v3/index.json ***api***key RequiredApiKey
Pushing ******beta.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 331ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  ***h|***help                      Show help information
  ***force***english***output         Forces the application to run using an invariant, English***based culture.
  ***s|***source <source>           Specifies the server URL
  ***ss|***symbol***source <source>   Specifies the symbol server URL. If not specified, nuget.smbsrc.net is used when pushing to nuget.org.
  ***t|***timeout <timeout>         Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  ***k|***api***key <apiKey>          The API key for the server.
  ***sk|***symbol***api***key <apiKey>  The API key for the symbol server.
  ***d|***disable***buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  ***n|***no***symbols                If a symbols package exists, it will not be pushed to a symbols server.
  ***no***service***endpoint          Does not append "api/v2/package" to the source URL.
  ***interactive                  Allow the command to block and require manual action for operations like authentication.
  ***skip***duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
##[error]Packages failed to publish
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.0 and 3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with ***o or ***Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en***us/azure/devops/pipelines/tasks/build/dotnet***core***cli?view=azure***devops#troubleshooting
Finishing: Push

```
