### ISSUE TITLE
SqlAzureDacpacDeployment@1 does not support ampersand in password

### ISSUE THREAD

**Issue by ivan-sam** [microsoft/azure-pipelines-tasks#12746]
**Question, Bug, or Feature?**  
*Type*: Bug

SqlAzureDacpacDeployment@1 does not support certain characters in password when using `authenticationType: aadAuthenticationPassword`

## Environment
- Azure Pipelines

- Agent - Hosted 

## Issue Description

I spent 2 days trying to figure out why **SqlAzureDacpacDeployment** did not work, whereas using Invoke-Sqlcmd with the same parameters succeeded.
Troubleshooting of SqlAzureDacpacDeployment is very limited, since most of the time AggregateException is thrown, so error message says only 

> ##[error]One or more errors occurred.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

In the end it turned out that the **task does not support** certain character in password: **&**

I did try:
- wrapping login/password parameters with double quotes:

```
    - task: AzureKeyVault@1
            displayName: 'Import Key Vault secrets'
            inputs:
              azureSubscription: "Azure Sub"
              KeyVaultName: 'vault-deployment-tst'
              SecretsFilter: 'DbDeployAdminName, DbDeployAdminPassword'

    - task: SqlAzureDacpacDeployment@1
            displayName: 'Upgrade DB'
            inputs:
              azureSubscription: 'Azure Sub'
              authenticationType: aadAuthenticationPassword
              aadSqlUsername: "$(DbDeployAdminName)"
              aadSqlPassword: "$(DbDeployAdminPassword)"
              serverName: 'tst-sql01.database.windows.net'
              databaseName: 'TheDB-tst'
              deployType: sqlTask
              sqlFile: '$(Pipeline.Workspace)/s/deploy/sql/DB.sql'

```
- wrapping login/password parameters with single quotes:

```
    - task: AzureKeyVault@1
            displayName: 'Import Key Vault secrets'
            inputs:
              azureSubscription: "Azure Sub"
              KeyVaultName: 'vault-deployment-tst'
              SecretsFilter: 'DbDeployAdminName, DbDeployAdminPassword'

    - task: SqlAzureDacpacDeployment@1
            displayName: 'Upgrade DB'
            inputs:
              azureSubscription: 'Azure Sub'
              authenticationType: aadAuthenticationPassword
              aadSqlUsername: '$(DbDeployAdminName)'
              aadSqlPassword: '$(DbDeployAdminPassword)'
              serverName: 'tst-sql01.database.windows.net'
              databaseName: 'TheDB-tst'
              deployType: sqlTask
              sqlFile: '$(Pipeline.Workspace)/s/deploy/sql/DB.sql'

```

- not wrapping login/password parameters at all:

```
    - task: AzureKeyVault@1
            displayName: 'Import Key Vault secrets'
            inputs:
              azureSubscription: "Azure Sub"
              KeyVaultName: 'vault-deployment-tst'
              SecretsFilter: 'DbDeployAdminName, DbDeployAdminPassword'

    - task: SqlAzureDacpacDeployment@1
            displayName: 'Upgrade DB'
            inputs:
              azureSubscription: 'Azure Sub'
              authenticationType: aadAuthenticationPassword
              aadSqlUsername: $(DbDeployAdminName)
              aadSqlPassword: $(DbDeployAdminPassword)
              serverName: 'tst-sql01.database.windows.net'
              databaseName: 'TheDB-tst'
              deployType: sqlTask
              sqlFile: '$(Pipeline.Workspace)/s/deploy/sql/DB.sql'

```
- even reading information available by the link https://aka.ms/sqlazuredeployreadme#troubleshooting-

No additional information is available in diagnostics mode since credentials are masked:
`-sqlUserName *** -sqlPassword *** `

If this cannot be fixed easily, please add information about the limitation at https://aka.ms/sqlazuredeployreadme#troubleshooting-

I also think that handling **AggregateException** would help a lot

![Annotation 2020-04-23 195239](https://user-images.githubusercontent.com/4918115/80132937-bc5faa80-859c-11ea-9e8c-2b159f164f95.png)
