### ISSUE TITLE
PowerShellV2/powershell.ts syntax error

### ISSUE THREAD

**Issue by waynesi** [microsoft/azure-pipelines-tasks#12771]
The powershell.ts source code line 70 -
``` TypeScript
        await fs.writeFile(
            filePath,
            '\ufeff' + contents.join(os.EOL), // Prepend the Unicode BOM character.
            { encoding: 'utf8' });  
```
, while `fs.writeFile` syntax is `fs.writeFile(file, data[, options], callback)`

So my self-hosted agent decided to run my powershell task in a container via Node, I ended up with `##[error]Callback must be a function. Received { encoding: 'utf8' }` (Node 12.16.2), or `##[error]Callback must be a function` (Node 10.15.1).

After providing a dummy 4th parameter, everything works.

**Comment by digitalinfinity** [comment]
This doesn't seem to be limited to self-hosted agents- I can repro this on the hosted pool with the following yaml:
```
pool:
  vmImage: 'ubuntu-16.04'

container: mcr.microsoft.com/powershell/test-deps:lts-alpine-3.9

steps:
- pwsh: |
    Write-Host "Current directory is $(Get-Location)"
```

I'm not sure if there's a workaround here short of what @waynesi did (using a self-hosted agent + dummy parameter patch)

**Comment by damccorm** [comment]
;tldr be careful using versions of Node > 6 in containers to execute tasks.

I added a PR to fix this particular issue. With that said, there's a larger issue here that could cause other issues here. Right now, our agents use Node 6 to execute tasks (I know Node 6 is pretty old) - Node 6 is packaged with the agent. All our tasks are guaranteed to work with Node 6, but beyond that all bets are off as of now. When you enter into a container, we use the version of node supplied by the container rather than trying to download a version of Node ourselves (which would be slow and potentially not possible depending on network constraints on the container).

With that said, we have some work scheduled to upgrade the version of Node that we use to a newer version (probably 14). Its a non-trivial amount of work, though, because of compatibility issues like this, and we probably won't slide tasks to the newer version by default.

Again, the PowerShell issue should be fixed by my PR, but I'm just recommending caution here. If you're able to use a container with a lower version of node, that might work better for you.

**Comment by waynesi** [comment]
@damccorm Thanks a lot for fixing this issue. Regarding the recommended Node version for bespoke containers, I'm sure you know the best. However I was following this https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#bring-your-own-nodejs which says Node 10 LTS is a safe choice. Maybe the document needs update?

**Comment by damccorm** [comment]
@waynesi thanks for calling that out, I'll try to get that updated

**Comment by larssb** [comment]
Sorry for writing on a closed issue. But I can't see where else I should go with this @damccorm.

I'm having the same issue with an Azure pipeline. The error: `Callback must be a function` is thrown. I can that #12923 has been successfully merged. However, I guess it hasn't been released to Azure DevOps just yet? When and how does such a fix get into Azure Pipelines and its helper components?
Furthermore, I'm at odds in regards on how-to apply the *4th parameter* patch you mention @waynesi. Could you assist the uninitiated 👍 

**TRIED**

- Updating the on-prem hosted agents. They are now on v2.168.2
- Deleted the pipeline then re-created it. The thought being that this might refresh the pipeline and get the fix that was merged into the PowerShellV2 task
- Tried the `options:` YAML property on the pipeline `container` [resource](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#container-resource)
- Tried the `parameters:` YAML property in the root of the pipeline. See [these docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cyaml-example#parameters)

**INFO**

For good measure. Here is my pipeline YAML file:

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - master
  #parameters:
  #- name: node_dummy_callback # https://github.com/microsoft/azure-pipelines-tasks/issue /12771
  #  type: object
  #  default: {}

pool:
  name: kubernetes-vsts-agents
resources:
  containers:
  - container: powershell # reusable alias
    image: artifact-repository.intra.coop:9443/powershell/test-deps:lts-alpine-3.10
    #options: "{}"
jobs:
  - job: MasterBuild
    container: powershell # reference
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        #arguments: # Optional
        script: 'Install-Module -Name InvokeBuild'
        errorActionPreference: 'stop'
        failOnStderr: true
        ignoreLASTEXITCODE: false
        pwsh: true
        workingDirectory: "$(Build.SourcesDirectory)"
```
---

I hope you can help. Thank you very much 💯
