### ISSUE TITLE
NPM Publish permission denied failure

### ISSUE THREAD

**Issue by josh-oakes** [microsoft/azure-pipelines-tasks#12775]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Npm

## Environment
- Server - Azure Pipelines

- Agent - Hosted: ubuntu-latest

## Issue Description
Trying to perform an npm publish, i am getting permission denied errors from the scripts that need to run in the package.json file. I can't find the page that mentioned it, but I remember reading that npm commands should be executed with sudo. Is there a way that I can execute this task with sudo privileges?

Task yaml:

```
- task: Npm@1
  displayName: Publish TypeScript SDK
  inputs:
    command: 'publish'
    workingDir: '$(Build.StagingDirectory)/dist'
    publishRegistry: 'useFeed'
    publishFeed: '<feed_id>'
``` 

Output:

```
/usr/local/bin/npm publish

> kcf-sd-sdk@1.0.5 prepack .
> npm install && npm run build

npm WARN checkPermissions Missing write access to /home/vsts/work/1/a/dist
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/vsts/work/1/a/dist
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/vsts/work/1/a/dist'
npm ERR!  [Error: EACCES: permission denied, access '/home/vsts/work/1/a/dist'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/home/vsts/work/1/a/dist'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/vsts/work/1/a/dist'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```
