### ISSUE TITLE
HelmDeploy with debugging returns a warning even with failOnStderr at false

### ISSUE THREAD

**Issue by padeshaies** [microsoft/azure-pipelines-tasks#12798]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0 

## Environment
- Server - Azure Pipelines

- Agent - Hosted (ubuntu-latest)

## Issue Description

We had the same issue as #11414 and we had the properties `failOnStderr: false` to our task. Doing so, the deployment passes though we are now getting the following warning and no further logs :

```
##[warning]Capturing deployment metadata failed with error: YAMLException: duplicated mapping key at line 18, column 21:
    BuildVersion: 1.1.20
                        ^
```

This is how we use the task 

```
- deployment: "DeployMonGentilServiceDev"
      displayName: "Deploy - MonGentilService - Dev"
      dependsOn: "ProvisionMonGentilServiceKeyVault"
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'devazure.$(environmentName)'
      variables:
        vaultConfigurationUri: $[ dependencies.ProvisionmongentilserviceKeyVault.outputs['ProvisionmongentilserviceKeyVault.vaultConfigurationUri'] ]
      strategy:
        runOnce:
          deploy:
            steps:
            - task: HelmInstaller@1
              displayName: Helm installer
              inputs: 
                helmVersionToInstall: 3.1.2
            - task: HelmDeploy@0
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: 'AKS | officevibe-dev ov-aks $(environmentName)'
                command: 'upgrade'
                namespace: '$(environmentName)'
                chartType: 'FilePath'
                chartPath: $(Pipeline.Workspace)/manifestMonGentilService/
                releaseName: "magentillefeature-mongentilservice"
                overrideValues: BuildVersion=$(Build.BuildNumber),EnvironmentName="$(environmentName)"
                valueFile: $(Pipeline.Workspace)/manifestMonGentilService/values-$(environmentName).yaml
                failOnStderr: false
                arguments: '--debug'
```

and here are the useful variables: 

```
variables:
  - name: environmentName
    value: 'sniper'
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: major
    value: 1
  - name: minor
    value: 1

name: $(major).$(minor)$(Rev:.r)
```

### Task logs
Helm Install Logs:
```
Starting: Helm installer
==============================================================================
Task         : Helm tool installer
Description  : Install Helm on an agent machine
Version      : 1.167.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-installer-tsg
==============================================================================
Downloading: https://get.helm.sh/helm-v3.1.2-linux-amd64.zip
Extracting archive
/usr/bin/unzip /home/vsts/work/_temp/helm-v3.1.2-393f40bb-59c9-4a8d-8375-1d3dbdc16325.zip
Archive:  /home/vsts/work/_temp/helm-v3.1.2-393f40bb-59c9-4a8d-8375-1d3dbdc16325.zip
   creating: linux-amd64/
  inflating: linux-amd64/helm        
  inflating: linux-amd64/README.md   
  inflating: linux-amd64/LICENSE     
Caching tool: helm 3.1.2 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/helm/3.1.2/x64/linux-amd64
Verifying helm installation...
Finishing: Helm installer
```

Helm Deploy Logs:
```
Starting: HelmDeploy
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.167.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
/opt/hostedtoolcache/helm/3.1.2/x64/linux-amd64/helm upgrade --namespace sniper --install --values /home/vsts/work/1/manifestMonGentilService/values-sniper.yaml --set BuildVersion=1.1.20,EnvironmentName=sniper --wait --debug magentillefeature-mongentilservice /home/vsts/work/1/manifestMonGentilService/
history.go:52: [debug] getting history for release magentillefeature-mongentilservice
Release "magentillefeature-mongentilservice" has been upgraded. Happy Helming!
upgrade.go:84: [debug] preparing upgrade for magentillefeature-mongentilservice
NAME: magentillefeature-mongentilservice
upgrade.go:92: [debug] performing update for magentillefeature-mongentilservice
LAST DEPLOYED: Wed Apr 29 14:17:23 2020
upgrade.go:234: [debug] creating upgraded release for magentillefeature-mongentilservice
NAMESPACE: sniper
client.go:163: [debug] checking 4 resources for changes
STATUS: deployed
client.go:403: [debug] Looks like there are no changes for Service "magentillefeature-mongentilservice-service"
REVISION: 9
client.go:403: [debug] Looks like there are no changes for Ingress "magentillefeature-mongentilservice-ingress"
client.go:403: [debug] Looks like there are no changes for AzureIdentityBinding "aad-pod-identity-magentillefeature-mongentilservice-sniper-binding"
wait.go:52: [debug] beginning wait for 4 resources with timeout of 5m0s
wait.go:224: [debug] Deployment is not ready: sniper/magentillefeature-mongentilservice-deployment. 0 out of 3 expected pods are ready
wait.go:224: [debug] Deployment is not ready: sniper/magentillefeature-mongentilservice-deployment. 1 out of 3 expected pods are ready
wait.go:224: [debug] Deployment is not ready: sniper/magentillefeature-mongentilservice-deployment. 1 out of 3 expected pods are ready
wait.go:224: [debug] Deployment is not ready: sniper/magentillefeature-mongentilservice-deployment. 2 out of 3 expected pods are ready
upgrade.go:99: [debug] updating status for upgraded release for magentillefeature-mongentilservice
TEST SUITE: None
USER-SUPPLIED VALUES:
BuildVersion: 1.1.20
ConfigurationVaultUrl: https://ov-dev-sniper-kv-mongent.vault.azure.net/
CpuLimit: 100m
EnvironmentName: sniper
HostName: mongentilservice-magentillefeature.sniper.officevibe-dev.com
ManagedIdentityClientId: /subscriptions/9c9e4c70-e581-420a-8906-ef2a37e02d94/resourceGroups/ov-aks-k8s-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aad-pod-identity-pyro
ManagedIdentityRessourceId: e71d5ac5-6d4d-42ac-8c69-1e763f56f005
MemoryLimit: 128Mi
ReplicaNumber: 3

COMPUTED VALUES:
BuildVersion: 1.1.20
ConfigurationVaultUrl: https://ov-dev-sniper-kv-mongent.vault.azure.net/
CpuLimit: 100m
EnvironmentName: sniper
HostName: mongentilservice-magentillefeature.sniper.officevibe-dev.com
ManagedIdentityClientId: /subscriptions/9c9e4c70-e581-420a-8906-ef2a37e02d94/resourceGroups/ov-aks-k8s-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aad-pod-identity-pyro
ManagedIdentityRessourceId: e71d5ac5-6d4d-42ac-8c69-1e763f56f005
MemoryLimit: 128Mi
ReplicaNumber: 3

HOOKS:
MANIFEST:
---
# Source: MaGentilleFeatureMonGentilService/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: magentillefeature-mongentilservice-service
  labels:
    app: magentillefeature-mongentilservice
spec:
  selector:
    app: magentillefeature-mongentilservice
  ports:
  - port: 80
    targetPort: 80
---
# Source: MaGentilleFeatureMonGentilService/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magentillefeature-mongentilservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magentillefeature-mongentilservice
  template:
    metadata:
      labels:
        app: magentillefeature-mongentilservice
        aadpodidbinding: aad-magentillefeature-mongentilservice-sniper-pod-identity
    spec:
      containers:
      - name: magentillefeature-mongentilservice-container
        image: officevibeacr.azurecr.io/magentillefeature-mongentilservice:1.1.20
        imagePullPolicy: Always
        env:
        - name: DOTNET_ENVIRONMENT
          value: sniper
        - name: ASPNETCORE_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONVAULT
          value: https://ov-dev-sniper-kv-mongent.vault.azure.net/
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
# Source: MaGentilleFeatureMonGentilService/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: magentillefeature-mongentilservice-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - mongentilservice-magentillefeature.sniper.officevibe-dev.com
    secretName: letsencrypt-secret
  rules:
  - host: mongentilservice-magentillefeature.sniper.officevibe-dev.com
    http:
      paths:
      - backend:
          serviceName: magentillefeature-mongentilservice-service
          servicePort: 80
---
# Source: MaGentilleFeatureMonGentilService/templates/podIdentity.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aad-pod-identity-magentillefeature-mongentilservice-sniper-binding
spec:
  AzureIdentity: aad-pod-identity-sniper
  Selector: aad-magentillefeature-mongentilservice-sniper-pod-identity
  apiVersion: "aadpodidentity.k8s.io/v1"

##[warning]Capturing deployment metadata failed with error: YAMLException: duplicated mapping key at line 18, column 21:
    BuildVersion: 1.1.20
                        ^
Finishing: HelmDeploy

```

**Comment by shigupt202** [comment]
@padeshaies Thanks for bringing this to our attention. This seems to be the same bug as reported in this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/11931.
I'm working on a fix for this.

**Comment by padeshaies** [comment]
I've just tried again and the error is still there..

![image](https://user-images.githubusercontent.com/10930774/84796916-33c32080-afc7-11ea-80bf-63fba1ea486c.png)

**Comment by shigupt202** [comment]
@padeshaies The deployment with this fix has not started yet. It'll take around 1-2 weeks to reflect the changes across all the rings.

**Comment by 4devnull** [comment]
Up status ?
I've just tried again and the error is still

**Comment by shigupt202** [comment]
Could you share the logs and part of the workflow where you're using this task? This fix has been deployed long back.

**Comment by 4devnull** [comment]
> @4devnull Could you share the logs and part of the workflow where you're using this task? This fix has been deployed long back.

Hi @shigupt202 

I have same warning with "Publish metadata from pipelines (preview)" Enabled or Disabled.

- Warning message :
```
2021-03-17T10:39:14.7502414Z ##[warning]Capturing deployment metadata failed with error: YAMLException: duplicated mapping key at line 23, column 1:
    ---
    ^
```

Context: 
- Azure Agent Self-hosting 
```
agent v2.183.1 |_| (commit b8617e6)
```

- HelmDeploy@0  (0.183.0)  : 
```yaml
variables:
  namespace: 'debug'
  appName: myapp
  appVersion: ${{ replace( variables['Build.SourceBranchName'], '_','-') }} # x.x.x OR (feature/(<SourceBranchName>))

pool:
  name: xxxxxxxxxxxx # Use self-hosting azure-agent

stages:

- stage: integration
  displayName: Integration
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
  jobs:
  - deployment:
    displayName: Deploy to Integration
    environment:
      name: integration
    strategy:
      runOnce:
        deploy:
          steps:

          - task: HelmDeploy@0
            displayName: Helm upgrade or install
            inputs:
              kubernetesServiceEndpoint: integration
              namespace: $(namespace)
              command: upgrade
              install: true
              chartType: FilePath
              chartPath: helmChart/
              releaseName: $(appName)-$(appVersion) # myapp-debug
              waitForExecution: true
              arguments:
                --debug
                --set ingress.host=example.org
            
```


Trace output : 
```
2021-03-17T10:38:57.0013005Z ##[section]Starting: Helm upgrade or install
2021-03-17T10:38:57.0025158Z ==============================================================================
2021-03-17T10:38:57.0025532Z Task         : Package and deploy Helm charts
2021-03-17T10:38:57.0025860Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2021-03-17T10:38:57.0026354Z Version      : 0.183.0
2021-03-17T10:38:57.0026550Z Author       : Microsoft Corporation
2021-03-17T10:38:57.0026793Z Help         : https://aka.ms/azpipes-helm-tsg
2021-03-17T10:38:57.0027075Z ==============================================================================
2021-03-17T10:38:57.9975013Z [command]/usr/local/bin/helm upgrade --namespace debug --install --wait --debug --set ingress.host=example.org myapp-debug /azp/agent/_work/1/s/helmChart/
2021-03-17T10:39:14.5803266Z history.go:56: [debug] getting history for release myapp-debug
2021-03-17T10:39:14.5805528Z Release "myapp-debug" does not exist. Installing it now.
2021-03-17T10:39:14.5817247Z install.go:173: [debug] Original chart version: ""
2021-03-17T10:39:14.5818882Z NAME: myapp-debug
2021-03-17T10:39:14.5821542Z install.go:190: [debug] CHART PATH: /azp/agent/_work/1/s/helmChart
2021-03-17T10:39:14.5822536Z LAST DEPLOYED: Wed Mar 17 10:38:59 2021
2021-03-17T10:39:14.5824555Z 
2021-03-17T10:39:14.5825439Z NAMESPACE: debug
2021-03-17T10:39:14.5827381Z client.go:122: [debug] creating 4 resource(s)
2021-03-17T10:39:14.5828973Z STATUS: deployed

[....]

2021-03-17T10:39:14.5968516Z 
2021-03-17T10:39:14.7502414Z ##[warning]Capturing deployment metadata failed with error: YAMLException: duplicated mapping key at line 23, column 1:
    ---
    ^
2021-03-17T10:39:14.7593544Z ##[section]Finishing: Helm upgrade or install
```
