### ISSUE TITLE
Azure App Service deploy Pipeline Failed on Deployment. Error ETIMEDOUT 

### ISSUE THREAD

**Issue by gynet** [microsoft/azure-pipelines-tasks#12813]
The release pipeline was working before, and VS studio deployment works fine. 
- **Task version: version 4.***
- **Task YAML**
--------------------------------------------------------------
```
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: '$(Parameters.WebAppKind)'
    WebAppName: '$(Parameters.WebAppName)'
```
--------------------------------------------------------------

- **Logs:** 
--------------------------------------------------------------
2020-05-02T01:13:42.7364395Z ##[error]Failed to deploy web package to App Service.
2020-05-02T01:13:42.7368053Z ##[error]Error: Error: Failed to deploy web package to App Service. Error: connect ETIMEDOUT xxx.xx.xx.107:443
