### ISSUE TITLE
PR YAML does not test testplan integration

### ISSUE THREAD

**Issue by TroyWalshProf** [microsoft/azure-pipelines-tasks#12817]
## Description
The PR build isn't testing that the vstest will work with Azure Test Plans.
AKA would expect to see something like:
```
    - task: VSTest@2
      inputs:
        testSelector: 'testPlan'
        testPlan: '1'
        testSuite: '2'
        testConfiguration: '3'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        testRunTitle: 'Unit tests'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
```
in [azure-pipelines.yml](https://github.com/microsoft/vstest/blob/master/azure-pipelines.yml)

## Steps to reproduce
NA

## Expected behavior
Would expect this to be tested

## Actual behavior
Not tested

## Environment
Azure DevOps
