### ISSUE TITLE
Issues getting docker daemon running on Windows/MacOS with DockerInstaller

### ISSUE THREAD

**Issue by jkotalik** [microsoft/azure-pipelines-tasks#12823]
*Type*: Bug

**Enter Task Name**: DockerInstaller@0

## Environment
- Server - AzurePipelines

- Agent - Hosted or Private: 
    - I think we have our own custom pools, but they are defined here: https://github.com/dotnet/tye/blob/master/azure-pipelines.yml#L48

## Issue Description

I'm trying to run unit tests on Windows, MacOS, and Linux which required docker to be running. For example, I have a unit test which runs `docker build`, and will fail if docker isn't running.

From what I can tell, of the agents we have, docker is running on Linux, but not macOS or Windows. I'm trying to use the `DockerInstall` to install and start docker, however I'm hitting issues on both OS.

You can see a list of different things I have tried here: https://github.com/dotnet/tye/pull/430. I'll describe some below

### Windows

After running,

```yaml
        - task: DockerInstaller@0
          displayName: Docker Installer
          inputs:
            dockerVersion: 17.09.0-ce
            releaseType: stable
```

I get the following error when trying to run

```
        - script: docker version
```

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

From this error, I don't know if there is a permissions issue or that the daemon isn't running. I've tried to run dockerd.exe, however I realize the DockerInstall task doesn't cache that. 

### MacOS
Running:
```
        - task: DockerInstaller@0
          displayName: Docker Installer
          inputs:
            dockerVersion: 19.03.5
            releaseType: stable
```

I get the following error when running docker version afterwards

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I've tried to follow https://github.com/MicrosoftDocs/azure-devops-docs/issues/3784, however that didn't work for me either.

Any insight on what I should be doing to fix this?
