### ISSUE TITLE
[Bug] Custom timeout ignored in PublishToAzureServiceBusV1

### ISSUE THREAD

**Issue by sebastienros** [microsoft/azure-pipelines-tasks#12828]
In Azure Pipelines.
Task: **PublishToAzureServiceBusV1**

## Issue Description
Following the documentation to define the timeout of a Task: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options

I defined it to 30 minutes like in this example:

```yml
steps:
- ${{ each s in parameters.scenarios }}:
  - task: PublishToAzureServiceBus@1
    condition: succeededOrFailed()
    timeoutInMinutes: 30 
    displayName: ${{ s.displayName }}
    inputs:
      azureSubscription: ${{ parameters.connection }}
      waitForCompletion: true
      messageBody: |
        {
          "name": "benchmarks"
        }
```

However a task is canceled after 10 minutes exactly as shown here:

![image](https://user-images.githubusercontent.com/1165805/81077563-f89ae100-8ea1-11ea-839d-49912cfc9e16.png)
