### ISSUE TITLE
Error when Setting Username from AzureKeyVault

### ISSUE THREAD

**Issue by scsloan** [microsoft/azure-pipelines-tasks#12824]
*Type*:  Question

**Enter Task Name**:  IISWebAppManagementOnMachineGroup@0

- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Given the following Yaml snippet

````yml
        - task: AzureKeyVault@1
          inputs:
            azureSubscription : '_removed_'
            KeyVaultName : '_removed_'
            SecretsFilter : 'AppPoolUsername, AppPoolPassword'
        - task: IISWebAppManagementOnMachineGroup@0
          displayName: Update Website and App Pool
          inputs:
            IISDeploymentType: 'IISWebsite'
            ActionIISWebsite: 'CreateOrUpdateWebsite'
            WebsiteName: 'FooBarWeb'
            WebsitePhysicalPath: '%SystemDrive%\inetpub\'
            AddBinding: true
            Bindings: '_removed_'
            CreateOrUpdateAppPoolForWebsite: true
            AppPoolNameForWebsite: 'FooBarWeb'
            DotNetVersionForWebsite: 'No Managed Code'
            AppPoolIdentityForWebsite: 'specificUser'
            AppPoolUsernameForWebsite: $(AppPoolUsername)
            AppPoolPasswordForWebsite: $(AppPoolPassword)
            ParentWebsiteNameForVD: 'FooBarWeb'
            VirtualPathForVD: ''
            ParentWebsiteNameForApplication: 'FooBarWeb'
            VirtualPathForApplication: ''
            AppPoolName: 'FooBarWeb'

````
### Error logs

[error]Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "userName" is not valid. Change the value of the "userName" argument and run the operation again."
