### ISSUE TITLE
DotNetCoreCLI@2 failing on .Net Core 3.1 web app build and publish

### ISSUE THREAD

**Issue by BlairMcc** [microsoft/azure-pipelines-tasks#12829]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Ask me privately

- Agent - Hosted or Private:    

    - If using private agent, provide the OS of the machine running the agent and the agent version: 2.166.4

## Issue Description

This does not work via Azure Pipeline or direct in server
```
"C:\Program Files\dotnet\dotnet.exe" build C:\agent\work1\2\s\Components\IdentityServer\IdentityServer.sln "-dl:CentralLogger,\"C:\agent\work1\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.168.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"*ForwardingLogger,\"C:\agent\work1\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.168.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"" -c:release
"C:\Program Files\dotnet\dotnet.exe" publish C:\agent\work1\2\s\Components\IdentityServer\IdentityServer\IdentityServer.csproj -c:release --no-build --output:C:\agent\work1\2\a/Deploy/IdentityServer'
```

Results in this error
`C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(154,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 53 item(s). They must have the same number of items. [C:\agent\work1\2\s\Components\IdentityServer\IdentityServer\IdentityServer.csproj]`

However, this does work without the extra pipeline fluff
```
dotnet build IdentityServer.sln -c:release
dotnet publish IdentityServer/IdentityServer.csproj --no-build -c:release --output:C:\agent\work1\2\a/Deploy/IdentityServer'
```

YAML definiton
```
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Components/IdentityServer/IdentityServer.sln
    arguments: -c:"${{ parameters.BuildConfiguration }}"

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish    
    PublishWebProjects: false
    projects: Components/IdentityServer/IdentityServer/IdentityServer.csproj
    arguments: -c:"${{ parameters.BuildConfiguration }}" --no-build --output:"$(Build.ArtifactStagingDirectory)/Deploy/IdentityServer"'
    zipAfterPublish: false
```

MSBuild Version - Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Agent Version - Private / 2.155.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
