### ISSUE TITLE
Multiple checkout with custom paths fails in the container job

### ISSUE THREAD

**Issue by beatcracker** [microsoft/azure-pipelines-tasks#12844]
## Required Information

*Type*: Bug

**Task Name**:  `checkout` aka `6d15af64-176c-496d-b583-fd2ae21d4df4@1`

## Environment

- Server - Azure Pipelines

  This is a private CI setup, I can provide the account name, team project name, build definition name/build number via email.

- Agent - Hosted, Azure Pipelines, `ubuntu-latest`

## Issue Description

When trying to use multiple checkout feature inside container job, it fails with `##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]/home/vsts/work/1/s' successfully.`

This `azure-pipelines.yml` reproduces the issue:

```yml
resources:
  containers:
  - container: netcore_sdk_3
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
stages:
- stage:
  jobs:
  - job:
    container: netcore_sdk_3
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        path: s
      - checkout: self
        path: s/.azd
```

### Task logs

Anonymized task logs: [azd_logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4595659/azd_logs.zip)

### Error logs

```none
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]/home/vsts/work/1/s' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Repository path '/home/vsts/work/1/s' should be located under agent's work directory '/__w/1'.
##[debug]System.ArgumentException: Repository path '/home/vsts/work/1/s' should be located under agent's work directory '/__w/1'.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.GetRelativeRepositoryPath(String buildDirectory, String repositoryPath)
   at Microsoft.VisualStudio.Services.Agent.Worker.PluginInternalUpdateRepositoryPathCommand.Execute(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.BaseWorkerCommandExtension.ProcessCommand(IExecutionContext context, Command command, IWorkerCommandRestrictionPolicy restrictionPolicy)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
```

**Comment by qmfrederik** [comment]
I'm having the same issue. Should this issue be tracked in the azure-pipelines-agent or azure-pipelines-tasks repository?

**Comment by beatcracker** [comment]
@qmfrederik FYI, I've worked around this issue by specifying `target: host` for checkout steps.

**Comment by qmfrederik** [comment]
@beatcracker Awesome! That works, thank you.

**Comment by mtene** [comment]
Also experienced this. @beatcracker's workaround removes OP's error, but the next task after it fails with a weird excpeption. It may be relevant that I am not checking out to 's' but to 'b/somedir'. Not being able to use absolute paths stemming from variables like $(Build.BinariesDirectory) is a pain I had to workaround to as well...
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /__a/externals/node/bin/node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1000 58ef71b982ab414e44f3b83bd961fa9db4536dd2e4c1d9686b936ed1a06d0667 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
```

**Comment by mtene** [comment]
Referenced in this [Developer Community](https://developercommunity.visualstudio.com/content/problem/1077497/unable-move-and-reuse-existing-repository-to-requi.html) post.

**Comment by jennli** [comment]
@beatcracker thank you so much for the work around, I am having the same issue and your method solved it.

**Comment by beatcracker** [comment]
> This issue is stale because it has been open for 180 days with no activity.

Just checked, I can still reproduce the issue using the example I provided in the description.

```none
Starting: Checkout foo/bar@test-checkout to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]/home/vsts/work/1/s' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Repository path '/home/vsts/work/1/s' should be located under agent's work directory '/__w/1'.
Repository is current at '/home/vsts/work/1/s/bar', move to '/home/vsts/work/1/s'.
```

It works if I add ```target: host``` to checkout steps.

**Comment by mtene** [comment]
The issue is still not fixed. Checkouts are central to pipeline operations, so this needs to be given high priority.

**Comment by MrOwen** [comment]
Just a heads-up for anyone else implementing this fix: the workaround using `target: host` means that the working directory for the build lives on the host OS and shared to the container but is not cleaned up automatically (another bug 🙄). I found out about this the hard way because I ended up eating all the disk space on our company-shared agent pool..

The aim of the fix is to remove the contents of the `Agent.BuildDirectory` but retain any `.git` directories because if you remove those, there is a system-generated post-task which runs a `git config --unset-all http.https://[...]` and it will fail if the `.git` directory is not present. I thought of a couple of ways to go about this; one approach is to use the `DeleteFiles@1` task or you can use a script/PowerShell task to run a file deletion operation. I found that the pattern I was providing `DeleteFiles@1` to remove all except the `.git` directories was **ABYSMAL** and adding about 10 minutes runtime to our pipelines (unacceptable) so I went with the PowerShell approach. Perhaps someone can come with a better/more efficient pattern than mine for the `DeleteFiles` task but until then, here's the PS script task I ended up with (adjust paths for your use as necessary):

```yaml
- task: PowerShell@2
  displayName: 'Post: cleanup agent workspace'
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem -Path '$(Agent.BuildDirectory)\s\checkout_location_a' -Exclude .git | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
      Get-ChildItem -Path '$(Agent.BuildDirectory)\s\checkout_location_b' -Exclude .git | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
      Get-ChildItem -Path '$(Agent.BuildDirectory)' -Exclude s | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
```

Unfortunately, this causes the `.git` sub-directories to stick around but the total disk space from those should be much less than not removing _anything_ (make sure you always perform checkouts with depth 1 though). Also, I did consider setting `Process.Clean` to `false` but even that won't disable the git checkout post-tasks and disabling it may have unintended consequences. Additionally, there was a change in behavior with `Get-ChildItem`, recursion, and exclusion with PowerShell v4 (?) so my code attempts to perform deletions couldn't be fit into a one-liner.

I can't imagine my situation is all that unique; hosted Windows vms with Docker container agents. Has anyone else in this thread run into this yet? It seems like as @mtene said, this is some broken behavior in some very core functionality of the pipelines. @chshrikh or @ashokirla, thoughts?
