### ISSUE TITLE
CMake cmakeArgs does not evaluate environment variables

### ISSUE THREAD

**Issue by Lectem** [microsoft/azure-pipelines-tasks#12848]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 

CMake

## Environment
- Server - Azure Pipelines

- Agent - Private: 

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az598'
Current agent version: '2.166.4'
Current image version: '20200430.2'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.164.0)
Downloading task: CMake (1.166.0)

OS: ubuntu

## Issue Description

When using environment variables in the `cmakeArgs` parameter, the environment variables are not evaluated anymore.

For example, with the EMSCRIPTEN environment variable set in the image:

```yml

  steps:
  - script: cmake -B build-script -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake
  - task: CMake@1
    inputs:
      workingDirectory: build-task
      cmakeArgs: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake ..
```

The first script works fine, but the one with the task will give the error 

> /usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCF_USE_ISPC=OFF -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake ..
> CMake Error at /opt/cmake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
>   Could not find toolchain file:
>   $EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:19 (project)
> 

We can see that CMake receives the string with $EMSCRIPTEN instead of its value.

Multiple possibilities:
- The task cleans the environment variables (I doubt so)
- The task escapes the cmakeArgs
- The task does not go through the shell to start cmake, hence not evaluating env vars

**Comment by egor-bryzgalov** [comment]
Hello, @Lectem!

Thanks for your report! Could you please try to use macro syntax to reference EMSCRIPTEN variable in 'cmakeArgs' by wrapping the variable in parentheses like this?

`'...-DCMAKE_TOOLCHAIN_FILE=$(EMSCRIPTEN)/cmake/Modules/...'`

Please, let us know if it helps. You may also find more information about variables here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax

**Comment by Lectem** [comment]
> Could you please try to use macro syntax to reference EMSCRIPTEN variable in 'cmakeArgs' by wrapping the variable in parentheses like this?
> 
> `'...-DCMAKE_TOOLCHAIN_FILE=$(EMSCRIPTEN)/cmake/Modules/...'`

Yes I tried this too and it gave me the following:

```
/usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCF_USE_ISPC=OFF -DCMAKE_TOOLCHAIN_FILE=$(EMSCRIPTEN)/cmake/Modules/Platform/Emscripten.cmake ..
CMake Error at /opt/cmake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file:
  $(EMSCRIPTEN)/cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)
```

I think it can probably be easily reproduced with any CMake variable and a small CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.14)
message(STATUS "Value of TEST_CMAKE_TASK is: ${TEST_CMAKE_TASK}")
```

and something using an env var such as

```yml
steps:
  - script: cmake -B build-script -DTEST_CMAKE_TASK=$USER
  - task: CMake@1
    inputs:
      workingDirectory: build-task
      cmakeArgs: -DTEST_CMAKE_TASK=$USER ..
```

(I do not have time to test this right now, but it should help reproduce the issue)
