### ISSUE TITLE
Blocking Pull Request based on Full Code Coverage

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/azure-pipelines-tasks#12851]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Ask

**Enter Task Name**: Visual Studio Test v2

## Environment
- Server - Azure Pipelines 
https://office.visualstudio.com/Project/_build?definitionId=10497&_a=summary

- Agent - Hosted or Private: 
```
Pool: OE Public Pool
Agent: Agent-APP-ADOBZ-105
Agent name: 'Agent-APP-ADOBZ-105'
Agent machine name: 'APP-ADOBZ-105'
Current agent version: '2.166.2'
Agent running as: 'localAgt'
```   
## Issue Description
I have enabled the Code Coverage in the VS Test task
```
steps:
- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    testAssemblyVer2: |
     **\*unittests*.dll
     !**\obj\**
    testFiltercriteria: '(TestCategory!=LocalOnly)&(TestCategory!=IntegrationTests)'
    runSettingsFile: test/TestRunSettings/local.runsettings
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    publishRunAttachments: false
    diagnosticsEnabled: True
```

As per the instructions provided in this link - 
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops
I have added the required yml file in the repo and I am able to get the comments on the pull request. I see that we can block the pull request based on the diff coverage status.

On the similar lines, do we have anything where we can block the Pull Request based on the Full Code Coverage?
