### ISSUE TITLE
Code Coverage Summary in Build 

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/azure-pipelines-tasks#12850]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Visual Studio Test v2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
https://office.visualstudio.com/Project/_build?definitionId=10497&_a=summary

- Agent - Hosted or Private: 
```
Pool: OE Public Pool
Agent: Agent-APP-ADOBZ-105
Agent name: 'Agent-APP-ADOBZ-105'
Agent machine name: 'APP-ADOBZ-105'
Current agent version: '2.166.2'
Agent running as: 'localAgt'
```

## Issue Description
I have enabled the Code Coverage in the VS Test task
```
steps:
- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    testAssemblyVer2: |
     **\*unittests*.dll
     !**\obj\**
    testFiltercriteria: '(TestCategory!=LocalOnly)&(TestCategory!=IntegrationTests)'
    runSettingsFile: test/TestRunSettings/local.runsettings
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    publishRunAttachments: false
    diagnosticsEnabled: True
```

Once the build completes, I could see an option to download the code coverage report on the Code Coverage Tab of the build - 
![image](https://user-images.githubusercontent.com/20378231/81420008-dab4d100-916c-11ea-9569-28cfed6ab1d6.png)
But the below section is empty.
I was wondering if it is possible to have the code coverage data visualized on the build itself in some tabular format ?
