### ISSUE TITLE
JavaToolInstaller needs option for Predefined JDK

### ISSUE THREAD

**Issue by Thrameos** [microsoft/azure-pipelines-tasks#12861]
As a prior user requested in
https://github.com/MicrosoftDocs/azure-devops-docs/issues/6630

Unlike the Python tool installer, the Java one requires a large number of required arguments.  I tried now for multiple hours to get it to do the simple task of switching from one preinstalled JDK to another to test a Jar file against multiple Java versions when doing a cross platform testing of a native library.  

Please consider adding "System" or "Cache" option to "jdkSourceOption" so that the following script can work...

```
   steps:
   - task: JavaToolInstaller@0
     inputs:
        versionSpec: '8'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: Cache
   - script: run_tests.sh
   - task: JavaToolInstaller@0
     inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: Cache
   - script: run_tests.sh
```

Without having to go through the process of downloading and installing the JDK.  This option should likely be the default as it covers the needs of many users.
