### ISSUE TITLE
Azure CLI task errors, but task is marked as success

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-tasks#12874]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLIV2

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: cbinfrastructure/cbi buildId=161260

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines/Windows-2019

## Issue Description

I'm not sure if it's related to [12676](https://github.com/microsoft/azure-pipelines-tasks/pull/12676), but twice in the last week I've seen a powershell script in the azure cli task throw an error, but the task does not fail

![image](https://user-images.githubusercontent.com/18499079/81639055-ba0da500-9412-11ea-85c3-15230d9ae57a.png)

The errors show up on the pipeline summary as errors, but the task and job are still green

![image](https://user-images.githubusercontent.com/18499079/81639089-d7db0a00-9412-11ea-9e1c-4bbba2e6726b.png)

**Comment by bishal-pdMSFT** [comment]
@hbuckle can you please enable debug logs and attach it here?
Also can you please attach the yaml for your task instance.
The task will typically not fail if the script returns exit code 0

**Comment by hbuckle** [comment]
@bishal-pdMSFT - It has only happened twice so I don't have a debug log, but this is the yaml

```yaml
- task: AzureCLI@2
  displayName: terraform apply
  inputs:
    addSpnToEnvironment: true
    azureSubscription: ${{ parameters.environment.service_connections.azure_contributor }}
    workingDirectory: $(ResolvedWorkingDirectory)
    scriptType: pscore
    scriptLocation: inlineScript
    powerShellErrorActionPreference: stop
    failOnStandardError: true
    inlineScript: |
      $ErrorView = "NormalView"
      Import-Module PSDeployTools
      # various commands
      throw $stderrstring
```

The `throw` statement combined with `powerShellErrorActionPreference: stop` should cause a terminating error and fail the task, which is what usually happens
