### ISSUE TITLE
Error in post-job step of CacheV2 task when caching yarn packages

### ISSUE THREAD

**Issue by c-eliasson** [microsoft/azure-pipelines-tasks#12892]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheV2 (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2)

## Environment
- Server - Azure Pipelines
    - Account name: markethype
    - Team project name: MarketHype
    - Build ID: 1563
    - URL: https://dev.azure.com/markethype/MarketHype/_build/results?buildId=1563

- Agent - Hosted: 
    
    - Agent Queue name: Azure Pipelines (https://dev.azure.com/markethype/MarketHype/_settings/agentqueues?queueId=17&view=jobs)

## Issue Description

Using the CacheV2 task to cache Yarn packages, we're getting an error in the post-job step of the cache task.

The task is defined exactly as in [the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsyarn).

```yaml
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
```

We're using the `vs2017-win2016` image.

### Error logs

```log
Starting: Cache Yarn packages
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - yarn                         [string]
 - "Windows_NT"                 [string]
 - common/config/rush/yarn.lock [file] --> 0551FA989D7CDCB2101F1397E8E7C5468396D4C72935548B6A74BEB126F0296F
Resolved to: yarn|"Windows_NT"|57F7K6kT3NtH/ZuSuWsxueTn4wCxuYls973WEnqCJgE=
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 06101a50-81b0-41b6-ab13-b130ee5c98ae
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `yarn|"Windows_NT"|57F7K6kT3NtH/ZuSuWsxueTn4wCxuYls973WEnqCJgE=`
Information, There is a cache miss.
tar: D\:\\a\\1\\.yarn: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 06101a50-81b0-41b6-ab13-b130ee5c98ae
##[error]Process returned non-zero exit code: 2
Finishing: Cache Yarn packages
```

**Comment by jmaragon** [comment]
Same issue here, but this time with _npm_
Starting: Cache npm
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - npm                                   [string]
 - "Windows_NT"                          [string]
 - ./product/package.json [file] --> 66FF0092057590D58252E7A1365E9520D41F83083CE0C8C1DA0E038DC4C2D9D1
Resolved to: npm|"Windows_NT"|2DZ3WcfStD108j8qipq/0v97TF5eyy6fpvtPYfpDrZM=
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session xxxxxxxxxx-1282-485c-a6f4-b92a59ed4955
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `npm|"Windows_NT"|2DZ3WcfStD108j8qipq/0v97TF5eyy6fpvtPYfpDrZM=`
Information, There is a cache miss.
tar: Cannot change to directory E:\Agents\3\283\s\node_modules: No such file or directory
tar: Error is not recoverable: exiting now
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session XXXXXXXX282-485c-a6f4-b92a59ed4955
##[error]Process returned non-zero exit code: 2
Finishing: Cache npm

**Comment by stevewarsa** [comment]
Same issue here with yarn:

tar: /blah/blahgent/_work/1/s/**/node_modules, !**/node_modules/**/node_modules: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 18de2057-e96c-4ff9-9091-595b9595f5cf
##[error]Process returned non-zero exit code: 2
Finishing: Cache

Any clue how to solve?

**Comment by lesterchan** [comment]
Came in here to +1 to this, below is my config:
```
variables:
  - name: yarnCacheFolder
    value: $(Pipeline.Workspace)/.yarn

  - task: Cache@2
    displayName: Cache Yarn Packages
    inputs:
      key: yarn | $(Agent.OS) | yarn.lock
      restoreKeys: |
        yarn | $(Agent.OS)
        yarn
      path: $(yarnCacheFolder)
```

`Post-job: Cache Yarn Packages` will throw an error
```
/home/vsts/work/1/.yarn: Cannot open: No such file or directory
```

**Comment by jfheins** [comment]
For me it works, but I have set the directory directly because I found no suitable pipeline variable:

```
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | Frontend/.../yarn.lock'
          restoreKeys: yarn | "$(Agent.OS)"
          path: /home/vsts/.cache/yarn
        displayName: Cache Yarn packages
```

I'm using a hosted agent (ubuntu-18.04); maybe this works for you as well.
One can print the relevant directory for yarn with `yarn cache dir`

**Comment by jotatoledo** [comment]
@jfheins thanks for the hint.

I was able to fix this (cloud-hosting) using:

```yml
pool:
  vmImage: 'ubuntu-latest'
variables:
 - name: YARN_CONFIG_CACHE
    value: /home/vsts/.cache/yarn/v6
...
- task: Cache@2
  displayName: Cache node modules
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
    path: $(YARN_CONFIG_CACHE)
```

**Comment by bradringel** [comment]
Bumping because this is still happening and I don't think it should be closed

**Comment by sheldonlynn** [comment]
I was running into this exact issue and fixed it by adding YARN_CACHE_FOLDER to the pipeline variables.

I had the Cache task as part of a task group and in the pipeline that uses the task group, there is a required field that asks for the value of `YARN_CACHE_FOLDER` which is used as 'path' for the Cache task. Filled in the field with `$(Pipeline.Workspace)/.yarn` but the post-job kept failing with same error as above.

Once I also defined `YARN_CACHE_FOLDER=$(Pipeline.Workspace)/.yarn` in the pipeline variables, the post-job stopped failing.

**Comment by rfink** [comment]
Bump - this actually just started happening on a build that hasn't changed since December.

**Comment by loxy** [comment]
Same here for Maven:

```yml

variables:
  IS_MASTER_OR_DEVELOP: $[in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')]
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

  - task: Cache@2
    displayName: "Cache Maven local repo"
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)

  - task: Maven@3
    displayName: "Publish artifacts"
    condition: eq(variables.IS_MASTER_OR_DEVELOP, true)
    inputs:
      mavenPomFile: './pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      mavenAuthenticateFeed: true
      goals: 'deploy'
```

**Comment by kevinpiske** [comment]
Same as @loxy

**Comment by loxy** [comment]
@pradpant No, didn't found a solution

**Comment by adriansergheev** [comment]
bump!

**Comment by daerogami** [comment]
This was working in a single stage pipeline, once I added another stage that causes this to get called twice, I now get the error with the cache post-job
Local agent running Win10 pro
```
Starting: Cache Yarn packages
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - yarn                          [string]
 - "Windows_NT"                  [string]
 - src/MyProject.Web.Host/yarn.lock [file] --> A51A47DAA3D812F7DBE1028017AC2CA60169EA036A0C8BDD2DE0B6DADB8B21FE
Resolved to: yarn|"Windows_NT"|+Z30KjYR/75Haaf6MF5eU1mX/TrlZ7I5cG6FuT0QJfE=
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 7d701a80-cde5-40c0-abed-7f66814cc117
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `yarn|"Windows_NT"|+Z30KjYR/75Haaf6MF5eU1mX/TrlZ7I5cG6FuT0QJfE=`
There is a cache miss.
tar: could not chdir to 'C:\agent\_work\5\.yarn'

ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 7d701a80-cde5-40c0-abed-7f66814cc117
##[error]Process returned non-zero exit code: 1
Finishing: Cache Yarn packages
```

**Comment by nadworny** [comment]
Same here. Seems the cache plugin is broken. Found another solution here: https://xebia.com/blog/caching-your-node-modules-in-azure-devops/

**Comment by Bengkel** [comment]
I think caching will only work on a self hosted agent?

**Comment by jfheins** [comment]
> I think caching will only work on a self hosted agent?

No, this task is especially made for the Azure hosted agents. In a self hosted scenario, most of the caching works without this task. (For example: yarn has a machine wide global cache that persists in a self hosted agent)

The tricky thing is to get the cache directory right.
For example, an Azure agent mighthave the yarn cache in "/home/vsts/.cache/yarn" while a self hosted might need "/home/AzDevOps/.cache/yarn"

I'd recommend to include a step that logs out the cache directories for easier troubleshooting:

          - script: |
              node -v
              npm -v
              yarn -v
              yarn cache dir
              npm config get cache
            displayName: "Log versions & paths"

**Comment by esoxjem** [comment]
## Solution
So, the issue seems to be that `$(Pipeline.Workspace)` does not return the home directory and hence the step can't find the build folders that are typically in the home dir. Take the output from the command @jfheins posted and add that to the variable directly.

```yml
# example for .npm

# replace this
variables:
  CACHE_FOLDER: $(Pipeline.Workspace)/.npm

# with this
variables:
  CACHE_FOLDER: /home/vsts/.npm

```

## Result
Here's the result of the successful run after making the change

![Screenshot 2023-02-08 at 21 21 36](https://user-images.githubusercontent.com/7837006/217580631-88d719b0-8391-4913-8c5f-7ed2b7ac6758.png)

**Comment by vixero-dev** [comment]
I have the same error, but with pnpm. This is the yaml from the [docs](https://pnpm.io/next/continuous-integration#azure-pipelines):

```yaml
variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      pnpm install
      pnpm run build
    displayName: "pnpm install and build"
```

**Comment by johnterickson** [comment]
@vixero-dev Can you share your the log from the task failure?

A lot of these issues look like folks either aren't:
1. Setting the correct variable (as defined by the package manager) at the pipeline-level to configure where the package manager should cache things
2. Actually invoking the package manager (the cache task does not do this)

**Comment by vixero-dev** [comment]
@johnterickson you are correct. The variable wasn't being set.

After changing this part:

```yaml
  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"
```

to this:

```yaml
  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
    displayName: "setup pnpm"

  - script: pnpm config set store-dir $(pnpm_config_cache)
    displayName: "setup pnpm config"
```

I stopped experiencing this issue.

**Comment by dombarnes** [comment]
I had some similar issues that ended up being due to agents getting different versions of yarn.
I added
```
- bash: |
        corepack enable
        echo "Requesting Yarn version $(YARN_VERSION)"
        yarn set version $(YARN_VERSION)
        echo "Running Yarn $(yarn --version)"
```
along with configuring the `YARN_VERSION` variable to 3.6.4 in my case. I found out some agents would give me 1.22 sometimes in some build steps and 3.6 in others.  This helped me diagnose this.

**Comment by yooakim** [comment]
Also experience this issue when following Microsoft's  documentation. It is an issue with the paths. This [blog posts](https://josh-ops.com/posts/azdo-angular-pipeline-caching/) is a great dive into how to fix this and the Cache task.

**Comment by nickshanks347** [comment]
Try adding an `s` between `$(Pipeline.Workspace)` and `.yarn`, so variable goes from:
```text
YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
```
To:
```
YARN_CACHE_FOLDER: $(Pipeline.Workspace)/s/.yarn
```

This is because when using `checkout: self`, it checks out the repository to `$(Pipeline.Workspace)/s`, as is explained [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#:~:text=No-,Build.Repository.LocalPath,-The%20local%20path). Unless your using magic, your .yarn folder should be inside the repository.

**Comment by DxTa** [comment]
@nickshanks347 's comment is really helpful. In deed, the same also happening to other tool such as pip

**Comment by Evanion** [comment]
I tried
 ```yml
variables:
  NPM_CACHE_FOLDER: $(Pipeline.Workspace)/s/.npm
# ...
steps:
  - task: Cache@2
     displayName: Cache NPM packages
     inputs:
       key: '"npm" | "$(Agent.OS)" | package-lock.json'
       restoreKeys: |
         "npm" | "$(Agent.OS)"
         "npm"
       path: $(NPM_CACHE_FOLDER)
       cacheHitVar: NPM_CACHE_RESTORED
```
But I get 
```
Post-job: Cache NPM packages

[View raw log](https://dev.azure.com/landshypotek/980d789b-7245-4c89-a4a0-320898842fa4/_apis/build/builds/9637/logs/19)
Starting: Cache NPM packages
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - "npm"             [string]
 - "Linux"           [string]
 - package-lock.json [file] --> 0C9C69F14CFB03BABFC87109EECCB2B787FBAD0ECFC7E1F9F823A953E0A5303E
Resolved to: "npm"|"Linux"|NyzAW704Sn4J2Y1PCdbgFC5xaendrqBTYW+d+xSeAhY=
Using default max parallelism.
Using default max parallelism.
Max dedup parallelism: 192
DomainId: 0
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session ab82fec9-6c06-4dc7-9d91-1f0827ba36b5
Hashtype: Dedup64K
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `"npm"|"Linux"|NyzAW704Sn4J2Y1PCdbgFC5xaendrqBTYW+d+xSeAhY=`
There is a cache miss.
tar: /home/vsts/work/1/s/.npm: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session ab82fec9-6c06-4dc7-9d91-1f0827ba36b5
##[error]Process returned non-zero exit code: 2
Finishing: Cache NPM packages
```

I would expect the post-job to create the folder if it doesn't exist.
