### ISSUE TITLE
Error when deploying nginx-controller using helm with Azure Pipelines to AKS cluster

### ISSUE THREAD

**Issue by kuchniak** [microsoft/azure-pipelines-tasks#12964]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0

## Environment
- Server - Azure Pipelines
 
- Agent - Hosted Hosted (ubuntu-latest)

## Issue Description

When trying to deploy nginx ingress controller using helm from Azure Pipelines to AKS cluster I am reviving following error:

` ##[error]Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: customresourcedefinitions.apiextensions.k8s.io "transportservers.k8s.nginx.org" is forbidden: User "system:serviceaccount:ingress-nginx:***" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope`

This is the task:

```
trigger:
- master

stages:  
  - stage: Deploy_nginx

    jobs:
    - deployment: Github_nginx_production
      displayName: Deploy
      environment: my-env
      pool:
        vmImage: 'ubuntu-latest'

      strategy:
        runOnce:
          deploy:
             steps:
              - checkout: self
              - task: HelmInstaller@1
                displayName: Helm installer
                inputs: 
                  helmVersionToInstall: 3.1.2
              - task: HelmDeploy@0
                displayName: Helm add nginx repo
                inputs:
                  namespace: ingress-nginx
                  command: repo
                  arguments: add nginx-stable https://helm.nginx.com/stable
              - task: HelmDeploy@0
                displayName: Helm repo update
                inputs:
                  namespace: ingress-nginx
                  command: repo
                  arguments: update
              - task: HelmDeploy@0
                displayName: Helm install or upgrade
                inputs:
                  namespace: ingress-nginx
                  command: install
                  install: true
                  chartNAme: nginx-stable/nginx-ingress
                  releaseName: nginx-ingress
```

It seems that this problem is related to Service Account that has insufficient permissions in AKS cluster.

Kind Regards
