### ISSUE TITLE
How to set value of variable for Azure Pipeline FileTransform conditionally

### ISSUE THREAD

**Issue by saraswat40** [microsoft/azure-pipelines-tasks#12988]
In my yaml I have a task defined like so:

```
- ${{ each profile in parameters.targetProfile }}:
        - task: FileTransform@1
          inputs:
            folderPath: '$(System.DefaultWorkingDirectory)/**/${{ Parameters.projectDir }}/*.csdef'
```
The servicedefinition.csdef has a line like this:

`<WorkerRole name="CRWorkerRole" vmsize="#{VMSIZE}#">`
If I define the VMSIZE variable from the Azure Pipeline UI, the FileTransform works correctly. However, if I define a variable within the YAML like so:

```
variables:
      VMSIZE: 'Standard_A4_v2'
```
it doesn't work. I have tried without quotes and also assume that the spacing is correct.

Also I am running FileTransform in a loop (see above). I want to set the value of the variable 'VMSIZE' conditionally.

Is this possible?
