### ISSUE TITLE
JavaToolInstaller task cannot get JDK file from network share

### ISSUE THREAD

**Issue by sdobrodeev** [microsoft/azure-pipelines-tasks#13006]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JavaToolInstaller task cannot get JDK file from network share

## Environment
- Server - Azure Pipelines
- Agent - Private: (Windows, 2.153.1 )

**Issue description (Steps to reproduce:)**
Create and run pipelne containing `JavaToolInstaller` task call using network path as `jdkFile` parameter value:
For example:
```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: \\$(fileShareServer)\ToolInstallationsForAzureDevOps
    jdkDestinationDirectory: '$(Build.ArtifactStagingDirectory)\java'
    cleanDestinationDirectory: false
```
**Expected:**
Java is installed from the archive located on the remote server

**Actual:**
We get the following error
```
Retrieving the JDK from local path.
Creating destination folder: C:\java
##[error]UNKNOWN: unknown error, stat '\\server\server-jre-8u231-windows-x64.tar.gz'
##[error]UNKNOWN: unknown error, stat '\\server\server-jre-8u231-windows-x64.tar.gz'
##[section]Finishing: JavaToolInstaller
```
