### ISSUE TITLE
InstallAppleCertificate@2 is executed for windows

### ISSUE THREAD

**Issue by flesicek** [microsoft/azure-pipelines-tasks#13039]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: InstallAppleCertificate@2  

## Environment
- Azure Pipelines    

## Issue Description

We have in the pipeline following task:

```
steps:
- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: 'Certificates.p12'
   certPwd: '$(PASS)'
   keychain: 'temp'
   deleteCert: true
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install Certificate on Mac
```

Task is split into pre-job: Install Certificate on Mac and post-job: Install Certificate on Mac

On MacOS task is executed correctly (both pre-job and post-job)
On Windows task pre-job is skipped as expected, task post-job: Install Certificate on Mac is executed even doe the condition is set for Macos only. THIS IS THE BUG.
