### ISSUE TITLE
Azure CLI V2 sets "--allow-no-subscriptions" argument

### ISSUE THREAD

**Issue by MetalWing** [microsoft/azure-pipelines-tasks#13042]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLIV2

- Agent - Private: 

Name | Value 
-- | -- |
Agent.Version | 2.165.0
Agent.OS | Windows_NT
 Agent.OSArchitecture | X64
Agent.OSVersion | 10.0.18363
AzurePS | 1.6.1

Task YAML:
```
steps:
- task: AzureCLI@2
  displayName: 'Upload DeploymentServerInterfaceDLL to Azure'
  inputs:
    azureSubscription: 'Visual Studio Ultimate with MSDN(Converted to EA) (xxx)'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
     #my script here
    addSpnToEnvironment: true
    useGlobalConfig: true
    workingDirectory: '$(System.DefaultWorkingDirectory)\$(Release.PrimaryArtifactSourceAlias)'
```

Task fails with the following error:
**The subscription of 'xxx' doesn't exist in cloud AzureCloud'.**

I have noticed this failure in AzureCLI V2.0.14 where the only difference is "--allow-no-subscriptions" argument is being set. I am not sure why that argument is now being provided, as there have been no changes to the task on our end.
![image](https://user-images.githubusercontent.com/1570136/83433548-64bc2680-a407-11ea-89e0-7647b57d8d02.png)

Last successful run was in AzureCLI V2.0.8
![image](https://user-images.githubusercontent.com/1570136/83432514-fecf9f00-a406-11ea-81af-cacdb08fba3d.png)
