### ISSUE TITLE
HelmDeploy@0 fails when installing nginx ingress with internal loadbalancer

### ISSUE THREAD

**Issue by alert101** [microsoft/azure-pipelines-tasks#13057]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The HelmDeploy task doesn't parse annotations properly when set as arguments regardless of them being quoted or not. The value for the service.beta.kubernetes.io/azure-load-balancer-internal annotation is parsed as a boolean when it's supposed to be a string. I've tried different methods of quoting it but without luck. I've also tried moving it to the valueFile but that fails with a different error, also here I've tried quoting it in different ways. Running the same command from the CLI works.

kubectl: 1.16.9
helm: 2.16.7
repo: https://helm.nginx.com/stable

```
- task: HelmDeploy@0
  displayName: Upgrade/install nginx-ingress
  inputs:
    azureSubscriptionEndpoint: 'myServiceConnection'
    azureResourceGroup: 'myRG'
    kubernetesCluster: 'myAKS'
    command: upgrade
    install: true
    chartType: Name
    chartName: nginx-stable/nginx-ingress
    releaseName: nginx
    namespace: nginx
    valueFile: nginx-affinity.yaml
    arguments: '--set replicaCount="2" --set loadBalancerIP="10.0.0.10" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=\"true\" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet"="mySubnet"'
```

Setting the annotation in the arguments (with the value unquoted) results in the following command:
```
helm upgrade --namespace nginx --install --values /.../nginx-affinity.yaml --wait --set replicaCount=2 --set loadBalancerIP=10.0.0.10 --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-internal=true --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet=mySubnet nginx nginx-stable/nginx-ingress
```
Which fails with the following error:
```
##[error]Error: release nginx failed: Service in version "v1" cannot be handled as a Service: v1.Service.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|nternal":true,"servi|..., bigger context ...|beta.kubernetes.io/azure-load-balancer-internal":true,"service.beta.kubernetes.io/azure-load-balance|...
```
Setting the annotation in the arguments (with the value quoted) results in the following command where the azure-load-balancer-internal syntax is broken:
```
helm upgrade --namespace nginx--install --values /.../nginx-affinity.yaml --wait --set replicaCount=2 --set loadBalancerIP=10.0.0.10 --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-internal=\true" --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet=mySubnet nginx nginx-stable/nginx-ingress
```

Setting the annotation in the valueFile results in the following error:
```
##[error]panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
```

Running this from the command line works:
```
helm upgrade --namespace nginx --install --set controller.service.loadBalancerIP="10.0.0.10"  --set controller.replicaCount="2" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=\"true\" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet"="mySubnet" -f nginx-affinity.yaml nginx nginx-stable/nginx-ingress
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by shigupt202** [comment]
@alert101 An override.yaml value file seems to be the best approach for key-values with double quotes. Can you please share your `valueFile` that you used?
Also, for single quotes

**Comment by alert101** [comment]
Here's the override.yaml with double quotes:
```
controller:
  replicaCount: 1
  service:
    loadBalancerIP: "10.0.0.10"
    annotations:
    - service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    - service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "mySubnet"
```
Error is:
Error: YAML parse error on nginx-ingress/templates/controller-service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .metadata.annotations of type map[string]string

I also tried with single quotes:
```
...
    - service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
    - service.beta.kubernetes.io/azure-load-balancer-internal-subnet: 'mySubnet'
```
Same error as above.

And with double single quotes:
...
    - service.beta.kubernetes.io/azure-load-balancer-internal: ''true''
    - service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ''mySubnet''
```
Different error:
Error: failed to parse /.../override.yaml: error converting YAML to JSON: yaml: line 5: did not find expected key

Trying your workaround with double single quotes in the args results in this command:
```
helm upgrade --namespace nginx --install --values /.../override.yaml --wait --set replicaCount=1 --set loadBalancerIP=10.0.0.10 --set controller.service.annotations.'service\.beta\.kubernetes\.io/azure-load-balancer-internal'='true' --set controller.service.annotations.'service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet'=mySubnet nginx nginx-stable/nginx-ingress
```
Which results in this error:
```
##[error]Error: release nginx failed: Service "nginx-nginx-ingress" is invalid: [metadata.annotations: Invalid value: "'service.beta.kubernetes.io/azure-load-balancer-internal'": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "'service.beta.kubernetes.io/azure-load-balancer-internal'": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.annotations: Invalid value: "'service.beta.kubernetes.io/azure-load-balancer-internal-subnet'": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "'service.beta.kubernetes.io/azure-load-balancer-internal-subnet'": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
```
I'm guessing single quotes isn't a valid syntax. I also tried different variations of the workaround but none worked, either the same error as this last one or the first error.

**Comment by shigupt202** [comment]
Can you try with this override file:
```
controller:
  replicaCount: 1
  service:
    loadBalancerIP: "10.0.0.10"
    annotations:
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
      "service.beta.kubernetes.io/azure-load-balancer-internal-subnet": "mySubnet"
```
