### ISSUE TITLE
Task DeleteFiles is deleting source even though is set to false

### ISSUE THREAD

**Issue by ylr-research** [microsoft/azure-pipelines-tasks#13078]
**Question**  
How to delete files from a folder without deleting the folder?

**Enter Task Name**: DeleteFiles  

## Environment
- Server - Azure Pipelines    
    - account: ylr.reasearch, 
    - team project: demo-deployment, 
    - build definition: geocodingapi-ci/20200606.10

- Agent - Hosted: 
    - fv-az674/Job 63:

## Issue Description
```
- task: DeleteFiles@1
  displayName: 'Remove configuration files'
  inputs:
    SourceFolder: 'GeoCodingAPI/ConfigurationFiles'
    Contents: '*'
    RemoveSourceFolder: false
```
