### ISSUE TITLE
Root paths in executing docker file are different

### ISSUE THREAD

**Issue by mehdihadeli** [microsoft/azure-pipelines-tasks#13110]
Hi,
I have this YAML file:

```
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: chmod -R a+x scripts
      displayName: before_script

    - bash: ./scripts/dotnet-build.sh
      displayName: run_build_script

    - bash: ./scripts/dotnet-test.sh
      displayName: run_test_script


    - bash: ./scripts/docker-publish-pipelines-azure-devops.sh
      env:
        Build_SourceBranchName: $(Build.SourceBranchName)
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

      displayName: run_docker-publish-pipelines-azure-devops_script

    - bash: ./scripts/after-success.sh
      displayName: run_after-success_script
````

-----------------------------------------------------------------------------
docker-publish-pipelines-azure-devops.sh

```
DOCKER_ENV=''
DOCKER_TAG=''
echo Branch Name is $Build_SourceBranchName
case "$Build_SourceBranchName" in
  "master")
    DOCKER_ENV=production
    DOCKER_TAG=latest
    ;;
  "develop")
    DOCKER_ENV=development
    DOCKER_TAG=dev
    ;;    
esac

dotnet publish ./src/Fibon.Api -c Release -o ./bin/Docker
dotnet publish ./src/Fibon.Service -c Release -o ./bin/Docker
ls ./bin/Docker
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

docker build -f ./src/Fibon.Api/Dockerfile.$DOCKER_ENV -t fibon-api:$DOCKER_TAG ./src/Fibon.Api --no-cache
docker build -f ./src/Fibon.Service/Dockerfile.$DOCKER_ENV -t fibon-service:$DOCKER_TAG ./src/Fibon.Service --no-cache

docker tag fibon-api:$DOCKER_TAG $DOCKER_USERNAME/fibon-api:$DOCKER_TAG
docker tag fibon-service:$DOCKER_TAG $DOCKER_USERNAME/fibon-service:$DOCKER_TAG

docker push $DOCKER_USERNAME/fibon-api:$DOCKER_TAG
docker push $DOCKER_USERNAME/fibon-service:$DOCKER_TAG
```
---------------------------------------------------------------------------
DockerFile

```
FROM microsoft/dotnet:2.0.0-runtime
WORKDIR /dotnetapp
COPY ./bin/Docker .
ENV ASPNETCORE_ENVIRONMENT docker
ENTRYPOINT dotnet Fibon.Api.dll --urls "http://*:5000"
```

My problem is my root path in the bash file `docker-publish-pipelines-azure-devops.sh` with executing  this command `dotnet publish ./src/Fibon.Api -c Release -o ./bin/Docker`  for `bin/Docker` folder will be `/home/vsts/work/1/s/bin/Docker/` but with executing my DockerFile inner this bash file root path for this command `COPY ./bin/Docker  .` for` bin/Docker` folder will be `/var/lib/docker/tmp/docker-builder234913245/bin/Docker`. why they are different I want they be the same.
