### ISSUE TITLE
AzureFileCopy@4 does not set storage container URI ans SAS token variables

### ISSUE THREAD

**Issue by jgierveld** [microsoft/azure-pipelines-tasks#13129]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopy@4

## Environment

Azure Pipelines hosted - windows-latest

## Issue Description

In V4 it's not possible anymore to provide the variables to store the storage container URI and SAS token. Based on the source code, I assume they are supposed to be stored in `StorageContainerUri` and `StorageContainerSasToken`. However, these variables are not set

Is this a bug? At first glance, there seem to be semicolons missing in the lines setting the variables. However, the task doesn't fail.

Snippet from [AzureFileCopy.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFileCopyV4/AzureFileCopy.ps1):
```
    # Complete the task if destination is azure blob
    if ($destination -eq "AzureBlob")
    {
        # Get URI and SaSToken for output variable
        $storageAccountContainerURI = $storageContext.BlobEndPoint + $containerName + "/"
        Write-Host "##vso[task.setvariable variable=StorageContainerUri]$storageAccountContainerURI"
        
        
        $storageContainerSaSToken = Generate-AzureStorageContainerSASToken -containerName $containerName -storageContext $storageContext -tokenTimeOutInMinutes $sasTokenTimeOutInMinutes
        Write-Host "##vso[task.setvariable variable=StorageContainerSasToken]$storageContainerSasToken"

        Remove-EndpointSecrets
        Write-Verbose "Completed Azure File Copy Task for Azure Blob Destination"
        
        return
    }
```

Input:
```
- task: AzureFileCopy@4
  inputs:
    SourcePath: '<path>'
    azureSubscription: '<subscription>'
    Destination: 'AzureBlob'
    storage: '<storage>'
    ContainerName: '<container>'
    BlobPrefix: '<prefix>'
    CleanTargetBeforeCopy: true
    sasTokenTimeOutInMinutes: '30'
```
