### ISSUE TITLE
Dotnet restore slow and slower with Cache 

### ISSUE THREAD

**Issue by musmuris** [microsoft/azure-pipelines-tasks#13127]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DotNetCoreCLI@2

## Environment
Azure Pipelines hosted - windows-latest 

## Issue Description

Trying out Azure Pipelines on one of our simpler projects and the whole build is taking ~2 mins. However it took 42 seconds just to do the dotnet restore step.  In an effort to make this faster I added a cache task but next time, even when the cache restored (in just 7 seconds) it then took 57 seconds to do the restore.

```
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/*.csproj'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(Pipeline.Workspace)/.nuget/packages
  displayName: Cache NuGet packages

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(solution)
    feedsToUse: 'select'
    verbosityRestore: 'Normal'
```

Task log files
[nocacherestore.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4785295/nocacherestore.txt)
[cachedrestore.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4785296/cachedrestore.txt)
