### ISSUE TITLE
Can I filter projects using "command: test" in task DotNetCoreCLI@2?

### ISSUE THREAD

**Issue by tonholis** [microsoft/azure-pipelines-tasks#13145]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DotNetCoreCLI@2  

This is my task:
```
  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: "test"
      projects: "**/*.Test.csproj;!**/*.TestX.csproj"
```

I tried that and I get the warning in the logs.

    ##[warning]Project file(s) matching the specified pattern were not found.

So apparently the command `test` doesn't support filters.

Is that right?

**Comment by anuragc617** [comment]
@phanikmmsft please have a look at this question.

**Comment by mishfit** [comment]
This doesn't appear to work if I specify multiple patterns (to overcome the lack of an _except_ syntax):

```
- task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: "test"
      projects: "**/*/A.Tests.csproj;*/*/B.Tests.csproj;**/*/C.Tests.csproj"
```
