### ISSUE TITLE
Please add $(go env GOPATH)/bin to $PATH

### ISSUE THREAD

**Issue by arvenil** [microsoft/azure-pipelines-tasks#13140]
Right now I can't install go tools.

```
stages:
  - stage: tools
    dependsOn: []
    displayName: Tools
    jobs:
      - job: tools
        steps:
          - script: go get github.com/golangci/golangci-lint/cmd/golangci-lint
          - script: golangci-lint --version
```
This results in:
```
golangci-lint: command not found
```
Please add `$(go env GOPATH)/bin` to `$PATH` or
```
GOBIN=$(go env GOPATH)/bin
PATH=$GOBIN:$PATH
```
