### ISSUE TITLE
KubernetesManifest@0 is not deploying baked kustomize files

### ISSUE THREAD

**Issue by Eossu** [microsoft/azure-pipelines-tasks#13173]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetsManifest@0

list here (V# not needed):  
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: free tier

## Issue Description

When baking kustomize files as seen here we are getting an error fomr kubectl as seen in Task Logs

```
  - task: KubernetesManifest@0
    displayName: Create K8S manifest files
    name: bake
    inputs:
      action: bake
      renderType: kustomize
      kustomizationPath: ${{parameters.KustomizePath}}

  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests
    inputs:
      action: deploy
      manifests: $(bake.manifestsBundle)
      containers: |
        ###.azurecr.io/${{parameters.DockerImage}}:${{parameters.Tag}}
```

### Task logs

```
Starting: Deploy K8s manifests
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.169.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-k8s-manifest-tsg
==============================================================================
==============================================================================
			Kubectl Client Version: v1.18.3
			Kubectl Server Version: v1.15.11
==============================================================================
/usr/bin/kubectl apply -f  --namespace some-namespace
error: must specify one of -f and -k
##[error]error: must specify one of -f and -k
Finishing: Deploy K8s manifests
```
