### ISSUE TITLE
NuGet restores Service Fabric project with .NET Framework 4.7.2 instead of .NET Core 3.1

### ISSUE THREAD

**Issue by secret-agent-B** [microsoft/azure-pipelines-tasks#13226]
I've been trying to setup a SeviceFabric CI in DevOps and I am unable to find a way to tell MSBuild that my app is a .NET Core app and not a .NET Framework 4.7.2 app. Is there another way to do that from within my project file aside from the usual .NET Core TargetFramework element in csproj file so MSBuild stops thinking that it is a .NET Framework app?

Type: Question
Task Name: MSBuild
Agent: Hosted

![image](https://user-images.githubusercontent.com/15314841/86401678-477db080-bc70-11ea-96c0-d1ffa3d449e1.png)

```
pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - Cmd

variables:
  BuildPlatform: 'x64'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.x'
  inputs:
    version: 3.1.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

============================
===This is where it fails===
============================
- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:Deterministic=true /p:PathMap=$(Agent.BuildDirectory)=C:\'

- task: MSBuild@1
  displayName: 'Build solution **\*.sfproj'
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\applicationpackage'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\pdbs'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)\applicationpackage'
    Contents: '**\*.pdb'
    TargetFolder: '$(build.artifactstagingdirectory)\pdbs'

- task: DeleteFiles@1
  displayName: 'Delete files from $(build.artifactstagingdirectory)\applicationpackage'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)\applicationpackage'
    Contents: '**\*.pdb'

- task: ServiceFabricUpdateManifests@2
  displayName: 'Update Service Fabric Manifests (Manifest versions)'
  inputs:
    applicationPackagePath: '$(build.artifactstagingdirectory)\applicationpackage'
    versionSuffix: '.$(build.buildnumber)'
    updateOnlyChanged: true
    pkgArtifactName: drop

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\projectartifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\PublishProfiles\*.xml
     **\ApplicationParameters\*.xml
    TargetFolder: '$(build.artifactstagingdirectory)\projectartifacts'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
```

Fails with error

`##[error]The nuget command failed with exit code(1) and error(NU1201: Project Delivery is not compatible with net472 (.NETFramework,Version=v4.7.2). Project Delivery supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)`

**Comment by temelj** [comment]
Can I ask a question please:
Was the SF app created from the "Visual Studio - New Project Template? Because as you create a new SF project, it asks for the framework which is the full .NETFramework 4.7/4.8. Once you create that, you need to specify the Service Fabric Service and your options are:
.NET Core - Stateless, Stateful, Stateless ASP.NET Core, Stateful ASP.NET Core
.NET Framework (4.7/4.8) - Stateless Service, Stateful Service, Stateless ASP.NET Core, Stateful Asp.NET Core (requiring .NET Core SDK 2.1)

Reason I ask is: 
If you went with the SF Project Template using a .NET Core service (which uses .NET Core) then your build pipeline may require both nuget restore and dotnet restore 

See doco here on NuGetCommand@2 - https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops

>Use this task to install and update NuGet package dependencies, or package and publish NuGet packages. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.

**Comment by secret-agent-B** [comment]
The only options there when I created the service fabric project was .NET Framework. But the service within we're all created using .NET Core.

**Comment by secret-agent-B** [comment]
I will replace those steps with .NET Core tasks. Thank you.

**Comment by secret-agent-B** [comment]
I am now able to build the .NET Core projects but when I build the .sfproj project using NuGet restore, it fails because the .NET Core services are referenced by that project and it tries to do the same thing it was doing before,

![image](https://user-images.githubusercontent.com/15314841/86421517-f1c0fc80-bc9f-11ea-8748-8e0afa2319d9.png)

**Comment by temelj** [comment]
Correct I was expecting that. You need a dotnetcore take to restore core packages and another classic nuget task  to restore sfproj packages

**Comment by secret-agent-B** [comment]
That is what I did. You'll notice on the screenshot that I have .NET Core tasks to take care of the .NET Core projects and the I have the NuGet restore only restoring the sfproj. Would you like me to add a .NET Core task to restore the sfproj too for its .NET Core references?

**Comment by secret-agent-B** [comment]
Yeah, adding a .NET Core task to build the sfproj didn't work.

**Comment by temelj** [comment]
top of yaml to define some variables
```
variables:
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: x64
- name: AppPackageLocation
  value: $(Build.ArtifactStagingDirectory)/applicationpackage
```
later in the yaml at the BUILD step
```
    - task: DotNetCoreCLI@2
      displayName: 'Restore Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        ##feedsToUse: 'config'
        ##nugetConfigPath: 'NuGet.Config'
        feedsToUse: 'select'
        vstsFeed: 'PRIVATE_FEED_GUID'
        includeNuGetOrg: false
    - task: NuGetCommand@2
      displayName: Restore packages
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sfproj'
        ##feedsToUse: 'config'
        ##nugetConfigPath: 'NuGet.Config'
        feedsToUse: 'select'
        vstsFeed: 'PRIVATE_FEED_GUID'
        includeNuGetOrg: false
        restoreDirectory: packages
    - task: VSBuild@1
      displayName: 'Build solution (release)'
      enabled: false
      inputs:
        solution: '**\*.sln'
        vsVersion: latest
        platform: '$(BuildPlatform)'
        configuration: $(BuildConfiguration)
        clean: true
    - task: VSBuild@1
      displayName: 'Build solution for Service Fabric'
      inputs:
        solution: '**\*.sfproj'
        vsVersion: latest
        msbuildArgs: '/t:Package /p:PackageLocation=$(AppPackageLocation)'
        platform: '$(BuildPlatform)'
        configuration: $(BuildConfiguration)
    - task: ServiceFabricUpdateManifests@2
      displayName: 'Update Service Fabric Manifest Versions'
      inputs:
        applicationPackagePath: '$(AppPackageLocation)'
        versionSuffix: '$(Build.BuildNumber)'
        versionBehavior: Replace
        updateOnlyChanged: true
        pkgArtifactName: drop
```

**Comment by temelj** [comment]
> top of yaml to define some variables
> 
> ```
> variables:
> - name: BuildConfiguration
>   value: Release
> - name: BuildPlatform
>   value: x64
> - name: AppPackageLocation
>   value: $(Build.ArtifactStagingDirectory)/applicationpackage
> ```
> 
> later in the yaml at the BUILD step
> 
> ```
>     - task: DotNetCoreCLI@2
>       displayName: 'Restore Packages'
>       inputs:
>         command: 'restore'
>         projects: '**/*.csproj'
>         ##feedsToUse: 'config'
>         ##nugetConfigPath: 'NuGet.Config'
>         feedsToUse: 'select'
>         vstsFeed: 'PRIVATE_FEED_GUID'
>         includeNuGetOrg: false
>     - task: NuGetCommand@2
>       displayName: Restore packages
>       inputs:
>         command: 'restore'
>         restoreSolution: '**/*.sfproj'
>         ##feedsToUse: 'config'
>         ##nugetConfigPath: 'NuGet.Config'
>         feedsToUse: 'select'
>         vstsFeed: 'PRIVATE_FEED_GUID'
>         includeNuGetOrg: false
>         restoreDirectory: packages
>     - task: VSBuild@1
>       displayName: 'Build solution (release)'
>       enabled: false
>       inputs:
>         solution: '**\*.sln'
>         vsVersion: latest
>         platform: '$(BuildPlatform)'
>         configuration: $(BuildConfiguration)
>         clean: true
>     - task: VSBuild@1
>       displayName: 'Build solution for Service Fabric'
>       inputs:
>         solution: '**\*.sfproj'
>         vsVersion: latest
>         msbuildArgs: '/t:Package /p:PackageLocation=$(AppPackageLocation)'
>         platform: '$(BuildPlatform)'
>         configuration: $(BuildConfiguration)
>     - task: ServiceFabricUpdateManifests@2
>       displayName: 'Update Service Fabric Manifest Versions'
>       inputs:
>         applicationPackagePath: '$(AppPackageLocation)'
>         versionSuffix: '$(Build.BuildNumber)'
>         versionBehavior: Replace
>         updateOnlyChanged: true
>         pkgArtifactName: drop
> ```
> 
> Keep in mind that I've used a private feed to fetch some packages from - you probably don't need that.
> 
> Also keep in mind that `- task: DotNetCoreCLI@2` can restore & build directly from a `**/*.sln` file - i am yet to try that out to see if the double restore & build steps are even required.

Probably are because DotNetCoreCLI will target only .NET Core SDK
but to build `*.sfproj` you need to target the full .NET 4.7/4.8 framework

**Comment by secret-agent-B** [comment]
I get that sfproj needs the full .NET 4.7/4.8 Framework and to do that you'll need to use the NuGet task. The issue now is that my services are .NET Core and are being referenced by the sfproj. So now whenever I try to build sfproj I get `

**Comment by temelj** [comment]
I have a project with exactly that scenario and it is restoring, building and deploying fine.

Basically, i don't think it is an issue with the azure pipelines tasks, but more about how they are being applied for your particular usecase.

**Comment by secret-agent-B** [comment]
I created a new project with an empty .NET Core in a new repo with a new Pipeline and I get the same result. Not really sure what I am missing here.

**Comment by temelj** [comment]
Might we worth while posting some logs? (and your updated pipeline yaml) I am not sure how else to help.
I've been successfully restoring, building and deploying Service Fabric Apps (with .NET Core 3.1 web api project) to an on-prem cluster for a while.

Are you still doing it in this order?
```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.x'
  inputs:
    version: 3.1.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

============================
===This is where it fails===
============================
- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:Deterministic=true /p:PathMap=$(Agent.BuildDirectory)=C:\'

- task: MSBuild@1
  displayName: 'Build solution **\*.sfproj'
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\applicationpackage'
```

because that's nothing like I've commented above.  - ie:  MSBUILD Solution is wrong to start off with
