### ISSUE TITLE
Documentation: AzureFileCopyV4 output variable documentation incomplete

### ISSUE THREAD

**Issue by soccerjoshj07** [microsoft/azure-pipelines-tasks#13246]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

documentation issue

**Enter Task Name**: AzureFileCopyV4  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4

## Environment
- Server - Azure Pipelines
   
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: n/a

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

## Issue Description

The [AzureFileCopyV4](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4) task has poor documentation on working with its output variables. In v3, the variables outputted were task inputs. In v4, they are created as [output variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks) (and not defined in the task ui). The documentation between v3 and v4 does not change in any way to reflect this.

You have to know to dig into the [task code](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFileCopyV4/AzureFileCopy.ps1#L197) to find out that the output variables are titled:

- StorageContainerUri
- StorageContainerSasToken

Following the [output variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks) documentation, we can then reference the variables like so:

```
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'Readme.md'
    azureSubscription: 'Test'
    Destination: 'AzureBlob'
    storage: 'azdo'
    ContainerName: 'workshops'
    BlobPrefix: ''
  name: AzureFileCopy
- script: | 
    echo $(AzureFileCopy.StorageContainerUri)
    echo $(AzureFileCopy.StorageContainerSasToken)
```

I can submit a PR for the readme update if desired.   Thanks

### Task logs

N/a

## Troubleshooting
n/a

### Error logs

n/a
