### ISSUE TITLE
dotnet pack does not support -p:PackageID

### ISSUE THREAD

**Issue by graphicsxp** [microsoft/azure-pipelines-tasks#13245]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotnetCoreCli@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
  In local environment I'm able to customize my packages name by running the following command : 

        dotnet pack  .\$(ProjectName).csproj  --include-symbols --no-build -p:PackageID=CustomName.$(ProjectName)

I don't see how to do that with the task when I build with the azure pipeline . Is this supported ?

**Comment by musmuris** [comment]
I found the same thing - I've been using a custom one for now

```yaml
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: pack
    arguments: >
      path/to/the.csproj
      --no-build
      -p:PackageId=$(thisPackageId)
      --output $(Build.ArtifactStagingDirectory)
      -p:PackageVersion=$(buildVersion)
      -p:Configuration=$(buildConfiguration)
```
