### ISSUE TITLE
Provide mechasnism to opt-out of DotNetCoreCLIV2 deprecation warnings

### ISSUE THREAD

**Issue by jpobst** [microsoft/azure-pipelines-tasks#13249]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Every time the `DotNetCoreCLIV2` task is used it now outputs this warning:

```
##[warning].NET Core SDK/runtime 2.2 and 3.0 are now End of Line(EOL) and have been removed from all agents. If you're using these SDK/runtimes, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the requied version.
```

This warning is displayed even if you aren't using 2.2 or 3.0, and there doesn't seem to be any way to opt out of this message.  We are using:
```
- task: UseDotNet@2
  inputs:
    version: 3.1.300
```

This task needs to either:
* Ideally, detect the version of .NET Core in use and not display this warning
* Allow us to set an environment variable (or something) to not display the warning

This message spams our logs and hides warnings that may be actual problems:
![image](https://user-images.githubusercontent.com/179295/87062245-6df09e00-c1d2-11ea-82ab-529325167666.png)

**Comment by bishal-pdMSFT** [comment]
@tejasd1990

**Comment by mconnew** [comment]
Detecting the version being used isn't going to work across the board. Some commands don't have a version specified. For example, I have the following in my pipeline and it still emits that warning:
```yaml
      - task: DotNetCoreCLI@2
        displayName: 'Install gitversion'
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'install -g gitversion.tool --version 5.3.7'
```
