### ISSUE TITLE
PublishTestResults@2: Duration of multiple test suites is not aggregated

### ISSUE THREAD

**Issue by eggilbert** [microsoft/azure-pipelines-tasks#13280]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: `Bug`

**Enter Task Name**: `PublishTestResults@2`

## Environment
- Server - Azure Pipelines 
- Agent - Private (`2.166.4` on Linux x64)

## Issue Description
`PublishTestResults@2` does not handle the _duration_ of multiple JUnit `<testsuite/>` as expected. I found https://github.com/microsoft/azure-pipelines-tasks/issues/7659 which points out that multiple `<testsuite/>` visually are flattened together and the hierarchy is lost in the results (which is the case for me as well), but I haven't found any open issues about the reported run duration of multiple `<testsuite/>`.

Based on my testing, as far as I can tell when there are multiple `<testsuite/>` present `PublishTestResults@2` will just report whichever _**is longest**_, rather than aggregating the times together. The total number of test cases and their results are combined correctly (with the loss of hierarchy), but the duration is not.

This is extra confusing as there is a `mergeTestResults` [configuration option](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#arguments) seemingly designed for this use case where the testing framework produced multiple output files that should be consumed together.
- Using JUnit 5 and the `maven-surefire-plugin` each java test class produces a separate JUnit XML with its own `<testsuite/>`.
- This `mergeTestResults` option is documented as defaulting to `false` where each test result file matching the `testResultsFiles` pattern should produce its own individual test run. However, there seems to be some undocumented limit where if there's enough files found the task will force this to `true` and combine everything together (as you'd likely want) but then the reported timing is incorrect.
- I've also tested this out using the `Maven@3` task instead of `PublishTestResults@2` and had identical behavior. All of the produced test results were published as a single test run, but the reported time was only the longest individual `<testsuite/>`.

### Example
```yaml
- job: Example
  steps:
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/demo-partial-run/TEST-example-1.xml'
        testRunTitle: Test suite 1
        searchFolder: $(System.DefaultWorkingDirectory)
        failTaskOnFailedTests: true

    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/demo-partial-run/TEST-example-2.xml'
        testRunTitle: Test suite 2
        searchFolder: $(System.DefaultWorkingDirectory)
        failTaskOnFailedTests: true

    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/demo-partial-run/TEST-*.xml'
        testRunTitle: Merge both test suites
        searchFolder: $(System.DefaultWorkingDirectory)
        failTaskOnFailedTests: true
        mergeTestResults: true  # Report both of the above together in a single run

    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/demo-full-run/TEST-*.xml'  # Report 200+ files at once; mergeTestResults not set
        testRunTitle: Full run gets auto-merged
        searchFolder: $(System.DefaultWorkingDirectory)
        failTaskOnFailedTests: true
```

![image](https://user-images.githubusercontent.com/6200216/87331343-6e08da80-c4ff-11ea-9531-cffaa1cd7b0f.png)

### Workaround
The only thing I've been able to get to work around this successfully is to write an ugly bash task that produces a single XML file with a _single_ `<testsuite/>` that has the _sum_ of all of the attributes on the individual `<testsuite/>` elements, and containing all of the individual `<testcase/>` results smashed together.

When published as a single file with only one `<testsuite/>` everything appears to be consumed and reported correctly. This is better than nothing as the delta of total time can be computed across builds properly.

However, some potentially important context is lost as time spent in a `@BeforeAll` is reported against the `<testsuite/>` as it's not tied to any individual `<testcase/>`. When all of the `<testsuite/>` are combined together this extra time is no longer associated with the related test cases. This is information I'd expect to see in the visual hierarchy (https://github.com/microsoft/azure-pipelines-tasks/issues/7659) too.
