### ISSUE TITLE
Evaluating environment dependent secret names in AzureKeyVault task

### ISSUE THREAD

**Issue by cbb330** [microsoft/azure-pipelines-tasks#13321]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureKeyVault@1

## Issue Description

I have an AzureKeyVault task that will run in three environments: Dev, Lab, and Prd.

Each environment has a Key Vault named: dev-kv, lab-kv, and prd-kv.

Each key vault has secrets following this naming convention named: dev-password, lab-password, and prd-password.

Below is the task to retrieve these secrets, with the environment passed in as a parameter:
```yaml
- task: AzureKeyVault@1
  inputs:
    azureSubscription: $(connectionService)
    keyVaultName: ${{ parameters.environment }}-kv
    secretsFilter: ${{ parameters.environment }}-password
```

This appears to retrieve the secret correctly, as the task doesn't give an error. An error is normally thrown if the secret name cannot be found. 

However, on attempting to use this secret as an input to another task, the variable cannot be accessed. For example: 

```yaml
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(connectionService)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    csmFile: $(armTemplateLocation)
    csmParametersFile: $(armTemplateParametersLocation)
    overrideParameters: >-
      -ResourcePassword $(${{ parameters.environment }}-password)
    deploymentMode: Incremental
    deploymentOutputs: resourceGroupDeploymentOutputs
```

This will evaluate the 'ResourcePassword' input as a string literally being: '$(dev-password)'

My question is: **Why is the variable not being evaluated at runtime?** Its especially confusing as clearly the pre-processing is completing as intended as ${{ parameters.environment }} has evaluated to 'dev'. 

Without the variable being properly evaluated at runtime, it is impossible to use a naming convention or calculated secret name in pipelines for Azure Key Vault.

I have also tried $[variables['${{ parameters.environment}}-password']] as an input to 'ResourcePassword' but getting the same evaluation issue. 

Thanks,
Christian.
