### ISSUE TITLE
PublishToAzureServiceBus doesn't resolve parameter for connectedServiceName

### ISSUE THREAD

**Issue by sebastienros** [microsoft/azure-pipelines-tasks#13326]
*Type*: Question/Bug
__PublishToAzureServiceBus__ 

I defined a job with a matrix of parameters. When binding a parameter to the `connectedServiceName` property of __PublishToAzureServiceBus__ the value `$(connection)` is seen instead of the actual value of the parameter. When used in the `displayName` property it shows up correctly, like `"My Service Bus Queue"`.

Here is an example of usage

```
  - task: PublishToAzureServiceBus@1
    displayName: "${{ s.displayName }} ${{ parameters.connection }}"
    inputs:
      connectedServiceName: ${{ parameters.connection }}
```

Looking at the definition of the task, this property is defined like this:

```
            "name": "connectedServiceName",
            "aliases": [
                "azureSubscription"
            ],
            "type": "connectedService:AzureServiceBus",
            "label": "Azure Service Bus service connection",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Select an Azure Service Bus service connection."
```

Is it possible that the fact it's not a `string` type would prevent from using parameters to be bound to it?
Is there another way to pass its value from a parameter in the invoking template?
