### ISSUE TITLE
Permissions error using downloadbuildartifact.  What Permisions???

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/azure-pipelines-tasks#13357]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DownloadBuildArtifacts@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: iMSTraining/RMS, RMS, 14.08.1002.0

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10 (Version 10.0.18363.959), vsts-agent-win-x64-2.168.2

## Issue Description

We are getting a permission related error but don't know what permissions are missing.  The build artifact does exist.
Task definition:
```
 # Download build artifacts
    # Download files that were saved as artifacts of a completed build
    - task: DownloadBuildArtifacts@0
      displayName: 'Download latest TestTool build'
      inputs:
        buildType: 'specific' # Options: current, specific
        project: 'TestTool' # Required when buildType == Specific
        pipeline: 'TestTool-bld' # Required when buildType == Specific
        #specificBuildWithTriggering: false # Optional
        buildVersionToDownload: 'latest' # Required when buildType == Specific. Options: latest, latestFromBranch, specific
        allowPartiallySucceededBuilds: false # Optional
        branchName: 'refs/heads/master' # Required when buildType == Specific && BuildVersionToDownload == LatestFromBranch
        #buildId: # Required when buildType == Specific && BuildVersionToDownload == Specific
        #tags: # Optional
        downloadType: 'single' # Choose whether to download a single artifact or all artifacts of a specific build. Options: single, specific
        artifactName: 'TestTool' # Required when downloadType == Single
        itemPattern: '**/**' # Optional
        downloadPath: '$(Build.ArtifactStagingDirectory)' 
        parallelizationLimit: '8' # Optional

```
![image](https://user-images.githubusercontent.com/4333956/88549475-3c703300-d018-11ea-805e-602b7a7a3605.png)

> Failed in getBuildDefinitions with error: Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.

### Task logs

##[debug]check path : C:\EvolveiMS\Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.167.2\node_modules\artifact-engine\lib.json
##[debug]adding resource file: C:\EvolveiMS\Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.167.2\node_modules\artifact-engine\lib.json
##[debug]system.culture=en-US
##[debug]check path : C:\EvolveiMS\Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.167.2\task.json
##[debug]adding resource file: C:\EvolveiMS\Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.167.2\task.json
##[debug]system.culture=en-US
##[debug]buildType=specific
##[debug]specificBuildWithTriggering=false
##[debug]buildVersionToDownload=latest
##[debug]allowPartiallySucceededBuilds=false
##[debug]branchName=refs/heads/master
##[debug]downloadPath=C:\EvolveiMS\Agent\_work\10\a
##[debug]downloadType=single
##[debug]tags=null
##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/iMSTraining/
##[debug]SYSTEMVSSCONNECTION auth param AccessToken = ***
##[debug]VSTS_HTTP_RETRY=undefined
##[debug]release.triggeringartifact.alias=undefined
##[debug]definition=TestTool-bld
##[debug]project=TestTool
##[debug]buildId=null
Error: in getBuildDefinitions, so retrying => retries pending  : 4
Error: in getBuildDefinitions, so retrying => retries pending  : 3
Error: in getBuildDefinitions, so retrying => retries pending  : 2
Error: in getBuildDefinitions, so retrying => retries pending  : 1
##[error]Failed in getBuildDefinitions with error: Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.
##[debug]Processed: ##vso[task.issue type=error;]Failed in getBuildDefinitions with error: Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.
##[debug]SYSTEM.HOSTTYPE=build
##[debug]BUILD.DEFINITIONNAME=RMS
##[debug]BUILD.BUILDID=118
##[debug]SYSTEM.TEAMFOUNDATIONSERVERURI=https://dev.azure.com/iMSTraining/
##[debug]SYSTEM.TEAMPROJECT=RMS
##[debug]BUILD.BUILDID=118
##[debug]TASK.DISPLAYNAME=Download latest TestTool build
##[debug]SYSTEM.JOBID=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3
##[debug]AGENT.VERSION=2.168.2
##[debug]AGENT.OS=Windows_NT
##[debug]AGENT.NAME=5CG70948WR
##[debug]Processed: ##vso[telemetry.publish area=DownloadBuildArtifacts;feature=reliability]{"hostType":"build","definitionName":"[NonEmail:RMS]","processId":"118","processUrl":"https://dev.azure.com/iMSTraining/RMS/_build?buildId=118","taskDisplayName":"Download latest TestTool build","jobid":"3dc8fd7e-4368-5a92-293e-d53cefc8c4b3","agentVersion":"2.168.2","agentOS":"Windows_NT","agentName":"5CG70948WR","version":{"Major":0,"Minor":167,"Patch":2},"issueType":"error","errorMessage":"{\"stack\":\"Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.\\n    at RestClient.<anonymous> (C:\\\\EvolveiMS\\\\Agent\\\\_work\\\\_tasks\\\\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\\\\0.167.2\\\\node_modules\\\\typed-rest-client\\\\RestClient.js:200:31)\\n    at next (native)\\n    at fulfilled (C:\\\\EvolveiMS\\\\Agent\\\\_work\\\\_tasks\\\\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\\\\0.167.2\\\\node_modules\\\\typed-rest-client\\\\RestClient.js:6:58)\\n    at process._tickCallback (internal/process/next_tick.js:109:7)\",\"message\":\"VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.\",\"statusCode\":400,\"result\":{\"message\":\"VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.\"}}"}
##[debug]task result: Failed
##[error]Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.
##[debug]Processed: ##vso[task.issue type=error;]Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.
##[debug]Processed: ##vso[task.complete result=Failed;]Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/d45ac940-5773-4d4f-a1d9-79206b0b4ba0' does not exist, or you do not have permission to access it.
Finishing: Download latest TestTool build

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
