### ISSUE TITLE
Xcode optional parameters don't work from yaml pipeline

### ISSUE THREAD

**Issue by MatkovIvan** [microsoft/azure-pipelines-tasks#13386]
## Required Information

**Type**: Bug
**Enter Task Name**: Xcode  

## Environment
- Server: Azure Pipelines
- Agent: macOS-10.15

## Issue Description

Optional parameters don't work from yaml pipeline.

I'm trying to migrate my pipeline from classic editor to yaml. It has Xcode task that I "exported" by "View YAML" button. The task uses some "default" parameters (like SDK and Configuration) and it works in a classic editor by just dropping these arguments in command line call like:

```
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 5.170.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xcode
==============================================================================
/usr/bin/xcodebuild -version
Xcode 11.5
Build version 11E608c
/usr/bin/xcodebuild -workspace /Users/runner/work/1/s/AppCenter.xcworkspace -scheme AppCenter iOS Framework -destination platform=iOS Simulator,name=iPhone 11 analyze CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/2.6.0/bin/xcpretty -r junit --no-color
▸ Processing Info.plist
...
```
But the same task fails if it's started from yaml (exported from the above) because it tries to specify optional parameters and fails to resolve it (see the logs below). I guess it works from UI just because if stores all optional parameters as empty strings, but YAML uses `defaultValue` from https://github.com/microsoft/azure-pipelines-tasks/blob/bae01dfb264abf44efdde6070a7a678dc3b59989/Tasks/XcodeV5/task.json#L66

As an user I do not have to specify all optional parameters (with empty values) to make it work.

### Classic editor
![image](https://user-images.githubusercontent.com/1836384/89303352-c487b580-d674-11ea-8138-594b741fc854.png)

### YAML (exported from classic editor)
```
steps:
- task: Xcode@5
  displayName: Analyze
  inputs:
    actions: analyze
    xcWorkspacePath: AppCenter.xcworkspace
    scheme: 'AppCenter iOS Framework'
    xcodeVersion: specifyPath
    xcodeDeveloperDir: '/Applications/Xcode_11.5.app/Contents/Developer'
    destinationPlatformOption: iOS
    destinationSimulators: 'iPhone 11'
```

### Task logs

```
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 5.170.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xcode
==============================================================================
/usr/bin/xcodebuild -version
Xcode 11.5
Build version 11E608c
/usr/bin/xcodebuild -sdk $(SDK) -configuration $(Configuration) -workspace /Users/runner/work/1/s/AppCenter.xcworkspace -scheme AppCenter iOS Framework -destination platform=iOS Simulator,name=iPhone 11 analyze CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/2.6.0/bin/xcpretty -r junit --no-color
xcodebuild: error: SDK "$(SDK)" cannot be located.
##[error]Error: /usr/bin/xcodebuild failed with return code: 64
```
