### ISSUE TITLE
docs(HelmDeploy@0): add docs around using secret environment variables with `overrideValues`

### ISSUE THREAD

**Issue by damienwebdev** [microsoft/azure-pipelines-tasks#13391]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: HelmDeploy@0)

## Environment
- Server - Azure Pipelines

## Issue Description
When attempting to utilize secret environment variables in the `HelmDeploy@0` task, I haven't been able to successfully set the `overrideValues` with values pulled from my environment,

## Troubleshooting
```yaml
- task: HelmDeploy@0
  displayName: Helm upgrade `releaseName`
  env: 
    propA: $(SECRET_PROP)
  inputs:
  command: upgrade
  chartType: filepath
  chartPath:  $(Pipeline.Workspace)/$(infrastructureArtifactName)
  releaseName: $(releaseName)
  overrideValues: myValue=$(propA)
  install: true
  waitForExecution: true
```

The resulting command generated looks like: 

```
/opt/hostedtoolcache/helm/3.2.4/x64/linux-amd64/helm upgrade --install --set myValue=$(propA) --wait releaseName .
```

Note that `$(propA)` was not successfully cast to the appropriate environment variable.
