### ISSUE TITLE
TRX file cannot be correctly located in VsTest 16.7 in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/azure-pipelines-tasks#13404]
## Description
Starting today, the VsTest 16.7.0 is available in Azure DevOps pipeline. We got an error message at the end of the VsTest step that it clamied TRX was not found when publishing the test. 
It appears the VsTest was looking for trx file in ```\agent\_work\_temp\TestResults``` while it was actually saved to ```$(Common.TestResultsDirectory)```

We were using VsTest 16.6.1 with the same pipeline this past Sunday without problem.

## Script
Here is the part of our yml pipeline file:
```yml

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'VsTest Platform Installer'
  inputs:
    versionSelector: latestStable

# To avoid vstest execution error, we need to split tests into group by framework version.
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\MyApp.UnitTest.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: 'toolsInstaller'
    codeCoverageEnabled: true
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/test/UnitTests/MyApp.UnitTest'
    otherConsoleOptions: '/ResultsDirectory:$(Common.TestResultsDirectory)'
```
## Log
Here is the log output:
```
**************** Starting test execution *********************
C:\agent\_work\_tool\VsTest\16.7.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\agent\_work\_temp\tb3bjofmr20.tmp"
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe "C:\agent\_work\31\s\test\UnitTests\MyApp.UnitTest\bin\x86\Release\MyApp.UnitTest.dll"
/Settings:"C:\agent\_work\_temp\5k2prh3hdf4.tmp.runsettings"
/Logger:"trx"
/TestAdapterPath:"C:\agent\_work\31\s\test\UnitTests\MyApp.UnitTest"
/ResultsDirectory:C:\agent\_work\31\TestResults
Starting test execution, please wait...
Microsoft (R) Coverage Collection Tool Version 16.0.30319.200


Copyright (c) Microsoft Corporation.  All rights reserved.




Results File: C:\agent\_work\31\TestResults\CMMMM038$_CMMMM038_2020-08-07_14_38_13.trx
Attachments:
  C:\agent\_work\31\TestResults\c52bfe34-15a7-4762-bbff-fbba29cac278\CMMMM038$_CMMMM038 2020-08-07 14_38_06.coverage
Test Run Successful.
Total tests: 5
     Passed: 5
 Total time: 9.0765 Seconds
Vstest.console.exe exited with code 0.
**************** Completed test execution *********************
Test results files: 
##[error]Error occurred while publishing test results : MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory C:\agent\_work\_temp\TestResults.
##[error]Skipping marking test run as complete as test run id 0 is invalid.
Completed TestExecution Model...
##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
##[error]Error: The process 'C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
Finishing: VsTest - testAssemblies - .Net Framework

```

Here is the log output for VsTest 16.7.0 installation
```
==============================================================================
Task         : Visual Studio test platform installer
Description  : Acquire the test platform from nuget.org or the tool cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
Version      : 1.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer
==============================================================================
Starting VsTest platform tools installer task.
==============================================================================
Looking for the latest stable version of the Microsoft.Testplatform.
C:\agent\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe list packageid:Microsoft.TestPlatform -NonInteractive -Source https://api.nuget.org/v3/index.json
Microsoft.TestPlatform 16.7.0
C:\agent\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe install Microsoft.TestPlatform -Version 16.7.0 -Source https://api.nuget.org/v3/index.json -OutputDirectory C:\agent\_work\_temp\VsTest -NoCache -DirectDownload -NonInteractive
Feeds used:
  https://api.nuget.org/v3/index.json



Attempting to gather dependency information for package 'Microsoft.TestPlatform.16.7.0' with respect to project 'C:\agent\_work\_temp\VsTest', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.26 sec
Attempting to resolve dependencies for package 'Microsoft.TestPlatform.16.7.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.TestPlatform.16.7.0'
Resolved actions to install package 'Microsoft.TestPlatform.16.7.0'
Retrieving package 'Microsoft.TestPlatform 16.7.0' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/16.7.0/microsoft.testplatform.16.7.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/16.7.0/microsoft.testplatform.16.7.0.nupkg 51ms
Adding package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Added package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Successfully installed 'Microsoft.TestPlatform 16.7.0' to C:\agent\_work\_temp\VsTest
Executing nuget actions took 7.53 sec
Caching tool: VsTest 16.7.0 x64
VsTest will use the Test Platform package found in C:\agent\_work\_tool\VsTest\16.7.0\x64
```

We were using VsTest 16.6.1 without problem before today.

## Environment
The agent is running at Windows 10 1803

**Comment by ShreyasRmsft** [comment]
@aDisplayName are you using AzureDevOps onprem or AzureDevOps hosted service?
 If onprem please mention which version.

**Comment by aDisplayName** [comment]
@ShreyasRmsft Azure DevOps hosted service. Sprint 172

**Comment by ShreyasRmsft** [comment]
@aDisplayName you'd need to use the dedicated input of results folder input field instead of providing it in the otherconsoleoptions input since we do not parse/validate otherconsole options as it is an open ended field and just pass it on to vstest.console.exe.

![image](https://user-images.githubusercontent.com/25194518/89902916-a8e85600-dc04-11ea-9d36-7c1ec95d55e6.png)

**Comment by aDisplayName** [comment]
@ShreyasRmsft Any idea why it was working when using VsTest before 16.7.0?

**Comment by aDisplayName** [comment]
> @aDisplayName you'd need to use the dedicated input of results folder input field instead of providing it in the otherconsoleoptions input since we do not parse/validate otherconsole options as it is an open ended field and just pass it on to vstest.console.exe.
> 
> ![image](https://user-images.githubusercontent.com/25194518/89902916-a8e85600-dc04-11ea-9d36-7c1ec95d55e6.png)

@Sanan07 , Will it be possible why the change of VsTest version caused the behavior change in pipeline task?

@ShreyasRmsft Sorry, but your solution doesn't work for us. 

Consider the following script, only the second vstest result is available for "Publish Test Results" task. Apparently the first vstest result was cleared up by ```resultsFolder: '$(Common.TestResultsDirectory)'``` option in the second vstest

![image](https://user-images.githubusercontent.com/19527258/89944894-1b802280-dc53-11ea-8e92-df97880a061a.png)

As I've mentioned earlier, our "SonarQube" code analysis task needs test results from all vstest tasks to be available.
```yml
trigger: none

pool:
  vmImage: 'windows-latest'

workspace:
  clean: all

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.302'
  inputs:
    version: 3.1.302

- powershell: |
    Set-Location $(System.DefaultWorkingDirectory)
    dotnet new mstest -o MyApp.UnitTest
    dotnet build MyApp.UnitTest/MyApp.UnitTest.csproj -o output
    Write-Host hello
    Write-Host $(Common.TestResultsDirectory)
  
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'VsTest Platform Installer'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

# To avoid vstest execution error, we need to split tests into group by framework version.
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/MyApp.UnitTest.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)/output'
    resultsFolder: '$(Common.TestResultsDirectory)'
    vsTestVersion: 'toolsInstaller'
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/output'
    codeCoverageEnabled: true


- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/MyApp.UnitTest.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)/output'
    resultsFolder: '$(Common.TestResultsDirectory)'
    vsTestVersion: 'toolsInstaller'
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/output'
    codeCoverageEnabled: true

- powershell: |
    Get-ChildItem $(Common.TestResultsDirectory)/*.trx -Recurse | Write-Host
    Get-ChildItem $(Common.TestResultsDirectory)/*.trx -Recurse | Measure-Object
    
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'
```
