### ISSUE TITLE
kubectl apply inine configuration using secrets

### ISSUE THREAD

**Issue by StickNitro** [microsoft/azure-pipelines-tasks#13400]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: KubectlInstaller

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account name: apdcommunications
team project name: NextGen999
release definition: 10

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
ubuntu-20.04

## Issue Description

I am trying to use a secret variable with the `kubctl` task but I am unable to inject the secrets from the release pipeline variables into the inline configuration, the inline configuration I have is:

```
apiVersion: v1
stringData: # or data but I get a base64 error if using data
  COSMOSDBCONNECTIONSTRING: $(COSMOSDB_CONNECTIONSTRING)
kind: Secret
metadata:
  creationTimestamp: null
  name: mongosecret
```

And I am mapping the secret in the arguments using `--from-literal=COSMOSDB_CONNECTIONSTRING=$(CosmosDb)` (`CosmosDb` is the name of the variable in the variables tab in the release pipeline)

I don't know if this is right and I have struggled to find any documentation that give an example of using release pipeline variables with this task. So could you provide an example using secret variables with the ADO Releases.
