### ISSUE TITLE
UseDotNet@2 Task deprecated in favor of NuGet Task?

### ISSUE THREAD

**Issue by FilBot3** [microsoft/azure-pipelines-tasks#13443]
# UseDotNet@2 task deprecated in favor of NuGet Task

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: `UseDotNet@2`

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: `bluekc`

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: Azure DevOps Hosted Agent, `ubuntu-latest`

## Issue Description

Visual Studio Code and even Vim with `coc.nvim` are saying that the `UseDotNet@2` task is deprecated but does not provide an alternative.

```yaml
stages:
  - stage: DevelopmentStage
    displayName: Development Stage
    jobs:
      - job: BuildAndPublishJob
        displayName: Build and Publish
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core SDK
            inputs:
              packageType: sdk
              version: '3.x'
```

### The error message

> [yaml] [E] NuGet is deprecated - Deprecated: use the “NuGet” task instead. It
> 2            works with the new Tool Installer framework so you can easily use new
> 3            versions of NuGet without waiting for a task update, provides better support
> 4            for authenticated feeds outside this organization/collection, and uses NuGet
> 5            4 by default.

However, the documentation

* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer

Doesn't say that it's deprecated and shouldn't be used. I don't see what I should be using instead and the linters just end up painting the whole rest of the file in a big ugly red line saying this same error message.

### Task logs

No Task logs as of yet. Pipeline not ran.

## Troubleshooting
> Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

Troubleshooting has been just looking through the different available tasks in the Task Catalog.

* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/

Which doesn't seem to list all of them with the actual task name to make it easier to find. 

### Error logs

No error logs other than the one from the linter.

> [yaml] [E] NuGet is deprecated - Deprecated: use the “NuGet” task instead. It
> 2            works with the new Tool Installer framework so you can easily use new
> 3            versions of NuGet without waiting for a task update, provides better support
> 4            for authenticated feeds outside this organization/collection, and uses NuGet
> 5            4 by default.
