### ISSUE TITLE
AzureRmWebAppDeployment: ConnectionType missing in "view yaml - copy to clipboard"

### ISSUE THREAD

**Issue by blumk** [microsoft/azure-pipelines-tasks#13449]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment@4  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

## Environment
- Azure Pipelines 
- Agent - Hosted 

## Issue Description

Migrating an existing release pipeline to YAML is missing the `ConnectionType`:
`##[error]Error: Input required: ConnectedServiceName`

1) Open existing release pipeline and click "View YAML"
![image](https://user-images.githubusercontent.com/2436496/90756860-23883400-e2dd-11ea-8b58-7631723fa952.png)

2) YAML does not match required task definition:
![image](https://user-images.githubusercontent.com/2436496/90757765-567ef780-e2de-11ea-91a9-ce4039fbcc24.png)

Expected:
```
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ---
```

Current value (ConnectionType is missing):
```
- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: ---
    ....
```

3) Running the pipeline with the provided code will throw an error
`##[error]Error: Input required: ConnectedServiceName`

### Error logs

`##[error]Error: Input required: ConnectedServiceName`

**Comment by blumk** [comment]
`azureSubscription ` is just an alias, needs to be renamed to `ConnectedServiceName`.

Expected YAML format should be:
```
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    ConnectedServiceName: ---
```

See [Azure App Service Deploy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
