### ISSUE TITLE
Task: Docker - Feature: Add Pull Command

### ISSUE THREAD

**Issue by AdamCoulterOz** [microsoft/azure-pipelines-tasks#13444]
### Task: Docker
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/Docker

### Add Pull Command

Add an additional command option to perform a docker pull on a given repository:tag. This is useful for restoring a container from a previous build to take advantage of cached layers to improve build time. This would also be helpful with multi-stage builds.

**Comment by ds-ms** [comment]
The `command` input is an editable dropdown; you should be able to achieve docker pull today by simply just editing that field.

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if the above suggested solution doesn't work for you

**Comment by AdamCoulterOz** [comment]
Thanks

**Comment by tusharb86** [comment]
@ds-ms The documentation does not indicate that one can use "pull" in the command field. Please consider updating the documentation to make it more clear that other commands can be used.

Documentation link: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker

> | command Command | (Required) Possible values: buildAndPush, build, push, login, logout Added in version 2.173.0: start, stop Default value: buildAndPush |
> |-----------------|----------------------------------------------------------------------------------------------------------------------------------------|

**Comment by rcomanne** [comment]
We've seen issues with the `pull` argument where it would **not** resolve parameters or variables provided to it.
```yaml
- task: Docker@2
            inputs:
              containerRegistry: 'MyCustomRegistry'
              repository: ${{ parameters.artifactId }}
              command: 'pull'
              tags: ${{ parameters.version }}
```
These parameters are variables provided to the pipelines, and we've seen that they are filled by printing them in a Bash task before the pull step.
