### ISSUE TITLE
Helm deploy cannot authenticate when deploying using environment

### ISSUE THREAD

**Issue by blake-mealey** [microsoft/azure-pipelines-tasks#13451]
## Required Information

**Type**: Bug

**Task Name**:  HelmDeploy@0

## Environment
- Server - Azure Pipelines

    - Account name: Nureva
    - Team project name: Nureva
    - Build definition ID: 1298

- Agent - Hosted or Private: 

    - Hosted: ubuntu-latest

## Issue Description

I first posted this issue on the Microsoft Developer Community: https://developercommunity.visualstudio.com/content/problem/1145660/helm-deploy-cannot-authenticate-when-deploying-usi.html?childToView=1154714#comment-1154714 but was redirected here.

I can successfully use the helm deploy task by specifying the following inputs:

* connectionType: Azure Resource Manager
* azureSubscriptionEndpoint: mySubscription
* azureResourceGroup: myResourceGroup
* kubernetesCluster: myCluster

However, when I set the environment of the deployment job like so:

* environment: myEnvironment.myNamespace

And then leave out the above inputs, I get the error:

`Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials`

When I look at the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#service-connection), I see "A service connection isn't required if an environment resource that points to a Kubernetes cluster has already been specified in the pipeline's stage" which I think means I should be able to only specify the environment resource?

Here's my pipeline for more info:

```yaml
# deploy_template.yaml

parameters:
  - name: should_deploy
    displayName: Should Deploy
    type: boolean
  - name: env_name
    displayName: Environment Name
    type: string
  - name: environment
    displayName: Azure DevOps Environment
    type: string
  - name: k8s_namespace
    displayName: Kubernetes Namespace
    type: string
  - name: k8s_azure_subscription
    displayName: Kubernetes Azure Subscription
    type: string
  - name: k8s_azure_resource_group
    displayName: Kubernetes Azure Resource Group
    type: string
  - name: k8s_azure_cluster
    displayName: Kubernetes Azure Cluster
    type: string

stages:
  - stage: deploy_${{ parameters.env_name }}
    displayName: Deploy to ${{ parameters.env_name }}
    condition: and(succeeded(), ${{ parameters.should_deploy }})
    variables:
      - name: ReleaseName
        value: my-service-${{ parameters.env_name }}
      - name: ChartPath
        value: pipeline_scripts/service/helm/my-service
    jobs:
      - deployment: deploy_helm_chart
        displayName: Deploy Helm Chart
        environment: ${{ parameters.environment }}.${{ parameters.k8s_namespace }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: HelmDeploy@0
                  displayName: Helm upgrade
                  inputs:
                    command: upgrade
                    install: true
                    arguments: --create-namespace
                    releaseName: $(ReleaseName)
                    chartType: FilePath
                    chartPath: $(ChartPath)
                    valueFile: $(ChartPath)/values/${{ parameters.env_name }}.values.yaml
                    useClusterAdmin: true
                    namespace: ${{ parameters.k8s_namespace }}
                    # Ideally this would not be required since it should get it from the
                    # current environment resource, however this does not seem to be working
                    connectionType: Azure Resource Manager
                    azureSubscriptionEndpoint: ${{ parameters.k8s_azure_subscription }}
                    azureResourceGroup: ${{ parameters.k8s_azure_resource_group }}
                    kubernetesCluster: ${{ parameters.k8s_azure_cluster }}
```

### Task logs

```
2020-08-11T16:19:07.2303297Z ##[section]Starting: Helm upgrade
2020-08-11T16:19:07.2312764Z ==============================================================================
2020-08-11T16:19:07.2313131Z Task         : Package and deploy Helm charts
2020-08-11T16:19:07.2313522Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2020-08-11T16:19:07.2313847Z Version      : 0.172.3
2020-08-11T16:19:07.2314094Z Author       : Microsoft Corporation
2020-08-11T16:19:07.2314383Z Help         : https://aka.ms/azpipes-helm-tsg
2020-08-11T16:19:07.2314709Z ==============================================================================
2020-08-11T16:19:07.4970366Z [command]/usr/local/bin/helm upgrade --namespace rome-development --install --values /home/vsts/work/1/s/pipeline_scripts/service/helm/my-service/values/dev.values.yaml --set image.digest=sha256:BLAH --wait --create-namespace my-service-dev /home/vsts/work/1/s/pipeline_scripts/service/helm/my-service
2020-08-11T16:19:10.5409885Z Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
2020-08-11T16:19:10.5458650Z ##[error]Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials

2020-08-11T16:19:10.5508695Z ##[section]Finishing: Helm upgrade
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
