### ISSUE TITLE
PublishCodeCoverageResults does not appear to support matching on summaryFileLocation

### ISSUE THREAD

**Issue by illegalnumbers** [microsoft/azure-pipelines-tasks#13463]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Ubuntu 16 and Azure Pipelines 6

## Issue Description

I publish my code coverage reports using Cobertura and then have a task setup like the following:
```
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: "$(Build.SourcesDirectory)/TestResults/Coverage/**/coverage.cobertura.xml"
          reportDirectory: "$(Build.SourcesDirectory)/TestResults/Coverage/Reports"
          failIfCoverageEmpty: true
```

My report generator task using the dotnet reportgenerator tool is successful at using the wildcard to find my coverage file though in a previous step.
` Writing report file '/home/vsts/work/1/s/TestResults/Coverage/Reports/index.html'`

But not matter what I try I can't get the publishing step to work. I suspect it has something to do with the Cobertura guid directory structure but it's weird since I can get my other steps to work appropriately. Just publishing is an issue.
