### ISSUE TITLE
Interpolate variable given inside arguments input for Docker@2 task.

### ISSUE THREAD

**Issue by sheeeng** [microsoft/azure-pipelines-tasks#13466]
*Type*: Question, Bug, or Feature?

## Environment
- Azure Pipelines, Agent Hosted

## Issue Description

Interpolate variable given inside `arguments` input for Docker@2 task.

## Example

The `displayName` can interpolate variable to correct output. But, `arguments` use the given verbatim string without interpolate argument.

_Expected_: `--build-arg environment=dev`

_Actual_: `--build-arg environment=$(echo targetEnvironment)`

```yaml
---
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: 'MatrixJob'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: '3'
      matrix:
        DevelopmentBuildMatrixJob:
          targetEnvironment: 'dev'
          targetEnvironmentName: 'Development'
        TestBuildMatrixJob:
          targetEnvironment: 'test'
          targetEnvironmentName: 'Test'
        ProductionBuildMatrixJob:
          targetEnvironment: 'prod'
          targetEnvironmentName: 'Production'

    - task: Docker@2
      displayName: 'Build Container Image ($(targetEnvironmentName))'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$(targetEnvironment)-$(Build.BuildNumber)'
        arguments: "--build-arg environment=$(targetEnvironment)"
```
