### ISSUE TITLE
DotNetCoreCLI@2 failing in latest 2.174.0 release

### ISSUE THREAD

**Issue by JohnLivermore** [microsoft/azure-pipelines-tasks#13472]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines (DevOps)
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
```
Account Name: WolfePak Software, LLC
Project Name: WPMobile
Pipeline: CI-WPMobile

```

- Agent - Hosted or Private: 
Hosted and selecting this in our yaml with...

```
- job: Server
  pool: 
    vmImage: 'windows-latest'

```
## Issue Description

This was working fine in 2.173.0, but now with 2.174.0 this build task is erroring out with...

`Error : Fody is only supported on MSBuild 16 and above. Current version: 15.
`
This builds fine locally with Visual Studio...

![image](https://user-images.githubusercontent.com/1489667/91459594-6d789900-e84c-11ea-9e05-e6579eb69bac.png)

and prior 2019 versions.

Here is our yaml up to the task that fails.  There are more tasks beyond this, but the last task in this chain is the one that fails...

```
- job: Server
  pool: 
    vmImage: 'windows-latest'
  variables:
    Major: '1'
    Minor: '0'
    Patch: '0'   
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.5.0'
      checkLatest: true

  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.104' 
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*Server.sln'
      vstsFeed: '6e587626-ef2d-4cc2-8040-ec1a812de9d1'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: '**/*/WP.MobileMidstream.Core.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: '**/*/WP.MobileMidstream.Shared.csproj'
      arguments: '--configuration $(buildConfiguration)'

```

### Task logs

[buildlog.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5137157/buildlog.zip)

### Error logs

![image](https://user-images.githubusercontent.com/1489667/91458817-8f255080-e84b-11ea-9625-8bb2edcde920.png)
