### ISSUE TITLE
NuGetCommand@2: 'mono' not found on Linux agent

### ISSUE THREAD

**Issue by joacar** [microsoft/azure-pipelines-tasks#13499]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NugetCommand@2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - **If using TFS on-premises, provide the version: Azure DevOps Server Version Dev17.M153.5**
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - **If using private agent, provide the OS of the machine running the agent and the agent version: Linux/x64  agent 2.153.1**

## Issue Description

```yaml
- task: NuGetCommand@2
    displayName: '[Docker config] Pack configuration file'
    condition: succeededOrFailed()
    inputs:
      command: pack
      packagesToPack: configuration.nuspec
      arguments: -Version $(Build.BuildNumber)
```

Error: Unable to locate executable file: 'mono'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
An error ocurred while trying to pack the files

### Task logs

I'll provide them in a secure manner since they contain information I don't feel comfortable disclosing on GitHub :)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Attempting to pack file: /azp/agent/_work/2/s/configuration.nuspec
##[debug]Absolute path for pathSegments: /azp/agent/_work/_tool/NuGet/4.9.4/x64/nuget.exe = /azp/agent/_work/_tool/NuGet/4.9.4/x64/nuget.exe
##[debug]which 'mono'
##[debug]not found
##[error]Error: Unable to locate executable file: 'mono'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Processed: ##vso[task.issue type=error;]Error: Unable to locate executable file: 'mono'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]task result: Failed
##[error]An error ocurred while trying to pack the files.
##[debug]Processed: ##vso[task.issue type=error;]An error ocurred while trying to pack the files.
##[debug]Processed: ##vso[task.complete result=Failed;]An error ocurred while trying to pack the files.

**Comment by joacar** [comment]
There is no install mono task ...

**Comment by joacar** [comment]
Lets close this since I understand that mono is needed to be installed. Issue was created hasty. Perhaps provide MonoInstaller@1 or just install mono if NuGet in Linux depends on it.

**Comment by ragnar474** [comment]
For Documentation:

Use `DotNetCoreCLI@2` on linux maschines
```
- task: DotNetCoreCLI@2
  displayName: "Pack"
  inputs:
  command: pack
```
