### ISSUE TITLE
NugetCommand@2 versioningScheme: byBuildNumber truncates a build number with a hyphen

### ISSUE THREAD

**Issue by MarkIannucci** [microsoft/azure-pipelines-tasks#13509]
## Required Information

Entering this information will route you directly to the right team and expedite traction.
*Type*: Bug
**Enter Task Name**: NugetCommand@2

## Environment
- Server - Azure Pipelines 
https://dev.azure.com/DenverHealth-EpicCogito/Epic/_build/results?buildId=34892&view=results

- Agent - Hosted or Private: 
Hosted: windows-latest    

## Issue Description

I tried to use the built in versioning scheme functionality in NugetCommand@2's pack functionality with the following yaml
```
- task: NuGetCommand@2
  displayName: Nuget Pack
  inputs:
    command: 'pack'
    packagesToPack: '$(Pipeline.Workspace)/b/dbatools.nuspec'
    versioningScheme: 'byBuildNumber'
```

I configured my build number using this yaml:
    name: 1.0.116-D$(BuildID)

Unfortunately, the version on the package is 1.0.116 :( 

![image](https://user-images.githubusercontent.com/16762974/92091986-bbcaf200-ed8e-11ea-9925-d099173966e8.png)

When I used the byPreReleaseNumber functionality it worked:

![image](https://user-images.githubusercontent.com/16762974/92092169-fc2a7000-ed8e-11ea-97cd-4bedf9ae660c.png)

I am unable to use the build date functionality because [PowerShell only allows you to have one hyphen](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-prerelease-support?view=powershell-7) in a pre-release package.

### Task logs

[logs_34892.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5167294/logs_34892.zip)
