### ISSUE TITLE
Feature Request: IIS Web App Deployment deploy to new folder

### ISSUE THREAD

**Issue by FuncLun** [microsoft/azure-pipelines-tasks#13514]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: IISWebAppDeploymentOnMachineGroupV0

## Environment
- Server - Azure Pipelines
    
- Agent - Private: Windows 2016 Datacenter, agent v2.174.1

## Feature Description

The "IIS Web App Deploy" task should limit downtime during the deployment by having a feature to extract and transform to a new folder, then update IIS to the new folder. A further option is to not extract/transform if the destination folder already exists.

Benefits:
1) The web site will only be down for the time of an application recycle
2) The previous version is preserved for easy rollback
3) Deploying a previous version will be faster, as extraction and transformation is skipped

*Example* new yaml inputs:

```
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    PhysicalPathForApplication: C:\inetpub\wwwroot\$(Build.DefinitionName)\$(Build.BuildNumber)
    SkipExtractionIfPathExists: true
```
```
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    # Relative to current IIS path
    PhysicalPathForApplication: ..\$(Build.BuildNumber)
    SkipExtractionIfPathExists: true
```
