### ISSUE TITLE
DownloadPipelineArtifact with preferTriggeringPipeline not working as expected

### ISSUE THREAD

**Issue by candritzky** [microsoft/azure-pipelines-tasks#13518]
**Question, Bug, or Feature?**  
*Type*: Bug, or missing feature, or maybe just a question, not sure.

**Enter Task Name**: DownloadPipelineArtifact

## Environment
Azure Pipelines, on-premise agent.

## Issue Description

We have a build pipeline with two pipeline triggers. The goal of this pipeline is to download the artifacts from two different source build pipelines to copy them to some network share in our network.

We want this build pipeline to be triggered whenever a build on specific branches of the source pipelines completed. For this we are using branch include filters on the pipeline resources.

Currently it is implemented like this:

```
trigger: none
resources:
  pipelines:
  - pipeline: A
    source: build_A
    trigger:
      branches:
        include:
        - feature/*
        - test/*
  - pipeline: B
    source: build_B
    trigger:
      branches:
        include:
        - develop

steps:
- checkout: none

- task: DownloadPipelineArtifact@2
  displayName: 'Download A'
  inputs:
    buildType: 'specific'
    project: '$(resources.pipeline.A.projectID)'
    pipeline: '$(resources.pipeline.A.pipelineID)'
    preferTriggeringPipeline: true
    artifact: 'Artifact Name A'
    targetPath: ...

- task: DownloadPipelineArtifact@2
  displayName: 'Download B'
  inputs:
    buildType: 'specific'
    project: '$(resources.pipeline.B.projectID)'
    pipeline: '$(resources.pipeline.B.pipelineID)'
    preferTriggeringPipeline: true
    artifact: 'Artifact Name B'
    targetPath: ...
```

Problem: When pipeline B completes, it takes the artifacts of the _latest_ build of pipeline A, no matter what branch it was built from. We want/expected the latest build of any branch _that matches the pipeline resource branch filter_ instead.

How can we achieve this?

I'm aware that the DownloadPipelineArtifact task supports a runBranch argument. But AFAIK this supports neither wildcards, nor multiple branch names (with wildcards).
