### ISSUE TITLE
YAML error using AzureCLI@2 on self-hosted build agent

### ISSUE THREAD

**Issue by michaelrp** [microsoft/azure-pipelines-tasks#13523]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI@2  

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV2

## Environment
- Server - Azure Pipelines local installation of DevOps
   
- Agent - Private: 
    - Windows agent

## Issue Description

Running the task example here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#example

Getting this error: "An error occurred while loading the YAML build pipeline. wrong number of segments"

Here's a clip of the failing pipeline YAML:

```
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: MyServiceName
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: az --version
```

When I run with v1 it works ok:

```
- task: AzureCLI@1
  displayName: Azure CLI
  inputs:
    azureSubscription: MyServiceName
    scriptLocation: inlineScript
    inlineScript: az --version
```

There are no other tasks in the YAML.

**Comment by bishal-pdMSFT** [comment]
When is this error happening - during pipeline run? Please attach task debug logs.

**Comment by michaelrp** [comment]
The error is happening during the pipeline run (either manually or with branch policy).

I don't seem to have access to the logs for this build. Here's a snip of what I see:

![image](https://user-images.githubusercontent.com/1393096/92801109-50cb7d80-f383-11ea-80f4-e51658171f12.png)

**Comment by michaelrp** [comment]
And here's the full YAML:

```
trigger:
- trunk

pool: 'MyPool'

variables:
  serviceName: MyService

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: $(serviceName)
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: az --version

```
