### ISSUE TITLE
Container Environment Variables Not Found for Task in Container Job

### ISSUE THREAD

**Issue by tmilnthorp** [microsoft/azure-pipelines-tasks#13540]
*Type*: bug
**Enter Task Name**: CopyFiles@2
## Environment
- Server: TFS on-premises Dev17.M153.5
- Agent - Private Win Server 2019 2.153.1

## Issue Description

When running the copy files task inside a container job, environment variables that only exist in the container do not work with the sourceFolder property. I have tried the following without success:
- SourceFolder: '$env:CUDA_PATH_V11_0\bin'
- SourceFolder: '$CUDA_PATH_V11_0\bin'
- SourceFolder: '%CUDA_PATH_V11_0%\bin'
- SourceFolder: '$(CUDA_PATH_V11_0)\bin'
- SourceFolder: '$[CUDA_PATH_V11_0]\bin'

### Task logs
##[error]Unhandled: Not found SourceFolder: C:\__w\2\s\%CUDA_PATH_V11_0%\bin

**Comment by tmilnthorp** [comment]
I added the following to double check the container's environment variables:

```yaml
  steps:
  - task: Bash@3
    inputs:
      targetType: inline
      script: "env | sort"
```

```CUDA_PATH_V11_0``` is defined in the container: 
```
CUDAPATH=CUDA_PATH_V11_0
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
CUDA_PATH_V11_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
```
## Task Info
With system.debug enabled I see the following in the task, however ```CUDA_PATH``` and ```CUDA_PATH_V11_0``` are not set:
```
##[debug]Set env: CUDAPATH=CUDA_PATH_V11_0
```

```CUDAPATH``` is not set in the host machine, so the task is picking that up out of the container. I wonder why the other two variables (```CUDA_PATH``` and ```CUDA_PATH_V11_0```) aren't picked up.

**Comment by tmilnthorp** [comment]
I tested the task using the ```CUDAPATH``` variable inside the macro format ```$(CUDAPATH)```. It does get expanded, however as part of the work directory path.

```yaml
  - task: CopyFiles@2
    displayName: 'Stage Artifacts: CUDA Dependencies'
    inputs:
      SourceFolder: '$(CUDAPATH)\bin'
      Contents: |  
       cublas64_11.dll
       cublaslt64_11.dll
       cusparse64_11.dll
      TargetFolder: '$(build.sourcesdirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)'
```

Output:
```
##[error]Unhandled: Not found SourceFolder: C:\__w\2\s\CUDA_PATH_V11_0\bin
```

It seems there are two potential bugs:
1. Not all environment variables from the container are accessible in the task for some reason
2) The task does not evaluate an expanded environment variable inside a container job the same way it does for a container-less task run.

Let me know if I need to file a separate bug for the first item.

**Comment by tmilnthorp** [comment]
For anyone who finds themselves in a similar situation, I found a way around this issue:
```yaml
- task: PowerShell@2
  displayName: Set Azure DevOps Variable from Container Environment
  inputs:
    targetType: inline
    script: Write-Host "##vso[task.setvariable variable=CudaPathExpanded]$env:CUDA_PATH"

- task: CopyFiles@2
  displayName: 'Copy CUDA Dependencies'
  inputs:
    SourceFolder: $(CudaPathExpanded)\bin
    TargetFolder: $(build.sourcesdirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)
    Contents: |  
      cublas64_11.dll
      cublaslt64_11.dll
      cusparse64_11.dll
```
