### ISSUE TITLE
Kubernetes Manifest Task - Create Secret Action - secretArguments is not exactly multiline

### ISSUE THREAD

**Issue by runwithranvit** [microsoft/azure-pipelines-tasks#13555]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes Manifest Task  

## Environment
Azure Pipelines

Account Name: `sifter`
Project Name: `musical-guide`
Build Number: `20200915.11`

- Agent - Hosted
agent queue name: `Azure Pipelines`

## Issue Description

I'm trying to use the **Create Secret** Action of the **Kubernetes Manifest** task. The docs say that the `secretArguments` field is multi-line, however...

The following results in `error: exactly one NAME is required, got 3`. No secret is created.
```
--from-literal=KEY1=VAL1 \
--from-literal=KEY2=VAL2 \
--from-literal=KEY3=VAL3 \
```

And the following, with backslashes removed, gives `error: exactly one NAME is required, got 2`. No secret is created, but the error message is listing fewer NAMES (2 instead of 3)
```
--from-literal=KEY1=VAL1 
--from-literal=KEY2=VAL2 
--from-literal=KEY3=VAL3 
```

Here's the **_REALLY_** weird stuff
The following creates a secret correctly with 3 keys in it.
```
--from-literal=KEY1=VAL1 --from-literal=KEY2=VAL2 
--from-literal=KEY3=VAL3
```

But the following fails with `error: exactly one NAME is required, got 2`
```
--from-literal=KEY1=VAL1 --from-literal=KEY2=VAL2 
--from-literal=KEY3=VAL3 
--from-literal=KEY4=VAL4
```

Extra Notes:
- I tried various combinations of `trailing spaces/no trailing spaces/backslashes` and none of it worked in a predictable way.
- All of the above works when I run it locally

### Task logs

[logs_2654.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5228022/logs_2654.zip)

### Error logs

`error: exactly one NAME is required, got 2`

**Comment by MarluanEspiritusanto** [comment]
Try to put all together without pipe or back slash:

```yml
- task: KubernetesManifest@0
  displayName: Create Kubernetes Secrets
  inputs:
    action: "createSecret"
    kubernetesServiceConnection: "my-aks-connection"
    secretType: "generic"
    secretName: "my-secret"
    secretArguments:
      --from-literal=prop1=$(KEY1)
      --from-literal=prop2=$(KEY2)
      --from-literal=prop3=$(key3)
```

In that way worked for me!!
