### ISSUE TITLE
Multi repo pipeline checkout for tags not working as expected using refs/tags/20.8 etc. 

### ISSUE THREAD

**Issue by nithinmohantk** [microsoft/azure-pipelines-tasks#13572]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Git Checkout 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:   

- buildId=16086
- account: carne-digital
- project: CORR

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 2.174.1

## Issue Description

Following syntax to checkout multi repo source from YAML pipeline is not working as expected, when you are passing a variable as the branch name in the format **refs/heads/master** or **refs/tags/20.8** etc..
Pipeline fails saying - unable to checkout from **/refs/heads/refs/heads/master**, see the different it adds an additional /refs/heads in the beginning, which causes incorrect reference. 

```
resources:
    repositories:
   
       - repository:  repo1
         type: github
         endpoint: orgname
         name: "orgname/reponame"
         ref: $(Checkout Branch or Tag)
```

But it works when the ref: input is static in YAML, it has challenge in accepting it, when it is build parameter. 
**For example: below works fine**
```
resources:
    repositories:
   
       - repository:  repo1
         type: github
         endpoint: orgname
         name: "orgname/reponame"
         ref: **refs/tags/20.8**    or **refs/tags/$(RELEASE-TAG-PARAMETER)**  or refs/heads/master or refs/heads/feature/somefeature 
```
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
![image](https://user-images.githubusercontent.com/453945/93595976-9229e180-f9b0-11ea-806c-c956168526c4.png)

[Insert error from the logs here for a quick overview]
