### ISSUE TITLE
Environment Transforms are not being applied with AzureRmWebAppDeployment in YAML pipelines

### ISSUE THREAD

**Issue by Zhaph** [microsoft/azure-pipelines-tasks#13580]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment

## Environment
- Server - Azure Pipelines?
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
      - Account: PromontoryNetwork
      - TeamProject: newco.com
      - Definition: 2
      - Build Number: 0.2.7

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **windows-latest**

## Issue Description

I have a multi-stage YAML pipeline that I'd like to apply config transforms to my web application. The `*.Release.config` transforms are applied correctly, but I'm not seeing the environment transforms (such as `courier.Dev.config` or `web.Prod.config` being applied. The files are included in the deployment package.

The documentation is clearly confused as to the name used, with the [task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#prerequisites-for-the-task) stating:

> The configuration transformations will be run for .Release.config and .{EnvironmentName}.config on the *.config files.

While the [File transforms and variable substitution reference documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#configuration-transform-file-naming-conventions) states:

> XML transformation will be run on the *.config file for transformation configuration files named `*.Release.config` or `*.<stage>.config`

 A sample stage is configured as (with Stage, Environment and Deployment all with the same name):

```
- stage: Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Dev
    environment: "Dev"
    variables:
    - group: DevDeploy
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/$(artifactName)/$(artifactName).zip'
              cleanDestinationFolder: true
              destinationFolder: '$(System.DefaultWorkingDirectory)\$(artifactName)\deploy\'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in **/*.config'
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)\$(artifactName)\deploy\'
              targetFiles: '**\*.config'
              tokenPrefix: '#{'
              tokenSuffix: '}'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: $(azureSubConnection)
              appType: webApp
              WebAppName: '$(WebApp)'
              packageForLinux: '$(System.DefaultWorkingDirectory)\$(artifactName)\deploy\'
              useWebDeploy: true
              deploymentType: webDeploy
              TakeAppOfflineFlag: false
              RemoveAdditionalFilesFlag: false
              ExcludeFilesFromAppDataFlag: false
              enableXmlTransform: true
              enableXmlVariableSubstitution: true
```

### Task logs

Logs for Dev Deployment attached.
[TaskLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5255114/TaskLogs.zip)

### Error logs

No errors are thrown.

**Comment by Zhaph** [comment]
Digging into a similar issue on the FileTransform task, I noticed that the default is to reference the predefined variable `Release.EnvironmentName` - however the `Release` object doesn't exist on CI/CD pipelines, this should be either `Environment.Name` (if running in a deployment step) or `System.StageName` (to be sure for all types of build).

**Comment by AmrutaKawade** [comment]
If you configure pipeline using UI `Release.EnvironmentName` will take stage name. I am able to reproduce this for pipeline configured though yaml.

**Comment by AmrutaKawade** [comment]
`Release.EnvironmentName` is classic release variable https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch. Its not available for yaml based releases.
you can add this variable to each stage like below

```
- stage: Dev
  jobs:
      variables:
        Release.EnvironmentName: 'Dev'
```
