### ISSUE TITLE
DotNetCoreCLIV2 push has no ability to skip duplicates

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#13591]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines

- Agent - Hosted
    
## Issue Description

A pipeline that tries to push a NuGet package can result in a 409 (Conflict) if the pipeline is run again with no change in the version number.

For example, if the following YAML is run more than once (with no project changes), all runs (except the first) result in an error:

```yaml
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  continueOnError: true
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'XXXXXXXX'
```

> Pushing XXXX.1.0.0.nupkg to 'https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/'...
>   PUT https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/
>   Conflict https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/ 72ms
> To skip already published packages, use the option --skip-duplicate
> error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'XXXX 1.0.0'. (DevOps Activity ID: CCA0F039-7739-4D8A-9B96-BC42DBCCEA1C)).

Per the error message, I need to set `--skip-duplicate`, but there is no way to set it. I tried adding an `arguments` value and inspected the source code, but I don't see any easy solutions.

### Error logs

> Pushing XXXX.1.0.0.nupkg to 'https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/'...
>   PUT https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/
>   Conflict https://XXXX.pkgs.visualstudio.com/_packaging/XXXX/nuget/v2/ 72ms
> To skip already published packages, use the option --skip-duplicate
> error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'XXXX 1.0.0'. (DevOps Activity ID: CCA0F039-7739-4D8A-9B96-BC42DBCCEA1C)).

**Comment by MisinformedDNA** [comment]
Workaround:

```yaml
- task: NuGetAuthenticate@0
  
- pwsh: |
    Get-ChildItem -Recurse $(Build.ArtifactStagingDirectory) *.nupkg
      | ForEach-Object { 
          dotnet nuget push $_.FullName --source https://pkgs.dev.azure.com/XXXX/_packaging/XXXX/nuget/v3/index.json --api-key AZDO --skip-duplicate
        }
```

**Comment by satbai** [comment]
We recommend using one of the two workarounds:
1. Use NuGet Authenticate task followed by a script task that does the dotnet command with `--skip-duplicate`
2. Use the "custom" command with the dotnet task and use the arguments option to add `--skip-duplicate`

Azure Artifacts no longer takes new feature requests or feature contributions for the bulkier package type tasks (nuget/dotnet/npm/maven/python) to restore/install or push packages to and from Artifacts feeds. The encouraged way to set up authentication is the authentication specific tasks such as NuGet Authenticate in this case. Contributions to these bulkier tasks is now limited to critical bug fixes.

**Comment by MisinformedDNA** [comment]
> now limited to critical bug fixes.

Is Azure DevOps moving into support mode so that development can be focused on GitHub?

**Comment by minhhungit** [comment]
This works for me, either use powershell like @MisinformedDNA or use Nuget 

```yaml
- task: NuGetAuthenticate@0

# - pwsh: |
#     Get-ChildItem -Recurse $(Build.ArtifactStagingDirectory) *.nupkg
#       | ForEach-Object { 
#           dotnet nuget push $_.FullName --source "https://pkgs.dev.azure.com/ABC_XYZ/_packaging/YOUR_FEED_NAME/nuget/v3/index.json" --api-key az --skip-duplicate
#         }

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '1c8a1b33-433e-12y9-a98f-6ef6969f9b9a'
    allowPackageConflicts: true
```

**Comment by galvesribeiro** [comment]
+1 fall into the same situation. In order to be able of retry a job and at the same time avoid have to have the `Conflict` response, we need to pass `--skit-duplicate` but it is not possible with the `DotNetCLI`. I find the response that "it is not taking any feature request" vague and not what we expect from a supported product (ADO and the pipelines) which is getting new features.

Also, this is a bug to be honest. The `arguments` are passed to the underlying CLI when using all other types of commands, but the `push` one. It should respect whatever the user pass in the `arguments`.

The solution to fallback to the `NuGetCommand` is far from ideal some we get deprecation warnings now:

```
WARNING: The credential plugin model used by '/home/vsts/work/_tasks/NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b/2.216.0/CredentialProvider/CredentialProvider.TeamBuild.exe' is deprecated. Please contact the provider of the plugin for an alternative. More information about the recommended plugin model can be found at 'https://aka.ms/nuget-cross-platform-authentication-plugin'.
```

**Comment by jaderanderson** [comment]
It's 2024 , the recomendation is to move from NuGet push task to dotnetCLI task and then use the push command but we can't use the skip flag. Now we should bypass using powershell ? Messy

**Comment by lcetinapta** [comment]
And the allowPackageConflicts:true does not work for external sources

**Comment by Joren-Thijs-KasparSolutions** [comment]
For people struggling in 2024. There is a new issue that is still open and I posted a workaround where you just reinstall mono before doing nuget push.

https://github.com/microsoft/azure-pipelines-tasks/issues/20981#issuecomment-2840887713

**Comment by bsumter** [comment]
For anyone wanting to migrate to dotnetcore cli, use this method:

```
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  - task: DotNetCoreCLI@2
    displayName: 'Push NuGet Package'
    inputs:
      command: 'custom'
      custom: 'nuget'
      arguments: 'push $(Pipeline.Workspace)/drop/nupkg/*.nupkg --api-key AzureArtifacts --source https://pkgs.dev.azure.com/$(organization)/_packaging/$(nugetFeedId)/nuget/v3/index.json --skip-duplicate'
```

If you need to push to a nuget feed outside your organization, check-out the official documentation on `NuGetAuthenticate`:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines#dotnet-1
