### ISSUE TITLE
nuget install task should work with any version

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/azure-pipelines-tasks#13605]
The nuget install task should work with any version of nuget. It currently doesn't support the latest nuget.

https://dist.nuget.org/win-x86-commandline/v5.8.0-preview.2/nuget.exe

No one wants to be blocked from accomplishing their work, and I doubt the azure team wants to continuously update this task every time there is a new nuget version, so this should just work. 

Trying to use 5.8.0-preview2 gives this error:

```
Starting: Use NuGet 5.8.0-preview.2
==============================================================================
Task         : NuGet tool installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 0.174.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0
==============================================================================
##[error]No version was found which matches the input 5.8.0-preview.2
ERR:Tool install failed: NuGet
##[error]The available versions are: 5.7.0; 5.6.0; 5.5.1; 5.5.0; 5.4.0; 5.3.1; 5.3.0; 5.2.0; 5.1.0; 5.0.2; 5.0.0; 4.9.4; 4.9.3; 4.9.2; 4.9.1; 4.8.2; 4.8.1; 4.7.3; 4.7.2; 4.7.1; 4.7.0; 4.6.4; 4.6.3; 4.6.2; 4.6.1; 4.6.0; 4.6.0-preview3; 4.5.3; 4.5.2; 4.5.1; 4.5.0; 4.4.3; 4.4.2; 4.4.1; 4.4.0; 4.4.0-preview3; 4.3.1; 4.3.0; 4.3.0-preview3; 4.3.0-preview1; 4.1.0; 4.0.0; 3.5.0; 3.4.4; 3.3.0; 3.2.0; 2.8.6
Finishing: Use NuGet 5.8.0-preview.2
```

**Comment by rolfik** [comment]
The same problem with preview.3

**Comment by shunkino** [comment]
This seems to be a designed behavior. Following line filters out releases with "EarlyAccessPreview" tag.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/packaging-common/nuget/NuGetToolGetter.ts#L202

Not sure if there is any possible side effect when letting user to install preview release of nuget.exe. Would love to here opinion from contributors here.
I am now using PowerShell task to download preview release of nuget as a workaround.

```
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Source file location
      $source = 'https://dist.nuget.org/win-x86-commandline/v5.10.0-preview.2/nuget.exe'
      # Destination to save the file
      $destination = '$(Agent.TempDirectory)\nuget.exe'
      #Download the file
      Invoke-WebRequest -Uri $source -OutFile $destination
      
      # Following variable names are used in installer task to pass exe path to NuGet tasks. But an other error occurred when using preview version of NuGet. 
      # So I commented it out and used PowerShell task to execute nuget.exe too.
      # echo "##vso[task.setvariable variable=NuGetExeCustomLocation;]$(Agent.TempDirectory)\nuget.exe"
      # echo "##vso[task.setvariable variable=NuGetExeToolPath;]$(Agent.TempDirectory)\nuget.exe"
      $(Agent.TempDirectory)\nuget.exe help
```
