### ISSUE TITLE
Helm v3 ACR login

### ISSUE THREAD

**Issue by bitva77** [microsoft/azure-pipelines-tasks#13602]
## Required Information

**Question, Bug, or Feature?**  
*Type*:  FEATURE

**Enter Task Name**:  `Package and deploy Helm charts`

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
    
- Agent - Hosted or Private: 
    
Private.  Redhat 7.5

## Issue Description

Using Helm 3, it does not seem possible to run a `helm registry login` command in order to login to Azure Container Registry.  The error we get is:

```
2020-09-23T19:30:09.6325304Z [command]/builds/agent1/_tool/helm/3.3.0/x64/linux-amd64/helm registry login $(server) -u $(user) -p $(password)
2020-09-23T19:30:09.6407913Z ##[error]Error: unknown command "registry login" for "helm"
```

HELM_EXPERIMENTAL_OCI=1 is being set.

I see this:  https://github.com/microsoft/azure-pipelines-tasks/pull/13005

But don't see it as an available task option?

Are we not allowed to use ACR as a chart store for Helm charts?

**Comment by shigupt202** [comment]
@bitva77 Can you try giving the command input as `registry` and the remaining inputs as required by this commad.
Ref: https://github.com/sonayak/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helmcommands/helmregistrylogin.ts

**Comment by bitva77** [comment]
@shigupt202 it seems as though it's ignoring everything in the arguments field:

``
2020-09-24T18:06:58.7660181Z ##[section]Starting: helm registry
2020-09-24T18:06:58.7670737Z ==============================================================================
2020-09-24T18:06:58.7671035Z Task         : Package and deploy Helm charts
2020-09-24T18:06:58.7671385Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2020-09-24T18:06:58.7671658Z Version      : 0.175.4
2020-09-24T18:06:58.7671843Z Author       : Microsoft Corporation
2020-09-24T18:06:58.7672076Z Help         : https://aka.ms/azpipes-helm-tsg
2020-09-24T18:06:58.7672508Z ==============================================================================
2020-09-24T18:06:59.5890467Z Error: "helm registry login" requires at least 1 argument
2020-09-24T18:06:59.5892428Z 
2020-09-24T18:06:59.5893515Z Usage:  helm registry login [host] [flags]
2020-09-24T18:06:59.6289130Z [command]/builds/agent1/_tool/helm/3.3.0/x64/linux-amd64/helm registry login --username --password
2020-09-24T18:06:59.6339121Z ##[error]Error: "helm registry login" requires at least 1 argument

Usage:  helm registry login [host] [flags]

2020-09-24T18:06:59.6352904Z ##[section]Finishing: helm registry

```

no matter what I put in as arguments

**Comment by shigupt202** [comment]
Please give the values of these inputs: `azureSubscriptionEndpointForACR` and `azureContainerRegistry`. You don't need to pass username and password explicitly in the `arguments`. The task takes care of getting these credentials from the service endpoint.

**Comment by bitva77** [comment]
I'm sorry, where am I putting that?

![image](https://user-images.githubusercontent.com/36420085/94615276-5a4a5600-025c-11eb-89eb-590677e1c212.png)

**Comment by shigupt202** [comment]
The PR that you have pointed to was to introduce the `helm chart save` [feature](https://github.com/microsoft/azure-pipelines-tasks/issues/12870) in the task. To be able to use that, you need to select `save` as the command and an Azure service connection in `Connection type`. 
Otherwise, if you only want to login to ACR, you can pass `registry` in the command field and the remaining information, i.e. `login <url> -u <username> -p <password>` in the arguments field.

**Comment by bitva77** [comment]
Not sure if something's up with our account but `save` doesn't give us our ACR.  The service connection is correct (I even created a new one with the same subscription)

![image](https://user-images.githubusercontent.com/36420085/95153380-28e1f680-0744-11eb-8973-a7e73fc5868f.png)


And then `registry` ignores the host and anything I put after `-u` and `-p`:

```
2020-10-06T02:49:13.0234310Z Usage:  helm registry login [host] [flags]
2020-10-06T02:49:13.0241727Z [command]/builds/agent1/_tool/helm/3.3.0/x64/linux-amd64/helm registry login --username --password
2020-10-06T02:49:13.0298545Z ##[error]Error: "helm registry login" requires at least 1 argument

Usage:  helm registry login [host] [flags]

2020-10-06T02:49:13.0312008Z ##[section]Finishing: helm registry
```

is this all documented somewhere where I'm not having to bug you all here?  That's sort of why I put this in as a Feature request as there's not a whole lot I could find out in there in regards to this.

**Comment by shigupt202** [comment]
Can you please share the complete pipeline that you are using, either the YAML verison (can be done from the option at the top) or UI?

**Comment by bitva77** [comment]
this one:

```
steps:
- task: HelmDeploy@0
  displayName: 'helm registry login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: kubernetes.aws.preprod
    command: 'registry login'
    arguments: 'reporedacted.azurecro.io --username spuser_redacted --password sppass_redacted'
```

Or this one

```
steps:
- task: HelmDeploy@0
  displayName: 'helm save'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: kubernetes.aws.preprod
    azureSubscriptionForACR: 'subscriptionredacted'
    command: save
    chartNameForACR: hemitest
    chartPathForACR: hemitest/hemitest
```

**Comment by shigupt202** [comment]
The first one is wrong because `registry login` is not a valid command. If you want to use it correctly, give `registry` in the command and login along with rest of the parameters in arguments as I've explained in the previous comment.
In the second one, I do not see the fields for `Azure subscription for Container registry`, `Resource Group` and `Azure Container Registry`. These are all required fields if you want to use `save` command.

**Comment by bitva77** [comment]
Sorry, I got further with `registry login` as `registry` errors with this:

```
2020-10-09T16:01:10.6954619Z ==============================================================================
2020-10-09T16:01:11.3595334Z [command]/builds/agent1/_tool/helm/3.3.0/x64/linux-amd64/helm registry login --username --password
2020-10-09T16:01:11.3680164Z Error: "helm registry login" requires at least 1 argument
2020-10-09T16:01:11.3680654Z 
2020-10-09T16:01:11.3680961Z Usage:  helm registry login [host] [flags]
2020-10-09T16:01:11.3754396Z ##[error]Error: "helm registry login" requires at least 1 argument

Usage:  helm registry login [host] [flags]
```

Here's the YAML:

```
steps:
- task: HelmDeploy@0
  displayName: 'helm registry'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: kubernetes.aws.preprod
    command: registry
    arguments: 'login blah.azurecro.io --username myuser --password supersecretpassword'
```

Regarding the `save` command, it doesn't propagate those fields.  They are unsearchable in the GUI.  The Subscription is present: `azureSubscriptionForACR` but nothing else and I can't type anything else in.  Using the YAML, those would be `azureSubscriptionEndpointForACR` and `azureContainerRegistry` ?
