### ISSUE TITLE
Environment variable substitution failed in Configuration File (docker-compose.yml)

### ISSUE THREAD

**Issue by Divjyot** [microsoft/azure-pipelines-tasks#13607]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: Azure Web App for Containers Deploy

## Environment
- Server - Azure Pipelines, Ubuntu:16.04
- Agent - Hosted or Private:  Hosted
   
## Issue Description
I have a pipeline with 3 tasks in it
**Task 1.** Run a Docker-Compose (Command : Build)
**Task 2.** Run a Docker-Compose (Command : Push)
**Task 3.** Azure Web App on Container Deploy 

**Task 1 & 2** are linked with a docker-compose.prod.yml file that have variables that get substituted from a environment variable group (linked with the pipeline ofcourse)

**Task 3** in which I have linked the following Configuration File (to be updated/deployed on my multicontainers web service) :- 

**Contents of Configuration File** 
```
version: '3.7'

services:
  web:
    command: python3 manage.py runserver 0.0.0.0:8000
    image: "${AZ_CONTAINER_REGISTRY}/${APP1_IMAGE}:${APP1_VERSION}"
    ports:
      - 8000:8000
  app2:
    command: python app.py
    image: "${AZ_CONTAINER_REGISTRY}/${APP2_IMAGE}:${APP2_VERSION}"
    expose:
      - 8080
    restart: always
```

However, in Task 3 the variables DO NOT get substituted when the Task is performed. Task updates my multicontainer web service config as it is as shown above.

What confuses me that Task 1 and Task 2 are successfully performed i.e. the yml files linked to those DO get variables substituted from same variable group but Task 3 fail to do so before deploying it to web service.

Important to note that:
* All Variables (AZ_CONTAINER_REGISTRY, APP1_IMAGE, APP1_VERSION, APP2_IMAGE, APP2_VERSION) are NOT secret.

**Comment by ds-ms** [comment]
Here's a doc for you to understand the variables syntax: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax

It looks like you're using them wrong. You should use it like $(AZ_CONTAINER_REGISTRY) or ${{ variables.AZ_CONTAINER_REGISTRY }}

**Comment by Divjyot** [comment]
> Here's a doc for you to understand the variables syntax: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
> 
> It looks like you're using them wrong. You should use it like $(AZ_CONTAINER_REGISTRY) or ${{ variables.AZ_CONTAINER_REGISTRY }}

Thanks for your comment. Just want to confirm/restate that the yml file I am referring to is the configuration file i.e. that one set in App Service Plan - NOT the yml that we use to define pipeline (tasks). When the pipeline runs **Task1** and **Task2**, the yml linked to those task (**contains same variables & syntax** runs  successfully i.e. variable substitution completes and builds & pushes images with correct tags.

**Comment by ds-ms** [comment]
What's your task3? AzureWebAppDeployment?

**Comment by Divjyot** [comment]
> What's your task3? AzureWebAppDeployment?

**Azure Web App on Container Deploy**

**Comment by ds-ms** [comment]
@chshrikh this seems like a task you guys own right?

**Comment by AmrutaKawade** [comment]
@Divjyot Can you share your task yml for all 3 tasks?

**Comment by amit-avit** [comment]
Closing due to inactivity.

**Comment by Divjyot** [comment]
> @Divjyot Can you share your task yml for all 3 tasks?

I created these Tasks directly using Pipelines UI interface, however here are yml created by the tasks (deidentified copies)

TASK 1
```
steps:
- task: DockerCompose@0
  displayName: 'Run a Docker Compose Build'
  inputs:
    azureSubscription: 'Visual Studio Professional (XXXXXXXXXXXXXXX)'
    azureContainerRegistry: '{"loginServer":"XXXXXXXXXXXXXXX", "id" : "XXXXXXXXXXXXXXX"}'
    dockerComposeFile: 'my_project_folder/docker-compose.yml'
    dockerComposeCommand: build
```


TASK 2
```
steps:
- task: DockerCompose@0
  displayName: 'Run a Docker Compose Push'
  inputs:
    azureSubscription: 'Visual Studio Professional (XXXXXXXXXXXXXXX)'
    azureContainerRegistry: '{"loginServer":"XXXXXXXXXXXXXXX", "id" : "XXXXXXXXXXXXXXX"}'
    dockerComposeFile: 'my_project_folder/docker-compose.yml'
    dockerComposeCommand: push
```


TASK 3
```
steps:
- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy: multicontainer'
  inputs:
    azureSubscription: 'Visual Studio Professional (XXXXXXXXXXXXXXX)'
    appName: multicontainer
    multicontainerConfigFile: 'my_project_folder/conf.yml'
```

**Comment by AmrutaKawade** [comment]
I am restating all things mentioned, to check whether problem is understood correctly. please confirm.

1. You are using classic pipeline and not yaml 
2. you have some variables in variable group
![image](https://user-images.githubusercontent.com/65217380/107631098-7d652780-6c8a-11eb-852f-f5c187a1fbc9.png)
3. there is config yaml file which is using variables defined in variable group

```
version: '3.7'

services:
  web:
    command: python3 manage.py runserver 0.0.0.0:8000
    image: "${AZ_CONTAINER_REGISTRY}/${APP1_IMAGE}:${APP1_VERSION}"
    ports:
      - 8000:8000
  app2:
    command: python app.py
    image: "${AZ_CONTAINER_REGISTRY}/${APP2_IMAGE}:${APP2_VERSION}"
    expose:
      - 8080
```

4. this variables in config file are getting substituted automatically for Docker Compose task without using any other variable substitution task and not for AzureWebAppContainer task.

**Comment by Castone22** [comment]
There are two bare minimum cases here that very much isolate this to the compose plugin.
https://gist.github.com/Castone22/4105b26c749533a69451b0084ec23a30
This one does it using a provided environment variable override in the plugin

https://gist.github.com/Castone22/6f4160703a5f3f0c518ea3c640d3f2ab
This one does it using docker compose environment binding as per its spec.

In both cases, the bash step will echo the current build id, BUT the compose step will echo $BUILD_ID because it's unset in the container, despite having been provided.

**Comment by Divjyot** [comment]
> I am restating all things mentioned, to check whether problem is understood correctly. please confirm.
> 
> 1. You are using classic pipeline and not yaml
> 2. you have some variables in variable group
>    ![image](https://user-images.githubusercontent.com/65217380/107631098-7d652780-6c8a-11eb-852f-f5c187a1fbc9.png)
> 3. there is config yaml file which is using variables defined in variable group
> 
> ```
> version: '3.7'
> 
> services:
>   web:
>     command: python3 manage.py runserver 0.0.0.0:8000
>     image: "${AZ_CONTAINER_REGISTRY}/${APP1_IMAGE}:${APP1_VERSION}"
>     ports:
>       - 8000:8000
>   app2:
>     command: python app.py
>     image: "${AZ_CONTAINER_REGISTRY}/${APP2_IMAGE}:${APP2_VERSION}"
>     expose:
>       - 8080
> ```
> 
> 1. this variables in config file are getting substituted automatically for Docker Compose task without using any other variable substitution task and not for AzureWebAppContainer task.

1. Correct - classical
2. Correct  - Variables are NOT secret.
3. Correct
4. Correct - there is ONLY one difference of ```build: ./appX``` in yml file used in Docker Compose tasks (Task1 and Task2) vs AzureWebAppContainer (Task3):

**yml : Docker Compose tasks Task1 and Task2 (docker-compose.yml)**

```
version: '3.7'

services:
  web:
    build: ./app1 
    command: python3 manage.py runserver 0.0.0.0:8000
    image: "${AZ_CONTAINER_REGISTRY}/${APP1_IMAGE}:${APP1_VERSION}"
    ports:
      - 8000:8000
  app2:
    build: ./app2
    command: python app.py
    image: "${AZ_CONTAINER_REGISTRY}/${APP2_IMAGE}:${APP2_VERSION}"
    expose:
      - 8080
```

**yml : Azure Web App Container Task (conf.yml)** 
```
version: '3.7'

services:
  web:
    command: python3 manage.py runserver 0.0.0.0:8000
    image: "${AZ_CONTAINER_REGISTRY}/${APP1_IMAGE}:${APP1_VERSION}"
    ports:
      - 8000:8000
  app2:
    command: python app.py
    image: "${AZ_CONTAINER_REGISTRY}/${APP2_IMAGE}:${APP2_VERSION}"
    expose:
      - 8080
```
