### ISSUE TITLE
FileTransform task sporadically doesn't apply variable substitutions

### ISSUE THREAD

**Issue by ajbrun** [microsoft/azure-pipelines-tasks#13618]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: FileTransform

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

The FileTransform task doesn't always appear to substitute variables in the appsettings section of my web.config file. I have pulled out a minimum working demonstration so that this can easily be replicated elsewhere.

The problem _may_ be related to there being dots in the key for the setting we're substituting, but I would expect this to work regardless. It is especially odd that it replaces some of the variables some of the time and isn't consistent in the ones is chooses to replace. I also have a query along similar lines regarding casing.

### Replication
**Create variable group "FileTransformIssue"**

- authentication_domain: DOMAIN_REPLACED
- authentication_password: PASSWORD_REPLACED
- authentication_username: USERNAME_REPLACED
- ControlVariable: True
- isLive: False

azure-pipelines.yaml:
``` yaml
trigger: none

pool:
  vmImage: 'windows-2019'

stages:
- stage: 'Staging'
  variables:
  - group: FileTransformIssue

  jobs:
  - job: 'Transform'
    # IsLive: $(isLive) is NOT included below due to it creating a cyclical reference.
    # However, without it, it is not replaced likely due to the casing difference. Is the
    # FileTransform task case sensitive? In the event we have the same variable key in multiple
    # config files with different casings, can it be made case in-sensitive?
    
    # Mapping variables in which we intend to replace.
    # Many apps depend on this variable group, and they may have different keys.
    # This allows us to define the variable once only in the variable group.
    variables: 
      Authentication.Domain: $(authentication_domain)
      Authentication.Username: $(authentication_username)
      Authentication.Password: $(authentication_password)
    steps:

    - script: |
        echo ControlVariable: $(ControlVariable)
        echo isLive: $(isLive)
        echo authentication_domain: $(authentication_domain)
        echo authentication_username: $(authentication_username)
        echo authentication_password: $(authentication_password)
      displayName: 'Output variables'
    
    - script: type Web.config
      displayName: 'Show Web.config contents before transform'

    - task: FileTransform@1
      displayName: 'Apply variable substitutions'
      inputs:
        folderPath: ''
        fileType: 'xml'
        targetFiles: 'Web.config'
        
    - script: type Web.config
      displayName: 'Show Web.config contents after transform'

```

web.config
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>    
    <add key="ControlVariable" value="TO_BE_REPLACED"/>
    <add key="IsLive" value="TO_BE_REPLACED"/>
    <add key="Authentication.Domain" value="TO_BE_REPLACED"/>
    <add key="Authentication.Username" value="TO_BE_REPLACED"/>
    <add key="Authentication.Password" value="TO_BE_REPLACED"/>
  </appSettings>
</configuration>
```

### Result
When this runs, the last three variables (Authentication.*) don't always get replaced. Sometimes they do, and sometimes they don't. There doesn't appear to be any consistency to it. I'm unsure if this is due to there being a dot in the original key name, which I believe should be a supported scenario.

**Actual results:**
This is only an example. Sometimes it all displays as expected and other times it only replaces a single authentication key.
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>    
    <add key="ControlVariable" value="True"/>
    <add key="IsLive" value="TO_BE_REPLACED"/>
    <add key="Authentication.Domain" value="TO_BE_REPLACED"/>
    <add key="Authentication.Username" value="TO_BE_REPLACED"/>
    <add key="Authentication.Password" value="PASSWORD_REPLACED"/>
  </appSettings>
```

**Expected results:**
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>    
    <add key="ControlVariable" value="True"/>
    <add key="IsLive" value="False"/>
    <add key="Authentication.Domain" value="DOMAIN_REPLACED"/>
    <add key="Authentication.Username" value="USERNAME_REPLACED"/>
    <add key="Authentication.Password" value="PASSWORD_REPLACED"/>
  </appSettings>
</configuration>
```

* Expect Authentication.* keys to be consistently replaced with values from the variable group.
* Expect key name matching not to be case sensitive so IsLive gets replaced.

**Comment by ajbrun** [comment]
After further testing, I believe now that this only happens when I map the variables to a new name. I've tried with a new set of variables (App.*) without mapping, and these substitutes as expected each of the times I ran the pipeline. Whilst I have a workaround, I would still prefer this to work as I would prefer the naming convention of my variable names not to be directly linked to the naming convention of our application settings which may not be consistent throughout our applications.

**Comment by AmrutaKawade** [comment]
> After further testing, I believe now that this only happens when I map the variables to a new name. I've tried with a new set of variables (App.*) without mapping, and these substitutes as expected each of the times I ran the pipeline. Whilst I have a workaround, I would still prefer this to work as I would prefer the naming convention of my variable names not to be directly linked to the naming convention of our application settings which may not be consistent throughout our applications.

Sorry I am not able to understand this. Can you give example of config file which did not work and which worked?

**Comment by AmrutaKawade** [comment]
Closing this issue due to inactivity. Please feel free reopen with requested information.

**Comment by ajbrun** [comment]
It's been a few weeks since I've looked at this, but please see my initial post with these lines:
```
    # Mapping variables in which we intend to replace.
    # Many apps depend on this variable group, and they may have different keys.
    # This allows us to define the variable once only in the variable group.
    variables: 
      Authentication.Domain: $(authentication_domain)
      Authentication.Username: $(authentication_username)
      Authentication.Password: $(authentication_password)
```

With those lines, a web config setting with the key name "authentication_domain" would get substituted, but if I map the variable value to a new variable "Authentication.Domain", then a key with the name "Authentication.Domain" does not get substituted.

The replication steps in my original post still stand I believe - using those lines of YAML code and following the steps, are you able to reproduce my issue?

**Comment by asranja** [comment]
The problem is because of the way Azure DevOps treats variables with dots(.). ADO converts dot characters to underscores in variables. So in this case, there is a conflict in the variable name `Authenticaion.Domain` which gets interpreted as `authentication_domain`. Since there is already a variable `authentication_domain` defined in the variable group, there is a conflict, so only one of either `Authentication.Domain` or `authentication_domain` is set. Whenever `Authentication.Domain` is set, the substitution works. Here is an example variables object passed to the FileTransform task with no `Authentication.Domain` key:
```
{ 'Authentication.Password': 'PASSWORD_REPLACED',
  'Authentication.Username': 'USERNAME_REPLACED',
  authentication_domain: 'DOMAIN_REPLACED',
  ControlVariable: 'True',
  VSTS_PROCESS_LOOKUP_ID: 'vsts_6b184275-3103-44eb-be98-395d3c834bc7',
  'task.displayname': 'Apply variable substitutions',
  'resources.triggeringAlias': '',
  GIT_TERMINAL_PROMPT: '0',
  MSDEPLOY_HTTP_USER_AGENT: 'VSTS_16d96c78-5bf5-4779-b1bd-be7ddb2395ba_build_41_0',
  isLive: 'False',
  system: 'build',
  'resources.triggeringCategory': '' }
```

**Suggestion:**
Please use a non conflicting name in the variable group like:
```
authenticationdomain: DOMAIN_REPLACED
authenticationpassword: PASSWORD_REPLACED
authenticationusername: USERNAME_REPLACED
ControlVariable: True
isLive: False
```

You can then reference this in your pipeline as :

```yml
variables: 
      Authentication.Domain: $(authenticationdomain)
      Authentication.Username: $(authenticationusername)
      Authentication.Password: $(authenticationpassword)
```
