### ISSUE TITLE
ExtractFiles Task does not work anymore

### ISSUE THREAD

**Issue by davidguidali** [microsoft/azure-pipelines-tasks#13613]
Since yesterday, the ExtractFiles task does not work anymore in my solution. I have not changed anything in my setup, so I guess its due to some updates in the task itself.

I have the following tasks in my pipeline definition yml:
```
 - download: current
   displayName: Download Binaries
   artifact: TestApp
 - task: ExtractFiles@1
   displayName: Unzip Files
   inputs:
     archiveFilePatterns: $(Pipeline.Workspace)/*.zip
     destinationFolder: $(Pipeline.Workspace)/extracted
     cleanDestinationFolder: true
```
My artifact folder is only containing the .zip folder I want to extract:
![image](https://user-images.githubusercontent.com/61904428/94268173-0d553f80-ff3d-11ea-9114-a4423cec33ef.png)

The task failes since last night:

![image](https://user-images.githubusercontent.com/61904428/94268393-61f8ba80-ff3d-11ea-8e00-fa9c910a1091.png)

As you can see, it is running in a windows docker container. 
Please fix.
