### ISSUE TITLE
DownloadPipelineArtifact uses inconsistent paths

### ISSUE THREAD

**Issue by vaughnbeanz** [microsoft/azure-pipelines-tasks#13622]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Maybe Bug

**Enter Task Name**: DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines
    
account name : vaughnbutt
team project name : ProjectPOC2
build definition name : YAMLPipelinePOC
build number: buildId=134, #20200929.15

- Agent - Hosted: 
    
agent queue name: umm?

## Issue Description

Summary : The paths used by DownloadPipelineArtifact when the path (aka targetPath) is specified and when it is not specified are inconsistent (I think).

If my analysis is correct then if you execute DownloadPipelineArtifact@2 then the files in the artifact are downloaded to either:
* the directory $(System.DefaultWorkingDirectory)/\<targetPath\>/ when targetPath is set OR
* the directory $(Pipeline.Workspace) when targetPath is not set

Thus a job with these steps:
```
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'myafiles'
          - script: ls -lR $(Pipeline.Workspace)
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'myafiles'
              targetPath: mytarget
          - script: ls -lR $(Pipeline.Workspace)
          - script: find $(Pipeline.Workspace) | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
```
results in 
```
ls -lR /home/vsts/work/1
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/a4cabc49-fbd0-4493-b809-bbd09930fc50.sh
/home/vsts/work/1:
total 20
drwxr-xr-x 2 vsts docker 4096 Sep 29 01:22 TestResults
drwxr-xr-x 2 vsts docker 4096 Sep 29 01:22 a
drwxr-xr-x 2 vsts docker 4096 Sep 29 01:22 b
drwxr-xr-x 2 vsts docker 4096 Sep 29 01:22 myafiles
-rw-r--r-- 1 vsts docker    0 Sep 29 01:22 myfile-20200929.18
drwxr-xr-x 3 vsts docker 4096 Sep 29 01:22 s

/home/vsts/work/1/TestResults:
total 0

/home/vsts/work/1/a:
total 0

/home/vsts/work/1/b:
total 0

/home/vsts/work/1/myafiles:
total 0
-rw-r--r-- 1 vsts docker 0 Sep 29 01:22 myfile-20200929.18

/home/vsts/work/1/s:
total 4
drwxr-xr-x 2 vsts docker 4096 Sep 29 01:22 mytarget

/home/vsts/work/1/s/mytarget:
total 0
-rw-r--r-- 1 vsts docker 0 Sep 29 01:22 myfile-20200929.18
```

and
```
find /home/vsts/work/1 | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/e2486638-f9f0-4912-b3bb-49627936a743.sh
 | | |-1
 | | | |-s
 | | | | |-mytarget
 | | | | | |-myfile-20200929.18
 | | | |-myfile-20200929.18
 | | | |-a
 | | | |-b
 | | | |-TestResults
 | | | |-myafiles
 | | | | |-myfile-20200929.18

```
_Note that the directory and file at $(Pipeline.Workspace)/myafiles is the result of the implicit Download Artifact step._

I would have expected that these paths would either both be based at $(Pipeline.Workspace) or both based at $(System.DefaultWorkingDirectory)

### Task logs

TBD
### Error logs

No errors logged.
