### ISSUE TITLE
Feature Request: [Pipeline Caching] Please add control options to run "Post-job: Cache" even if a previous task has failed.

### ISSUE THREAD

**Issue by Connect-a** [microsoft/azure-pipelines-tasks#13625]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Pipeline Caching

## Issue Description
I encountered a case where I wanted to cache a specified folder, regardless of the success or failure of the pipeline.  
The pnpm package manager caches library packages in the ".pnpm-store" folder.  
Often it fails to download packages, but this does not cause any inconsistencies in the cache folder.  
Cache tasks don't work when the pipeline fails, so there are no fewer packages to download when you run the pipeline again.  

That's why I want to configure the Cache task to work even if the pipeline fails.

**Comment by AndrewCraswell** [comment]
I'm also trying to enable pipeline caching for pnpm at the moment as well, do you happen to have a yaml example you're working with?

**Comment by Connect-a** [comment]
@AndrewCraswell 
I am currently trying to use the following yaml.
```yaml
- script: 'npm install -g pnpm'
  displayName: 'install pnpm'

- script: 'pnpm config set store-dir $(Agent.TempDirectory)/.pnpm-store'
  displayName: 'set store dir'

- task: Cache@2
  displayName: Cache
  inputs:
    key: '""'
    path: '$(Agent.TempDirectory)/.pnpm-store'
  continueOnError: true
  condition: always()

- script: 'pnpm install --frozen-lockfile'
  displayName: 'pnpm install'

- script: 'pnpm build'
  displayName: 'pnpm build'

- task: ArchiveFiles@2
  displayName: 'Archive dist'
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
```
