### ISSUE TITLE
Why is JavaToolInstaller cleaning destination folder when using 'PreInstalled'

### ISSUE THREAD

**Issue by henryju** [microsoft/azure-pipelines-tasks#13629]
I tried to use JavaToolInstaller in my pipeline. I put it just after the checkout step:
```
    jobs:
    - job: build
      steps:
      - checkout: self
        fetchDepth: 1
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
```

To my surprise, all checked out source files have been removed. Looking at the logs, I found:
```
Starting: JavaToolInstaller
==============================================================================
Task         : Java tool installer
Description  : Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME
Version      : 0.175.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/java-tool-installer
==============================================================================
Cleaning destination folder before extraction: /home/vsts/work/1/s
Use preinstalled JDK from /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
JAVA_HOME is being set to: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
JAVA_HOME_11_x64 is being set to: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
Prepending PATH environment variable with directory: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin
Finishing: JavaToolInstaller
```

I'm wondering what is the point to clean the destination folder in this case, especially when it seems to default to the [work dir.](https://github.com/microsoft/azure-pipelines-tasks/blob/414c031e3dc5d51f0f22845caae79cfa07e1c9fc/Tasks/JavaToolInstallerV0/task.json#L114) and it is not even supposed to be set when using `PreInstalled`.

My workaround is to do the checkout after calling JavaToolInstaller, but this will prevent to switch to a different JDK later.
