### ISSUE TITLE
FtpUpload task add option to fail if no files were uploaded

### ISSUE THREAD

**Issue by oleksabor** [microsoft/azure-pipelines-tasks#13648]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: FtpUpload

## Issue Description

It would be nice to have a feature (new option) that will raise an error if no files were uploaded.

I've got a problem recently: there was an error in the task parameterisation. 
The FtpUpload task has not find files to upload but no error was shown and pipeline was marked as completed succesfuly. 
But the purpose of the pipeline was to upload files by ftp. 
And "no files were found to upload" is an error actually in that case. 
Probably there are cases when file uploading is not mandatory but it would be nice to have an option and make it mandatory.

I have a task like 

```
steps:
- task: FtpUpload@2
  displayName: 'FTP Upload: $(System.ArtifactsDirectory)\bin'
  inputs:
    credentialsOption: inputs
    serverUrl: '$ftpUrl)'
    username: '$(ftpUser)'
    password: '$(ftpPassword)'
    rootDirectory: '$(System.ArtifactsDirectory)\bin'
    remoteDirectory: /site/wwwroot
    cleanContents: true
    preservePaths: true
    trustSSL: true
```

### Task logs

Task writes warning if no files were found
> 2020-10-01T14:25:36.4142531Z ##[warning]Could not find any files to upload

I've [added additional step with powershell script](https://stackoverflow.com/q/64168812/940182) but it does not look good
