### ISSUE TITLE
How to get latest version on chartPath for HelmDeploy task?

### ISSUE THREAD

**Issue by francescocristallo** [microsoft/azure-pipelines-tasks#13654]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: HelmDeploy

## Environment

Azure Devops Pipeline - Yaml

## Issue Description

I have an Azure Pipeline that builds a Docker container from an Asp.Net Core application and uploads it to Azure Container Registry.

The source code chart is packaged, deployed on the temp artifact path, and then deployed to Kubernetes with Helm 3 commands.

```
 - task: HelmDeploy@0
        inputs:
          command: 'package'
          chartPath: Server/charts/server
          destination: $(Build.ArtifactStagingDirectory)

      - task: HelmDeploy@0
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'Staging12602128'
          namespace: 'staging'
          command: 'upgrade'
          chartType: 'FilePath'
          chartPath: '$(Build.ArtifactStagingDirectory)/server-0.0.1.tgz' **<<== How to select latest version?**
          releaseName: 'server'
```

The destination on the package command, uses the latest version of the chart (that I change from Visual Studio updating Chart.yaml manually every time), and it's like this /home/vsts/work/1/a/server-0.1.1.tgz

The 'chartPath' variable of the upgrade command, in all the examples I found online and in the documentation, specify the exact version of the tgz package. Is there a way to automatically insert the latest chart version so I don't have to change it manually on every upgrade?

I tried without success:

```
chartPath: '$(Build.ArtifactStagingDirectory)/server-*.tgz'

chartPath: '$(Build.ArtifactStagingDirectory)/*.tgz'

chartPath: '$(Build.ArtifactStagingDirectory)/$(Build.SourceVersion).tgz'

chartPath: '$(Build.ArtifactStagingDirectory)/server-$(Build.DefinitionName).tgz'
```

Any help or insightwould be really appreciated.
I also opened a StackOverflow question 2 days ago:

https://stackoverflow.com/questions/64175561/azure-devops-pipelines-helmdeploy-how-to-get-latest-version-on-chartpath
