### ISSUE TITLE
Scope is ignored when using fallback keys in Cache task 

### ISSUE THREAD

**Issue by beatcracker** [microsoft/azure-pipelines-tasks#13666]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment

- **Server**:  Azure Pipelines
- **Agent**
  - Private agent 2.173.0
  - CentOS Linux 7 (Core) 3.10.0-1127.19.1.el7.x86_64

## Issue Description

When using fallback keys, the scope is ignored and cache is restored from another branch.
In my case, the pipeline was run on the `release/0.618` branch. Inexact cache hit restored cache from the `master` branch.

```none
Used scope: 46;88ce3bc5-b5d8-4e40-8765-65e959460288;refs/heads/master;foo/bar
Missed on the following scopes: 46;88ce3bc5-b5d8-4e40-8765-65e959460288;refs/heads/release/0.618.0;foo/bar
```

This contradicts documentation:

- https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching#cache-isolation-and-security

> Because caches are already scoped to a project, pipeline, and branch, there is no need to include any project, pipeline, or branch identifiers in the cache key.

### Cache task configuration

```yml
# Implements rolling cache using Git revision as a key to keep cache fresh
- task: Cache@2
  displayName: Restore cache | build
  inputs:
    cacheHitVar: BUILD_CACHE
    key: '"build" | "$(Build.SourceVersion)"'
    restoreKeys: |
      "build"
    path: $(Build.SourcesDirectory)/build
```

### Task logs (anonymized)

```none
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - "build"                                   [string]
 - "d8779b713a2031b0ea5ac7ed0dfeb0b139bd660" [string]
Resolved to: "build"|"d8779b713a2031b0ea5ac7ed0dfeb0b139bd660"
Resolving restore key:
 - "build" [string]
Resolved to: "build"|**
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session beeb18f3-b50e-494f-a5c6-6ee722a8eba6
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `"build"|"d8779b713a2031b0ea5ac7ed0dfeb0b139bd660"`
Fingerprint: `"build"|**`
There is a cache hit: `"build"|"e59ff9f63151105dd4eae54622b836b50d1c7ab7"`
Used scope: 46;88ce3bc5-b5d8-4e40-8765-65e959460288;refs/heads/master;foo/bar
Missed on the following scopes: 46;88ce3bc5-b5d8-4e40-8765-65e959460288;refs/heads/release/0.618.0;foo/bar
Entry found at fingerprint: `"build"|"e59ff9f63151105dd4eae54622b836b50d1c7ab7"`
Expected size to be downloaded: 411.2 MB
Downloaded 0.0 MB out of 411.2 MB (0%).
Downloaded 230.7 MB out of 411.2 MB (56%).
Downloaded 411.2 MB out of 411.2 MB (100%).

Download statistics:
Total Content: 411.2 MB
Physical Content Downloaded: 158.0 MB
Compression Saved: 253.2 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 4,700
Nodes Downloaded: 10

Process exit code: 0
Cache restored.
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session beeb18f3-b50e-494f-a5c6-6ee722a8eba6
```

**Comment by johnterickson** [comment]
@fadnavistanmay There is a question to walk through exact/inexact first or through scopes first. I think this is the expected order, right?

**Comment by beatcracker** [comment]
> I think this is the expected order, right?

I see how this may be expected from the code perspective, but the documentation doesn't mention that. For now, I've fixed this using branch name in keys:

```yml
key: '"build" | "$(Build.SourceBranch)" | "$(Build.SourceVersion)"'
restoreKeys: |
  "build" | "$(Build.SourceBranch)"
```

It would be great if this behavior was at least documented.
