### ISSUE TITLE
AzureDevops ServiceConnection for AKS can create a role assignment for acrpull with KubernetesManifest Task

### ISSUE THREAD

**Issue by Sudharma** [microsoft/azure-pipelines-tasks#13685]
For AKS currently we do not use the imagePullSecret and instead we create a role for AcrPull from the service principal which created the AKS. Azure does the magic inside the cluster which delegates the Kubernetes manifests to pull docker images from azure container registry. However with Azure devops we are creating a service connection which is used to spawn the AKS.  I would like to have a plug point to provide a role for AcrPull instead of imagePull secret. This creates consistency since we have manifests running via both azure devops and also via our bamboo pipelines. This will make life easy for others who want to migrate to azure devops.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: KubernetesManifest

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ds-ms** [comment]
You could run an az-cli script to achieve the same though, right?
```sh
SP_ID=$(az aks show --resource-group myResourceGroup --name myAKSCluster --query servicePrincipalProfile.clientId -o tsv)
az role assignment create --assignee $SP_ID --scope <resourceScope> --role AcrPull
```

**Comment by Sudharma** [comment]
of course but it involves creating another shell task and do not want to go with the boilerplate code again. Wouldn't it be just easy to create it in a task by adding a key called `AcrPull` Role. in `KubernetesManifest` task

**Comment by ds-ms** [comment]
Honestly I see this as a one time setup, so you wouldn't even need it to be a part of your pipeline. 
I'd suggest you have this script integrated with your ServicePrincipal rotation's automation. 

Also while creating a K8s connection for AKS, we don't create a Service Principal internally, we create a service account in the cluster to establish a connection. Given that the task you're mentioning doesn't support SPN mode for connection (exclusively depends on SA mode) I don't see the need for this feature.

Adding our PM to take a look. @anraghun

**Comment by Sudharma** [comment]
Well the whole purpose of managed identity is not to manage service principal but with above suggestion I need to create and maintain one. Also I see the problem from different angle.

**Outside the scope of azure devops**

1. with Service Principal.

    -  I create a AKS cluster and assign a service principal to it which it uses for internal usage(PVC, key vault) 

    -  I create a role with AcrPull with the same SP I created before.( This is also as suggested by Azure)

2. With managed Identity.

  - I create AKS cluster with system managed identity.
 - A role needs to be created . Git issue is here --> https://github.com/Azure/AKS/issues/1428

**Now within the Scope of Azure Devops.**

The creation of SP and MSI is abstracted via service connection. Now as a developer It doesn't make sense for me to create a new SP and then create a role for it. What I could however do is create a service connection with ACR and basically do this

```
- task: KubernetesManifest@0
  displayName: Create imagePullSecret
  inputs:
    action: createSecret
    secretName: dockerregistry
    namespace: default
    dockerRegistryEndpoint: acr-service-connection
    kubernetesServiceConnection: aks-service-connection
```

However to get this running I need to do this and add the `dockerregistry`. So basically I need to do this additional work.

```
- task: KubernetesManifest@0
  displayName: Deploy to Kubernetes cluster
  inputs:
    action: deploy
    namespace: default
    manifests: |
       $(System.DefaultWorkingDirectory)/my.yaml
    imagePullSecrets: |
       **dockerregistry**
    containers: |
      myhub.azurecr.io/nginx/hello:test
    kubernetesServiceConnection: aks-service-connection
```



> Also while creating a K8s connection for AKS, we don't create a Service Principal internally, we create a service account in the cluster to establish a connection.

This is not true because it is an option to the developer and I am not using service account but a proper managed identity via a Kubernetes Service connection.

The situation is not bad either I can go ahead with the above approach but the only problem is the consistency of usage of cluster on azure devops or on gitlab CI/CD.
