### ISSUE TITLE
Deploy SQL Dacpac Deployment Group Variable Input Not Working

### ISSUE THREAD

**Issue by BChip** [microsoft/azure-pipelines-tasks#13696]
## Required Information
*Type*: Bug
**Enter Task Name**: SqlDacpacDeploymentOnMachineGroupV0

## Environment
- Server - Azure Pipelines
- Agent - Private: 
    - Windows Server 2016 - Agent version 2.166.4

## Issue Description

Variables for task's sql auth inputs does not work. If I manually put the sqlusername and sqlpassword in plaintext into the task inputs, it does work. 

Ex (does not work):
```
steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName 'Deploy using : sqlQuery'
  inputs:
    TaskType: sqlQuery
    SqlFile: '$(System.DefaultWorkingDirectory)\_MyRepo\drop\init.sql'
    ServerName: mysql.company.com
    DatabaseName: appdb
    AuthScheme: sqlServerAuthentication
    SqlUsername: '$(DatabaseUser)'
    SqlPassword: '$(DatabasePassword)'
```

Error: **Login failed for user 'company\releaseagent'**

It looks like it is switching to windows authentication instead when using variables for the sql username and password.

Ex (does work):
```
steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName 'Deploy using : sqlQuery'
  inputs:
    TaskType: sqlQuery
    SqlFile: '$(System.DefaultWorkingDirectory)\_MyRepo\drop\init.sql'
    ServerName: mysql.company.com
    DatabaseName: appdb
    AuthScheme: sqlServerAuthentication
    SqlUsername: username123
    SqlPassword: password123
```
Overall, I don't want these credentials sitting in plain text in the task. I would like to use secret variables. Is this a bug or is this feature not implemented in this task?

Thank you!!!!
