### ISSUE TITLE
Code Coverage  do not match with Azure DevOps summary

### ISSUE THREAD

**Issue by vishwanathsrikanth** [microsoft/azure-pipelines-tasks#13703]
## Required Information

The build summary page of Azure DevOps pipelines show a different code coverage (less code coverage) when compared to TRX file. 

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure DevOps build summary 

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishTestResultsV2

## Environment
- Server - Azure Pipelines
- Agent - Private: 
![image](https://user-images.githubusercontent.com/2102408/95956548-163e8000-0e1c-11eb-9eff-7c110a098ea9.png) 

## Issue Description

Azure DevOps build summary shows different code coverage than what is show on Visual studio when we download the trx file.

From build summary
![image](https://user-images.githubusercontent.com/2102408/95956723-53a30d80-0e1c-11eb-8e93-ac36c9c79fea.png)

From VS when I downloaded the TRX file. 

![image](https://user-images.githubusercontent.com/2102408/95957291-299e1b00-0e1d-11eb-89be-ed15b95392e0.png)

The task does not contain any Test filters, RunSettings - below is the configuration 

![image](https://user-images.githubusercontent.com/2102408/95957642-91546600-0e1d-11eb-8f79-935c94d9c44c.png)

**Comment by TianyuHou** [comment]
Any updates on this issue? our project faced the same issue.
![image](https://user-images.githubusercontent.com/31544262/100140947-83472b80-2e46-11eb-8f6b-a80ed85efad7.png)
![image](https://user-images.githubusercontent.com/31544262/100141054-a4a81780-2e46-11eb-96d5-49669e0e763a.png)

**Comment by paulroreilly** [comment]
Same problem for our project - DevOps Pipeline shows 70% code coverage, but same tests in VS2019 show 95%.

Not ideal to have to lower the threshold so much to make sure the builds are failed when the coverage is good.

**Comment by anatolybolshakov** [comment]
Hi @vishwanathsrikanth this issue doesn't seem to be related to pipeline tasks - could you please create an issue on https://developercommunity.visualstudio.com - to get the right eyes on it?

**Comment by StingyJack** [comment]
Same problem here, but for me its the line counts that are deficient from the pipeline task thats causing the numbers to be off

This is VS displaying the coverage file that was produced from VSTest task (Single file depicted). That total line count is WAY off. 
![image](https://user-images.githubusercontent.com/15381181/111035795-09818080-83ea-11eb-9d32-f9698b9621ad.png)


This is from running the code coverage in VS for the same commit.  VS has made a bunch of lambdas out of things but the "testable and not covered" line count of 529 would be closer to correct for a 900 line file, sans namespaces, imports, braces, etc.  
![image](https://user-images.githubusercontent.com/15381181/111035885-7432bc00-83ea-11eb-85f8-f50f0f8de609.png)

**Comment by nk111** [comment]
In my case it was the difference between "% of blocks covered" which is displayed in VS by default and "% of lines covered" which seems to be displayed in the build summary!

**Comment by StingyJack** [comment]
You should be able to change the columns in VS to see if the counts match up

**Comment by nk111** [comment]
> @nk111 You should be able to change the columns in VS to see if the counts match up

Yepp, your screenshot made me aware of this option actually ;)

**Comment by eduralph** [comment]
This error occurred for me when I had 2 different test runs - a Unit Test & then later an Integration Test. In this case, the percentage shown on the summary page was from the Unit Test **only** while on the detail page, it showed the **accumulated** coverage by Unit & Integration Test.

**Comment by Patafoin** [comment]
Same problem here : multiple tests projects running after each other.
Report is showing 97% of covered code
Azure pipeline summary is showing about 25% percent. 
Seems that azure pipelines doesn't take care of the same results than ReportGenerator do. 
And it's not only a problem of using last project results because all my included projects are about 95-97% tested. I think Azure pipelines doesn't take care of tests settings neither (for my, they exclude some tools projects that don't have to be covered).

**Comment by lsiddiquee** [comment]
Seems like this is a very common issue. Any update on this issue? I am seeing a coverage of 23% in summary in reality when the tests are executed in VS I have over 90% coverage.

**Comment by FrankRua** [comment]
Same here, VS showing ~80% test coverage, Azure showing 50.51%.

**Comment by FrankRua** [comment]
@phanikmmsft - Any update on this issue? This is critical to CI/CD pipelines ensuring good code coverage.

**Comment by nadesu** [comment]
@v-pkoneti - pls look into this.

**Comment by gioce90** [comment]
I have noticed some similar problems.

My pipeline run these tasks:

```
# ... DotNetCoreCLI@2 restore task ...

  - task: DotNetCoreCLI@2
    displayName: 'DotNetCoreCLI Test with report (cobertura format)'
    inputs:
      command: test
      projects: '**/**.Tests.csproj'
      arguments: '--no-restore --collect "Code Coverage" --logger trx --results-directory "TestResults/Coverage/" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
      publishTestResults: false

  - task: reportgenerator@4
    inputs:
      reports: '$(Build.SourcesDirectory)/TestResults/Coverage/**/**.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/TestResults/Coverage/Reports'
      reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
      assemblyfilters: '+MyOrganization.**;-MyOrganization.**.Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      failTaskOnFailedTests: true

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(Build.SourcesDirectory)/TestResults/Coverage/Reports/Cobertura.xml
      reportDirectory: $(Build.SourcesDirectory)/TestResults/Coverage/Reports
      failIfCoverageEmpty: false
```
Please note that I set a variable `disable.coverage.autogenerate = true` and use a preview nuget package  17.1.0-preview-20211118-03

This works well and pubblish tests and code coverage. In the "code coverage" tab I see this:
![image](https://user-images.githubusercontent.com/6142403/151369836-f1d17d3b-606f-4ccd-8afc-f4a57c66a605.png)

However, if I switch the test task to coverlet in this way:

```
# same restore...

  - task: DotNetCoreCLI@2
    displayName: 'DotNetCoreCLI Test with report (XPlat Code Coverage - cobertura format)'
    inputs:
      command: test
      projects: '**/**.Tests.csproj' # if multiple test projects are to be executed, create a dirs.proj and use it here. That will ensure the tests are executed in parallel
      arguments: '--no-restore --collect "XPlat Code Coverage" --logger trx --results-directory "TestResults/Coverage/" '
      publishTestResults: false

# same tasks...
```

This is what I see in the "code coverage" tab this time:
![image](https://user-images.githubusercontent.com/6142403/151370103-5bd7fba8-8e24-4e9a-a732-86a2a42f6711.png)
Why?

Another try is with this:

```
# same restore...
  - task: DotNetCoreCLI@2
    displayName: 'DotNetCoreCLI Test with report (.coverage format)'
    inputs:
      command: test
      projects: '**/**.Tests.csproj' # if multiple test projects are to be executed, create a dirs.proj and use it here. That will ensure the tests are executed in parallel
      arguments: '--collect "Code Coverage" '
      publishTestResults: true
# no other tasks needed...
```
I don't like that because doesn't populate the "Code coverage" tab on the build. I use this on another pipeline for obtain the Pull Request Diff coverage (and is awkward, I know, but for now is the only way to have full and diff coverage). However, is possible to download the .coverage file and I noticed something interesting:
![image](https://user-images.githubusercontent.com/6142403/151377722-d3e48f50-5e5c-4f95-ba17-2472899a9ac1.png)

I also saw my solution's "Code Coverage Results" in Visual Studio, and it seems to me that I have others different results (I noticed that in VS the code coverage include the "*.Tests.dll".
 
Probably all these different methods to obtain code coverage use different filters. How to choose one?
