### ISSUE TITLE
Maven task needs to allow setting the working directory

### ISSUE THREAD

**Issue by thorntonrp** [microsoft/azure-pipelines-tasks#13753]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven

## Environment
- Server - Azure Pipelines
https://dev.azure.com/churchofjesuschrist/Stack%20Team/_build/results?buildId=128892&view=results

- Agent - Hosted or Private: 
Hosted and Private

## Issue Description

The Maven does not appear to allow setting the working directory. Setting the working directory is necessary in order for Maven to detect and use the .mvn/extensions.xml file. Without being able to set the working directory, builds that rely on Maven extensions will fail. In my case, the Maven build extension reads the Maven project model from a `pom.kts` kotlin script instead of the default pom.xml.

**Comment by EzzhevNikita** [comment]
Hi @thorntonrp , unfortunately I couldn't reproduce this issue. I would like to to ask for some additional information about this issue, please provide:
- the full log with enabled diagnostics
- if it is possible please share the minimal reproducible sample for this issue or concrete steps to reproduce this issue

**Comment by thorntonrp** [comment]
It was apparently a configuration issue on my end. I've been able to get it working with this configuration:

```yml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: "pom.kts"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: "1.11"
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/surefire-reports/TEST-*.xml"
    goals: "verify"
```

Thanks for looking into it.
