### ISSUE TITLE
helm lint does not recognize chartType / chartPath

### ISSUE THREAD

**Issue by agilekevin** [microsoft/azure-pipelines-tasks#13786]
**Question, Bug, or Feature?**  
*Bug*: 
I expected to be able to set the chart path with the chartPath input variable, but it is ignored.

Expected to work:
```
          - task: HelmDeploy@0
            displayName: Helm Lint
            inputs:
              ConnectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: k8s
              command: lint
              arguments: -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml
              chartType: filepath
              chartPath: ./multi-helm/
```

Instead, I had to wedge it into arguments:
```
              arguments: ./multi-helm -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml
```

**HelmDeploy**: HelmDeploy@0

## Environment
- Server - Azure Pipelines
