### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3: Request for template spec support

### ISSUE THREAD

**Issue by aholler2** [microsoft/azure-pipelines-tasks#13789]
## Required Information

**Type**: Feature Request

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Please add [template spec support](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-specs) for YAML deployment task **AzureResourceManagerTemplateDeployment@3** e.g.
```yaml
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'My Service Connection'
    subscriptionId: '22222222-2222-2222-2222-222222222222'
    resourceGroupName: 'myresourcegroup'
    location: 'Central US'
    templateSpecId: '/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/templateSpecsRG/providers/Microsoft.Resources/templateSpecs/storageSpec/versions/1.0'
    templateParameterFile || csmParametersFile: 'mainTemplate.parameters.json'
```
