### ISSUE TITLE
InstallAppleCertificate@2 Doesn't accept variables for parameter certSecureFile

### ISSUE THREAD

**Issue by Zanchee** [microsoft/azure-pipelines-tasks#13783]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

Feature / Bug

InstallAppleCertificate@2

## Environment
- Server - Azure Pipelines

- Agent - Private: 
    
    - macOS-10.15

## Issue Description

The InstallAppleCertificate@2 task doesn't support the ability to pass in a variable for the secure file. Is this on purpose or is this something that could be added? Our Xcode project builds multiple applications from one source and each app has its own signing certificate. I was hoping to utilize this task with matrices to install the relevant certificate per run.

Ideally it would be helpful to be able to do something like this.
```
- task: InstallAppleCertificate@2
  displayName: '🔐 Install Signing Certificate'
  inputs:
    certSecureFile: $(certificate)
    certPwd: $(certificate_password)
```

### Error logs

```
There was a resource authorization issue: "The pipeline is not valid. Job Job: Step InstallAppleCertificate input certSecureFile references secure file $(certificate) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
```

**Comment by egor-bryzgalov** [comment]
Hi @Zanchee 
Thank you for opening the issue! 
I've tried to reproduce the issue but it worked fine for me. For us to investigate the issue further, could you please share the following information if it's possible:
- build logs in debug mode;
- YAML file containing the pipeline definition;
We're looking forward to hearing from you!

**Comment by Zanchee** [comment]
@egor-bryzgalov so I can't grab you a build log b/c it doesn't startup the build. It immediately cancels with the following issue

<img width="818" alt="Screen Shot 2020-10-28 at 10 19 41 AM" src="https://user-images.githubusercontent.com/13373737/97448585-32a3e780-1907-11eb-8660-30b2fae3f464.png">

I pruned my YAML to the following, just to make sure I was focusing JUST on the certificate installs.

```
pool:
  vmImage: 'macOS-10.15'

variables:
- group: certificate-passwords

strategy:
  matrix:
    APP_1:
        certificate: 'MY_CERTIFICATE_1.p12'
    APP_2:
        certificate: 'MY_CERTIFICATE_2.p12'

steps:
- task: InstallAppleCertificate@2
  displayName: '🔐 Install Certificate'
  inputs:
    certSecureFile: $(certificate)
    certPwd: $(certificate_password)
```

**Comment by LaurentGoderre** [comment]
I am experiencing the same issue!

**Comment by LaurentGoderre** [comment]
Here's how to reproduce:

```
jobs:
  - job:
    strategy:
      matrix:
        mojave:
          imageName: 'macOs-10.14'
          certificateFile: myCertificate
          certificatePassword: myPassword
        catalina:
          imageName: 'macOs-10.15'
          certificateFile: myCertificate1
          certificatePassword: myPassword2
          provisioningProfile: myProfile
    pool:
      vmImage: '$[variables.imageName]'
    steps:
    - task: InstallAppleCertificate@2
      displayName: 'Install an Apple certificate'
      inputs:
        certSecureFile: $(certificateFile)
        certPwd: $(certificatePassword)
```

**Comment by LaurentGoderre** [comment]
From what I can tell, there is some validation that happen on the pipeline definition before the variable substitution so the build doesn't even start. I am not able to find any of that logic in this repo though.

**Comment by egor-bryzgalov** [comment]
@LaurentGoderre @Zanchee Thank you for the information you've provided! We'll investigate this issue and keep you posted on the results.

**Comment by egor-bryzgalov** [comment]
Hi @Zanchee @LaurentGoderre 
It seems that it's not supported at the moment.
This issue's root cause is in pipeline processing steps order. It's required to have `secureFile` inputs values defined by the authorization step otherwise errors like one you had would be thrown.
So the matrix is resolved after the authorization step.

You can find more [information about pipeline processing here.](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline)

**Comment by Zanchee** [comment]
Thanks for the  update. We ended up making a dummy matrix yesterday by creating a pipeline that just calls a template with the same parameters. This worked 👍

**Comment by egor-bryzgalov** [comment]
@Zanchee I'm closing this issue. Please feel free to reopen it if it's necessary. Thank you!

**Comment by Guuz** [comment]
@egor-bryzgalov I would like to re-open this issue. Or at least ask for help. I believe i'm experiencing the same issue but don't see a workaround/solution.
note: this also looks to be the same issue: https://developercommunity.visualstudio.com/content/problem/984321/installsshkey-task-cant-resolve-variable-reference.html

I have a pipeline that deploys an app to a staging environment and later, after approval, to a production environment. This means that putting the variables for the `certSecureFile` for instance cant be place at the root level. They are different per environment.

But when placed at the stage or job level the `InstallAppleCertificate` task fails with the above mentioned error.

So how can we use the `InstallAppleCertificate` task with a `certSecureFile: '$(p12FileName)'` configuration? Combined with variables defined at the stage or job level since they are different per stage/job.

**Comment by egor-bryzgalov** [comment]
Hi @Guuz 

I think that you could try to use templates as was suggested by @Zanchee. 
As per [this article ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline) templates are processed before checking resources authorization. Only variables explicitly included in the pipeline can be used for such inputs. It also makes sense to experiment with variables syntax if it suits your demands.

If it doesn't help you to resolve your issue please share your YAML structure so we can look for possible ways to help you.

**Comment by Guuz** [comment]
I think the YAML might help. since i'm using templates already. but this seems to cause the issue. The below YAML files are obviously shortend by A LOT. just to show you the most important parts:

```yaml
# Part of the main pipeline that runs. contains other stages for testing for instance.
# And will later deploy to ACC, and with a manual approval build and deploy to PROD.
stages:
  - stage: build_acc
    jobs:
      - job: build_ios_acc
        variables:
          - group: ios_acc_variables
        steps:
          - template: pipeline-helpers/acc/build-ios.yml
      - job: build_android_acc
        variables:
            - group: android_acc_variables
        steps:
          - template: pipeline-helpers/acc/build-android.yml
```

```yaml
# Part of the build-ios.yml file.
steps:
  - task: CocoaPods@0
    inputs:
      projectDirectory: 'ios'
  - task: InstallAppleCertificate@2
    inputs:
      # This is what breaks
      certSecureFile: '$(p12FileName)'
      certPwd: '$(p12Password)'
      keychain: 'temp'
      deleteCert: true
```
The "Authorize resources" button seems to work. But does not fix the issue. The resources have also already been given access to all pipelines anyway.
![image](https://user-images.githubusercontent.com/810327/104327955-9e035b80-54eb-11eb-8461-d541f7090555.png)

Moving the `variables` to the root level will cause this to work. Proving the bug.
But they can't be at the root level because we need to differentiate between ACC and PROD. Let alone that the iOS and Android steps (templates) might use the same variable so even they need to be different. The root scope is not an option, and shouldn't be in scenario's like this.

Thanks for helping and looking into this!

**Comment by egor-bryzgalov** [comment]
@Guuz I see that you're using variable groups but as per the article mentioned above `Variable groups are themselves a resource subject to authorization, so their data is likewise not available when checking resource authorization.` I guess the only way here might be to pass secure files as template parameters somehow. [Here you can find more information about template parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters).

**Comment by Guuz** [comment]
Using a template paramater sounds like it could work. I'll try it out and post the results here. Thanks!

Thought:
It would still feel "broken" though. Since using variables works only at the root level, and not lower. But this is the intended usage of variables.
The paramaters sound like a viable workaround.

**Comment by Guuz** [comment]
@egor-bryzgalov i tried to use the template parameters combined with variables. But this resulted in the same error.

I ended up using the parameters and hardcoding the required arguments for them, instead of using variables. since the secure files are only a name reference, this is acceptable. the passwords (which should be secure) do work via variables and then passing them on as parameters.

i hope it makes any sense what i'm saying ^_^ it's kinda hard to explain. the take-away is that i still dont see a way to use devops variables and templates. to re-use build steps and inject them with variable inputs configured outside the pipelines.

**Comment by Zanchee** [comment]
Correct, you can't use a variable explicitly for a certificate, but by creating a template that takes in parameters, and then just creating N jobs each passing in your required parameters to the template, you are essentially doing the same thing as a matrix, but now on each template call you can define the certificate you wish to use.

To be honest. We publish many apps from one code source, and this covers that solution perfectly. I'm not really sure what benefit being able to use a variable would be. I can't think of a use case. Even if you could, it's either a single update to a yml or a single update to the Azure GUI

This has worked perfectly for us now. I think I was simply just too focused on using a matrix that I forgot about the other tools in the shed.

**Comment by DanielSchafer87** [comment]
I managed to solve the same issue:
![image](https://user-images.githubusercontent.com/23694181/106377511-23b94f00-63a6-11eb-8a91-b99fd5e0fc30.png)

by defining the variables like this:
```yaml
variables:
  - group: CodeSign
  - name : BuildConfiguration
    value: 'Release'
  - name: SetupBuildConfiguration
    value: 'Release'

stages:
- stage: Stage1
  
  jobs:
  - job: LLT
    timeoutInMinutes: 0
    steps:
    - checkout: self
      submodules: true
      persistCredentials: true
```

it's a desktop application building pipeline but I think the issue was the same.

**Comment by egor-bryzgalov** [comment]
Closing the issue since the workaround has been found.

**Comment by egor-bryzgalov** [comment]
Please feel free to open a ticket at https://developercommunity.visualstudio.com/ if you'd like to suggest an enhancement or found any issue related to Azure DevOps.

**Comment by Jerome-Liger** [comment]
Hi,
The "workaround" is not acceptable (and adaptable) for me... 2 days I'm trying to solve this... without success.

I'm building 18 applications (x2 : Android & iOS = 36 unique apps), based on the same unique Xamarin.Forms code-base.
And each unique application has his unique .Keystore(android) or .mobileprovision(iOS)

So I have only 1 pipeline for Android and 1 pipeline for iOS, and in these 2 pipelines I'm looping foreach application I choose to build (as build parameter) to copy the specific files, to get the specific variablesGroup, to build the Xamarin.android, and to SIGN each of them with their own keystore... all is working fine, except that I'm unable to sign correctly with the good keystore (it takes always the "defaut-keystore") :-(

I've tried with different tasks (androidSignin / CmdLine / DownloadSecure / ...) but everytime it takes the SecureFile in the "pre-build step) and impossible to get/set the securefile in my "each" loop...

So I'm completely stuck, unable to get the corresponding keystore for each application.

Here's a part of YAML, if anybody can help, it would be great 👍 :

```
#Ask (as BuildParameter) the city/cities that need to be built
# !!!! Add new cities here (in values and in default) after having created the "city-specific-VariableGroup"
parameters:
  - name: CitiesToBuild
    type: object
    values:
      - CityA
      - CityB
      - CityC
      - CityD
      - CityE
    #By default -> build ALL the cities (if new comercea "master functional modification" for example)
    default:
      - CityA
      - CityB
      - CityC
      - CityD
      - CityE

#Do not trigger automatic CI !
trigger: none

#Our own Mac Agent
pool:
  name: Respawnsive
  demands:
  - MSBuild 
  - Xamarin.Android
  - JDK

#Get the variables from _Common_VariablesGroup and other locals variables.
variables:
- group: _Common_VariablesGroup
- name: buildConfiguration
  value: 'AppStore'
- name : outputDirectory
  value: '$(build.binariesDirectory)/$(buildConfiguration)'

#Define the build Name
name: $(Build.DefinitionName)_V$(VersionMajor).$(VersionCode)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
  #Run a new Job foreach selected city !
  - ${{ each city in parameters.CitiesToBuild }}:
    - job: 
      displayName: 'Build AppStore Android for ${{ city }}'

      #Clean the workspace between each city
      workspace:
        clean: all

      #Get the variables group for the specific city
      variables:
      - group: ${{ city }}VariableGroup

      # ALL JOB STEPS
      steps:
        
      #Copy/Overrite the City specific files (images, json, etc.) to local source-code
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'Comercea/Cities/${{ city }}'
          Contents: '**'
          TargetFolder: 'Comercea/FormsKiosk'
          OverWrite: true
          retryCount: '3'

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.11.0'
        inputs:
          versionSpec: 5.11.0

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
          includeNuGetOrg: true
          verbosityRestore: Detailed

      - task: android-manifest-package-name@1
        displayName: 'AndroidManifest.xml Change packageName and appLabel'
        inputs:
          sourcePath: 'Comercea/FormsKiosk/FormsKiosk.Android/Properties/AndroidManifest.xml'
          packageName: '$(PackageId_Android)'
          appLabel: '$(ApplicationName)'
          printFile: true

      - task: android-manifest-version@1
        displayName: 'AndroidManifest.xml Change versionCode and versionName'
        inputs:
          sourcePath: 'Comercea/FormsKiosk/FormsKiosk.Android/Properties/AndroidManifest.xml'
          versionCodeOption: buildid
          versionCode: '$(VersionCode)'
          versionName: '$(VersionMajor).$(VersionCode)'
          printFile: true

      - task: XamarinAndroid@1
        displayName: 'Build Xamarin.Android project **/*Droid*.csproj'
        inputs:
          projectFile: '**/*Droid.csproj'
          outputDirectory: '$(outputDirectory)'
          configuration: '$(buildConfiguration)'
          msbuildVersionOption: latest
          msbuildArguments: '/verbosity:detailed'

      - task: DownloadSecureFile@1
        displayName: 'DownloadingKeyStore'
        name: 'MyKeystoretemp'
        inputs:
          secureFile: '$(Android_KeystoreFilename)'
          retryCount: 3

      - script: |
          echo '-------'
          echo 'Android_KeystoreFilename:'
          echo '$(Android_KeystoreFilename)'
          echo '-------'
          echo 'MyKeystoretemp.secureFilePath:'
          echo '$(MyKeystoretemp.secureFilePath)'
          echo '-------'

      - task: CmdLine@2
        displayName: 'Signing and aligning AAB with commandline'
        continueOnError: true
        inputs:
          script: 'jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $(MyKeystoretemp.secureFilePath) -storepass $(Android_KeystorePwd) -keypass $(Android_KeyPwd) $(outputDirectory)/*.aab $(Android_KeystoreAlias)'

      - task: AndroidSigning@2
        displayName: Sign and Align AAB
        enabled: false
        inputs:
          apkFiles: '$(build.binariesdirectory)/$(BuildConfiguration)/*.aab'
          jarsignerKeystoreFile: '$(Android_KeystoreFilename)'
          jarsignerKeystorePassword: $(Android_KeystorePwd)
          jarsignerKeystoreAlias: $(Android_KeystoreAlias)
          jarsignerKeyPassword: $(Android_KeyPwd)
          jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact ${{ city }}'
        inputs:
          PathtoPublish: '$(outputDirectory)'
          ArtifactName: '${{ city }}'
          publishLocation: 'Container'

```
