### ISSUE TITLE
AzurePowerShell@4 ignores actual exit code

### ISSUE THREAD

**Issue by M0ns1gn0r** [microsoft/azure-pipelines-tasks#13819]
## Required Information

*Type*: Bug

**Enter Task Name**: AzurePowerShell

## Environment
- Server - Azure Pipelines
- Agent - Hosted (ubuntu-latest)

## Issue Description

**My task:**
```
      - task: AzurePowerShell@4
        name: TestOfFailure
        inputs:
          azureSubscription: xxxxxxxx
          azurePowerShellVersion: latestVersion
          scriptType: inlineScript
          inline: |
            exit 666
```

**Actual:**
Logs contain `2020-11-02T12:14:58.7716488Z ##[error]PowerShell exited with code '1'.`
DevOps Pipeline UI shows *PowerShell exited with code '1'*.

**Expected:**
 Both logs and UI shows the code 666.
