### ISSUE TITLE
Cache@2 renames a folder to PaxHeader after populating the Yarn cache

### ISSUE THREAD

**Issue by srmagura** [microsoft/azure-pipelines-tasks#13847]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Cache  

## Environment
- Server: Azure Pipelines, Account: CareServices, Project: CDS 2 App, Pipeline: CDS 2 Build, Build Number: 789 (among others)
- Agent: Hosted, Pool: Azure Pipelines, Image: windows-latest

## Issue Description
Here's the part of my YAML that restores the Yarn cache and installs Yarn packages. This is using Yarn v1.
```
- task: Cache@2
  displayName: Restore Yarn cache
  inputs:
    key: 'yarn | "$(Agent.OS)" | **/yarn.lock,!**/node_modules/**'
    path: $(YARN_CACHE_FOLDER)

- pwsh: yarn install --cwd Source --non-interactive --frozen-lockfile
  displayName: yarn install

# For debugging
- pwsh: ls -Recurse Source\node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors
```

* When there is a cache miss, the TypeScript build succeeds, like it does on my local PC.
* When there is a cache hit, the TypeScript build fails because the folder `Source\node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors\SamplingScoreGenerators` has the name `PaxHeader` instead. This has happened every time there is a cache hit. From my Googling, it looks like PaxHeader has something to do with the tar format.

### Task logs

[logs_789.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5495261/logs_789.zip)

### Error logs

Here's the output from the `pwsh` step in the YAML above. This is when there is a cache hit.

```
    Directory: D:\a\1\s\Source\node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           11/5/2020  3:04 PM                PaxHeader
d----           11/5/2020  3:04 PM                SamplingScoreGenerators
-a---           11/4/2020 11:42 PM           1703 HashCodeScoreGenerator.js
-a---           11/4/2020 11:42 PM           2050 HashCodeScoreGenerator.js.map
-a---           11/4/2020 11:42 PM           1994 Sample.js
-a---           11/4/2020 11:42 PM           2330 Sample.js.map
-a---           11/4/2020 11:42 PM           1565 SamplingScoreGenerator.js
-a---           11/4/2020 11:42 PM           1903 SamplingScoreGenerator.js.map

    Directory: 
D:\a\1\s\Source\node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors\PaxHeader

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           11/4/2020 11:42 PM            279 HashCodeScoreGenerator.js
-a---           11/4/2020 11:42 PM            283 HashCodeScoreGenerator.js.map
-a---           11/4/2020 11:42 PM            279 SamplingScoreGenerator.js
-a---           11/4/2020 11:42 PM            283 SamplingScoreGenerator.js.map
```

**Comment by gaziqbal** [comment]
I am encountering the same and have a temporary workaround to delete this package after restoring the cache to force a redownload from npm.

```
  # Temporary workaround for https://github.com/microsoft/azure-pipelines-tasks/issues/13847
  - task: DeleteFiles@1
    inputs:
      sourceFolder: $(YARN_CACHE_FOLDER)
      contents: |
        **/*@microsoft-applicationinsights-channel-js*
    displayName: Prepare App Cache


```
