### ISSUE TITLE
Kubernetes task removes quotes

### ISSUE THREAD

**Issue by jasper-d** [microsoft/azure-pipelines-tasks#13919]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: Azure Devops Server 2020 Dev18.M170.6
    

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 18.04.1-Ubuntu, Agent version 2.175.2

## Issue Description
Running a Kubernetes@1 taks, quotes are removed from the provided argument. For instance, having the following task:

```
    - task: Kubernetes@1
      displayName: Patch 
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: ${{ parameters.k8sCredentials }}
        command: patch
        arguments: daemonset node-exporter -n foobar --patch="$(cat patch.json)"
        secretType: generic
```
Is translated to the following command (from the build log):
```
/usr/local/bin/kubectl patch daemonset node-exporter -n foobar --patch=$(cat patch.json) -o json
```

Kubectl then fails, because the patch must be enclosed in double quotes.

## Expected:
Tasks shouldn't tamper with inputs.
