### ISSUE TITLE
FileTransform task doesn't work with absolute paths for -transform parameter

### ISSUE THREAD

**Issue by kingjan1999** [microsoft/azure-pipelines-tasks#13948]
##  Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  FileTransform

## Environment
- Server: Azure Pipelines, [example build / project](https://janbeckmann.visualstudio.com/Test%203/_build/results?buildId=24&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9)
    
- Agent - Private: Windows 10, Agent v2.175.2
   
## Issue Description

Passing an absolute path as `-transform` parameter into the FileTransform task (both V1/V2) for XML/XDT transformation doesn't work, the task fails with `Unable to apply transformation for the given package`. This works fine when using a relative path instead.

The [reproduction project](https://janbeckmann.visualstudio.com/_git/Test%203) includes two files, `Web.config` and `Web.release.config`. The following task definition:

```yaml
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    enableXmlTransform: true
    xmlTransformationRules: '-transform Web.Release.config -xml Web.config'
    fileType: 'xml'
```

works fine, transforming the `Web.config` using the `Web.Release.Config`. This definition however:
```yaml
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    enableXmlTransform: true
    xmlTransformationRules: '-transform $(System.DefaultWorkingDirectory)\Web.Release.config -xml Web.config'
    fileType: 'xml'
```
doesn't work but instead fails with `Unable to apply transformation for the given package`. I would have expected both configurations to give identical results (the file is transformed).

### Task logs

[Raw log](https://janbeckmann.visualstudio.com/0fd64480-b471-43e0-b1f9-92e8f85b2e36/_apis/build/builds/24/logs/7) for the job

## Troubleshooting

N/A

### Error logs

N/A
