### ISSUE TITLE
[Improvement] PipelineCaching: provide a mechanism to upload and download cache at specific times

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/azure-pipelines-tasks#13949]
*Type*: Feature, Improvement

**Enter Task Name**:  Cache@2, Azure Pipelines

## Issue Description

My job processes many build variations, but bc of the software I'm using the cache is located in the same folder for each platform I'm building to. I'd like to have a mechanism to trigger when the post build cache event uploads the cache.

for example:

```
- ${{ each target in parameters.targets }}:
  - ${{ each validTarget in parameters.validTargets }}:
    - ${{ if eq(target, validTarget) }}:
      - task: CacheDownload@0
        inputs:
          key: '"cache" | "$(Agent.OS)" | "${{ target }}"'
          path: 'cacheFolder'
      - template: steps/run-tests.yml
        parameters:
          target: ${{ target }}
      - template: steps/build.yml
        parameters:
          target: ${{ target }}
      - task: CacheUpload@0
        inputs:
          key: '"cache" | "$(Agent.OS)" | "${{ target }}"'
          path: 'cacheFolder'
```
