### ISSUE TITLE
Unexpected behaviour in finding Dockerfile

### ISSUE THREAD

**Issue by rcomanne** [microsoft/azure-pipelines-tasks#13954]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question or a bug

**Enter Task Name**: 

- Docker@2

## Environment

Agent on custom build agents, running version 2.175.2 on Ubuntu 16.04  

## Issue Description

When providing the Dockerfile argument on a docker build task, it uses an incorrect pattern when including the `$(System.DefaultWorkingDirectory)` variable, causing the build to not find a pattern at all and not searching for the Dockerfile.   
The task looked like this;
```yaml
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '$(System.DefaultWorkingDirectory)/**/Dockerfile'
```

Also, when using the default pattern, it will find stuff in the Docker tmp directory, so I have to change this pattern I guess?

### Task logs

[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5582747/logs.zip)

### Error logs

##[debug]Dockerfile=/appl/kwxbuild/agent/linux-agent-0004-1/_work/147/s
##[debug]No pattern found in Docker filepath parameter
