### ISSUE TITLE
Helm Task in ADO Pipeline

### ISSUE THREAD

**Issue by StephanZaat** [microsoft/azure-pipelines-tasks#13979]
## Required Information

When I use the Helm task to deploy a Helm chart to AKS I receive an error message.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Helm Deploy

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

```
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '$(AKS_SC)'
    namespace: '$(k8sNamespace)'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(Build.ArtifactStagingDirectory)/dso/Helm'
```
Running this pipeline task gives the following Helm command:
`/usr/local/bin/helm upgrade --namespace default --install --wait 20201126.10 /home/vsts/work/1/a/dso/Helm`

And results in the following error:
`Error: unable to build kubernetes objects from release manifest: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 2, error found in #10 byte of ...|nstance":20201126.1,|..., bigger context ...|etadata":{"labels":{"app.kubernetes.io/instance":20201126.1,"app.kubernetes.io/managed-by":"Helm","a|...
`

The issue seems to be that the automatically generated Release Name containing a "period" is not allowed in the default Helm templates. I get the same issue when running this on my command line.

---

On a side note, In the documentation the Parameter "chartPath" is not present but it is used in the example. This should be added here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#upgrade-command
