### ISSUE TITLE
Passing in an Array for OverrideParameters, in AzureResourceManagerTemplateDeployment task

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/azure-pipelines-tasks#14021]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment

## Environment
- Agent - Hosted    
    - If using Hosted agent, provide agent queue name: Hosted Agent / Azure Pipelines

## Issue Description
The error is thrown when I'm trying to deploy an ARM template which requires an array to be passed in as a parameter. I'm picking the value of the parameter from a Pipeline variable (which is clearly stored as a string). Whilst the string is a JSON-valid array, it seems that the task treats the string as a string, rather than an array.

```
Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.
```

### Task logs

2020-12-03T12:56:41.3045178Z ##[section]Starting: Deploy ARM template
2020-12-03T12:56:41.3054011Z ==============================================================================
2020-12-03T12:56:41.3054317Z Task         : ARM template deployment
2020-12-03T12:56:41.3054628Z Description  : Deploy an Azure Resource Manager (ARM) template to all the deployment scopes
2020-12-03T12:56:41.3054893Z Version      : 3.179.0
2020-12-03T12:56:41.3055099Z Author       : Microsoft Corporation
2020-12-03T12:56:41.3055420Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2020-12-03T12:56:41.3055789Z ==============================================================================
2020-12-03T12:56:42.4197390Z ARM Service Connection deployment scope - ManagementGroup
2020-12-03T12:56:42.4633886Z Creating deployment parameters.
2020-12-03T12:56:42.4639033Z The detected encoding for file '/home/vsts/work/1/s/infra/arm/azuredeploy.apim.json' is 'utf-8'
2020-12-03T12:56:42.4644567Z There was an error while overriding 'appSrvApiApps' parameter because of 'SyntaxError: Unexpected token r in JSON at position 4', make sure it follows JavaScript Object Notation (JSON)
2020-12-03T12:56:42.4645581Z Starting template validation.
2020-12-03T12:56:42.4645958Z Deployment name is test-build-1977
2020-12-03T12:56:42.5124767Z There were errors in your deployment. Error code: InvalidTemplate.
2020-12-03T12:56:42.5186282Z ##[error]Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.
2020-12-03T12:56:42.5205398Z ##[warning]Validation errors were found in the Azure Resource Manager template. This can potentially cause template deployment to fail. Task failed while creating or updating the template deployment.. Please follow https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax
2020-12-03T12:56:42.5207880Z Starting Deployment.
2020-12-03T12:56:42.5208751Z Deployment name is test-build-1977
2020-12-03T12:56:42.5919115Z There were errors in your deployment. Error code: InvalidTemplate.
2020-12-03T12:56:42.5925482Z ##[error]Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.
2020-12-03T12:56:42.5931442Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
2020-12-03T12:56:42.5933950Z ##[error]Task failed while creating or updating the template deployment.
2020-12-03T12:56:42.5977995Z ##[section]Finishing: Deploy ARM template

### Error logs

2020-12-03T12:56:42.5925482Z ##[error]Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.
2020-12-03T12:56:42.5931442Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
2020-12-03T12:56:42.5933950Z ##[error]Task failed while creating or updating the template deployment.

**Comment by bishal-pdMSFT** [comment]
@iamalexmang you should pass the override value as stringified JSON e.g. override value for a array parameter can be a string ` -arrayParam ["value 1", "value 2"]`

**Comment by iamalexmang** [comment]
That is specifically what I tried: pass in the stringified JSON returned from an ARM output, and that results in the task specifying that rather than passing an array in, I specified a string.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bishal-pdMSFT** [comment]
Could you please attach yamp/screenshot of your pipeline?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tiwarishub** [comment]
Hi @iamalexmang , If you are still facing this issue then please share the yaml/Screenshot of your pipeline.

**Comment by iamalexmang** [comment]
My apologies. Will send you a set of YAMLs in a moment

**Comment by tiwarishub** [comment]
Hi @iamalexmang , If you are still facing this issue then please share the yaml/Screenshot of your pipeline.

**Comment by ashwinsangem** [comment]
Hi @iamalexmang, this issue has been stale for a while. Can you please share the YAML/Screenshot of your pipeline?

**Comment by iamalexmang** [comment]
My apologies for the late reply to this thread.
In the meantime I prepared a complete set of templates and YAMLs to elaborate the issue. By doing so I came up with several ideas and eventually managed to get it to work - not sure if this is of my doing or the task got updated under the hood - in which case, my apologies for the arrogance.

TL/DR: **in this scenario I was trying to get the ARM template output from one job and have it used in another job instead.**
Using arrays in `overrideParameters` when the array value is sourced from a pipeline, stage, or job variable/parameter is easy enough and works with not tweaks, so I'm not going to be referring to that use case.

For future references and anyone else trying to get this done, below is a sample scenario:
- Azure Pipelines has a job in which it deploys an ARM template. The template returns an output
- The output is persisted and references in another job
- The next job references the output of the ARM template and uses it for another ARM deployment

The issue I was facing is that when I was persisting the ARM output, it was saving the result as a Hash Table rather than a String which resulted in Azure Pipelines not being able to store the result. The solution was to convert the ARM output as a string first by using the ConvertTo-Json cmdlet (as you probably already realized, the output variable value was a Hash Table, not a String).

Here's are ARM templates used:
### ARM template returing a JSON array as output 
``` JSON
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [],
    "outputs": {
        "arrayoutput": {
            "type": "array",
            "value": [
                { 
                    "name": "firstentry" 
                }, 
                { 
                    "name": "secondentry" 
                }, 
                { 
                    "name": "thirdentry" 
                }
            ]
        }
    }
}
```

### ARM template receiving the array as a parameter
``` JSON
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "arrayprop": {
            "type": "array"
        }
    },
    "functions": [],
    "variables": {},
    "resources": [
        {
            "name": "[concat('stgarmtempdepl', copyIndex())]",
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2019-06-01",
            "tags": {
                "displayName": "[concat('stgarmtempdepl', copyIndex())]"
            },
            "location": "[resourceGroup().location]",
            "kind": "StorageV2",
            "sku": {
                "name": "Standard_LRS",
                "tier": "Standard"
            },
            "copy": {
                "name": "stgcopy",
                "count": "[length(parameters('arrayprop'))]"
            }
        }
    ],
    "outputs": {}
}
```

### Azure Pipelines definition using ARM output across jobs
``` YAML
parameters:
- name: subscriptionId
  displayName: Subscription ID
  type: string
- name: armConnection
  displayName: ARM connection
  type: string

trigger:
  branches:
    exclude:
      - '*'

stages:
- stage: PrepareInfra
  jobs:
  - job: SimAzureDepl
    displayName: 'Simulate an Azure deployment' 
    pool:
      vmImage: ubuntu-latest   
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ parameters.armConnection }}
        subscriptionId: '${{ parameters.subscriptionId }}'
        resourceGroupName: 'DELETEME-rg-testarraysinazdevops-we-dev'
        action: 'Create Or Update Resource Group'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploywithoutput.json'
        deploymentMode: 'Incremental'
        deploymentName: 'azure-pipelines-build-outputs-$(Build.BuildId)'
        deploymentOutputs: 'armOutputs'

    - task: PowerShell@2
      name: armOutputs
      displayName: 'Configure ARM outputs'
      inputs:
        targetType: 'inline'
        script: |
          $var = ConvertFrom-Json '$(armOutputs)'          
          $output = ConvertTo-Json $var.arrayoutput.value -Compress -Depth 4 
          echo $output
          Write-Host "##vso[task.setvariable variable=arrayoutput;isOutput=true;]$output"

  - job: DeployAzureInfrastructure
    displayName: 'Deploy Azure resources'     
    dependsOn: SimAzureDepl
    pool:
      vmImage: ubuntu-latest 
    variables:
      arrayoutput: $[ dependencies.SimAzureDepl.outputs['armOutputs.arrayoutput'] ]  
    steps:
    - task: PowerShell@2
      displayName: 'Output stringified array'
      inputs:
        targetType: 'inline'
        script: |
          echo '$(arrayoutput)'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ parameters.armConnection }}
        subscriptionId: '${{ parameters.subscriptionId }}'
        resourceGroupName: 'DELETEME-rg-testarraysinazdevops-we-dev'
        action: 'Create Or Update Resource Group'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        overrideParameters: '-arrayprop $(arrayoutput)'
        deploymentMode: 'Incremental'
        deploymentName: 'azure-pipelines-build-$(Build.BuildId)'
        deploymentOutputs: 'armOutputs'
```

That said, I will close the issue now.
