### ISSUE TITLE
Throw `Could not find the module path with given version`

### ISSUE THREAD

**Issue by lin404** [microsoft/azure-pipelines-tasks#14024]
## Note 

https://github.com/microsoft/azure-pipelines-tasks/blob/a1502bbe67561f5bec8402f32c997406f798a019/Tasks/AzurePowerShellV4/Utility.ps1#L42

## Required Information

**Type**: Bug?
**Task Name**:  AzurePowerShell@4  

## Environment

- Azure Pipelines 
- MSHosted Agent

## Issue Description

Pipeline using `AzurePowerShell@4`
```yaml
  - stage: testStage
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job: testJob
      steps:
      - task: AzurePowerShell@4
        displayName: UpdateSomething
        inputs:
          azureSubscription: $(AzureConnection)
          scriptType: inlineScript
          inline: |
            # update something
```
Throw the error:

```
Exception: /home/vsts/work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/5.176.3/Utility.ps1:42
Line |
  42 |  …             throw ("Could not find the module path with given version …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find the module path with given version.
```

## Troubleshooting

I found error occurred in [here](https://github.com/microsoft/azure-pipelines-tasks/blob/a1502bbe67561f5bec8402f32c997406f798a019/Tasks/AzurePowerShellV4/Utility.ps1#L42)

I had to explicit set **TargetAzurePs = ''** to avoid error:

```yaml
- task: AzurePowerShell@4
        displayName: Install PreReqs
        inputs:
          azureSubscription: $(AzureConnection)
          TargetAzurePs: ''
          scriptType: inlineScript
          inline: |
            # update something
```

**Comment by chshrikh** [comment]
this is by design. radio "Azure PowerShell Version" input is defaulted to "specify other version", this means one need mandatory provide input "Preferred Azure PowerShell Version".
Refer below sample in case latest az version need to be use

```yaml
 - task: AzurePowerShell@4
    displayName: 'Azure PowerShell script: FilePath'
    inputs:
      ConnectedServiceNameARM: <service connection name>
      TargetAzurePs: LatestVersion
```
