### ISSUE TITLE
SQL server database deploy is not logging verbose with inline sql

### ISSUE THREAD

**Issue by mwc360** [microsoft/azure-pipelines-tasks#14043]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SQL server database deploy

## Environment
- Server - Azure Pipelines

- Agent - Azure Hosted Agent

## Issue Description

Adding verbose does not result in any logged outputs via print messages. This was also a bug in the Azure SQL Database deploy task and was resolved via the below PR. This same change needs to be implemented in this task.

https://github.com/microsoft/azure-pipelines-tasks/pull/9741/commits/0b12366f7b14b8e27e51bfd4c3f08a70dd147848

**Comment by AmrutaKawade** [comment]
@mwc360 are you passing `-verbose` option in additional arguments?


![image](https://user-images.githubusercontent.com/65217380/103283408-7e096d80-49fe-11eb-8543-09a523414d10.png)

**Comment by 20shivangi** [comment]
@mwc360 Have you tried the above approach ?

**Comment by AmrutaKawade** [comment]
I am able to repro this issue.
Repro steps

```
steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: 'Deploy using : sqlInline'
  inputs:
    TaskType: sqlInline
    InlineSql: 'PRINT N''abc'''
    DatabaseName: master
    AdditionalArgumentsSql: '-Verbose'
```

Required fix similar to this https://github.com/microsoft/azure-pipelines-tasks/pull/9741

in this method https://github.com/microsoft/azure-pipelines-tasks/blob/b908bffea681a03d1b8925e299d2a2b794bc035e/Tasks/SqlDacpacDeploymentOnMachineGroupV0/Main.ps1#L176

https://github.com/microsoft/azure-pipelines-extensions/blob/5dd1dba15c474153c8b8d971c77959112f0b12a3/TaskModules/powershell/TaskModuleSqlUtility/SqlQueryOnTargetMachines.ps1#L91
