### ISSUE TITLE
AzureFunction@1 ignores "key" from a secret variable in a variable group.

### ISSUE THREAD

**Issue by patriziobrunoms** [microsoft/azure-pipelines-tasks#14067]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunction

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionV1

## Environment
- Server - Azure Pipelines, microsoft, OSGCXE, csd.build.pipeline/29650231
    
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: agentless

## Issue Description
I put the key for the AzureFunction in a keyvault and linked it to a variable group. I checked the variable using a bash task and verified that is properly set, but the task AzureFunction@1 doesn't use it, leading to a 401 error when calling the function. I tried putting the value of the key into a pipeline variable that I set when starting the build and it works correctly. It looks like the task can't take a key from a secret variable coming from a variable group.

### Task logs

Task         : Telemetry Build.Job.SourceEnlist Start.Reached
Description  : Invoke an Azure Function
Version      : 1.0.12
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function

POST https://XXX.XX/XXX/api/emit-insights?code=&
Request body: {
  "Namespace": "Build.Job.SourceEnlist",
  "Event": "Start.Reached",
  "LinkContextNode": "",
  "WorkflowId": "XXXX-XXX-XXXXX-XXXX-XXXXXX",
  "ConsumesWorkflowId": "test-123",
  "ParentWorkflowId": "",
  "Input": {},
  "Context": {}
}
				Response Code: 0
				Response: An error was encountered while processing request. Exception: 
Exception Message: The remote server returned an error: (401) Unauthorized. (type WebException)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by Ganeshrockz** [comment]
@patriziobrunoms I tried the similar scenario and looks like the task reads secrets from variable groups

```yaml
variables:
- group: sample

stages:
- stage: Stage1
  jobs:
  - job:
    pool: 'Server'
    steps:
    - task: AzureFunction@1
      inputs:
        function: $(url)
        key: $(key)
        method: 'POST'
        body: |
          {
          "name":"foo"
          }
        waitForCompletion: 'false'
```

Both the variables `url` and `key` are present inside a variable group. `key` is a secret variable. This triggered the azure function in the expected manner without throwing a 401.

**Comment by patriziobrunoms** [comment]
@Ganeshrockz Thanks for testing this out. I understand that you weren't able to reproduce my problem, which for my pipeline still persists. Is your key stored in the variable group or is it a reference to a keyvault. In my case the secret is stored in a keyvault.

To make the task work I had to use a work-around, which reduces the security of my pipeline. I added a task to a job running on an agent, the powershell task takes as input the secret and sets a new non-secret variable. This fixed the problem for me, but it's less than ideal, not just for the security, but also for the dependency of the task on a non-agentless job.

**Comment by Ganeshrockz** [comment]
@patriziobrunoms  I didn't have them in a keyvault. I saw that you were able to print the value of the secret from the keyvault inside a script. This proves that the variable group gets the value from the Keyvault. If the variable is set properly in the VG then it should be accessible by the task. I can try reproducing this by placing it in a vault.

**Comment by patriziobrunoms** [comment]
@Ganeshrockz is there any way to make the AzureFunction task log a debug message with the key?

**Comment by Ganeshrockz** [comment]
We generally make use of the `System.Debug` variable by setting its value to `True`

**Comment by patriziobrunoms** [comment]
@Ganeshrockz it is set, and there's a log message with the full URL of the function, but the key querystring-parameter is empty. Is it empty because debug messages don't include secret variables? Or does it mean the variable is not received by the task?

**Comment by Ganeshrockz** [comment]
@patriziobrunoms We generally mask secrets when they get printed as logs. One way to test whether we get the value from the keyvault is to do a equality check in a separate task.

**Comment by patriziobrunoms** [comment]
@Ganeshrockz I have a separate task in a separate job that does equality check and the test returns true. The value of the secret from the keyvault is the expected one

**Comment by patriziobrunoms** [comment]
Hi @Ganeshrockz, Happy New Year! Did you get the chance to test the secret-on-keyvault setup?

**Comment by Ganeshrockz** [comment]
Hi @patriziobrunoms. Sorry for the delay from my end. I tried the following case
1. Created a secret in my keyvault in azure.
2. Referenced the same in a variable group in azure devops
3. Linked the variable group to the release pipeline
4. Referenced the variable in my Invoke Azure function task function key input.

My azure function got invoked and i was able to see the expected logs. Can you also try a similar scenario in your personal account and let me know the results?

**Comment by Ganeshrockz** [comment]
Closing it as stale issue since the author didn't get back

**Comment by tokleine** [comment]
I had a similar issue and managed to get it to work like this:

```
jobs:
- job: fetchKey
  displayName: Fetch Function Key and write to variable
  dependsOn: ${{ parameters.dependency }}
  variables:
    secretName: ${{ parameters.functionAppKeySecretName }}
  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: 'Fetch Function Key from KeyVault'
    name: writeFunctionKey
    inputs:
      azureSubscription: ${{ parameters.armConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: | 
        Write-Host 'Fetching Default Key from Key Vault ...'
        $defaultKey = az keyvault secret show --vault-name ${{ parameters.keyVault }} --name ${{ parameters.functionAppKeySecretName }} --query value -o tsv
        Write-Host 'Wirting Default Key to variable ...'
        Write-Host "##vso[task.setvariable variable=functionKey;issecret=true;isOutput=true;]$defaultKey"
        Write-Host 'Successfully wrote Default Key to variable.'
 
- job: testFunctionApp
  displayName: Test my Function App
  dependsOn: fetchKey
  pool: server
  variables:
    defaultKey: $[ dependencies.fetchKey.outputs['writeFunctionKey.functionKey'] ]
  steps:
  - task: AzureFunction@1
    displayName: Call Azure Function App
    inputs:
      function: ${{ parameters.functionAppURL }}
      key: $(defaultKey)
      method: 'POST'
      headers: '{"Content-Type":"application/json"}'
      body: ' '
      waitForCompletion: 'false'
      successCriteria: 
 
```

Hope it helps someone :-)
