### ISSUE TITLE
Consider adding a meta-task that contains multiple sub-tasks

### ISSUE THREAD

**Issue by BrianVallelunga** [microsoft/azure-pipelines-tasks#14062]
**Question, Bug, or Feature?**  
*Type*: Feature

## Issue Description

Within a deployment job of a YAML pipeline, I often want to skip several tasks, in an effort to avoid re-deploying code that hasn't changed. Right now I'm using the `condition` field on most tasks for this. It would be more helpful to have a meta-task that I could assign a `condition` to that did nothing more but run its other tasks conditionally. For example, I want to treat the deployment and swapping of a slot atomically and have both be done based on one condition:

```yaml
- task: MetaTask
  displayName: 'Deploy API'
  condition: eq(true, variables['DeployAPI'])
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy API App'
    // other properties
  - task: AzureAppServiceManage@0
    displayName: 'Swap API App Slot'
    // other properties
```

This is especially useful when tasks such as `AzureAppServiceManage` don't support the `condition` property, potentially resulting in the wrong slot being deployed (see: https://github.com/microsoft/azure-pipelines-tasks/issues/14061). In theory, jobs could be used for this purpose, but those aren't quite right either since I want this capability within a single deployment job, in a specific order with everything else.
