### ISSUE TITLE
Xcode builds failing with message 'error: <pod> does not support provisioning profiles

### ISSUE THREAD

**Issue by Carolhaha** [microsoft/azure-pipelines-tasks#14092]
**Question, Bug, or Feature?**  
*Type*: Bug or Question

**Enter Task Name**: Xcode@5 

## Environment
    
- Azure Pipelines
    
- Agent : 
    -  MacOS, xcode 8.0

## Issue Description

IOS Object-C app, want to build a pipeline for it, but it failing with error code 65.
   -  error: <podname> does not support provisioning profiles. <podname> does not support provisioning profiles but provisioning profile <distrprofile> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target '<podname>')
   
- Changing provisioning sign mode to "Automatic" will raise error in release pipeline.
![relseaseerror1](https://user-images.githubusercontent.com/32686035/102404556-e182ac80-3fb5-11eb-9ddf-a6c74fc5f04b.PNG)
and 
ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle <Bundle Name>[Payload/Name.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. 

- So I keep use "Manual" sign mode.
With the solutions that others gave https://github.com/microsoft/azure-pipelines-tasks/issues/9984, I tried to downgrade the pods version
I tried https://github.com/microsoft/azure-pipelines-tasks/issues/9984#issuecomment-478647641
    ```
    echo "uninstalling all cocoapods versions"
    sudo gem uninstall cocoapods -ax
    echo "installing cocoapods version 1.5.3"
    sudo gem install cocoapods -v 1.5.3
    ```
and https://github.com/microsoft/azure-pipelines-tasks/issues/9984#issuecomment-483968562

![Capture1](https://user-images.githubusercontent.com/32686035/102406069-0841e280-3fb8-11eb-9219-b47b25a21804.PNG)
The build will stuck in the uninstall the old version step without moving on
![Capture2](https://user-images.githubusercontent.com/32686035/102406102-17289500-3fb8-11eb-9f4c-de06aacf8bab.PNG)

**Comment by alexander-smolyakov** [comment]
Hi, @Carolhaha! Could you please re-run the pipeline with the “[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)” option enabled and share the following information:
- YAML file of your pipeline
- Pipeline logs with system diagnostics information

Thanks!

**Comment by Carolhaha** [comment]
@alexander-smolyakov , Yes, here is the Yaml and the Pipeline log which has the downgrade task

YAML:
```
pool:
  name: OS X
  demands: xcode

#Your build pipeline references a secret variable named ‘P12password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.signingIdentity’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘TestConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘TestSDK’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.xcWorkspacePath’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.scheme’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.xcodeVersion’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.xcWorkspacePath’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.scheme’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.xcodeVersion’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.signingIdentity’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.provisioningProfileUuid’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:

- bash: |
   echo "uninstalling all cocoapods versions"
   sudo gem uninstall cocoapods -ax
   echo "installing cocoapods version pre"
   sudo gem install cocoapods --pre 
   
  noProfile: false
  noRc: false
  displayName: 'CocoaPods downgrade copy'

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'e3f43287-43ef-46cc-b797-4eed109287b5'
    certPwd: '$(P12password)'
    signingIdentity: '$(Parameters.signingIdentity)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: '554f0271-8551-4659-82db-24cc50129a86'

- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    xcWorkspacePath: '$(Parameters.xcWorkspacePath)'
    scheme: '$(Parameters.scheme)'
    xcodeVersion: '$(Parameters.xcodeVersion)'
    packageApp: true
    signingOption: manual
    signingIdentity: '$(Parameters.signingIdentity)'
    provisioningProfileUuid: '$(Parameters.provisioningProfileUuid)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

```

And here is the pipeline log:
[log17.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5711572/log17.txt)
