### ISSUE TITLE
PublisPipelineArtifact@1 badly documented ?

### ISSUE THREAD

**Issue by gillg** [microsoft/azure-pipelines-tasks#14090]
## Required Information

**Question / Bug**  

Hi,

While I was trying to publish an artifact with 

```yaml
- task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
        artifactName: 'NuGet'
```

I got an error "path not found"...

But if I add `archiveFilePatterns` it works. Is it a lack of documentation or a side effect of something ?

```yaml
- task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/'
        archiveFilePatterns: '**/*.nupkg'
        artifactName: 'NuGet'
```

## Environment
- Server - Azure Pipelines
