### ISSUE TITLE
Helm deploy task fails with Environment in YAML Release Pipeline 

### ISSUE THREAD

**Issue by raswinraaj** [microsoft/azure-pipelines-tasks#14119]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

HelmDeploy@0 tasks fails to authenticate the cluster when using the environment in yaml release pipeline

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  
HelmDeploy@0
list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    Account: waynefs 
    Project: NextGenMedia
    Build Definition Id: 260  

- Agent - Hosted
    
     agent queue name: ubuntu-20.04    

## Issue Description

HelmDeploy@0 tasks fails to authenticate the cluster when using the environment in yaml release pipeline
Getting the below error: 
[error]Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused. I have attached my service connection, resource and environment configuration screenshots as well
Here is my pipeline 
`- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: Dev.default
    pool: 
      vmImage: 'Ubuntu 20.04'
    strategy: 
      runOnce:
        deploy:
          steps: 
          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.2.4'
              installKubectl: true

          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:                            
              command: upgrade
              chartType: filepath              
              chartPath: $(Pipeline.Workspace)/charts/myservice-2.0.0.tgz
              releaseName: apple
              install: true
              waitForExecution: true                  
              connectionType: None`

### Task logs

[logs_83542.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5727952/logs_83542.zip)
![env1](https://user-images.githubusercontent.com/50330414/102852760-f42d3380-4444-11eb-8cde-e2e3ce9b8b2b.jpg)
![resource](https://user-images.githubusercontent.com/50330414/102852763-f55e6080-4444-11eb-9210-d635ad1354bf.jpg)
![svcconnection](https://user-images.githubusercontent.com/50330414/102852764-f55e6080-4444-11eb-9e89-2e37e552cfc0.jpg)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[error]Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused

**Comment by raswinraaj** [comment]
I have event tried changing the service connection of type kubeconfig and manually updating it as well. I get the same issue even after trying that.

**Comment by shigupt202** [comment]
@raswinraaj Could you please validate the server url in Kuubeconfig that you are using? It should have been a public endpoint, but from the error logs, looks like it is not: `http://localhost:8080/version?timeout=32s`

**Comment by shigupt202** [comment]
Closing stale issue. Feel free to reopen it in case you need more clarity.

**Comment by Shaked** [comment]
I am experiencing a similar problem. 

I have defined the following YAML: 

```
- stage: Deploy
  jobs:
  - deployment: stage_v2
    displayName: stage-v2
    environment: 'aksstage.devops'
    dependsOn: 
    pool: 
      name: $(vmName)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
- task: HelmInstaller@0
            displayName: 'Install Helm $(helmVersion)'
            inputs:
              helmVersion: '$(helmVersion)'
              checkLatestKubectl: true
          - task: Bash@3
            displayName: 'Bash Script'
            inputs:
              targetType: filePath
              filePath: '$(appDir)/prepare.sh'
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              namespace: 'devops'
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'csi-secrets-store-provider-azure/csi-secrets-store-provider-azure'
              releaseName: 'csi-secrets-store-provider-azure'
              valueFile: '$(appDir)/values.yaml'
```

While `aksstage` is a Kubernetes provider with a `devops` namespace as the resource. 

However, when I run it, it keeps failing with the following message: 

> Error: UPGRADE FAILED: could not get information about the resource: customresourcedefinitions.apiextensions.k8s.io "secretproviderclasses.secrets-store.csi.x-k8s.io" is forbidden: User "system:serviceaccount:devops:***" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

Only when I add the following to the `HelmDeploy` task it works: 

```
connectionType: 'Azure Resource Manager'
azureSubscription: 'Microsoft Azure Sponsorship (..)'
azureResourceGroup: 'stage-general'
kubernetesCluster: '...'
```

and while it does deploy, the environment resource stays empty: 

<img width="792" alt="Environments - Pipelines 2021-03-04 18-00-07" src="https://user-images.githubusercontent.com/960015/109991987-7ecac280-7d13-11eb-9671-603e60fce53e.png">

So I assume that the same problem occurs because of permission issue. 

Having said that, the `environment: dev` with the `default` namespace does work as expected: 

<img width="371" alt="Environments - Pipelines 2021-03-04 18-01-14" src="https://user-images.githubusercontent.com/960015/109992118-a0c44500-7d13-11eb-9105-499d607c7855.png">

And the ServiceAccount that was created by Azure DevOps is indeed set to be a `cluster-admin`.

Any idea what might went wrong? 

Thanks
Shaked
