### ISSUE TITLE
AzureFunctionApp@1 doesn't seem to honor the zip file name for deploying to kudu

### ISSUE THREAD

**Issue by gabrielmccoll** [microsoft/azure-pipelines-tasks#14157]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/cloudkingdoms/SP-principal-creation/  All of them

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-2019

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
AzureFunctionApp@1

When I use this to deploy my function it always seems to use the build ID for the zip.
This means on the Azure End, I end up with a pile of extra space being taken up with older versions
I thought this would be because of what I had named the Zip file but I tried changing it to be the same name everytime with the expectation it would carry through as gmtest-dev.zip but it's not and still seems to use buildID or a date time. 

Not sure if I'm being dumb and there's something simple am missing 

![image](https://user-images.githubusercontent.com/25871665/103414837-77eacc80-4b77-11eb-852d-99b1c0743775.png)

```

# PowerShell Function App to Windows on Azure
# Build a PowerShell Function App and deploy it to Azure as a Windows function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell
trigger:
- main

variables:

  # Function app name
  functionAppName: 'gmtest-dev'

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/SPFunctioncode/gmtest-dev'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - powershell: |
        if (Test-Path "extensions.csproj") {
            dotnet build extensions.csproj --output ./$(workingDirectory)/bin
        }
      displayName: 'Build extensions'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: $(workingDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(functionAppName).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(functionAppName).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(functionAppName)
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'functionApp'
              appName: '$(functionAppName)'
              package: '$(Pipeline.Workspace)/drop/$(functionAppName).zip'
              deploymentMethod: 'runFromPackage'
```

### Task logs
[logs_276.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5757504/logs_276.zip)

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
