### ISSUE TITLE
NpmV1 publish scoped packages with public access

### ISSUE THREAD

**Issue by balanza** [microsoft/azure-pipelines-tasks#14165]
**Feature** 

**Enter Task Name**: Npm@V1 (with command=publish)

## Environment
- Server - Azure Pipelines 
- Account name, team project name, build definition name/build number: will be happy to provide in private message

- Agent - Hosted or Private: 
  - `ubuntu-latest`

## Issue Description

When publishing a scoped package there's no option to tell `npm` which kind of access it needs to assign. As by documentation, this option applies only to scoped packages and it has `restricted` as default value.
When using plain `npm` cli, we would use 
```sh
npm publish --access public # or restricted
```
Pipeline's user should be able to instruct `Npm@V1` to do the same, but it seems not to be possible. As a result, scoped packages can be published only if they are intended to be `restricted`.

### Error logs

There are no errors but the task does not allow some of the desired scenarios.

**Comment by balanza** [comment]
It seems there's a workaround that just get things done:
```yaml
- task: Npm@1
   inputs: 
     command: custom
     customCommand: publish --access public
     customEndpoint: my-npm-service-connection
```

Basically, use a custom command to solve the problem.
