### ISSUE TITLE
AzureResourceGroupDeployment@3 TemplateLink ID can only be used with api-version '2019-11-01' or later

### ISSUE THREAD

**Issue by bgk0018** [microsoft/azure-pipelines-tasks#14173]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeployment

## Environment
Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

ben.kennedy@cecentertainment.com
Reservations
PPPFunnel
20210104.6

Agent - Hosted or Private: Hosted

## Issue Description

Running `AzureResourceGroupDeployment@3` returns an error on ARM template validation _"The deployment definition is invalid; TemplateLink ID can only be used with api-version '2019-11-01' or later."_

This does not block deployment and does not result in any failed ARM Template deployments in the Azure Portal, but does result in an error being lodged against the deployment:

![image](https://user-images.githubusercontent.com/1944453/103560948-45461a00-4e7e-11eb-8f5e-3057955af065.png)

We are leveraging Template Specs for shared template usage which makes use of `Microsoft.Resources/deployments`'s 'TemplateLink IDs' to reference the template specs in a particular resource group. The `apiVersion` listed in the template for all of these resources is version `2020-06-01`.

I can not reproduce this error on my local machine deploying the same ARM template to the same resource group.
I can not reproduce this error on my local machine using `az deployment group validate`.

### Task logs

See Attached
[Logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5765935/Logs.zip)

### Error logs

"The deployment definition is invalid; TemplateLink ID can only be used with api-version '2019-11-01' or later."

**Comment by majorvin** [comment]
Is there any update on this issue?

**Comment by tnsholding** [comment]
Having same issue - preventing us from using Template Specs as our deployment pipelines uses AzureResourceGroupDeployment@3.

**Comment by majorvin** [comment]
@tnsholding  you can still use it and it works but just have to ignore that error message.

**Comment by willynagel** [comment]
We have this issue for months already. Waiting patiently for this issue to be resolved. When can we expect a solution? 
We have dozens of DSC tasks in Azure DevOps that give these errors.

**Comment by jper** [comment]
Still an issue today, very annoying to have false negatives in your release pipeline

**Comment by kwiecek** [comment]
there is an easy workaround:
```yaml
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(armServiceConnection)
        ScriptType: 'InlineScript'
        Inline: 'New-AzResourceGroupDeployment -ResourceGroupName $(sharedResourceGroupName) -TemplateFile ./templates/shared.json -templateSpecResourceGroupName "$(templateSpecResourceGroupName)"'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
```
