### ISSUE TITLE
AzureRmWebAppDeployment with Zip Deploy without deleting files left over from a previous deployment

### ISSUE THREAD

**Issue by izikl** [microsoft/azure-pipelines-tasks#14177]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureRmWebAppDeployment@4

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipeline
         https://dev.azure.com/msazure/One/_build/results?buildId=38049033

- Agent - Hosted or Private:   OneBranchPipelines 
        LinuxContainerImage: "centos:centos7"

## Issue Description

Currently Zip Deploy deletes files left over from a previous deployment. Is there a way to prevent this behavior?

**Motivation**: deployment to a web-app runs from a linux agent (so Web Deploy is not working) in a pull request pipeline. The idea is just to copy the zip to the web app and extract it without deleting other deployed ZIPs. The zip contains the files under folder PR<PR_ID> which enables this URL for every PR https://[site].azurewebsites.net/PR[PR_ID]. However, when files from previous deployments are deleted, only the latest PR is available.

I was able to do it using Web Deploy on a windows agent, but I need linux for other steps and I don't want to wait for a windows agent just for deploying the web app.

**Yaml**
```yaml
- task: AzureRmWebAppDeployment@4 
  displayName: "Azure App Service Deploy"
  inputs:
    ConnectedServiceName: ...
    WebAppName: kustowebdf
    Package: $(System.DefaultWorkingDirectory)/.../site-staging.zip
    TakeAppOfflineFlag: false
    AdditionalArguments: ""
    UseWebDeploy: true
    DeploymentType: zipDeploy
    RemoveAdditionalFilesFlag: false
```

### Task logs

Not a bug. Just a feature request so not adding any logs. 

### Error logs

Not a bug. Just a feature request so not adding any logs.
