### ISSUE TITLE
continueOnError results in failed tasks...

### ISSUE THREAD

**Issue by droopy4096** [microsoft/azure-pipelines-tasks#14184]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Any task.  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: Any 
    
## Issue Description

using code like:

```yaml
                  - task: DownloadPipelineArtifact@2
                    inputs:
                      buildType: specific
                      buildVersionToDownload: latestFromBranch
                      branchName: ${{ parameters.sourceBranch }}
                      project:  ${{ parameters.project_id }}
                      pipeline: ${{ pipeline_id }} 
                      downloadType: single
                      downloadPath: $(Pipeline.workspace)/downloads/${{ pipeline_id }}
                    displayName: download ${{ pipeline_id }} artifacts

                    continueOnError: true
```
to fetch any existing build artifacts results in errors for tasks, while job ends up in "warning" state... this creates a situation where "normal" failures can obfuscate "real" failures making things difficult for end-users. What is needed to completely ignore errors with either a warning marker or no marker whatsoever to silence them.

Note that it's the same issue for Kubectl tasks etc. *all* tasks would benefit greatly from ability to silence error output when task already been instructed that errors are OK via `continueOnError`
