### ISSUE TITLE
JavaTooInstallerV0 install failue via azureStorageAccount due to storage path

### ISSUE THREAD

**Issue by robododge** [microsoft/azure-pipelines-tasks#14214]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JavaTooInstarllerV0 

## Environment
- Server - Azure Pipelines or TFS on-premises?  Pipelines
    - ACC-Azure-02
    - 30253-Rainmaker
    - rainweb
    - buildID: 67205

- Agent - Hosted or Private: 
   Private:  Ubuntu 18, agent version 2.164.8

## Issue Description

When using the azure storage account to load in jdk gzip file, if a nested path to the jdk file is supplied, file extraction fails because the azureCommonVirtualFile path does nor handle a prefixed extra path as described in tool tips.   The resulting logs indicate an attempt to stat the tar.jz file from a with a double stacked path $(Pipeline.Workspace)/jdk15/jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz   which does not exist.  Note, the doubling of the jdk15 intermediate path.

```
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '15'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'AzureStorage'
        azureResourceManagerEndpoint: 'Rainmaker-SC'
        azureStorageAccountName: '30253adobuildstorage'
        azureContainerName: 'openjdk-container'
        azureCommonVirtualFile: 'jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz'
        jdkDestinationDirectory: '$(Pipeline.Workspace)/jdk15'
        cleanDestinationDirectory: true
```

## Troubleshooting
Tried moving the jdk artifact to the top-level directory in the storage account blob. That worked because it removed the need to use an extra path in the azureCommonVirtualFile property

### Error logs
```
Retrieving the JDK from Azure blob storage.
Downloading artifacts from Azure blob storage, Container Name: openjdk-container
Successfully fetcted list of items
Downloading openjdk-15.0.1_linux-x64_bin.tar.gz to /azagent/_work/1/jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz
Downloaded openjdk-15.0.1_linux-x64_bin.tar.gz to /azagent/_work/1/jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz
Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 3.124 secs, Download size: 0Bytes
Extracting archive to: /azagent/_work/1/jdk15/JAVA_HOME_15_x64_openjdk-15.0.1_linux-x64_bin_tar.gz
Creating destination folder: /azagent/_work/1/jdk15/JAVA_HOME_15_x64_openjdk-15.0.1_linux-x64_bin_tar.gz
##[error]ENOENT: no such file or directory, stat '/azagent/_work/1/jdk15/jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz'
##[error]ENOENT: no such file or directory, stat '/azagent/_work/1/jdk15/jdk15/openjdk-15.0.1_linux-x64_bin.tar.gz'
Finishing: JavaToolInstaller
```
