### ISSUE TITLE
HelmDeploy@0 task: cannot list resource "pods" in API group "" in the namespace "kube-system"

### ISSUE THREAD

**Issue by sarndt** [microsoft/azure-pipelines-tasks#14234]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question, maybe Bug?

**Enter Task Name**: HelmDeploy@0

## Environment

    Server - Azure Pipelines
    Agent - Hosted

## Issue Description

Helm Version: 2.x
When trying to use the Helm Deploy task with an environment specifying the connection details, like so:

```
jobs:
  - deployment: <deployment-name>
    displayName: Deploy Service
    pool:
      vmImage: $(vmImageName)
    environment: <environment-name>.<resource-name>
    strategy:
      runOnce:
        deploy:
          steps:
           - task: HelmInstaller@0
              displayName: 'Install Helm $(helmVersion)'
              inputs:
                helmVersion: '$(helmVersion)'
                checkLatestHelmVersion: false
            - task: HelmDeploy@0
              displayName: 'Initialize Helm on both client and server'
              inputs:
                command: init
                arguments: '--force-upgrade'
                failOnStderr: true
            - task: HelmDeploy@0
              displayName: 'Upgrade the release'
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: '$(Pipeline.Workspace)/_service_build/$(serviceName)'
                releaseName: '$(serviceName)'
                overrideValues: 'image.tag=$(Build.SourceVersion)'
                valueFile: '$(Pipeline.Workspace)/_service_build/$(serviceName)/environments/$(stageName)/values.yaml'
                arguments: "--namespace $(serviceNamespace)"
                recreate: true
                resetValues: true
                force: true
                waitForExecution: false
                failOnStderr: true
```

This task will fail with the following error:

```
##[error]Error: pods is forbidden: User "system:serviceaccount:<service-account-name>:***" cannot list resource "pods" in API group "" in the namespace "kube-system"
```

**Question**

Am I doing something wrong here, or have I not done everything necessary to deploy like this? I would have expected to not even need to supply the `--namespace` argument if I use an environment supplying the context of this deployment.

Looks a bit like #13421, does it maybe have something to do with that?
I haven't created debug logs/task logs yet, for now I've switched to supplying a connection myself which works, but I can try to provide some logs on request, would just need to check if any project-specific data is in there.
