### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3 or AzureResourceGroupDeployment@2 outputs not working when a value is null

### ISSUE THREAD

**Issue by cloudlucky** [microsoft/azure-pipelines-tasks#14246]
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3 and AzureResourceGroupDeployment@2 outputs fail to create variable when the property value is null.

list here (V# not needed):  
* AzureResourceGroupDeploymentV2
* AzureResourceManagerTemplateDeploymentV3

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
		Account Name: Circle6Dev
		Team Project: Project Marvel
		Build Definition: Platform CI
		Build Number: 7365
		https://dev.azure.com/circle6dev/Project%20Marvel/_build/results?buildId=7362&view=logs&j=e8e6a1fd-a743-5726-10d0-3eedb03850cf&t=db74fcaa-6fdf-5c59-5b9d-9323a47fc28b

- Agent - Hosted or Private:  Hosted    
    - If using Hosted agent, provide agent queue name: vmImage: windows-2019

## Issue Description

Setup: 
* Have a ARM Template with outputs.
* AzureResourceManagerTemplateDeployment or AzureResourceGroupDeployment task with deploymentOutputs

When a property value of the ARM Template output is "null" then it fails to create the deploymentOutputs variable.

For example (some lines have been removed for clarity):
In the yml build definition
```yml
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            [.....]
            csmFile: '$(dropDirectory)/armTemplates/FunctionsAppServicePlan-Template.json'
            csmParametersFile: '$(dropDirectory)/armTemplates/FunctionsAppServicePlan-Parameters.json'
            overrideParameters: -environment $(EnvironmentNameLower) -name Platform
            deploymentOutputs: 'functionsAppServicePlanOutputs'
```

In the log window:
```
2021-01-18T13:46:47.5848445Z Updated output variable 'appInsightsOutputs.appInsightsObject.value.provisioningState', which contains the outputs section of the current deployment object in string format.
2021-01-18T13:46:47.5873832Z (node:6392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
```

Then for the next task, the variable "functionsAppServicePlanOutputs" is not defined.

Also, when this happens, the task finish sucessfully but the output variable is not created.

### Task logs

[ARM Templates and Logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5832373/ARM.Templates.and.Logs.zip)
I included two ARM Templates where I can reproduce the issue:

* AppInsights where the "samplingPercentage" is null.
* AppServicePlan where the "workerTierName" is null on a ConsomptionPlan for the Azure Functions.

### Error logs

```
2021-01-18T13:46:47.5842828Z Updated output variable 'appInsightsOutputs.appInsightsObject.value.CreationDate', which contains the outputs section of the current deployment object in string format.
2021-01-18T13:46:47.5845800Z Updated output variable 'appInsightsOutputs.appInsightsObject.value.TenantId', which contains the outputs section of the current deployment object in string format.
2021-01-18T13:46:47.5848445Z Updated output variable 'appInsightsOutputs.appInsightsObject.value.provisioningState', which contains the outputs section of the current deployment object in string format.
2021-01-18T13:46:47.5873832Z (node:6392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
```
