### ISSUE TITLE
AzureRmWebAppDeployment@4 runFromPackage deploy not working in Azure App Service

### ISSUE THREAD

**Issue by little-eyes** [microsoft/azure-pipelines-tasks#14257]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment

list here (V# not needed):  4
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://microsoft.visualstudio.com/DefaultCollection/Data%20Science/_build?definitionId=53227&_a=summary

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

AzureRmWebAppDeployment successfully deployed a dotnet core 3.1 web service to Azure App Service, but the service stopped working. WEBSITE_RUN_FROM_PACKAGE=1 is set, but the wwwroot/ folder is not mounted to the content of zip package but the upper level that contains this zip file. see screenshot below. 

![image](https://user-images.githubusercontent.com/1495542/105284544-8a00cf00-5b67-11eb-9d78-234af7454f50.png)

When going to the app service using its URL, the error message is: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

The task YAML is below:

```yaml
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'xxx'
    appType: 'webApp'
    WebAppName: 'yyy'
    deployToSlotOrASE: true
    ResourceGroupName: 'zzz'
    SlotName: 'staging'
    packageForLinux: '$(Pipeline.Workspace)/Service_${{ parameters.build }}/Host.zip'
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
