### ISSUE TITLE
Ability to disable MSBuild distributed logger

### ISSUE THREAD

**Issue by Bouke** [microsoft/azure-pipelines-tasks#14255]
**Question, Bug, or Feature?** 
*Type*: Feature

**Enter Task Name**: MSBuild / VSBuild

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:
      Pool: Azure Pipelines
      Image: windows-2019
      Agent: Azure Pipelines 3

## Issue Description

I've reported a bug with the [distributed logger used by MSBuild / VSBuild](https://github.com/microsoft/azure-pipelines-tasks/blob/37b7beed4f89a64e51b2fcc8fe50eb6cc900e680/Tasks/Common/MSBuildHelpers/InvokeFunctions.ps1#L108), which is tracked under #14211. As a workaround for this bug, I want to use my own logger that emits VSO compatible output. I can add my own logger, but it _appends_ my logger instead of _replacing_ the existing logger. As a result, all build warnings are sometimes recorded twice. The first time by my logger (always) and sometimes by the distributed logger (not always, which is bug #14211).

I'd like the ability to disable the distributed logger.

```yaml
    - task: VSBuild@1
      displayName: Build
      inputs:
        solution: $(solution)
        platform: $(buildPlatform)
        configuration: $(buildConfiguration)
        maximumCpuCount: true
        msbuildArgs: -l:CentralLogger,$(System.DefaultWorkingDirectory)\.azuredevops\CustomLogger.dll
```

### Task logs

```
2021-01-20T15:50:05.0611276Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" \
    "D:\a\1\s\PROJECT.sln" /nologo /nr:false \
    /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.166.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=d76a57a7-1fe9-43be-b288-64732cd53bbf|SolutionDir=D:\a\1\s\Source"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.166.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" \
    -l:CentralLogger,D:\a\1\s\.azuredevops\CustomLogger.dll \
    /p:platform="x64" /p:configuration="Debug" /p:VisualStudioVersion="16.0" /m \
    /p:_MSDeployUserAgent="VSTS_66fd5d42-a447-4b7b-86ed-7c934fa7b924_build_25_0"
...
1> 2021-01-20T15:50:31.7911334Z ##[warning]File.cs(35,1): Warning S103: Split this 254 characters long line (which is greater than 160 authorized).
2> 2021-01-20T15:50:32.2586552Z     21>D:\a\1\s\File.cs(35,1): warning S103: Split this 254 characters long line (which is greater than 160 authorized). [D:\a\1\s\Project.csproj]
3> 2021-01-20T15:50:32.3723662Z ##[warning]File.cs(35,1): Warning S103: 'Split this 254 characters long line (which is greater than 160 authorized).'
```

I have annotated the output, with `1>` being the distributed logger, `2>` msbuild console output and `3>` being my custom logger.
