### ISSUE TITLE
Docker@2 Task ("Build") adds tag with space in path, breaking the build

### ISSUE THREAD

**Issue by ipointer-certifid** [microsoft/azure-pipelines-tasks#14264]
It appears that the tag source is injecting a tag for the working path of the build, which is adding a space to the tag, and causing docker to choke.

I'm not sure if we want to fix this with a simple PR to the Docker task to change `tag` to `tag.Trim()`, or if this is an issue that needs to be fixed higher up in the chain, or both.

See: https://github.com/microsoft/azure-pipelines-tasks/blob/e5a345be00dd924af015c62cb6c1437a375f8b00/Tasks/DockerV2/dockerbuild.ts#L54

Take, for example:

```
/usr/bin/docker build -f /home/vsts/work/1/s/Dockerfile --label com.azure.dev.image.system.teamfoundationcollectionuri=https://dev.azure.com/CertifID/ --label com.azure.dev.image.build.sourceversion=b1e056b8fcbcff87e398b1b05581b405a6aa9561 --build-arg CERTIFID_GIT_USER=ipointer-certifid --build-arg CERTIFID_GIT_PAT=*** -t ***/certifidhomeroom:185 -t ***/certifidhomeroom:latest -t ***/certifidhomeroom: /home/vsts/work/1/s
##[error]invalid argument "***/certifidhomeroom:" for "-t, --tag" flag: invalid reference format
```
Notice the space between that last tag's prefix, and the work location ☝️ .

For reference, the relevant part of my YML:
```
    - task: Docker@2
      displayName: Build HR & Vnts Img
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: '--build-arg CERTIFID_GIT_USER=$(CERTIFID_GIT_USER) --build-arg CERTIFID_GIT_PAT=$(CERTIFID_GIT_PAT)'
```

_Originally posted by @ipointer-certifid in https://github.com/microsoft/azure-pipelines-tasks/issues/14262#issuecomment-764908578_

**Comment by modmoto** [comment]
I use it similarly like that:
```
  - task: Docker@2
    inputs:
      containerRegistry: "official-docker-modmoto"
      repository: "modmoto/w3champions-matchmaking-service"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      buildContext: "."
      tags: |
        $(TAG)
        $(IS_LATEST)
```
On pull-request build the `IS_LATEST` variable is null, on master builds it is `latest`. In the version 2.176.0 this resulted in a command where the `IS_LATEST` was ignored and the image did not have the `latest` tag. Now this breaks my build because it tries to tag the build like that: `--tag myImage: ` (mark the empty space).
