### ISSUE TITLE
XCode tests are failing

### ISSUE THREAD

**Issue by nick3389** [microsoft/azure-pipelines-tasks#14278]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XCode  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Hello,

There is something really strange happening. I am new to azure pipelines but I managed to setup one for an iOS project. project builds fine but the majority of the tests are failing but only in the pipeline. If I run them through XCode or even Jenkins the testa are always successful. Can you help me with this? Is something that I should set up? 
Also I get this error at the end of the task:
`/usr/bin/xcodebuild failed with return code: 65`

**Comment by anatolybolshakov** [comment]
Hi @nick3389 could you please share your yaml file and pipeline logs?

**Comment by nick3389** [comment]
Hi @anatolybolshakov. yaml is here:

```
pool:
  name: Azure Pipelines
  demands: xcode

#Your build pipeline references an undefined variable named ‘Parameters.xcodeVersion’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.destinationSimulators’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: CocoaPods@0
  displayName: 'pod install'
  inputs:
    workingDirectory: my_directory
    projectDirectory: my_directory

- task: Xcode@5
  displayName: Xcode
  inputs:
    actions: 'clean build test'
    xcWorkspacePath: my_path
    scheme: TestApp
    xcodeVersion: '$(Parameters.xcodeVersion)'
    destinationPlatformOption: iOS
    destinationSimulators: '$(Parameters.destinationSimulators)'
    args: '-enableCodeCoverage YES'
    publishJUnitResults: true
```

Because of privacy issues, do you need something specific from the logs? I am asking you because I don't want project information to be public.
