### ISSUE TITLE
Error: EMFILE: too many open files, open 'D:\a_temp\temp_web_package_9235376407089184\node_modules\tar-fs\test\fixtures\d\file1'

### ISSUE THREAD

**Issue by NWH-SAmin5** [microsoft/azure-pipelines-tasks#14273]
Error: EMFILE: too many open files, open 'D:\a\_temp\temp_web_package_9235376407089184\node_modules\tar-fs\test\fixtures\d\file1'

Log:
2021-01-24T08:18:19.9115523Z ##[section]Starting: Azure Web App Deploy: APP_SERVICE_NAME
2021-01-24T08:18:19.9336583Z ==============================================================================
2021-01-24T08:18:19.9336939Z Task         : Azure Web App
2021-01-24T08:18:19.9337213Z Description  : Deploy an Azure Web App for Linux or Windows
2021-01-24T08:18:19.9337482Z Version      : 1.168.3
2021-01-24T08:18:19.9338774Z Author       : Microsoft Corporation
2021-01-24T08:18:19.9339107Z Help         : https://aka.ms/azurewebapptroubleshooting
2021-01-24T08:18:19.9340184Z ==============================================================================
2021-01-24T08:18:21.4138038Z Got service connection details for Azure App Service:'APP_SERVICE_NAME'
2021-01-24T08:18:22.4206941Z $APP_SERVICE_NAME
2021-01-24T08:18:22.4207745Z APP_SERVICE_NAME.scm.azurewebsites.net
2021-01-24T08:19:30.4109454Z ##[error]Error: EMFILE: too many open files, open 'D:\a\_temp\temp_web_package_9235376407089184\node_modules\tar-fs\test\fixtures\d\file1'
2021-01-24T08:19:39.5648101Z Successfully updated deployment History at https://APP_SERVICE_NAME.scm.azurewebsites.net/api/deployments/11611476370410
2021-01-24T08:19:39.5650514Z App Service Application URL: http://APP_SERVICE_NAME.azurewebsites.net
2021-01-24T08:19:45.6860095Z ##[section]Finishing: Azure Web App Deploy: APP_SERVICE_NAME

```
Azure Pipeline Hosted Agent
Version: 2.181.0
```

_Originally posted by @NWH-SAmin5 in https://github.com/microsoft/azure-pipelines-tasks/issues/4127#issuecomment-766312322_

**Comment by amit-avit** [comment]
@NWH-SAmin5 can you please try making use of: "Azure App Service Deploy" (AzureRmWebAppDeployment@V4)

**Comment by NWH-SAmin5** [comment]
Okay let me try using Azure App Service Deploy

**Comment by NWH-SAmin5** [comment]
@amit-avit 

I tried using "Azure **App Service** Deploy" and this does not work. But this one throwing error "credential cannot be null". I tried recreating Service Connection but still facing this issue.

I have attached both Log and YAML please review.
azure-app-service-deploy.log
azure-app-service-deploy.yaml.txt



Also previous failed Release for "Azure **Web App** Deploy" I have attached LOG and YAML
azure-web-app-deploy.log
azure-web-app-deploy.yaml.txt

**Comment by amit-avit** [comment]
You need to provide the mandatory/required parameters. You can use the assistant(right pane) for making things easier.

Please check out [this](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/README.md#parameters-of-the-task) readme for parameters required.

```
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '<connection_name>'
    appType: 'webApp'
    WebAppName: '<web_app_name>'
    Package: '<package_path>'
```

![image](https://user-images.githubusercontent.com/8944724/105988537-cbdcc880-60c5-11eb-829d-6f016f33dcbb.png)

**Comment by amit-avit** [comment]
Please confirm if your issue gets resolved.

**Comment by NWH-SAmin5** [comment]
Hi @amit-avit,

I used the assist pane and I did fill the all the required information OR else it doesnt let me save. Not sure why YAML is doesnt have all parameters mentioned but it there in my assist pane. see below screenshot.

Also if you notice debug Log it looks like it has all that information.


![image](https://user-images.githubusercontent.com/44787317/106013854-de85dc00-608a-11eb-83a2-4aea17a888c7.png)

**Comment by amit-avit** [comment]
Are you archiving the required deployment folder to a zip?
The package path should be the root folder or the zip.

**Comment by NWH-SAmin5** [comment]
Yes I am, this is my build yaml.

```
stages:
  - stage: Build
    displayName: Build and package
    jobs:
      - job: Build
        displayName: Build and package
        pool:
          vmImage: "windows-latest"
        steps:
          - task: NodeTool@0
            displayName: Use Node 10.21.0
            inputs:
              versionSpec: "10.21.0"
          - script: |
              npm install
            displayName: npm install
          - script: |
              npm run build
            displayName: npm run build
          - task: CopyFiles@2
            displayName: Only publish files needed for runtime
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: |
                dist/**
                library/**
                package.json
                node_modules/**
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(Build.ArtifactStagingDirectory)"
              includeRootFolder: false
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(appName).zip"
              archiveType: zip
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/$(appName).zip"
```

![image](https://user-images.githubusercontent.com/44787317/106015982-04ac7b80-608d-11eb-8e4a-1df1fde9a943.png)
