### ISSUE TITLE
Kubernetes task does not fail on failure

### ISSUE THREAD

**Issue by tbuico-premera** [microsoft/azure-pipelines-tasks#14283]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - account name: tom.buico@premera.com
        - team project name: Premera
        - build definition name/build number: (unsure how to locate)

- Agent - Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
        - OS: RHEL 7.7
        - Agent Version: 2.175.2
        - Container: alpine:3
## Issue Description

The following task in an ado pipeline is used in order to log into a kubernetes cluster:

```yaml
- task: Kubernetes@1
  displayName: 'login to k8s'
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: 'kubernetesServiceEndpoint.com'
    command: login
```

If there is a timeout or another failure for any reason, this task does not fail. This leads to any future tasks in the pipeline which executes code on the k8s cluster to fail.

Here is an example of a **failure**:

```yaml
Starting: login to k8s
==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.181.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-kubectl-tsg
==============================================================================
Prepending PATH environment variable with directory: /usr/bin
==============================================================================
      Kubectl Client Version: v1.20.1
  Kubectl Server Version: Could not find kubectl server version
==============================================================================
commandOutput
Finishing: login to k8s
```

Retries of the same pipeline without any changes will often work.

Here is an example of a **success** on Attempt #2, without any changes to code or pipeline.

```yaml
Starting: login to k8s
==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.181.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-kubectl-tsg
==============================================================================
Prepending PATH environment variable with directory: /usr/bin
==============================================================================
      Kubectl Client Version: v1.20.1
      Kubectl Server Version: v1.18.12+vmware.2
==============================================================================
commandOutput
Finishing: login to k8s
```

One can notice that now the `Kubectl Server Version` is valid on Attempt #2

### Task logs

Attached as a zip file
[f715a6ba-3879-5f79-a1ba-81e2d10a389e.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5876688/f715a6ba-3879-5f79-a1ba-81e2d10a389e.zip)
