### ISSUE TITLE
[Question] Cache@2 returns cache miss even though a previsous build with the exact same key populated the cache

### ISSUE THREAD

**Issue by mastoj** [microsoft/azure-pipelines-tasks#14290]
How is the cache supposed to work? 

I almost get a cache miss on every build, even though I'm 100% sure it is using the same cache key. Is it anythin more than this I need to do:

```
    - task: Cache@2
      inputs:
        key: 'nuget | "$(Agent.OS)" | **/fake.fsx.lock'
        path: $(PACKAGES_PATH)
      displayName: Cache NuGet packages
```

Is the cache only there for a specific amount of time?
