### ISSUE TITLE
Docker activity logs secrets

### ISSUE THREAD

**Issue by lygasch** [microsoft/azure-pipelines-tasks#14293]
**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: DOCKER

## Environment
AZURE PIPELINES, 
acct MSENG
project: SPACE
pipeline: https://dev.azure.com/mseng/1ES/_build?definitionId=10355&_a=summary
agent: ubuntu-20.04

## Issue Description
I am looking into our docker command task is logging some secrets that are passed on the command line.
I am not sure if the issue is in the task or the task caller. The secret is fetched in a prior task and set like this:
```
echo "##vso[task.setvariable variable=secret.docDbKey;issecret=true]$docDbKey"
```
and it is passed to the Docker task in the Arguments field (UI pipeline, not yaml) as
```
-e docDbKey="$(secret.docDbKey)"
```

this is how the logging looks
![image](https://user-images.githubusercontent.com/13108325/106070395-3c311d00-60b9-11eb-9371-8e6a96c095c1.png)

**Comment by ds-ms** [comment]
The docker task doesn't explicitly handle the masking of secrets. The masking is taken care of by the agent while parsing the raw pipeline logs.

@damccorm could you take a look?

**Comment by damccorm** [comment]
@ds-ms my guess is that the secret is being modified somehow and isn't an exact match (e.g. some sort of escaping or whitespace is being injected). From the logging side we guarantee that the exact secret will be masked, but not modified variants - could you confirm that is the case?

In general, it is not a great idea to intentionally log secrets, I would consider not logging the value in this case regardless

**Comment by lygasch** [comment]
Is it not matched because it is appended to docDbKey= and no longer whitespace delimited?
Also, would it be possible to surface a flag that pipeline authors could use to immediately suppress logging of the cmd string? This would allow a mitigation while the issue is being investigated. As it stands, I have no control over this at all. It would be great to treat this as high priority. Thanks!

**Comment by lygasch** [comment]
I saw in debug logs (don't have the example any longer) where the secret WAS redacted in those logs but then not here. I have learned from that troubleshooting session that the args are converted into an array and I wonder if this text is built with something like array select so the secret-ness is lost? Please bump the priority, this is a serious leak and I have no mitigation.

**Comment by ds-ms** [comment]
@Ganeshrockz could you take a look at this?

**Comment by lygasch** [comment]
Hi, is there any progress on this issue? Thanks!

**Comment by Ganeshrockz** [comment]
@lygasch Apologies for the delay. Can you help me reproducing this one?

I tried with the following yaml

```
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docDbKey=Sample
      
      echo "##vso[task.setvariable variable=secret.docDbKey;issecret=true]$docDbKey"

- task: Docker@2
  inputs:
    containerRegistry: 'sample-acr'
    repository: 'sampleAcr'
    command: 'run'
    arguments: '-d key="$(secret.docDbKey)"'
```

The secret seems to be masked in this case. I believe your tasks also do something very similar right?
