### ISSUE TITLE
DotNetCoreCLI@2 doesn't have access to feeds when installing tools which leads to failures

### ISSUE THREAD

**Issue by ElvenSpellmaker** [microsoft/azure-pipelines-tasks#14318]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: DotNetCoreCLI@2

## Issue Description
Trying to install tools when you have a `nuget.config` fails because it doesn't have access to the feeds. Even though this tool is in the public Nuget.org repo it still tries our private repositories first and fails to auth.

```yml
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global dotnet-reportgenerator-globaltool'
      feedsToUse: 'config'
      nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'
    displayName: "Install dotnet-reportgenerator-globaltool"
```

This is a public tool in Nuget but for some reason it tries to look in the private repositories first and so fails. I understand that some tasks don't have access to feeds (only `restore` does) but this means we can't use this to install the tool we want as we have private feeds in our `nuget.config`.

When I first tried this I tried not passing:
```yml
      feedsToUse: 'config'
      nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'
```
but it still fails as it picks up the config in the root of the repo by default.

Our `nuget.config`:
![image](https://user-images.githubusercontent.com/2286713/106324344-dedfcc00-6270-11eb-87ac-7e1929e61236.png)

### Task logs
![image](https://user-images.githubusercontent.com/2286713/106323916-2023ac00-6270-11eb-89f5-b50d7916a1c2.png)

**Comment by ElvenSpellmaker** [comment]
For now I'm having to work around this by using a Pwsh script that installs the tool and make sure I set the directory to somewhere random outside of the project root:
```yml
  - task: PowerShell@2
    inputs:
      targetType: inline
      script:
        dotnet tool install --global dotnet-reportgenerator-globaltool
      workingDirectory: $(Agent.ToolsDirectory) # Try to be outside of the project
    displayName: "Install dotnet-reportgenerator-globaltool"
```

**Comment by vineetmimrot** [comment]
Hey @ElvenSpellmaker,

You don't need to mention nuget feed in the task as this field is used only by the restore command.
You can directly use dotnet task with below configuration:



```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet custom'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --tool-path coverage dotnet-reportgenerator-globaltool'
```

**Comment by ElvenSpellmaker** [comment]
The above fails as it loads the `NuGet.config` file in the project as mentioned in my issue, it tries to enumerate the sources and fails to do so as only `restore` has access... This shouldn't be closed, it's still an issue.

**Comment by vineetmimrot** [comment]
@ElvenSpellmaker Can you pass the NuGet config as an argument to the task as mentioned in this doc
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#options

It is the dotnet tool that is automatically picking your Nuget file, so the task can't do anything here.

**Comment by vineetmimrot** [comment]
The dotnet custom command is not supposed to use any nuget configuration. Please reach out to dotnet team, if above solution doesn't fix the issue.

**Comment by ElvenSpellmaker** [comment]
@vineetmimrot The `custom` command needs to use the nuget config, because the tool you install _could_ be in a private feed.

**Comment by vineetmimrot** [comment]
Can you please try the workaround as passing nuget configuration as argument of custom command.

**Comment by sharpjs** [comment]
@ElvenSpellmaker The following worked for me to install a tool from a private Azure DevOps Artifacts feed:

```yaml
- task: NuGetAuthenticate@1
  displayName: Authenticate artifacts feed

- task: DotNetCoreCLI@2
  displayName: Download package
  inputs:
    command: custom
    custom: tool
    arguments: >-
      install MyTool
      --tool-path .
      --add-source https://pkgs.dev.azure.com/MyOrg/MyProj/_packaging/MyFeed/nuget/v3/index.json
```
