### ISSUE TITLE
CUrlUploaderV2 task can have more uses than documentation suggest

### ISSUE THREAD

**Issue by guicey** [microsoft/azure-pipelines-tasks#14324]
https://github.com/microsoft/azure-pipelines-tasks/blob/ef86c44958bf55a6d7f045060b96117c310a4bf5/Tasks/CUrlUploaderV2/curluploader.ts#L36

Hi Community, 

I'm currently using the CUrlUploaderV2 task to search for JSON files in a directory and HTTP.POST them to a Wiremock server for stubbing purposes on our test environment where no username and password is needed. The documentation suggest that you should pick an authentication method: “#authType: 'ServiceEndpoint' # Optional. Options: serviceEndpoint, userAndPass“. If you don't enter a value the default will be serviceEndpoint. 

Can a third option be added e.g. noAuthentication? And maybe be more elaborate in the documentation that http methods are also supported.

(Nice plugin btw)

**Usage:**
```
- task: cURLUploader@2
  inputs:
     files: mocks/mappings/*.json
     authType: noAuthentication
     url: https://mywiremock.server.nl/
     remotePath: __admin/mappings
     options: '-X POST -H "Content-Type: application/json"' 
```

**Stdout:**
```
/usr/bin/curl -T {/agent/mocks/mappings/login.json, /agent/mocks/mappings/annual-statements.json, /agent/mocks/mappings/loans.json} https://mywiremock.server.nl/__admin/mappings --stderr - -X POST -H Content-Type: application/json
  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "id" : "8e8d20e8-c0d0-4762-953b-1b0db4aa928b",
  "request" : {

	etc.......
```
