### ISSUE TITLE
AzureFunctionAppV1 and AzureRmWebAppDeploymentV4 fail when used with Management Group Service Connection

### ISSUE THREAD

**Issue by cstrempfer** [microsoft/azure-pipelines-tasks#14359]
Copied from #13779, because it was closed incorrectly and nobody reopened it since 3 months.

Justification:
1. Service Connections support Management Groups
2. App Service Tasks support Service Connections
3. App Service Tasks fail if used with a Management Group Service Connection
=> Bug, because it isn't compatible with the Azure Pipelines' standard and users cannot fix it themselves

## Required Information
**Question, Bug, or Feature?**
_Type_: Bug?

**Enter Task Name**: AzureFunctionAppV1 and AzureRmWebAppDeploymentV4

## Environment
* Server - Azure Pipelines
  
  * If using Azure Pipelines, provide the account name, team project name, build definition name/build number: not specific to our environment....
* Agent - Hosted
  
  * If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description
When using the two mentioned tasks to deploy a WebApp/FunctionApp we get the error: "'subscriptionId' cannot be null" when using a Management Group Service connection. Checking the code both tasks don't support the subscriptionId yet. Using the tasks with the normal Subscription Level Service connection works fine.

### Task logs
##[error]Error: 'subscriptionId' cannot be null.

### Error logs
##[error]Error: 'subscriptionId' cannot be null.

**Comment by cstrempfer** [comment]
It could be easily avoided if there would be an optional "subscriptionId" parameter in addition to the "azureSubscription" parameter (which is actually pointing to a service connection), and if its value would be applied in case that a service connection with Management Group is selected. If you put this logic into "InitializeAzModuleFunctions.ps1" you could use the same mechanism for other Pipeline Tasks as well, because I've seen other bug reports for similar issues.

**Comment by 20shivangi** [comment]
@cstrempfer As pointed out earlier, Management Group service connection will not work for deploying to a web app. Since Management Group service connection does not take subscription id while creation but for deploying to resources like a web app, we do need the subscription id.
And for your idea of being having an optional "subscriptionId" parameter in case of Management Group service connection, we will reach out to PMs and confirm about this requirement.

**Comment by cstrempfer** [comment]
@20shivangi I'm not sure we are on the same page here. Service connections should not have an additional subscription id, because that would defeat the purpose of using management groups in service connections. My suggestion was to add a subscription id to the pipeline tasks, so that it can handle both kinds of service connections.

Trying to put the subscription id anywhere else would ignore increasing adoption of management groups. I created this as a bug, because there is no obvious reason for not supporting Management Groups already and because there is no documented limitation.

**Comment by 20shivangi** [comment]
@cstrempfer I totally agree what you said "Service connections should not have an additional subscription id, because that would defeat the purpose of using management groups in service connections."

What I am saying is that , `having an optional "subscriptionId" parameter in addition to the "azureSubscription" parameter (which is actually pointing to a service connection), and its value would be applied in case that a service connection with Management Group is selected`, we will confirm this with our PMs about this.

**Comment by KZeronimo** [comment]
@20shivangi  any update on this - in general, the Tasks ecosystem needs to catch up with management group scoped service connections - [AzureResourceManagerTemplateDeployment@3](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3) is a good pattern with a clear separation of the required params

`azureResourceManagerConnection` for the service connection
and
`subscriptionId` for the subscription id

**Comment by nadesu** [comment]
+ @v-jkarri for visibility, @vijayma for prioritisation

**Comment by cstrempfer** [comment]
Still waiting for a solution...

**Comment by SamBonavika** [comment]
Allow me to add my 2 cents:

Half of Microsoft pushes really hard to promote a top-down strategy for managing policy and security ...

Half of Microsoft pushes really hard to "empower" the Azure DevOps user community to create truly dynamic CI/CD pipeline implementations ...

But unfortunately, these two halves never seem to intersect, leaving those of us who really really REALLY want to invest in the entire MS tech stack out in the cold pulling our hair and gnashing our teeth in ABJECT FRUSTRATION!!!!

Please escalate this issue to a Tech PM who has actually USED these products and who understands how the omission of a seemingly trivial feature can result in such chaos to the user community.

**Comment by FinVamp1** [comment]
Hello,

This is an enhancement for the agent overall that the team is tracking. Adding @geekzter to help

**Comment by cstrempfer** [comment]
Another year passes by ...

**Comment by FinVamp1** [comment]
Hello, I'm following up with the Azure DevOps to help understand if there is another work item tracking overall Task Support for Management Group Service Connections as opposed to implementing for specific Tasks as asked in this item.

**Comment by FinVamp1** [comment]
@geekzter Can you update this work item with the plans for this?

**Comment by FMERI001** [comment]
Any word from MS on this issue?

**Comment by FinVamp1** [comment]
Updated the labels and my assignment. @geekzter  can follow up on this.

**Comment by cstrempfer** [comment]
😴

**Comment by SamBonavika** [comment]
Anyone? Anyone? Bueller???

**Comment by msterin** [comment]
bump. Any update ?

**Comment by HamiltonMedicalMichael** [comment]
Bump. Maybe we could open the PR ourself?

**Comment by bjuraga** [comment]
I just hit this, it invalidates a use case where my team is granted permissions (trust) on a management group, but we need to bother the sec team every time a new subscription is created. It defeats the purpose of management group level trust, so i wonder why this is simply ignored for years. 

By the looks of it, it seems like exposing the subscription id as a field would simply work.

**Comment by AlexManev** [comment]
Same issue with Kubernetes@1 using a Management Group scoped Service Connection getting the same error

**Comment by darkLordOfTheCommit** [comment]
Any update here?  Cross-subscription deployments are a thing, so not sure why there are crickets on this issue.  We have a service connection with management group permissions to be able to handle deployments in two subs.  Using @AzureFunctionsApp@2 to deploy to a Flex Consumption app and receiving this same error.
 
```yaml
- task: AzureFunctionApp@2
  displayName: 'Deploy to ${{ parameters.appServiceName }}'
  inputs:
    appType: "functionAppLinux"
    azureSubscription: ${{ parameters.serviceConnectionName }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    appName: ${{ parameters.appServiceName }}
    package: '$(System.ArtifactsDirectory)/${{ parameters.serviceName }}/**/*.zip'
    deploymentMethod: "auto"
    appSettings: '-AZURE_FUNCTIONS_ENVIRONMENT $(AzureFunctionsEnvironment)'
    isFlexConsumption: true
    subscriptionId:  ${{ parameters.subscriptionId }} #this sure would be nice?
```

**Comment by rexhinokovaci** [comment]
bump, any updates? or what did you do for a workaround?

**Comment by dotnetcadet** [comment]
We use Management Groups for Subscriptions that separate our individual clients. Here is a work around with powershell that works for both Functions and Web Apps. Thought I'd leave this here given this has open for quite a while.


code: Here is a real world scenario

```yml
parameters:
  - name: client
    type: string

  - name: affix
    type: string

  - name: region
    type: string

  - name: environment
    type: string

  # The service being deployed
  - name: domain
    type: string


jobs:
  - deployment: ${{ parameters.client }}_${{ parameters.domain }}
    displayName: "Domain: ${{ upper(parameters.domain) }} "
    ${{ if eq(parameters.environment, 'dev') }}:
      environment: "Development"
    ${{ if eq(parameters.environment, 'qa') }}:
      environment: "Quality Assurance"
    ${{ if eq(parameters.environment, 'stg') }}:
      environment: "Staging"
    ${{ if eq(parameters.environment, 'uat') }}:
      environment: "User Acceptance Testing"
    ${{ if eq(parameters.environment, 'prd') }}:
      environment: "Production"
    strategy:
      runOnce:
        deploy:
          steps:
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: DevOps SA (${{ upper(parameters.environment) }})
                    pwsh: true
                    workingDirectory: "$(Pipeline.Workspace)/drop"
                    azurePowerShellVersion: "LatestVersion"
                    ScriptType: InlineScript
                    Inline: |
                      $DefaultSubscription = (Get-AzSubscription | Where-Object {  
                          # some logic to get the default subscription 
                       })
      
                      Set-AzContext -SubscriptionObject $DefaultSubscription

                      Publish-AzWebApp `
                        -ResourceGroupName '${{ parameters.affix }}-app-${{parameters.environment}}-${{ parameters.region }}-rg-01' `
                        -Name '${{ parameters.affix }}-app-${{parameters.environment}}-${{ parameters.region }}-app-${{ parameters.domain }}' `
                        -Slot Staging `
                        -ArchivePath "$(Pipeline.Workspace)/drop/${{ parameters.domain }}.zip" `
                        -AsJob `
                        -Type zip `
                        -Force

                      Swap-AzWebAppSlot `
                        -ResourceGroupName '${{ parameters.affix }}-app-${{parameters.environment}}-${{ parameters.region }}-rg-01' `
                        -Name '${{ parameters.affix }}-app-${{parameters.environment}}-${{ parameters.region }}-app-${{ parameters.domain }}' `
                        -SourceSlotName staging `
                        -DestinationSlotName production 

```

**Comment by rexhinokovaci** [comment]
yeah thats what i currently use also az account set --subscription , thanks

**Comment by Tni04** [comment]
If you are still facing this issue, you can bypass the validation by providing the subscription ID through an environment variable.

The pattern is ENDPOINT_DATA_<CONNECTION_GUID>_SUBSCRIPTIONID.

```YAML
- task: AzureWebApp@1
  inputs:
   #  ...
  env:
    ENDPOINT_DATA_00000000-0000-0000-0000-000000000000_SUBSCRIPTIONID: 'your-subscription-id
```

You can find the full example and why this works in this comment: https://github.com/microsoft/azure-pipelines-tasks/issues/13779#issuecomment-4080480560. This unblocks the pipeline while we wait for native support from Microsoft.
