### ISSUE TITLE
Bash task environment variable not working

### ISSUE THREAD

**Issue by little-eyes** [microsoft/azure-pipelines-tasks#14370]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Bash or script  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://microsoft.visualstudio.com/DefaultCollection/Data%20Science/_build?definitionId=53227&_a=summary

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I'm using bash task to set environment variable before running python code in a container, but the environment variable does not exist when python code try to read the variable.

YAML script:
```yaml
- script: |
    echo "Client_Secret=$(Deployment_Client_Secret)"
    python deploy-aml-pipeline.py --env ${{ parameters.env }} --pipeline enrich --no-wait
  displayName: 'Deploy AML pipeline'
  workingDirectory: src/Deployment
  env:
    Deployment_Client_Secret: ${{ parameters.client_secret }}
```

```bash
Starting: Deploy AML pipeline
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/9b3bda9a-aa1c-4c34-b726-2c0206aa1092.sh
/__w/_temp/9b3bda9a-aa1c-4c34-b726-2c0206aa1092.sh: line 1: Deployment_Client_Secret: command not found
Client_Secret=
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
