### ISSUE TITLE
Unable to provide mapping of env variables to Bash script.

### ISSUE THREAD

**Issue by Zanchee** [microsoft/azure-pipelines-tasks#14384]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
Type: Bug

**Enter Task Name:** Bash

## Environment

- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
        Not at liberty to share publicly, can provide privately if asked.

- Agent - Hosted:
   - Image: macOS-latest

## Issue Description

I am unable to provide a map of environment variables to my Bash script. I read the docs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) and it says that `env` is a "mapping of environment variables to add". Am I missing something obvious here?
 
```
steps:
- task: Bash@3
  displayName: '🐙 Coverage Report'
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: coverage -c ${{ parameters.current_results_path }} -p ${{ parameters.pull }}
    env:
      GITHUB_USERNAME: $(github_username)
      GITHUB_TOKEN: $(github_token)
      GITHUB_OWNER: $(github_owner)
      GITHUB_REPO: $(github_repo)
```

<img width="681" alt="Screen Shot 2021-02-11 at 8 11 43 PM" src="https://user-images.githubusercontent.com/13373737/107719615-a5fb1a80-6ca6-11eb-8ff2-4ae18875a2a7.png">
