### ISSUE TITLE
"kubernetes@1" does not configure a context

### ISSUE THREAD

**Issue by Justin-DynamicD** [microsoft/azure-pipelines-tasks#14401]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: kubernetes@1

## Environment: Azure Pipelines

Account Name: itsocloud
project Name: DevOps
Pool: DevOps-Builders

## Issue Description

After using kubernetes@1 'login' command, attempting to run kubectl from command line reveals no configured context which make subsequent commands fail.

task used:
```
- task: Kubernetes@1
        displayName: K8S Authentication
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'redacted'
          command: 'login'
 
- task: CmdLine@2
        displayName: Container Build
        inputs:
          script: |
            kubectl build -t ${{ parameters.name }}:latest ${{ parameters.buildArgs }} ${{ parameters.buildContext }}
```

Error output
```
Error: no context is currently set, use "kubectl config use-context <context>" to select a new one
```

Attempting to simply pass `kubectl config get-contexts` it returns an empty list:

```
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE
```

Logs attached

[logs_474.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5991905/logs_474.zip)
