### ISSUE TITLE
UseDotNet@2: no option to install aspnetcore runtime (only full sdk or regular runtime)

### ISSUE THREAD

**Issue by megafinz** [microsoft/azure-pipelines-tasks#14405]
**Type**: Question || Feature

**Enter Task Name**: UseDotNet

## Issue Description

I would like to install **aspnetcore runtime 3.1** along with **sdk 5.0** during the pipeline run. I'm trying to use `UseDotNet` task for that. It seems that there is no option for installing the **aspnetcore runtime**, the choice is either **regular runtime** or **sdk**. Installing the **sdk** also installs the correct **aspnetcore runtime**, but I only need the runtime, not the full sdk.

### Task logs

If I use this yaml:

```yaml
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1.12 runtime'
  inputs:
    packageType: runtime
    version: 3.1.12
- task: UseDotNet@2
  displayName: 'Install .NET 5.0.103 SDK'
  inputs:
    packageType: sdk
    version: 5.0.103
```
and then dump runtime versions with `dotnet --list-runtimes`, I get this output:

```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet --list-runtimes
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/c5a498e9-e15c-4323-903b-480b1392e357.sh
Microsoft.AspNetCore.App 5.0.3 [/__t/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.12 [/__t/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.3 [/__t/dotnet/shared/Microsoft.NETCore.App]

Finishing: CmdLine

```

If I install the full sdk instead, I get the aspnetcore runtime installed as expected:

```yaml
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1.405 SDK'
  inputs:
    packageType: sdk
    version: 3.1.405
- task: UseDotNet@2
  displayName: 'Install .NET 5.0.103 SDK'
  inputs:
    packageType: sdk
    version: 5.0.103
```

```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet --list-runtimes
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/c4326120-83e3-4e63-9af0-cae582f506ad.sh
Microsoft.AspNetCore.App 3.1.11 [/__t/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.3 [/__t/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.11 [/__t/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.12 [/__t/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.3 [/__t/dotnet/shared/Microsoft.NETCore.App]

Finishing: CmdLine
```

**Comment by vineetmimrot** [comment]
@megafinz Since a possible workaround is available to install AspNetCore runtime as part of SDK, we will not be planning to take this up in near future. Hence closing the issue.

**Comment by TsengSR** [comment]
> [@megafinz](https://github.com/megafinz) Since a possible workaround is available to install AspNetCore runtime as part of SDK, we will not be planning to take this up in near future. Hence closing the issue.

That's a really dumb point of view. Installing the SDK is slow and it changes the tooling. There is a lot of use cases where we want to use new tooling and new runtime and hence install the SDK, but then have a specific tool which requires a specific runtime and an older Microsoft.AspNetCore.App. 

Installing that changes the whole tooling for the rest of the pipeline. i.e.

```yaml
      - task: UseDotNet@2
        displayName: 'Install .NET 7.x SDK'
        inputs:
          packageType: 'sdk'
          version: '7.x'
     # required for Swashbuckle.AspNetCore.Cli
      - task: UseDotNet@2
        displayName: 'Install .NET 3.x Runtime'
        inputs:
          packageType: 'runtime'
          version: '3.x'

      - bash: if [[ $(dotnet tool list -g | grep swashbuckle.aspnetcore.cli) ]]; then echo "Tool is already installed"; else dotnet tool install --version 5.6.3 -g Swashbuckle.AspNetCore.Cli; fi
        displayName: 'Install Swashbuckle CLI'
      - bash: |
          swagger tofile --output StorageLocationService.json ${BUILD_SOURCESDIRECTORY}/build/$(project_name).dll v1
        displayName: 'Generate swagger.json'

     # Build rest
```

Now in this case the tooling fails, because it can't find `Microsoft.AspNetCore.App`. When changing it from `runtime` to `sdk`, it works, but the rest of the pipeline runs with 3.x tooling!! Which causes all kind of issues
