### ISSUE TITLE
Intermittent quote failure in bash task/variable substitution

### ISSUE THREAD

**Issue by Korijn** [microsoft/azure-pipelines-tasks#14408]
Given:

```yaml
  parameters:
    image: 'myorganization.azurecr.io/project/system'
```

The following **_sometimes_** fails. I can't explain it. Retrying usually works.

```yaml
  steps:
  - task: Bash@3
    displayName: Set vars
    name: setVars
    inputs:
      targetType: inline
      script: |
        set -ex
        export GIT_REV=$(git rev-parse --short $(Build.SourceVersion))
        echo "##vso[task.setvariable variable=GIT_REV]$GIT_REV"
  - task: Bash@3
    displayName: Docker pull
    inputs:
      targetType: inline
      script: |
        set -ex
        docker pull ${{ parameters.image }}:dev-$(GIT_REV)
```

Like so:

```
Starting: Set vars
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/cf264bb2-704a-4b52-b55c-68922e8b64c9.sh
++ git rev-parse --short 464c86960599671cd35e0d3b87cb17baffeed09a
+ export GIT_REV=464c8696
+ GIT_REV=464c8696
Finishing: Set vars
```

```
Starting: Docker pull
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/bf0524ed-7aa5-4b38-bcfa-33ce8d1a6ac5.sh
/home/vsts/work/_temp/bf0524ed-7aa5-4b38-bcfa-33ce8d1a6ac5.sh: line 2: unexpected EOF while looking for matching `''
##[error]Bash exited with code '2'.
Finishing: Docker pull
```

**Comment by Korijn** [comment]
Another data point, this also sometimes happens in another location in the script, with a different error:

```yaml
    - task: Bash@3
      displayName: Push Docker images
      inputs:
        targetType: inline
        script: |
          set -ex
          docker push ${{ parameters.image }}:dev-$(GIT_REV)
          docker push ${{ parameters.image }}:$(GIT_REV)
```

```
Starting: Push Docker images
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/25f0fe4d-9876-49dc-ab65-e8c8c5b39c62.sh
+ docker push '***/project/system:dev-ee9e0f3a
docker push ***/project/system:ee9e0f3a'
invalid reference format
##[error]Bash exited with code '1'.
Finishing: Push Docker images
```

Notice that dangling quote at the end of the line which has seemingly appeared out of nowhere: `docker push ***/project/system:ee9e0f3a'`
