### ISSUE TITLE
AzurePowerShell@4: blob property set stopped working

### ISSUE THREAD

**Issue by pkgw** [microsoft/azure-pipelines-tasks#14409]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell@4

## Environment
- Server - Azure Pipelines or TFS on-premises?

  - Azure Pipelines: aasworldwidetelescope/WWT org/project, build definition WorldWideTelescope.wwt-web-client; build number 20210217.1    

- Agent - Hosted or Private: 
    
    - Hosted: windows-latest VM

## Issue Description

I have a build task that modifies the content-type of a blob on an Azure Storage Account. The (abbreviated) definition is:

```yaml
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: '[elided]'
      azurePowerShellVersion: 'LatestVersion'
      scriptType: 'inlineScript'
      inline: |
        $ctxt = New-AzStorageContext -UseConnectedAccount -StorageAccountName "wwtwebstatic"
        $blob = Get-AzStorageBlob -Context $ctxt -Container '$web' -Blob "webclient/default.aspx"
        $blob.ICloudBlob.Properties.ContentType = "text/html"
        $blob.ICloudBlob.SetProperties()
```

This used to work, and it stopped working at some point in the past month or two. Nothing in my configuration has changed in that time.

### Error logs

The only output of interest is the error report:

```
##[error]The property 'ContentType' cannot be found on this object. Verify that the property exists and can be set.
```
