### ISSUE TITLE
Publish Pipeline Artifacts Task Ignores .artifactIgnore For File Share

### ISSUE THREAD

**Issue by dign17** [microsoft/azure-pipelines-tasks#14417]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishPipelineArtifact@1

## Environment
- Server - Azure Pipelines
- Agent - Private:
    - WIndows 10

## Issue Description
Using the following ignores .artifactsIgnore file due to execution of ROBOCOPY with default setting:

> Files: *

```
- task: PublishPipelineArtifact@1
   inputs:
     targetPath: '$(System.DefaultWorkingDirectory)'
     artifact: 'BuildArtifacts'
     publishLocation: 'filepath'
     fileSharePath: '\\path\to\fileshare'
```
The whole folder is unfortunately copied to destination.

If I use the default with _publishLocation: pipeline_ .artifactsIgnore file is correctly recognized.
```
- publish: $(System.DefaultWorkingDirectory)
   displayName: Publish Build Artifacts
   artifact: BuildArtifacts
```
Is it possible to only include files defined in .artifactsIgnore when publishing to a file share?
