### ISSUE TITLE
ManualValidation task doesn't send email notifications

### ISSUE THREAD

**Issue by SimonAlling** [microsoft/azure-pipelines-tasks#14422]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ManualValidation

## Environment
- Server: Azure Pipelines
- Agent: hosted

## Issue Description

I have this job:

```yaml
  - job:
    displayName: Manual validation
    pool: server
    timeoutInMinutes: 4320 # 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # 1 day
      inputs:
        notifyUsers: |
          12345678.contoso.onmicrosoft.com@emea.teams.ms
        instructions: 'Please validate the build configuration to resume.'
        onTimeout: 'resume'
```

It works insofar as I can choose to reject or resume in the web GUI – but I get no email notification. I've tried with my personal work email as well as a generated email for one of our Teams channels (which I have confirmed is working; shown in the above example). I have waited for several hours and also checked my Junk Email folder in OWA.

### Task logs

The ManualValidation task doesn't seem to log anything.

### Error logs

No errors logged.
