### ISSUE TITLE
UseDotNet@2 does not handle useGlobalJson well with netcore 5

### ISSUE THREAD

**Issue by Danthar** [microsoft/azure-pipelines-tasks#14437]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet@2

## Environment
- Server - Azure Pipelines
- Agent -Private: 
    
## Issue Description

When you define the UseDotNet@2 task to download the .NET core sdk based on the global.json. It does not work.

```
- task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              useGlobalJson: true
```

It errors out with the message that 5.0.x is not supported.

global json looks like this

```
{
  "sdk": {
    "version": "5.0.x"
  }
}
```

![image](https://user-images.githubusercontent.com/986519/108706620-27587580-750f-11eb-872d-3d6781eb82b4.png)

When you change the task definition to:

```
- task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              version: '5.0.x'

```

It works.
