### ISSUE TITLE
Python version used by py.exe does not match version configured by task UsePythonVersion

### ISSUE THREAD

**Issue by raspe88** [microsoft/azure-pipelines-tasks#14451]
*Type*: Bug or Feature, depending on your point of view

**Enter Task Name**: UsePythonVersion

## Environment
- Azure DevOps Pipelines
- Agent - Hosted: vs2017-win2016, windows-2019

## Issue Description

I'm writing this report on recommendation of the Microsoft Support (https://developercommunity2.visualstudio.com/t/pyexe-in-windows-agents-pointing-to-wrong-version/1323399)

Within the pipelines of Azure DevOps the `py.exe` does not call the Python version configured by the task `UsePythonVersion`.
This is a hindrance for executing code that e.g. includes a workaround for https://bugs.python.org/issue38905 using the `py.exe`.

**Steps to reproduce:**
Execute this pipeline in Azure DevOps:
```
strategy:
  matrix:
    win2016:
      imageName: 'vs2017-win2016'
    win2019:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7
    architecture: 'x64'

- bash: |
    python -c "import sys; print(sys.executable)"
    python -c "import subprocess; subprocess.run(['python', '-c', 'import sys; print(sys.executable)'], check=True)"
    python -c "import subprocess; subprocess.run('python -c \"import sys; print(sys.executable)\"', check=True, shell=True)"
    python -c "import subprocess; subprocess.run('py -c \"import sys; print(sys.executable)\"', check=True, shell=True)"
  displayName: 'Print python versions'
```

The output of the step with diplay name “Print python versions” will contain:
```
2021-01-28T07:29:40.8019617Z C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
2021-01-28T07:29:41.0524463Z C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
2021-01-28T07:29:41.2308643Z C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
2021-01-28T07:29:42.4727843Z C:\hostedtoolcache\windows\Python\3.9.1\x64\python.exe
```

As you can see, the call to the `py.exe` returns the `python.exe` of version `3.9.1` instead of `3.7.9`.

The observed behaviour of `py.exe` is basically the one you can observe on a system with multiple Python versions installed, but when running a task that configures a system to use a specific Python version I expect the system to behave as if it is the only Python version installed. This is e.g. needed when the test environment of a system should be close to the deployment environment.
