### ISSUE TITLE
Possible to do parallel pushes to Nuget feed with NuGetCommand task?

### ISSUE THREAD

**Issue by kirk-marple** [microsoft/azure-pipelines-tasks#14460]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGetCommand

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

## Issue Description

When using the NuGetCommand for pushing packages to an Azure Artifacts feed, I see it breaks up each package into a separate VstsNuGetPush call.

Given that we have ~20 packages to push, this is pretty slow when done serially.

Is there anyway to push in parallel to Azure Artifacts with this task, so we can speed up our builds?

```
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    feedsToUse: 'select'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Onboarding/onboarding-feed'
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    allowPackageConflicts: true
    verbosityPush: Normal

D:\a\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.179.0\VstsNuGetPush\0.19.0\tools\VstsNuGetPush.exe D:\a\1\a\{redacted}.2021.2.24.6.nupkg -Source https://pkgs.dev.azure.com/{redacted}/Onboarding/_packaging/cded099a-19c8-79a9-b26a-afc26ad51a38/nuget/v3/index.json -AccessToken *** -NonInteractive
```
