### ISSUE TITLE
Expression in Docker Task repository field not evaluated

### ISSUE THREAD

**Issue by msidave** [microsoft/azure-pipelines-tasks#14497]
https://github.com/microsoft/azure-pipelines-tasks/blob/4f1cfb92d79b4b10eadc2417b328c7cd977c06fd/Tasks/DockerV2/dockerbuild.ts#L26

Given a pipeline
with `System.TeamProject` = `MyProject`
and `Build.Repository.Name` = `MyRepo`
```
variables:
  - name: CONTAINER_REPOSITORY
    value: $[ lower(variables['System.TeamProject']) ]/$[ lower(variables['Build.Repository.Name']) ]

steps:
  - task: Docker@2
    displayName: 'Push an image'
    inputs:
      containerRegistry: <registry connection>
      command: buildAndPush
      repository: $(CONTAINER_REPOSITORY)
      tags: |
        $(Build.BuildNumber)

```

The docker task will fail with something like

```
invalid argument "<registry host>/MyProject/$[lower(variables['build.repository.name']):20210301.4" for "-t, --tag" flag: invalid reference format
```

It appears that expressions in the repository field are not evaluated.

**Comment by msidave** [comment]
The evaluation issue might be earlier
```
Pool: Azure Pipelines
Image: ubuntu-latest
Agent: Azure Pipelines 20
Started: Today at 2:45 PM
Duration: 20s

Job preparation parameters
Variables:
  PROJECT:
    Parsing expression: <lower(variables['System.TeamProject'])>
    Evaluating: lower(variables['System.TeamProject'])
    Expanded: lower('MyProject')
    Result: 'myproject'
  lower_repo_name:
    Parsing expression: <lower(variables['Build.Repository.Name'])>
    Evaluating: lower(variables['Build.Repository.Name'])
    Expanded: lower(Null)
    Result: ''
ContinueOnError: False
TimeoutInMinutes: 60
CancelTimeoutInMinutes: 5
Expand:
  MaxConcurrency: 0
  ########## System Pipeline Decorator(s) ##########
```
