### ISSUE TITLE
AzureWebApp web config template error after 1.184.0 upgrade (nodejs app)

### ISSUE THREAD

**Issue by irega** [microsoft/azure-pipelines-tasks#14542]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureWebApp

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppV1

## Environment
- Server - Azure Pipelines or TFS on-premises?

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/gsccanarias/Bot/_build/results?buildId=184

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Image: Ubuntu16
Agent: Hosted Agent

## Issue Description

After the automatic upgrade of AzureWebApp task from 1.182.0 to 1.184.0, a deploy of a nodejs app with a custom web config is not working. We guess it's trying to find the webconfig template in the incorrect path.

The task definition from our CD yaml:

```
- task: AzureWebApp@1
              displayName: "Deploy to App Service"
              inputs:
                azureSubscription: ${{ parameters.subscriptionId }}
                appName: $(webAppName)
                package: "$(Pipeline.Workspace)/server.zip"
                customWebConfig: "-Handler iisnode -NodeStartFile lib/index.js -appType node"
                appSettings: "
                  -WEBSITE_NODE_DEFAULT_VERSION 10.14.1 
                  -MicrosoftAppPassword $(appSecret)"
```

### Task logs

```
Starting: Deploy to App Service
==============================================================================
Task         : Azure Web App
Description  : Deploy an Azure Web App for Linux or Windows
Version      : 1.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurewebapptroubleshooting
==============================================================================
Got service connection details for Azure App Service:'xxx'
##[error]Error: Failed to generate web.config. Error: ENOENT: no such file or directory, open '/home/vsts/work/_tasks/AzureWebApp_18bde28a-8172-45cb-b204-5cef1393dbb1/1.184.0/node_modules/azure-pipelines-tasks-azurermdeploycommon/WebConfigTemplates/node'
App Service Application URL: http://xxx.azurewebsites.net
Finishing: Deploy to App Service
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

See above
