### ISSUE TITLE
Maven@3 does not fail task on test failures

### ISSUE THREAD

**Issue by mercer** [microsoft/azure-pipelines-tasks#14570]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@3

## Environment
Azure Pipelines: 
    - account name: censored

- Agent - Hosted or Private: 
    - private: ubuntu 18.04

## Issue Description

1. junit test fails
2. but task does not fail

```
- task: Maven@3
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/E2e/pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    goals: 'clean verify'
    options: '-Dtest=".*ApiTest" -Dsurefire.rerunFailingTestsCount=3'
    publishJUnitResults: true
    testResultsFiles: '$(system.defaultWorkingDirectory)/E2e/target/surefire-reports/TEST-*.xml'
  displayName: 'Execute All API Integration Tests'
  timeoutInMinutes: 10
```
Build is green after this.

![image](https://user-images.githubusercontent.com/95358/110766407-ceeadd00-825d-11eb-897f-22aa61397a7c.png)

### Task logs

N/A did not collect
