### ISSUE TITLE
Java tool installer task "EACCES: permission denied, mkdir '/builds"

### ISSUE THREAD

**Issue by estebanes22** [microsoft/azure-pipelines-tasks#14589]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: JavaToolInstaller@0  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      ```Azure Pipelines```

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ```ubuntu-latest```

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "11"
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
    jdkDestinationDirectory: "/builds/binaries/externals"
    cleanDestinationDirectory: true
```

### Task logs
```
Extracting archive to: /builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz
Creating destination folder: /builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz
##[error]Unable to create directory '/builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz'. EACCES: permission denied, mkdir '/builds'
##[error]Unable to create directory '/builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz'. EACCES: permission denied, mkdir '/builds'
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
##[error]Unable to create directory '/builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz'. EACCES: permission denied, mkdir '/builds'
##[error]Unable to create directory '/builds/binaries/externals/JAVA_HOME_11_X64_openjdk-11.0.2_linux-x64_bin_tar.gz'. EACCES: permission denied, mkdir '/builds'
```
