### ISSUE TITLE
Deploying Logic App flow using Azure Pipeline task "AzureResourceManagerTemplateDeployment@3"

### ISSUE THREAD

**Issue by LianaN** [microsoft/azure-pipelines-tasks#14585]
Hi,

I'm trying to automate the deployment of Logic App flow from the Azure DevOps IaC pipeline. To do so, I created manually the Logic App flow and tested it to be sure that there is no error. Then I downloaded the it as a code (JSON file). 

![image](https://user-images.githubusercontent.com/11301976/111074660-59447280-84e4-11eb-9c7c-21832f3fd89d.png)

Finally, I uploaded this JSON file into Azure DevOps repo and created the following job in YAML file: 

```
  jobs:
  - job: logicapp_deploy
    displayName: 'Logic App Deployment'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'templates/arm-templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: mytemplates

  - deployment: test_deployment
    displayName: 'Test Deployment'
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: mytemplates

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: <...>
              subscriptionId: <...>
              action: 'Create Or Update Resource Group'
              resourceGroupName: <...>
              location: westeurope
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/mytemplates/logicapp.template.json'
              csmParametersFile: '$(Pipeline.Workspace)/mytemplates/logicapp.parameters.json'
              overrideParameters: '-name logicAppTest -location westeurope'
              deploymentMode: Incremental
              deploymentName: 'deployedLogicApps'
```

When I run this YAML file, I get the following error:

```
ARM Service Connection deployment scope - Resource Group
Checking if the following resource group exists: my_rg.
(node:1859) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Resource group exists: true.
Creating deployment parameters.
The detected encoding for file '/home/vsts/work/1/mytemplates/logicapp.template.json' is 'utf-8'
The detected encoding for file '/home/vsts/work/1/mytemplates/logicapp.parameters.json' is 'utf-8'
There was an error while overriding 'name' parameter because of 'TypeError: Cannot read property 'type' of undefined', make sure it follows JavaScript Object Notation (JSON)
There was an error while overriding 'location' parameter because of 'TypeError: Cannot read property 'type' of undefined', make sure it follows JavaScript Object Notation (JSON)
Starting template validation.
Deployment name is deployedLogicApps
There were errors in your deployment. Error code: InvalidRequestContent.
##[error]The request content was invalid and could not be deserialized: 'Could not find member 'actions' on object of type 'Template'. Path 'properties.template.actions', line 1, position 155.'.
##[warning]Validation errors were found in the Azure Resource Manager template. This can potentially cause template deployment to fail. Task failed while creating or updating the template deployment.. Please follow https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax
Starting Deployment.
Deployment name is deployedLogicApps
There were errors in your deployment. Error code: InvalidRequestContent.
##[error]The request content was invalid and could not be deserialized: 'Could not find member 'actions' on object of type 'Template'. Path 'properties.template.actions', line 1, position 155.'.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
Finishing: Deploy Logic App
```

It looks like `task: AzureResourceManagerTemplateDeployment@3` does not support the format of a JSON file that I downloaded from Logic App, and neither it supports the schema `$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json`.

**Should I use any other Azure Pipelines task instead of `AzureResourceManagerTemplateDeployment@3`?**

The JSON file `logicapp.template.json` looks as follows:

```
{
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
        "Get_blob_content": {
            "inputs": {
                "host": {
                    "connection": {
                        "name": "@parameters('$connections')['azureblob']['connectionId']"
                    }
                },
                "method": "get",
                "path": "/datasets/default/files/@{encodeURIComponent(encodeURIComponent(uriPath(triggerBody()?['data'].url)))}/content",
                "queries": {
                    "inferContentType": true
                }
            },
            "metadata": {
                "JTJmZGV2cmVwb3J0cyUyZmRldmVsb3BtZW50cmVwb3J0LnBkZg==": ""
            },
            "runAfter": {},
            "type": "ApiConnection"
        },
        "Send_an_email_(V2)": {
            "inputs": {
                "body": {
                    "Attachments": [
                        {
                            "ContentBytes": "@{base64(body('Get_blob_content'))}",
                            "Name": "Test"
                        }
                    ],
                    "Body": "@triggerBody()?['LastModified']",
                    "Subject": "Test",
                    "To": "<>@gmail.com"
                },
                "host": {
                    "connection": {
                        "name": "@parameters('$connections')['office365']['connectionId']"
                    }
                },
                "method": "post",
                "path": "/v2/Mail"
            },
            "runAfter": {
                "Get_blob_content": [
                    "Succeeded"
                ]
            },
            "type": "ApiConnection"
        }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "parameters": {
        "$connections": {
            "defaultValue": {},
            "type": "Object"
        }
    },
    "triggers": {
        "When_a_resource_event_occurs": {
            "inputs": {
                "body": {
                    "properties": {
                        "destination": {
                            "endpointType": "webhook",
                            "properties": {
                                "endpointUrl": "@{listCallbackUrl()}"
                            }
                        },
                        "filter": {
                            "includedEventTypes": [
                                "Microsoft.Storage.BlobCreated"
                            ],
                            "subjectBeginsWith": "/blobServices/default/containers/devreports/"
                        },
                        "topic": "/subscriptions/b632876c-cd99-4be5-bb92-f3c4090d2ad1/resourceGroups/dataMinds_rg/providers/Microsoft.Storage/storageAccounts/datamindsaml1576913410"
                    }
                },
                "host": {
                    "connection": {
                        "name": "@parameters('$connections')['azureeventgrid_1']['connectionId']"
                    }
                },
                "path": "/subscriptions/@{encodeURIComponent('b632876c-cd99-4be5-bb92-f3c4090d2ad1')}/providers/@{encodeURIComponent('Microsoft.Storage.StorageAccounts')}/resource/eventSubscriptions",
                "queries": {
                    "x-ms-api-version": "2017-09-15-preview"
                }
            },
            "splitOn": "@triggerBody()",
            "type": "ApiConnectionWebhook"
        }
    }
}
```
