### ISSUE TITLE
Packer Task does not support "build_resource_group_name"

### ISSUE THREAD

**Issue by JamesMacClaranet** [microsoft/azure-pipelines-tasks#14590]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: PackerBuild@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: "Azure Pipelines"

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: "windows-latest"

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Unable to provide a "build_resource_group_name" in the additionalBuildParameters field. The "location" field is required for Packer to create the resource group however when supplying "build_resource_group_name" the pipeline will error with:

```bash
* Specify either a location to create the resource group in or an existing
build_resource_group_name, but not both.
```

Removing the "location" value and the pipeline will error with:

```bash
##[error]Error happened while initializing task: Error: Input required: location.
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anuragc617** [comment]
@JamesMacClaranet build_resource_group_name input is for using existing resource group for packer build. If you don't want to use existing resource group then give location and optionally add temp_resource_group_name which packer will create for building image and delete during clean-up.
For more reference check this https://www.packer.io/docs/builders/azure/arm#resource-group-usage
Closing this as it is not an issue in task.

**Comment by JamesMacClaranet** [comment]
@anuragc617 apologies for any confusion here.

The default Packer CLI supports build_resource_group_name when providing your own packer files yes, you are right. However, the Azure DevOps Task "PackerBuild@1" when using the build type of "builtin" to autogenerate the Packer files does not support providing an existing resource group for the build.

```yml
- task: PackerBuild@1
   inputs:
      templateType: 'custom'
```

The above snippet works fine since the build_resource_group_name is provided in the json file provided.

```yml
- task: PackerBuild@1
   inputs:
      templateType: 'builtin'
``` 

This snippet does not work since the Azure DevOps task does not accept the build_resource_group_name parameter.

The only parameters that seem to be supported are:

```yml
            - task: PackerBuild@1
              inputs:
                templateType: 'builtin'
                ConnectedServiceName: ''
                isManagedImage: true
                managedImageName: ''
                location: ''
                storageAccountName: ''
                azureResourceGroup: ''
                baseImageSource: ''
                baseImage: ''
                packagePath: ''
                deployScriptPath: ''
                imageUri: ''
                imageId: ''
```
