### ISSUE TITLE
[Bug] VSTestV2: collect code coverage throws errors after updating to VS Enterprise 16.9.1 and private agent to version 2.183.1

### ISSUE THREAD

**Issue by bwstaal** [microsoft/azure-pipelines-tasks#14594]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: VSTestV2

## Environment
- Azure Pipelines

- _Agent:_ private
    
_OS:_ Windows Server 2012 R2
_Agent Version:_ 2.183.1

## Issue Description

After updating Visual Studio to version 16.9.1 and all the build agents to version 2.183.1 on the CI server at my employer, collecting code coverage for a .Net 4.6.1 solution doesn't work anymore. Below are the settings of the VSTestV2 task and the error message that is being thrown. Updating the NuGet packages "MSTest.TestAdapter" and "MSTest.TestFramework" to version 2.2.2, including installing/updating any related NuGet packages unfortunately didn't help. I tried this, because according to the [release notes](https://github.com/microsoft/testfx-docs/blob/master/docs/releases.md), support for TestPlaform v16.9.1 was added.

**VSTest V2 'Test Assemblies' task settings:**
#Your build pipeline references an undefined variable named ‘BuildPlatform’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

```
steps:
- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\obj\**
    searchFolder: '$(Build.BinariesDirectory)'
    runOnlyImpactedTests: true
    runAllTestsAfterXBuilds: 10
    runInParallel: true
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: true
```
_BuildConfiguration:_ release
_BuildPlatform:_ any cpu

**Error message**

##[error]Data collector 'Code Coverage' message: Data collector 'Code Coverage' failed to provide initialization information. Error: System.ArgumentNullException: Value cannot be null.
##[error]Parameter name: first
##[error]   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
##[error]   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.GetEnvironmentVariables()
##[error]   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.SetTestExecutionEnvironmentVariables()
##[error]   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.GetEnvironmentVariables(Boolean& unloadedAnyCollector).
##[error]Data collector 'Test Impact' message: No diagnostics or data will be collected because the diagnostic data adapters did not initialize..
Blame: Attaching crash dump utility to process testhost.net461.x86 (3396).
Blame: Attaching crash dump utility to process testhost.net461.x86 (1340).
##[error]Testhost process exited with error: . Please check the diagnostic logs for more information.
##[error]Testhost process exited with error: . Please check the diagnostic logs for more information.
Blame: Attaching crash dump utility to process testhost.net461.x86 (4268).
##[error]Testhost process exited with error: . Please check the diagnostic logs for more information.
Blame: Attaching crash dump utility to process testhost.net461.x86 (5752).
##[error]Testhost process exited with error: . Please check the diagnostic logs for more information.
2.7669
6.5914
2.8132
... and so forth
