### ISSUE TITLE
Visual Studio Test (VSTest@2) does not upload Code Coverage

### ISSUE THREAD

**Issue by jrahlf** [microsoft/azure-pipelines-tasks#14593]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Azure Pipelines

## Issue Description
VSTest@2 should publish both test results and test coverage according to documentation. However, only the test results are published. See the pipeline settings below. According to the log, a `.coverage` file is generated.
Please note the test project in question is a native c++ test project. 

**Build pipeline**
```
pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - master

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'x86'
    configuration: 'Debug'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    platform: 'x86'
    configuration: 'Debug'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
  displayName: 'Run tests'
```

The tests are run correctly and the results are also collected correctly, as shown below. Coverage information is missing.
![image](https://user-images.githubusercontent.com/1239909/111284235-3a5af300-8640-11eb-9156-233ed8ca8a2f.png)

**test log**
![image](https://user-images.githubusercontent.com/1239909/111286085-1bf5f700-8642-11eb-9fef-e76809a4911d.png)
