### ISSUE TITLE
KubernetesManifest task does not replace container image when referenced by digest

### ISSUE THREAD

**Issue by vidarkongsli** [microsoft/azure-pipelines-tasks#14604]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: KubernetesManifestV0

## Environment

- Server - Azure Pipelines
- Agent - Hosted
    
## Issue Description

When an existing Kubernetes deployment contains a container image reference using the digest format, the container image reference is not updated by the task.

Given a deployment spec:
```
kind: Deployment
apiVersion: apps/v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    spec:
      containers:
        - name: foo-image
          image: >-
            bar.azurecr.io/foo-image@sha256:4b523e3b94d90dfaaa7e075d52f43be8407a32e68203a1678be659132f4e1393
```
And the step:

```
- task: KubernetesManifest@0
  inputs:
    action: deploy
    namespace: ${{ parameters.environmentName }}
    manifests: |
      $(deployFile)
      $(svcFile)
    imagePullSecrets: |
      devops-pullsecret-${{ parameters.environmentName }}
    containers: |
       bar.azurecr.io/foo-image:20210311.1
```

The container reference is not being replaced, as expected.
