### ISSUE TITLE
Enable alternative to service connection for AzureRmWebAppDeploymentV4

### ISSUE THREAD

**Issue by rorychatterton** [microsoft/azure-pipelines-tasks#14622]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureRmWebAppDeploymentV4  

## Environment
Azure Pipelines
- Account / Team Project / Build: N/A
- Agent - Hosted or Private: N/A

## Issue Description

We leverage Hashicorp Vault to manage short-lived secrets for deployments today in our environment.

We would like to be able to pass Subscription/Client ID/Client Secret/Tenant ID as parameters into the AzureRMWebAppDeployment task, so we can source credentials from Vault at deploy time, rather than leveraging a service credential. 

We would like to be able to do something like:

```
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          AzureClientID: <Client_ID>
          AzureSecretKey: <Secret_Key>
          AzureSubscriptionID: <Subscription_ID>
          AzureTenantID: <Tenant_ID>
```

That way, we can use a previous task to auto-generate the SPN through Vault, and pass that information as inputs.

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A
