### ISSUE TITLE
Recent breaking change now ignores SlotName and deploys straight to Production!

### ISSUE THREAD

**Issue by jmg48** [microsoft/azure-pipelines-tasks#14639]
This recent [change](https://github.com/microsoft/azure-pipelines-tasks/pull/14455/files) breaks existing behaviour in quite a dangerous way, by silently removing the `SlotName` setting if the `DeployToSlotOrASEFlag` setting is not supplied.

The [documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)is not super clear on the relationship between these settings, and up until this change a specified `SlotName` was respected if supplied, regardless of the value of `DeployToSlotOrASEFlag`

Consider an existing pipeline yaml script which supplies a `SlotName `but no `DeployToSlotOrASEFlag`, in order to deploy to a staging slot as a prelude to final testing before swapping that slot into production:

```
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: ${{parameters.subscription}}
      appType: functionApp
      appName: ${{parameters.app}}    
      slotName: ${{parameters.slot}}
      package: '$(System.ArtifactsDirectory)/drop/netcoreapp${{parameters.netCoreVersion}}'
```

This change means that the same script will now have the `SlotName` parameter silently cleared and the deployment will now be direct to production!

My strong preference, if it is felt that there is a need to enforce that `DeployToSlotOrASEFlag` is supplied along with `SlotName`, would be to have the script fail with a validation error, rather than silently ignore `SlotName`. This is especially because silently altering the behaviour of scripts that previously deployed to a slot, to deploy direct to production, is likely to have serious implications.
