### ISSUE TITLE
AzureResourceManagerTemplateDeployment fails on multiline strings

### ISSUE THREAD

**Issue by SDedik** [microsoft/azure-pipelines-tasks#14645]
## Required Information
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Consider following very minimal ARM template `poc.json`:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/subscriptionDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "parameter1": {
            "type": "string",
            "defaultValue": "abc",
            "metadata": {
                "description": "very long
                and multiline
                description"
            }
        }
    },
    "functions": [],
    "variables": {},
    "resources": [],
    "outputs": {}
}
```
and Azure Pipeline to run it:
```
trigger: none

pool: 
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: Subscription
    azureResourceManagerConnection: 'my service connection 1'
    subscriptionId: 40f2d467-c27b-4ded-a7bc-82dc0b95cbb2
    templateLocation: Linked artifact
    csmFile: poc.json
    location: eastus
```
Pipeline fails with the following error message 
**##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Error: Ensure the Template file ( '/home/vsts/work/1/s/poc.json' ) is valid. Task failed while parsing with following error: Unexpected token 
 in JSON at position 321**

Running the template manually from PowerShell like this works without any problems `New-AzSubscriptionDeployment -Location 'eastus' -TemplateFile .\poc.json`

As soon as the parameter description in the ARM template is changed from multiline string to single line like so
```
        "parameter1": {
            "type": "string",
            "defaultValue": "abc",
            "metadata": {
                "description": "single line description"
            }
        }
```
the pipeline task works as expected
