### ISSUE TITLE
PublishCodeCoverageResults@1 - Displays Code Coverage only after Deployment Jobs have been Approved

### ISSUE THREAD

**Issue by hannahchan** [microsoft/azure-pipelines-tasks#14640]
I have a pipeline with three stages. In the first stage I build and test my application and collect code coverage. In the last stage, I have a deployment job targeting an environment that requires approval.

When my pipeline runs, the first and second stage complete successfully and then waits for approval for the last stage. At this point I cannot see the Code Coverage tab even though this task has completed successfully in the first stage.

Only when I approve and the last stage runs to completion I am able to see the Code Coverage tab. I would like to see the Code Coverage before I approve.

The task I am referring to is `PublishCodeCoverageResults@1`. I'm using Azure DevOps Pipelines with Hosted Agents.

I have replicated this issue here in my test project - https://github.com/hannahchan/AzureDevOpsTest.

My pipeline file currently looks like this and is checked in at the root of the above project:

```yaml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: publish
    displayName: Publish
    jobs:
      - job: publish
        displayName: Publish
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore .NET Tools
            inputs:
              command: custom
              custom: tool
              arguments: restore

          - task: DotNetCoreCLI@2
            displayName: Run Cake Build Script
            inputs:
              command: custom
              custom: cake
              arguments: --Target=Publish

          - task: PublishTestResults@2
            displayName: Publish Test Results
            inputs:
              failTaskOnFailedTests: true
              mergeTestResults: true
              testResultsFiles: Tests/**/TestResults/*.trx
              testResultsFormat: VSTest
              testRunTitle: Integration and Unit Tests

          - task: PublishCodeCoverageResults@1
            displayName: Publish Code Coverage Results
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: Artifacts/CoverageReports/Combined/Cobertura.xml
              failIfCoverageEmpty: true

  - stage: staging
    displayName: Deploy to Staging
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment: Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - script: echo "Deploying to Staging"
                - script: echo "Deployed to Staging"

  - stage: production
    displayName: Deploy to Production
    jobs:
      - deployment: production
        displayName: Deploy to Production
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - script: echo "Deploying to Production"
                - script: echo "Deployed to Production"
```
