### ISSUE TITLE
The app service doesn't restart to use the latest deployment asset by using `AzureRmWebAppDeployment@4`

### ISSUE THREAD

**Issue by 928PJY** [microsoft/azure-pipelines-tasks#14691]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: AzureRmWebAppDeployment@4

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure pipeline: https://ceapex.visualstudio.com/Engineering/_build/results?buildId=407258&view=results

- Agent - Hosted or Private: 
    
    Pool: Azure Pipelines
    Image: windows-latest
    Agent: Hosted Agent

## Issue Description

When we use the task `AzureRmWebAppDeployment@4` to deploy our app service, it runs successfully, but the app service doesn't restart, so the running service is still using the old version package. The new package can only be used until we manually restart the app service. we have confirmed that the new package has been uploaded successfully to the directory `site/wwwroot` by the kudu. but in the `Prcoess explorer`, our module used by the w3wp.exe is still the old version.
![image](https://user-images.githubusercontent.com/17958546/113674153-74be2a00-96ec-11eb-83b8-62018f70bdd8.png)

**Comment by AmrutaKawade** [comment]
@928PJY Can you share what app service type and additional deployment options you are using?

**Comment by 928PJY** [comment]
For sure, here are the detail configuration of the step:
```yaml
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: Deploy To Staging Slot'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscriptionPPE)
    appType: webApp
    WebAppName: $(webAppNamePPE)
    deployToSlotOrASE: true
    ResourceGroupName: $(resourceGroupNamePPE)
    SlotName: 'staging'
    Package: '$(Pipeline.Workspace)/Docs.VideoEncoding.Artifact/DocsVideoEncodingService'
    UseWebDeploy: true
    RemoveAdditionalFilesFlag: true
    RenameFilesFlag: true
```

**Comment by AmrutaKawade** [comment]
@928PJY are you using AzureRmWebAppDeployment@4 or AzureRmWebAppDeployment@3?
inputs which you are using are compatible to AzureRmWebAppDeployment@3. 

Can you use settings option in yaml?

![image](https://user-images.githubusercontent.com/65217380/113740307-36416300-971e-11eb-88b7-ef0d3967b555.png)

**Comment by 928PJY** [comment]
@AmrutaKawade I am using `AzureRmWebAppDeployment@4`, just like what I paste in the last comments.

**Comment by AmrutaKawade** [comment]
@928PJY for `AzureRmWebAppDeployment@4` use like this. inputs you are using are compatible to `AzureRmWebAppDeployment@3` 

```yaml
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: Deploy To Staging Slot'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscriptionPPE)
    appType: 'webApp'
    WebAppName: $(webAppNamePPE)
    deployToSlotOrASE: true
    ResourceGroupName: $(resourceGroupNamePPE)
    SlotName: 'staging'
    packageForLinux: '$(Pipeline.Workspace)/Docs.VideoEncoding.Artifact/DocsVideoEncodingService'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    TakeAppOfflineFlag: false
    RemoveAdditionalFilesFlag: true
    ExcludeFilesFromAppDataFlag: false
```
