### ISSUE TITLE
parameter Machinenames is not optional in WindowsMachineFileCopy@2

### ISSUE THREAD

**Issue by Anderman** [microsoft/azure-pipelines-tasks#14714]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

*Type*: Bug

WindowsMachineFileCopy@2

## Environment
Devops 2020

### private agent

windows 2019 datacenter
agent:'2.170.1'

## Issue Description
Machinenames is optional according the documentation but when when not supplied an error is generated:

``` yaml
# Windows machine file copy
# Copy files to remote Windows machines
- task: WindowsMachineFileCopy@2
  inputs:
    sourcePath: 
    #machineNames: # Optional
    #adminUserName: # Optional
    #adminPassword: # Optional
    targetPath: 
    #cleanTargetBeforeCopy: false # Optional
    #copyFilesInParallel: true # Optional
    #additionalArguments: # Optional
```
![image](https://user-images.githubusercontent.com/1858745/114279109-3fd70d80-9a33-11eb-9ae2-87cf7abb6e26.png)

I like to use robo copy but local only
