### ISSUE TITLE
Npm@1 Publish support --dry-run with Azure Feed

### ISSUE THREAD

**Issue by leepowelldev** [microsoft/azure-pipelines-tasks#14774]
Hi

We have a step in our pipeline like this:

```
 - task: Npm@1
   displayName: Publish
   inputs:
     command: publish
     publishRegistry: useFeed
     publishFeed: $(OUR_NPM_REGISTRY)
```

However we'd like the ability on occasions to use `--dry-run` flag when we're testing our pipelines. Could this be considered as a new feature?
