### ISSUE TITLE
xcode task: test-without-building

### ISSUE THREAD

**Issue by ingemarson** [microsoft/azure-pipelines-tasks#14779]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: XCode Task: test-without-building

## Environment
Azure Pipelines, Hosted agent

## Issue Description

Is it possible to run: **test-without-building** with the provided XCode Task? If not, is it planned to support in near future?

**Comment by schnaser** [comment]
I have this question as well.

**Comment by KonstantinTyukalov** [comment]
XCode task is wrapping the `xcodebuild` CLI tool, which means you are free to make things that can `xcodebuild`.
As I tested, there are no blockers to set up to XCode task of resolving `test-without-building` action.
Here's my test pipeline snippet:

```yaml

## Firstly builds the tests without running them
- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    sdk: 'iphonesimulator'
    xcodeVersion: '11'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'

## Runs the previously built tests
- task: Xcode@5
  inputs:
    actions: 'test-without-building'
    sdk: 'iphonesimulator'
    xcodeVersion: '11'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'
```

If it's helpful to you, I was guided by this documentation: https://developer.apple.com/library/archive/technotes/tn2339/_index.html

If you run into problems related to our task when making the `test-without-building` action, feel free to ask additional questions or create a related issue
