### ISSUE TITLE
Clang error in gRPC-Core and xcodebuild failed with return code: 65

### ISSUE THREAD

**Issue by psdewar2** [microsoft/azure-pipelines-tasks#14775]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Xcode@5  

## Environment
- Server - Azure Pipelines
    - Account name: psdewar2@live.com
    - Organization: hacksnextdoor
    - Project name: Lyrist
    - Build: #20210425.10 Update pipeline-ios.yml for Azure Pipelines

- Agent - Hosted 
    - Not sure where to find agent queue name. Pipeline name is **Lyrist CI-ios**.

## Issue Description
Build succeeds in Xcode but fails in the pipeline whether or not the legacy build system is used. I have also tried Debug / Release configurations, manual signing by following the instructions for [iOS apps](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app), and auto signing. Nothing seems to work and I'm not sure what's missing.

### Relevant pipeline steps
```
  - task: InstallAppleCertificate@2
    displayName: Install Apple Certificate
    inputs:
      certSecureFile: 'dev-cert.p12'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    displayName: "Install Apple provisioning profile"
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'dev.mobileprovision'

  - task: CocoaPods@0
    displayName: 'Install iOS dependencies'
    inputs:
      workingDirectory: 'ios'

  - task: Xcode@5
    displayName: 'Build iOS'
    inputs:
      actions: 'build'
      configuration: 'Debug'
      sdk: 'iphoneos'
      xcWorkspacePath: 'ios/Lyrist.xcworkspace'
      scheme: 'Lyrist'
```

### Task logs
Raw logs: https://dev.azure.com/hacksnextdoor/f0e18470-e914-4b62-a081-888527664ce6/_apis/build/builds/217/logs/14
Zipped logs: [logs_217.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6371470/logs_217.zip)

### Error logs
```
    ...
    The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'gRPC-Core' from project 'Pods')
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Lyrist-czsdykdfnicfwodqkmhliduillpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/armv7/xds_load_balancer_api.o /Users/runner/work/1/s/ios/Pods/gRPC-Core/src/core/ext/filters/client_channel/lb_policy/xds/xds_load_balancer_api.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```
