### ISSUE TITLE
.NET 5 Function Deployment

### ISSUE THREAD

**Issue by DillonAd** [microsoft/azure-pipelines-tasks#14796]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines
   - Account Name: Momentum3
   - Project Name: Customer-Cloverleaf  
   - Build Definition Name: Web
   - Build Number: 12150

- Agent - Hosted or Private: 
   - Private Agent
   - Agent Pool: Default
   - OS: Windows Server 2016
   - Agent Version: 2.185.1

## Issue Description

My team is using the new [isolated functions](https://github.com/Azure/azure-functions-dotnet-worker) and trying to publish these .NET 5 functions via Azure Pipelines. When a deploy occurs via Azure Pipelines, the functions are not registered in the Azure portal and are not able to execute. The Azure Function Core Tools perform the publish successfully but having to publish our functions outside of the automation is less than ideal.

Are there configuration or app settings that need to be specified to make this deployment successful or are the isolated functions not currently supported since the functionality is so new?

Thanks in advance!

### Task logs
I can provide these logs if necessary.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
N/A

**Comment by Kumar-Ashwin-Hubert** [comment]
Facing the same issue.
I would like to use the `AzureFunctionApp@1` task to deploy .Net 5 Functions instead of using the Azure Function core tools in the deployment pipelines. 
Any updates on this @nadesu.

**Comment by Kumar-Ashwin-Hubert** [comment]
@DillonAd I was able to successfully deploy Azure Function .Net 5 isolated function using the `AzureFunctionApp@1` task without any configuration changes. 

But can you confirm how you had created the Azure Function resource ? 
Using ARM templates ? If so please verify the following are set rightly in the ARM template:

- `linuxFxVersion` inside `siteConfig` is set to `"DOTNET-ISOLATED|5.0"`
- `FUNCTIONS_WORKER_RUNTIME` appSettings  is set to `"dotnet-isolated"`

For the  `AzureFunctionApp@1` task this is what I had used :
```yaml
  - task: AzureFunctionApp@1
    displayName: 'Deploying to function'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnectionName }}'
      appType: functionAppLinux
      appName: 'YOUR-APP-NAME'
      package: '$(Pipeline.Workspace)/drop/DROP-PACKAGE.zip'
```

**Comment by Kumar-Ashwin-Hubert** [comment]
@DillonAd I was able to successfully deploy Azure Function .Net 5 isolated function using the `AzureFunctionApp@1` task without any configuration changes. 

But can you confirm how you had created the Azure Function resource ? 
Using ARM templates ? If so please verify the following are set rightly in the ARM template for a **Linux** Server:
- `linuxFxVersion` inside `siteConfig` is set to `"DOTNET-ISOLATED|5.0"`

And ensure the following appSettings is rightly set for **Linux** as well as **Windows** server
- `FUNCTIONS_WORKER_RUNTIME` appSettings  is set to `"dotnet-isolated"`

For the  `AzureFunctionApp@1` task this is what I had used :
```yaml
  - task: AzureFunctionApp@1
    displayName: 'Deploying to function'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnectionName }}'
      appType: functionAppLinux
      appName: 'YOUR-APP-NAME'
      package: '$(Pipeline.Workspace)/drop/DROP-PACKAGE.zip'
```

**Comment by DillonAd** [comment]
@Kumar-Ashwin-Hubert Thanks for the information! We aren't using ARM templates quite yet, but I did specify those values (or at least what I perceived to be the equivalent for a Windows function) in the function definition and I'm still having the same issue of the functions not loading properly after the deployment. I checked the function's settings from the Azure CLI and all of those settings are being set correctly. 

Here is the YAML that I am using for this task:

```yml
- task: AzureFunctionApp@1
  displayName: 'Azure functions app deploy'
  inputs:
    azureSubscription: '$(Deploy.FunctionsSubscription)'
    appType: functionApp
    appName: '$(Deploy.FunctionAppName)'
    package: '$(Pipeline.Workspace)/functions'
    appSettings: >-
        -FUNCTIONS_WORKER_RUNTIME dotnet-isolated
        -FUNCTIONS_WORKER_RUNTIME_VERSION 5.0
        -languageWorkers:dotnet5:workerDirectory .
    configurationStrings: '-netFrameworkVersion v5.0 -windowsFxVersion DOTNET-ISOLATED|5.0'
```
