### ISSUE TITLE
AzureWebAppContainerV1 incorrectly sets 'windowsFxVersion' for linux container

### ISSUE THREAD

**Issue by jbowtie** [microsoft/azure-pipelines-tasks#14805]
## Required Information

*Type*: Bug

*Task Name*: AzureWebAppContainer 

## Issue Description

When a Linux Web App with kind: `app,linux,container` does not have linuxFxVersion set (as can happen with an ARM Template), the AzureWebAppContainer incorrectly sets windowsFxVersion instead. This is difficult to debug as the deployment succeeds but the site does not come up.

However, if linuxFxVersion is set to a placeholder value (such as "DOCKER|alpine") it will correctly be updated. (So there is a workaround).

Explicitly setting a placeholder value is undesirable for many workflows. For example:

* Run an ARM template to ensure the web app exists (this would overwrite the linuxFxVersion to be the placeholder; normally in incremental mode you would not expect the resource to change)
* ...additional steps... (failure here leaves the placeholder running!)
* Run this step to deploy the latest version of a docker image (this would overwrite the linuxFxVersion again)

Since the kind reliably indicates the OS, it seems very odd that the wrong configuration setting is updated.

### Task logs

```
Trying to update App Service Configuration settings. Data: {"appCommandLine":null,"windowsFxVersion":"DOCKER|p***:latest"}
Updated App Service Configuration settings.
Restarting App Service: app-...
App Service 'app-...' restarted successfully.
```

**Comment by AmrutaKawade** [comment]
are you sure kind property is set to `app,linux,container` ?

**Comment by jbowtie** [comment]
Yes, I can confirm this.

I've done some experimentation - I think the heuristic being followed is "if linuxFxVersion is set, update that, otherwise update windowsFxVersion" - I don't think the isLinux flag is being passed down to whatever common code is actually setting this property.

**Comment by AmrutaKawade** [comment]
Can you set `system.debug=true` in variables and run pipeline again?
share detail logs

**Comment by jbowtie** [comment]
I'll have to set up a new pipeline to repro but will make some time to do so.

**Comment by KasperPurunen** [comment]
I'm having the same issue. We are setting the kind to `app,linux,container` as well but the logs from Azure DevOps says the following when deploying with the task: `{"appCommandLine":null,"windowsFxVersion":"DOCKER| ... " }`

**Comment by AmrutaKawade** [comment]
@KasperPurunen can you share debug logs?

**Comment by jbowtie** [comment]
Here is the debug log for the deploy azure resources stage:
[azure-resource-log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6587902/azure-resource-log.txt)

Here is the debug log for the AzureWebAppContainer stage:
[web-container-log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6587900/web-container-log.txt)

**Comment by jbowtie** [comment]
@AmrutaKawade Were those logs helpful?  Do you need any more detail?

**Comment by abdok96** [comment]
Any plans to solve this issue soon?

**Comment by PhilipsonJoseph** [comment]
@jbowtie , @KasperPurunen For us Whenever app is created without **linuxFXVersion** in ARM template, app kind is set to as  **app,linux** and not **app,linux,container**  Can any one of you confirm this behavior ?,

**Comment by PhilipsonJoseph** [comment]
Due to inactivity we are closing this. If it is still exists please raise a new bug

**Comment by SteveLillis** [comment]
@PhilipsonJoseph This issue is still outstanding.  As you note above, any ARM template deployed without `linuxFxVersion` strips `container` from the `kind` so `app,linux,container` becomes `app,linux`.  This is easily avoided by not using an exact string match for the OS type lookup, but instead case-insensitively searching "linux" in the `kind`.

**Comment by cfauchere** [comment]
How can this issue be swept under the carpet? This is clearly blocking deployment of Linux container.

**Comment by nadesu** [comment]
+ @v-nagarajku

**Comment by SteveLillis** [comment]
@nadesu @PhilipsonJoseph @v-nagarajku do you know when we might see a review for this one line correction and an update to the task?

I ask as this is currently blocking my team from being able to use this task as intended, and we will need to make alternative plans if we think this may take some time to make it's way out.

Thank you.

**Comment by SteveLillis** [comment]
For anyone still struggling with this issue, we worked around it by not using the task at all and instead setting `linuxFxVersion` in the ARM just for the staging slot, while continuing to leave `linuxFxVersion` unset for the production slot.

This allowed us to get the staging slot set up correctly with the latest image without disrupting the production slot, perform our testing, etc. then we swap slots as per the usual process.

**Comment by eosho** [comment]
I can verify I have linuxFxVersion set to "DOCKER|<arcInfo>:latest". Web app kind is also set to "app,linux,container". Upon using the task, it sets both linuxFxVersion and windowsFxVersion.

**Comment by cfauchere** [comment]
I am using Azure CLI `az webapp config container set` as a workaround

**Comment by onionhammer** [comment]
I just ran into this naturally, tearing my hair out for hours trying to figure out whats going on

**Comment by CMeeg** [comment]
I've hit this issue recently also. I have some Bicep templates that I am using to deploy App Service resources (and other things) within a pipeline, and do not want to set `linuxFxVersion` in the Bicep template because I want that to happen later on in the pipeline via the `AzureWebAppContainer` task.

If I don't set `linuxFxVersion` when the App Service is created the `AzureWebAppContainer` task ends up setting `windowsFxVersion` i.e. the task output includes: `Trying to update App Service Configuration settings. Data: {"appCommandLine":null,"windowsFxVersion":"DOCKER|undefined"}`.

As per the issue description, setting a placeholder `linuxFxVersion` on the App Service does workaround this, but it's not something I want to maintain.

I have also now switched to use `az webapp config container set` as per [this comment](https://github.com/microsoft/azure-pipelines-tasks/issues/14805#issuecomment-1082513278), and that's setting `linuxFxVersion` fine and has unblocked me for now.

In case it's helpful to have an example, I have switched this:

```yml
- task: AzureWebAppContainer@1
  displayName: 'Deploy to web app' 
  inputs:
    azureSubscription: '$(ServiceConnection)'
    appName: '$(WebAppName)'
    multicontainerConfigFile: '$(Pipeline.Workspace)/path/to/docker-compose.yml'
    deployToSlotOrASE: true
    resourceGroupName: '$(ResourceGroupName)'
    slotName: '$(WebAppDeploySlotName)' 
```

To this:

```yml
- task: AzureCLI@2
  displayName: 'Deploy to web app'
  inputs:
    azureSubscription: '$(ServiceConnection)'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az webapp config container set --name "$(WebAppName)" --resource-group "$(ResourceGroupName)" --multicontainer-config-file "$(Pipeline.Workspace)/path/to/docker-compose.yml" --multicontainer-config-type COMPOSE --slot "$(WebAppDeploySlotName)"
```

**Comment by vidarkongsli** [comment]
Having had a brief look at the source code for this task, it seems to me that it always looks at the main web site setting when determining whether it is a Linux service, even if you are deploying to a deployment slot: 
https://github.com/microsoft/azure-pipelines-tasks/blob/7adc2fa8639ba6cf8a18dbe3d0bd93d78c641c9d/Tasks/AzureWebAppContainerV1/taskparameters.ts#L49
This seems to be the reason for this task failing in the my situation.

**Comment by ph-ict** [comment]
We've also just hit this after spending the afternoon trying to work out why our DevOps deployed image wasn't working. Same issue.

**Comment by mortenbock** [comment]
I just spent an hour debugging this as well. The `kind` was set to `app,linux` and that seemingly caused the image to be written to `WindowsFxVersion`

**Comment by mortenbock** [comment]
Just FYI, I switche to the `AzureRmWebAppDeployment@4` task in DevOps, that does it correctly:

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to Azure
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: ${{ parameters.azure_subscription }}
        appType: 'webAppContainer'
        WebAppName: ${{ parameters.app_service_name }}
        DockerNamespace: ${{ parameters.dockerNamespace }}
        DockerRepository: ${{ parameters.dockerRepository }}
        DockerImageTag: ${{ parameters.dockerImageTag }}

**Comment by Guilhermeslucas** [comment]
> 

What are you setting to? I am having the same issue!

**Comment by Spencerooni** [comment]
Just spent a day trying to understand why my deployed linux container wasn't working. How the container deploy task does not work for linux is super confusing. It wasn't until I did `az resource show --ids <resource id>` and compared all the attributes of a web app deployed via manually selecting the image vs one I deployed using the pipeline, that I could see the windowsFxVersion being set in the one using this task... @mortenbock your solution worked perfectly for me.

**Comment by crow-ua** [comment]
This one also caused me some grief lately (situation is complicated by the fact I'm using Terraform for IaC and deploying compose instead of single dockerfile). @CMeeg's workaround worked, but it would be interesting to know proper way to handle this.
@PhilipsonJoseph any insights on this?

**Comment by ajpogue** [comment]
Was this resolved? It is still occurring, and we encountered it this week.

**Comment by laksharun** [comment]
Spent an entire day troubleshooting the issue of why the docker image would not run a Linux web app when deployed through the pipeline. Finally found the difference in the `WindowsFxVersion` value via https://resources.azure.com when comparing the settings with an app that was deployed manually. It finally worked after using the `AzureRmWebAppDeployment@4` task as suggested by @mortenbock.

Has there been any updates on this issue? If not, I believe at least the documentation should be updated with this.

**Comment by chrisflem** [comment]
A colleague of mine found a good workaround for this using bicep templates.
**First ensure the web app:**
````yaml
resource sites_WebService 'Microsoft.Web/sites@2021-03-01' = {
  name: webServiceName
  location: location
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    enabled: true
    reserved: true
.......omittet for brevity
  }
  tags: tags
}
````

Then set the config, where we either use the existing value, or set a placeholder
````yaml
resource sites_app_invoemailtrackingapi_config 'Microsoft.Web/sites/config@2022-09-01' = {
  parent: sites_WebService
  name: 'web'
  properties: {
    netFrameworkVersion: 'v6.0'
    vnetRouteAllEnabled: true
    acrUseManagedIdentityCreds: true
    alwaysOn: true
    linuxFxVersion: empty(sites_WebService.properties.siteConfig.linuxFxVersion) || sites_WebService.properties.siteConfig.linuxFxVersion == null ? 'DOCKER|alpine' : sites_WebService.properties.siteConfig.linuxFxVersion
    minTlsVersion: '1.2'
  }
}
````
This will prevent the app from restarting and using the wrong image, since there is no changes.
On the first time creation of the web app, the placeholder will be used, ensuring the web app is created correctly
