### ISSUE TITLE
DownloadBuildArtifacts@0 error when inside container

### ISSUE THREAD

**Issue by Ravio1i** [microsoft/azure-pipelines-tasks#14812]
When using DownloadBuildArtifacts to download artifacts in a [container job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops) the `getBuildAPI` cannot download the artifact.

Without using a container it works. Working without a container is no option for me.

## Required Information

**Type**: **Bug**
**Task Name**:  `DownloadBuildArtifacts@0`

## Environment
- Server: Azure DevOps Server 2019
- Agent: Self-Hosted Linux 
- Os dist: Ubuntu 18.04
- Agent.Version 2.184.2

## Issue Description

This works

```yaml
- job: ...
  pool: ...
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Build.SourcesDirectory)'
```

This doesnt work:

```yaml
- job: ...
  pool: ...
  container:
    image: debian:buster
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Build.SourcesDirectory)'
```

### Task logs

[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6433045/logs.zip)

### Error logs

```bash
...
##[error]Failed in getBuildApi with error: Error: tunneling socket could not be established, statusCode=502
...
##[error]Error: tunneling socket could not be established, statusCode=502
```

**Comment by Ravio1i** [comment]
The container seems  to pick up somwehre a proxy setting. As a workaround the proxy settings for a container can be set to `""`

```yaml
  env:
     HTTP_PROXY: ""
     HTTPS_PROXY: ""
```

A job could look like this:

```yaml
- job: ...
  pool: ...
  container:
    image: debian:buster
    env:
       HTTP_PROXY: ""
       HTTPS_PROXY: ""
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Build.SourcesDirectory)'
```

**Comment by doeringp** [comment]
You can even unset the http proxy only for this single task:

```yaml
- download: current
  artifact: drop
  env:
    HTTP_PROXY: ''
    HTTPS_PROXY: ''
```
