### ISSUE TITLE
Bug on Kubernetes manifest task

### ISSUE THREAD

**Issue by maxisam** [microsoft/azure-pipelines-tasks#14822]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  Kubernetes manifest task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

Azure Pipelines: 
millerslab 
LabSuppor
buildId=1298

- Agent - Hosted or Private: 
    - private agent: ubuntu 20.04 

## Issue Description

The findPath works differently between signal line and multiple line

```yml
                - task: KubernetesManifest@0
                  displayName: Deploy To K8S
                  inputs:
                    kubernetesServiceConnection: "production-linux"
                    namespace: "web-app"
                    manifests: |
                      "$(System.ArtifactsDirectory)/drop/!(XXXXX).yml"
```

##[error]No manifest file(s) matching /home/*****/myagent/_work/10/s/"/home/*****/myagent/_work/10/a/drop/!(xxxxx).yml" was found.

https://dev.azure.com/millerslab/LabSupport/_build/results?buildId=1299&view=logs&j=d77ff9be-8983-589d-bd24-5a29c66a7d42&t=39aa7e07-a442-5565-39a3-98e9288106b0&l=13

```yml
                - task: KubernetesManifest@0
                  displayName: Deploy To K8S
                  inputs:
                    kubernetesServiceConnection: "production-linux"
                    namespace: "web-app"
                    manifests:  "$(System.ArtifactsDirectory)/drop/!(*****).yml"
```

[debug]findPath: '/home/*****/myagent/_work/10/a/drop'
https://dev.azure.com/millerslab/LabSupport/_build/results?buildId=1298&view=logs&j=d77ff9be-8983-589d-bd24-5a29c66a7d42&t=39aa7e07-a442-5565-39a3-98e9288106b0&l=142

I think signal line behaves correctly.
