### ISSUE TITLE
NodeTool@0 Node & NPM version not matched

### ISSUE THREAD

**Issue by Fitmavincent** [microsoft/azure-pipelines-tasks#14824]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  NodeTool@0, NodeTool

## Environment
- Server - Azure Pipelines
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - Account name: TandmInternationa, 
    - Project: Tandm, 
    - Pipeline: Tandm-Infra-CDK-PR
    - Build Number: 20210509.6

- Agent - Hosted or Private: 
    
    - Hosted Agent: 20210509.6 Tandm-Infra-CDK-PR

## Issue Description

Specify Node version in NodeTool, but Node JS and NPM version are not correct. 

```yml
  - task: NodeTool@0
    inputs: 
      versionSpec: '16.x'
    displayName: "Install NodeJS"
  - script: | 
      echo "Check version"
      which node
      echo "Node Version: " 
      sudo node -v
      echo "NPM Version: " 
      sudo npm -v
    displayName: "Node Version check"
```

Build output: 
```
==============================================================================
Downloading: https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.gz
Extracting archive
/usr/bin/tar xC /home/vsts/work/_temp/40945baf-cceb-41a2-9104-8aef5e655a15 -f /home/vsts/work/_temp/512f0d65-c548-432c-8f52-39dcd7a624ff
Caching tool: node 16.1.0 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/node/16.1.0/x64/bin
Finishing: Install NodeJS
```

```
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/2304f45a-19e6-4960-b70c-228dea5ff8b5.sh
Check version
/opt/hostedtoolcache/node/16.1.0/x64/bin/node
Node Version: 
v14.16.1
NPM Version: 
6.14.12
Finishing: Node Version check
```
