### ISSUE TITLE
AzureKeyVault - SecretsFilter error (EditableOptions)

### ISSUE THREAD

**Issue by stefankip** [microsoft/azure-pipelines-tasks#14844]
**Question, Bug, or Feature?**  
*Type*: Bug

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
The `AzureKeyVault@1` task has a parameter called `SecretsFilter`. If I enter the name of a secret, I get an error:
`Value is not accepted. Valid values: "EditableOptions".`
The task how I defined it:
```
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'my-subscription'
    KeyVaultName: 'my-kv'
    SecretsFilter: 'some-secret-name'
    RunAsPreJob: false
```
