### ISSUE TITLE
Provide a way to suppress `ExactVersionNotRecommended` warnings

### ISSUE THREAD

**Issue by G-Rath** [microsoft/azure-pipelines-tasks#14869]
*Type*: Feature
**Task Name**: `UseRubyVersion@0`

## Issue Description

#13513 implemented a `ExactVersionNotRecommended` warning in `UsePythonVersion` & `UseRubyVersion` which triggers when you pass an exact version of Python or Ruby - the underlying principle behind this makes sense, but there are situations where you want to pass an exact version.

Specifically in our case we lock the version of Ruby for our projects using `.ruby-version` file - this is read by our `Gemfile` meaning that you *have* to be running the version of ruby specified by that file or `bundler` will error when you attempt to do anything.

This is highly compatible with potential hosts: Heroku will use the version of ruby denoted in `.ruby-version` if that file exists, and our provisioning scripts for cloud services like AWS and Azure use `rbenv` which uses `.ruby-version` and only supports exact version syntax, and so on.

This means for us we want to be providing an exact version to `UseRubyVersion`, which we do like so:

```
steps:
  - bash: echo "##vso[task.setvariable variable=value;isOutput=true]$(cat .ruby-version)"
    name: RubyVersion
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(RubyVersion.value)
```

However, this means we get warnings on every one of our tasks:

![image](https://user-images.githubusercontent.com/3151613/119285742-d8011d00-bc96-11eb-92df-1ea014d549a3.png)

It would be good if there was a way to suppress these warnings. I'd be fine doing so with an input since we can abstract it away into a template.
