### ISSUE TITLE
Kubernetes@1 'log' command causes build warning

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tasks#14864]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes@1  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

If you use the `Kubernetes@1` task to execute logs, the task tries to set an output variable with the result, which generates a warning because the logs are generally larger than the maximum allowed size.

Here's an example of what the task looks like in the build:

```yaml
- task: Kubernetes@1
  displayName: "Get logs"
  inputs:
    connectionType: "Kubernetes Service Connection"
    kubernetesServiceEndpoint: "myConnection
    command: logs
    arguments: job/jobname -n namespace --all-containers
```

Here's an example of the build warning:

`##[warning]Output variable not set as kubectl command output exceeded the maximum supported length. Output length: 156239, Maximum supported length: 32766`

I'm guessing this comes from the `ToolRunner` being used to execute `kubectl` but it'd be nice if there was a way to disable setting the output variable or otherwise suppress the warning - getting logs to echo here shouldn't be a warning. (Hence "bug" rather than "feature.")
