### ISSUE TITLE
Setting HTTP/2 on app service using AzureAppServiceSettings@1 not working (or undocumented)

### ISSUE THREAD

**Issue by sussexrick** [microsoft/azure-pipelines-tasks#14879]
I am attempting to set an app service to use HTTP/2 using the AzureAppServiceSettings@1 task. The [documentation in this repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureAppServiceSettingsV1) only gives syntax for a couple of the `generalSettings` and links to a page about modifying them in the Azure portal.

Looking at the examples given they match the names used in ARM templates, and the ARM template name for the HTTP/2 setting is `http20Enabled`, but the following task does not update the setting:

```yml
 - task: AzureAppServiceSettings@1
    displayName: Configure the Azure Web App
    inputs:
      azureSubscription: 'service-connection-here'
      appName: 'app-name-here'
      generalSettings: |
        [
          {
            "name": "http20Enabled",
            "value": true,
            "slotSetting": false
          }
        ]
```

Please can someone clarify whether this is the correct syntax and, if so, why it might not work?
