### ISSUE TITLE
YAML task for download artifacts does not work with variable

### ISSUE THREAD

**Issue by titans2016** [microsoft/azure-pipelines-tasks#14882]
I have been working in Azure Devops Services.
I’ve added to my azure devops pipeline step to download artifact from CI pipeline.
It is working perfect, but I tried to change artifact name to variables, because this names is using in many places.

```
strategy:

        runOnce:

          deploy:

            steps:    
      
            - download: $(artifactPipe) 
            
              artifact: $(artifactName)
```

When I execute this code I receive error:

> ##[error]Invalid hex string #/11700000/drop (Parameter ‘hex’)

I think this is a bug.
I want to ask to fix this ASAP. Because it is block our production pipeline.
Thanks in advance.

**Comment by anatolybolshakov** [comment]
Hi @titans2016 I can't reproduce this issue - could you please share your full logs and minimal sample to reproduce it?

**Comment by titans2016** [comment]
Here my code.
Just add you ci pipeline name to line 12.


```
trigger:
- none

variables:
  vmImageName: 'windows-latest'
  artifactPipe: 'deployArtifact' 
  artifactName: 'deploy'

resources:
  pipelines:
  - pipeline: $(artifactPipe) 
    source: 'CINamePipeline'
    
stages:
  - stage: Deploy_Dev_Stage  
    jobs:
    - deployment: Dev
      displayName: DeployDev
      environment: devSubTest
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:          
            - download: $(artifactPipe) 
              artifact: $(artifactName)  
            - script: |  
                tree
              workingDirectory: $(Agent.BuildDirectory)\$(artifactPipe) 

```

**Comment by anatolybolshakov** [comment]
@titans2016 still can't reproduce it.. Could you please share pipeline logs in debug mode - to understand where this error comes from?

**Comment by titans2016** [comment]
Here my log.
[logs_13.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6559341/logs_13.zip)

**Comment by SheGe** [comment]
I was affected by similar issue. If variable is a static pipeline variable (variable specified in yaml file and its value is not changing during pipeline execution) you could use a templating language as a temporary fix: `artifact: ${{ variables.artifactName }}`

**Comment by titans2016** [comment]
When I put artifact: ${{ variables.artifactName }} I've got an error:
/azure-pipelines-CD.yml (Line: 14, Col: 13): A template expression is not allowed in this context

**Comment by SheGe** [comment]
From what I know usage of variables is not supported yet today in definition of `resources`: https://developercommunity.visualstudio.com/t/Allow-variables-at-resourcesrepositori/816606

Hope that's your issue. Temporary fix I proposed was working fine for me with a standard jobs (not deployment jobs). I do not have any yaml based release def today to verify if usage of templating language on deployment jobs is even possible.

Check this one:

```yaml
resources:
  pipelines:
  - pipeline: deployArtifact
    source: 'CINamePipeline'

trigger:
- none

variables:
  vmImageName: 'windows-latest'
  artifactPipe: 'deployArtifact'
  artifactName: 'deploy'

stages:
  - stage: Deploy_Dev_Stage
    jobs:
    - deployment: Dev
      displayName: DeployDev
      environment: devSubTest
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
            - download: '${{ variables.artifactPipe }}'
              artifact: ${{ variables.artifactName }}
            - script: |
                tree
              workingDirectory: $(Agent.BuildDirectory)\$(artifactPipe)
```

**Comment by anatolybolshakov** [comment]
@titans2016 do you use PublishPipelinesArtifacts task to publish artifacts? Looks like original artifact was generated by publish build artifacts task - so some field has wrong format, which causes this issue.

**Comment by titans2016** [comment]
Here is my CI pipeline for create artifact.
Nothing special. 

```
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:OutDir=$(Build.BinariesDirectory)/publish_output'

- task: ArchiveFiles@2
  displayName: Archive azure function
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: CopyPublishBuildArtifacts@1
  displayName: Copy and publish artifacts
  inputs:
    CopyRoot: '$(Build.ArtifactStagingDirectory)\'
    Contents: '$(Build.BuildNumber).zip'
    ArtifactName: 'deploy'
    ArtifactType: 'Container'
```

**Comment by anatolybolshakov** [comment]
@titans2016 CopyPublishBuildArtifactsV1 task is deprecated and it's not recommended to use it - this tasks publish build artifacts, but you are trying to download artifact using DownloadPipelineArtifacts task. This causes such issue probably.

**Comment by anatolybolshakov** [comment]
Hi @titans2016 do you have any updates?

**Comment by titans2016** [comment]
Based that old task won't work, I switched to tasks which provided on library:


```
trigger:
 none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:OutDir=$(Build.BinariesDirectory)/publish_output'

- task: ArchiveFiles@2
  displayName: Archive azure function
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: deploy


```

On CD pipeline I put everything on variable:

```
trigger:
- none

variables:
  vmImageName: 'windows-latest'
  artifactPipe: 'deployArtifact' 
  artifactName: 'deploy'
  cipipeline: 'SeleniumParserCI'
  system.debug: true

resources:
  pipelines:
  - pipeline: $(artifactPipe)
    source:  $(cipipeline)


stages:
  - stage: Deploy_Dev_Stage  
    jobs:
    - deployment: Dev
      displayName: DeployDev
      environment: devSubTest
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:          
            - download: $(artifactPipe) 
              artifact: $(artifactName)  
            - script: |  
                tree
              workingDirectory: $(Agent.BuildDirectory)/$(artifactPipe) 
```

But I got error:
/azure-pipelines-CD.yml (Line: 13, Col: 15): Pipeline Resource $(artifactPipe) Input Must be Valid.

If I change code to:
```
trigger:
- none

variables:
  vmImageName: 'windows-latest'
  artifactPipe: 'deployArtifact' 
  artifactName: 'deploy'
  cipipeline: 'SeleniumParserCI'
  system.debug: true

resources:
  pipelines:
  - pipeline: 'deployArtifact'
    source:  'SeleniumParserCI'


stages:
  - stage: Deploy_Dev_Stage  
    jobs:
    - deployment: Dev
      displayName: DeployDev
      environment: devSubTest
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:          
            - download: $(artifactPipe) 
              artifact: $(artifactName)  
            - script: |  
                tree
              workingDirectory: $(Agent.BuildDirectory)/$(artifactPipe) 
```

Pipeline is starting but I get an error:
##[error]No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.

So still everything fail except case if I remove variables and provide only string value.

**Comment by anatolybolshakov** [comment]
@titans2016 you still publish artifacts as build artifacts (PublishBuildArtifacts task), but download it using DownloadPipelineArtifacts task - could you please try to switch to PublishPipelineArtifacts task too?

**Comment by anatolybolshakov** [comment]
Hi @titans2016 is this still actual for you?

**Comment by titans2016** [comment]
Yes. The new task which you recommend, absolutely does not help.
CI pipeline:

```
trigger:
 none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:OutDir=$(Build.BinariesDirectory)/publish_output'

- task: ArchiveFiles@2
  displayName: Archive azure function
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'deploy'
    publishLocation: 'pipeline'

```

This CD pipeline does not even start:

```
trigger:
- none

variables:
  vmImageName: 'windows-latest'
  artifactPipe: 'deployArtifact' 
  artifactName: 'deploy'
  cipipeline: 'SeleniumParserCI'
  system.debug: true

resources:
  pipelines:
  - pipeline: $(artifactPipe) 
    source:  $(cipipeline)


stages:
  - stage: Deploy_Dev_Stage  
    jobs:
    - deployment: Dev
      displayName: DeployDev
      environment: devSubTest
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:          
            - download: $(artifactPipe) 
              artifact: $(artifactName)  
            - script: |  
                tree
              workingDirectory: $(Agent.BuildDirectory)/$(artifactPipe) 

```

The error:

/azure-pipelines-CD.yml (Line: 13, Col: 15): Pipeline Resource $(artifactPipe) Input Must be Valid.

If I put this code instead of variable:

```
resources:
  pipelines:
  - pipeline: 'deployArtifact' 
    source:  'SeleniumParserCI'
```

 I receive the same error as I reported in previous message:

> ##[warning]Failed to download task 'Download'. Error No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
> ##[warning]Back off 15.634 seconds before retry.
> ##[warning]Failed to download task 'Download'. Error No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
> ##[warning]Back off 26.479 seconds before retry.
> ##[error]No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.

**Comment by anatolybolshakov** [comment]
@titans2016 could you please create an issue on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it? At this moment this issue does not seem to be an issue with a task itself, but rather an issue on a server side.

**Comment by anatolybolshakov** [comment]
@titans2016 this seems to be current limitation for yaml task coming from server, please see related issue also - https://github.com/microsoft/azure-pipelines-tasks/issues/12862
Let me close this issue here since it's not related to the pipeline task itself.

**Comment by htho** [comment]
I have the same issue, but since the bug seems to stay unfixed, I decided to share my workaround.
I use the `DownloadPipelineArtifact@2` task and provide resource information via variables.

This is how my template is setup.
```yaml
resources:
  pipelines:
  - pipeline: MyProjectPipeline
    source: MyProject

parameters:
- name: DataSource
  default: 'current'
  values:
    - 'current'
    - 'MyProjectPipeline'
```

This is what I want to do:
```yaml
# this does not work because there is a variable name in artifact
  - download: ${{ parameters.DataSource}}
    artifact: '$(NameOfArtifactProvidedByMyProjectPipeline)'
```

Instead i do this:
```yaml
  - ${{ if eq(parameters.DataSource, 'current') }}:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: '$(NameOfArtifactProvidedByMyProjectPipeline)'
    
  - ${{ if eq(parameters.DataSource, 'MyProjectPipeline') }}:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '$(resources.pipeline.MyProjectPipeline.projectID)'
        definition: '$(resources.pipeline.MyProjectPipeline.pipelineID)'
        buildVersionToDownload: 'specific'
        pipelineId: '$(resources.pipeline.MyProjectPipeline.runID)'
        artifactName: '$(NameOfArtifactProvidedByMyProjectPipeline)'
