### ISSUE TITLE
FileTransform - Zipping after transform modifies dates of files to UTC

### ISSUE THREAD

**Issue by FullyFerret** [microsoft/azure-pipelines-tasks#14901]
After running the FileTransform utility _directly_ on a `.zip` file, the transform task seems to modify the dates of the files to UTC date. This causes an issue when running through a private agent on a server with a different timezone and can appear to have "futuristic" dates if the timezone is behind. This impacts processes that rely on up-to-date timestamps of files. 

Please fix this by either utilizing the agent's local timezone or including an settings option preserving time similar to CopyFile utility. Thank you.

Task name: **FileTransform**

## Environment
- Agent - Private: 

    - Windows Server 2016
    - (Eastern Time)

**Comment by fauresco** [comment]
This is a major issue for older asp.net applications that use WebResource.axd (embedded resources in the application like scripts, css).

Steps to reproduce the issue:

1) At the build job, set the timezone to match your web server, i.e. with a power shell task:

```
- task: PowerShell@2
  displayName: 'Set agent timezone'
  inputs:
    targetType: 'inline'
    script: |
      Set-TimeZone -Id "E. South America Standard Time" -PassThru
```

2) Use the web deploy task with variable substitution:

```
- task: IISWebAppDeploymentOnMachineGroup@0
          displayName: 'IIS Web App Deploy'
          inputs:
            WebSiteName: 'ParentSite'
            VirtualApplication: '/myvirtualpath'
            Package: '$(Pipeline.Workspace)\drop\project.zip'
            RemoveAdditionalFilesFlag: true
            TakeAppOfflineFlag: true
            XmlVariableSubstitution: true

```

After this, the zip file artifact you can download from Az DevOps does have the dll files with the expected UTC -3 timestamps, but the dll files deployed to the web server have UTC timestamps.

3) At the web server, if you look at the azagent\_work\1\drop\project.zip you will find that the dll files have the correct timestamp (UTC -3).

4) At the web server, if you look at the azagent\_work\1\s\temp_web_package_ramdomstuff.zip you will find that the dll files have incorrect UTC timestamp.

**Comment by fauresco** [comment]
I was able to workaround the issue by disabling the variable substitution option of the IISWebAppDeploymentOnMachineGroup task and adding a FileTransform task like this:

```
    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'IIS Web App Deploy'
      inputs:
        WebSiteName: 'ParentSite'
        VirtualApplication: '/virtualpath'
        Package: '$(Pipeline.Workspace)\drop\myproject.zip'
        RemoveAdditionalFilesFlag: true
        TakeAppOfflineFlag: true
        XmlVariableSubstitution: false
    
    - task: FileTransform@1
      displayName: 'Replace variables'
      inputs:
        folderPath: 'c:\sites\mysite\wwwroot' 
        fileType: xml
        targetFiles: |
          *.config
```
