### ISSUE TITLE
AzureFileCopy@4 azureSubscription from library variable isn't correctly parsed

### ISSUE THREAD

**Issue by daniel-anova** [microsoft/azure-pipelines-tasks#14906]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzureFileCopy@4

list here (V# not needed):  4
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

using Azure Pipelines:
    - https://dev.azure.com/anovateam/Mapleleaf/_git/PipelineTests?version=GBfeature%2Ftest-pipeline-libs
    - Agent - Hosted:  Azure Pipelines

## Issue Description

When using a variable defined in a Library to pass to AzureFileCopy@4 it's value isn't properly parsed not allowing the task to run with an error.

![image](https://user-images.githubusercontent.com/71904581/120010987-b4f7a580-bfd5-11eb-91ab-66e39d806dd5.png)

If instead of library the variable is set on the pipeline or directly in the file there's no error and works as expected.

Running the pipeline with a bash task completes with success showing the expected variable value.

Bellow I include the yaml of an example pipeline demonstrating the issue.
 [azure-pipelines.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6561952/azure-pipelines.zip)

### Task logs

Task does not run so there's no log of the error.

__There was a resource authorization issue: "The pipeline is not valid. Job Job1: Step input azureSubscription references service connection $(myvalue) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."__

**Comment by AmrutaKawade** [comment]
Can you remove double qoutes around parameter value

```yaml
parameters:
  - name: System.Debug
    type: boolean
    default: true

trigger:
  batch: true
  branches:
    exclude:
    - master

stages:
  - stage: passlibtmpl
    displayName: Pass variable to Template
    variables:
      - group: pipeline-test
    jobs:
      - template: template.yml
        parameters:
          value: $(myvalue)
```

**Comment by daniel-anova** [comment]
> Can you remove double quotes around parameter value?
> 
> ```yaml
> parameters:
>   - name: System.Debug
>     type: boolean
>     default: true
> 
> trigger:
>   batch: true
>   branches:
>     exclude:
>     - master
> 
> stages:
>   - stage: passlibtmpl
>     displayName: Pass variable to Template
>     variables:
>       - group: pipeline-test
>     jobs:
>       - template: template.yml
>         parameters:
>           value: $(myvalue)
> ```

Without double quotes it exhibits the same behavior. The quotes were added in an attempt to workaround it.

**Comment by chshrikh** [comment]
with "template.yml" which job you are using ? Is it regular job or deployment job ?

**Comment by daniel-anova** [comment]
> with "template.yml" which job you are using ? Is it regular job or deployment job ?

The template.yml is included in the attached in the azure-pipelines.zip i'll also add it here

```yaml
parameters:
  - name: value
    type: string

jobs:
- deployment:
  environment: test
  pool:
    vmImage: ubuntu-latest

  strategy:
    runOnce:
      deploy:
        steps:
          - task: Bash@3
            displayName: "bashtest"
            inputs:
              targetType: 'inline'
              script: echo ${{ parameters.value }}
          - task: AzureFileCopy@4
            displayName: "Upload to Azure"
            inputs:
              SourcePath: '$(Pipeline.Workspace)/*'
              azureSubscription: ${{ parameters.value }}
              Destination: 'AzureBlob'
              storage: 'fakestorage'
              ContainerName: "$web"
```
