### ISSUE TITLE
Can VSTest@2 be used for net5?

### ISSUE THREAD

**Issue by JohanLarsson** [microsoft/azure-pipelines-tasks#14909]
I tried a couple of permutations with no success

```yml
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: '$(buildConfiguration)'
```

^ Builds but does not run tests

```yml
- task: VSTest@2
  displayName: Test
  inputs:
    configuration: '$(buildConfiguration)'
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v5.0'
```

^ Builds and runs tests but fails CI due to stuff like:

> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.

```yml
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    configuration: '$(buildConfiguration)'
```

Builds and runs tests but produced 247k false warnings.

Would be nice if something minimal like the first yml could work.
