### ISSUE TITLE
Use more recent java version in Maven@3

### ISSUE THREAD

**Issue by sfragata** [microsoft/azure-pipelines-tasks#14915]
Feature
*Type*: Upgrade Maven task to more updated java version

**Enter Task Name**: Maven@3 (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenV3)

## Environment
- Server - Azure Pipelines

## Issue Description

The more updated `jdkVersionOption` used by task `Maven@3` is 11
 (#jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6) 

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops.

I'd like to use more recent versions like java 14 or 16

**Comment by LadyCailin** [comment]
I've figured out a workaround that's relatively easy enough. You just need an azure blob store where you can store the java version you want to use, then use the JavaToolInstaller to install it, then tell the maven tool to use that version. (It will give a warning, but you can ignore that.) See [here](https://github.com/EngineHub/CommandHelper/blob/master/azure-pipelines.yml) for how I'm doing it. You can use the windows-2019 vm image to get the latest version of maven (3.8.1).

**Comment by sfragata** [comment]
My workaround was not use Maven@3 :) 
I used a container maven with java 16
```
variables:
  maven_ops: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS'

trigger:
  - master

pool:
  vmImage: ubuntu-latest

container: maven:3.8.1-openjdk-16-slim

steps:
  - script: mvn ${maven_ops} -B clean verify
```

**Comment by sfragata** [comment]
I found it

```
trigger:
  - master

pool:
  vmImage: ubuntu-latest

container: maven:3.8.1-openjdk-16-slim

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'path'
      jdkDirectory: '/usr/local/openjdk-16'
      publishJUnitResults: false
      mavenAuthenticateFeed: true
      effectivePomSkip: true
```

I'm using `maven:3.8.1-openjdk-16-slim` container so it needs to set a java home

```
      javaHomeOption: 'path'
      jdkDirectory: '/usr/local/openjdk-16'
```
