### ISSUE TITLE
DownloadPipelineArtifact@2 not taking input parameters for artifact and path

### ISSUE THREAD

**Issue by matteotumiati** [microsoft/azure-pipelines-tasks#14913]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Hosted agents

## Issue Description

I have a pretty simple template defined as following:

```yaml
parameters:
- name: artifactName
  default: 'xxxx'
- name: pipelineId
  default: '400'
- name: branchName
  default: ''

steps:

- task: DownloadPipelineArtifact@2
  displayName: Download Customer.ProCo
  inputs:
    buildType: 'specific'
    project: 'xxx'
    definition: ${{ parameters.pipelineId }}
    buildVersionToDownload: 'latestFromBranch'
    branchName: '${{ parameters.branchName }}'
    artifact: '${{ parameters.artifactName }}'    
    path: '$(System.ArtifactsDirectory)\${{ parameters.artifactName }}'
```

Notice how artifact and path are provided using parameters. 

When I try to run the pipeline that uses this template, I'm presented the following error:

<img width="349" alt="error message" src="https://user-images.githubusercontent.com/3147566/120203119-a7d1f500-c227-11eb-8619-4d5c132f14cf.PNG">

It seems that the parameters are causing the issue, because if I add a constant value then it works nicely. 

### Task logs
The pipeline is not able to start, so there are no logs. 

### Error logs

Please see the image above.
