### ISSUE TITLE
VSBuild & MSBuild fails when target is specified

### ISSUE THREAD

**Issue by kim3er** [microsoft/azure-pipelines-tasks#14922]
## Required Information

Bug, VSBuild@1 & MSBuild@1

## Environment

Server: Azure Pipelines
Account: WriteUpp
Project: WriteUpp
Build Number: 20210528.4 onwards

Agent: Hosted
Queue: Azure Pipelines
Image: windows-latest

## Issue Description
We have a single solution with multiple web projects and shared libraries. We build and deploy each web project in separate jobs within the same pipeline. We specify a target parameter in the build to ensure that only the required project is built in each job.

This was working until last week. At some point last week the build tasks intermittently failed, until Friday, at which point none would run successfully.

For each project in the solution that isn't the target, the same error is generated:

```
##[error]X.csproj(0,0): Error MSB4057: The target "Projects\Y" does not exist in the project.
```

This is an example of one of the tasks. We use VSBuild, but I have confirmed that the same error occurs with MSBuild.

```
          # MSBuild
          - task: VSBuild@1
            inputs:
              solution: "$(solution)"
              msbuildArgs: '/t:Projects\Desktop /clp:ErrorsOnly /verbosity:m /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
              platform: "$(buildPlatform)"
              configuration: "$(buildConfiguration)"
              logFileVerbosity: "minimal"
            displayName: "Build solution"
```

Running the build command locally runs without error. Running the pipeline tasks without the target parameter works, but obviously builds the whole solution. I also tried rolling back to a previously working build, which now also fails.

### Task logs

[33.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6583818/33.txt)
