### ISSUE TITLE
How to reference build artifacts correctly in task AzureFileCopy@4

### ISSUE THREAD

**Issue by thyme51** [microsoft/azure-pipelines-tasks#14974]
**Question**

In my task, I have to use "../" to avoid the empty directory - my build files that I want to deploy is in the "drop" directory. 
The code belows works perfectly but looks odd
```
 task: AzureFileCopy@4
              displayName: "Kopier til blob storage"
              name: "AzCopy"
              inputs:
                sourcePath: '$(Build.ArtifactStagingDirectory)/../drop/*'
                AdditionalArgumentsForBlobCopy: '--recursive'
```
This is the files on my deploy agent which is different from the build agent:
![billede](https://user-images.githubusercontent.com/8446402/122037214-a7fbf400-cdd4-11eb-9415-705bbc5124a5.png)

**Enter Task Name**: AzureFileCopy@4

## Environment
- Server - Azure Pipelines
