### ISSUE TITLE
Build Pipeline Powershell task exposes a variable's sensitive information in the Activity Log on a Parse Error

### ISSUE THREAD

**Issue by Jharr20210609** [microsoft/azure-pipelines-tasks#14972]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Powershell task**: To retrieve sensitive information dumps it to the log on a Parse Error

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines: AccumatchDevOps / Blue_System / Blue_System (1) / 69b0700
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
Hosted agent 'fv-az191-259'

## Issue Description

When attempting to retrieve a variable's value that is marked sensitive, which should not be possible (it should be written to a file), the system will actually display part of that secret value in the log if there is a parsing error in the YAML. Note: in this case our secret is at or above 100 characters in length. Not sure whether or not the length has anything to do with it.

## Troubleshooting
Not sure what we can add here. The bug appears to dump sensitive information when there is a ParseError.

## YAML
```

trigger:
- develop

variables:
- group: 'legacy-pipeline'
- name: 'secret'
  value: 

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        Write-Host "secVG:" $(SigningCertPassword)
        Write-Host "secVG-MAP:" $env:MAPPED_SECRET_VG 
  env:
    MAPPED_SECRET_VG : $(SigningCertPassword) 
```

### Error logs

```
Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.186.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/597f6e9a-6202-458d-a40d-712874462f02.ps1'
ParserError: /home/vsts/work/_temp/597f6e9a-6202-458d-a40d-712874462f02.ps1:2
Line |
   2 |  … <SensitiveSecretValueIsDisplayedHere!> …
     |                                                                 ~
     | Missing closing ')' in expression.

##[error]PowerShell exited with code '1'.
Finishing: PowerShell
```
