### ISSUE TITLE
HelmDeploy - Use registry service connection

### ISSUE THREAD

**Issue by Heisenberg74** [microsoft/azure-pipelines-tasks#15000]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: HelmDeploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**
- Agent - Hosted or Private: **Hosted**

## Issue Description

I am trying to update my pipeline to push my Helm chart to our ACR registry.
In documentation, it is written I have to add the following task :
```
- task: HelmDeploy@0
  displayName: Helm save
  inputs:
    command: save
    chartNameForACR: mycontainerregistry.azurecr.io/helm/hello-world:v1
    chartPathForACR: Application/charts/sampleapp
    azureSubscriptionEndpointForACR: $(azureSubscriptionEndpointForACR)
    azureResourceGroupForACR: $(azureResourceGroupForACR)
    azureContainerRegistry: $(azureContainerRegistry)
```

**My feature**:

I would like to be able to use a Service connection instead setting all the following keys:
- **azureSubscriptionEndpointForACR**
- **azureResourceGroupForACR**
- **azureContainerRegistry**.

Like with the key **containerRegistry** of Docker@2 pipeline task.

Thank you for your support.
