### ISSUE TITLE
KubernetesManifest@0 accepts invalid containers with no warning and defaults to the Kustomize base 

### ISSUE THREAD

**Issue by Larswa** [microsoft/azure-pipelines-tasks#15017]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
Account name  Factus
Project name  Main

- Agent - Private
    
    - Ubuntu 20.04

## Issue Description

When running a deploy stage with the `KubernetesManifest@0` task on a manifest from a Kustomize output, and the Container attribute provides and invalid/nonexisting container, the container from the Kustomize base is used. 

In my case there was a `:latest` tag on the kubernetes server, so it didn't fail or notify me that this container was invalid. (I had a typo in the container variables that I use. See below.  I had a missing forward slash in one of the containers/)

I would have expected and error or at least a warning, telling me that the container does not exist. 

Here is the yaml parts from my deployment for Kustomize and the Deployment. This example would end up deploying the container specified in the Kustomize Base (effectively just grab the :latest), and not fail on the fact that this container does not exist. 

tag: $(Build.BuildNumber)
apiimage: 'hotlaps/hotlapsapi'
uiimage: 'hotlaps/hotlapsui'
repository: 'nexuscr.obfuscated'

``` yaml

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from kustomize files
            inputs:
              action: bake
              renderType: kustomize
              kustomizationPath: $(Pipeline.Workspace)/k8s/overlay/test

          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              action: deploy
              imagePullSecrets: nexus-docker
              # kubernetesServiceConnection: homek8sconnection
              namespace: hotlaps-test
              manifests: $(bake.manifestsBundle)
              containers: |
                $(repository)/$(apiimage):$(tag)
                $(repository)$(uiimage):$(tag)

```
