### ISSUE TITLE
AzureCLI task censorring inline acquired and consumed passwords

### ISSUE THREAD

**Issue by SartriX** [microsoft/azure-pipelines-tasks#15028]
Based on https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/deploy-ftp/deploy-ftp.sh
I want to upload a single file over FTP, using the publishing credentials.

The following works fine when ran from a local source:
```
        creds=($(az webapp deployment list-publishing-profiles --resource-group $resourceGroup --name $appname --slot staging --query "[?contains(publishMethod, 'FTP')].[publishUrl,userName,userPWD]" --output tsv))
        curl -T appsettings.json -u ${creds[1]}:${creds[2]} ${creds[0]/ftp:/ftps:}/
```
The password is correctly stored in creds[2] when running the az webapp deployment list-publishing-profiles locally.

However, when run from within an AzureCLI@2 task, it will send *** as password to the FTP server. As the below task definition shows, it's not in any way being displayed, moving into or exporting out of the scope of the task.

```
  - task: AzureCLI@2
    displayName: Upload config
    inputs:
      azureSubscription: ${{ parameters.azSubscription }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        creds=($(az webapp deployment list-publishing-profiles --resource-group $resourceGroup --name $appname --slot staging --query "[?contains(publishMethod, 'FTP')].[publishUrl,userName,userPWD]" --output tsv))
        curl -T appsettings.json -u ${creds[1]}:${creds[2]} ${creds[0]/ftp:/ftps:}/
      workingDirectory: ${{ parameters.folder }}
    env:
      appname: ${{ parameters.azResource }}
      resourceGroup: ${{ parameters.azResourceGroup }}
```

The result is an FTP errorcode 530 due to bad password.

The above task is run in an AzureDevops pipeline.
