### ISSUE TITLE
Enable PublishTestResultsV2 to publish to another project

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoft/azure-pipelines-tasks#15034]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishTestResultsV2

## Environment
Azure Pipelines

## Summary of the feature request

Looking at the available arguments for PublishTestResults@2 task:

```yaml
# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    #testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    #testResultsFiles: '**/TEST-*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
```

There is no option to publish to another project. This would be helpful since I have a scenario where we would like to publish the test results to another project instead of the current project the pipeline is running in. 

## How should it work?

From a quick glance In the code I see that this is just using the predefined `System.TeamProject` variable:

```typescript
envVars = this.addToProcessEnvVars(envVars, 'projectname', tl.getVariable('System.TeamProject'));
```

The extra option would probably make this default, but giving the user the option to override `projectname` with another project.
