### ISSUE TITLE
Problem with caching npm modules

### ISSUE THREAD

**Issue by ksmigiel** [microsoft/azure-pipelines-tasks#15057]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: windows-2019

## Issue Description

I have noticed the problem with caching `npm-cache`/`.npm` folder (similar to unfortunately closed without resolution issue: #12121), either by using default `%AppData%\npm-cache` or setting `npm_config_cache` environment variable. After some investigation it seems like `Cache@2` task has problem with uploading tarballed archive with .npm folder content. It uploads only ~20% in my case of all npm modules.
It must be somehow connected with .npm folder structure (_cacache folder to be precise) which contains hashes as folder and files names.
Some deduplication and archive optimization process must treat those files as possible to compress/deduplicate and thus results in stripped archive.

When I zipped .npm folder before upload, then  `Cache@2` uploaded 100% of chunks of data. Also `.cypress` cache folder, which we are using in the same pipeline is being cached without any problem.

**Comment by Ogglas** [comment]
We are also having this issue, cache code from docs.microsoft.com

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm

```
trigger:
  batch: true
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'windows-2022'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  clientApp: 'Repo\Repo.Web\ClientApp'

steps:
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(clientApp)\package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm
  
- script: npm ci
  displayName: 'npm ci'
  workingDirectory: $(clientApp)

- script: npm run build
  displayName: 'npm run build'
  workingDirectory: $(clientApp)

```

Both `Cache npm` and `npm ci` looks successful but looking at `npm ci ` it is full of `Invalid response body while trying to fetch` errors.

Example:

> npm WARN old lockfile FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/resolve: ENOENT: no such file or directory, lstat 'D:\a\1\.npm\_cacache\content-v2\sha512\12\57\394f579cc50c27a51fafd47bc9b67bad8f0b3e6c37e5d7af10541cb3c48f62a57e1f58700f1e6a2789e73b52898a12e79b0e1760b8d943b09d2c546c09de'
> npm WARN old lockfile     at C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\body.js:162:15
> npm WARN old lockfile     at async Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:741:9)
> npm WARN old lockfile  Could not fetch metadata for resolve@1.20.0 FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/resolve: ENOENT: no such file or directory, lstat 'D:\a\1\.npm\_cacache\content-v2\sha512\12\57\394f579cc50c27a51fafd47bc9b67bad8f0b3e6c37e5d7af10541cb3c48f62a57e1f58700f1e6a2789e73b52898a12e79b0e1760b8d943b09d2c546c09de'
> npm WARN old lockfile     at C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\body.js:162:15
> npm WARN old lockfile     at async Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:741:9) {
> npm WARN old lockfile   code: 'ENOENT',
> npm WARN old lockfile   errno: 'ENOENT',
> npm WARN old lockfile   syscall: 'lstat',
> npm WARN old lockfile   path: 'D:\\a\\1\\.npm\\_cacache\\content-v2\\sha512\\12\\57\\394f579cc50c27a51fafd47bc9b67bad8f0b3e6c37e5d7af10541cb3c48f62a57e1f58700f1e6a2789e73b52898a12e79b0e1760b8d943b09d2c546c09de',
> npm WARN old lockfile   type: 'system'
> npm WARN old lockfile }

If I remove cache everything works normally. The code worked perfectly well up until 2021-11-30 but started to fail 2021-12-02. In the morning 2021-12-02 1/5 builds got through with cache but since then everything failed. 

The actual error occurs in `npm run build` that simply says:

> 'react-scripts' is not recognized as an internal or external command, operable program or batch file.
