### ISSUE TITLE
MavenV3 field publishJUnitResults read as string, boolean seems more appropriate

### ISSUE THREAD

**Issue by MKaandorp** [microsoft/azure-pipelines-tasks#15060]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

## Issue Description

In the MavenV3 task, the input field publishJUnitResults is read as string, although reading it as a boolean seems more appropriate, as the only value checked for is 'true'. https://github.com/microsoft/azure-pipelines-tasks/blob/43c1554bc3f7d9726cbf0a3cb040d580e2b34740/Tasks/MavenV3/maventask.ts#L29 
Reading it as boolean would also be consistent with the GradleV2 task. https://github.com/microsoft/azure-pipelines-tasks/blob/29c7ef74ecd0d86f9b38663919552e7302c5132b/Tasks/GradleV2/gradletask.ts#L197

The current implementation can give unexpected problems when used in a template in the following way:
```
parameters:
  - name: publishJUnitResults
    type: boolean
    default: true

....

steps:
  - task: Maven@3
    displayName: "Build"
    inputs:
      publishJUnitResults: ${{ parameters.publishJUnitResults }}
```
This template example will never be able to publish the JUnit results, because the parameter has the wrong type.

Is there a specific reason this field is read as a string? If not, I think it would be better to read it as a boolean.
