### ISSUE TITLE
Need a simple way of displaying SQL Print/RaiseError statements in the DevOps release Pipeline log

### ISSUE THREAD

**Issue by BlakesHeaven** [microsoft/azure-pipelines-tasks#15066]
I have the same need as #9500 allegedly resolved in PR #9741
I'm not convinced this is resolved. I have tried a simple PRINT 'Hello World'; both inline and in a file and the only way of getting "Hello World" to appear in the release log is to set `system.debug` to "True" and as stated this is not a real option. Far too much noise.

Adding -Verbose appears to do nothing as well.
Below is the yaml
```yaml
steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: 'Deploy using : !Config_ExecuteScriptByDevOps.sql'
  inputs:
    TaskType: sqlQuery
    SqlFile: '$(System.DefaultWorkingDirectory)\OOTB.Config.Database\Deploy\Publish\!Config_ExecuteScriptByDevOps.sql'
    ServerName: '$(SqlServer)'
    DatabaseName: '$(ConfigDatabaseName)'
    AuthScheme: sqlServerAuthentication
    SqlUsername: '$(SqlUserName)'
    SqlPassword: '$(SqlUserPassword)'
    AdditionalArgumentsSql: '-Verbose'
```

If there is anything I can check, change or confirm; I'm love to know.
Thanks.
