### ISSUE TITLE
Cache not saved when status is SucceededWithIssues

### ISSUE THREAD

**Issue by mklenbw** [microsoft/azure-pipelines-tasks#15077]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description

Post-job of Cache@2 task is not saving when status is 'SucceededWithIssues'. When 'continueOnError: true' is set on a task the cache should be working.

This sample will never cache:
``` yml
trigger: 
  - '*'

steps:
- task: Cache@2
  inputs:
    key: 'nokey'
    path: '.'

- script: |
    exit -1
  displayName: 'Run script'
  continueOnError: true
```
