### ISSUE TITLE
Is it possible to configure Health Check for an App Service using AzureRmWebAppDeploymentV4

### ISSUE THREAD

**Issue by ranikamadurawe** [microsoft/azure-pipelines-tasks#15103]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureRmWebAppDeploymentV4  

## Environment
- Server - Azure Pipelines
    
- Agent -  Private:

    - Ubuntu 20.04 / Agent Version 2.118.4

## Issue Description

I am trying to configure a App Service deployment with Health Checks using Azure Pipelines. I am using the inbuilt Azure DevOps Task AzureRmWebAppDeploymentV4. I am using the following `yml` configuration for this purpose.

```
jobs:
  - job: deploy_app_svc
    displayName: Deploy App Service
    steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'mySubscriptionSvcConnection'
          appType: 'webAppContainer'
          WebAppName: 'myWebApp'
          DockerNamespace: 'repoNamespace'
          DockerRepository: 'repoName'
          DockerImageTag: 'repoImageTag'
          AppSettings: '-DOCKER_REGISTRY_SERVER_USERNAME $(docker_username) -DOCKER_REGISTRY_SERVER_PASSWORD $(docker_pass) -DOCKER_REGISTRY_SERVER_URL $(docker_url)'
          ConfigurationSettings: '-healthCheckPath: /svc/health'


```

### Error logs
The pipeline finished with no Error Logs, However when accessing the App Service from the portal the `Health Check Path` has not been changed.
