### ISSUE TITLE
Bicep What-if fails with false-positive on Azure DevOps.

### ISSUE THREAD

**Issue by pinakighatak** [microsoft/azure-pipelines-tasks#15121]
**Bug**  
*Type*: Pipeline error

**AzureCLI@2**:

## Environment
- Azure Pipelines
- Agent - Hosted
    
## Issue Description
In Azure DevOps, I'm using this step like this:
````yaml
      - task: AzureCLI@2
        displayName: Analyze Bicep Template
        continueOnError: true
        inputs:
          azureSubscription: '$(AZURE_CREDENTIALS)'
          scriptType: ps
          failOnStandardError: false
          scriptLocation: inlineScript
          inlineScript: |
            az account show
            az deployment group what-if -f $(System.DefaultWorkingDirectory)/bicep/main.bicep  -p $(System.DefaultWorkingDirectory)/bicep/parameters.dev.json -g $(AZURE_RESOURCE_GROUP)

````

### Task logs

````
Starting: Analyze Bicep Template
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.1.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
azure-cli                         2.27.0

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

core                              2.27.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
Setting active cloud to: AzureCloud
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "70b77cc4-67c1-4e40-bd7b-b4853065111a",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Pinaki-MSFT",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription 70b77cc4-67c1-4e40-bd7b-b4853065111a"
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1628109034773.ps1'"
ERROR: 'NoEffect'
##[error]Script failed with exit code: 1
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"

````

This break the pipleine, even with  `failOnStandardError: false` applied and the templates are OK. Fails on what-if but works fine on deployment.
