### ISSUE TITLE
##[error]sdk version matching: 6.0.0-preview.6.21352.2 could not be found

### ISSUE THREAD

**Issue by aherrick** [microsoft/azure-pipelines-tasks#15122]
I have the following step to try and install Net6 Preview6:

```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.6 preview'
  inputs:
    version: '6.0.0-preview.6.21352.2'
    vsVersion: 16.11.0
    includePreviewVersions: true
```

```
Starting: Use .NET Core sdk 6.0.6 preview
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 6.0.0-preview.6.21352.2.
No matching sdk version could be found for specified version: 6.0.0-preview.6.21352.2 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 6.0.0-preview.6.21352.2 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 6.0
##[error]sdk version matching: 6.0.0-preview.6.21352.2 could not be found
```
