### ISSUE TITLE
Feature: Resolve ~ as HOME path

### ISSUE THREAD

**Issue by matkoch** [microsoft/azure-pipelines-tasks#15131]
**Enter Task Name**: Cache  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Azure Pipelines provides no consistent way to reference the HOME directory. These are:

- For macOS: `/Users/runner/`
- For Windows: `C:\Users\VssAdministrator`
- For Linux: `/home/vsts`

This is particularly an issue for the Cache task, which then requires providing different settings. I.e., the following does not work for every image:

```
  - task: Cache@2
    inputs:
      key: $(Agent.OS) | **/global.json, **/*.csproj
      path: ~/.nuget/packages
```

**Comment by matkoch** [comment]
FYI, [GitHub Actions does this resolution]. It's an older revision because I couldn't find it in the current HEAD, but the behavior is preserved.

**Comment by matkoch** [comment]
@DenisRumyantsev

**Comment by hansmbakker** [comment]
This issue is not solved. @johnterickson @DergachevE @matkoch can you please reopen this?

The [TFLint plugins folder is stored in `~/.tflint.d/plugins` by default](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#plugin-directory).

This issue prevents me from easily caching that folder, which is recommended to avoid unnecessary calls to GitHub Releases in CI pipelines.

**Comment by johnterickson** [comment]
@ivanduplenskikh is there some part of the stack (YML, task host, etc) that should be taking care of this so that every task doesn't have to? (not sure who to ask)

**Comment by ivanduplenskikh** [comment]
@johnterickson I don't know of such mechanism off the top of my head.
Usually, we use [azure-pipelines-task-lib](https://github.com/microsoft/azure-pipelines-task-lib) as an SDK for sharing methods between Node-based tasks, but I noticed that this task is part of the Agent itself.

@hansmbakker, as a temporary solution, you can try to use environment variables: `$HOME` in bash and `$env:USERPROFILE` in PowerShell to propagate it as a variable to Cache task:
```yaml
- powershell: echo "##vso[task.setvariable variable=HOMEDIR;]$env:USERPROFILE"
- powershell: New-Item "$env:USERPROFILE/.tflint.d/plugin/1.somefile" -Force
- task: Cache@2
  inputs:
    key: './*'
    path: $(HOMEDIR)/.tflint.d/plugin
```
