### ISSUE TITLE
MSBuild task does not respect SuppressTSqlWarnings property in .sqlproj

### ISSUE THREAD

**Issue by kalimah-apps** [microsoft/azure-pipelines-tasks#15142]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: MSBuild

## Issue Description

I am trying to build a DACPAC file using MSBuild task. Here is my yaml code:
```
 - task: MSBuild@1
          inputs:
            solution: '**\*.sqlproj'
            msbuildLocationMethod: 'location'
            msbuildLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\MSBuild\15.0\Bin'
            configuration: '$(buildPlatform)'
            msbuildArguments: '/p:noWarn="71501,SQL71501"'
            clean: true
            logProjectEvents: true
            createLogFile: true
            logFileVerbosity: 'quiet'
```
When running the pipeline I get errors similar to this:
```
##[error]dbo\Functions\function_name.sql(10,40): Error SQL71501: Function: [dbo].[function_name] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: ......
```
The process works fine on local server as the reference exist but it is not checked out to the git repo on AzureDevops.

In my .sqlproj file I added the following line to build and release (For testing):
```
 <SuppressTSqlWarnings>71562,71501,71502</SuppressTSqlWarnings>
```
and the complete propertygroup tag looks like this:
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
    <BuildScriptName>$(MSBuildProjectName).sql</BuildScriptName>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <SuppressTSqlWarnings>71562,71501,71502</SuppressTSqlWarnings>
  </PropertyGroup>
```

but the error is not suppressed. 

I also tried to add arguments to the task using noWarn:
```
/p:noWarn="71501,SQL71501"
```

but still it is not working. 

Any thoughts?
