### ISSUE TITLE
Expressions using Pipeline Variables behave inconsistently across template files

### ISSUE THREAD

**Issue by DhavalShewale** [microsoft/azure-pipelines-tasks#15147]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Expressions

## Environment
- Server - Azure Pipelines 
- Agent - Impacts Both (MSFT Hosted & Self Hosted)

## Issue Description
- Pipeline variable behave inconsistently in nested templates. 
- Expressions using same pipeline variables should produce consistent results irrespective of the file which contain them.
- Pls use below pipelines to reproduce the issue.
- In the example below:
  - AzurePipeline and BehaveWeirdly1 stages have the exact same steps, however the results are different. 
    - **Results in BehaveWeirdly1 stage are incorrect.**
  - Similarly, BehaveWeirdly2 and BehaveWeirdly3 stages have similar steps and still produce different results. 
    - **Results in BehaveWeirdly2 stage are incorrect.**

### azure-pipelines.yml
```
trigger:
  - master

pool: 
  vmImage: 'ubuntu-latest'

variables:
  SOMETHING_IMPORTANT: hahaha

stages:
  - stage: AzurePipeline
    jobs:
      - job: AzurePipeline
        steps:
          - checkout: none

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step AP01 - hahaha"
            displayName: Step AP01 - $(SOMETHING_IMPORTANT)
          
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step AP02 - hahaha"
            displayName: Step AP02 - ${{variables['SOMETHING_IMPORTANT']}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step AP03 - hahaha"
            displayName: Step AP03 - ${{variables.SOMETHING_IMPORTANT}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step AP04 - True"
            displayName: Step AP04 - ${{eq(variables['SOMETHING_IMPORTANT'], 'hahaha')}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step AP05 - True"
            displayName: Step AP05 - ${{eq(variables.SOMETHING_IMPORTANT, 'hahaha')}}

  - template: behave-weirdly.yml

  - template: actual-use-case.yml
```

### behave-weirdly.yml
```
stages:
  - stage: BehaveWeirdly1
    jobs:
      - job: BehaveWeirdly1
        steps:
          - checkout: none
        
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW01 - hahaha"
            displayName: Step BW01 - $(SOMETHING_IMPORTANT)
        
          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW02 - hahaha"
            displayName: Step BW02 - ${{variables['SOMETHING_IMPORTANT']}}

          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW03 - hahaha"
            displayName: Step BW03 - ${{variables.SOMETHING_IMPORTANT}}

          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW04 - True"
            displayName: Step BW04 - ${{eq(variables['SOMETHING_IMPORTANT'], 'hahaha')}}

          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW05 - True"
            displayName: Step BW05 - ${{eq(variables.SOMETHING_IMPORTANT, 'hahaha')}}

  - stage: BehaveWeirdly2
    variables:
      SOMETHING_IMPORTANT_COPY: $(SOMETHING_IMPORTANT)
    jobs:
      - job: BehaveWeirdly2
        steps:
          - checkout: none
        
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW01 - hahaha"
            displayName: Step BW01 - $(SOMETHING_IMPORTANT_COPY)
        
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW02 - hahaha"
            displayName: Step BW02 - ${{variables['SOMETHING_IMPORTANT_COPY']}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW03 - hahaha"
            displayName: Step BW03 - ${{variables.SOMETHING_IMPORTANT_COPY}}

          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW04 - True"
            displayName: Step BW04 - ${{eq(variables['SOMETHING_IMPORTANT_COPY'], 'hahaha')}}

          # This does not work as expected - FAIL
          - script: echo "Expected Step Name ==> Step BW05 - True"
            displayName: Step BW05 - ${{eq(variables.SOMETHING_IMPORTANT_COPY, 'hahaha')}}

  - stage: BehaveWeirdly3
    variables:
      SOMETHING_NOT_IMPORTANT: hahahahaha
    jobs:
      - job: BehaveWeirdly3
        steps:
          - checkout: none
        
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW01 - hahahahaha"
            displayName: Step BW01 - $(SOMETHING_NOT_IMPORTANT)
        
          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW02 - hahahahaha"
            displayName: Step BW02 - ${{variables['SOMETHING_NOT_IMPORTANT']}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW03 - hahahahaha"
            displayName: Step BW03 - ${{variables.SOMETHING_NOT_IMPORTANT}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW04 - True"
            displayName: Step BW04 - ${{eq(variables['SOMETHING_NOT_IMPORTANT'], 'hahahahaha')}}

          # This works as expected - PASS
          - script: echo "Expected Step Name ==> Step BW05 - True"
            displayName: Step BW05 - ${{eq(variables.SOMETHING_NOT_IMPORTANT, 'hahahahaha')}}
```

### actual-use-case.yml

```
stages:
  - stage: ActualUseCase
    jobs:
      - job: ActualUseCase
        steps:
          - checkout: none
        
          # This does not work as expected - Resolves to false - FAIL
          - ${{ if eq(variables.SOMETHING_IMPORTANT, 'hahaha') }}:
            - script: echo "Do Something"
              displayName: Step AUC01 - Do Something
        
          # This does not work as expected - Resolves to false - FAIL 
          - ${{ if eq(variables['SOMETHING_IMPORTANT'], 'hahaha') }}:
            - script: echo "Do Something Else"
              displayName: Step AUC02 - Do Something Else
```

### Executed Pipeline Screenshot

![image](https://user-images.githubusercontent.com/55530256/129150296-ce4f88a6-7930-4d0c-aada-785f9065470a.png)
