### ISSUE TITLE
AzurePowerShell throws The string is missing the terminator: ". even when the contents of the script are write-host "task doesn't work"

### ISSUE THREAD

**Issue by MarkIannucci** [microsoft/azure-pipelines-tasks#15154]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell  

## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/DHHA/DHHA/_build/results?buildId=52410&view=results

- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name:  ubuntu-latest

## Issue Description

I'm trying to use Azure CLI and Azure PowerShell in the same script using [these instructions](https://www.integration-playbook.io/docs/combining-az-cli-and-azure-powershell-az-modules-in-a-pipeline).  I'm doing this because the [New-ContainerGroup cmdlet](https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/new-azcontainergroup?view=azps-6.3.0) doesn't have parameters for vnet and [Azure CLI does](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az_container_create).

So, I have the following yaml:

```
jobs:
  - job: RunScriptToSetupAtlantisOnAzureContainerInstances
    steps:
      - task: AzureCLI@2
        displayName: 'Azure CLI - Promote Service Principal'
        inputs:
          azureSubscription: Mark VS Enterprise
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            write-host "##vso[task.setvariable variable=ARM_CLIENT_ID]$($env:servicePrincipalId)"
            write-host "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$($env:servicePrincipalKey)"
            write-host "##vso[task.setvariable variable=ARM_TENANT_ID]$($env:tenantId)"
          addSpnToEnvironment: true
      - task: AzurePowerShell@4
        displayName: SpinUpContainer
        inputs:
          azureSubscription: Mark VS Enterprise
          scriptType: filepath
          scriptPath: ./devops pipelines/Infrastructure/AtlantisOnAci.ps1
        env:
          AZUREDEVOPS_BASIC_AUTH: $(AzureDevOpsBasicAuth)
          AZUREDEVOPS_WEBHOOK_USER: $(AzureDevOpsWebHookUser)
          AZUREDEVOPS_TOKEN: $(AzureDevOpsAtlantisPAT)
          AZUREDEVOPS_USER: $(AzureDevOpsUser)
          ATLANTIS_LOCATION: $(AzureLocation)
          SUFFIX: $(Build.BuildId)

```
When the contents of AtlantisOnAci.ps1 are :

 ````
write-host "task doesn't work"
````

The pipeline throws `The string is missing the terminator: "`

### Task logs

[logs_52411.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6984001/logs_52411.zip)

## Troubleshooting

I reviewed that stuff and didn't find anything.  Looking at the logs, I think the issue is that secret isn't escaped in the JSON on line `1659` in the 1_RunScriptToSetupAtlantisOnAzureContainerInstances (1).txt in the attached zip file.  

### Error logs

````
2021-08-13T15:30:38.8516414Z [command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/b6ffa7c1-7bf2-4f80-acba-ad3a2627bc55.ps1'
2021-08-13T15:30:38.8564549Z Saved!
2021-08-13T15:30:39.4174635Z [91mParserError: [0m/home/vsts/work/_temp/b6ffa7c1-7bf2-4f80-acba-ad3a2627bc55.ps1:4
2021-08-13T15:30:39.4176223Z [96mLine |
2021-08-13T15:30:39.4177524Z [96m   4 | [0m … yM9gfrSivsKPOYIfuNbA==","isADFSEnabled[96m":false}}' -targetAzurePs  null[0m
2021-08-13T15:30:39.4179006Z [96m     | [91m                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-08-13T15:30:39.4180211Z [91m[96m     | [91mThe string is missing the terminator: ".
2021-08-13T15:30:39.4181101Z [0m
2021-08-13T15:30:39.4377781Z ##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
````

# We are a customer, please label accordingly.
