### ISSUE TITLE
Using task PowershellTask@2 to invoke a pscore script in a YAML pipeline generates a dotnet error

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#15175]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Powershell

list here (V# not needed):  2

## Environment
- Server - Azure Pipelines
    
    Please reach out to me in private so I can provide account name, team project name, build definition name, and build number.

- Agent - Hosted: 
    
   I'm using pool with vmImage: 'ubuntu-latest' in yaml pipeline. I've tried using private agents as well and the same error persists .

## Issue Description

   When calling a powershell script via pwsh, I get an unexpected error about an option: -V which I'm never setting at all in my script or in the YAML task.

```yaml
- task: PowerShell@2
  displayName: 'Set or register PrivatePSGallery'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/src/setprivatepsgallery.ps1'
    arguments: '-RepositoryName $(PowershellRepositoryName) -RepositorySourceLocation $(PowershellRepositorySourceLocation)'
    failOnStderr: true
    showWarnings: true
    pwsh: true
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

### Task logs

Please reach out to me privately so I can provide you a zip file of the task logs.

### Error logs

##[debug]/usr/bin/pwsh arg: . '/home/vsts/work/_temp/a132de4b-03fd-42f2-bb22-8aecb6d3cd96.ps1'
##[debug]exec tool: /usr/bin/pwsh
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -Command
##[debug]   . '/home/vsts/work/_temp/a132de4b-03fd-42f2-bb22-8aecb6d3cd96.ps1'
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/a132de4b-03fd-42f2-bb22-8aecb6d3cd96.ps1'

Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------  
1      94558a0b-00d0-…                 NotStarted    False                     
Searching for repository: PrivatePSGallery
Registering repository PrivatePSGallery name with SourceLocation to https://pkgs.dev.azure.com/myaccount/_packaging/myfeedname/nuget/v2
Unknown option: -V
