### ISSUE TITLE
XamarinAndroid not building APK with x86 or x64 support

### ISSUE THREAD

**Issue by FinitelyFailed** [microsoft/azure-pipelines-tasks#15236]
Hi,

I just noticed that when using XamarinAndroid@1 build task the resulting APK does not contain x86 or x64 support. We really need that. If there is an issue with the config I'm not sure as it says nothing about the platform support in the documentation I found.

This is how my build-task look like:
```
- task: XamarinAndroid@1
  inputs:
    projectFile: 'X.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:DefineConstants=PROD'
    jdkOption: 'JDKVersion'
```
