### ISSUE TITLE
Download Package extract files with spaces in as %20 in the name

### ISSUE THREAD

**Issue by musmuris** [microsoft/azure-pipelines-tasks#15258]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Download Package

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines
Hosted    

## Issue Description

Task in YAML is as follows:

```yaml
- task: DownloadPackage@1
  displayName: Get Latest Metadata
  inputs:
    packageType: 'nuget'
    feed: orgdefault
    view: Local
    definition: MyMetadata
    version: latest
    extract: true
    downloadPath: '$(Build.SourcesDirectory)/src/LatestMetadata/MyMetadata'
```

Package is download correctly. However inside the package are files with spaces in like (e.g.) `Data Source\source1.txt`, `Data Source\source other.txt`  
When extracted, and then looked at using powershell  `Get-ChildItem -Path '$(Build.SourcesDirectory)/src/MyMetadata' -recurse`  the spaces appear to have %20 in them:
````
Directory: D:\a\1\s\src\DashboardBuilder\MyMetadata\Data%20Source


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         9/6/2021   3:35 PM         318163 source1.txt
-a----         9/6/2021   3:35 PM           9124 source%20other.txt
```

When our tests then look for the files with spaces it doesn't find them.
