### ISSUE TITLE
Weird behavior DockerV2 Task

### ISSUE THREAD

**Issue by rdvansloten** [microsoft/azure-pipelines-tasks#15270]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug?

**Task Name**: DockerV2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    funda-sre, funda-deliverables, 3062

- Agent - Hosted or Private: 
    Private, 2019-datacenter-with-containers-g2, 2.192.0

## Issue Description

Using the template provided by Azure DevOps (pasted below) I run into the issue where the image building is throwing errors, looking for an image called "the new image." I have no idea where this comes from or how to get rid of this. The tasks go through, but the finished image won't successfully pull from the Azure Container Registry. In the logs, I can see it feeding the arg `"image.base.ref.name=the new image."` and `"C:\Program Files\Docker\docker.exe" pull "the new image."` `"C:\Program Files\Docker\docker.exe" inspect "the new image."` which then error out.

The files used are as vanilla as possible. Windows container and Azure DevOps pipeline file from the wizard in Azure DevOps.

pipeline.yml
```
trigger:
- main

resources:
- repo: self

pool: SelfHostedWindows

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'REDACTED'
  imageRepository: 'windowshello'
  containerRegistry: 'REDACTED.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: REDACTED16910019-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: SelfHostedWindows
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
```

Dockerfile
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Metadata indicating an image maintainer.
LABEL maintainer="rudy"

# Uses dism.exe to install the IIS role.
RUN dism.exe /online /enable-feature /all /featurename:iis-webserver /NoRestart

# Creates an HTML file and adds content to this file.
RUN echo "Hello World" > c:\inetpub\wwwroot\index.html

# Sets a command or process that will run each time a container is run from the new image.
CMD [ "cmd" ]
```

### Task logs

```
Starting: Build
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.188.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
==============================================================================
"C:\Program Files\Docker\docker.exe" pull "the new image."
invalid reference format
"C:\Program Files\Docker\docker.exe" inspect "the new image."
Error: No such object: the new image.
[]
"C:\Program Files\Docker\docker.exe" build -f C:\a\1\s\app\Dockerfile 
--label com.azure.dev.image.system.teamfoundationcollectionuri=https://dev.azure.com/REDACTED/ 
--label com.azure.dev.image.system.teamproject=REDACTED 
--label com.azure.dev.image.build.repository.name=WindowsContainers-Hello-World 
--label com.azure.dev.image.build.sourceversion=21a8a4591e6380ce241d249f6a09cdb1f17342e6 
--label com.azure.dev.image.build.repository.uri=https://REDACTED 
--label com.azure.dev.image.build.sourcebranchname=main 
--label com.azure.dev.image.build.definitionname=WindowsContainers-Hello-World 
--label com.azure.dev.image.build.buildnumber=20210910.18 --label com.azure.dev.image.build.builduri=vstfs:///Build/Build/3062 --label "image.base.ref.name=the new image." -t ***/windowshello:3062 C:\a\1\s\app
```

### Error logs

[Insert error from the logs here for a quick overview]
