### ISSUE TITLE
How to upgrade from DotNetCoreCLI@2 restore using specific feed, to NuGetAuthenticate?

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azure-pipelines-tasks#15297]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGetAuthenticate

## Environment
- Server: Azure Pipelines
- Agent: Hosted

## Issue Description

We are currently using the following (which works perfectly) to restore packages from our Azure Artifacts feed:

```yaml
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    feedRestore: 'NameOfFeed'  
    projects: '**/*.csproj'
```

However, https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli states:

> The NuGet Authenticate task is the new recommended way to authenticate with Azure Artifacts and other NuGet repositories. The restore and push commands of this task no longer take new features and only critical bugs are addressed.

So I changed the above to:

```yaml
- task: NuGetAuthenticate@0

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
```

But the `restore` task now fails because it doesn't even attempt to use our feed for restoring packages.

So I tried changing it to:

```yaml
- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'NameOfFeed'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
```

but that prevents the build from running at all with the error:

> There was a resource authorization issue: "The pipeline is not valid. Job Job: Step NuGetAuthenticate input nuGetServiceConnections references service connection NameOfFeed which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

There is an "Authorize resources" button next to this error, but clicking it does nothing (it shows a popup that the resource has been authorized, but if I refresh the build page the same error is there).

It's a very poor customer experience (but sadly, a completely normal one) that Microsoft provides a new and "improved" way of doing something and tells everyone to use it, yet doesn't bother informing those using the old way how to upgrade.
