### ISSUE TITLE
DotNetCoreCLIV2 restore command doesn't respect workingDirectory option

### ISSUE THREAD

**Issue by aressler38** [microsoft/azure-pipelines-tasks#15292]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2  

## Environment
- Server - Azure Pipelines 

- Agent - Hosted 
    
## Issue Description

I have a dotnet project with a `.sln` file in a subfolder called dotnet. I am using the following configuration, and it doesn't work.

```
steps:
  - checkout: self
    path: myrepo
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      workingDirectory: $(Pipeline.Workspace)/myrepo/dotnet
      command: restore
```

The restore command doesn't go through the logic that would normally set the workingDirectory. 
See https://github.com/microsoft/azure-pipelines-tasks/blob/5823bd073cf005000fed8e1cd43f2e2f1e372bdf/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L55

It appears that you need to set the `projects` input instead: https://github.com/microsoft/azure-pipelines-tasks/blob/5823bd073cf005000fed8e1cd43f2e2f1e372bdf/Tasks/DotNetCoreCLIV2/restorecommand.ts#L28

But the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops) says otherwise.

workingDirectoryWorking Directory | Current working directory where the script is run. Empty is the root of the repo (build) or artifacts (release), which is $(System.DefaultWorkingDirectory)
-- | --
