### ISSUE TITLE
Cannot pass library secret into docker task build as an argument

### ISSUE THREAD

**Issue by asos-saveriocutrupi** [microsoft/azure-pipelines-tasks#15319]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: Docker@2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted or Private: 
    
    - Hosted

## Issue Description

code:
```
variables:
  - group: MyVariablesGroup
  - name:  version
    value: $(Build.BuildId)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and push

    jobs:
    - job: Build
      displayName: Build job
      pool:
        vmImage: ubuntu-latest

      steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: MyACR

        - task: Docker@2
          displayName: 'Build'
          inputs:
            command: build
            containerRegistry: MyACR
            repository: function
            tags: |
              $(version)
            arguments: KEY=$(key)
```

What I'm trying to do is build a container while passing a secret variable from the pipeline library into docker as an argument, but the result I get back is:
```
/usr/bin/docker build -f /home/vsts/work/1/s/Dockerfile --label 
[...] KEY=$(key) -t ***/function:10000 /home/vsts/work/1/s
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
##[error]"docker build" requires exactly 1 argument.
##[error]See 'docker build --help'.
##[error]Usage:  docker build [OPTIONS] PATH | URL | -
##[error]Build an image from a Dockerfile
##[error]The process '/usr/bin/docker' failed with exit code 1
```

I'd also like to point out that I've tried like twenty small variations in order to get the variable into docker, and the only one that didn't bonk the pipeline is passing `arguments: --secret KEY=$(key)`, but then the variable is empty so it's not really an improvement.

Is there any solution or hacky fix for this issue?

### Error logs

```
##[error]"docker build" requires exactly 1 argument.
```
