### ISSUE TITLE
Cannot pipe stdin to external program in PowerShell task

### ISSUE THREAD

**Issue by fedorbirjukov** [microsoft/azure-pipelines-tasks#15318]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell

>list here (V# not needed): https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: DevOps Server 2020 - Dev18.M170.8
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/fbiryukov/fbiryukov/_build/results?buildId=24

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-2019

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10, agent v2.170.1

## Issue Description

I am logging this here because I cannot reproduce the issue outside of a pipeline.

The issue can be easily reproduced with this pipeline on dev.azure.com:

```
trigger:
- main

pool:
  vmImage: windows-2019

steps:
- script: git diff HEAD~ HEAD --name-only --diff-filter=d | git checkout HEAD --pathspec-from-file=-
  displayName: 'Pipe changed files to git checkout - CMD'
- powershell: git diff HEAD~ HEAD --name-only --diff-filter=d | git checkout HEAD --pathspec-from-file=-
  displayName: 'Pipe changed files to git checkout - PowerShell'
```

This issue could be related: https://github.com/powershell/powershell/issues/5974.

### Task logs

[logs_24.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7217417/logs_24.zip)

>## Troubleshooting
>Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

error: pathspec '﻿azure-pipelines.yml' did not match any file(s) known to git
##[error]PowerShell exited with code '1'.
