### ISSUE TITLE
Publish does not accept projects:

### ISSUE THREAD

**Issue by crgarcia12** [microsoft/azure-pipelines-tasks#15339]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/crgarcia/crgar-microservices-devops/_build/results?buildId=292&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:  Azure Pipelines | image: windows-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I think i figured out. When doing `dotnet publish` having `publishWebProjects: true` and `projects:...`, only the first one is respected. I would rather make the task fail with a descriptive message, or give priority to the `projects` keywords.

```
variables:
  SolutionFolderPath: 'src/BackEndApi/BackEndApi/BackEndApi.sln'
  BuildConfiguration: 'Debug'

# This one takes the <projects> param correctly
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      $(SolutionFolderPath)

# This one omits the <projects> and publishes the first project that it can find
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: |
      $(SolutionFolderPath)
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
```

### Task logs
The first one (build): <notice the path>
```
"C:\Program Files\dotnet\dotnet.exe" build D:\a\1\s\src\BackEndApi\BackEndApi\BackEndApi.sln ....
```

The second one (publish) <notice the path>:
```
"C:\Program Files\dotnet\dotnet.exe" publish D:\a\1\s\src\SignalRChat\SignalRChat.csproj 
```

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
