### ISSUE TITLE
Memory configuration not possible using Xmx and Xms properties

### ISSUE THREAD

**Issue by Solksjaer** [microsoft/azure-pipelines-tasks#15377]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle@2  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    	- syncier
    	- bipro-project
    	- bipro-connector-mapping-ci
    	- 177192

## Issue Description
When executing the `sonarqube` task on Gradle we run into a heap memory issue.
Therefore we included the `JAVA_OPTS` for `Xmx` and `Xms` but they don´t appear to be affecting the size config of the JVM.
`Initial heap size set to a larger value than the maximum heap size`

The Task configuration looks as follows:

```
  - name: java_props
    value: "-Xmx10240m -Xms4096m -XX:MaxPermSize=8224m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
...
          - task: Gradle@3
            displayName: "Run PR Gradle tests"
            condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
              LOG_LEVEL: INFO
              JAVA_OPTS: $(java_props)
            inputs:
              gradleWrapperFile: $(projectPath)/gradlew
              tasks: sonarqube
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.11
              jdkArchitectureOption: x64
              options: -b $(projectPath)/build.gradle.kts $(sonar_props_pr) $(gradle_props)
```

The same issue occurs if we use the SonarQube configuration as follows:

```
          - task: Gradle@2
            displayName: Test
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
              BUILD_USER: $(build_user)
              JAVA_OPTS: $(java_props)
            timeoutInMinutes: 30
            inputs:
              gradleWrapperFile: $(projectPath)/gradlew
              options: -b $(projectPath)/build.gradle.kts --build-cache --stacktrace --info
              tasks: test jacocoTestReport
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: JDKVersion
              jdkVersionOption: "1.11"
              sonarQubeRunAnalysis: true
              sqGradlePluginVersionChoice: build
```

We have already tried multiple configuration values (i.e. `3084m`) but we always reach the same error.

Could you please provide us some help, in order to increase the memory configuration when executing SonarQube analysis on Azure?

Thanks!

### Error logs

```
Starting: Run PR Gradle tests
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.191.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
==============================================================================
/home/vsts/work/1/s/norm430-mapping/gradlew -b norm430-mapping/build.gradle.kts -Dsonar.pullrequest.branch=fix/sonarCloud -Dsonar.pullrequest.key=163 -Dsonar.pullrequest.base=master -Dsonar.pullrequest.provider=vsts -Dfile.encoding=UTF-8 sonarqube
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Error: The process '/home/vsts/work/1/s/norm430-mapping/gradlew' failed with exit code 1
    at ExecState._setResult (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.191.0/node_modules/azure-pipelines-task-lib/toolrunner.js:944:25)
    at ExecState.CheckComplete (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.191.0/node_modules/azure-pipelines-task-lib/toolrunner.js:927:18)
    at ChildProcess.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.191.0/node_modules/azure-pipelines-task-lib/toolrunner.js:840:19)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
No test result files matching /home/vsts/work/1/s/**/TEST-*.xml were found, so publishing JUnit test results is being skipped.
##[error]Error: The process '/home/vsts/work/1/s/norm430-mapping/gradlew' failed with exit code 1
Finishing: Run PR Gradle tests

```
