### ISSUE TITLE
False "The feed already contains" message

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [microsoft/azure-pipelines-tasks#15407]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

```yaml
variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  isMaster: $[eq(variables['Build.SourceBranchName'], 'master')]
  isDevelop: $[eq(variables['Build.SourceBranchName'], 'develop')]
  dateStamp: $[format('{0:yyyyMMdd}', pipeline.startTime)]
  timeStamp: $[format('{0:HHmm}', pipeline.startTime)]
  nugetVersion: $['0.0.0']

steps:

- powershell: |
    try
    {
      $xml = [Xml] (Get-Content .\src\PiX\PiX\PiX.csproj)
      [string] $version = $xml.Project.PropertyGroup.VersionPrefix
      [string] $buildNameDevelop = "$version-develop+$(Build.BuildId)"
      [string] $buildNameRelease = "$version"
      [string] $buildName = "$buildNameDevelop"
      if( $(isMaster) )
      {
        $buildName = $buildNameRelease
      }
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.UpdateBuildNumber]$buildName"
      echo $buildName
      echo "##vso[task.setvariable variable=nugetVersion]$buildName"  
      exit 0
    }
    catch
    {
      Write-Error "Setting Build Number failed."
      exit 1
    }
  displayName: 'Setting the build name (Build.BuilNumber).'
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: 'src'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: 'src'

# Pack nightly NuGets.
- task: DotNetCoreCLI@2
  displayName: Pack Zeiss.PiX NuGet (Develop)
  condition: eq(variables['Build.SourceBranchName'], 'develop')
  inputs:
    command: 'pack'
    packagesToPack: '**/PiX.csproj;**/PiX.Common.csproj;**/PiX.Math.csproj;**/PiX.MeshModel.csproj;**/PiX.WpfInterop.csproj;**/PiX.UI.csproj'
    nobuild: true
    includesymbols: false
    includesource: true
    versioningScheme: byEnvVar
    versionEnvVar: nugetVersion

- task: DotNetCoreCLI@2
  displayName: Push Nightly NuGets to PiWeb-Dependencies feed
  condition: eq(variables['Build.SourceBranchName'], 'develop')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '25f56d55-c2bb-431d-a0d1-2de6090ded31/03ef0ace-589b-4f67-a857-24739b521cd4'
```

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Trying to push to an internal NuGet feed. Version numbers are like

+ 0.1.7-develop-0001
+ 0.1.7-develop-0002
+ a.s.o.

When having pushed 0.1.7-develop-0001 and trying to push 0002, I get an error message: "The feed already contains '<Package ID> 0.1.7-develop+0002' although only version 0001 is there (checked it in the artifacts overview).

### Task logs

```sh
C:\hostedtoolcache\windows\dotnet\dotnet.exe nuget push D:\a\1\a\<PackageID>.0.1.7-develop.nupkg --source https://pkgs.dev.azure.com/<HostedName>/<UUID>/_packaging/<UUID>/nuget/v3/index.json --api-key VSTS
Pushing <PackageID>.0.1.7-develop.nupkg to 'https://pkgs.dev.azure.com/<HostedName>/<UUID>/_packaging/<UUID>/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/<HostedName>/<UUID>/_packaging/<UUID>/nuget/v2/
  Conflict https://pkgs.dev.azure.com/<HostedName>/<UUID>/_packaging/<UUID>/nuget/v2/ 370ms
To skip already published packages, use the option --skip-duplicate
error: Response status code does not indicate success: 409 (Conflict - The feed already contains '<PackageID> 0.1.7-develop+0002'. (DevOps Activity ID: <ID UUID>)).
```

### Idea

Might it be that the feed ignores the last part of the versioning (after 0.1.7-develop or even after 0.1.7) and thereby recognizes both packages as duplicates?

Best regards,
Georg
