### ISSUE TITLE
Problem: UsePythonVersion on self-hosted agents is open to side effects from previous builds

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/azure-pipelines-tasks#15417]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: UsePythonVersion

## Issue Description

When using *UsePythonVersion* with ms-hosted agents everything works
nicely, you get a clean environment on every build (you get a clean machine) 👌.

When using the same task in self-hosted agents you get the selected
python environent under *AGENT_TOOLSDIRECTORY* leaving the door open to
side effects due to inplace modifications of that virtual environment in
that self-hosted machine.

Shouldn't *UsePythonVersion* provide a clean virtual environent in
self-hosted machines to avoid side effects?

**Comment by FrancescElies** [comment]
@max-zaytsev ping 🙂any chances of getting this clarified?

**Comment by FrancescElies** [comment]
I am starting to think this should have been marked as a bug 🐛.

UsePythonVersion having different behavior in self-hosted or microsoft-hosted agents does not feel right.

**Comment by FrancescElies** [comment]
@max-zaytsev will I get an answer?

**Comment by max-zaytsev** [comment]
Hi @FrancescElies,
Could you please clarify what do you mean by different behavior?
There should be no side effects if you set the `addToPath` [parameter](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#arguments) to false.
The difference you described is the difference between ms-hosted and self-hosted agents, which is [expected](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser). In general, if you are using self-hosted agents, you are responsible for cleaning up the environment.

**Comment by FrancescElies** [comment]
Maybe I am having the wrong expectations.

On ms-hosted you can do:

```yaml

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
      
      -run: pip install -r my-pinned-packages.txt
      
      # this is just fine, packages are installed
      # and on the next run I get a new VM and a 
      # clean python venv
```

On self-hosted the same pattern is broken:

```yaml

    steps:
      # this now installs things in Agent.ToolsDirectory
      # which is shared between builds. One ends up installing 
      # python packages on the same installation across builds.
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
      
      -run: pip install -r my-pinned-packages.txt
      
      # this is normally fine, unless something strange happens
      # and the python environment gets broken.
```

I would expect getting a clean python environment when I call `UsePythonVersion@0` but in self hosted we don't.

As mentioned above this is normally not a problem, but sometimes strange things happen.

In self hosted we need to create a new venv to make sure we don't pollute `Agent.ToolsDirectory` and eventually breaking many different builds that depend on the python version installed there.

Making us having to distinguish between self-hosted or ms-hosted agents when we write yaml ci code is not optimal.

Are my expectations wrong?
