### ISSUE TITLE
DownloadPipelineArtifactV2 preferTriggeringPipeline not working as expected

### ISSUE THREAD

**Issue by aressler38** [microsoft/azure-pipelines-tasks#15412]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Contact me for private details

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 20.04, Agent 2.193.1

## Issue Description

I have a task configuration that looks like this.
```
                - task: DownloadPipelineArtifact@2
                  displayName: Download Deployment Artifact 
                  inputs:
                    source: specific
                    project: $(System.TeamProject)
                    pipeline: $(app.ciPipeline)
                    runVersion: latestFromBranch
                    preferTriggeringPipeline: true
                    runBranch: ${{ parameters.runBranch }}
                    artifact: $(app.artifactName)
                    path: $(Pipeline.Workspace)/${{ stageParameters.functionapp }}-pipeline
```
Even though the pipeline was automatically triggered by a CI pipeline that ran on branch foobar, the `preferTriggeringPIpeline: true` doesn't seem to override any of the options. An older artifact is downloaded from the configured variables. 

### Task logs

I can privately share pipeline logs with Microsoft.
```
Starting: Download Deployment Artifact foobar project
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
Download from the specified build: #14395
Download artifact to: /agent/_work/1/foobar....
Minimatch patterns: [**]
Start downloading FCS artifact- blah blah 
Downloading: /agent/_work/1/blah / blah .zip
Downloading artifact finished.
Finishing: Download Deployment Artifact blah 
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
