### ISSUE TITLE
Unable to use deployment token from Bicep output in AzureStaticWebApp@0

### ISSUE THREAD

**Issue by joserosaswmda** [microsoft/azure-pipelines-tasks#15435]
## Note  
Hi thanks in advance,  I am trying to create a static web app with bicep, retrieve the deployment token and use that in the AzureStaticWebApp@0 azure_static_web_apps_api_token
main.bicep
```
param resourcePrefix string

@allowed([
  'dev'
  'prod'
])
param environmentName string

param tags object = {
  EnvironmentType: environmentName
  ApplicationTag: 'AngularFrontend'
  SourceTag: 'BICEP'
}

var staticSiteName = '${resourcePrefix}build'

resource staticSite 'Microsoft.Web/staticSites@2020-12-01' = {
  name: staticSiteName
  tags: tags
  location: resourceGroup().location
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    // The provider, repositoryUrl and branch fields are required for successive deployments to succeed
    // for more details see: https://github.com/Azure/static-web-apps/issues/516
    provider: 'DevOps'
    repositoryUrl: 'https://dev.azure.com/somecompany/somerepo/_git/somerepo'
    branch: 'master'
    buildProperties: {
      skipGithubActionWorkflowGeneration: true
    }
  }
}


output deployment_token string = listSecrets(staticSite.id, staticSite.apiVersion).properties.apiKey

```

azure-pipeline.yml
```
trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  azConfig : https://test.com
  resourceGroupName: 'jose-angular-test'
  location: 'West Europe'
  templateFile: './deploy/environment/main.bicep'
  environment: 'prod'

stages:
  - stage : infrastructure
    displayName: 'Build Infrastructure'
    jobs:
      - job: build
        steps:
          - task: AzureCLI@2
            name: DeployBicep
            inputs:
              azureSubscription: 'my subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az --version
                az group create --name $(resourceGroupName) --location $(location)
                az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters resourcePrefix="angular-test" environmentName=$(environment)
                output=$(az deployment group show --resource-group '$(resourceGroupName)' --name main --query properties.outputs.deployment_token.value)
                echo $output
                echo "##vso[task.setvariable variable=deploymentToken;isoutput=true]$output"
  - stage: build
    displayName: 'Build Application'
    dependsOn: infrastructure
    variables:
      deploymentToken: $[stageDependencies.infrastructure.build.outputs['DeployBicep.deploymentToken']]
    jobs:
      - job: build
        displayName: 'Run Npm Install and build with tokenized environment'
        steps:
          # some jobs here not included just to build the app
          - task: AzureStaticWebApp@0
            name: DeployStaticWebAPP
            inputs:
              app_location: './app/artifact/dist/'
              output_location: 'dist'
              skip_app_build: true
            env:
              azure_static_web_apps_api_token: $(deploymentToken)

````
Result when running this pipeline is always deployment_token provided was invalid.
I have echoed the deployment token in the second stage to confirm value is matching with resource create and its the correct token passed to AzureStaticWebApp.
![image](https://user-images.githubusercontent.com/73114648/138703990-754ff8a2-0994-4c8d-920b-0f196866793b.png)

**Comment by joserosaswmda** [comment]
any help is appreciated.

**Comment by alexander-smolyakov** [comment]
@bishal-pdMSFT could you please take a look at this issue?

**Comment by joserosaswmda** [comment]
any updates on this? Its still unresolved for me.

**Comment by sbugalski** [comment]
Same here.

Related to #15415 and #15154
```
/agent/_work/_temp/azureclitaskscript1640280374175.sh: line 8: MYVAR: command not found
You can use macro syntax for variables: 
```

Task:
```yaml
          - task: AzureCLI@2
            displayName: 'Job prepare'
            inputs:
              azureSubscription: $(ARM_CONNECTION)
              scriptType: bash
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -euo pipefail
                az account set -s $(SUBSCRIPTIONID)
                echo "##vso[task.setvariable variable=MYVAR;]foo"
                echo "You can use macro syntax for variables: $(MYVAR)"
```
