### ISSUE TITLE
[error]No value was found for the provided environment variable.

### ISSUE THREAD

**Issue by woeterman94** [microsoft/azure-pipelines-tasks#15450]
I'm trying to release a nuget package for my .NET project

In my YAML I'm using
```
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - domain.azure-pipelines.yml
	  
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]


stages:
  - stage: Build
    displayName: Build and Push

    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: restore
              projects: "**/BuildingBlocks.Domain.csproj"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              projects: "**/BuildingBlocks.Domain.csproj"

      - job: Push_Package
        dependsOn: Build
        displayName: "Push image"
        condition: eq(variables.isMaster, true)
        pool:
          vmImage: ubuntu-latest
          variables:
            majorMinorVersion: 1.0
            packageVersion: $[format('{0}.{1}', $(majorMinorVersion), counter($(majorMinorVersion), 0))]
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet pack"
            inputs:
              command: pack
              packagesToPack: BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
              versioningScheme: byEnvVar
              versionEnvVar: packageVersion

          - task: NuGetCommand@2
            displayName: "NuGet push"
            inputs:
              command: push
              publishVstsFeed: "..."
              allowPackageConflicts: true
```
The dotnet pack part is failing. I get the error ##[error]No value was found for the provided environment variable.
When enabling system diagnostics I see the variable packageVersion is undefined indeed.

I tried using             
`packageVersion: $[format('{0}.{1}', variables['majorMinorVersion'], counter(variables['majorMinorVersion'], 0))]
`
But that doesn't work as well.

What am I doing wrong?  I am setting the variable in my job. Why can I not use it?
