### ISSUE TITLE
Azure Powershell task gets INPUT_SCRIPTARGUMENTS wrong in log, if one is an azure portal URL

### ISSUE THREAD

**Issue by vincebowdren** [microsoft/azure-pipelines-tasks#15462]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowershell 

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - tribalgroup, EdgePlatform, pipeline 1705

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

## Issue Description

When parameters are passed into a script run by the AzurePowershell task running in debug mode, these parameters are logged as INPUT_SCRIPTARGUMENTS. This works fine normally, but if one of the parameters contains an azure portal URL then the logging goes wrong:
  - one or more of the parameters goes missing entirely
  - part of the azure portal URL is not printed; it is replaced by asterisks *** as if the value were a secret (which it is not)

### Task logs

Sample task for reproducing the problem:

```
  - task: AzurePowerShell@5
    displayName: 'Reproducing Script Parameter Problem'
    inputs:
      azureSubscription: redacted
      scriptType: inlineScript
      ScriptArguments: >
        -parameterA "https://url-parameter-A.example.com"
        -parameterB "https://url-parameter-B.example.com"
        -parameterC "https://portal.azure.com/#@tribalgroup.onmicrosoft.com/resource/subscriptions/placeholdersubscriptionId/resourceGroups/placeholderResourceGroupName/providers/Microsoft.EventGrid/partnerNamespaces/placeholderEGPN/eventChannels"
        -parameterD "https://url-parameter-D.example.com"
      inline: |
        Write-Host "If this were a separate script with params, it would get the correct values for all 4 parameters, I assure you"
        # param ($parameterA, $parameterB, $parameterC, $parameterD)
        # Write-Host "parameterA is: $parameterA"
        # Write-Host "parameterB is: $parameterB"
        # Write-Host "parameterC is: $parameterC"
        # Write-Host "parameterD is: $parameterD"
      azurePowerShellVersion: LatestVersion
      FailOnStandardError: true
```

(of course normally ScriptArguments would be used with a powershell script file, not an inline script; however to make it easy for you to reproduce I have used an inline script task here)

> ##[debug]INPUT_SCRIPTARGUMENTS: '-parameterA "https://url-parameter-A.example.com" -parameterB "https:***@tribalgroup.onmicrosoft.com/resource/subscriptions/placeholdersubscriptionId/resourceGroups/placeholderResourceGroupName/providers/Microsoft.EventGrid/partnerNamespaces/placeholderEGPN/eventChannels" -parameterD "https://url-parameter-D.example.com"'

Note the mistakes in that output:
1. the value for parameterB is missing
2. the name for parameterC is missing
3. the value for parameterC is not correct; the part at the start "https://portal.azure.com/#@" is mostly missing; the forward-slashes, the domain, and the hash character # are all replaced with a set of three asterisks.
