### ISSUE TITLE
PowershellV2 - Secret variables visible in event logs (4103) as plaintext when module logging is enabled

### ISSUE THREAD

**Issue by LeoVisser** [microsoft/azure-pipelines-tasks#15465]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowershellV2 

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: in multiple envirioments

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: every private agent running windows

## Issue Description

We are in a situation where sometimes we have azure devops agent running on servers which are co-managed by both us (IT Outsourcing party) and a customer or another IT oursourcing party they have.
Because of this we wanted to check that secrets passed in the pipelines aren't stored somewhere in the logs. Especially API keys we use to communicate with internal and 3rd party services.
So I set up a VM in azure (Windows Server 2019 Datacenter) where I installed the devops agent on (agent version: 2.194.0).
The envirioment where we work it likes to audit a lot so I enabled the following policies on the VM:

1. **User Configuration\Powershell Core\Turn on Module Logging**
Use windows powershell policy settings = true
Module Names = *
2. **User Configuration\Powershell Core\Turn on Powershell script block logging**
All options enabled
3. **User Configuration\Windows Components\Powershell\Windows Turn on Module Logging**
Module Names = *
4. **User Configuration\Windows Components\Windows Powershell\Turn on Powershell script block logging**
All options enabled

The azure devops agent was set up to run under the same account as where the policies where applied.
I then made the following three pipelines:

**secret-variable.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Test Pool

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if($env:MAPPED_TESTVAR -like "*C1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }

    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar) # the recommended way to map to an env variable
```
I've created a secret variable in this pipeline
![secret_pipeline1](https://user-images.githubusercontent.com/58498958/139814269-6805ceca-dae7-469e-8543-b5edaafc7f13.png)

**secret-variablegroup.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Test Pool

variables:
- group: VarGroup

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if($env:MAPPED_TESTVAR -like "*D1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }

    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar2) # the recommended way to map to an env variable
```
I've created a variable group with a secret value
![secret_pipeline2](https://user-images.githubusercontent.com/58498958/139814233-39e22f09-a8b6-489e-920f-24e9014f48a0.png)

**secret-akv.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Test Pool

variables:
- group: VarGroupAKV

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if($env:MAPPED_TESTVAR -like "*E1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }

    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar3) # the recommended way to map to an env variable
```
I've created a azure key vault which is connected to a variable group that is used
![secret_pipeline3](https://user-images.githubusercontent.com/58498958/139814182-227b2cc7-cb7d-4119-8f58-e2156e4b49ce.png)

After this I checked the agent VM to see if I could find the secrets in the logs. I've used these secrets:

TestVar = AABBCC112233
TestVar2 = AABBDD112244
TestVar3 = AABBEE112255

Via powershell I gathered the powershell and powershell core logs and then queried them for the secret I used. These are the results for all three secrets:

**TestVar**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBCC112233*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/1/2021 11:01:32 AM         4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBCC112233"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = da2aa33f-a8a7-4599-97ce-85b7f5db9c00
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\powershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = 32077bfb-9316-4d5b-94d2-ec6fac29abe2
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 182
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

**TestVar2**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBDD112244*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/1/2021 11:02:07 AM         4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBDD112244"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = c580fdf7-aa50-48fe-a3aa-5856735d0641
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\powershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = a9c1dcb2-eb74-43d1-80ea-1f96c5876dd0
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 190
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

**TestVar3**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBEE112255*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/1/2021 11:02:43 AM         4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBEE112255"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = 01c2cd3f-a5ff-4c96-8aea-6c9d67e6975b
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\powershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = 0c071e73-f80e-4a86-9b95-c9c8dc83f042
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.190.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 182
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

As you see all three methodes seem to have a powershell command running to convert something to a secure string which is logged in the 4103 logs. I was wondering if this was a bug because as far as I'm aware I'm using the recommended methode from [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) which also warns for OS logging. So I was hoping this way would make sure it wasn't logged in the OS.
This problem is also present in the Azure Powershell task. Made a seperate issue for that one:
https://github.com/microsoft/azure-pipelines-tasks/issues/15485
