### ISSUE TITLE
DotNetCoreCLI@2 publish command incorrectly excludes a valid web project when publishWebProjects=true

### ISSUE THREAD

**Issue by dmaassen** [microsoft/azure-pipelines-tasks#15469]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

This task:
```

- task: DotNetCoreCLI@2
  inputs:
   command: publish
   publishWebProjects: True
   arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
   zipAfterPublish: True
```

is being used to publish two ASP.NET Core API projects that belong in the same solution.

As soon as a `web.config` is introduced to **one** of the projects, the project **without** the `web.config` is no longer published.

## Troubleshooting
The root cause seems to be here: [relevant pipeline code](https://github.com/microsoft/azure-pipelines-tasks/blob/019f20abce0f61483356ea392916ccf6fd6672eb/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L357).

The code does not handle the case when both `web.config` and `isWebSdkUsed` project filters return valid project files from a solution.

We came up with two workarounds:
- add a dummy `web.config` to the other project. Not an ideal solution.
- set `publishWebProjects=false` and pass in a `projects` argument that specifies the projects to publish

Similar issue: [DotNetCli task incorrectly identifies Razor class library projects as web projects when publishWebProjects is 'true'](https://github.com/microsoft/azure-pipelines-tasks/issues/14806).
