### ISSUE TITLE
Cache step error in pipeline: CaptureResult has already been called for action PipelineCache.RestoreCache

### ISSUE THREAD

**Issue by bgranados** [microsoft/azure-pipelines-tasks#15475]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines    

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
An error is found at the end of npm cache step:

This is a template called from another yaml, tests.yml
```
steps:
- download: Build
  artifact: BuildResult

- task: Cache@2
  inputs:
    key: 'cypress | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/Api/package-lock.json'
    restoreKeys: cypress | "$(Agent.OS)"
    path: $(cypress_cache_folder)
    cacheHitVar: IsCypressCacheRestored
  displayName: Cache cypress

# Npm install
- task: Npm@1
  inputs:
    command: custom
    customCommand: ci
    workingDir: src/Api/
  env:
    NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  displayName: Install npm packages

# Run cypress tests
- task: PowerShell@2
  displayName: 'Handle user and run tests'
  inputs: 
    targetType: 'filePath'
    filePath: 'src/Api/cypress/cypress.ps1'
    workingDirectory: 'src/Api/'
    arguments: >
      run
      -server https://$(testUrl)
  condition: succeeded()

# Publish results
- task: PublishTestResults@2
  displayName: "Publish Cypress Results"
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: "src/Api/cypress/results/cypress-e2e-*.xml"
    failTaskOnFailedTests: true
    mergeTestResults: true
    testRunTitle: "Cypress Tests"
  condition: succeededOrFailed()
```

### Task logs

Resolving key:
 - cypress                                            [string]
 - "Linux"                                            [string]
 - /home/vsts/work/1/integrationTests/src/Api [file] --> 645F38D01CB99957D4A48389885FF335C2ACD473E2D2C3DF803FB561C84FAB5B
Resolved to: cypress|"Linux"|BJlokX07zKfm11IBqp2aYUhBy3Ui+ccwgTcZ/EniilM=
Resolving restore key:
 - cypress [string]
 - "Linux" [string]
Resolved to: cypress|"Linux"|**
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session eb399d50-6a51-438c-bf74-062af15df110
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `cypress|"Linux"|BJlokX07zKfm11IBqp2aYUhBy3Ui+ccwgTcZ/EniilM=`
Fingerprint: `cypress|"Linux"|**`
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `cypress|"Linux"|BJlokX07zKfm11IBqp2aYUhBy3Ui+ccwgTcZ/EniilM=`
Fingerprint: `cypress|"Linux"|**`
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `cypress|"Linux"|BJlokX07zKfm11IBqp2aYUhBy3Ui+ccwgTcZ/EniilM=`
Fingerprint: `cypress|"Linux"|**`
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `cypress|"Linux"|BJlokX07zKfm11IBqp2aYUhBy3Ui+ccwgTcZ/EniilM=`
Fingerprint: `cypress|"Linux"|**`
ApplicationInsightsTelemetrySender correlated 5 events with X-TFS-Session eb399d50-6a51-438c-bf74-062af15df110
**##[error]CaptureResult has already been called for action PipelineCache.RestoreCache
Finishing: Cache cypress**

### Error logs

**##[error]CaptureResult has already been called for action PipelineCache.RestoreCache**

The result is that we cannot cache npm. This step is in a template called from another yaml. In either the template or the calling pipeline yaml, there is not another cache step.

**Comment by johnterickson** [comment]
```
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Unable to find pipeline caching scopes. 
```

Huh, is this running in a Release? Cache only works in Builds.

**Comment by bgranados** [comment]
Alright, sounds like we misused the Caching task. Thanks for your response!

**Comment by zordark** [comment]
Good day, was this bug fixed? 
Because we have the same issue for our pipeline on "cache node_modules" task 

```
resources:
  pipelines:
  - pipeline: build
    source: build
    trigger:
      branches:
        include:
        - develop
variables:
- group: variable-group-dev
trigger:
  enabled: false
pr:
  enabled: false
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Deploy
  displayName: Deploy Dev
  jobs:
  - job: Deploy
    timeoutInMinutes: 0
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      displayName: 'use python 3'
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - task: CmdLine@2
      displayName: 'pip install aws cli'
      inputs:
        script: pip3 install awscli
    - task: Cache@2
      displayName: cache node_modules
      inputs:
        key: 'npm1 | "$(Agent.OS)" | $(Build.SourcesDirectory)/cdk/package-lock.json'
        restoreKeys: |
          npm1 | "$(Agent.OS)"
        path: $(Build.SourcesDirectory)/cdk/node_modules
    - task: CmdLine@2
      displayName: 'npm install'
      inputs:
        script: npm install
        workingDirectory: cdk

... remain part omitted 
```
