### ISSUE TITLE
AzurePowerShellV5 - Secret variables visible in event logs (4103) as plaintext when module logging is enabled

### ISSUE THREAD

**Issue by ghost** [microsoft/azure-pipelines-tasks#15485]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: in multiple envirioments

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: every private agent running windows

## Issue Description

We are in a situation where sometimes we have azure devops agent running on servers which are co-managed by both us (IT Outsourcing party) and a customer or another IT oursourcing party they have.
Because of this we wanted to check that secrets passed in the pipelines aren't stored somewhere in the logs. Especially API keys we use to communicate with internal and 3rd party services.
So I set up a VM in azure (Windows Server 2019 Datacenter) where I installed the devops agent on (agent version: 2.194.0).
The envirioment where we work it likes to audit a lot so I enabled the following policies on the VM:

1. **User Configuration\Powershell Core\Turn on Module Logging**
Use windows powershell policy settings = true
Module Names = *
2. **User Configuration\Powershell Core\Turn on Powershell script block logging**
All options enabled
3. **User Configuration\Windows Components\Powershell\Windows Turn on Module Logging**
Module Names = *
4. **User Configuration\Windows Components\Windows Powershell\Turn on Powershell script block logging**
All options enabled

The azure devops agent was set up to run under the same account as where the policies where applied.
I then made the following three pipelines:

**azure-secret-variable.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: Test Pool

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<<REDACTED>>'
    ScriptType: 'InlineScript'
    Inline: |
      if($env:MAPPED_TESTVAR -like "*C1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar1) # the recommended way to map to an env variable
```
I've created a secret variable in this pipeline
![azure_secret_pipeline1](https://user-images.githubusercontent.com/58498958/140777576-6fe8cdff-e863-462d-b893-2fcdd57e9135.png)

**azure-secret-variablegroup.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: Test Pool

variables:
- group: VarGroup

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<<REDACTED>>'
    ScriptType: 'InlineScript'
    Inline: |
      if($env:MAPPED_TESTVAR -like "*D1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar2) # the recommended way to map to an env variable
```
I've created a variable group with a secret value
![secret_pipeline2](https://user-images.githubusercontent.com/58498958/140777819-29b22298-824b-4e1c-a43b-4f5add2b5a3c.png)

**azure-secret-akv.yml**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: Test Pool

variables:
- group: VarGroupAKV

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<<REDACTED>>'
    ScriptType: 'InlineScript'
    Inline: |
      if($env:MAPPED_TESTVAR -like "*E1*") {
        Write-Host "yes"
      }
      else {
        Write-Host "no"
      }
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  env:
    MAPPED_TESTVAR: $(TestVar3) # the recommended way to map to an env variable
```
I've created a azure key vault which is connected to a variable group that is used
![secret_pipeline3](https://user-images.githubusercontent.com/58498958/140777948-b57b6d0b-57da-4df1-947d-0dfa303aa5d9.png)

After this I checked the agent VM to see if I could find the secrets in the logs. I've used these secrets:

TestVar = AABBCC112233
TestVar2 = AABBDD112244
TestVar3 = AABBEE112255

Via powershell I gathered the powershell and powershell core logs and then queried them for the secret I used. These are the results for all three secrets:

**TestVar**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBCC112233*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/8/2021 4:00:51 PM          4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBCC112233"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = 58669cb3-0655-47ae-82b0-9ca2f06ec87f
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\azurepowershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = 6989e731-5e08-458b-aadb-b23760eb1e0c
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 370
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

**TestVar2**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBDD112244*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/8/2021 4:03:12 PM          4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBDD112244"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = 76f0873b-fd70-45b9-bc43-4ba03717f6dc
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\azurepowershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = e5414503-e1f4-4362-99d4-4889b4ad1666
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 378
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

**TestVar3**
```
PS C:\Users\ICT> $logs = Get-WinEvent @('PowerShellCore/Operational','Microsoft-Windows-PowerShell/Operational')
PS C:\Users\ICT> $filter = $logs | Where-Object {($_.Message -like "*AABBEE112255*")}
PS C:\Users\ICT> $filter

   ProviderName: Microsoft-Windows-PowerShell

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11/8/2021 4:06:06 PM          4103 Information      CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString…

PS C:\Users\ICT> $filter[0].Message
CommandInvocation(ConvertTo-SecureString): "ConvertTo-SecureString"
ParameterBinding(ConvertTo-SecureString): name="String"; value="AABBEE112255"
ParameterBinding(ConvertTo-SecureString): name="AsPlainText"; value="True"
ParameterBinding(ConvertTo-SecureString): name="Force"; value="True"


Context:
        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.17763.2183
        Host ID = df28782c-acf1-4d71-81cf-58d8ca1b50ca
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\azurepowershell.ps1'''))
        Engine Version = 5.1.17763.2183
        Runspace ID = c112c160-742c-4137-8cab-a219d28d8f7d
        Pipeline ID = 1
        Command Name = ConvertTo-SecureString
        Command Type = Cmdlet
        Script Name = C:\agent\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.185.0\ps_modules\VstsTaskSdk\InputFunctions.ps1
        Command Path =
        Sequence Number = 370
        User = adoworkeragent\ICT
        Connected User =
        Shell ID = Microsoft.PowerShell


User Data:


PS C:\Users\ICT>
```

As you see all three methodes seem to have a powershell command running to convert something to a secure string which is logged in the 4103 logs. I was wondering if this was a bug because as far as I'm aware I'm using the recommended methode from [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) which also warns for OS logging. So I was hoping this way would make sure it wasn't logged in the OS.
This same problem was also reported for the normal powershell task here:
https://github.com/microsoft/azure-pipelines-tasks/issues/15465
