### ISSUE TITLE
Task reports failure even though it succeeds... TypeError: Cannot read property 'updateStartupCommandAndRuntimeStack' of undefined

### ISSUE THREAD

**Issue by tompi** [microsoft/azure-pipelines-tasks#15498]
*Type*: Bug
**Enter Task Name**: AzureWebAppV1

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
       LaerdalMedical, Laerdal Global Health:
       https://dev.azure.com/LaerdalMedical/Laerdal%20Global%20Health/_releaseProgress?_a=release-environment-logs&releaseId=250&environmentId=508

- Agent - Hosted
    - If using Hosted agent, provide agent queue name:

## Issue Description
Getting this error message when trying to deploy dotnet core 5.0 webapp to Linux app service:
```
TypeError: Cannot read property 'updateStartupCommandAndRuntimeStack' of undefined
```
BUT, everything SEEMS to be fine... (webapp is deployed...)

### Task logs
[tasklog_6.log](https://github.com/microsoft/azure-pipelines-tasks/files/7528060/tasklog_6.log)

**Comment by v-jkarri** [comment]
Can you please share your task configuration screen or YML steps for this task?

**Comment by v-jkarri** [comment]
Since long time we didn't get any response. We are temporarily closing this issue now. Please feel free to reopen the issue if you are still facing the issue.

**Comment by henrikx** [comment]
@v-jkarri This is still an issue and wrongfully closed.

Sample YML:
```yaml
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'TestDeploy-ServiceConnection'
              appType: 'webAppLinux'
              appName: 'test'
              deployToSlotOrASE: true
              resourceGroupName: 'resourcegroup'
              slotName: 'production'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
```
Azure Subscription in this case is a Publish Profile Service Connection.

As OP explains, webapp is deployed and everything seems fine, but yet the pipeline is failing.

Elsewhere a few have suggested to fill in the parameters `runtimeStack` and `startUpCommand`, but this does not resolve the issue.
