### ISSUE TITLE
xcode task: Help Requested : embedded.mobileprovision isn't updated with entitlements

### ISSUE THREAD

**Issue by alimdi** [microsoft/azure-pipelines-tasks#15506]
Hi,

I'm using xcode@5 with following config :

```
    inputs:
      actions: "build"
      configuration: "${{ parameters.appleConfiguration }}"
      sdk: "iphoneos"
      xcWorkspacePath: './src/APP/ios/app/app.xcworkspace'
      scheme: 'APP-${{ parameters.env }}'
      packageApp: true
      exportPath: "output"
      signingOption: "manual"
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileName: '$(APPLE_PROV_PROFILE_UUID)'
      publishJUnitResults: true
      xcodeVersion: "default"
      args: '-derivedDataPath $(build.Repository.LocalPath)/APP/'
```

The provided mobileprovision with InstallAppleProvisioningProfile@1 contains default entitlements that needs to be updated.
To do so, I've added entitlement file with custom values and was expecting to find them in embedded.mobileprovision located in the archive.

After digging into the different phases of the process :

1. The build :

`/usr/bin/xcodebuild -sdk iphoneos -configuration Development -workspace /Users/runner/work/1/s/src/APP/ios/app/app.xcworkspace -scheme APP-dev build -derivedDataPath /Users/runner/work/1/s/APP/ CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=iPhone Distribution: XXX PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=YYYY`

The build is successful and logs shows that the entitlements are updated through xcent file which is containing the expected values

`/usr/bin/codesign --force --sign XXX --entitlements /Users/runner/work/1/s/APP/Build/Intermediates.noindex/App.build/Development-iphoneos/APP.build/APP.app.xcent --timestamp\=none --generate-entitlement-der /Users/runner/work/1/s/APP/Build/Products/Development-iphoneos/APP.app`

**At this point the embedded.mobileprovision file is still containing initial, non updated entitlements.
Is that expected ?**

2. The archive: 

`/usr/bin/xcodebuild -workspace /Users/runner/work/1/s/src/APP.Mobile/ios/app/app.xcworkspace -scheme APP-dev archive -sdk iphoneos -configuration Development -archivePath /Users/runner/work/1/s/APP-dev CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=XXX PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=XXX -derivedDataPath /Users/runner/work/1/s/XXX/`

The packaging is successful and the XCODEBUILD_ARCHIVE_LOG shows the new entitlements.

**At this point the embedded.mobileprovision file is still containing initial, non updated entitlements.
Is that expected ?**

3. The signing :

It looks for the embedded.mobileprovision

```
##[debug]pattern: '**/embedded.mobileprovision'
##[debug]findPath: '/Users/runner/work/1/s/APP-dev.xcarchive'
##[debug]adjustedPattern: '/Users/runner/work/1/s/APP-dev.xcarchive/**/embedded.mobileprovision'
##[debug]1 matches
##[debug]1 final results
##[debug]1 iOS embedded.mobileprovision file(s) found.
##[debug]embedded prov profile = /Users/runner/work/1/s/APP-dev.xcarchive/Products/Applications/APP.app/embedded.mobileprovision
```

embedded.mobileprovision is still from origin without custom entitlements.
All the security commands are executed with that embedded.mobileprovision

`/usr/bin/security cms -D -i /Users/runner/work/1/s/APP-dev.xcarchive/Products/Applications/APP.app/embedded.mobileprovision`

**At this point the embedded.mobileprovision file is still containing initial, non updated entitlements.
Is that expected ?**

4. The export :

`/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/s/APP-dev.xcarchive -exportPath /Users/runner/work/1/s/output -exportOptionsPlist _XcodeTaskExportOptions.plist`

Export is successful, he DistributionSummary.plist shows the new entitlements but the embedded.mobileprovision bundled in the ipa is still the original one.

**At this point the embedded.mobileprovision file is still containing initial, non updated entitlements.
Is that expected ?**

Any clue on what's going wrong?
Thanks for helping out.
