### ISSUE TITLE
xcode multiple provision profile

### ISSUE THREAD

**Issue by abdullah007001** [microsoft/azure-pipelines-tasks#15500]
Following up on same topic, may i know if this has been addressed by Microsoft?
#13776
#8811

**Comment by abdullah007001** [comment]
displayName: "Apple[${{ parameters.envName }}]: Building Release Version"
      inputs:
        actions: 'build'
        sdk: 'iphoneos'
        scheme: 'App'
        configuration: ${{ parameters.configuration }}
        xcWorkspacePath: 'ios/App/App.xcworkspace'
        xcodeVersion: 'default'
        packageApp: true
        signingOption: 'manual'
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
        exportPath: '$(Build.SourcesDirectory)/ios/output/${{ parameters.envName }}'


How can i use two provisioningProfileUuid?

**Comment by wilgert** [comment]
We have the same issue. We want to implement [iOS Service Extensions](https://documentation.onesignal.com/docs/ionic-sdk-setup#ios-service-extensions) to receive rich push notifications. This requires our build to use 2 provisioning profiles. 
Since we can only have one `$(APPLE_PROV_PROFILE_UUID)` variable we can not make it work using the standard setup of Azure Pipelines.

**Comment by neoswallow** [comment]
You have to use export options plist file.
```
- task: Xcode@5
  displayName: "Apple[${{ parameters.envName }}]: Building Release Version"
  inputs:
    exportOptions: 'plist'
    exportOptionsPlist: '$(System.DefaultWorkingDirectory)/ios/_XcodeTaskExportOptions.plist'
    signingOption: 'default'
```
And this is a Github gist for sample plist: https://gist.github.com/skabber/4f2b20c6bd18e5934909189489549cce
