### ISSUE TITLE
WindowsMachineFileCopyV2 fails in a pipeline when using DFS

### ISSUE THREAD

**Issue by mc0re** [microsoft/azure-pipelines-tasks#15505]
## Required Information

**Bug**  
*Type*: YAML

**Enter Task Name**: WindowsMachineFileCopyV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - TFS on-premises
    - If using TFS on-premises, provide the version: 2020.1

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: default (shared pool)

## Issue Description

The pipeline runs under `user1`, the task uses `user2` to copy files to a protected directory.
```
    - task: WindowsMachineFileCopy@2
      displayName: 'Copy the installer to file share'
      inputs:
        SourcePath: 'unpacked'
        MachineNames: 'mycompany.net'
        AdminUserName: '$(CopyUser)'
        AdminPassword: '$(CopyPassword)'
        TargetPath: '$(CopyPath)'
        CleanTargetBeforeCopy: false
        CopyFilesInParallel: false
```

When the directory is given as a direct server path, the task works. When given as a DFS namespace, fails.

### Task logs

```
##[error]Failed to Create PSDrive with Destination: '\\mycompany.net\...\Applications', ErrorMessage: 'Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again'
```
