### ISSUE TITLE
Fallback branches for DownloadPipelineArtifact

### ISSUE THREAD

**Issue by stephenatwork** [microsoft/azure-pipelines-tasks#15541]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Feature*

**DownloadPipelineArtifact**

## Issue Description

It's a common task to consume some pipeline artifacts, and process them in some way.

For PRs, edits to the build.yamls exist on a *topic* branch, thus the artifacts are often not available (only available when CI has been run e.g. on develop or main branches).

So it would be excellent to have an option to download them from the current branch _if available_ or to fallback to a specific branch if not.

This could take the form of a new option or to allow runBranch to take several arguments (first one wins).

```yaml
- task: DownloadPipelineArtifact@2
          inputs:
            source: specific
            runVersion: latestFromBranch
            runBranch: |
                $(Build.SourceBranch)
                refs/heads/develop
```
