### ISSUE TITLE
AzurePowerShellV5 always warns to run Connect-AzureRmAccount to login

### ISSUE THREAD

**Issue by timmkrause** [microsoft/azure-pipelines-tasks#15555]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzurePowerShellV5

## Environment
- Server - TFS on-premises (Version Azure DevOps Server 2020 Update 1)
- Agent - Private: 

## Issue Description

When running a script with Azure PowerShell I do get the following warning:

`##[warning]Run Connect-AzureRmAccount to login.`

The script only utilizes the Az modules not AzureRM.

Warning is related to https://github.com/microsoft/azure-pipelines-tasks/issues/13890 but the solution does no apply here.

```
- task: AzurePowerShell@5
    displayName: 'OMITTED'
    inputs:
    azureSubscription: ${{ variables.azureServiceConnection }}
    scriptPath: $(OMITTEDScriptPath)
    scriptArguments: '-OMITTEDConfigurationJsonAsString ''OMITTED'''
    azurePowerShellVersion: latestVersion
    pwsh: true
```

```
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.179.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
```

### Task logs

[azure-powershell-warning.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7626431/azure-powershell-warning.zip)

### Error logs

`##[warning]Run Connect-AzureRmAccount to login.`
