### ISSUE TITLE
Docker@2 does not allow to use multiple connections.

### ISSUE THREAD

**Issue by DominikaSorn** [microsoft/azure-pipelines-tasks#15573]
*Type*: Bug

**Enter Task Name**: Docker@2

list here (V# not needed):  2
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description
I want to be able to interact with different ACRs depending on the stage of my pipeline. 
So having:

```
variables:
  - group: DEVVariables
  - group: TSTVariables

extends:
  template: /releases/deployment.yml
  parameters:
    stages:
      - name: Development
        variableGroups:
          - DEVVariables
      - name: Test
        variableGroups:
          - TSTVariables
```

and deployment.yml:
```
stages:
  - ${{ each stage in parameters.stages }}:
      - stage: ${{ stage.name }}
        variables:
          - ${{ each value in stage.variableGroups }}:
            - group: ${{ value }}
        jobs:
          - job: PostDeployment
            steps:
            - task: Docker@2
            displayName: Login to previous container registry
            inputs:
                command: login
                containerRegistry: $(dockerRegistryServiceConnection)
```

Each stage includes another variable group with dockerRegistryServiceConnection variable.
The problem is:
I need to declare all the variable groups at the root level. Otherwise, I've got build errors like in 
https://github.com/microsoft/azure-pipelines-tasks/issues/13350
But then, the value from the lastly declared group will be used in all stages.

## Troubleshooting
When you use my template and add a second step with "docker pull" I would break. 
Error is misleading and says: "not such image", but after my investigation, it's clear that I have no access.

**I'm using KubernetesManifest@0 task in the same way and it resolves a proper service connection.
Maybe you could use the same approach?**
