### ISSUE TITLE
HelmDeploy@0: unnecessary service connection at helm package

### ISSUE THREAD

**Issue by DrackThor** [microsoft/azure-pipelines-tasks#15591]
*Type*: Bug
**Enter Task Name**: HelmDeploy@0

## Environment
Azure DevOps Server 2020

## Issue Description

When using HelmDeploy@0 to update helm chart dependencies, as mentioned in #8374, I need to specify a Service Connection.
In this part of my pipeline I just want to package a helm chart, therefore I don't need a Service Connection imho.
So when using something like this..
```yaml
steps:
- task: HelmDeploy@0
  displayName: 'Add Service Catalog Helm Repo'
  enabled: true
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'repo'
    arguments: 'add svc-cat https://svc-catalog-charts.storage.googleapis.com'
```
... I don't want to be obliged to specify a Service Connection, because I simply don't need one.

Thanks in advance, D
