### ISSUE TITLE
Unable to stop web job (intermittent)

### ISSUE THREAD

**Issue by virtualvoid** [microsoft/azure-pipelines-tasks#15599]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureAppServiceManage  

## Environment
- Server - Azure Pipelines

## Issue Description
Sometimes the web job just can't be stopped (even if it is running). I can use the `continueOnError` set to **true**, however the resulting build will appear as "partially succeeded" which is quite annoying. Is there any possibility to add another switch, something like `ignoreError` which will happily, well, ignore that `CODE 404` and report as succeeded ?

## YAML
```
- task: AzureAppServiceManage@0
  displayName: 'Stop all continuous webjobs (if any)'
  inputs:
    azureSubscription: $(azsub)
    Action: 'Stop all continuous webjobs'
    WebAppName: $(waname)
  continueOnError: true

```
### Logs
`
[error]Error: Failed to stop continuous WebJob 'WebJobName'. Error: Not Found (CODE: 404)`
