### ISSUE TITLE
VSTest@2 on 'windows-2022': Could not load file or assembly 'System.Runtime, Version=6.0.0.0'

### ISSUE THREAD

**Issue by tymtam2** [microsoft/azure-pipelines-tasks#15607]
## Required Information

*Type*: Bug

**VSTest@2**: 

## Environment

Pipeline:
https://dev.azure.com/rbtech/Redback/_build/results?buildId=59050

- Agent - Hosted or Private: 

```
Starting: Initialize job
Agent name: 'Azure Pipelines 3'
Agent machine name: 'fv-az532-646'
Current agent version: '2.195.2'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20211206.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DotNetCoreCLI (2.187.0)
Downloading task: VSTest (2.195.0)
Downloading task: PublishPipelineArtifact (1.2.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

```    

## Issue Description

Having the following unit test task:

```
pool:
  name: Azure Pipelines
  vmImage: 'windows-2022' # Needed for .NET6 'windows-latest' did not work 2021 Dec

(...)

- task: VSTest@2
  displayName: "Run unit tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    minimumExpectedTests: 1
    failOnMinTestsNotRun: true
```

the task doesn't run any tests and it reports `Could not load file or assembly 'System.Runtime, Version=6.0.0.0`:

```
[MSTest][Discovery][...] Failed to discover tests from assembly D:\a\1\s\aaa\bin\Release\net6.0\aaa.dll. Reason:Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Tests run correctly when run locally. This issue happens only on Azure Pipelines.

### Task logs

[UnitTests.Failed.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7715391/UnitTests.Failed.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
Failed to discover tests from assembly D:\a\1\s\TymTam.Factory.API.Tests\bin\Release\net6.0\TymTam.Factory.API.Tests.dll. Reason:Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

**Comment by tymtam2** [comment]
The issue goes away - the test task finds the tests and runs them - after installing .net 6 explicitly.

```
steps:
- task: UseDotNet@2 # 2021-Dec Needed for running Unit Test, otherwise https://github.com/microsoft/azure-pipelines-tasks/issues/15607
  displayName: 'Install .net6 runtime (required for running Unit Tests only)'
  inputs:
    packageType: 'runtime'
    version: '6.x'
```
