### ISSUE TITLE
vsBuild ignoring Java version set via JavaToolInstaller

### ISSUE THREAD

**Issue by carbon-paulc** [microsoft/azure-pipelines-tasks#15658]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSBuild

## Environment
- Server - Azure Pipelines

- Agent - Hosted windows-latest

## Issue Description
Trying to build a MultiTargeted project that targets Android, iOS and Standard.  This has been working okay, until recently we upddated the build target for Android to monoandroid12.  The project will build locally, however, on the pipeline it errors with:

` Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0. `

After a bit of research we tried the JavaToolInstaller to use version 11, this seems to set the java versions correctly, however, when VSBUILD runs it still seems to find the 1.8.0 version:
```
_ResolveAndroidTooling:
  Found Java SDK version 1.8.0.
```

relevant YAML:
```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: CmdLine@2
  inputs:
    script: |
      echo %JAVA_HOME%
      javac -version
      java -version

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

### Task logs
JavaToolInstaller:
```
Starting: JavaToolInstaller
==============================================================================
Task         : Java tool installer
Description  : Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME
Version      : 0.194.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/java-tool-installer
==============================================================================
Use preinstalled JDK from C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64
JAVA_HOME is being set to: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64
JAVA_HOME_11_X64 is being set to: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64
Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64\bin
Finishing: JavaToolInstaller

```

CmdLine Output:
```
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64
javac 11.0.13
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

```

VSBUILD:
```
_ResolveAndroidTooling:
  Found Java SDK version 1.8.0.
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(265,5): Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.  Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(265,5): error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.  Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 [D:\a\1\s\Kingdom.Shared.Ui\Kingdom.SharedUi\Kingdom.SharedUi.csproj]

```

**Comment by carbon-paulc** [comment]
After more expermienting it would seem that i needed the vsVersion of 17 and to get this the agent pool to be 'windows-2022'

After changing YAML to below it worked:
```
pool:
  vmImage: 'windows-2022'

...

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: "17.0"

```
