### ISSUE TITLE
publishTestResults does not work for dotnet test when setting results-directory

### ISSUE THREAD

**Issue by sxmanton** [microsoft/azure-pipelines-tasks#15663]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCli@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

When using the --results-directory flag along with `publishTestResults: true`, the .trx file is generated but the publishing fails with a warning that no results file was found

My task looks like this:

```yml
- task: DotNetCoreCLI@2
      displayName: 'Run unit tests' 
      inputs:
        command: 'test'
        nobuild: true
        arguments: > 
          --configuration $(buildConfiguration)
          --collect:"XPlat Code Coverage"
          --settings coverlet.runsettings
          --results-directory ./coverage
        projects: '**/*.Tests.csproj'
        publishTestResults: true
```

Relevant bit of log:

```
Results File: D:\a\1\s\coverage\VssAdministrator_fv-az344-300_2022-01-06_18_53_13.trx

Attachments:
  D:\a\1\s\coverage\300c14cf-5aa0-4878-8ae4-93ad6acdb6e2\coverage.cobertura.xml
Passed!  - Failed:     0, Passed:     7, Skipped:     0, Total:     7, Duration: 76 ms - MyLib.Tests.dll (net6.0)
##[warning]No test result files were found.
```
