### ISSUE TITLE
Gradle Task is overwriting gradlew file, altering the repository into a commit-dirty state

### ISSUE THREAD

**Issue by djechelon** [microsoft/azure-pipelines-tasks#15668]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle 

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Organization: TheAvantGardeGroup
Project: AML Controlli
Build definition: AML Controlli-BE-Development.
Build ID: 20220110.9

- Agent - Hosted or Private: 
    
Hosted, but I can't find the queue name

## Issue Description

Gradle task overwrites gradlew file, resulting in a dirty repository that [`reckon`](https://github.com/ajoberstar/reckon) refuses to tag.
I have a complex build pipeline made using templates, detailed in a subsequent post, where the complexity is mainly about parameterization and reuse of same pipeline.

It can be summarized as
- Login to Maven
- Login to ACR
- Prepare SonarCloud
- **Run Gradle** (clean publish)
  - clean
  - build Java
  - build Test
  - run JUnit
  - run Jib (build Docker)
  - Tag the repository with reckon
  - Push
- Publish SonarCloud analysis
- Publish coverage reports and unit tests reports
- Logout from ACR

When Gradle runs, it executes the tasks descripted at 2nd level. My build file is fairly complex, so I'll be providing log

**The expected result** is that Gradle never _touches_ the repository. Assuming the gitignores are set up correctly, Gradle should build in the ignored folder(s) and keep repository clean. This happens locally, as `reckon` can tag the repository

```
            - task: Gradle@3
              displayName: Publish with Gradle
              inputs:
                gradleWrapperFile: gradlew
                gradleOptions: -Xmx10240m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
                options: -Pci=true -PbuildId=$(Build.BuildId) -Preckon.stage=FINAL -Preckon.scope=${{parameters.versionScope}}
                jdkVersionOption: 1.11
                jdkArchitectureOption: x64
                publishJUnitResults: true
                sqAnalysisEnabled: true
                sqGradlePluginVersionChoice: specify
                sqGradlePluginVersion: 3.2.0
                testResultsFiles: '$(System.DefaultWorkingDirectory)/build/test-results/**/TEST-*.xml'
                tasks: clean publish
              env:
                IT_ORBIT_FILE_REPOSITORY_AZURE_STORAGE_CONNECTION_STRING: ${{variables.testStorageAccountConnectionString}}

```

What happens is that:

1. Reckon Gradle plugin complains about repository in dirty state, refuses to work, the pipeline fails
2. I have investigated with a simple `git status` command and looks like `gradlew` script is modified

Note: the error in the pipeline execution is a **feature** of Reckon Gradle Plugin, but shouldn't be triggered

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

[logs_6074.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7838399/logs_6074.zip)

## Troubleshooting

I have "wrapped" the above Gradle task with a couple of `git status commands`. After the Gradle task, looks like gradlew script is modified.

This is a problem in my scenario.

Locally, the gradlew script is **never** overwritten.
I guess this is a problem with Azure DevOps Gradle task

### Error logs
```
Downloading https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Script '/home/vsts/work/1/s/gradle/jib.gradle' line: 13

* What went wrong:
A problem occurred evaluating script.
> Cannot release a final or significant stage without a clean repo.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
Error: The process '/home/vsts/work/1/s/gradlew' failed with exit code 1
```

**Comment by djechelon** [comment]
Full `azure-pipelines.yaml`

```
parameters:
  # true to publish a Docker artifact to the Registry, false to keep the build local
  - name: publish
    type: boolean
    #
  - name: versionScope
    type: string
    default: patch
    values:
      - major
      - minor
      - patch
  - name: versionStage
    type: string
    default: SNAPSHOT
    values:
      - SNAPSHOT
      - FINAL

stages:
  - stage: Build
    variables:
      # Build
      vstsFeed: ....
      buildArtifactName: aml-controlli-be

      # SonarCloud parameters
      sonarCloudOrganization: regtechopenproject
      sonarCloudProjectKey: TheAvantGardeGroup_aml-controlli-be
      sonarCloudProjectName: aml-controlli-be

    jobs:
      - job: Build
        displayName: Build application

        pool:
          vmImage: ubuntu-20.04
        steps:

          - checkout: self
            persistCredentials: true

          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'AVG_RTOP_Feed'

              # Docker ACR Login
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: AVG Orbit Registry

            # SonarCloud Prepare Analysis
          - task: SonarCloudPrepare@1
            displayName: SonarCloud Prepare Analysis
            inputs:
              SonarCloud: 'SonarCloud'
              organization: $(sonarCloudOrganization)
              scannerMode: 'Other'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                sonar.exclusions=**/*.bin, build/**, build-extra/**
                sonar.projectKey=$(sonarCloudProjectKey)
                sonar.projectName=$(sonarCloudProjectName)

          - script: git status
            displayName: Git status
            condition: succeededOrFailed()

          - ${{ if eq(parameters.publish, false) }}:

              - task: Gradle@3
                displayName: Build with Gradle
                inputs:
                  gradleWrapperFile: gradlew
                  gradleOptions: -Xmx10240m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
                  options: -Pci=true -PbuildId=$(Build.BuildId) -Preckon.stage=${{parameters.versionStage}} -Preckon.scope=${{parameters.versionScope}}
                  jdkVersionOption: 1.11
                  jdkArchitectureOption: x64
                  publishJUnitResults: true
                  sqAnalysisEnabled: true
                  sqGradlePluginVersionChoice: specify
                  sqGradlePluginVersion: 3.2.0
                  testResultsFiles: '$(System.DefaultWorkingDirectory)/build/test-results/**/TEST-*.xml'
                  tasks: clean build
                env:
                  IT_ORBIT_FILE_REPOSITORY_AZURE_STORAGE_CONNECTION_STRING: ${{variables.testStorageAccountConnectionString}}

          - ${{ if eq(parameters.publish, true) }}:

              - task: Gradle@3
                displayName: Publish with Gradle
                inputs:
                  gradleWrapperFile: gradlew
                  gradleOptions: -Xmx10240m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
                  options: -Pci=true -PbuildId=$(Build.BuildId) -Preckon.stage=${{parameters.versionStage}} -Preckon.scope=${{parameters.versionScope}}
                  jdkVersionOption: 1.11
                  jdkArchitectureOption: x64
                  publishJUnitResults: true
                  sqAnalysisEnabled: true
                  sqGradlePluginVersionChoice: specify
                  sqGradlePluginVersion: 3.2.0
                  testResultsFiles: '$(System.DefaultWorkingDirectory)/build/test-results/**/TEST-*.xml'
                  tasks: clean publish
                env:
                  IT_ORBIT_FILE_REPOSITORY_AZURE_STORAGE_CONNECTION_STRING: ${{variables.testStorageAccountConnectionString}}

          - script: git status
            displayName: Git status
            condition: succeededOrFailed()

          - task: SonarCloudPublish@1
            displayName: Publish SonarCloud Quality Gate
            inputs:
              pollingTimeoutSec: '300'

          # Publish Artifacts

          - task: PublishCodeCoverageResults@1
            displayName: Publish code coverage results (test)
            condition: succeededOrFailed()
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/*.xml'
              pathToSources: $(System.DefaultWorkingDirectory)/src/main/java
              failIfCoverageEmpty: false


          # Finally logout from Docker
          - task: Docker@2
            condition: succeededOrFailed()
            displayName: Logout from ACR
            inputs:
              command: logout
              containerRegistry: AVG Orbit Registry

```
