### ISSUE TITLE
azure-pipelines-tasks/Tasks/AzureFileCopyV4/ is not compatible with AgentVersion = 2.196.2

### ISSUE THREAD

**Issue by jontreynes** [microsoft/azure-pipelines-tasks#15712]
## Note  
azure-pipelines-tasks/Tasks/AzureFileCopyV4/ is not compatible with a newer version AgentVersion = 2.196.2

I am receiving the error

```
No agent found in pool which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.163.1
```

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: feature

**Enter Task Name**: create AzureFileCopyV5 which is compatible with AgentVersion = 2.196.2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - PepsiCoIT, Mosaic_Product_Teams, 20220113.16 with id 638454

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - Agent.OS Windows_NT, Agent.Version  2.196.2

### Error logs
No agent found in pool which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.163.1

**Comment by jontreynes** [comment]
As for the azureps demand, I'm still troubleshooting. I do have azure powershell installed on the agent so I'm a bit confused

**Comment by v-ibshaik** [comment]
Hello jontreynes,

I have tried  to repro issue on my local machine, its working expected only. Could you please provide the complete logs and YAML file.

Thanks.

**Comment by jontreynes** [comment]
```

jobs:
- deployment: deploy_adf_${{parameters.environment}}
  displayName: ${{parameters.environment}} deploy ADF
  dependsOn: ${{parameters.dependsOn}}
  condition: ${{parameters.condition}}
  environment: ${{parameters.environment}}
  pool: "myselfhosted(Windows)"
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFileCopy@4
          inputs:
            SourcePath: './devops/scripts/adf.ps1'   #for testing
            azureSubscription: 'mysub'
            Destination: 'AzureBlob'
            storage: 'mystorage289371'
            ContainerName: 'standard/Config'
```

There is no log file because the job did not start due to the compatibility issues

This is all that outputs
##[error]No agent found in pool myselfhosted(Windows) which satisfies the specified demands: azureps, Agent.Version -gtVersion 2.163.1


When you repro, does your windows agent have gtVersion 2.163.1?
