### ISSUE TITLE
Convert DotNetCoreCLI@2 Task to Script

### ISSUE THREAD

**Issue by thepaulmacca** [microsoft/azure-pipelines-tasks#15710]
## Required Information

**Question, Bug, or Feature?**  
**Type**: Question

**Enter Task Name**: DotNetCoreCLI@2

## Issue Description

I'd like to convert the below task to a `dotnet publish` script instead:

```yaml
- task: DotNetCoreCLI@2
  displayName: Dotnet Publish ${{ parameters['project'] }} - ${{ parameters.buildConfiguration }}
  inputs:
    command: publish
    publishWebProjects: false
    projects: ${{ parameters['project'] }}
    arguments: --configuration ${{ parameters.buildConfiguration }} --no-build --output $(Build.ArtifactStagingDirectory)/MyApp_$(Build.BuildNumber)
    zipAfterPublish: true
    modifyOutputPath: false
  
```

Can anyone help me with the argument for `publishWebProjects: false` please? It's the only part I'm struggling with to complete the script

Thanks
