### ISSUE TITLE
IISWebAppManagementOnMachineGroup Remove username and password when they are not required

### ISSUE THREAD

**Issue by Hotjava** [microsoft/azure-pipelines-tasks#15792]
Is it possible to remove the username and password for Virtual Directory on a website. 

I am using yaml to deploy a website which app pool already configured, noted that everytime I use ADO to deploy the applicationhost.config file has been updated as 
```
 <site name="MyWebsite" id="12" serverAutoStart="true">
                <application path="/" applicationPool="DotNetCorePortal-Pre-Prod">
                    <virtualDirectory path="/" physicalPath="c:\MyWebsite" userName="" password="[enc:AesProvider:3AvwL+dsx7Zf2oaniKfGVEbN0ox+mYeQaKkUsW1p6Lo=:enc]" />
```
The website fails to start with this username and password, the error is "Failed to decrypt attribute 'password' because the keyset does not exist" . I don't know if there is issue with my server or not, but I don't want do any fixes even the issue is the server itselft as it's a production server,  

I understand the IIS is trying to encrypt the password evenif it's empty, but I want to get rid off the username and password completely. As if I manually remove them, the website worked just fine. e.g 

```
<site name="MyWebsite" id="12" serverAutoStart="true">
                <application path="/" applicationPool="DotNetCorePortal-Pre-Prod">
                    <virtualDirectory path="/" physicalPath="c:\MyWebsite" />
```

The ADO output as follwing 
```
##[debug]Updating website properties. Running command : "C:\Windows\system32\inetsrv\appcmd.exe"  set site /site.name:"MyWebsite" -applicationDefaults.applicationPool:"AppPool" -[path='/'].[path='/'].physicalPath:"c:\MyWebsite" -[path='/'].[path='/'].userName: -[path='/'].[path='/'].password:
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
##[debug] Arguments: ' set site /site.name:"MyWebsite" -applicationDefaults.applicationPool:"AppPool" -[path='/'].[path='/'].physicalPath:"c:\MyWebsite" -[path='/'].[path='/'].userName: -[path='/'].[path='/'].password:'
##[debug] RequireExitCodeZero: 'True'
"C:\Windows\system32\inetsrv\appcmd.exe"  set site /site.name:"MyWebsite" -applicationDefaults.applicationPool:"AppPool" -[path='/'].[path='/'].physicalPath:"c:\MyWebsite" -[path='/'].[path='/'].userName: -[path='/'].[path='/'].password:

```

**Comment by GeorgieH** [comment]
I have also encountered this issue and I don't know what's causing it.

In case anyone else runs into this problem, you can add this task as a deployment step (replace `$(iisWebsiteName)` with whatever you need it to be):

```yaml
# This is required because for some reason the pipeline creates a password against the virtual directory for the website even
# though it is never configured in the build: https://github.com/microsoft/azure-pipelines-tasks/issues/15792
# Be very careful if you're modifying this script. Make a backup of applicationHost.config beforehand.
- task: PowerShell@2
  displayName: Fix applicationHost.config
  inputs:
    targetType: inline
    script: |
      $applicationHostPath = "$env:SystemRoot\System32\inetsrv\config\applicationHost.config"
      $siteName = "$(iisWebsiteName)"
      $virtualDirectoryNodePath = "//configuration/system.applicationHost/sites/site[@name='$siteName']/application/virtualDirectory"
      $xml = [xml](Get-Content $applicationHostPath)
      $virtualDirectoryNode = $xml.SelectSingleNode($virtualDirectoryNodePath)
      $virtualDirectoryNode.RemoveAttribute("userName")
      $virtualDirectoryNode.RemoveAttribute("password")
      $xml.save($applicationHostPath)
```
