### ISSUE TITLE
HelmDeploy@0 and Kubernetes@1 do not work with kubelogin

### ISSUE THREAD

**Issue by nlighten** [microsoft/azure-pipelines-tasks#15802]
**Question, Bug, or Feature?**
*Type*: bug

**Task Name**:
- *HelmDeploy@0*
- *Kubernetes@1*

## Environment
- Server: Azure Pipelines

- Agent:  Private, ubuntu 18.04, version 2.196.2

## Issue Description
Both `HelmDeploy@0` and `Kubernetes@1` do not work with [kubelogin](https://github.com/Azure/kubelogin) while under the same conditions the plain `helm` and `kubectl` binaries do.

We run AKS with AAD integration enabled and avoid using local K8S service accounts. Instead we use an ARM Service Connection with MSI. If you try to use `kubectl` using an ARM Service Connection on an AKS cluster with AAD integration you will get a prompt for `https://microsoft.com/devicelogin` which does not work in a devops pipeline context.
. 
The `kubelogin` utility is a client-go credential plugin for `kubectl` that implements Azure AD authentication. This works fine when using it from the command prompt, but not when using the `HelmDeploy@0` and `Kubernetes@1` tasks. Somehow there is a subtle difference in the process context where the `kubectl` and `helm` are used from the command line when compared to the invocation done by the tasks. 

Below is an example pipeline to illustrate the issue:
- The first task does an `az aks get-credentials`, installs `kubelogin` and converts the `kubeconfig` file to use `kubelogin`.
- The seconds task uses `kubectl` and `helm` binaries directly from a bash shell. This works without issues.
- The third task uses `HelmDeploy@0` task to list the deployed charts. This fails when calling the `kubelogin` credential plugin: `getting credentials: exec: executable kubelogin failed with exit code 1`.
- The fourth task uses `Kubernetes@1` task to list pods in a namespace. This fails with similar errors as the helm task.

```yaml
      - task: AzureCLI@2
        displayName: aks non-admin login using kubelogin
        inputs:
          azureSubscription: ${{parameters.serviceConnection}}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az aks get-credentials -n <aks cluster> -g <resource group>
            # install kubelogin
            wget https://github.com/Azure/kubelogin/releases/download/v0.0.10/kubelogin-linux-amd64.zip
            unzip kubelogin-linux-amd64.zip
            mv bin/linux_amd64/kubelogin /usr/bin
            kubelogin convert-kubeconfig -l azurecli
 
      - task: AzureCLI@2
        displayName: test kubectl and helm from bash
        continueOnError: true 
        inputs:
          azureSubscription: ${{parameters.serviceConnection}}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            kubectl get pods -n <some namespace>
            helm list --namespace <some namespace>

      - task: HelmDeploy@0
        displayName: test HelmDeploy task
        continueOnError: true 
        inputs:
          connectionType: None
          namespace: <some namespace>
          command: list

      - task: Kubernetes@1
        displayName: test Kubernetes task
        continueOnError: true 
        inputs:
          connectionType: None
          command: get
          arguments: pods -n <some namespace>
```

Possibly this issue needs to be fixed in the [kubelogin](https://github.com/Azure/kubelogin) project but would like to understand the likely differences on how the tasks call the underlying `kubectl` and `helm` binaries when compared to invoking them from `bash`. 

### Task logs

See attached [logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7900774/logs.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2022-01-19T20:33:52.7909008Z ##[debug]set helmExitCode=1
2022-01-19T20:33:52.7910461Z Error: Kubernetes cluster unreachable: Get "https://<aks cluster>-a15872ed.hcp.westeurope.azmk8s.io:443/version?timeout=32s": getting credentials: exec: executable kubelogin failed with exit code 1
2022-01-19T20:33:52.7912489Z helm.go:88: [debug] Get "https://<aks cluster>-a15872ed.hcp.westeurope.azmk8s.io:443/version?timeout=32s": getting credentials: exec: executable kubelogin failed with exit code 1
2022-01-19T20:33:52.7915456Z ##[debug]Processed: ##vso[task.setvariable variable=helmExitCode;issecret=false;]1
```

**Comment by nlighten** [comment]
I found out that my problem was caused by AzureCLI@2 doing `az account clear` at the end. As a result there was no valid login anymore when the HelmDeploy and Kubernetes task where invoked.

If I use plain bash and an explicit login/logout everything works as expected in combination with a MSI:  

```yaml
      - task: Bash@3
        displayName: az and aks login
        inputs:
          targetType: 'inline'
          script: |
            az login --identity 
            az aks get-credentials -n <aks cluster> -g <resource group>
            kubelogin convert-kubeconfig -l azurecli
 
      - task: HelmDeploy@0
        displayName: test HelmDeploy task
        inputs:
          connectionType: None
          namespace: <namespace>
          command: list

      - task: Kubernetes@1
        displayName: test Kubernetes task
        inputs:
          connectionType: None
          command: get
          arguments: pods -n <namespace>
 
      - task: Bash@3
        condition: always()
        displayName: az and aks logout
        inputs:
          targetType: 'inline'
          script: |
            az account clear
            rm -rf ~/.kube
```

Still, I would prefer explicit support for kubelogin as part an ARM Service Connection on the Kubernetes and HelmDeploy tasks. Will submit a feature request when I find the time.

**Comment by michaelelleby** [comment]
This workaround only works if you are using self-hosted agents with managed identity. We are using Microsoft hosted agents and thus we cannot use `az login --identity`, but we are forced to use the AzureCLI@2 task.

As a workaround for that, you can deploy Helm charts using the AzureCLI@2 task:
```
- task: AzureCLI@2
  displayName: Login to AKS using kubelogin
  inputs:
    azureSubscription: <service connection>
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      set -e

      export KUBECONFIG=$(Build.SourcesDirectory)/.kubeconfig-<aks cluster>

      # Fails if it doesn't exist
      touch .kubeconfig-<aks cluster>
      chmod 600 .kubeconfig-<aks cluster>

      # Populate kubeconfig
      az aks get-credentials \
        --resource-group <resource group> \
        --name <aks cluster> \
        --overwrite-existing \
        --file .kubeconfig-<aks cluster>

      # Pass kubeconfig to kubelogin to access k8s API
      kubelogin convert-kubeconfig -l azurecli

      # confirm it works
      kubectl get pods --namespace default

      # Ensure the kubeconfig path is available to subsequent tasks as an environment variable
      echo "##vso[task.setvariable variable=KUBECONFIG]${KUBECONFIG}"
    displayName: kubelogin - aks-credentials to kubecontext```

- task: AzureCLI@2
  displayName: Install Secrets Store CSI Driver Helm chart
  inputs:
    azureSubscription: <service connection>
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      export KUBECONFIG=$(Build.SourcesDirectory)/.kubeconfig-<cluster name>

      helm upgrade \
        keyvault-provider \
        csi-secrets-store-provider-azure/csi-secrets-store-provider-azure \
        --install \
        --set secrets-store-csi-driver.syncSecret.enabled=true \
        --set secrets-store-csi-driver.enableSecretRotation=true
```

**Comment by PehrGit** [comment]
We have a similar setup and for us it works if we use `connectionType: "Azure Resource Manager"` and add `useClusterAdmin: true`. No additional steps or workarounds needed. We need to use `kubelogin` from our workstations but on our privately hosted build agents this just works without any need for kubelogin stuff.

**Comment by PehrGit** [comment]
> @PehrGit `useClusterAdmin` will just bypass all Azure AD integration and in general will not make your auditors happy.

Fair enough!

**Comment by kingli-crypto** [comment]
Will this ever be fixed by MS? The workaround works but it's something that should work out of the box?

**Comment by miqm** [comment]
+1

**Comment by miqm** [comment]
Can someone reopen this ticket? I think the problem is still valid although the author had found a workaround.

**Comment by georgejdli** [comment]
This work around has worked well for me but I did run into an issue where an outdated kubelogin was not working with AKS v1.24 (upgrade from 0.0.11 to 0.0.27 did the trick though)

**Comment by sambitr** [comment]
Did anyone try below?
1. using AzureCLI stage to perform login, converting kubeconfig file using kubelogin like mentioned by @michaelelleby 
**2. Export the KUBECONFIG file through environment variable**. Done by Michael
3. Use HelmDeploy stage to perform deployment, by keeping connectionType: None. This will accept the exported KUBECONFIG environment file.

https://helm.sh/docs/helm/helm/: helm respects the $KUBECONFIG env

It worked for me. This is from kubelogin stage

```
         az aks get-credentials -n '${{ parameters.kubernetesCluster }}' -g '${{ parameters.azureResourceGroup }}' --subscription '${{ parameters.subscriptionID }}' --file $(Build.ArtifactStagingDirectory)/.kubeconfig-'${{ parameters.kubernetesCluster }}'

          export KUBECONFIG=$(Build.ArtifactStagingDirectory)/.kubeconfig-'${{ parameters.kubernetesCluster }}'

          export AAD_SERVICE_PRINCIPAL_CLIENT_ID=$servicePrincipalId
          export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=$servicePrincipalKey

          echo "Converting kubeconfig file using kubelogin"
          kubelogin convert-kubeconfig -l spn --client-id $servicePrincipalId --client-secret $servicePrincipalKey

          echo "Ensure the kubeconfig path is available to subsequent tasks as an environment variable"
          echo "##vso[task.setvariable variable=KUBECONFIG]${KUBECONFIG}"
```
and below is the helm task

```
- task: HelmDeploy@0
  displayName: 'Helm Deploy ${{parameters.chartName}}'
  condition: and(succeeded(), ${{ parameters.enabled }})
  inputs:
    connectionType: None
    namespace: '${{ parameters.defaults.namespace }}'
    command: upgrade
    chartType: FilePath
    chartPath: '$(Pipeline.Workspace)/drop/charts/${{parameters.chartName}}'
    ${{ if eq(parameters.slot, 'default') }}:
     releaseName: '${{ parameters.defaults.namespace }}-${{parameters.chartName}}'
    ${{ if ne(parameters.slot, 'default') }}:
     releaseName: '${{ parameters.slot }}${{ parameters.defaults.namespace }}-${{parameters.chartName}}'
    overrideValues: '${{ parameters.overrideValues }}${{ parameters.additionalValues }}'
    arguments: '--timeout ${{ parameters.timeout }}'
    waitForExecution: true
```
