### ISSUE TITLE
AzureFunctionApp@1 often fails with 'Resource '****' doesn't exist. Resource should exist before deployment.'

### ISSUE THREAD

**Issue by wkoeter** [microsoft/azure-pipelines-tasks#15838]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzureFunctionApp@1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionAppV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - Azure Pipelines
     
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - **Failed Build** : https://dev.azure.com/mstack/test-project2/_build/results?buildId=3552
    - **Succeeded** : https://dev.azure.com/mstack/test-project2/_build/results?buildId=3545

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name:  ubuntu-latest 

## Issue Description
When rerunning a build and deployment pipeline that only deploys a demo function, I get mixed results. Half the time it succeeds, half the time it gives the same error message.

`##[error]Error: Resource 'demo-function-pub' doesn't exist. Resource should exist before deployment.`

To display the problem I've created a public function app called `demo-function-pub` using bicep, and am trying to deploy to that function app. The function app is created ONCE with bicep (manually from my dev PC), and deployed to multiple times (14 to be exact) by rerunning the pipline from the DevOps portal.

**When doing 14 deploys to an existing resource of the same unchanged code, 7 fail with the error message**

[Include task name(s), screenshots and any other relevant details]
List of manual triggers of the pipeline. Mixed results when deploying unchanged code to existing resource.
![image](https://user-images.githubusercontent.com/17491881/151663920-17250390-f469-40b8-bdc3-183356810fce.png)

Deployment task:
```
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure Functions App Deploy: func-rp-alt-westeurope-orch'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: zipDeploy
```
Bicep file (to show that its really straight forward function app)

```
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-06-01' = {
  name: toLower('strpalt${resourceGroup().location}${applicationNamePart}')
  location: resourceGroup().location
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    encryption: {
      services: {
        file: {
          enabled: true
          keyType: 'Account'
        }
        blob: {
          enabled: true
          keyType: 'Account'
        }
        queue: {
          enabled: true
          keyType: 'Account'
        }
        table: {
          enabled: true
          keyType: 'Account'
        }
      }
      keySource: 'Microsoft.Storage'
    }
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
  }
  sku: {
    name: 'Standard_LRS'
  }
  tags: {
    role: 'App Service Plan Storage'
    version: versionTagValue
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-asp-${applicationNamePart}'
  location: resourceGroup().location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
  tags: {
    role: 'Application Insights'
    version: versionTagValue
  }
}

var functionName = 'demo-function-${applicationNamePart}'

resource functionApp 'Microsoft.Web/sites@2021-02-01' = {
  name: functionName
  location: resourceGroup().location
  kind: 'functionapp,linux'
  properties: {
    httpsOnly: true
    serverFarmId: servicePlan.id
    reserved: true
    siteConfig: {
      scmType: 'VSTSRM'
      cors: {
        allowedOrigins: [
          'https://portal.azure.com'
        ]
      }
      alwaysOn: true
      appSettings: [
        {
          name: 'AzureWebJobsStorage'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccount.name};AccountKey=${listKeys(storageAccount.id, storageAccount.apiVersion).keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
        }
        {
          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          value: appInsights.properties.InstrumentationKey
        }
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: 'dotnet-isolated'
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: appInsights.properties.ConnectionString
        }
      ]
      linuxFxVersion: 'DOTNET-ISOLATED|6.0'
      webSocketsEnabled: true
    }
  }
  tags: {
    role: 'Function App for demo purposes'
    version: versionTagValue
  }
}
```

### Task logs
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

[Deploy_Failed.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7952017/Deploy_Failed.txt)
[Deploy_Success.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7952021/Deploy_Success.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
##[error]Error: Resource 'demo-function-pub' doesn't exist. Resource should exist before deployment.
