### ISSUE TITLE
Subdirectories are not copied

### ISSUE THREAD

**Issue by erossini-chi** [microsoft/azure-pipelines-tasks#15862]
I'm trying to deploy from Azure DevOps via FTPS a WordPress to a App Service on Azure. First, I created the resource WordPress. Then I created the repository in Azure DevOps and this is the structure. I created a folder called `Virtuoso` that is a new theme for WordPress.

![image](https://user-images.githubusercontent.com/70210793/152019122-0a94f981-6174-492d-85f3-24fda654573f.png)

Now, this is the YAML I'm using to copy all the files and directories on the App Service.

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '<my ftp server>'
    username: '<my username>'
    password: '<my password>'
    rootDirectory: 'src'
    filePatterns: '**'
    remoteDirectory: '/'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false
```

I copied `serverUrl`, `username` and password from the **Deployment Center** in the App service.

![image](https://user-images.githubusercontent.com/70210793/152018511-ec9b27c3-0e04-441e-b827-2eed545d2983.png)

In the pipeline log seems that all files in all subdirectories are copied.

For example, those are few lines from the log.

> files uploaded: 1018, directories processed: 120, total: 1138, remaining: 2029, successfully uploaded: /home/vsts/work/1/s/src/wp-content/themes/twentytwentyone/template-parts/post/author-bio.php to: /wp-content/themes/twentytwentyone/template-parts/post/author-bio.php
> files uploaded: 1018, directories processed: 121, total: 1139, remaining: 2028, remote directory successfully created/verified: /wp-content/themes/virtuoso
> File: /wp-content/themes/virtuoso/404.php Type: upload Transferred: 0
> File: /wp-content/themes/virtuoso/404.php Type: upload Transferred: 262
> files uploaded: 1019, directories processed: 121, total: 1140, remaining: 2027, successfully uploaded: /home/vsts/work/1/s/src/wp-content/themes/virtuoso/404.php to: /wp-content/themes/virtuoso/404.php
> files uploaded: 1019, directories processed: 122, total: 1141, remaining: 2026, remote directory successfully created/verified: /wp-content/themes/virtuoso/acf-json
> File: /wp-content/themes/virtuoso/acf-json/group_61e83e5f28ee4.json Type: upload Transferred: 0
> File: /wp-content/themes/virtuoso/acf-json/group_61e83e5f28ee4.json Type: upload Transferred: 21356
> files uploaded: 1020, directories processed: 122, total: 1142, remaining: 2025, successfully uploaded: /home/vsts/work/1/s/src/wp-content/themes/virtuoso/acf-json/group_61e83e5f28ee4.json to: /wp-content/themes/virtuoso/acf-json/group_61e83e5f28ee4.json
> File: /wp-content/themes/virtuoso/acf-json/group_61e9501992b4b.json Type: upload Transferred: 0
> File: /wp-content/themes/virtuoso/acf-json/group_61e9501992b4b.json Type: upload Transferred: 1029
> files uploaded: 1021, directories processed: 122, total: 1143, remaining: 2024, successfully uploaded: /home/vsts/work/1/s/src/wp-content/themes/virtuoso/acf-json/group_61e9501992b4b.json to: /wp-content/themes/virtuoso/acf-json/group_61e9501992b4b.json
> File: /wp-content/themes/virtuoso/acf-json/group_61e977c989658.json Type: upload Transferred: 0
> File: /wp-content/themes/virtuoso/acf-json/group_61e977c989658.json Type: upload Transferred: 2566

![image](https://user-images.githubusercontent.com/70210793/152018790-03a0cf2e-40c6-461c-9fcb-bdc025c53fba.png)

Now, if I open the FTP via FileZilla with the same credentials, I can't find the folders and the files I expect (for example `Virtuoso`)

![image](https://user-images.githubusercontent.com/70210793/152018928-3c923c2a-2d21-4dda-99ef-10e57fe77b0b.png)

What am I doing wrong?
