### ISSUE TITLE
DotNetCoreCLI@2 nuget push does not respect --skip-duplicate argument

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [microsoft/azure-pipelines-tasks#15866]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - Account: kasparsolutions.be
    - Team project name: Kaspar-Solutions
    - Build defenition name: ?
    - Build number: #20220202.8

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: #20220202.8

## Issue Description

The command nuget push with DotNetCoreCLI@2 does not respect the `--skip-duplicate` argument. It has proven very difficult to find good documentation on this. Am I mising something, or is this a bug?

```
      - job: PublishClientNuget
        container: mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim
        steps:
          - task: NuGetAuthenticate@0
          - task: DotNetCoreCLI@2
            inputs:
              command: "pack"
              packagesToPack: "**/*.csproj"
          - task: DotNetCoreCLI@2
            inputs:
              command: "push"
              packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
              nuGetFeedType: "internal"
              publishVstsFeed: "331-(valid guid)/331-(valid guid)"
              arguments: "--skip-duplicate"
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[logs_18614.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7985826/logs_18614.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

#### I cleaned this up to hide potential sensitive info

```
Starting: DotNetCoreCLI
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/usr/bin/dotnet nuget push /__w/1/a/Kaspar123.Case.Api.Grpc.Client.1.0.2-PullRequest4212.5.nupkg --source https://pkgs.dev.azure.com/Kaspar-Solutions/18d05e66-e21d-4b8b-b8b5-560616c2aa63/_packaging/2f42d7da-4bce-7d1a-80e7-de151241dda9/nuget/v3/index.json --api-key VSTS
Pushing Kaspar123.Case.Api.Grpc.Client.1.0.2-PullRequest4212.5.nupkg to 'https://pkgs.dev.azure.com/Kaspar-Solutions/(valid guid)/_packaging/(valid guid)/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/Kaspar-Solutions/(valid guid)/_packaging/(valid guid)/nuget/v2/
  Conflict https://pkgs.dev.azure.com/Kaspar-Solutions/(valid guid)/_packaging/(valid guid)/nuget/v2/ 106ms
To skip already published packages, use the option --skip-duplicate
error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'RepoName.Api.Grpc.Client 1.0.2'. (DevOps Activity ID: A57947D1-6E3B-4AED-9E63-1407F8979AB0)).


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[error]Packages failed to publish
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
Finishing: DotNetCoreCLI

```

**Comment by heavenwing** [comment]
According to this [description](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?source=recommendations&view=azure-devops#task-control-options):
_Note: This input only currently accepts arguments for build, publish, run, test, custom. If you would like to add arguments for a command not listed, use custom._ 

But when I use custom command to run it like that:

```yaml
  - task: DotNetCoreCLI@2
    displayName: "Push all nuget packages"
    inputs:
      workingDirectory: "dotnet-dto"
      command: "custom"
      custom: "nuget push"
      arguments: "--skip-duplicate"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "d46a4ac1-5d7c-47a3-89ff-9d7e364532b0/7b50499b-808a-45d4-9bbc-2472a09e1b2b"
```

I also got this error:

```log
2022-10-18T09:42:42.5599594Z ==============================================================================
2022-10-18T09:42:42.9500685Z Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
2022-10-18T09:42:42.9508887Z [command]/usr/bin/dotnet nuget push --skip-duplicate
2022-10-18T09:42:43.5458345Z Could not execute because the specified command or file was not found.
2022-10-18T09:42:43.5460498Z Possible reasons for this include:
2022-10-18T09:42:43.5461666Z   * You misspelled a built-in dotnet command.
2022-10-18T09:42:43.5463060Z   * You intended to execute a .NET program, but dotnet-nuget push does not exist.
2022-10-18T09:42:43.5464321Z   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
2022-10-18T09:42:43.5665625Z ##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
2022-10-18T09:42:43.5678170Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2022-10-18T09:42:43.5680605Z ##[error]Dotnet 命令失败，以下项目具有非零退出代码: 
2022-10-18T09:42:43.5702736Z ##[section]完成: Push all nuget packages
```
