### ISSUE TITLE
Populate variable with ACR hostname on "login" using Docker task

### ISSUE THREAD

**Issue by malthe** [microsoft/azure-pipelines-tasks#15863]
It should be possible to derive the ACR hostname having only a service connection available.

That is, for a given service connection, the `Docker` task should make available to hostname, i.e. `<name>.azurecr.io` which is registered with that service connection.

See for example the following unanswered post:

https://stackoverflow.com/questions/67921817/derive-the-acr-name-from-a-service-connection-in-azure-devops-pipeline

**Comment by ryanhatfield** [comment]
After the `docker login` command is run, the `${DOCKER_CONFIG}` environment variable is set (or reused) and the connection information is saved to `${DOCKER_CONFIG}/config.json`. The config file will not exist before the `login` command though, so you might need to specifically call the `login` command first before any `buildAndPush` or `push` commands.

If logged in with a service connection, this file should look something like (formatted here for readability):
```json
{
  "auths": {
    "https://gcr.io/container-registry-999999/": {
      "auth": "SomeMonsterBase64EncodedStringAuthThing",
      "email": ""
    }
  },
  "HttpHeaders": { "X-Meta-Source-Client": "VSTS" }
}
```

You can see mine here is for `gcr.io` but I assume the hostname should be there for an `ACR` service connection.

When I tested this, it thought the service connection name was `secret` so it obfuscated it from the pipeline logs, so I added a publish task to let you see what that value ends up being (you won't need the publish after you get it working)
```yaml
- script: echo "##vso[task.setvariable variable=serviceConnectionHostname]$(jq '.auths|keys|first' ${DOCKER_CONFIG}/config.json)"
  displayName: Set serviceConnectionHostname from Service Connection

- script: echo "$(serviceConnectionHostname)" > serviceHostname.txt
  displayName: Output serviceConnectionHostname

- publish: serviceHostname.txt
  artifact: serviceHostname
```

Hope this helps 👍
