### ISSUE TITLE
Command line tasks not expanding pipeline variables correctly when value contains the chars -0 (hyphen + zero)

### ISSUE THREAD

**Issue by jls-0** [microsoft/azure-pipelines-tasks#15884]
*Type*: Bug
**Enter Task Name**: PowerShell, Command Line, Bash  
Azure Pipelines, javihigh, gitlab, sync-gitlab-azure-repos, build number: 129
Hosted agent

## Issue Description

When defining a pipeline variable value that contains a hyphen + zero character (-0) on it; **myVar** on the image below:
![image](https://user-images.githubusercontent.com/86844531/152556444-50580acf-d5a8-4b4a-8112-cf1c6eccfeb9.png)
Having the following pipeline to test the issue:
```
pool:
  name: Azure Pipelines
steps:
- powershell: 'Write-Host $env:MYVAR'
  displayName: 'PowerShell Script'

- script: |
   echo $MYVAR
   
  displayName: 'Command Line Script'
```
It doesn't expand the variable value correctly as you can see in the following image:
![image](https://user-images.githubusercontent.com/86844531/152558004-9440537b-25bd-4803-9b5c-89af98ca1ff0.png)
![image](https://user-images.githubusercontent.com/86844531/152558074-7061eb07-b955-43eb-a3d2-8e6e0156d71d.png)

As you can see, it shows the string like *** instead of the actual value **jls-0**, which causes and big issue if you need to use string values that contains -0.

**Note:** it appears that the chars -0 in the string is converting the contiguous left chars to asterisks.

Tested jls-1 and jls-a without any issue, the problem is when the value contains a -0
