### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by ozbillwang** [microsoft/azure-pipelines-tasks#15903]
## Required Information

**Question, Bug, or Feature?**  : Question. if not have, will be a feature request
**Enter Task Name**: docker@2

## Issue Description

In one repo, I have several application folders with Dockerfile in each of them. I can't find the option to define the working directory in task `Docker@2`

```
    - task: Docker@2
      displayName: 'docker build'
      inputs:
        containerRegistry: $(dockerRegistryServer)
        repository: '$(ImageName)'
        command: build
        Dockerfile: 'Dockerfile'
        tags: $(tag)
        # workingDirectory: $(DirName)    # But this doesn't work as expect.
```

So how can I build the images in different folders, that means I need set `workingDirectory` in task `Docker@2`. 

reference in shell commands:

```
pushd <path>
docker build -t xxxx . 
popd
```

reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops
