### ISSUE TITLE
HelmDeploy install and upgrade overrideValues multi-line documentation issue

### ISSUE THREAD

**Issue by lancegliser** [microsoft/azure-pipelines-tasks#15936]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Documentation

**Enter Task Name**: HelmDeploy  

## Environment
- Server - Azure Pipelines?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      Account: TorchResearchLLC
      Project: Deployment and Hosting
      Definition: definitionId=250
      Build: 11239
      https://dev.azure.com/TorchResearchLLC/Deployment%20and%20Hosting/_build?definitionId=250&_a=summary

- Agent - Hosted: 
    - If using Hosted agent, provide agent queue name: 
    Pool: Azure Pipelines
    Agent: Hosted Agent

## Issue Description

#13579 and the [docs for helm upgrade](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#upgrade-command) suggest that we should be able to use a multi line syntax like the below:

> ...You can also specify multiple values by delimiting them with newline as so:
>  key1=val1
>  key2=val2

Reading that made me think the syntax below would work:

```yaml
steps:
  - task: HelmDeploy@0
    displayName: helm upgrade hydra-postgresql
    inputs:
      overrideValues:
        postgresql.postgresqlUsername=${{ parameters.postgresqlUsername }}
        postgresql.postgresqlPassword=${{ parameters.postgresqlPassword }}
        postgresql.postgresqlDatabase=${{ parameters.postgresqlDatabase }}
```
Results in this command in execution:

```shell
/usr/local/bin/helm upgrade --namespace auth --install --set postgresql.postgresqlUsername=hydra-user postgresql.postgresqlPassword=l****ns postgresql.postgresqlDatabase=hydra hydra-postgresql /home/vsts/work/1/drop/helm/hydra-postgresql
```

The proper syntax should be:
```yaml
steps:
  - task: HelmDeploy@0
    displayName: helm upgrade hydra-postgresql
    inputs:
      overrideValues: |-
        postgresql.postgresqlUsername=${{ parameters.postgresqlUsername }}
        postgresql.postgresqlPassword=${{ parameters.postgresqlPassword }}
        postgresql.postgresqlDatabase=${{ parameters.postgresqlDatabase }}
```

Need to get that documentation to read something more like:

>
> ...You can also specify multiple values by delimiting them with newline as so:
>  overrideValues: |-
>    key1=val1
>    key2=val2

**Comment by ryanhatfield** [comment]
I would switch your `HelmDeploy@0` Task to use a multiline string, I'm not sure your current usage is valid YAML?

Old value:
```yaml
overrideValues:
  postgresql.postgresqlUsername=${{ parameters.postgresqlUsername }}
  postgresql.postgresqlPassword=${{ parameters.postgresqlPassword }}
  postgresql.postgresqlDatabase=${{ parameters.postgresqlDatabase }}
```

New value:
```yaml
overrideValues: |-
  postgresql.postgresqlUsername=${{ parameters.postgresqlUsername }}
  postgresql.postgresqlPassword=${{ parameters.postgresqlPassword }}
  postgresql.postgresqlDatabase=${{ parameters.postgresqlDatabase }}
```

According to [this line](https://github.com/microsoft/azure-pipelines-tasks/blob/d088f37bc2ceb858be702aaebce2ffebf7531fd7/Tasks/HelmDeployV0/src/helmcommands/helmupgrade.ts#L57) in the Task, it's using multiple `--set` commands as opposed to comma separated values.

I've completely moved away from using the `overrideValues` parameter, as using the `valueFIle` can be far easier to write (you don't need to get all the nested arrays / objects right).

I use the `convertToJson` template function to convert a value file YAML object into a JSON file, then use that as the `valueFile`

```yaml
parameters:
  - name: valueFileValues
    type: object
    default:
      auth:
        username: postgresql_username
        password: postgresql_password
        database: postgresql_default_database_name

trigger: [main]

pool: { vmImage: ubuntu-latest }


steps:
  - script: echo '${{ convertToJson(parameters.valueFileValues) }}' > localValueFile.json
    displayName: output localValueFile.json

  - script: cat localValueFile.json
    displayName: display localValueFile.json

  - script: helm repo add bitnami https://charts.bitnami.com/bitnami

  - task: HelmDeploy@0
    displayName: helm upgrade postgresql
    inputs:
      kubernetesServiceEndpoint: endpoint-name-here
      namespace: namespace-name-here
      command: install
      chartType: Name
      chartName: bitnami/postgresql
      releaseName: fuzzy-lizzard-postgresql
      valueFile: localValueFile.json
      waitForExecution: false
      arguments: --dry-run
```

This results in a json object like:
```json
{
  "auth": {
    "username": "postgresql_username",
    "password": "postgresql_password",
    "database": "postgresql_default_database_name"
  }
}
```

And since all YAML is a superset of JSON, you can feed this JSON file back into the `valueFiles` and enjoy proper syntax for your override values inside the pipeline, without having to deal with weird multiline string values, and concatenated `--set` arguments.
