### ISSUE TITLE
Add `DeleteRG` action in AzureResourceManagerTemplateDeploymentV3 in documentation.

### ISSUE THREAD

**Issue by troy0820** [microsoft/azure-pipelines-tasks#15947]
Listed in this list of  [actions](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/README.md#parameters-of-the-task) in the AzureResourceManagerTemplateDeployment@3 it shows that the delete action is 'Delete Resource Group'.  In the article that is published, ([public facing docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/deploy-arm-template?view=azure-devops)) it shows that the action is `DeleteRG`.  When trying to use the examples, it is unclear which action is used for deleting a resource group in a pipeline.  

#### Public facing docs example
```yaml
task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<your-resource-manager-connection>'
    subscriptionId: '<your-subscription-id>'
    action: 'DeleteRG'
    resourceGroupName: 'ARMPipelinesLAMP-rg'
    location: ''<your-closest-location>'
```
#### GitHub repository for azure-pipeline-tasks [microsoft/azure-pipeline-tasks](https://github.com/microsoft/azure-pipelines-tasks)
```
Action*: If the deployment scope is 'Resource Group', select the action to be performed on the resource group. Following actions are available:

- Create or Update Resource Group: creates a new resource group or to update an existing one (using [Azure Resource Manager templates](https://azure.microsoft.com/en-in/documentation/articles/resource-group-template-deploy/)).
- Delete Resource Group
- Select Resource Group( not supported here - use Version 2.0 for this action ): reads the Resource Group information from Azure and creates an Output Variable with the VMs in the Resource Group
Start, Stop, Deallocate, Restart, Delete Virtual Machines( not supported here - use Version 2.0 for this action )
```
Looking at [this](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/main.ts#L53) it seems to be that the docs need to be updated to use `DeleteRG` as the action in that task.
