### ISSUE TITLE
UseDotNet: No definition for nugetVersion input

### ISSUE THREAD

**Issue by spSlaine** [microsoft/azure-pipelines-tasks#15955]
We are having an issue with the UseDotNet task defaulting to use nuget 4.4.1. 

Looking at the task you can override this by specifying nugetVersion: in the yaml

```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    nugetVersion: '6.0.0'
```

This does work however warns that the input is Unexpected

The input is not defined in the task json

https://github.com/microsoft/azure-pipelines-tasks/blob/82f0b6a90d45f4c4a728e60fd5e9c809c2517ff5/Tasks/UseDotNetV2/task.json#L34,L109
