### ISSUE TITLE
AzureResourceManagerTemplateDeploymentV3 doesn't recognize bicep files

### ISSUE THREAD

**Issue by rwaal** [microsoft/azure-pipelines-tasks#15959]
## Required Information

According to the README, the `AzureResourceManagerTemplateDeploymentV3` task should now natively support Azure Bicep deployments. However, when using this task it throws an error, indicating it expects a JSON file.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

## Environment
- Agent - Hosted: ubuntu-latest

## Issue Description

In the AzureResourceManagerTemplateDeployment@3 task I am pointing to a Bicep file. This results in the follwing error: `##[error]Error: Ensure the Template file ( '/home/vsts/work/1/s/azure/resourcegroup.bicep' ) is valid. Task failed while parsing with following error: Unexpected token a in JSON at position 1`

This is my pipeline definition (or at least part of it):

``` YAML
trigger: none
pr: none

stages:
- stage: Infrastructure
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Resource Group'
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: ${{ variables.armConnectionManagementGroup }}
        subscriptionId: $(subscriptionId)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/azure/resourcegroup.bicep'
        overrideParameters: '<redacted>'
```

### Task logs

I added the pipelines log, but left some things out that contained information about the organisation. In case something is missing that is required, please let me know.
[logs_81347.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8123445/logs_81347.zip)
