### ISSUE TITLE
Environment Variable in Python Script 

### ISSUE THREAD

**Issue by estepangugu** [microsoft/azure-pipelines-tasks#15975]
Hi,

I want to inject client secret from keyvault to python script classic task. But there isn't enviroment variable section in python script. (like powershell or commandline task)

How can set environment variable in python script task (not YAML)

Any advice would be appreciated.

**Comment by DenisRumyantsev** [comment]
Hi @estepangugu, could you try to use Python script arguments to pass the environment variable into the script?

Such pipeline works good to me when using the classic editor:

![image](https://user-images.githubusercontent.com/61472718/157794997-b73b6517-a2fe-4cb3-a8fc-f82fbde572d6.png)

The same when using the pipeline yml file:
```yml
pool:
 vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: inline
    script: |
      import sys
      argument = sys.argv[1] # equals '19'
      first = int(argument) # equals 19
      second = 23
      print(first + second) # expected 42
    arguments: $(secret-variable)
```
