### ISSUE TITLE
Unable to run DownloadBuildArtifacts task when Pipeline is set to run in container (self-hosted agent)

### ISSUE THREAD

**Issue by matman26** [microsoft/azure-pipelines-tasks#15986]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  DownloadBuildArtifact  

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadBuildArtifactsV1/

## Environment
- Server - Azure Pipelines  
- Agent - Private (self-hosted) 
  - OS: CentOS Linux release 7.9.2009 (Core)
  - Agent version: 2.200.2

## Issue Description

I'm trying to execute a package build from inside a container running on my self-hosted Pipelines Agent. See my azure-pipelines.yml file:
```yaml
trigger:
- master

pool:
  name: <agent-name>
  
container: 
  image: <image>

steps:
- script: |
    pwd 
    ls -lah
    whoami
    groups
  displayName: Some pre-checks to make sure I'm inside teh container

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '<project>'
    pipeline: '<pipeline>
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: '<artifact-name>'
    downloadPath: '$(System.ArtifactsDirectory)'
    #downloadPath: '/opt/<package>/'
  displayName: Download dependency

- script: |
    make
  displayName: 'Compile package with dependency'
```
As far as I've been able to identify, both of the tasks under `script` run just fine INSIDE the container, but DownloadBuildArtifact is running OUTSIDE of the container, on the machine where the pipelines agent is installed. This means the dependency is not available at compile-time.

Not sending any logs as they contain sensitive data, but as far as I've been able to test DownloadBuildArtifacts is downloading directly to the machine running the azure agent rather than the container (as was the expected behavior given I've specified the `container` tag for this pipeline run).

**Comment by golubev-ivan** [comment]
Hi @matman26, I currently investigate this issue, for now as a workaround you can use the CopyFiles task after the DownloadBuildArtifact task to pass the necessary files into the container.

Example of using the workaround:
```yaml
container: 
  image: <image>

steps:
...
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '<project>'
    pipeline: '<pipeline>
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: '<artifact-name>'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(System.ArtifactsDirectory)/<artifact-name>'
    contents: '**' 
    targetFolder: '$(Build.SourcesDirectory)'
...
```

**Comment by golubev-ivan** [comment]
Hi @matman26, as far as I see the DownloadBuildArtifactsV1 task works as expected. The script task runs in sources directory by default, if you want to use artifacts in the script task, you would put the artifact to $(Build.SourcesDirectory) or specify the custom working directory parameter of the script task. Also, for clarification, artifact are placed in a folder with the same name as the artifact.

Example:
```yaml
steps:
- script: |
    pwd 
    ls -lah
    whoami
    groups
  displayName: Some pre-checks to make sure I'm inside teh container

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '<project>'
    pipeline: '<pipeline>
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: '<artifact-name>'
    downloadPath: '$(Build.SourcesDirectory)'
  displayName: Download dependency

- script: |
    make
  displayName: 'Compile package with dependency'
  #workingDirectory: '$(System.ArtifactsDirectory)' # Instead of changing the dowloadPath
```
