### ISSUE TITLE
Trouble passing arguments to console app using dotnet run

### ISSUE THREAD

**Issue by mortenn** [microsoft/azure-pipelines-tasks#15997]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLIV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Azure Devops organization: FlytIT
Project: HRA
Build definition HRA-API definitionId=56
build number 1256

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Ubuntu 20.04

## Issue Description
I have defined this task in a pipeline:
```yml
    - task: DotNetCoreCLI@2
      displayName: Run integration tests
      inputs:
       command: 'run'
       arguments: '-- -a $(BaseAddress)'
       projects: |
         tests/Hra.ApiTests/Hra.ApiTests.csproj
```

Trying to use dotnet run with arguments for the project being execute fails:
```
/usr/bin/dotnet run --project /home/vsts/work/1/s/tests/Hra.ApiTests/Hra.ApiTests.csproj -- -a https://somesite.azurewebsites.net/
CSC : error CS2013: Invalid image base number 'https://somesite.azurewebsites.net'/ [/home/vsts/work/1/s/src/Hra.EntityFramework/Hra.EntityFramework.csproj]
```
Doing the same on my windows laptop works fine:
```
$ dotnet run Hra.ApiTests.csproj -- -a https://somesite.azurewebsites.net
Running tests on https://somesite.azurewebsites.net/
All 25 API tests passed!
```
