### ISSUE TITLE
Update of vstest.console.exe from 16.1 to 17.1 shows errors in log

### ISSUE THREAD

**Issue by vitaliy-ostapchuk93** [microsoft/azure-pipelines-tasks#16008]
## Bug

We noticed the recent update of the default vstest.console.exe (16.1 -> 17.1) that is used in the VSTest@2 shows error logs despite the tests itself reported as passed and the whole pipeline succeeding.

## Task

    # run unit tests
    - task: VSTest@2
      displayName: 'Release Tests'
      inputs:
        platform: '$(buildPlatform)'
        configuration: 'Release'

## Task logs

    ...
    ##[error]  Passed logInfoTest [< 1 ms]
    ##[error]  Passed logErrorTest [< 1 ms]
    ##[error]  Passed logWarningTest [< 1 ms]
    ##[error]  Passed getIsoTimeStringTest [< 1 ms]
    ##[error]  Passed resultToNameTest [< 1 ms]
    ...
    ##[error]Results File: D:\a\_temp\TestResults\VssAdministrator_WIN-40G8FPB160N_2022-03-09_10_59_24.trx
    ##[error]Test Run Successful.
    ##[error]Total tests: 24
    ##[error]     Passed: 24
    ##[error] Total time: 4.7972 Seconds

## Environment

Using the windows-latest image on the Azure DevOps pipeline. The whole solution is built with the C++ latest compiler in both Debug and Release (both project and tests)

## Troubleshooting

We can confirm that using the previous version is a workaround.

```
    # install test tools (as of 12-03-2022 the VS test shows some erros, although test passes)
    - task: VisualStudioTestPlatformInstaller@1
      inputs:
        packageFeedSelector: 'nugetOrg'
        versionSelector: 'specificVersion'
        testPlatformVersion: '16.11.0'

    # run unit tests
    - task: VSTest@2
      displayName: 'Release Tests'
      inputs:
        platform: '$(buildPlatform)'
        configuration: 'Release'
        vsTestVersion: 'toolsInstaller'
```
