### ISSUE TITLE
AzureRmWebAppDeployment@4 with webAppContainer started failing with BadRequest - The parameter LinuxFxVersion has an invalid value. (CODE: 400)

### ISSUE THREAD

**Issue by awithy** [microsoft/azure-pipelines-tasks#16024]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment@4

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private: Hosted

## Issue Description

The task started failing with 400s and the message: The parameter LinuxFxVersion has an invalid value.  There were no changes to the pipeline configuration.  This same issue is now hitting all of our deployment pipelines - none of which have changed.

### Pipeline YAML

```

resources:
  containers:
  - container: buildContainer
    type: ACR
    azureSubscription: 'REDACTED'
    resourceGroup: 'REDACTED'
    registry: 'REDACTED'
    repository: 'REDACTED'

stages:
- stage: DeployDev1
  displayName: Deploy Dev1
  jobs: 
  - deployment: DeployDev1
    displayName: DeployDev1
    environment: Dev1
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'REDACTED'
                appType: 'webAppContainer'
                WebAppName: 'REDACTED'
                DockerNamespace: 'REDACTED.azurecr.io'
                DockerRepository: 'REDACTED'
                DockerImageTag: '$(resources.container.buildContainer.tag)'

```

### Task logs

```
Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"DOCKER|REDACTED.azurecr.io/REDACTED:$(resources.container.buildContainer.tag)"}


Starting: AzureRmWebAppDeployment
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
Got service connection details for Azure App Service:'REDACTED'
Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"DOCKER|REDACTED.azurecr.io/REDACTED:$(resources.container.buildContainer.tag)"}
##[error]Error: Failed to patch App Service 'REDACTED' configuration. Error: BadRequest - The parameter LinuxFxVersion has an invalid value. (CODE: 400)
Successfully updated deployment History at https://REDACTED.scm.azurewebsites.net/api/deployments/6091647287836678
App Service Application URL: http://REDACTED.azurewebsites.net
Finishing: AzureRmWebAppDeployment
```
