### ISSUE TITLE
Nuget Restore does not use version installed with Nuget Tool Installer

### ISSUE THREAD

**Issue by balfa666** [microsoft/azure-pipelines-tasks#16053]
## Required Information
 
*Type*: Bug
**Enter Task Name**: NuGetCommandV2

## Environment
- Server - Azure Pipelines
   account: Investpsp
   team: horus
   buildname: horus
   buildId: 182879

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    -  OS: 10.0.14393
    - agent version: 2.200.2

## Issue Description

NugetRestore does not pick up the version installed by NuGetToolInstallerV1 when in different jobs. I have provided my pipelines in the attached files

### Error logs

2022-03-21T13:12:27.9691197Z ==============================================================================
2022-03-21T13:12:27.9691496Z Task         : NuGet tool installer
2022-03-21T13:12:27.9691907Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
2022-03-21T13:12:27.9692296Z Version      : 1.198.0
2022-03-21T13:12:27.9692467Z Author       : Microsoft Corporation
2022-03-21T13:12:27.9692728Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/nuget
2022-03-21T13:12:27.9693023Z ==============================================================================

2022-03-21T13:12:28.8663602Z Found tool in cache: NuGet 5.11.0 x64
2022-03-21T13:12:28.8663906Z Using version: 5.11.0

2022-03-21T13:14:02.4636472Z ==============================================================================
2022-03-21T13:14:02.4636951Z Task         : NuGet
2022-03-21T13:14:02.4637537Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2022-03-21T13:14:02.4638003Z Version      : 2.198.0
2022-03-21T13:14:02.4640343Z Author       : Microsoft Corporation
2022-03-21T13:14:02.4640766Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
2022-03-21T13:14:02.4641074Z ==============================================================================

2022-03-21T13:14:03.2878484Z Found tool in cache: NuGet 4.1.0 x64
2022-03-21T13:14:03.3028454Z Resolved from tool cache: 4.1.0
2022-03-21T13:14:03.3028775Z Using version: 4.1.0

[Documents.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8315679/Documents.zip)
[pipelines.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8315718/pipelines.zip)

**Comment by satbai** [comment]
Why not add the NuGet tool installer to the same job as the nuget restore step?

```
steps:      
  - task: NuGetToolInstaller@1
      inputs:
        checkLatest: true
        versionSpec: 5.x
  - task: NuGetCommand@2
        displayName: 'Nuget Restore'
        inputs:
          noCache: true
          solution: ${{ parameters.ProjectToBuild }}
          nugetConfigPath: .nuget/nuget.config
          selectOrConfig: config
          command: restore
```

Even better to use the recommended [NuGet Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) task instead of the NuGetCommand task.
