### ISSUE TITLE
Documentation of Docker@2 task should be updated - docker pull works fine with ACR

### ISSUE THREAD

**Issue by miniGweek** [microsoft/azure-pipelines-tasks#16071]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: `Docker@2`

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
-  Azure Pipelines
    
## Issue Description

I tried out using Docker pull functionality using the task and it worked.

Here's the task syntax
```
 - task: Docker@2
          displayName: "Docker pull from Azure ACR"
          inputs:
           command: pull
           containerRegistry: ${{ variables.containerRegistryServiceConnection }}
           repository: ${{ variables.imageRepository }} 
           arguments:  ${{ variables.containerRegistryAndRepository }}:${{ variables.tag }}
           tags: |
            ${{ variables.tag }}
```
