### ISSUE TITLE
PublishCodeCoverageResults should not warn on html generation when reportDirectory is present

### ISSUE THREAD

**Issue by karataliu** [microsoft/azure-pipelines-tasks#16084]
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 
PublishCodeCoverageResults 

## Environment
 Azure Pipelines

## Issue Description
1. agent doesn't have dotnet installed
2. the task has reportDirectory set, which already contains html report
```
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'A'
          reportDirectory: 'B'
```

In this case `PublishCodeCoverageResults` still warns about:
`##[warning]Please install dotnet core to enable automatic generation of Html report.`

This is not correct as user doesn't need html generation in this case when reportDirectory  parameter is already present.
