### ISSUE TITLE
Stage is getting skipped eventhough all dependencies seems conditions are present.

### ISSUE THREAD

**Issue by oxana-viktorovna** [microsoft/azure-pipelines-tasks#16097]
*Type*: question

## Environment
- Server - Azure Pipelines
- Agent - Private
 
## Issue Description

Stage is getting skipped eventhough all dependencies seems conditions are present.

Here are rquirements for a pipeline:
- stage 'NextTest' should be run after stage 'FakeTests' completed
- stage 'NextTest' should not depend on 'FakeTests' stage result (even if 'FakeTests' failed 'NextTest' should be run)
- stage 'NextTest' should not run if 'ToSkip' stage failed
- stage 'NextTest' should run if 'ToSkip' stage skipped.

Here is yaml:
```
stages:
- stage: ToSkip
  jobs:
  - job: Skip
    steps:
    - powershell: |
        Write-Host "Something"
- stage: FakeTests
  jobs:
  - job: PassTest
    steps:
    - powershell: |
        Write-Host "Test Passed"
  - job: FailTest
    steps:
    - powershell: |
        Write-Host "Test Failed"
        exit 1
- stage: NextTests
  dependsOn: 
  - FakeTests
  - ToSkip
  condition: | 
    and(
    in(dependencies.FakeTests.result, 'Succeeded', 'SucceededWithIssues', 'Skipped', 'Failed'),
    in(dependencies.ToSkip.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    )
  jobs:
  - job: NextPassTest
    steps:
    - powershell: |
        Write-Host "Test Passed"
```
This YAML is used as AzureDevOps pipeline. 
However if 'ToSkip' skipped and 'FakeTests' failed 'NextTest' are skipped as well. Why is that? And how to correct it? pipeline
![image](https://user-images.githubusercontent.com/102962410/161534260-585cfdf5-ae93-4f8f-9477-1fda2ca28044.png)
