### ISSUE TITLE
HelmDeploy: Unable to locate executable file: 'kubectl'

### ISSUE THREAD

**Issue by JWDobken** [microsoft/azure-pipelines-tasks#16138]
I have a pipeline task that should simply list all Helm installations;

```yaml
- task: HelmDeploy@0
  displayName: Helm list
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(myServiceConnectionTest)
    command: ls
```

But the pipeline task fails with:

```logs
Starting: Helm list
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.201.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Unable to locate executable file: 'kubectl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
Finishing: Helm list
```

In the same way, with the Kubernetes client, I can list all pods successfully:

```yaml
- task: Kubernetes@1
  displayName: kubectl get pods
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(myServiceConnectionTest)
    command: get
    arguments: pods
```

**Comment by JWDobken** [comment]
Apperently I have to login first

```yaml
- task: Kubernetes@1
  displayName: Login to Kubernetes
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(serviceConnectionTest)
    command: login
```
