### ISSUE TITLE
Please remove extraneous call-to-actions from the default code coverage output template

### ISSUE THREAD

**Issue by mattborja** [microsoft/azure-pipelines-tasks#16157]
I'm noticing some sponsorship buttons in our Code Coverage area, which is under a restricted area:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/3855027/163482333-23617f4d-dfa8-4a72-90b1-4b6de15ec7d1.png">

Please kindly remove these as this is a red flag and candidate reason for plugin removal/replacement, or advise where would be more appropriate for me to submit this request (also evaluating https://github.com/danielpalme/ReportGenerator).

I'm also happy to submit a PR if you wish.

Thank you.

Related configurations:
**azure-pipelines.yml**
```yaml
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true
    otherConsoleOptions: '/collect:"Code Coverage;Format=Cobertura"

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/TestResults/...'
    failIfCoverageEmpty: false
```
