### ISSUE TITLE
DockerComposeV0 push actually calls `docker push` instead of `docker-compose push`

### ISSUE THREAD

**Issue by TripleEmcoder** [microsoft/azure-pipelines-tasks#16152]
This might be anything from a question through a bug to a feature request...

Is there a reason that this Docker Compose task:

```yaml
  - task: DockerCompose@0
    inputs:
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Push services'
```
enumerates services by reading YAML directly and calls `docker push` in a loop, instead of calling `docker-compose push` and relying in that tool's semantics?

https://github.com/microsoft/azure-pipelines-tasks/blob/44541f598e3b59abf5da166573ea7fa913dece67/Tasks/DockerComposeV0/dockercomposepush.ts#L10
```ts
function dockerPush(connection: DockerComposeConnection, imageName: string, onCommandOut: (output: any) => any) {
    var command = connection.createCommand(); //<--- instead of createComposeCommand()
    command.arg("push");
    var arg = tl.getInput("arguments", false);
    var commandArgs = dockerCommandUtils.getCommandArguments(arg || "");
    command.line(commandArgs || "");
    command.arg(imageName);

    return connection.execCommandWithLogging(command)
    .then((output) => onCommandOut(output));
}
```

**Comment by AndreyIvanov42** [comment]
Hi @TripleEmcoder  thanks for reporting!
I think your question is more about the way it is implemented. Both implementations lead to same result.

**Comment by TripleEmcoder** [comment]
Well, not exactly. The reason I asked is because the behavior is different, actually, or least does not allow the same scenarios. My use case is pushing only a single image from a multi-container (duh) docker-compose.yml (e.g. service1, service2).

Running docker-compose directly and specifying the container name works as expected:
```
docker-compose push service1
```

Things are different when running DockerCompose@0 even with custom arguments (which is obvious once you look into the implementation):
```
- task: DockerCompose@0
    inputs:
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Push services'
      arguments: service1
```

Internally the task enumerates services and issues docker push manually which leads to:
```
docker push service2 service1
````

I always thought of Azure Pipelines tasks named after preexisting tools (i.e. NuGet, Docker, DockerCompose) as rather thin wrappers, switching the command entirely was unexpected, at least for me.
