### ISSUE TITLE
AzureFunctionAppV1 fails due to missing permission to perform joinViaServiceEndpoint/action on subnet

### ISSUE THREAD

**Issue by rantsi** [microsoft/azure-pipelines-tasks#16167]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionAppV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

Private agent Agent.Version: 2.200.2 Agent.OSVersion: 10.0.17763

## Issue Description

During the deployment the build prints a warning and fails:
`##[warning]Failed to update App Service configuration details. Error: Error: Failed to update App service 'func-xxx-dev' configuration. Error: The client 'xxxx...' with object id 'xxxx...' has permission to perform action 'Microsoft.Web/sites/config/write' on scope '/subscriptions/xxx.../resourceGroups/rg-xxx/providers/Microsoft.Web/sites/func-xxxx-dev/config/web'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/xxx.../resourceGroups/rg_xxx/providers/Microsoft.Network/virtualNetworks/vnet-xxx-dev/subnets/snet-xxx-dev' or the linked scope(s) are invalid. (CODE: 403)` 

yaml for step:
```
- task: AzureFunctionApp@1 
  displayName: 'Deploy Azure Function App' 
  inputs: 
    azureSubscription: '$(Parameters.AzureSubscription)' 
    appType: '$(Parameters.AppType)' 
    appName: '$(Parameters.AppName)'
```

Using the same credentials to publish the same package with [PowerShell](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#with-powershell) using _Publish-AZWebApp_ completes successfully.
