### ISSUE TITLE
Looks like packDestination of DotNetCoreCLI@2 is not working when using the pack command

### ISSUE THREAD

**Issue by JohanKlijn** [microsoft/azure-pipelines-tasks#16171]
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server: Azure Pipelines
- Agent: Hosted
    
## Issue Description

In my pipeline I am using the following yaml to create nuget packages for my project.
```yaml
      - task: DotNetCoreCLI@2
        displayName: 'Build Nuget package assemblies'
        inputs:
          command: pack
          packagesToPack: 'assemblies/project1/project1.csproj'
          packDestination: '$(Build.ArtifactStagingDirectory)/nuget/generatedpackages'
          verbosityPack: Detailed
```
I would expect the nuget packages will be stored in  '$(Build.ArtifactStagingDirectory)/nuget/generatedpackages', which should be resolved to '/home/vsts/work/1/a/nuget/generatedpackages'. Unfortunately the package are stored in the root ''/home/vsts/work/1/a'.

When I look a the log information, it looks like the packDestination is not passed to the command:
```
Starting: Build Nuget package assemblies
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/usr/bin/dotnet pack /home/vsts/work/1/s/assemblies/project1/project1.csproj --output /home/vsts/work/1/a /p:Configuration=Release --verbosity Detailed

```
