### ISSUE TITLE
Docker repository ***/ prefix

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/azure-pipelines-tasks#16186]
From the docs:

> repository | (Optional) Name of repository within the container registry corresponding to the Docker registry service connection specified as input for containerRegistry. Prefix with username/ for DockerHub.

- Why does the task automatically prefix *****/** to the repository name? Can I disable this so I can run `docker create` without it throwing an exception for reference format?
- The tags property is dependent on repository being present. If no repository is specified, no tags are added.

I am hitting an issue because I am unable to run `docker create -i -t --name pipelinecontainer my-container:$(Build.BuildId)` due to the image not being found (because it's prefixed with *****/**). If I were to change my command to `docker create -i -t --name pipelinecontainer ***/my-container:$(Build.BuildId)` docker throw an error for invalid reference.

If I remove the repository property, then I run into an issue with docker publish since it requires a repository.

Basic Idea:

```
          - task: Docker@2
            displayName: "docker build"
            inputs:
              containerRegistry: 'azureContainerConnection'
              command: 'build'
              repository: my-container
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
              arguments: '--target build'
       ....
          - task: Bash@3
            displayName: "Copy Artifacts to Pipeline"
            inputs:
              targetType: 'inline'
              script: |
                docker image ls
                docker create -i -t --name pipelinecontainer my-container:$(Build.BuildId)
                docker cp pipelinecontainer:/app/clients/ $(Build.ArtifactStagingDirectory)/clients
                docker rm -fv pipelinecontainer
```

I don't know if there's special meaning in docker with the prefix of ***/ but it seems to be the root cause here.
