### ISSUE TITLE
`conda` pipeline cache restoration fails due to `tar` permission errors

### ISSUE THREAD

**Issue by kracwarlock** [microsoft/azure-pipelines-tasks#16203]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `Cache@2`

## Environment
- Server - Azure Pipelines
- Agent - Private: `ubuntu-latest`

## Issue Description

`conda` cache restore fails for me when there is a cache hit. My pipeline looks like this:

```
variables:
  CONDA_CACHE_DIR: /usr/share/miniconda/envs

jobs:
- job: linux
  displayName: 'linux'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'

  - task: Cache@2
    displayName: 'Use cached Anaconda environment'
    inputs:
      key: 'conda | "$(Agent.OS)" | ./path/to/environment.yml'
      restoreKeys: |
        python | "$(Agent.OS)"
        python
      path: $(CONDA_CACHE_DIR)
      cacheHitVar: CONDA_CACHE_RESTORED

  - script: conda env create --quiet --file ./path/to/environment.yml
    displayName: 'Create Anaconda environment'
    condition: eq(variables.CONDA_CACHE_RESTORED, 'false')
```

### Task logs

```
Starting: Use cached Anaconda environment
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - conda                               [string]
 - "Linux"                             [string]
 - ./path/to/environment.yml [file] --> CE6835D05F47D13C49BFD8CFB04382EBC31EF0AEAB979BEC77BE8DDFD692E507
Resolved to: conda|"Linux"|5t960bBvEneiw0sDGdszQ6mbszk6XbP6cuDzEiOLiKw=
Resolving restore key:
 - python [string]
Resolved to: python|**
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 655c5ba7-ffd7-4cc1-8bc3-db4ac8b3a271
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `conda|"Linux"|5t960bBvEneiw0sDGdszQ6mbszk6XbP6cuDzEiOLiKw=`
Fingerprint: `python|"Linux"|**`
Fingerprint: `python|**`
There is a cache hit: `conda|"Linux"|5t960bBvEneiw0sDGdszQ6mbszk6XbP6cuDzEiOLiKw=`
Used scope: <removed>
Entry found at fingerprint: `conda|"Linux"|5t960bBvEneiw0sDGdszQ6mbszk6XbP6cuDzEiOLiKw=`
Expected size to be downloaded: 243.9 MB
Downloaded 0.0 MB out of 243.9 MB (0%).
Downloaded 183.3 MB out of 243.9 MB (75%).
Downloaded 243.9 MB out of 243.9 MB (100%).

Download statistics:
Total Content: 243.9 MB
Physical Content Downloaded: 103.7 MB
Compression Saved: 140.2 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 2,949
Nodes Downloaded: 6

tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
ApplicationInsightsTelemetrySender correlated 3 events with X-TFS-Session 655c5ba7-ffd7-4cc1-8bc3-db4ac8b3a271
##[error]Process returned non-zero exit code: 2
Finishing: Use cached Anaconda environment
```
