### ISSUE TITLE
HelmDeployV0: updatedependency broken for v3+

### ISSUE THREAD

**Issue by fredzach** [microsoft/azure-pipelines-tasks#16281]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeployV0  

## Issue Description

This task allows for the parameter `updatedependency`, but this does not work for Helm v3+.

Helm v3 renamed the option `--dep-up` to `--dependency-update`, but this task still only supports the v2 version (without noting this in the docs).

```yaml
  - task: HelmDeploy@0
    inputs:
      updatedependency: true
```

I'm planning to pick this up myself.
