### ISSUE TITLE
Setting output variable directly from AzureResourceManagerTemplateDeployment@3 deployment output value gives leading whitespace

### ISSUE THREAD

**Issue by feliasson** [microsoft/azure-pipelines-tasks#16280]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

## Environment
- Server - Azure Pipelines
- Agent - Private, Ubuntu20.04 
  - Azure DevOps + VMSS
  - VM-extension (Microsoft.Azure.DevOps.Pipelines.Agent - Microsoft.VisualStudio.Services.TeamServicesAgentLinux - 1.22)
    
## Issue Description

Setting output variables with "##vso[task.setvariable]" using the deployment output values directly from AzureResourceManagerTemplateDeployment@3 task gives leading whitespace in the results.

![image](https://user-images.githubusercontent.com/45947114/166719646-8b4d9251-8c32-4cc2-8fb9-a1c57d99039f.png)

```
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy ExpressRoute Circuit
  inputs:
    <obfuscated>
    deploymentMode: Incremental
    deploymentOutputs: ercOutputs
```

```
- powershell: |
    Write-Host "##vso[task.setvariable variable=ercId;isOutput=true]$(ercOutputs.ercId.value)"
    Write-Host "##vso[task.setvariable variable=ercLocation;isOutput=true]$(ercOutputs.ercLocation.value)"
  displayName: 'Write output variables'
  name: ercVars

```

Next job using the output variables as stageDependencies:

```
- stage: MyNextStage
  dependsOn:
  - TheOtherStage

  jobs:

  - job: ExpressRouteGatewayAndConnection
    displayName: 'Deploy Expressroute Gateway and Connection'
    variables:
      ercId: $[stageDependencies.ExpressRouteCircuit.DeployExpressRouteCircuit.outputs['ercVars.ercId']]
      ercLocation: $[stageDependencies.ExpressRouteCircuit.DeployExpressRouteCircuit.outputs['ercVars.ercLocation']]
```

### Task logs

The job preparation parameters result always have a leading whitespace, and I guess this is not intended. This seems to have made the parameter validation for my next job fail atleast.

![image](https://user-images.githubusercontent.com/45947114/166723768-0f8e1ba3-d7ab-4be0-90f8-e8dd8d2be19f.png)

### Troubleshooting

I am fully aware that I can solve this by doing the traditional example.

```
        $json = ConvertFrom-Json '$(ercOutputs)'
        Write-Host "##vso[task.setvariable variable=ercId;isOutput=true]$($json.ercId.value)"
        Write-Host "##vso[task.setvariable variable=ercLocation;isOutput=true]$($json.ercLocation.value)"
```

However if this could be used properly it would feel atleast a bit smoother working with the outputs. 

### Error logs

```
2022-05-04T14:38:29.1504100Z There were errors in your deployment. Error code: InvalidDeploymentParameterKey.
2022-05-04T14:38:29.1507327Z ##[error]One of the deployment parameters has an empty key. Please see https://aka.ms/resource-manager-parameter-files for details.
2022-05-04T14:38:29.1528085Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
2022-05-04T14:38:29.1542329Z ##[error]Task failed while creating or updating the template deployment.
```
