### ISSUE TITLE
Build is failing when PackageVersion is specified using floating version

### ISSUE THREAD

**Issue by koljada** [microsoft/azure-pipelines-tasks#16325]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
**Server** Azure Pipelines
https://techfinity.visualstudio.com/Lib.Azure/_build/results?buildId=1192&view=logs&j=85d215f4-f754-5125-7b2d-475e6367e012&t=c0f78b06-671a-5a39-9fbb-99e756047ab8
**Agent** Hosted agent using `windows-2022`

## Issue Description

Dotnet build is failing when PackageVersion in the .csproj is specified using floating version number(e.g. using asterisks). After I specify an exact package version(3.0.1.1 in my case) everything works fine.

Here is my pipeline:

```
jobs:
- job: BuildAndPublishNugetPackage  

  variables:
    buildConfiguration: Release
    nugetFeed: TechfinityWeb
    projectPath: '${{ parameters.project }}/*.csproj'

  pool:
    vmImage: 'windows-2022'
  
  steps:

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 6.x.x

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: restore
      nobuild: true
      vstsFeed: $(nugetFeed)
      projects: '${{ parameters.project }}/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      vstsFeed: $(nugetFeed)
      projects: $(projectPath)
      arguments: '--configuration $(buildConfiguration)'
```

Here is my .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<Authors>Roman Koliada</Authors>
		<Company>Techfinity</Company>
		<Description>Domain entity interfaces, DTO's, enums, helpers</Description>
		<PackageTags>SaaSFramework Domain</PackageTags>
		<Copyright>Techfinity Ltd ©  2022</Copyright>
		<Version>3.0.1</Version>
		<!--<PackageVersion>$(Version).$([System.DateTime]::Now.ToString("MMddHHmm"))</PackageVersion>-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="readme.md" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="readme.md">
	    <PackagePath>readme.md</PackagePath>
	    <Pack>true</Pack>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SaaSFramework.Infrastructure.Abstractions" Version="3.0.*" />
	</ItemGroup>
</Project>
```

### Task logs
Here are my logs:
[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8689654/logs.zip)

### Error logs

##[error]SaaSFramework.Domain\SaaSFramework.Domain.csproj(0,0): Error NU1101: Unable to find package SaaSFramework.Infrastructure.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
