### ISSUE TITLE
KubernetesManifest@0 createSecret fails when value contains a space (multiline) with error "exactly one NAME is required, got 3"

### ISSUE THREAD

**Issue by adrien-constant** [microsoft/azure-pipelines-tasks#16343]
## Required Information

*Type*: BUG

**Enter Task Name**:  KubernetesManifest@0  

## Environment
- Server - Azure Pipelines 
- Account name: scamark
- Team Project Name: Website/IdentityServer
- Build number: 0.1.168
    
- Agent - Hosted or Private: HOSTED

## Issue Description

When using task `KubernetesManifest@0` with action `createSecret` and multiline secrets, the task fails when the value used after the "=" contains a space. Using the quote sign doesn't fix the issue.

### Example

`$(ConnectionString.IdentityServer)` value contains a space (User ID=)

```
  - task: KubernetesManifest@0
            displayName: Create secrets
            inputs: 
              kubernetesServiceConnection: Kubernetes-Production
              action: createSecret
              namespace: $(namespace)
              secretType: generic
              secretName: identity-server-secrets
              secretArguments:
                --from-literal=auth.keytab=$(auth-keytab)
                --from-literal=ConnectionString_IdentityServer=$(ConnectionString.IdentityServer)
```

### Task logs

```
/usr/local/bin/kubectl create secret generic identity-server-secrets --from-literal=auth.keytab=*** --from-literal=ConnectionString_Users=***
##[error]error: exactly one NAME is required, got 3
```
