### ISSUE TITLE
AzureCLI@2 ps script not passing arguments

### ISSUE THREAD

**Issue by martinjanocko** [microsoft/azure-pipelines-tasks#16373]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI@2

## Issue Description

Have following tasks:

```
         - task: AzureCLI@2
            inputs:
              azureSubscription: '<sub>'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              arguments: 'ps_param1'
              inlineScript: |
                Write-Output "PS param test:"
                Write-Output $1

          - task: AzureCLI@2
            inputs:
              azureSubscription: '<sub>'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              arguments: 'bash_param1'
              inlineScript: |
                echo "Bash param test:"
                echo $1
```

The output is as follows:

PS param test:
Bash param test:
bash_param1

The argument in ps type script is not passed on. Also checking the PSBoundParameters.Count == 0.

### Task logs

```
Pool: [Azure Pipelines](https://dev.azure.com/<org>/_settings/agentqueues?poolId=&queueId=2943)
Image: windows-latest
Agent: Azure Pipelines 3

Starting: AzureCLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.36.0 *


Please let us know how we are doing: https://aka.ms/azureclihats
core                              2.36.0 *
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
telemetry                          1.0.6

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

```
