### ISSUE TITLE
Result formats mapping attribuite issues

### ISSUE THREAD

**Issue by ASHR4** [microsoft/azure-pipelines-tasks#16387]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishTestResults@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

I use TFLint to lint my Terraform code - I want to use the classname, from the xml, as the Test Result Title and not the name attribuite - Please shoot me down if any of these options are not viable :)

![image](https://user-images.githubusercontent.com/72310905/171229702-103e7f55-3162-4cc5-a232-f777b228ad80.png)

[Link to above](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=junit%2Cyaml)

I also have raised a Issue on TFlint side to see if anything can be done from either side

### Suggestion 1

Update JUnit Result Format Mappings to include:

/testsuites/testsuite/testcase/Attributes["name"].Value or
/testsuites/testsuite/testcase/Attributes["classname"].Value

### Suggestion 2

Allow the Attribuite to be passed in as a paramter in the task

```yaml
# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    #testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    #testResultsFiles: '**/TEST-*.xml' 
    **#testResultAttribuiteTitle: '/testsuites/testsuite/testcase/Attributes["name"].Value' # Options: /testsuites/testsuite/testcase/Attributes["name"].Value, /testsuites/testsuite/testcase/Attributes["classname"].Value**
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
```

Any advice on how I could achieve this outside of the task would be greatly appreciated

Thanks Guys!
