### ISSUE TITLE
AzurePowerShell@5 fails to execute if an Azure devops pipeline variable exists named ImageVersion

### ISSUE THREAD

**Issue by rybal06** [microsoft/azure-pipelines-tasks#16404]
This may be an edge case, but it took some time to figure out what was happening and reporting this help someone else in the future. If a pipeline variable is set for imageversion, the AzurePowerShell@5 task fails to start with this error:

```pwsh
Import-Module: An item with the same key has already been added. Key: IMAGEVERSION
```

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
    Hosted
    - If using Hosted agent, provide agent queue name: 
     fv-az31-869, version 2.204.0

## Issue Description

AzurePowerShell@5

Take this sample pipeline:

```yaml
pool:
  vmImage: ubuntu-latest

steps:
  - task: AzurePowerShell@5
    displayName: 'Use it once'
    inputs:
      azureSubscription: my
      pwsh: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
         Write-Host "##vso[task.setvariable variable=imageVersion;]samplevalue"


  - task: AzurePowerShell@5
    displayName: 'Try again'
    inputs:
      azureSubscription: my
      pwsh: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        write-host "instantiate this again"

```

### Error logs
```pwsh
Import-Module: An item with the same key has already been added. Key: IMAGEVERSION
```

### Workaround
The workaround is quite simple, change the name of the variable to something other than imageVersion, i.e. MYImageVersion
```pwsh
Write-Host "##vso[task.setvariable variable=MYimageVersion;]samplevalue"
```
