### ISSUE TITLE
Kubernetes@1 exec against deployment name

### ISSUE THREAD

**Issue by JWDobken** [microsoft/azure-pipelines-tasks#16424]
Executing a command against the deployment name is more stable when pod names get generated hash names, so normally this should be a fine setup:

```yaml
- task: Kubernetes@1
  displayName: kubectl create file
  inputs:
    namespace: $(clusterNameSpace)
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(serviceConnection)
    command: exec
    arguments: deploy/deployment-name -- bash -c "touch $HOME/hello.txt"
```

which is the `kubectl` equivalent of:

```cmd
kubectl exec deploy/<deployment-name> -- bash -c "touch $HOME/hello.txt"
```

But gives the following error:

```logs
##[error]error: invalid resource name "deploy/deployment-name": [may not contain '/']
```

I consider this is a bug
