### ISSUE TITLE
'Tcl wasn't installed properly' on python test workflow

### ISSUE THREAD

**Issue by mscheltienne** [microsoft/azure-pipelines-tasks#16426]
I got a couple of workflow running on a matrix of `(windows, macOS, ubuntu)` with python `(3.7, 3.8, 3.9, 3.10)`. **_Randomly_**, some of the windows tests will fail when trying to show matplotlib figures with the error message:

```
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: Can't find a usable init.tcl in the following directories: 
E           {C:\hostedtoolcache\windows\Python\3.7.9\x64\tcl\tcl8.6}
E       
E       C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl: couldn't read file "C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl": No error
E       couldn't read file "C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl": No error
E           while executing
E       "source C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel #0 [list source $tclfile]"
E       
E       
E       This probably means that Tcl wasn't installed properly.
```

Any idea how to solve this and make it work 100% of the time? It looks to me like Python is not always correctly setup by:

```
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
```

For x-ref: https://github.com/vferat/pycrostates/pull/41

**Comment by hodgestar** [comment]
We see the same in QuTiP's builds on Windows, e.g. https://github.com/qutip/qutip/runs/7696687924. It's mysterious to me how its possible that only some workers don't have Python Tcl installed correctly.

**Comment by janosh** [comment]
Having the same problem over at https://github.com/janosh/pymatviz ([CI run](https://github.com/janosh/pymatviz/actions/runs/3317205803/jobs/5479817275#step:5:103)). Curious if anyone has a hypothesis why this is flaky.

**Comment by janosh** [comment]
[This discussion](https://github.com/orgs/community/discussions/26434) suggests setting the `matplotlib` backend prior to plotting helps:


```yml
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
     ...
```
