### ISSUE TITLE
CopyFilesOverSSH: not honoring overwrite eq false

### ISSUE THREAD

**Issue by victorbrca** [microsoft/azure-pipelines-tasks#16447]
## Required Information

*Type*: Bug

**Task Name**: CopyFilesOverSSH

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/CopyFilesOverSSHV0

## Environment
- Server - Azure Pipelines
- Agent - Hosted 
  - Image: windows-latest

## Issue Description

We have a pipeline with a Windows based agent that goes through promotion requests and linked tasks, downloads attached files, deploys them to our servers and then copies them to a Linux SFTP server. The problem is that we have configured our SCP task to not overwrite the files, but it keeps overwriting them. 

The task is configured as the following:

_Task_
```
    - task: CopyFilesOverSSH@0
      displayName: 'Upload deployment files'
      inputs:
        sshEndpoint: 'custom-automation-sftp-connection'
        sourceFolder: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/AutomationBuild/SFTP'
        contents: '**'
        targetFolder: '/home/user/data/Bundles/'
        cleanTargetFolder: false
        overwrite: false
```

Unfortunately, I can't post screenshots due to sensitive information. But after enabling debug on the pipeline I can see that it looks for the files, and even though they are there, it doesn't see them... hence why it's overwriting the files. 

I think that there might be a chance that the task is not converting back slashes to forward slashes when checking for the files (but it does when copying them).

### Task logs

File listing on the Linux server showing modified timestamp for 2 consecutive runs:

![2022-06-07_15-27-21](https://user-images.githubusercontent.com/9310736/173453694-1be14a4d-484f-4774-b632-190b63adbec5.png)

![2022-06-07_15-16-04](https://user-images.githubusercontent.com/9310736/173454116-64e64a7d-142e-49e4-951f-6cf0f4ff86b9.png)

Here you can see more clear the use of back slashes and forward slashes:

```
##[debug]Checking if /home/user/data/Bundles/PD\20220607\####\1_####_S2_Create user ID-####.sql on the remote machine exists.
##[debug]/home/user/data/Bundles/PD\20220607\####\1_####_S2_Create user ID-####.sql doesn't exist on the remote machine
##[debug]Upload D:\a\1\s\#### Bundle Repository\AutomationBuild\SFTP\PD\20220607\####\1_####_S2_Create user ID-####.sql to /home/user/data/Bundles/PD/20220607/####/1_####_S2_Create user ID-####.sql on remote machine.
```
