### ISSUE TITLE
App Center Test failing to find App Center CLI

### ISSUE THREAD

**Issue by TheresasAccount** [microsoft/azure-pipelines-tasks#16484]
## Required Information
**Bug**  
*Type*: Task failing when it previously worked

**Enter Task Name**: App Center Test

## Environment
- Server - Azure Pipelines
    

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name:  Windows-latest

## Issue Description

Starting last night all( 6) of my nightly testing release pipelines using App Center Test failed with the error:
##[error]Error: Not found CLI for Visual Studio App Center: D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.205.2\node_modules\.bin\appcenter.cmd
![image](https://user-images.githubusercontent.com/50762188/175322320-9d7cdb1f-d6e9-43d2-b9cd-cffb3c431d24.png)

As far as I can tell nothing has changed, there are no new versions, I am using the latest build environment, and it should still work. 

There are only 3 tasks in the release pipelines: Install Node, App Center Test, and Create Work Item
![image](https://user-images.githubusercontent.com/50762188/175323534-51983ef5-64c2-48bf-b296-07ef7d7785bd.png)

### Task logs

2022-06-23T14:12:30.7268558Z ##[section]Starting: Test with Visual Studio App Center
2022-06-23T14:12:30.7473055Z ==============================================================================
2022-06-23T14:12:30.7473358Z Task         : App Center test
2022-06-23T14:12:30.7473627Z Description  : Test app packages with Visual Studio App Center
2022-06-23T14:12:30.7473852Z Version      : 1.205.2
2022-06-23T14:12:30.7474043Z Author       : Microsoft Corporation
2022-06-23T14:12:30.7474353Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/app-center-test
2022-06-23T14:12:30.7474701Z ==============================================================================
2022-06-23T14:12:31.8438981Z ##[error]Error: Not found CLI for Visual Studio App Center: D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.205.2\node_modules\.bin\appcenter.cmd
2022-06-23T14:12:31.8451807Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8452353Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8452894Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8454045Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8454749Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8455154Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8455558Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8455945Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8456922Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8457318Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8457716Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8458558Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8459535Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8459985Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8460696Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8461356Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8461766Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8465095Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8465626Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8466019Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8466422Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8466809Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8467220Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8467620Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8468020Z (node:1620) Warning: Use Cipheriv for counter mode of aes-256-ctr
2022-06-23T14:12:31.8543539Z ##[section]Finishing: Test with Visual Studio App Center

## Troubleshooting
Using a step to install node ahead of time, tried using the latest version instead of the required 10.15.1, did not solve the issue.

Have re-run a build which was successful in the past to make sure the build didn't break anything and the same error occurs.

### Error logs

##[error]Error: Not found CLI for Visual Studio App Center: D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.205.2\node_modules\.bin\appcenter.cmd

**Comment by akrol95** [comment]
We are facing exactly the same issue.

**Comment by rygo-msft** [comment]
I see this as well. It looks like the regression may be this change https://github.com/microsoft/azure-pipelines-tasks/pull/16288

**Comment by dominik-weber** [comment]
same issue here

**Comment by Jaax90** [comment]
The same problem

**Comment by TheresasAccount** [comment]
@alexey-chernikov This did not fix the issue for me. After doing this I started getting the error:
Error: Error: spawn "D:\a\r1\a\_APM Mobile Android Yaml\Inspections UI Tests\test-cloud.exe" ENOENT

Which again nothing has changed so this should work.

I added a task to make sure the file is there, copying the path from the error:
![image](https://user-images.githubusercontent.com/50762188/175968729-35f234c7-6b2e-4581-bdc8-53bbdd58d709.png)

Which returns:
![image](https://user-images.githubusercontent.com/50762188/175968861-2cc8a254-0599-4415-bb03-3cb25dabefab.png)

So the file exists exactly where it should be, but now it doesn't get found when the npm install is done seperately

**Comment by alexey-chernikov** [comment]
@TheresasAccount Could you please try specify specific version? Specific version which used before was 1.1.15

`npm install -g appcenter-cli@1.1.15`

**Comment by TheresasAccount** [comment]
@alexey-chernikov 1.15 didn't quite do the trick, but the package.json was ^1.15, so I tried 

npm install -g appcenter-cli@1.2.2

And it worked. Thanks for the help

**Comment by sergei-fedorov** [comment]
We rolled back the task to previous version 1.198.0. Please check if it works for you.

**Comment by dominik-weber** [comment]
@sergei-fedorov works :) thanks!

**Comment by sergei-fedorov** [comment]
@dominik-weber, @TheresasAccount could you please describe how you run tests with AppCenterTest task using built-in old appcenter-cli 1.2.2? When I tried to do so it fails with "command invalid", like this: 
```
Error: Command test prepare uitest --artifacts-dir AppCenterTest --app-path Palisade.ipa --build-dir build --uitest-tools-dir build --quiet is invalid
```

But if I add Command Line Script with `npm install -g appcenter-cli` to install latest version - I can run a test with the same arguments as it failed on built-in appcenter.
It would be great if you provided your configuration.

**Comment by dominik-weber** [comment]
@sergei-fedorov we use the task like this in our yaml pipeline:

```
      steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: '10.x' # https://github.com/microsoft/appcenter-cli/issues/696
      - task: NuGetCommand@2
        displayName: 'Install Xamarin.UITest $(uiTestVersion)'
        inputs:
          command: 'custom'
          arguments: 'install Xamarin.UITest -Version "$(uiTestVersion)" -OutputDirectory "$(System.DefaultWorkingDirectory)/packages"'
      - task: AppCenterTest@1
        inputs:
          appFile: '$(apkDrop)'
          artifactsDirectory: '$(System.DefaultWorkingDirectory)/AppCenterTest'
          frameworkOption: 'uitest'
          uiTestBuildDirectory: '$(testAssemblyPath)'
          uiTestToolsDirectory: '$(System.DefaultWorkingDirectory)/packages/Xamarin.UITest.$(uiTestVersion)/tools'
          credentialsOption: 'serviceEndpoint'
          serverEndpoint: 'App Center'
          appSlug: 'open-as-app/open-as-app-android'
          devices: 'open-as-app/default-android-devices'
          series: '$(Build.SourceBranchName)'
          localeOption: 'en_US'
```

please note that there are a couple of "hacks" in place that unfortunately are required to make the task work for us:
1. we need to force node 10.x, anything more recent does NOT work
2. we need to manually install the nuget package as the command needs the .exe file that is shipped in the nuget. Because the version needs to be identical to the one used when building the test assemblies (we're building the assemblies in an earlier stage of the pipeline), we keep the `uiTestVersion` variable in the yaml file in sync with the package reference in the csproj.
