### ISSUE TITLE
DotNetCli Nuget Restore nuget.config gets re-used/can't change

### ISSUE THREAD

**Issue by mattdurak** [microsoft/azure-pipelines-tasks#16482]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: msazure, Azure-Messaging-ElasticLog, Build 56848508

- Agent - Hosted or Private: Private?
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Azure-MessagingStore-IntTestPoolVS2022 1, Windows...

## Issue Description

When running DotNetCoreCLI@2 for "restore" multiple times, the nuget.config path is ignored the second time.

E.g.

```yaml
...
- task: UseDotNet@2
  displayName: Use .NET 6 SDK
  inputs:
    packageType: sdk
    version: 6.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6.2'
  inputs:
    versionSpec: 6.2.*

- task: NuGetAuthenticate@1

- task: DotNetCoreCLI@2
  displayName: 'NuGet restore Some Solution'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)\build\elastic_log.sln'
    feedsToUse: 'config'
    nugetConfigPath: '$(Build.SourcesDirectory)/MyPath1/nuget.config'
    noCache: true

- task: CmdLine@2
  displayName: 'DEBUG SHOW NUGET CONFIG'
  inputs:
    script: 'type $(Pipeline.Workspace)\Nuget\tempNuGet_$(Build.BuildID).config'
  condition: always()

- task: DotNetCoreCLI@2
  displayName: 'NuGet restore Other Solution'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)\build\test.sln'
    feedsToUse: 'config'
    nugetConfigPath: '$(Build.SourcesDirectory)/MyPath2/nuget.config'
    noCache: true

- task: CmdLine@2
  displayName: 'DEBUG SHOW NUGET CONFIG 2'
  inputs:
    script: 'type $(Pipeline.Workspace)\Nuget\tempNuGet_$(Build.BuildID).config'
  condition: always()
```

Example $(Build.SourcesDirectory)/MyPath1/nuget.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="MSAzure" value="https://msazure.pkgs.visualstudio.com/One/_packaging/MY-FEED/nuget/v3/index.json" />
    </packageSources>
</configuration>
```

Example $(Build.SourcesDirectory)/MyPath2/nuget.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="LocalFeed" value="%BUILD_BINARIESDIRECTORY%\RelWithDebInfo\test_nuget" />
        <add key="MSAzure" value="https://msazure.pkgs.visualstudio.com/One/_packaging/MY-FEED2/nuget/v3/index.json" />
    </packageSources>
</configuration>
```

Expected:

Each invocation of NuGet restore will use the provided nuget.config.

Actual, the first time it is executed a file is created at `$(Pipeline.Workspace)\Nuget\tempNuGet_$(Build.BuildID).config` with the provided config (and then auth keys are added). The second time, the file exists so the nuget.config from nugetConfigPath is ignored (silently).

I looked at the source here and it seems to be due to the behavior of `ensureTempConfigCreated()` which uses the existing file even if there is a different config provided https://github.com/microsoft/azure-pipelines-tasks/blob/4db190650be134609d0ea2b8e5294fc80bf0b5b6/Tasks/Common/packaging-common/nuget/NuGetConfigHelper2.ts#L44

I am not familiar enough with this code or Typescript to send a PR or I would suggest a fix, but I don't think that the same temp config should be used across all invocations of the DotNetCLI task.

I've wasted a full day figuring this out, but hopefully now that it is known it can be fixed.

### Task logs

Can provide if needed but the repro is very easy

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Can provide if needed but the repro is very easy
