### ISSUE TITLE
UseDotNet@2 - Need both x64 and x86 SDKs - DOTNET_ROOT and DOTNET_ROOT(x86)

### ISSUE THREAD

**Issue by nietras** [microsoft/azure-pipelines-tasks#16501]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: UseDotNet@2

## Environment
- Server - Azure Pipelines or TFS on-premises?    Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10 x64, agent version 2.186.1

## Issue Description
We have a pipeline defined which summarized does something like below. This has worked for a long time on our build servers running Windows 10.
```yml
- task: UseDotNet@2
  displayName: 'Use .NET'
  inputs:
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet test x86'
  inputs:
    command: test
    arguments: '--nologo -c $(BuildConfiguration) --no-restore -- RunConfiguration.TargetPlatform=x86 /Parallel'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test x64'
  inputs:
    command: test
    arguments: '--nologo -c $(BuildConfiguration) --no-restore -- RunConfiguration.TargetPlatform=x64 /Parallel'
```
 However, recently this stopped working with an error like:
```
D:\agent\_work\_tool\dotnet\dotnet.exe test --logger trx --results-directory D:\agent\_work\_temp --nologo -c Release --no-restore -- RunConfiguration.TargetPlatform=x86 /Parallel

...

Could not find 'dotnet.exe' host for the 'X86' architecture.

You can resolve the problem by installing the 'X86' .NET.

The specified framework can be found at:
  - https://aka.ms/dotnet-download

Could not find 'dotnet.exe' host for the 'X86' architecture.

You can resolve the problem by installing the 'X86' .NET.

The specified framework can be found at:
  - https://aka.ms/dotnet-download
```
We have no idea why this suddenly stopped working. However, we quickly realized the specific command (in same working directory) worked fine outside the context of the pipeline. I.e. the following worked fine:
```powershell
D:\agent\_work\_tool\dotnet\dotnet.exe test --logger trx --results-directory D:\agent\_work\_temp --nologo -c Release --no-restore -- RunConfiguration.TargetPlatform=x86 /Parallel
```
but when run (i.e. in powershell task) this would fail just like the `DotNetCoreCLI@2` task would.

Debugging this the difference came down to `UseDotNet@2` automatically defining the `DOTNET_ROOT` environment variable. I don't know if this has changed or if .NET itself starting using it but the definition of it caused our builds to not work.

By defining `DOTNET_ROOT(x86)` in a task in powershell would then let us resolve this issue, but then the pipeline is dependent on the x86 SDK being installed on the machine and not by being installed by `UseDotNet` and we would really like for pipelines to be independent of SDKs installed on machine, that is after all the purpose of `UseDotNet` task.
```yml
- powershell: |
    Write-Host "Setting environment variable DOTNET_ROOT(x86)=${{ parameters.DotNetRootX86 }}"
    Write-Host "##vso[task.setvariable variable=DOTNET_ROOT(x86)]${{ parameters.DotNetRootX86 }}"
  displayName: 'Set `DOTNET_ROOT(x86)` environment variable'
```

It seems however this scenario is not supported? This seems like something that really should be supported, the ability to install both x86 and x86 SDKs (on x64 agent).

**Comment by pharring** [comment]
I think I have the same -- or at least a similar problem.
My pipeline builds a tool that has both x86 and x64 versions of a .NET 6 executable. So, my test cases require that both the x86 and x64 .NET 6 runtime is installed.

As far as I can tell, UseDotNet installs only the x64 runtime. Is there a way to get it to install the x86 runtime?

**Comment by MaceWindu** [comment]
Workaround: because task taskes architecture from [PROCESSOR_ARCHITECTURE](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2/externals/get-os-platform.ps1#L4) environment variable, it is possible to install x86 SDK by overriding variable for task:
```yaml
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 7.x
  env:
    PROCESSOR_ARCHITECTURE: x86
```

**Comment by nietras** [comment]
@MaceWindu nice trick, but this does not allow both being present at the same time does it?

**Comment by nietras** [comment]
@MaceWindu have you tried it? Having two tasks:
```yml
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 7.x
  env:
    PROCESSOR_ARCHITECTURE: x86
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 7.x
```
what happens then? This is installed to default `_tool` directory which has no concept of both having x86 and x64 at the same time. Perhaps it can be done with `installationPath` and `DOTNET_ROOT(x86)` which I am trying now, but currently suffering from some nuget issues that I am unsure are related to this.
