### ISSUE TITLE
##[error]An image does not exist locally with the tag: ***/image/repo

### ISSUE THREAD

**Issue by Parkhost** [microsoft/azure-pipelines-tasks#16502]
Seems to be impossible to push a docker image with Docker@2 **_without_** using the build option.

Am trying to push a custom docker image (builded with the use of "ansible-builder") but Docker@2 doesn't recognize the local image repository name, It seems Docker@2 adds "***" in front of the repository, but the image repository is without the *** ...

When i build the image through Docker@2 it automatically adds the three stars (***) to the repository name... and it pushes the image also to ACR

(Error) Task:
```yaml
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: myacr
    repository: awx/custom-ee
    command: push
    tags: latest
```

Error message:
```
The push refers to repository [***/awx/custom-ee]
An image does not exist locally with the tag: ***/awx/custom-ee
##[error]An image does not exist locally with the tag: ***/awx/custom-ee
##[error]The process '/usr/bin/docker' failed with exit code 1
```

with a CmdLine task before pushing it, i can see the docker image exists with the appropriate repo name..

```
REPOSITORY                        TAG                  IMAGE ID       CREATED         SIZE
awx/custom-ee                     latest               5223b12351fa   1 second ago    1.97GB
```
