### ISSUE TITLE
Unhandled: Not found mavenPOMFile: /home/vsts/work/1/s/pom.xml

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/azure-pipelines-tasks#16534]
## Required Information

**Question, Bug, or Feature?** Bug
**Enter Task Name**: Maven

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/task.json

## Environment
- Server - **Azure Pipelines**
- Agent - **Hosted**

## Issue Description

Some Maven goals do not require a `pom.xml`. For example, some script task may want to run a `java` command on a specific JAR file, which can be downloaded from a Maven repository.

> Downloads a single artifact transitively from the specified remote repositories.

https://maven.apache.org/plugins-archives/maven-dependency-plugin-2.6/get-mojo.html

`azure-pipelines.yml`:
``` yaml
variables:
  MAVEN_CACHE: '$(Pipeline.Workspace)/.m2/repository'
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE)'
  PLANTUML_VERSION: '1.2022.6'

steps:
- task: Maven@3
  displayName: 'PlantUML Installer'
  inputs:
    goals: 'dependency:get'
    options: |
      -Dartifact='net.sourceforge.plantuml:plantuml:$(PLANTUML_VERSION)'
      -Ddest='$(Build.SourcesDirectory)'
      -DremoteRepositories='https://repo1.maven.org/maven2'
      -Dtransitive=false
    mavenOptions: '$(MAVEN_OPTS)'
- script: java -jar plantuml-$(PLANTUML_VERSION).jar *.puml
  displayName: 'PlantUML Export'
```

### Task logs

```
==============================================================================
Task         : Maven
Description  : Build, test, and deploy with Apache Maven
Version      : 3.206.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
==============================================================================
##[error]Unhandled: Not found mavenPOMFile: /home/vsts/work/1/s/pom.xml
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by AnthonyMastrean** [comment]
I'm familiar with Maven and POMs, but I have a use case where PlantUML says to call it from the command-line as such.

> The most basic way to run it is:
>
> ```
> java -jar plantuml.jar file1 file2 file3
> ```

https://plantuml.com/command-line

And recommends one way to retrieve the JAR is from the Maven repository.

> You can [use PlantUML directly with Maven integration.](https://oss.sonatype.org/content/repositories/releases/net/sourceforge/plantuml/plantuml/)

https://plantuml.com/download

I don't think it's fair to say it's "not recommended" since there are Maven goals that explicitly work without a POM.

https://maven.apache.org/plugins-archives/maven-dependency-plugin-2.6/get-mojo.html

You're recommending to download the file directly from the website or the GitHub Releases, that's fine, but can you recommend a task? I see the cURL task is for upload only.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/curl-upload-files?view=azure-devops

**Comment by rammaddela** [comment]
this is my pipleline.yaml,    **mavenPomFile: '$(system.defaultWorkingDirectory)/scim-web/pom.xml'**

Starting: Maven
==============================================================================
Task         : Maven
Description  : Build, test, and deploy with Apache Maven
Version      : 3.211.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
==============================================================================
**##[error]Unhandled: Not found mavenPOMFile: /home/vsts/work/1/s/scim-web/pom.xml
Finishing: Maven**

**my project sructure:  scim-parent/scim-web/pom.xml , why its prefixing /home/vsts/work/1/s/**

1 error(s), 1 warning(s)
--
  | Unhandled: Not found mavenPOMFile:   /home/vsts/work/1/s/scim-web/pom.xml




</body>

</html>


# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(system.defaultWorkingDirectory)
- task: Maven@3
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/scim-web/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package

**Comment by rammaddela** [comment]
why its  prefixing /home/vsts/work/1?

**Comment by DmitriiBobreshev** [comment]
Hi @rammaddela,  /home/vsts/work/1s is the default prefix for ms-hosted agents, [$(system.defaultWorkingDirectory)](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) just defaults predefined variable, in your case, if pom.xml file exists inside you repo and your "scim-web" inside root you can use task without $(system.defaultWorkingDirectory):
```
task: Maven@3
inputs:
  mavenPomFile: 'scim-web/pom.xml'
  mavenOptions: '-Xmx3072m'
  javaHomeOption: 'JDKVersion'
  jdkVersionOption: '1.8'
  jdkArchitectureOption: 'x64'
  publishJUnitResults: true
  testResultsFiles: '**/surefire-reports/TEST-*.xml'
  goals: 'package
```
