### ISSUE TITLE
PublishSymbols@2 task does not log verbose output

### ISSUE THREAD

**Issue by daniel-ju** [microsoft/azure-pipelines-tasks#16613]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishSymbols

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      Internal. Happy to provide privately over email.

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: 
      Azure Pipelines

## Issue Description

With the following task configuration, the PublishSymbols task does not log verbose output with the `DetailedLog` arugment like the MSDN docs say (even when explicitly set to true):

```
    - task: PublishSymbols@2
      displayName: Index sources
      inputs:
        SearchPattern: $(binFolder)\**\*.pdb
        PublishSymbols: false
        DetailedLog: true
        TreatNotIndexedAsWarning: true
```

In particular, the [task source code](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishSymbolsV2/IndexHelpers/SourceFileFunctions.ps1#L69-L77) implies that one of the following messages should be logged in the task log output whenever the sources are not indexed:
`Write-Verbose "One or more source files not under sources root directory: $SourcesRootPath"`
`Write-Verbose "One or more source files not found."`

### Task logs
Output example:

```
##[warning]Unable to index one or more source files for symbols file 'D:\a\1\s\bin\x64\Release\xx.pdb
"D:\a\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.203.0\pdbstr.exe" -w -p:"D:\a\1\s\bin\x64\Release\xx.pdb" -i:"C:\Users\VssAdministrator\AppData\Local\Temp\tmpF70.tmp" -s:srcsrv
```
