### ISSUE TITLE
MavenAuthenticate task should support adding mirrorOf

### ISSUE THREAD

**Issue by johnoliver** [microsoft/azure-pipelines-tasks#16675]
*Type*: Feature

**Enter Task Name**: MavenAuthenticate 

## Issue Description

It is a common when trying to use a single repository in maven to add a mirrorOf section to the settings.xml file, as described in [using mirrors](https://maven.apache.org/guides/mini/guide-mirror-settings.html). Currently the MavenAuthenticate  does not support setting this. Ideally the user would be able to configure this and add it to the settings.xml such as:
```
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'my-feed'
      mirrorOf: 'repo1,repo2'
```

which would then produce:

```  
  <mirrors>
    <mirror>
      <id>my-feed</id>
      <name>my-feed</name>
      <url>...</url>
      <mirrorOf>repo1,repo2</mirrorOf>
    </mirror>
  </mirrors>
```
