### ISSUE TITLE
PublishBuildArtifacts fails silently on `+`, `%`, `{`, or `}` in ArtifactName

### ISSUE THREAD

**Issue by Codym48** [microsoft/azure-pipelines-tasks#16697]
## Required Information

**Question, Bug, or Feature?**  Bug

**Enter Task Name**: PublishBuildArtifactsV1

## Environment
- Server - TFS on-premises
    - Version Azure DevOps Server 2020 Update 1.1
- Agent - Private
    - Red Hat Enterprise Linux Workstation release 7.9 (Maipo)
    - Agent.Version 2.202.0

### Setup
I'm using the PublishBuildArtifactsV1 task to publish downloadable test logs as build artifacts to work around https://github.com/microsoft/azure-pipelines-tasks/issues/16696. I have several jobs within a multi-configuration pipeline that are similar but use different cmake commands. Rather than maintain and remember a mapping between `cmake ../command -Dwith=special+characters` and a mangled version of that name, I'm using the job name directly as the artifact name. In the excerpts below, each .yaml includes the template below it.

```yaml
jobs:
- template: ./CMakeBuildWorkflowOneJob.yaml
  parameters:
    jobName: SimpleDescriptiveString1
    cmakeArguments: ../command -Dwith=special+characters
- template: ./CMakeBuildWorkflowOneJob.yaml
  parameters:
    jobName: SimpleDescriptiveString2
    cmakeArguments: ../different/command -Dwith=different_special+characters
```

```yaml
jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.cmakeArguments }}
  steps:
  - template: ./CmakeBuildWorkflowSteps.yaml
```

```yaml
steps:
  ...
  - template: ./PublishTestResults.yaml
    parameters:
      publishName: '$(Agent.JobName)'
```

```yaml
steps:
  ...
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: ${{ parameters.publishName }}"
    inputs:
      artifactName: '${{ parameters.publishName }} logs'
````

### The Good
`ArtifactName`s that contain alphanumeric characters, spaces, and some special characters (`-`, `=`, `(`, and `)`) successfully upload the artifacts.

### The Bad
`ArtifactName`s that contain the special character `+` silently fail, passing the Publish Build Artifacts task step, generating a expandable file tree in the **Artifacts** tab of the pipeline summary, but then providing a "Server Error 404 - File or directory not found. The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable." error message when I try to download the artifacts.

![image](https://user-images.githubusercontent.com/34431661/183250817-8ac2fb76-b9ec-4a56-9be3-f213ea51f8d2.png)

### Requested Fix
1. Support `+` special character in the `artifactName` argument of PublishBuildArtifacts
or
2. Fail the pipeline task if special characters are detected in `artifactName` that would make the artifacts undownloadable
or
3. Provide a way to remove special characters like `+` from predefined variables like `${Agent.JobName}`?

### Task logs

I can't provide logs from my company machine, but should be able to recreate this with a public project if that would help.
