### ISSUE TITLE
Kubernetes@1's "arguments" argument doesn't follow Bash's word splitting rules but has custom word splitting rules

### ISSUE THREAD

**Issue by schra** [microsoft/azure-pipelines-tasks#16704]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes  

## Issue Description

I expect that the `arguments` parameter of `Kubernetes@1` is expanded exactly like it is expanded on my command like. That is, that is expanded according to Bash's word splitting rules (see https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html).

For example:

```
- task: Kubernetes@1
  displayName: foo
  inputs:
    ....
    command: patch
    arguments: hpa my-hpa --patch='{"spec": {"maxReplicas": 123}}'
```

I would expect that `arguments` is parsed like it is parsed on my command line:

* argv[1] = `patch`
* argv[2] = `hpa`
* argv[3] = `my-hpa`
* argv[4] = `--patch={"spec": {"maxReplicas": 123}}`

However, `arguments` is in fact parsed like this:

* argv[1] = `patch`
* argv[2] = `hpa`
* argv[3] = `my-hpa`
* argv[4] = `--patch='{spec:`
* argv[5] = `{maxReplicas:`
* argv[6] = `123}}'`

Note how the arguments are expanded "wrongly" in two ways:

* It does word splitting on whitespace, even though the whitespace is within quotes `' ... '`

* It expands quotes - note how the `"` quotes disappear.

Also maybe consider supporting a json list for the `arguments`, so that we can circumvent the shell expansion rules entirely?

### Task logs

Here is how I found out how `arguments` is expanded:

* I used:

  ```
  - task: Kubernetes@1
    displayName: foo
    inputs:
      ....
      command: patch
    arguments: hpa my-hpa --patch='{"spec": {"maxReplicas": 123}}'
  ```

  and in the pipeline output I can see

  ```
  ##[error]F0809 09:26:19.445328     593 helpers.go:116] error: unable to parse "'{spec:": yaml: found unexpected end of stream
  ```

  That is, the whitespace got expanded, even though they are within quotes.

* I used (now without whitespace in the json string):

  ```
  - task: Kubernetes@1
    displayName: foo
    inputs:
      ....
      command: patch
      arguments: hpa my-hpa --patch='{"spec":{"maxReplicas":123}}'
  ```

  and in the pipeline output I can see

  ```
  2022-08-09T09:44:25.4596448Z [command]/mnt/azp/_work/_tool/kubectl/1.22.6/x64/kubectl patch -n api hpa nkw-service-hpa-1-in --patch='{spec:{maxReplicas:123}}' -v=9 -o json
  ```

  and

  ```
  2022-08-09T09:44:26.0242642Z I0809 09:44:26.022889     552 request.go:1181] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal string into Go value of type map[string]interface {}","reason":"BadRequest","code":400}
  ```

  That is, the `"` got removed from `arguments`.
