### ISSUE TITLE
AzureFunctionApp task - Resource doesn't exist error

### ISSUE THREAD

**Issue by kamikaz8** [microsoft/azure-pipelines-tasks#16729]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted - unsure what is meant by "agent queue name"
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I have an AzureFunctionApp task that is throwing an error of : ##[error]Error: Resource '<fxn-app-name> ' doesn't exist. Resource should exist before deployment.  The resource certainly does exist as it is created in a previous Job step.  One of the issues here is that it appears to be intermittent.  After several runs, it has run through without issue once or twice.  Oddly, using 'enable system diagnostics' appears to make it run without issue (so far 3/3).  It makes me wonder if there is some sort of race condition occurring in which the extra logging slows the deployment down enough for it to work consistently.  I'm not sure how to troubleshoot further, any guidance would be appreciated.

### Task logs

See below/attached.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[logs_353.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9329158/logs_353.zip) - from a failed run without diagnostics enabled

[logs_349.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9329164/logs_349.zip) - from a working run without diagnostics enabled

[logs_348.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9329169/logs_348.zip) - from a working run with diagnostics enabled.

**Comment by kamikaz8** [comment]
Have now encountered a failure with diagnostics turned on.  Attaching here.
[logs_356.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9329312/logs_356.zip)

**Comment by pinakighatak** [comment]
Team, having this issue in AzDo, I have solved it in the following way.
```yaml
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Provision Azure Function App from Bicep
  name: FunctionDeployStep
  inputs:
    deploymentScope: "Resource Group"
    subscriptionId: "$(AZURE_SUBSCRIPTION_ID)"
    location: "$(GEOLOCATION)"
    azureResourceManagerConnection: "$(AZURE_CREDENTIALS)"
    action: "Create Or Update Resource Group"
    resourceGroupName: "${{parameters.AzureResourceGroup}}"
    templateLocation: "Linked artifact"
    csmFile: "$(Pipeline.Workspace)/drop/AzureFunctions/bicep/azurefunction.bicep"
    overrideParameters: "-prefix $(PREFIX)"
    deploymentMode: "Incremental"
    deploymentName: $(DEPLOYMENT_NAME)
    deploymentOutputs: deployOutputs

- task: PowerShell@2
  name: outputVars
  displayName: "Set Output Variables"
  inputs:
    targetType: inline
    pwsh: true
    script: |
      $armOutputObj = '$(deployOutputs)' | ConvertFrom-Json
      $armOutputObj.PSObject.Properties | ForEach-Object {
        $keyname = $_.Name
        $value = $_.Value.value
        Write-Host "##vso[task.setvariable variable=$keyName;isOutput=true]$value"
      }

- task: AzureFunctionApp@1
  displayName: "Deploy Azure Functions Code"
  # enabled: false # disable this task for now
  inputs:
    azureSubscription: "$(AZURE_CREDENTIALS)"
    appType: functionApp
    appName: $(outputVars.functionName)
    resourceGroupName: "${{parameters.AzureResourceGroup}}"
    package: "$(Pipeline.Workspace)/drop/**/*.zip"
```
So my findings are:
although the line `deploymentOutputs: deployOutputs` is supposed to put all the output variables on the environment, it does so with some errors sometimes including the double quotes or spaces. So the remedy task of `PowerShell@2` is required to get the correct string.

Then your `AzureFunctionApp@1` task works, since it needs the `appName` exactly as it is provisioned. So the flaw here is not in the `AzureFunction@1` task but it is in the `AzureResourceManagerTemplateDeployment@3` task which I believe is due time for an update
