### ISSUE TITLE
AzureFunctionApp fails when attempting to change FUNCTIONS_EXTENSION_VERSION and linuxFxVersion

### ISSUE THREAD

**Issue by jenko1080** [microsoft/azure-pipelines-tasks#16732]
## Required Information

**Type**: Bug
**Task Name**: AzureFunctionApp

## Environment
**Server**: Azure Pipelines
**Agent**: Hosted

## Issue Description

When attempting to change both `FUNCTIONS_EXTENSION_VERSION` and `linuxFxVersion` on release, a failure appears to be caused due to the request order.

In a failure the process attempts to perform `Syncing triggers for function app` and gets the following error:
```
Syncing triggers for function app
##[error]Error: Failed to sync triggers for function app '____'. Error: BadRequest - Encountered an error (ServiceUnavailable) from host runtime. (CODE: 400)
```

When `FUNCTIONS_EXTENSION_VERSION` is removed from `appSettings` the process succeeds, leaving the app with the incorrect extension version:
```
Syncing triggers for function app
Sync triggers for function app completed successfully
Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"PYTHON|3.8"}
Updated App Service Configuration settings.
```

### Task logs

Partial pipeline to reproduce...

- Assumes clean Function App exists in consumption plan
- Example initial state
   - `FUNCTIONS_WORKER_RUNTIME: python`
   - `FUNCTIONS_EXTENSION_VERSION: ~3`
   - `linuxFxVersion: PYTHON|3.6`

```yml
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: __serviceConnection__
    appType: "functionAppLinux"
    appName: "testfunction"
    package: "testfn.zip"
    runtimeStack: "PYTHON|3.8"
    configurationStrings: "-linuxFxVersion PYTHON|3.8"
    appSettings: >-
      -FUNCTIONS_WORKER_RUNTIME: python
      -FUNCTIONS_EXTENSION_VERSION: ~4
```

**Output**
```
Starting: AzureFunctionApp
==============================================================================
Task         : Azure Functions
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 1.206.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
Got service connection details for Azure App Service:'___'
Trying to update App Service Application settings. Data: {"FUNCTIONS_EXTENSION_VERSION":"~4","FUNCTIONS_WORKER_RUNTIME":"python","WEBSITE_RUN_FROM_PACKAGE":"[https://____.blob.core.windows.net/azure-pipelines-deploy/package_XXX.zip?***"}]
Updated App Service Application settings.
Updated WEBSITE_RUN_FROM_PACKAGE Application setting to https://____.blob.core.windows.net/azure-pipelines-deploy/package_XXX.zip?***
Syncing triggers for function app
##[error]Error: Failed to sync triggers for function app '____'. Error: BadRequest - Encountered an error (ServiceUnavailable) from host runtime. (CODE: 400)
Successfully added release annotation to the Application Insight : XXX
App Service Application URL: http://____.azurewebsites.net/
Finishing: AzureFunctionApp
```
