### ISSUE TITLE
BashV3 task incorrectly sends SIGTERM to child process instead of SIGINT

### ISSUE THREAD

**Issue by DaRosenberg** [microsoft/azure-pipelines-tasks#16731]
## Required Information

**Type**: Bug
**Task Name**: BashV3  

## Environment

**Server:** Azure Pipelines
**Agent:** Hosted

## Issue Description

`BashV3` contains code to listen for `SIGINT` from the agent and forward the signal to the child process (via the `ToolRunner.killChildProcess()` method). This logic was initially introduced in https://github.com/microsoft/azure-pipelines-tasks/pull/13573.

The implementation does not work as expected, for two reasons:

1. Because of https://github.com/microsoft/azure-pipelines-task-lib/issues/858 the POSIX signals get mixed up; the agent sends `SIGINT` to the task, but the task ends up sending `SIGTERM` to the child process.

2. The task listens *only* for `SIGINT` but it should also listen for `SIGTERM` because [as stated here](https://github.com/Microsoft/azure-pipelines-agent/issues/1757#issuecomment-412156123) the agent apparently sends both, at different times to indicate different levels of urgency.

A more correct implementation would be:

- Add a parameter in upstream `ToolRunner.killChildProcess()` to allow specifying the signal to send
- Listen for `SIGINT` and call `bash.killChildProcess("SIGINT");`
- Listen for `SIGTERM` and call `bash.killChildProcess("SIGTERM");`

Small changes are necessary in both libraries to address this, so I will create issues and PRs in both repos and update both with links to cross-reference.

### Task logs

Here's a simple repro pipeline:

```yaml
pool:
  vmImage: ubuntu-latest

trigger: none

jobs:

  - job: signals
    displayName: Test POSIX signals
    # Have the job cancel after 1 minute:
    timeoutInMinutes: 1
    steps:
      - checkout: none
      - bash: |
          trap "echo 'SIGHUP'" SIGHUP
          trap "echo 'SIGINT'" SIGINT
          trap "echo 'SIGQUIT'" SIGQUIT
          trap "echo 'SIGTERM'" SIGTERM
          trap "echo 'EXIT'" EXIT
          while true; do sleep 1; echo .; done
        displayName: Wait for signals
```

Running it will show the following:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/3889090/184516678-236b0d44-4e93-4c3a-94f3-e6cd9d378c10.png">

As show in the screenshot, the script task receives `SIGTERM` and nothing else.
