### ISSUE TITLE
Task JavaToolInstaller creating jdk folder incorrectly. 

### ISSUE THREAD

**Issue by kaibocai** [microsoft/azure-pipelines-tasks#16744]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: JavaToolInstaller

**Enter Task Name**: JavaToolInstaller

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am using JavaToolInstaller documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops#examples) with below configuration

```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: 8
    jdkArchitectureOption: 'x64'
    jdkSourceOption: LocalDirectory
    jdkFile: "$(downloadPath)/$(JAVA_VERSION).tar.gz"
    jdkDestinationDirectory: "$(downloadPath)/externals"
    cleanDestinationDirectory: true
```

where `$(downloadPath) =="/mnt/vss/_work/1/s/"`

The output of this tasks indicate it's creating wrong path for install jdk. 
![image](https://user-images.githubusercontent.com/89094811/184963934-ab44b3e2-2e51-4af2-b7e7-3f2d12dce729.png)
The JAVA_HOME set after installation also indicate same thing
![image](https://user-images.githubusercontent.com/89094811/184964020-a64153ae-bd61-4a42-874a-842d7a07f590.png)
I expect it to be `/mnt/vss/_work/1/s/externals/jdk8u322-b06`
Want to confirm if this is expected behavior? Thanks. 
### Task logs
[JavaToolInstaller.log](https://github.com/microsoft/azure-pipelines-tasks/files/9353873/JavaToolInstaller.log)

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
