### ISSUE TITLE
PublishTestResults@2 fails with: Failed find: ENOENT: no such file or directory, lstat '/System/Library/Frameworks/iTunesLibrary.framework/Versions/Versions'

### ISSUE THREAD

**Issue by rolfbjarne** [microsoft/azure-pipelines-tasks#16786]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults@2  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6592423&view=logs&j=d41f5e19-24ee-5ef2-2214-c17739a58f28&t=4c181720-c9a6-5955-936c-a23f0a866e99

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Queue: VSEng-Xamarin-RedmondMacBuildPool-iOS-Untrusted
Agent: XAMBOT-1183.Monterey

OS:

```
Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: XAMBOT-1183
      User Name: builder (builder)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 38 days 9:19

Hardware:

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1731.120.10.0.0 (iBridge: 19.16.15071.0.0,0)
      OS Loader Version: 540.120.3~6
      Activation Lock Status: Disabled
```

## Issue Description

Yaml:

```yml
- task: PublishTestResults@2
  displayName: 'Publish NUnit Device Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/vsts-*.xml'
    failTaskOnFailedTests: true
  continueOnError: true
  condition: succeededOrFailed()
```

### Task logs

```
2022-08-23T02:39:07.6891260Z ##[section]Starting: Publish NUnit Device Test Results
2022-08-23T02:39:07.6910900Z ==============================================================================
2022-08-23T02:39:07.6911830Z Task         : Publish Test Results
2022-08-23T02:39:07.6912450Z Description  : Publish test results to Azure Pipelines
2022-08-23T02:39:07.6913040Z Version      : 2.203.0
2022-08-23T02:39:07.6913900Z Author       : Microsoft Corporation
2022-08-23T02:39:07.6914790Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
2022-08-23T02:39:07.6915620Z ==============================================================================
2022-08-23T02:39:41.3785380Z ##[error]Error: Failed find: ENOENT: no such file or directory, lstat '/System/Library/Frameworks/iTunesLibrary.framework/Versions/Versions'
2022-08-23T02:39:41.4213950Z ##[section]Finishing: Publish NUnit Device Test Results
```

**Comment by olstakh** [comment]
Can this be reopened? Having the same issue after adding `failTaskOnFailedTests: true`.

Step:
```
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Agent.TempDirectory)'
    failTaskOnFailedTests: true
```

Error logs:

```
Starting: PublishTestResults
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.248.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
##[error]Error: Failed find: ENOENT: no such file or directory, scandir 'D:\a\_work\_temp\.azclitask\telemetry\20250404043558473'
Finishing: PublishTestResults
```

This happens occasionally and wasn't happening without `failTaskOnFailedTests: true`, AFAIK
