### ISSUE TITLE
[PowerShellOnTargetMachines@3] Access is denied error when running on self-hosted agent.

### ISSUE THREAD

**Issue by yury-romanov** [microsoft/azure-pipelines-tasks#16792]
## Required Information
*Type*: Bug
**Task Name**: PowerShellOnTargetMachines@3

## Environment
- Server - Azure Pipelines
    - Account name: [Redacted. Send me PM for the info]
    - Team project name: [Redacted. Send me PM for the info]
    - Build number: #20220823.8

- Agent - Private: 
    
    - OS: Windows Server 2022 Datacenter Azure Edition

    - Agent version: 2.206.1

## Issue Description

`PowerShellOnTargetMachines@3` task throws access is denied error when running on Self-hosted agent, but doesn't throw that error when running on Microsoft-hosted agent.
This YAML works:
```
trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- checkout: none

- task: PowerShellOnTargetMachines@3
  displayName: 'PowerShell on Target VM'
  inputs:
    Machines: '$(VM-PublicIP)'
    UserName: '$(VM-UserName)'
    UserPassword: '$(VM-Password)'
    InlineScript: |
      Write-Host Hello-World
```

However when changing:
```
vmImage: 'windows-2019'
```
to:
```
name: 'DevOps-Agent2-VM'
```

the task fails with access is denied error.
![2022-08-23_17-48-17](https://user-images.githubusercontent.com/48393833/186175622-2fc84332-b22e-418c-b451-44539d5d8753.png)

This YAML doesn't work:
```
trigger: none

pool:
  name: 'DevOps-Agent2-VM'

steps:
- checkout: none

- task: PowerShellOnTargetMachines@3
  displayName: 'PowerShell on Target VM'
  inputs:
    Machines: '$(VM-PublicIP)'
    UserName: '$(VM-UserName)'
    UserPassword: '$(VM-Password)'
    InlineScript: |
      Write-Host Hello World
```
### Error logs
```
Starting: PowerShell on Target VM
==============================================================================
Task         : PowerShell on target machines
Description  : Execute PowerShell scripts on remote machines using PSSession and Invoke-Command for remoting
Version      : 3.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines
==============================================================================
##[error]Unable to create pssession. Error: 'Connecting to remote server [REDACTED IP] failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.'
##[error]PSSession could not be created for Machine:'[REDACTED IP]:5986'
Finishing: PowerShell on Target VM
```
