### ISSUE TITLE
SqlAzureDacpacDeployment@1 No files were found to deploy with search pattern

### ISSUE THREAD

**Issue by thatham** [microsoft/azure-pipelines-tasks#16794]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1  

## Issue Description

SqlAzureDacpacDeployment@1 ##[error]No files were found to deploy with search pattern, below is our implementation

```
- task: SqlAzureDacpacDeployment@1
     inputs:
       azureSubscription: '<OUR_AZURERM_SERVICE_CONNECTION_USING_SAME_SERVICE_PRINCIPAL>'
       AuthenticationType: 'servicePrincipal'
       ServerName: $(server_name)
       DatabaseName: $(database_name)
       deployType: 'DacpacTask'
       DeploymentAction: 'Publish'
       DacpacFile: '$(System.ArtifactsDirectory)/drop/<USER_DEFINED_FILE_NAME>.dacpac'
       AdditionalArguments: '/p:AllowIncompatiblePlatform=true'
       IpDetectionMethod: 'AutoDetect'
```
## Troubleshooting
We're using ServicePrincipal authentication type provided with Access Token to publish our changes to Azure SQL server using dacpac file.

According to my Troubleshooting, the code flows thru the following

1. First, DeploySqlAzure.ps1 authenticationType check @ line no 100
```
elseif ($authenticationType -eq "servicePrincipal") {
```
2. Then, DeploySqlAzure.ps1 switch @ line no 139
```
switch ($taskNameSelector) {
...
"DacpacTask" {
            switch ($deploymentAction) {
                "Publish" {
                    Write-Verbose "Executing 'Publish' action."
                    Publish-Dacpac -serverName $serverName -authenticationType $authenticationType -databaseName $databaseName -sqlUsername $sqlUsername -sqlPassword $sqlPassword -dacpacFile $dacpacFile -publishProfile $publishProfile -connectionString $connectionString -sqlpackageAdditionalArguments $sqlpackageAdditionalArguments -token $accessToken
                }
```
3. Then, SqlAzureActions.ps1 to the function "Publish-Dacpac" @ line no 173

```
function Publish-Dacpac {
...
#Ensure that a single package (.dacpac) file is found
    $dacpacFilePath = Find-SqlFiles -filePathPattern $dacpacFile -verboseMessage (Get-VstsLocString -Key "SAD_DacpacFilePath") -throwIfMultipleFilesOrNoFilePresent
```
4. Then, it's looking for some sql files using "Find-SqlFiles" function and throws below error from the function "ThrowIfMultipleFilesOrNoFilePresent"
```
function Find-SqlFiles {
....
$filePath = Find-VstsFiles LegacyPattern $filePathPattern

    if ($throwIfMultipleFilesOrNoFilePresent) {
        ThrowIfMultipleFilesOrNoFilePresent -files $filePath -pattern $filePathPattern
    }
```
### Note:
If we're using connectionstring authentication type provided with username and password, then there's no error. The task completed successfully. The below error only happens when using DacPac Task Type.

### Error logs

Temporary inline SQL file: C:\Users\teamcityagent\AppData\Local\Temp\tmp64E3.tmp
Invoke-Sqlcmd -AccessToken "**********" -ServerInstance "**********" -Database "**********"  -Inputfile "C:\Users\teamcityagent\AppData\Local\Temp\tmpXXXX.tmp" 

##[error]No files were found to deploy with search pattern D:\<MS_SELF_HOSTED_WIN_AGENT>\_work\120\a\drop\<USER_DEFINED_FILE_NAME>.dacpac Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

Finishing: SqlAzureDacpacDeployment
