### ISSUE TITLE
How to override NDK_ROOT when using MSBuild task

### ISSUE THREAD

**Issue by victorjonsson** [microsoft/azure-pipelines-tasks#16823]
**Question:**  
How to override NDK_ROOT when using MSBuild task

**Enter Task Name**: MSBuild  

## Environment
- Azure Pipelines
- Hosted Agent (pool: windows-2022)
    
## Issue Description
I'm trying to build a vcxproject with the following yaml configuration

```
- task: MSBuild@1
  displayName: 'Project build - ARM'
  env:
    ANDROID_HOME: $(androidSdkPath)
    NDK_ROOT: $(ndkPath)
    ANDROID_NDK_HOME: $(ndkPath)
  inputs:
    solution: 'theproject\theproject.vcxproj'
    msbuildArgs: '/p:AndroidNdkDirectory="$(ndkPath)"'
    platform: 'ARM'
    configuration: 'BuildOfficial'
    logFileVerbosity: detailed
```

When the task runs I can see that it doesn't use the NDK that I'm trying to point out in above configuration

```
...
2022-08-31T08:44:27.9465479Z SetBuildDefaultEnvironmentVariables:
2022-08-31T08:44:27.9465961Z   ANDROID_HOME=C:\\Microsoft\AndroidSDK\25
2022-08-31T08:44:27.9466390Z   ANT_HOME=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Apps\apache-ant-1.9.3
2022-08-31T08:44:27.9468000Z   JAVA_HOME=C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08
2022-08-31T08:44:27.9469686Z   NDK_ROOT=C:\\Microsoft\AndroidNDK\android-ndk-r21e
...
...
ClCompile:
2022-08-31T08:44:28.1563109Z   C:\\Microsoft\AndroidNDK\android-ndk-r21e\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe -c  ...
```

How am I supposed to controll which NDK to be used by MSBuild? I don't see in the logs that my `msbuildArgs` are passed on to MSBuild neither.

**Comment by DmitriiBobreshev** [comment]
Hello @victorjonsson, thank you for the request. 

If I understood you correctly, you want to set env variable NDK_ROOT, have you tried define it [this way](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#variable-naming-restrictions), because it seems like MSBuild tasks call [Invoke-BuildTools](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MSBuildV1/MSBuild.ps1#L63) which have another scope than your env block, in your case you can do something like this: 

```
 - bash: |
    echo "##vso[task.setvariable variable=NDK_ROOT]$(ndkPath)"
    echo "##vso[task.setvariable variable=ANDROID_NDK_HOME]$(ndkPath)"
    echo "##vso[task.setvariable variable=ANDROID_HOME]$(androidSdkPath)"
- task: MSBuild@1
  displayName: 'Project build - ARM'
  inputs:
    solution: 'theproject\theproject.vcxproj'
    msbuildArgs: '/p:AndroidNdkDirectory="$(ndkPath)"'
    platform: 'ARM'
    configuration: 'BuildOfficial'
    logFileVerbosity: detailed
```
