### ISSUE TITLE
How do I correctly pass arguments with AzureCLI Task?

### ISSUE THREAD

**Issue by opencloudcode** [microsoft/azure-pipelines-tasks#16845]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: How do I correctly pass arguments with AzureCLI@2 Task

**Enter Task Name**: AzureCLI@2 Task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

The documentation states the below is how you pass arguments:
```
- task: AzureCLI@2
  inputs:
    azureSubscription: <Azure_Resource_Manager_Service_Connection>
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    arguments: '$(AZURE_STORAGE_ACCOUNT) $(AZURE_STORAGE_KEY)'
    scriptPath: './scripts/publish.ps1'

```
When I do something similar the arugments are not getting passed:
```

              - task: AzureCLI@2
                displayName: "Running ${{parameters.ScriptName}} on Machines"
                inputs:
                  azureSubscription: DeploymentMI
                  scriptType: 'ps'
                  scriptLocation: 'scriptPath'
                  scriptPath: '$(Pipeline.Workspace)/BPC-Operations/Run-Command.ps1'
                  Arguemnts: "$(SubNames)"
```

Here is the Ps file that I am running:

```
[CmdletBinding()]
param (
    [Parameter()]
    [string]
    $SubNames
)

Write-Output "hi: $SubNames"
```

The output:

`hi: `

### More Info

With that is there a better way to pass arugments like how we do it for Azure PS task? E.g. 

ScriptArguments: "-subname shahel -arg2 github"

**Comment by clintgrove** [comment]
There was no answer to this question. This should not be a closed issue

**Comment by thwr** [comment]
I think I just ran into something very similar, if not the same issue.

Let's assume something like this:

```yaml
      - task: AzureKeyVault@2
        displayName: "Fetch KeyVault secrets"
        inputs:
          azureSubscription: 'myArmServiceConnection'
          KeyVaultName: 'myKeyVault'
          SecretsFilter: 'some-secret-a,some-secret-b'
          RunAsPreJob: false
  
      - task: AzureCLI@2
        displayName: 'Run PowerShell script'
        inputs:
          azureSubscription: 'myArmServiceConnection'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          scriptPath: 'pipelines/somepipeline/somepipeline.ps1'
          arguments: '-Transfer -BlobContainer myblobcontainer -ResourceGroup myrg -Stage ${{ variables.stage_long}} -SomeParam $(some-secret-a) -SomeOtherParam $(some-secret-b)'
  ```
  While `${{ variables.stage_long}}` gets replaced with the actual value just fine (that's coming from a yaml config file at stage level), my pipeline failes with 
  
`The term 'some-secret-a' is not recognized as a name of a cmdlet, function, script file, or executable program.`

I think PowerShell is trying to interpret something here (e.g. executing `$(some-secret-a)`)

For instance, I'm using KeyVault secrets, AzureKeyVault@2 and so in in a couple other pipelines without any problems. This is very specific to using $(some-secret-a) as argument on AzureCLI@2
