### ISSUE TITLE
Gradle task with Cobertura code coverage fails after upgrade to Gradle 7

### ISSUE THREAD

**Issue by jan-dolejsi** [microsoft/azure-pipelines-tasks#16859]
**Bug**  
*Type*: build task fails

**Enter Task Name**: Gradle,v2

## Environment
- Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Gradle+Cobertura:
https://dev.azure.com/slb-swt/ai-planning/_build/results?buildId=4044085&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: hosted

## Issue Description

Yaml pipeline:

```yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'Cobertura'
      codeCoverageClassFilesDirectories: 'build/classes/java/main/'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
```

Gradle.properties

```
gradleVersion=7.4.2
```

Gradle-wrapper.properties

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

### Task logs

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vsts/work/1/s/build.gradle' line: 70

* What went wrong:
A problem occurred evaluating root project 'tabu-search'.
> Failed to apply plugin 'net.saliman.cobertura'.
   > Could not create an instance of type net.saliman.gradle.plugin.cobertura.CoberturaExtension.
      > Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
```
