### ISSUE TITLE
Gradle task with Jacoco code coverage fails after upgrade to Gradle 7

### ISSUE THREAD

**Issue by jan-dolejsi** [microsoft/azure-pipelines-tasks#16860]
**Bug**  
*Type*: build task fails

**Enter Task Name**: Gradle,v2

## Environment
- Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Gradle+Jacoco:
https://dev.azure.com/slb-swt/ai-planning/_build/results?buildId=4043438&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ea098990-53e4-52aa-5a84-5ead7c5f17f2&l=167

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: hosted

## Issue Description

Yaml pipeline:

```yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilesDirectories: 'build/classes/java/main/'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
```

Gradle.properties

```
gradleVersion=7.4.2
```

Gradle-wrapper.properties

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

### Task logs

```
> Task :processTestResources
> Task :testClasses
> Task :test
> Task :jacocoTestReport FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vsts/work/1/s/build.gradle' line: 70

* What went wrong:
Execution failed for task ':jacocoTestReport'.
```

**Comment by vmapetr** [comment]
Hi @jan-dolejsi
Thank you for your report,
We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by idrisscharai** [comment]
Any updates on this issue please?

**Comment by kaito-ms** [comment]
Any updates on this issue please?

This problem is caused by the Gradle task writing the following to the build.gradle file

// build.gradle
classDirectories.setFrom fileTree(dir: "build/classes/java/main/").exclude(jacocoExcludes).include(jacocoIncludes)

In Gradle 6.x and later, classDirectories is read-only.
[JacocoReport - Gradle DSL Version 7.6.1](https://docs.gradle.org/7.6.1/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html#org.gradle.testing.jacoco.tasks.JacocoReport:classDirectories)

In Gradle 5.x, it was possible to write values to classDirectories, so the problem did not occur.
[JacocoReport - Gradle DSL Version 5.6.4](https://docs.gradle.org/5.6.4/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html#org.gradle.testing.jacoco.tasks.JacocoReport:classDirectories)

**Comment by sreich** [comment]
I am also interested in an update on this. Nice investigation/root cause analysis @kaito-ms

**Comment by mikeviggiani** [comment]
Thanks @kaito-ms and @jan-dolejsi for highlighting this issue.

I am also running into this and interested in a resolution!

**Comment by morrowyn** [comment]
I have the same problem. I'm getting the following error: ` The value for this file collection is final and cannot be changed.`

**Comment by mikeviggiani** [comment]
You can add it to build.gradle following Gradles plugin documentation as a workaround.

**Comment by morrowyn** [comment]
I have added the following to my build.gradle

```
jacocoTestReport {
	classDirectories.setFrom fileTree(dir: "build/classes/java/main/").exclude('').include('')
}
```
and I still receive the same error. I'm using `gradle 7.6.1` by the way.

**Comment by mikeviggiani** [comment]
I used the following. Agent running Gradle 8.0

plugins {
    id 'jacoco'
}

jacocoTestReport {
    dependsOn test // tests are required to run before generating the report
    reports {
        xml.required = true
    }
}

**Comment by morrowyn** [comment]
Still the same error with 7.6.1
With 8.2.1 I get :
```
Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.
```

**Comment by matthewcorven** [comment]
> Still the same error with 7.6.1 With 8.2.1 I get :
> 
> ```
> Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.
> ```

I have the same issue with Gradle 8.0.2 and 8.4.

**Comment by vicky17d** [comment]
Hi 
Any updates on this? Any workaround? 
It was working fine in 6.9.4 (even though the documentation says readOnly for [classDirectories](https://docs.gradle.org/6.9.4/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html#org.gradle.testing.jacoco.tasks.JacocoReport:classDirectories))

After upgrading to Gradle 7, it is failing

**Comment by rs10615** [comment]
Any Update on this issue , I am upgrading my from 6.8 to 7 and getting the following error . They are 6 vulnerabilities reported by the sonar for gradle v6.x


 Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.

**Comment by NickJohn98** [comment]
I'm facing this when upgrading to gradle 8.3. Any update?

**Comment by olegpoltora** [comment]
Gradle - 8.4
jacoco toolVersion - 0.8.9

At local environment all is ok.
Problem ONLY at azure:
```
/home/vsts/work/1/s/gradlew clean build jacocoTestReport

> Configure project :
0.8.9

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vsts/work/1/s/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating root project 'lead-time-prediction-history'.
> Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.

```

`build.gradle`:

```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'io.freefair.lombok' version '8.0.1'
    id 'jacoco'
}

// java, repositories, dependencies and other blocks are skipped...

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn test
    reports {
        xml.required.set(false)
        csv.required.set(false)
        html.required.set(true)
    }
}
```

`azure-pipeline.yml`:
```
// other tasks are skipped

      - task: Gradle@3
        displayName: 'Build by Gradle'
        inputs:
          gradleWrapperFile: 'gradlew'
          workingDirectory: '$(Build.SourcesDirectory)'
          tasks: 'build'
          codeCoverageToolOption: 'JaCoCo'
          codeCoverageClassFilesDirectories: 'build/classes/java/main/','build/classes/java/test/'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          gradleOptions: '-Xmx3072m'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken) # Use the system access token for authentication

// other tasks are skipped
```

**Comment by Hypertext-Assassin-RSS** [comment]
i have the same error any updates or workarounds

**Comment by emmanuels0n** [comment]
Hi, I'm having the same problem, locally it works perfect, the problem is when I use the gradle task on Azure DevOps

Gradle 8.2
```

* What went wrong:
A problem occurred evaluating root project 'clavedinamica-ms-security'.
> Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.
```

**Comment by templier2** [comment]
I have disabled the "Code Coverage" functionality from a Gradle Test task.
Instead, my colleague has added Jacoco section inside of build.gradle and configured a dependency for tests on it.
But yes, it is not working as expected and we spent a few days fixing it with SonarQube.

**Comment by SchulteMarkus** [comment]
**Probable reason for this bug**

The Gradle option 'enabled' on the 'Report' type mentioned here was removed in Gradle v8.0, which was released on Feb 13, 2023, see https://docs.gradle.org/8.0/userguide/upgrading_version_7.html#report_and_testreport_api_cleanup for details.
So I assume Gradle@3 has still not adapted this Gradle change.

**Workaround**
Let's get hands dirty and do it on our own.
Notes:
- I didn't find a Cobertura plugin for Gradle, so sticking with JaCoCo
- I didn't manage to get jacoco.exec working, so using XML JaCoCo coverage result

1. Gradle with JaCoCo plugin and XML report
- https://docs.gradle.org/current/userguide/jacoco_plugin.html
- `reports {xml.required = true}`
2. In your DevOps pipeline additionally:
```yml
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: build/reports/jacoco/test/jacocoTestReport.xml
```
