### ISSUE TITLE
ManualValidation should have the option `onTimeout: "cancel"`

### ISSUE THREAD

**Issue by JWDobken** [microsoft/azure-pipelines-tasks#16880]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: ManualValidation@0  

## Issue Description

Actually I'm looking for a way to manually start pipeline parts (like I would do with gitlab-ci manual steps).
The `ManualValidation@0` comes closest to want I need:

```yaml
steps:
- task: ManualValidation@0
  timeoutInMinutes: 1440
  inputs:
    instructions:
      onTimeout: "reject"
```

But very often I just let the time-out period pass since no follow-up action is needed. The task will be rejected as expected, but I need something that is more neutral, like `onTimeout: "cancel"` and the pipeline does not have an error but a cancel status:

![image](https://user-images.githubusercontent.com/15050499/189909382-0fdd6acc-c275-4555-b2e9-c3f7a9b4d7b4.png)
