### ISSUE TITLE
Yaml DownloadPipelineArtifact@2 not able to download from a tagged build that has been canceled

### ISSUE THREAD

**Issue by mikerains** [microsoft/azure-pipelines-tasks#16902]
**Question, Bug, or Feature?**  
Question
**Enter Task Name**: DownloadPipelineArtifact@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadPipelineArtifactV2

## Environment
- Server - Azure Pipelines 
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account name: michaelrains
team project name: 'M7Computers'
build definition name: 'TestConsoleApp' (definitionId=56)
build number: 387

https://dev.azure.com/michaelrains/M7Computers/_build/results?buildId=387&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

## Issue Description

Intent is to use DownloadPipelineArtifact@2 to find latest previous run that is tagged with a value 'spocktagx', for the same pipeline, latestFromBranch, for a specific tag.

Using the input properties allowFailedBuilds: true and allowPartiallySucceededBuilds: true

PROBLEM: Prior build that is cancelled is not being found, it is going to a prior build that has the matching build tag.  There is no input property for this task to specify allowing from Canceled build.  It is unfortunate, since allowed Failed build one would expect that to include a Canceled build, or there to exist an input property such as allowCanceledBuild: true.

````
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Upload and Tag Stuff
  jobs:
  - job: maker
    steps:
    - task: PublishPipelineArtifact@1
      name: SpockUpload
      inputs:
        path: '$(Pipeline.Workspace)'
        artifactType: 'pipeline'
        artifactName: 'WorkspaceFolderCopy'

    - bash: |
        echo "##vso[build.addbuildtag]spocktagx"
        echo "tagged"

- stage: read
  displayName: Download and list 
  jobs:
  - job: reader
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: M7Computers
        pipeline: $(System.DefinitionId)
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/main'
        tags: 'spocktagx'
        allowFailedBuilds: true
        allowPartiallySucceededBuilds: true
        path: $(Pipeline.Workspace)/downloadtest4

    - bash: |
        ls -l $(Pipeline.Workspace)
        ls -lR $(Pipeline.Workspace)/downloadtest4

````
