### ISSUE TITLE
'&' in secret variable mishandled in Kubernetes@1 task

### ISSUE THREAD

**Issue by fscottmiller** [microsoft/azure-pipelines-tasks#16903]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using **Azure Pipelines**, provide the account name, team project name, build definition name/build number: _Using pipelines; can't provide publicly_

- Agent - Hosted or **Private**: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu, agent 2.210.0

## Issue Description

When using secret pipeline variables in the Kubernetes@1 step, we noticed that instances of `&` are replaced with `&amp;amp;`
By 'secret pipeline variables', I mean variables you create under the 'Variables' pane next to the 'Run' button in the pipeline web editor.

Task yaml:
```
- task: Kubernetes@1
   inputs:
     connectionType: 'Kubernetes Service Connection'
     kubernetesServiceEndpoint: 'my-endpoint'
     namespace: 'my-namespace'
     command: 'create'
     arguments: secret generic db-secret --from-literal=secretKey="$(SECRETVARIABLE)"
     secretType: 'dockerRegistry'
     containerRegistryType: 'Azure Container Registry'
```

We do have a workaround (not really a great one). Before the Kubernetes@1 task, we can run a bash step to use sed to correct the value:

```
- bash: |
    escaped_secret=$(echo "$(SECRETVARIABLE)" | sed 's/&amp\;amp\;/\&/g')
    echo "##vso[task.setvariable variable=SECRETVARIABLE;]$escaped_secret"
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
