### ISSUE TITLE
[AzureCLI@2] Must not make `*.sh` mandatory in bash script calls

### ISSUE THREAD

**Issue by bigbrozer** [microsoft/azure-pipelines-tasks#16916]
Hi,

Imagine this:

```yaml
- task: "AzureCLI@2"
  displayName: "📜 Import certificates"
  inputs:
    azureSubscription: "${{ parameters.spn }}"
    scriptType: "bash"
    scriptLocation: "scriptPath"
    scriptPath: "${{ parameters.scripts_folder }}/create-tls-secret"
```

You will get an error that the file cannot be found despite it exists because it seems the task is looking for `*.sh` extension in the filename which must not be forced from my point of view (AzureCLI@1 is working well so this looks like a regression...):

https://github.com/microsoft/azure-pipelines-tasks/blob/28d2387a289a5b462f598f5e46b78ca188a0509b/Tasks/AzureCLIV2/src/ScriptType.ts#L90

Do you think we can change this ? This is good if users have full control on the script name. It is creating a lot of confusion here...

Thanks.
