### ISSUE TITLE
NuGetAuthenticate@1 encodes already encoded Feed URL

### ISSUE THREAD

**Issue by rc1cent** [microsoft/azure-pipelines-tasks#16937]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetAuthenticate@1

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

In my `NuGet.config` file one of the package sources url is:
`https://pkgs.dev.azure.com/XXXXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_packaging/XXXX%40Release/nuget/v3/index.json`
**The key thing is that the url contains `%40` (encoded `@` character).**
I have service connection defined (name: `External-Feed`) with exactly the same url.

Restoring packages works fine when I use `DotNetCoreCLI@2` task:
```yaml
- task: DotNetCoreCLI@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: './NuGet.Config'
    externalFeedCredentials: External-Feed
    verbosityRestore: 'minimal'
```

I want to restore NuGet packages using `dotnet restore` command in Powershell script.
So first I'm using:
```yaml
- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: External-Feed
```
and then I'm running the restore command:
```yml
- powershell: |
    $slnFilePath = ...
    $nugetConfig = ...
    dotnet restore $slnFilePath --configfile $nugetConfig --verbosity minimal
```
The restore command fails due to `Unauthorized` error.
After I run the build with `system.debug=true` I noticed that `NuGetAuthenticate` task **encodes already encoded url** - see the logs below. The result url is:
`https://pkgs.dev.azure.com/XXXXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_packaging/XXXX%2540Release/nuget/v3/index.json`
Instead of `%40` there is `%2540` in the url.
When I used the url with `@` (in the service connection and `NuGet.config` file) the restore command worked fine, i.e. the nugets from the external feed were restored and the project was built successfully.

I don't want to get into the details but unfortunately I cannot use `@` in the url. I changed it only temporarily for testing.

### Task logs

From `NuGetAuthenticate` task:
```
##[debug]Detected token credentials for 'https://pkgs.dev.azure.com/XXXXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_packaging/XXXX%2540Release/nuget/v3/index.json'
##[debug]set VSS_NUGET_EXTERNAL_FEED_ENDPOINTS={"endpointCredentials":[{"endpoint":"https://pkgs.dev.azure.com/XXXXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_packaging/XXXX%2540Release/nuget/v3/index.json","password":***}]}
##[debug]Processed: ##vso[task.setvariable variable=VSS_NUGET_EXTERNAL_FEED_ENDPOINTS;issecret=false;]{"endpointCredentials":[{"endpoint":"https://pkgs.dev.azure.com/XXXXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_packaging/XXXX%2540Release/nuget/v3/index.json","password":***}]}
```
