### ISSUE TITLE
`helm registry` command no longer works in HelmDeploy@0

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tasks#16932]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: HelmDeploy  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

The HelmDeploy command [has support for a command `registry`](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helm.ts#L137) that appears to [allow you to login to an Azure Container Registry to push packages](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helmcommands/helmregistrylogin.ts). Issue #13602 mentions that it exists, but it's unclear if it is/was getting deprecated. The code is still there, but [only the `save` command is documented](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#save-command).

The problem is that I have a single repo with several Helm charts in it, so I need to authenticate to the ACR, but then script a foreach over the set of charts to push. As such, I can't really use the `save` command.

However, when trying to execute the `registry` command like this...

```yaml
- task: HelmDeploy@0
  inputs:
    command: registry
    azureSubscriptionEndpointForACR: $(serviceConnection)
    azureResourceGroupForACR: $(registryNamespace)
    azureContainerRegistry: $(registryName)
```

...I get an error:

```text
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.208.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Input required: kubernetesServiceEndpoint
```

Obviously I don't have a Kubernetes service endpoint to provide. I'm not deploying a Helm chart, I'm trying to login to the registry.

Given I can't execute this easily, I'm unclear how to use a service connection to authenticate to ACR so I can do a `helm push`. Is there something I'm missing? Is this not a use case currently being addressed? (If the `registry` command is deprecated, why is the code still there? If it's not deprecated, why doesn't it work and where is the documentation?)

**Comment by tillig** [comment]
The only way I've found around this is to skip using the `HelmDeploy` task altogether and use the `AzureCLI@2` task.

```yaml
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: pscore
    addSpnToEnvironment: true
    scriptLocation: inlineScript
    inlineScript: |
      [System.Environment]::SetEnvironmentVariable("HELM_EXPERIMENTAL_OCI", "1")
      $username = $env:servicePrincipalId
      $password = $env:servicePrincipalKey
      helm registry login $(registryName).azurecr.io --username $username --password $password
      helm push $(Build.ArtifactStagingDirectory)/mychart-0.1.0.tgz oci://$(registryName).azurecr.io/helm
      helm pull oci://$(registryName).azurecr.io/helm/mychart --version 0.1.0
```

**Comment by joshwright10** [comment]
I believe that you can use the `save` command. It was added with https://github.com/microsoft/azure-pipelines-tasks/pull/13005.
Just be sure to set `HELM_EXPERIMENTAL_OCI` to `1` in the env vars for the task based on what was mentioned in the PR.
````
- task: HelmDeploy@0
  inputs:
    azureSubscriptionForACR: $(azureSubscription)
    azureContainerRegistry: $(registryName)
    azureResourceGroupForACR: $(registryNamespace)
    command: 'save'
    chartNameForACR: "mychart"
    chartPathForACR: "mypath"
  env:
    HELM_EXPERIMENTAL_OCI: 1
````
