### ISSUE TITLE
[UseDotNetV2] Not setting "no_proxy" nuget config on Windows agents

### ISSUE THREAD

**Issue by gigi81** [microsoft/azure-pipelines-tasks#16935]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Private

## Issue Description

When UseDotNet (V2) runs on a Windows agent, it runs a series of nuget.exe commands at the end to setup the proxy configuration. However these series of commands do not set the "**no_proxy**" parameter resulting in a wrong configuration and following dotnet restore step failing.

### Task logs

Setting up proxy configuration for NuGet.
D:\ado\agents\agent-1\_work\_tool\NuGet\4.4.1\x64\nuget.exe config -set http_proxy=http://myproxy.com:8080
D:\ado\agents\agent-1\_work\_tool\NuGet\4.4.1\x64\nuget.exe config -set http_proxy.user=undefined
D:\ado\agents\agent-1\_work\_tool\NuGet\4.4.1\x64\nuget.exe config -set http_proxy.password=undefined

### Work Around
Added this step after UseDotNet@2 to make it work.

```yaml
- task: CmdLine@2
  displayName: 'Nuget config work around'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    script: 'nuget.exe config -set no_proxy=.mydomain.com'
```

### Fix
The issues is in [nugetinstaller.ts]( https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2/nugetinstaller.ts)
Which is not using the [proxyBypassHosts ](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/proxy.md)parameter to set the no_proxy nuget parameter.
There should be another command issued to set the **no_proxy** parameter.
