### ISSUE TITLE
[Xcode@5] Unable to set manageAppVersionAndBuildNumber

### ISSUE THREAD

**Issue by idutka** [microsoft/azure-pipelines-tasks#16984]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Xcode@5  

## Environment
Pool: Azure Pipelines
Image: macOS-12
Agent: Azure Pipelines 2

Task         : Xcode
Version      : 5.200.0

Xcode 13.4.1
Build version 13F100

## Issue Description

Since Xcode 13 Apple added a new option called **"Manage Version and Build Number" (manageAppVersionAndBuildNumber)**. This option is enabled by default

Every build with XCode 13 changes the build number of the frameworks in our iOS application to the app version. This causes issues for some of our frameworks because they depend on the correct version number of that framework. 

See the links belowe for more context. 
https://github.com/Jumio/mobile-react#ios-runs-on-debug-crashes-on-release-build
https://developer.apple.com/forums/thread/690647
https://github.com/microsoft/appcenter/issues/2324

We need to be able to set this parameter to FALSE in order to build the correct production ipa's using azure pipeline.
What is the best way to achieve this? 

Our task:
```
      - task: Xcode@5
          displayName: 'Build iOS App'
          inputs:
          actions: 'clean'
          configuration: 'Release'
          packageApp: true
          signingOption: 'manual'
          sdk: 'iphoneos15.5'
          xcWorkspacePath: 'ios/App.xcworkspace'
          scheme: 'App'
          exportMethod: app-store
          exportTeamId: '$(AppleDistributionTeamId)'
          exportPath: 'output/package'
          archivePath: 'output/archive'
          xcodeVersion: 'specifyPath'
          xcodeDeveloperDir: '/Applications/Xcode_13.4.1.app/Contents/Developer'
          teamId: '$(AppleDistributionTeamId)'
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
