### ISSUE TITLE
Add engines & nvmrc support to UseNode

### ISSUE THREAD

**Issue by jamiehaywood** [microsoft/azure-pipelines-tasks#16991]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: UseNode

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UseNodeV1

## Issue Description
It would be great to add optional inputs to UseNode that would allow for engines & nvmrc detection, i.e:
```yaml
- task: UseNode@1
  inputs:
    detectVersionFromEngines: true
    detectVersionFromNvmrc: true
```

Currently we do some convoluted detection by doing the following:

```yaml
- bash: |
    if test -f ".nvmrc"; then
      NODE_VERSION=$(cat .nvmrc)
      echo "##vso[task.setvariable variable=NODE_VERSION]$NODE_VERSION"
    fi  
  displayName: 'Set node version from .nvmrc (if exists)'

- bash: |
    if jq -e -r '.engines | has("node")' package.json > /dev/null; then
      ENGINES_NODE_VERSION=$(jq -e -r '.engines.node' package.json)
      echo "##vso[task.setvariable variable=ENGINES_NODE_VERSION]$ENGINES_NODE_VERSION"
    fi  
  displayName: 'Set node version from engines property (if exists)'

- task: UseNode@1
  displayName: Use Node.js
  inputs:
    version: ${{ coalesce(parameters.nodeVersion, '$(ENGINES_NODE_VERSION)', '$(NVMRC_NODE_VERSION)') }}
```
