### ISSUE TITLE
AzureRmWebAppDeployment@4 InlineScript runs with wrong version of Node

### ISSUE THREAD

**Issue by jesserizzo** [microsoft/azure-pipelines-tasks#17021]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment@4  

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

- Agent - Hosted or Private: 
    
Hosted

## Issue Description

When including an Inline script to be run post deployment, it runs on the wrong version of Node. I have set the App Service to run 16 LTS, and the command in my Inline Script runs with 10.22.0

Here's the full task
```
 - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy app'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '$(azureServiceConnection)'
      appType: 'webAppLinux'
      WebAppName: '$(webAppName)'
      packageForLinux: '$(System.DefaultWorkingDirectory)/dist'
      runtimeStack: 'NODE|16-lts'
      ScriptType: 'Inline Script'
      InlineScript: 'node --version && yarn install --production=true --network-timeout 3600000'
      StartupCommand: 'node main'

```

### Task logs

Successfully deployed web package to App Service.
Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"NODE|16-lts","appCommandLine":"node main"}
Updated App Service Configuration settings.
Trying to update App Service Application settings. Data: {"SCM_COMMAND_IDLE_TIMEOUT":"1800"}
App Service Application settings are already present.
Executing given script on Kudu service.
Standard output from script: 
v10.22.0
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Standard error from script: 
##[error]error @azure/identity@2.1.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.22.0"
error Found incompatible module.

##[error]Error: Unable to run the script on Kudu Service. Error: Error: Executed script returned '1' as return code. Error: error @azure/identity@2.1.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.22.0"
error Found incompatible module.
