### ISSUE TITLE
AzureStaticWebApp@0: Preview environments are named `merge` when task is used inside build validation

### ISSUE THREAD

**Issue by feedm3** [microsoft/azure-pipelines-tasks#17066]
## Current behaviour

I have a static web app and using `AzureStaticWebApp@0` in order to deploy each pull request in my Azure DevOps Repo separately. The pipeline file to do this looks very basic:

```
name: Deploy static web app

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-...
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_DUNE_044A9F703)
      app_location: "/"
      output_location: "/dist"
      production_branch: 'main'
```

I don't use the `trigger` inside the pipeline config, but the "Build validation" in DevOps itself because:
- I want to make the pipeline mandatory
- The pipeline run should be visible right inside the pull request

<img width="857" alt="image" src="https://user-images.githubusercontent.com/7814926/196528813-c64d1d4d-de6d-4329-9d24-83b36999bebc.png">

## The problem

When using "Build validation" to trigger a pipeline, the branch inside the pipeline isn't the branch of the pull request anymore. It changes to `merge`. Because of this, every pull request gets deployed to the `merge` environment, which makes the feature more or less useless:

<img width="786" alt="screenshot-18-10-2022-at-21-45-16@2x" src="https://user-images.githubusercontent.com/7814926/196533751-803ff82f-6379-40da-891f-3c2f610cb0bd.png">

I read a bunch of issues here on GitHub, this one goes into detail about it: https://github.com/microsoft/azure-pipelines-tasks/issues/8793. Pull request builds are merged into their source branch with a virtual commit, and this commit lives in the `merge` branch. The pipeline runs with the branch. Therefore, the variable `SourceBranchName` doesn't refer to the original branch of the pull request anymore, but to this virtual one. Unfortunately, this is the one the AzureStaticWebApp task is using:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureStaticWebAppV0/index.ts#L125

## Expected behaviour

The AzureStaticWebApp task should:
- deploy each pull request trigger with the appropriate branch name, and not use the virtual `merge` branch 
- be a "Build validation" step

How can I achieve this?

**Comment by bkarstaedt** [comment]
For me this bug/feature makes the "preview environments" for my use case useless, too :(.

As a workaround I now use the [named environments](https://learn.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=azure-devops) with the PR ID as the name:

```yaml
- task: AzureStaticWebApp@0
  inputs:
    deployment_environment: $(System.PullRequest.PullRequestId)
    ...
```

This way I have a stable _unique_ environment per PR.

The above example is a simplified version of my pipeline. If the branch is e.g. "main" I skip setting the `deployment_environment` so that I avoid named environments of non-feature branches.
