### ISSUE TITLE
PublishTestResults task "hangs forever"

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/azure-pipelines-tasks#17101]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults -> Version 2.210.0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Microsoft Internal

- Agent - Hosted or Private: Hosted
    

## Issue Description

Intermitently we are seeing the PublishTestResults task "Freeze or Disappear" completely

The task is : 
```yaml
  - task: PublishTestResults@2
    displayName: Publish Test Results
    retryCountOnTaskFailure: 4
    timeoutInMinutes: 30
    inputs:
      testResultsFiles: |
        $(Build.SourcesDirectory)/logs/test-results/unit/unit-tests-report.xml
      testRunTitle: UnitTests_$(System.JobPositionInPhase)
      platform: $(Build.DefinitionName)
      configuration: Tests
    condition: succeededOrFailed()

```

Keep in mind `timeoutInMinutes

![image](https://user-images.githubusercontent.com/37447884/198414671-c1f68b02-f332-4146-af89-0f92366a8b6b.png)

Unfortunately, there is nothing here in the logs, even the timeline logs of the pipeline : 

![image](https://user-images.githubusercontent.com/37447884/198414908-1428b91c-54c5-4ca4-8e75-e46c03d55cf1.png)

This happens a couple of times a week for us and is a bit frustrating for our developers as they are not sure what is happening since the build is taking 4+h
