### ISSUE TITLE
Secrets exposed by AzureRmWebAppDeployment@4 when pulled from another job

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-pipelines-tasks#17100]
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment  

## Environment
- Server - Azure Pipelines
- Agent - Hosted (windows-latest and ubuntu-latest)

## Issue Description

When `AzureRmWebAppDeployment` is invoked with `AppSettings`, and the value of that parameter includes a secret from another job, the console output will output the secret **UNMASKED** in the logs. Attempting to expose the secret by directly printing it from a script is not successful, and the secret remains masked. This seems to indicate that the `AzureRmWebAppDeployment` somehow defeats the built-in masking functionality unintentionally.

Here is a minimal YAML example that demonstrates the issue:
```
jobs:
- job: job1
  steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: my_azure_sub
        keyVaultName: my_key_vault

    - pwsh: |
        $settingsArgs = "-ENABLEFOOBAR "true" -SECRETAPIKEY $(secret_from_keyvault)"
        echo "##vso[task.setvariable variable=value;isOutput=true;isSecret=true;]$settingsArgs"
        echo "$settingsArgs" # MASKED
      name: task

- deployment: job2
  dependsOn:
    - job1
  variables:
    slotAppSettings: $[ dependencies.job1.outputs['task.value'] ]
  steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        AppSettings: $(slotAppSettings) # UNMASKED
        # other inputs omitted for brevity

    - pwsh: echo "You can't see the secret here: $env:MYVAR" # MASKED
      env:
        MYVAR: $(slotAppSettings)
```

### Task logs

The log prints the value of `SECRETAPIKEY` unmasked:
```
Trying to update App Service Application settings. Data: {"SECRETAPIKEY":"UNMASKED_SECRET_KEY"...
```
