### ISSUE TITLE
PowerShell@2 [uri]::EscapeDataString a value then stored in Pipeline variable unescapes ;

### ISSUE THREAD

**Issue by SteveGoodman** [microsoft/azure-pipelines-tasks#17116]
## Required Information
**Bug**  
*Type*: Azure Pipeline

**Enter Task Name**: Powershell@2 

## Environment
- Server - Azure Pipelines 
    
- Agent - Hosted
    Agent name: 'Hosted Agent'
    Agent machine name: 'fv-az378-501'
    Current agent version: '2.211.1'
    Operating System Ubuntu, 20.04.5, LTS  (also occurs on Windows)
    Agent running as: 'vsts'

## Issue Description

When I store a Uri escaped value in a devops variable and then retrieve the value in the next step, any ';' are subsequently unescaped. For example if I use the following yaml:

```yaml
- task: PowerShell@2
  displayName: Test Encoding - Perform Encoding
  inputs:
    targetType: inline
    script: |
      $myEncodedString = [uri]::EscapeDataString("This; is a $ string; that - needs // some encoding;")
      Write-Host $myEncodedString
      echo "##vso[task.setvariable variable=myEncodedString;]$myEncodedString"

- task: PowerShell@2
  displayName: Test Encoding - Write out Encoding
  inputs:
    targetType: inline
    script: |
      Write-Host "$(myEncodedString)"
```

This then produces the following output:
```powershell
Test Encoding - Perform Encoding:
This%3B%20is%20a%20%24%20string%3B%20that%20-%20needs%20%2F%2F%20some%20encoding%3B
##[debug]Processed: ##vso[task.setvariable variable=myEncodedString;]This%3B%20is%20a%20%24%20string%3B%20that%20-%20needs%20%2F%2F%20some%20encoding%3B
```
followed by 
```powershell
Test Encoding - Write out Encoding:
This;%20is%20a%20%24%20string;%20that%20-%20needs%20%2F%2F%20some%20encoding;
```

Note the `;` are no longer encoded in the subsequent step.

### Task logs
[TestEncodingWriteOutEncoding.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9909132/TestEncodingWriteOutEncoding.txt)
[TestEncoding-PerformEncoding.log](https://github.com/microsoft/azure-pipelines-tasks/files/9909133/TestEncoding-PerformEncoding.log)
