### ISSUE TITLE
Task Maven@4 with report-aggregate

### ISSUE THREAD

**Issue by sebschmeister** [microsoft/azure-pipelines-tasks#17118]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@4 

## Issue Description

Pull Request for Maven@4 says:
> Submodule reports are saved in associated directories using the "prepare agent" and "report" goals. The Maven task creates a special submodule for reports. This submodule's pom file contains the main pom file as a parent, the other submodules as dependencies, and the "report-aggregate" goal in the "verify" phase. An aggregated report is used as the final results.

But if a submodule is of type packaging pom the special submodule can not resolve it correctly.

This is added to CCReport43F6D5EF pom.xml:
```
<dependency>
    <groupId>com.test</groupId>
    <artifactId>test-pom</artifactId>
    <version>0.0.1</version>
</dependency>
``` 

But that fails when trying to download the jar that is not available

### Task logs

`[ERROR] Failed to execute goal on project CCReport43F6D5EF: Could not resolve dependencies for project com.test:CCReport43F6D5EF:pom:1.0-SNAPSHOT: Failure to find com.test:test-pom:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by kirill-ivlev** [comment]
@sebschmeister thank you for reporting that!
We will have a look.
Could you please share the part of YML with task input parameters?

**Comment by sebschmeister** [comment]
Sure, here it is:

```
- task: Maven@4
     displayName: 'Maven package'
     inputs:
	  mavenPomFile: '/agent/_work/1/pom.xml'
	  mavenOptions: '-Xmx3072m -Dmaven.repo.local=/agent/_work/1/myrepo/.m2/repository'
	  options: '-ntp -B'
	  javaHomeOption: 'JDKVersion'
	  jdkVersionOption: '1.8'
	  jdkArchitectureOption: 'x64'
	  publishJUnitResults: true
	  testResultsFiles: '**/surefire-reports/TEST-*.xml'
	  goals: 'package'
	  codeCoverageToolOption: 'jaCoCo'
	  codeCoverageClassFilesDirectories: 
	  codeCoverageSourceDirectories: 
	  codeCoverageFailIfEmpty: false
	  sonarQubeRunAnalysis: false
	  sqMavenPluginVersionChoice: 'latest'
	  isJacocoCoverageReportXML: true
	  codeCoverageClassFilter: 
```
