### ISSUE TITLE
Can I use DownloadBuildArtifacts task to download all content in drop instead of just vstsdrop.json file?

### ISSUE THREAD

**Issue by JiayuanL** [microsoft/azure-pipelines-tasks#17113]
I am trying use DownloadBuildArtifacts task to download all content in drop, but what I get is just vstsdrop.json file. I found artifactDropDownloadTask could be used to get all drop content but it seems only support windows while I need to have the pipeline running in linux. Is there way I could use DownloadBuildArtifacts task to get all drop content? Thanks!

**Comment by DenisRumyantsev** [comment]
Hi, @JiayuanL. The `DownloadBuildArtifactsV1` task is designed to download artifacts published during the build.

The `PublishBuildArtifactsV1` and `PublishPipelineArtifactV1` tasks, and the `publish` shortcut, can be used to publish artifacts.

The `DownloadBuildArtifactsV1`, `DownloadPipelineArtifactV2`, and `DownloadFileshareArtifactsV1` tasks, and the `download` shortcut, can also be used to download artifacts.

Here is an example of using these tasks in the `yml` pipeline —
```yml
pool: <Some-Agent-Pool>

trigger: none

variables:
  System.Debug: true

jobs:
- job: _publish_
  displayName: Publish
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: path/to/source-x1
      ArtifactName: artifact-x1
      publishLocation: Container

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: path/to/source-x2
      artifact: artifact-x2
      publishLocation: pipeline

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: path/to/source-x3
      ArtifactName: artifact-x3
      publishLocation: FilePath
      TargetPath: path/to/fileshare

- job: _download_
  dependsOn: _publish_
  displayName: Download
  steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: current
      downloadType: single
      artifactName: artifact-x1
      downloadPath: path/to/target-x1

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: current
      artifactName: artifact-x2
      targetPath: path/to/target-x2

  - task: DownloadFileshareArtifacts@1
    inputs:
      filesharePath: path/to/fileshare
      artifactName: artifact-x3
      downloadPath: path/to/target-x3
```
