### ISSUE TITLE
Warnings about Resource file already set when using AzureKeyVault v1.212.0

### ISSUE THREAD

**Issue by jsloan117** [microsoft/azure-pipelines-tasks#17127]
## Required Information

*Type*: Bug

**Enter Task Name**: AzureKeyVault

## Environment
- Agent - Private: 
  - OS: RHEL7
  - Version: 2.211.1

## Issue Description

Dozens of warnings about "Resource file already set". This started today, from what I can tell.

```text
##[warning]Resource file has already set to: /opt/buildagent/_work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

**Comment by jdaugherty** [comment]
For us, this started happening in a build done on Nov 1st at 1:51 PM.  It did not occur in the previous build that ran on Oct 26 at 6:01 PM.  It's happening in the pre-job task for us, where it transfers secrets from the keyvault to populate the library values.

**Comment by Poovamma** [comment]
+1 . 
We are facing issues with the same. We are seeing multiple warnings while fetching secrets from Azure Key vault using the task 
- task: AzureKeyVault@1 

Error 

` ##[warning]Resource file has already set to: /azp/agent/_work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json`

**Comment by IanMoroney** [comment]
This just started happening for us too, and i get 12+ warnings in some pipelines.

**Comment by IanMoroney** [comment]
@chshrikh , @thesattiraju , @tauhid621 could someone get this bug assigned and resolved? It's causing too many false positives and devs have now started ignoring warnings altogether in the pipelines.

**Comment by fmck** [comment]
We are seeing the same issue, multiple warnings per build all on a pre-job to grab secrets from key vault.

**Comment by Turbofroggy** [comment]
We are seeing this in our pipelines as well.

**Comment by schrx1964** [comment]
we are seeing this in our buil pipelines again since a couple of days. Last Tuesday everything was still ok.

**Comment by gpkrieger** [comment]
We are seeing this in our build pipelines as well, the pipelines finish successfully, but it doesn't seem to be actually updating with values from the keyvault.  to test, I deleted one of my keys used in the pipeline, and the pipeline still finished successfully, and the app still used the old key value.

**Comment by JagadeeshVenkatesan** [comment]
+1 
I started seeing these warnings from Friday onwards and still see them in all my pipelines(100+), can anyone help me with it?

**Comment by gorziza** [comment]
We have the same problem!

**Comment by at-besa** [comment]
+1 We also started seeing this issue in our pipelines about a week ago. This also turned out that most of the people ignore the warnings now.

**Comment by AnkitPathak41** [comment]
+1 We are also facing the same issue more than 300 warnings for keyvault task in Azure DevOps pipeline

**Comment by jcontti-axa** [comment]
+ 1 same problem here, more than 200 warnings :(

**Comment by v-mohithgc** [comment]
Task version has been rolled back to 1.211.2

**Comment by jwikman** [comment]
We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.

Is there any easy way to revert all those to v1.211.2?

**Comment by v-mohithgc** [comment]
> We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.
> 
> Is there any easy way to revert all those to v1.211.2?

Hi, you can try to clean agent tasks cache.

Example path:
<agentname>\_work\_tasks\*

**Comment by at-besa** [comment]
> > We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.
> > Is there any easy way to revert all those to v1.211.2?
> 
> Hi, you can try to clean agent tasks cache.
> 
> Example path: {agentname}\ _work \ _tasks *

I already tried that and it does not help, these warnings appear immediatly with the first run after cleaning.

**Comment by That1Guy007** [comment]
We are also running into this issue. Any resolution so far? It is for our download secrets task from a variable group that is linked to an azure key vault.

**Comment by v-mohithgc** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/17151 revert is completed, will take time to roll out 213

**Comment by hilari0n** [comment]
We're using Azure DevOps and Hosted Agents and we're not directly referencing this task in our pipelines, but we are using variable groups, defined based on Azure KeyVault, which probably causes implicit use of this task. This basically translates to all of our pipelines being affected by this issue, with no way to address it, without remaking all our pipelines to explicitly use the task in a corrected version.

**Comment by abatishchev** [comment]
@v-mohithgc can you please share the status of the rollout? namely when the new version is expected to land on `msazure`?

**Comment by hilari0n** [comment]
The issue is also being [raised on the StackOverflow](https://stackoverflow.com/questions/74288802).

**Comment by jwikman** [comment]
I'm having the same setup as @hilari0n, on hosted agents with variable groups.
My agents are still downloading 1.212.0 of AzureKeyVault... 
I've tried to delete the 1.212.0 folder and files from the `[agent folder]\_work\_tasks\AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e` folder, but 1.212.0 is downloaded as soon as I start a pipeline. The agent is running version 2.213.2.

When can we expect that 1.213.0 is in use when variable groups are used?
I've got more than a hundred pipelines affected by this, so refactoring from variable groups to explicit use of the AzureKeyVault task isn't appealing.

**Comment by tomaustin700** [comment]
Like others have said; this happens when a pipeline references a variable group linked to a Key Vault. It doesn't seem to cause any actual issues but I've got 252 warnings thrown in one of my largest pipelines.

**Comment by IanMoroney** [comment]
it's fixed for me after the revert

**Comment by andrii-lundiak** [comment]
**BAD**
At first I used variables group defined in AzureDevOps Library section with reusing dedicated (filtered out) KeyVault values (via KeyVault Connection) and as turned out AzureKeyVault was `1.212.0` was in usage and the the issue flow is almost exactly as @hilari0n described. 

```
##[warning]Resource file has already set to: 
/home/vsts/work/_tasks/AzureKeyVault_***244*****33**
/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

I tried different combinations with library and KeyVault, but issue still was happening.

**OK**
I then detached from using Library entry, and I configured `AzureKeyVault` task in my YAML file directly as such:

```
 - task: AzureKeyVault@1 # expected 1.212.0 as latest version. Try later to hardcode version to 1.211.2
    inputs:
      azureSubscription: $(myAzureSubscription)
      KeyVaultName: $(myKeyVaultName)
      runAsPreJob: false
      SecretsFilter: 'MYSECRETKEY'
```

Actual version got as `1.211.2` WHICH IS with NO issues (no warnings).

**OK**
But this way I ALSO realize, that I really narrow down filtered out number of secrets, which is OK but still doesn't answer why that warning wasn't there and then appeared.

**WEIRD but OK**
Anyway I got from above comments and mentioned PRs, that official version for `azure-pipelines-tasks-azure-arm-rest-v2` package got reverted, and now I decided to also TRY using `AzureKeyVault@2`, which got me ` 2.211.1` actual version. BUT then that task did NOT get my KeyVault secret was NOT shown as "downloaded" in logs. I suspected something bad will happen w my code. But whole YAML and code flow was OK.

**OK vs. OK**
So looks like, for now it's either 
- OK/safe for me to hardcode version `1.211.2`... But it's a pity I should do it.
- Or use latest `AzureKeyVault@2` version

**Comment by bdbvb** [comment]
> #17151 revert is completed, will take time to roll out 213

@v-mohithgc 

When I run a YAML pipeline with a build stage and a deployment stage, the build stage gets the offending version (1.212.0), whereas the deployment stage gets the reverted version (1.211.2).

Steps to reproduce:

- In Azure Devops create a project with a Git repo and a YAML pipeline. The YAML is listed below.
- In Azure, create a Key Vault with a secret named “a-secret” with an arbitrary value.
- In the Azure DevOps project, under Pipelines > Library, create a variable group called BuildSecrets, link that to the Key Vault mentioned above, and select “a-secret” as one of the variables.
- Run the pipeline.
- Look in the execution logs and see warnings.

```
name: $(Build.DefinitionName)_$(Year:yy)$(DayOfYear)$(Rev:.r)

trigger:
- main

pool:
  vmImage: windows-2022

stages:
- stage: Build
  displayName: Build
  variables:
    - group: BuildSecrets
    # mapped standard variables for secrets
    - name: my-secret
      value: $(a-secret)
  jobs:
  - job: MyJob
    steps:
    - script: echo '$(my-secret)'

- stage: ReleaseDev
  displayName: Release-Dev
  dependsOn: Build
  condition: succeeded()
  variables:
    - group: BuildSecrets
    # mapped standard variables for secrets
    - name: my-secret
      value: $(a-secret)
  jobs:
  - deployment: Release
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: echo '$(my-secret)'
```

The same sort of thing happens for me with a single on-prem build agent.
