### ISSUE TITLE
ArchiveFiles includes MacOS pointer files in generated files on MacOS 13

### ISSUE THREAD

**Issue by AndyGettingAn** [microsoft/azure-pipelines-tasks#17136]
Archive Files includes MacOS pointer files (._) in generated .tar file on new MacOS 13
*Type*: Bug

**Enter Task Name**: ArchiveFilesV2 

## Environment
Private Agent with MacOS 13

## Issue Description
After updating private agent to MacOS 13 the ArchiveFiles task includes the MacOS pointer files in the generated tar. Works fine on MacOS 11.

Task: 
```
ArchiveFilesV2
 task: ArchiveFiles@2
  displayName: 'Create tar archive'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build/$(scheme)'
    archiveType: tar
    archiveFile: '$(Build.SourcesDirectory)/$(scheme)-release/$(product_name).tar.gz'

```
Valid Result on MacOS 11:
```
Folder.tar.gz
 - Folder
    - Framework.xcframework
    - Framework.podspec

```

Invalid Result on MacOS 13:
```
Folder.tar.gz
 - Folder
    - Framework.xcframework
    - ._Framework.xcframework
    - Framework.podspec
    - ._Framework.podspec
 -._Folder

```

**Comment by DmitriiBobreshev** [comment]
Hi @AndyGettingAn, thank you for reporting, checked the ArchiveFiles task on macOS 11 and macos 12, seems like files with pointers are always included in the archive. You can check it by yourself by running a pipeline like this [example.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9963113/example.txt)

Are you sure that aren't some other tasks that won't clean pointer files after finishing?

**Comment by AndyGettingAn** [comment]
@DmitriiBobreshev 
Executing this pipeline on macOS 11/12 and macOS 13 results in different files. 
```
pool:
  name: Azure Pipelines
steps:
- bash: |
   mkdir testArchieve
   touch testArchieve/testFile.txt
  displayName: 'Bash Script'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)/testArchieve'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/testArchieve'
    archiveType: tar
    archiveFile: '$(Build.ArtifactStagingDirectory)/testArchieve.tar.gz'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/testArchieve.tar.gz'
    artifact: test
```

You can see the pointer files when opening the tar files on Mac. Our problem occurred when uploading to Artifactory.


The yml above produces following files on macOS 11 and macOS 13:

<img width="421" alt="Screenshot 2022-11-08 at 22 28 39" src="https://user-images.githubusercontent.com/24636447/200679967-9c2a3f88-fef9-41ff-9793-18e1ab43ba8b.png">


Uploading both files onto artifactory results in this:

<img width="348" alt="Screenshot 2022-11-08 at 22 28 17" src="https://user-images.githubusercontent.com/24636447/200680044-4be9a32d-f782-41c2-92c4-f4a367ead9d8.png">
