### ISSUE TITLE
How to read multi-line variable for use in Docker release task?

### ISSUE THREAD

**Issue by jtheisen** [microsoft/azure-pipelines-tasks#17234]
I have a working build pipeline that can release to Docker Hub with the Docker@2 target:

```
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'Squil Docker Hub'
        repository: squiltech/squil
        tags: $(squildockertags)
```

I now struggle to bring the release over to a proper release pipeline.

The target accepts the tags as a multi-line value, but now that multi-line value needs to be passed from the build pipeline to the release pipeline, ie. I need to read it from an artifact in the release pipeline:

```
echo "##vso[task.setvariable variable=squildockertags]$(cat dockertags.txt)"
```

That, however, makes the lines become on line, each tag separated by a space. Docker@2 isn't happy about that and says the format is wrong:

```
invalid argument "***/squil:1.1 1.1.12 1.1.12 latest " for "-t, --tag" flag: invalid reference format
```

I also seem to be unable to use expressions (`$[...]`) in the tag field of the Docker target.

Can anyone tell me what else to try?
