### ISSUE TITLE
Kubectl diff should not break the execution of a yaml pipeline

### ISSUE THREAD

**Issue by SupportNubersia** [microsoft/azure-pipelines-tasks#17279]
Hi all,
the following piece of code uses the Kubernetes@1 task in order to run the "kubectl diff" command.
```
- task: Kubernetes@1
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: mysa
          namespace: mynamespace
          command: diff
          arguments: aws-auth.yaml
          outputFormat: none
```
If the diff returns diferences, (exit status 1) it breaks the pipeline. How can I apply my kubectl diff and see the differences without breaking the code?
