### ISSUE TITLE
Error: /usr/bin/xcodebuild failed with return code: 65 apparent without reason

### ISSUE THREAD

**Issue by alimdi** [microsoft/azure-pipelines-tasks#17295]
## Required Information

*Type*: Bug

**Enter Task Name**: Xcode

## Environment
- Server - Azure Pipelines
    
  
    - Account name, team project name, build definition name/build number: Confidential

- Agent -  Private: 
    

## Issue Description

##[error]Error: /usr/bin/xcodebuild failed with return code: 65
**There is no apparent error and the verbose option doesn't reveal any clue on the error source**
Is there a way to get any relevant information on why the build is failing?

  - task: Xcode@5
    displayName: '[Mobile] - ${{ parameters.environment }} - Build ios app'
    inputs:
      actions: "build -verbose"
      configuration: "${{ parameters.appleConfiguration }}"
      sdk: "iphoneos"
      xcWorkspacePath: './src/SYNCBLOB.Mobile/ios/app/app.xcworkspace'
      scheme: 'SyncBlob-${{ parameters.env }}'
      packageApp: true
      exportPath: "output"
      signingOption: "manual"
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileName: '$(APPLE_PROV_PROFILE_UUID)'
      publishJUnitResults: true
      xcodeVersion: "default"

### Task logs

[task-debug.txt](https://github.com/microsoft/azure-pipelines-tasks/files/10105881/task-debug.txt)

## Troubleshooting

The build with xcode on a mac is working

### Error logs

See task logs

**Comment by alimdi** [comment]
The problem was with the signing but the task didn't return that information.
I had to publish de tmpdir as artifact and get the xcodebuild.log to identify the errors.

```
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/AgentTempDirectory'
    displayName: 'Copy Agent.TempDirectory to drop'
```

```
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact: tmp'
    inputs:
      targetPath: '$(Build.artifactStagingDirectory)/AgentTempDirectory'
      artifactName: 'Agent.TempDirectory'
```
