### ISSUE TITLE
PackerBuild fail when build_resource_group_name is defined

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/azure-pipelines-tasks#17484]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PackerBuild

## Environment
- Server - Azure Pipelines or TFS on-premises?
  Azure Pipelines

- Agent - Hosted or Private: 
  Hosted
    
    - If using Hosted agent, provide agent queue name:
      windows-latest

## Issue Description

It is not possible for packer to specify a resource group to be used for image creation, but this is important for companies as no admin will give global permissions to the executing service principal.
in the default case the task creates a resource group with a random name. packer (.exe) offers to override this with the configuration parameter [build_resource_group_name](https://developer.hashicorp.com/packer/plugins/builders/azure/arm#build_resource_group_name). but if this parameter is set in an azure pipeline an error occurs because the task sets a non-forced parameter by itself.

> * Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

```yaml
- task: PackerBuild@1
  inputs:
    templateType: 'builtin'
    ConnectedServiceName: 'CBL Visual Studio Enterprise - MPN'
    isManagedImage: true
    managedImageName: 'BuildAgent'
    location: 'westeurope'
    storageAccountName: 'kvscblvmssscripts'
    azureResourceGroup: 'KvsCblVmssAgent'
    baseImageSource: 'default'
    baseImage: 'MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:windows'
    packagePath: 'VmSetupScripts'
    deployScriptPath: 'vmss_ext.min.ps1'
    additionalBuilderParameters: '{"vm_size":"Standard_D4ads_v5","build_resource_group_name":"kvscbltempimagebuilder","shared_image_gallery_destination":{"subscription": "***","resource_group": "KvsCblVmssAgent","gallery_name": "kvscblsig01","image_name": "BuildAgent","image_version": "1.1.0","replication_regions": ["westeurope"],"storage_account_type": "Standard_LRS"}}'
    imageUri: 'PackerImageUrl'
    imageId: 'PackerResourceId'

```

### Task logs

```
Starting: PackerBuild
==============================================================================
Task         : Build machine image
Description  : Build a machine image using Packer, which may be used for Azure Virtual machine scale set deployment
Version      : 1.208.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/packer-build
==============================================================================
Resolving deploy package path.
Resolved deploy package path: D:\a\1\s\VmSetupScripts.
Resolving deploy script path.
Resolved deploy script path: vmss_ext.min.ps1.
Parsing additional builder parameters json.
C:\ProgramData\Chocolatey\bin\packer.exe --version
1.8.4
Current installed packer version is 1.8.4.
Created staging directory for keeping packer binary and templates: D:\a\_temp\1671049768345.
Original template location: D:\a\_tasks\PackerBuild_845fd4f4-642d-4694-8514-047948a5a556\1.208.0\DefaultTemplates\default.managed.windows.template.json
Copying original template from D:\a\_tasks\PackerBuild_845fd4f4-642d-4694-8514-047948a5a556\1.208.0\DefaultTemplates\default.managed.windows.template.json to temporary location D:\a\_temp\1671049768345
Copied template file to a temporary location: D:\a\_temp\1671049768345
Running packer fix command
C:\ProgramData\Chocolatey\bin\packer.exe fix -validate=false D:\a\_temp\1671049768345\default.managed.windows.template-builderUpdated.json
{
  "builders": [
    {
      "build_resource_group_name": "kvscbltempimagebuilder",
      "client_id": "{{user `client_id`}}",
      "client_secret": "{{user `client_secret`}}",
      "communicator": "winrm",
      "image_offer": "{{user `image_offer`}}",
      "image_publisher": "{{user `image_publisher`}}",
      "image_sku": "{{user `image_sku`}}",
      "location": "{{user `location`}}",
      "managed_image_name": "{{user `managed_image_name`}}",
      "managed_image_resource_group_name": "{{user `resource_group`}}",
      "object_id": "{{user `object_id`}}",
      "os_type": "Windows",
      "shared_image_gallery_destination": {
        "gallery_name": "kvscblsig01",
        "image_name": "BuildAgent",
        "image_version": "1.1.0",
        "replication_regions": [
          "westeurope"
        ],
        "resource_group": "KvsCblVmssAgent",
        "storage_account_type": "Standard_LRS",
        "subscription": "2a4a7111-5e88-43cf-ac40-01760aa4f23a"
      },
      "subscription_id": "{{user `subscription_id`}}",
      "tenant_id": "{{user `tenant_id`}}",
      "type": "azure-arm",
      "vm_size": "Standard_D4ads_v5",
      "winrm_insecure": "true",
      "winrm_timeout": "15m",
      "winrm_use_ssl": "true",
      "winrm_username": "packer"
    }
  ],
  "provisioners": [
    {
      "inline": [
        "cmd /c \"if exist c:\\\\DeployTemp rd /s /q c:\\\\DeployTemp\"",
        "cmd /c \"mkdir c:\\\\DeployTemp\""
      ],
      "type": "windows-shell"
    },
    {
      "destination": "c:\\DeployTemp",
      "source": "{{user `package_path`}}",
      "type": "file"
    },
    {
      "inline": [
        "cd \"C:\\DeployTemp\"",
        "ls",
        "C:\\DeployTemp\\{{user `package_name`}}\\{{user `script_relative_path`}} {{user `script_arguments`}}"
      ],
      "type": "powershell"
    },
    {
      "inline": [
        "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
        "\u0026 $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quit /quiet"
      ],
      "type": "powershell"
    }
  ],
  "variables": {
    "capture_name_prefix": "",
    "client_id": "",
    "client_secret": "",
    "image_offer": "",
    "image_publisher": "",
    "image_sku": "",
    "location": "",
    "managed_image_name": "",
    "object_id": "",
    "package_name": "",
    "package_path": "",
    "resource_group": "",
    "script_arguments": "",
    "script_relative_path": "",
    "storage_account": "",
    "subscription_id": "",
    "tenant_id": ""
  }
}

Running packer validate command to ensure template is valid
C:\ProgramData\Chocolatey\bin\packer.exe validate -var-file=D:\a\_temp\mm95ec6p38r.json -var-file=D:\a\_temp\xsxyn9e9g3f.json D:\a\_temp\1671049768345\default.managed.windows.template-builderUpdated-fixed.json
Error: Failed to prepare build: "azure-arm"

1 error(s) occurred:

* Specify either a location to create the resource group in or an existing
build_resource_group_name, but not both.


##[error]Packer validate command failed. This could happen if task does not support packer version.
Finishing: PackerBuild
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.
##[error]Packer validate command failed. This could happen if task does not support packer version.
```
