### ISSUE TITLE
Allow environment variable pass in AzureContainerApps task

### ISSUE THREAD

**Issue by cilerler** [microsoft/azure-pipelines-tasks#17493]
*Type*: Feature

**Enter Task Name**: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureContainerAppsV0

## Issue Description

I would like to be able to pass environment variables.

## Expected

Please locate the `EXAMPLE` line below

```yaml
steps:
- task: microsoft-oryx.AzureContainerAppsRC.container-apps-deploy-pipelines-task.AzureContainerAppsRC@0
  displayName: 'Azure Container Apps Deploy (Release Candidate)'
  inputs:
    azureSubscription: '...'
    acrName: mycompany
    acrUsername: '$(ACR_USERNAME_SECRET)'
    acrPassword: '$(ACR_PASSWORD_SECRET)'
    imageToDeploy: 'mycompany.azurecr.io/mycompany.myproject.myrepo:$(Release.Artifacts._mycompany.myproject.myrepo.BuildNumber)'
    containerAppName: 'myrepo-integration'
    resourceGroup: Default
    containerAppEnvironment: 'myrepo-integration'
    runtimeStack: 'dotnetcore:7.0'
    targetPort: 80
    environmentVariables: 'EnvironmentName=integration;KEY2=VALUE2;KEY3=VALUE3' # <== EXAMPLE
```

**Comment by nnellanspdl** [comment]
All tasks support a top-level `env` property.  [source](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-task?view=azure-pipelines#common-task-properties)
```yaml
steps
- task: something
  env:
    KEY: value
    KEY: value
  inputs:
```
