### ISSUE TITLE
NodeTool cannot install Node.js binaries from an alternative mirror

### ISSUE THREAD

**Issue by trippingtarballs** [microsoft/azure-pipelines-tasks#17575]
**Type**: Feature
**Enter Task Name**: NodeTool  

## Issue Description

`https://nodejs.org/dist` is the default mirror from which Node.js can be installed. 

However, at work we use the Azure Pipeline from a closed (private) network and, consequently, access to `nodejs.org` is blocked for the execution context of our Azure Pipeline. We do have an internal mirror from which Node.js can be installed (using Artifactory).

Presently the [NodeTool Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-tool-v0?view=azure-pipelines) is hardcoded to use `nodejs.org`. This prevents me from being able to use NodeTool on my Azure Pipeline from the context of my closed network.

I would like to be able to install Node.js from a mirror when using NodeTool.

**Comment by Roman-Shchukin** [comment]
Hi @trippingtarballs thanks for contribution! Let us take a look.

**Comment by milapointe** [comment]
@Roman-Shchukin we are waiting on this issue too here, would be glad to have an ETA on when we can think to use it !

Thanks

**Comment by trippingtarballs** [comment]
#17500 has been merged 🥳  

@Roman-Shchukin / @ismayilov-ismayil, now that this PR is merged, please can you confirm if / how / when I can start using the new `nodejsMirror` input option with my `NodeTool@0` task in my ADO pipeline?

**Comment by trippingtarballs** [comment]
@Roman-Shchukin / @ismayilov-ismayil, please advise me how I can use `NodeTool@0.218.0`.  Do I need to wait for a release? When does NodeTool get released?

**Comment by trippingtarballs** [comment]
Good news, NodeTool at v0.218.0 has been released! 

![image](https://user-images.githubusercontent.com/2758507/230121565-dba285c8-c45c-403c-8503-98a71f04a8d1.png)

That means that #17500 is now available to all `NodeTool@0` tasks, and Node.js can be installed from a custom mirror:

```yaml
stages:
  - stage: Initialise
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              nodejsMirror: https://custom.registry.com/artifactory/gen-nodejs-dist/
              versionSpec: 16.17.0
            displayName: Install Node.js.

          - script: |
              npm install
            displayName: Install dependencies.
```

The following screenshot shows this working:

![image](https://user-images.githubusercontent.com/2758507/230127231-88e9124b-c7d5-4785-ae19-b93e5a14ed59.png)

⚠️ `nodejsMirror` is not yet [documented](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-tool-v0?view=azure-pipelines) as one of NodeTool's inputs, so this is a bit of "magic" API for now ⚠️
