### ISSUE TITLE
Kubernetes@1 task fails with "Endpoint auth data not present" error

### ISSUE THREAD

**Issue by zpdeering** [microsoft/azure-pipelines-tasks#17626]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes@1  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: JH-TIC/MULESOFT/azure-devops-mule-certs/45546

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: ubuntu 20.04, agent 2.213.2

## Issue Description

In the Kubernetes@1 task, I'm getting an error "Endpoint auth data not present" when using the Kubernetes Service Connection. My pipeline snippet is:
```
# Apply with Kubernetes
  - task: Kubernetes@1
    displayName: "Deploy certificate secret"
    condition: succeeded()
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'jh-tic-eaesb-dev-aks-01'
      namespace: 'cert'
      command: apply
      arguments: '-f tlssecret.yaml'
```
I've checked and that service connection exists and is shared with all pipelines.

### Task logs

[logs_45550.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10451165/logs_45550.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
Starting: Deploy certificate secret
==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.214.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-kubectl-tsg
==============================================================================
##[error]Endpoint auth data not present: 032a19d7-090b-47b5-b8c6-7ec1f3773839
Finishing: Deploy certificate secret
```
