### ISSUE TITLE
Gradle task cannot read from resources folder

### ISSUE THREAD

**Issue by timony** [microsoft/azure-pipelines-tasks#17665]
Im building Spring boot app using gradle. Integration tests (Spock) need to access code/src/resouces/docker-compose.yml file to prepare TestContainers container:

```
static DockerComposeContainer postgresContainer = new DockerComposeContainer(
        ResourceUtils.getFile("classpath:docker-compose.yml"))
```

The git file structure is:

```
- code
  - src
    - main
    - test
      - resources
        - docker-compose.yml
```
This is working fine on my local machine, but once I run it in Azure pipeline, it gives

**No such file or directory: '/__w/1/s/code/build/resources/test/docker-compose.yml'**

My pipeline yaml is like bellow. I use Ubuntu container with Java17 as I need to build with 17 but Azure's latest is 11 (maybe this plays any role in the error I get?)

trigger: none

```
stages:
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-22.04'
        container: gradle:7.6.0-jdk17
        variables:
          - name: JAVA_HOME_11_X64
            value: /opt/java/openjdk
        displayName: Test
        steps:
          - script: java --version
            displayName: Java version
          - script: |
              echo "Build reason is: $(Build.Reason)"
            displayName: Build reason
          - checkout: self
            clean: true
          - task: Gradle@2
            displayName: 'Gradle Build'
            enabled: True
            inputs:
              javaHomeSelection: 'path'
              jdkDirectory: '/opt/java/openjdk'
              wrapperScript: code/gradlew
              cwd: code
              tasks: clean build
              publishJUnitResults: true
              jdkVersionOption: 1.17
```
Thanks for help!

**Comment by DmitriiBobreshev** [comment]
Hi @timony, thank you for the question, could you please provide the pipeline log with debug flag? If you don't want to share logs in the GH issue, you can send them to me directly via e-mail at v-bobreshevd@microsoft.com

**Comment by timony** [comment]
I've solved it by "workarround" - I realied that I dont need to use the container with jdk17 that was causing the problem (could not access files on host machine of course)
The true is the Azure silently supports Jkd17 by directive: **jdkVersionOption: 1.17**

```
trigger: none

stages:
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-22.04'
        displayName: Test
        steps:
          - script: java --version
            displayName: Java version
          - script: |
              echo "Build reason is: $(Build.Reason)"
            displayName: Build reason
          - checkout: self
            clean: true
          - task: Gradle@2
            displayName: 'Gradle Build'
            enabled: True
            inputs:
              wrapperScript: server/code/gradlew
              cwd: server/code
              tasks: test
              publishJUnitResults: true
              jdkVersionOption: 1.17
```
