### ISSUE TITLE
Pipeline YAML validator on multistage checkout task broken

### ISSUE THREAD

**Issue by kOstovic** [microsoft/azure-pipelines-tasks#17689]
*Type*: Bug

**Pipeline YAML validator on multistage checkout task broken**

## Environment
- Server - Azure Pipelines (on private you can get organization name/project)

- Agent -Private: 
    
    - Ubuntu 20.04 OS, version 2.214.1

## Issue Description

checkout task breaks internal scheme validator
Create 2 stages with checkout task like in documentation:
```
steps:
  - checkout: git://project/repo-code@$(Build.SourceBranch) 
```
try to validate yaml syntax with Validate button - there is no validation response and page breaks with this errors in console

![image](https://user-images.githubusercontent.com/13186974/215757914-5cf77bad-6950-49d2-8c78-94f757994dfa.png)

try to save pipeline anyway and run it, error will be shown at the start of pipeline run:
"An item with the same key has already been added"

Delete any one of checkouts, everything works, validations is passed and pipeline works, which means multistage checkout if you want specific branch doesnt work and breaks Azure pipeline editor and pipeline itself, problem is in validator it self tho, not pipeline obviously, yaml syntax checker says everything is okay with yaml

**Comment by KonstantinTyukalov** [comment]
Hi @kOstovic, thanks for reporting!
To get around this behavior, I might suggest using the [repository](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines) definition:

```yaml
resources:
  repositories:
  - repository: SourceBranch
    type: git
    name: YourProject/YourRepo
    ref: ${{ variables['Build.SourceBranchName'] }} #https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-212-update#template-expressions-in-repository-resource-definition

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - checkout: SourceBranch

- stage: B
  jobs:
  - job: B1
    steps:
    - checkout: SourceBranch
```

If you have further questions about YAML validation, I would suggest to create a ticket on the [developer community](https://developercommunity.visualstudio.com/AzureDevOps) portal to get right eyes on it.
Thanks!
