### ISSUE TITLE
Unexpected error handling on copy files 

### ISSUE THREAD

**Issue by havrazO** [microsoft/azure-pipelines-tasks#17705]
## Required Information
Coping files to network Windows server machine 
Using Task configurations : 
```
        - task: CopyFiles@2
            displayName: Copy Files to $(TargetServer)
            inputs:
              sourceFolder: '$(Build.ArtifactStagingDirectory)/app1FilesAndFolders/'
              contents: '**'
              targetFolder: '$(TargetServerFolderPath)'
              OverWrite: true

```
If the TargetServerFolder have the same folder structure as in app1FilesAndFolders, this should be no problem as if the 
**OverWrite set to true.**
BUT if the agent service user have **no write permissions** on the target folder, the process throws the error 

**##[error]Unhandled: Unable to create directory '\\TargetServerFolderPath..\'. EEXIST: file already exists, mkdir** '\\TargetServerFolderPath..\'

which in this case should be 
**##[error]Unhandled: EPERM: operation not permitted, stat '\\TargetServerFolderPath..\'**

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: CopyFiles@2 Version 2.180.1

## Environment
- Server - Azure Pipelines 

- Agent - Hosted Azure Pipelines Agent
