### ISSUE TITLE
PublishCodeCoverageResults@2 fails when .Net Core 2.1 is not installed

### ISSUE THREAD

**Issue by stan-sz** [microsoft/azure-pipelines-tasks#17700]
When using the latest version in an agent that has .net6 and .net7 SDK installed this error is observed:

```
==============================================================================
Task         : Publish code coverage results
Description  : Publish any of the code coverage results from a build
Version      : 2.215.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
Found 1 result(s) matching pattern: D:\a\_work\_temp/Cobertura.xml
D:\a\_work\_temp\Cobertura.xml
"C:\hostedtoolcache\windows\dotnet\dotnet.exe" D:\a\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\2.215.0\node_modules\coveragepublisher\CoveragePublisher\CoveragePublisher.Console.dll "D:\a\_work\_temp\Cobertura.xml" --reportDirectory D:\a\_work\_temp\71b24c1a-5997-47df-a89a-df6e00a99de7
You must install or update
 .NET to run this application.

App: D:\a\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\2.215.0\node_modules\coveragepublisher\CoveragePublisher\CoveragePublisher.Console.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '2.1.0' (x64)
.NET location: C:\hostedtoolcache\windows\dotnet\

The following frameworks were found:
  6.0.5 at [C:\hostedtoolcache\windows\dotnet\shared
\Microsoft.NETCore.App]
  6.0.13 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]
  7.0.2 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by jakubch1** [comment]
Try to add to your console project file `runtimeconfig.template.json` with content:
```
{
  "rollForwardOnNoCandidateFx": 2
}
```

**Comment by vinayakmsft** [comment]
Please use the .net core task before Publish Code Coverage v2. We have added the same in the public documentation : https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines

**Comment by stan-sz** [comment]
@vinayakmsft can this requirement be removed with the suggestion from @jakubch1?

**Comment by vinayakmsft** [comment]
This task works correctly on using the .net core 2.1.x before. Please use the same.

**Comment by wilfriedb** [comment]
Why is this issue closed?  The .net core sdk 2.1.x requirement should be unnecessary, the V2 task  should run on higher versions without changing templates, like version 1.

**Comment by vinayakmsft** [comment]
That is 1 dependency for the V2 task. It is the .Net core 2.1.x. We will have to add this task in the pipeline before the V2 task. 
![image](https://user-images.githubusercontent.com/110326599/217220442-ec6dbf76-ce2f-4549-a1f2-a5f62b61483a.png)

**Comment by stan-sz** [comment]
@vinayakmsft have you tried the suggestion from @jakubch1 above?

**Comment by vinayakmsft** [comment]
Yes, created a PR to fix: https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/46

Once this https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/47/files completes, will merge that PR

**Comment by boppbo** [comment]
@vinayakmsft Any ETA for updating https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/coveragepublisher/make.json to use the new CoveragePublisher release?

**Comment by ChristopherHaws** [comment]
.NET Core 2.1 Runtime has been [EoL since Aug 2021](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)... This seems like a security vulnerability, since that runtime is not receiving security patches anymore. This issue should not be closed until the task has been fixed IMO.

**Comment by vinayakmsft** [comment]
Hi We have updated the .net core version of coveragepublisher to latest 7.0.x . It would start showing up post the deployments.

**Comment by ChristopherHaws** [comment]
@vinayakmsft Any idea when the deployment will take place? From what I can see, the PR to fix this issue was merged almost 2 months ago.

For anyone else running into this issue, I ended up using the following to temporarily fix the issue:

```yaml
# PublishCodeCoverageResults@2 requires v2.1.0 of .NET Core runtime still
# https://github.com/microsoft/azure-pipelines-tasks/issues/17700
- task: UseDotNet@2
  inputs:
    packageType: runtime
    version: 2.1.0
    installationPath: $(Agent.ToolsDirectory)/dotnet210

- task: PublishCodeCoverageResults@2
  displayName: publish test results
  env:
    # https://github.com/microsoft/azure-pipelines-tasks/issues/17700
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet210
  inputs:
    failIfCoverageEmpty: true
    summaryFileLocation: $(workingDirectory)/**/cobertura-coverage.xml

# Make sure to switch back to the correct version of .NET after publishing the results
- task: UseDotNet@2
  displayName: dotnet setup
  inputs:
    useGlobalJson: true
```

I was not able to get it working by only setting `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2`.
