### ISSUE TITLE
Xcode@5 - Provide multiple simulators to destinationSimulators parameter

### ISSUE THREAD

**Issue by cdw-abacai** [microsoft/azure-pipelines-tasks#17710]
**Question, Bug, or Feature?**
Type: Question

**Enter Task Name:** Xcode@5

## Environment
- Server - Azure Pipelines or TFS on-premises?
     - Azure Pipelines

- Agent - Hosted or Private: 
    Hosted

## Issue Description

We are currently looking at investigating how we can improve unit test execution time in Azure Pipelines and have sourced various articles across the web which reference the use of Parallel Distributed Testing with Xcode, in particular xcodebuild. However, one of the main stumbling blocks here is how we can provide multiple destination simulators to the Xcode task in Azure Pipelines. As referenced in the documentation [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/xcode-v5?view=azure-pipelines), the name of the `destinationSimulators` parameter suggests that multiple simulators can be provided, however the documentation is not clear enough on this.

I've attempted various combinations which look like the following:

_Provide multiple simulators via destinationSimulators parameter_
```
- task: Xcode@5
  inputs:
    actions: 'test'
    args: '-derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES'
    configuration: 'Debug Dev'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11, iPhone 12'
    scheme: 'AppDev'
    sdk: '14.2'
    xcWorkspacePath: 'MyApp.xcworkspace'
```

_Providing multiple destinations via args parameter_
```
- task: Xcode@5
  inputs:
    actions: 'test'
    args: '-derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES -destination "platform=iOS,name=iPhone 8"  -destination "platform=iOS,name=iPhone 8 Plus"'
    configuration: 'Debug Dev'
    destinationPlatformOption: 'iOS'
    scheme: 'AppDev'
    sdk: '14.2'
    xcWorkspacePath: 'MyApp.xcworkspace'
```

Is anyone able to provide guidance on how we can achieve the outcome of providing multiple destination simulators to this task?

**Comment by vmapetr** [comment]
Hi @cdw-abacai, thank you for your question!

Unfortunately, for now, `Xcode` task doesn't support the usage of multiple simulators in the `destinationSimulators` argument.

`destinationSimulators` here is used to simplify passing arguments to xcode - if the `destinationSimulators` argument is specified, the values that passed with this argument will be parsed and piped into the xcode build command with the `-destination` parameter.

So using the first approach:

```yaml
- task: Xcode@5
  inputs:
    actions: 'test'
    args: '-derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES'
    configuration: 'Debug Dev'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11, iPhone 12'
    scheme: 'AppDev'
    sdk: '14.2'
    xcWorkspacePath: 'MyApp.xcworkspace'
```
You get the following xcode build command:

```bash
/usr/bin/xcodebuild -sdk 14.2 \
                    -configuration Debug Dev \
                    -workspace MyApp.xcworkspace \
                    -scheme AppDev \
                    -destination platform=iOS Simulator,name=iPhone 11, iPhone 12 \ 
                    test \ 
                    -derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES
```

Which will lead to the following error:

```yaml
xcodebuild: error: unreadable input ' iPhone 12' at end of value for option 'Destination'
```
Please notice that if you use the `platform=iOS Simulator`, you can only use the single simulator with the `id`, `name`, and `os` keys.

In the second case:
```yaml
- task: Xcode@5
  inputs:
    actions: 'test'
    args: '-derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES -destination "platform=iOS,name=iPhone 8"  -destination "platform=iOS,name=iPhone 8 Plus"'
    configuration: 'Debug Dev'
    destinationPlatformOption: 'iOS'
    scheme: 'AppDev'
    sdk: '14.2'
    xcWorkspacePath: 'MyApp.xcworkspace'
```

If you use `destinationPlatformOption == iOS` without explicitly setting the `destinationSimulators`, default simulator `iPhone 7` will be used, and after that `-destination` arguments from `args` will be added, so it will look like this:

```bash
/usr/bin/xcodebuild -sdk 14.2 \
                    -configuration Debug Dev \
                    -workspace MyApp.xcworkspace \
                    -scheme AppDev \
                    -destination platform=iOS Simulator,name=iPhone 7 \
                    test \ 
                    -derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES \
                    -destination platform=iOS,name=iPhone 8 \
                    -destination platform=iOS,name=iPhone 8 Plus
```

However, you can pass the first simulator via the `destinationSimulators` argument and another(s) via `args`:

```yaml
- task: Xcode@5
  inputs:
    actions: 'test'
    args: '-derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES  -destination "platform=iOS Simulator,name=iPhone 12"'
    configuration: 'Debug Dev'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11'
    scheme: 'AppDev'
    sdk: '14.2'
```

So eventually it will look like this:
```bash
/usr/bin/xcodebuild -sdk 14.2 \
                    -configuration Debug Dev \
                    -workspace MyApp.xcworkspace \
                    -scheme AppDev \
                    -destination platform=iOS Simulator,name=iPhone 11 \
                    test \
                    -derivedDataPath Build/ -enableCodeCoverage YES -parallel-testing-enabled YES \
                    -destination platform=iOS Simulator,name=iPhone 12
```

You can use this approach as a workaround. 

Please feel free to open a request ticket about adding the support for multiple simulator targets in task arguments, if you think that we should add it in near future.
