### ISSUE TITLE
[Bug] Publish and download steps run outside container job 

### ISSUE THREAD

**Issue by SoftwareApe** [microsoft/azure-pipelines-tasks#17715]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishPipelineArtifact, DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines

## Issue Description

I'm trying to use container jobs as described here: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops.

To quote from the documentation (_emphasis_ mine):
>When you specify a container in your pipeline, the agent will first fetch and start the container. Then, _each step_ of the job _will run inside the container_.

And further
>If you need fine-grained control at the individual step level, [step targets](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops#step-target) allow you to choose container or host for each step.

Now this is an issue because the container job:
a) Sometimes mounts `$(Pipeline.Workspace)`, e.g. `-v /agent/_work/7:/__w/7`, but sometimes only subfolders, seemingly at random. So we can't even share files through the workspace consistently. So if I want to publish `$(Pipeline.Workspace)/some_file.tar.gz` it's not always possible. Because it may or may not be mounted.
b) If it's not mounted one can't use `-v $(Pipeline.Workspace):/workspace` because these variables don't work in the `options` part of the container resource yet (another bug if you ask me).
c) It doesn't match the description of container jobs, so it's clearly a bug. Please just run everything in the container job as stated. Otherwise this feature is useless.

### Task logs

I can't provide full logs here due to NDAs. When publishing an artifact in `$(Pipeline.Workspace)` the download and publish steps use the host workspace (e.g. `/agent/_work/7`), not the container workspace e.g. `/__w/7`. 

## Troubleshooting

Even setting the container as a resource and as a target of publish and download explicitly, e.g.

```yaml
resources:
  containers:
  - container: example_container
    image: ubuntu20.04
```

And then

```yaml
- publish: '$(Pipeline.Workspace)/example_logs.tar.gz'
  target:
    container: example_container
  artifact: example_logs
  displayName: Publish logs
```

the step is still executed in the host environment.
