### ISSUE TITLE
Is AzureContainerApps@V0 generally available?

### ISSUE THREAD

**Issue by jamesmcroft** [microsoft/azure-pipelines-tasks#17733]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureContainerApps@V0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines   

- Agent - Hosted 

## Issue Description

When looking into deploying Azure Container Apps via Azure Pipelines tasks, most articles and docs point to a Release Candidate version of a task which includes details of an out-of-the-box task within this repository (AzureContainerApps@V0). 

However, when you try to use this task based on the examples given in this repository in pipelines on Microsoft hosted agents, you get the following error with no additional logs from the build:

![image](https://user-images.githubusercontent.com/13505183/217762438-dd6d0de9-ecb2-4e12-8905-c900e3806940.png)

This is the task:

```yml
            - task: AzureContainerApps@V0
              inputs:
                azureSubscription: $(azureSubscription)
                acrName: $(acrName)
                containerAppName: ${{parameters.containerAppName}}
                resourceGroup: $(resourceGroup)
                imageToDeploy: "$(acrName).azurecr.io/${{parameters.containerAppName}}:$(Build.BuildId)"
```

Is this meant to be the case? 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
