### ISSUE TITLE
PublishCodeCoverageResults@2 fails to write report to reportDirectory

### ISSUE THREAD

**Issue by etkr** [microsoft/azure-pipelines-tasks#17756]
## Required Information

**Type**: Bug
**Task Name**: PublishCodeCoverageResults@2

## Environment
- Server: Azure Pipelines 
- Agent: MS hosted Ubuntu-22.04

## Issue Description

PublishCodeCoverageResults@2 produces an invalid command to the underlying program

Ran with the following template 

```yaml
steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'
  - task: PublishCodeCoverageResults@2
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
```

### Error logs

```shell
Starting: PublishCodeCoverageResults
==============================================================================
Task         : Publish code coverage results
Description  : Publish any of the code coverage results from a build
Version      : 2.215.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
CoveragePublisher.Console 1.0.0
Copyright (C) 2023 CoveragePublisher.Console

ERROR(S):
  Option 'reportDirectory 
/home/vsts/work/_temp/c2a6c08c-dd26-417e-925a-9a9502100a9e' is unknown.

  --reportDirectory    (Default: ) Path where html report will be generated.

  --sourceDirectory    (Default: ) List of source directories separated by ';'.

  --timeout            (Default: 120) Timeout for CoveragePublisher in seconds.

  --noTelemetry        (Default: false) Disable telemetry data collection.

  --help               Display this help screen.

  --version            Display version information.

  value pos. 0         Required. Set of coverage files to be published.


Found 2 result(s) matching pattern: /home/vsts/work/_temp/**/coverage.cobertura.xml
/home/vsts/work/_temp/595a46d5-239e-47eb-8b18-452278343573/coverage.cobertura.xml
/home/vsts/work/_temp/_fv-az363-480_2023-02-13_14_17_13/In/fv-az363-480/coverage.cobertura.xml
/opt/hostedtoolcache/dotnet/dotnet /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/2.215.0/node_modules/coveragepublisher/CoveragePublisher/CoveragePublisher.Console.dll "/home/vsts/work/_temp/595a46d5-239e-47eb-8b18-452278343573/coverage.cobertura.xml" "/home/vsts/work/_temp/_fv-az363-480_2023-02-13_14_17_13/In/fv-az363-480/coverage.cobertura.xml" --reportDirectory /home/vsts/work/_temp/c2a6c08c-dd26-417e-925a-9a9502100a9e
Finishing: PublishCodeCoverageResults

```

**Comment by basnijholt** [comment]
@etkr, I am also experiencing this issue. Did you find a workaround?

**Comment by alkofahi** [comment]
Me too! Here is the job:
```
- job: Combine_code_coverage_report
    dependsOn:
      - ExperimentationSystem_Tests
      - DataSystem_Build
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: DataSystemCoverage
          path: $(System.DefaultWorkingDirectory)/data_system/
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: ExpSystemCoverage
          path: $(System.DefaultWorkingDirectory)/experimentation_system/
      - task: UseDotNet@2
        inputs:
          version: "2.1.x"
      - task: PublishCodeCoverageResults@2
        inputs:
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/@(Cobertura|coverage).xml"
```

**Comment by JaccoRademaker** [comment]
Same here, task version 2.215.0 fails with the error mentioned above.
As a workaround I now use PublishCodeCoverageResults@1 again.

**Comment by TomONeill** [comment]
Ran into the exact same issue. Seems like it's time for a `@3`.
Why do we need to use a dotnet version that's end of life anyway?

**Comment by foxlollato** [comment]
Hi, everyone!
I did an workaround for this issue.
Im just bypassing the native task and running it as a CmdLine.
Notice the tasks UseDotnet@2 and PublishCodeCoverageResult@2 are nedded for download task dependencies.

`steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.x'
    
- task: Npm@1
  inputs:
    command: 'install'
    customCommand: 'Npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run coverage'
  displayName: 'Tests Running'
  continueOnError: true


- task: PublishCodeCoverageResults@2
  condition: eq('true', 'false') # THIS WILL NEVER RUN ONCE IS NEEDE TASK DECLARATION TO DOWNLOAD IT SOURCES
  inputs:
    summaryFileLocation: PATH/TO/YOUR/COVERAGE.xml
    
# here the magic happens
# CREATE A DIR TO USE IN reportDirectory parameter
# Run publish as bash command
- task: CmdLine@2
  displayName: Publish Code Coverage
  env: { 'SYSTEM_ACCESSTOKEN': $(System.AccessToken) }
  inputs:
    script: |
      mkdir /home/vsts/work/_temp/cobertura 
      /opt/hostedtoolcache/dotnet/dotnet `find /home/vsts/work/_tasks/ -name CoveragePublisher.Console.dll` "PATH/TO/YOUR/COVERAGE.xml" --reportDirectory /home/vsts/work/_temp/cobertura

**Comment by davidkarlsen** [comment]
> Ran into the exact same issue. Seems like it's time for a `@3`. Why do we need to use a dotnet version that's end of life anyway?

My though exactly - this whole thing is just a big facepalm. And why can't the mess be encapsulated instead of irritating all ADO users, after all it's not exactly rocket-science going on here...

**Comment by imWildCat** [comment]
Any updates on this?

**Comment by stan-sz** [comment]
For the net2.1 requirement, see #17700

**Comment by stavshamir** [comment]
I also ran into this issue, please update when possible.

**Comment by mateid** [comment]
Any ETA on this? How can this still broken since February 13? It's a basic thing people will try to do with their pipelines.

**Comment by dimangulov** [comment]
The same on my side

**Comment by mortware** [comment]
Also seeing this issue:
![image](https://user-images.githubusercontent.com/1643268/232149825-a8609aec-c667-49d5-9451-206fb4709740.png)

**Comment by freefreeP** [comment]
> Hi, everyone! I did an workaround for this issue. Im just bypassing the native task and running it as a CmdLine. Notice the tasks UseDotnet@2 and PublishCodeCoverageResult@2 are nedded to download dependencies.
> 
> ```
> steps:
> 
> - task: UseDotNet@2
>   inputs:
>     packageType: 'sdk'
>     version: '2.1.x'
>     
> - task: Npm@1
>   inputs:
>     command: 'install'
>     customCommand: 'Npm install'
> 
> - task: Npm@1
>   inputs:
>     command: 'custom'
>     customCommand: 'run coverage' #HERE YOU USE YOUR COVERAGE SCRIPT
>   displayName: 'Tests Running'
>   continueOnError: true
> 
> 
> - task: PublishCodeCoverageResults@2
>   condition: eq('true', 'false') # THIS WILL NEVER RUN ONCE TASK DECLARATION IS NEEDED TO DOWNLOAD IT SOURCES
>   inputs:
>     summaryFileLocation: PATH/TO/YOUR/COVERAGE.xml
>     
> # here the magic happens
> # CREATE A DIR TO USE IN reportDirectory parameter
> # Run publish as bash command
> - task: CmdLine@2
>   displayName: Publish Code Coverage
>   env: { 'SYSTEM_ACCESSTOKEN': $(System.AccessToken) } #access token is needed to upload report to azure pipeline tabs
>   inputs:
>     script: |
>       mkdir /home/vsts/work/_temp/cobertura 
>       /opt/hostedtoolcache/dotnet/dotnet `find /home/vsts/work/_tasks/ -name CoveragePublisher.Console.dll` "PATH/TO/YOUR/COVERAGE.xml" --reportDirectory /home/vsts/work/_temp/cobertura
> ```

You are amazing, works !!!

**Comment by stan-sz** [comment]
With #17700 there's no longer need to have the .Net 2.1 SDK installed

**Comment by ManuelTS** [comment]
> With #17700 there's no longer need to have the .Net 2.1 SDK installed

But its still in the documentation when I post this comment, so people will use it. See:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines

**Comment by ManuelTS** [comment]
> Hi, everyone! I did an workaround for this issue. Im just bypassing the native task and running it as a CmdLine. Notice the tasks UseDotnet@2 and PublishCodeCoverageResult@2 are nedded to download dependencies.
> 
> ```
> steps:
> 
> - task: UseDotNet@2
>   inputs:
>     packageType: 'sdk'
>     version: '2.1.x'
>     
> - task: Npm@1
>   inputs:
>     command: 'install'
>     customCommand: 'Npm install'
> 
> - task: Npm@1
>   inputs:
>     command: 'custom'
>     customCommand: 'run coverage' #HERE YOU USE YOUR COVERAGE SCRIPT
>   displayName: 'Tests Running'
>   continueOnError: true
> 
> 
> - task: PublishCodeCoverageResults@2
>   condition: eq('true', 'false') # THIS WILL NEVER RUN ONCE TASK DECLARATION IS NEEDED TO DOWNLOAD IT SOURCES
>   inputs:
>     summaryFileLocation: PATH/TO/YOUR/COVERAGE.xml
>     
> # here the magic happens
> # CREATE A DIR TO USE IN reportDirectory parameter
> # Run publish as bash command
> - task: CmdLine@2
>   displayName: Publish Code Coverage
>   env: { 'SYSTEM_ACCESSTOKEN': $(System.AccessToken) } #access token is needed to upload report to azure pipeline tabs
>   inputs:
>     script: |
>       mkdir /home/vsts/work/_temp/cobertura 
>       /opt/hostedtoolcache/dotnet/dotnet `find /home/vsts/work/_tasks/ -name CoveragePublisher.Console.dll` "PATH/TO/YOUR/COVERAGE.xml" --reportDirectory /home/vsts/work/_temp/cobertura
> ```

You are absolutely awesome, thanks literally a ton!

**Comment by rafaelbm** [comment]
@foxlollato awersome work there!

Do you know if CoveragePublisher.Console.dll accepts a summaryFileLocation that has file matching patterns?
For instance: "PATH/TO/YOUR/**/COVERAGE.xml"

**Comment by foxlollato** [comment]
@rafaelbm, i believe it won't work.
A trick is to create an intermediate directory named with the id of the current build, and You'll may use the $(Build.BuildId) variable to reference it in the task.
eg. "PATH/TO/YOUR/$(Build.BuildId)/COVERAGE.xml"

**Comment by miqm** [comment]
@rafaelbm - it will not work, I managed to workaround it by using a copyFiles step, but this requires splitting path into 2 variables:
```
  - task: CopyFiles@2
    displayName: "Copy coverage files"
    inputs:
      SourceFolder: "${{ parameters.summaryFilesFolder }}"
      Contents: "${{ parameters.summaryFilesPattern }}"
      TargetFolder: "$(Agent.TempDirectory)/coverage"

  - task: CmdLine@2
    displayName: Publish Code Coverage
    env: { "SYSTEM_ACCESSTOKEN": $(System.AccessToken) } #access token is needed to upload report to azure pipeline tabs
    inputs:
      script: |
        mkdir $(Agent.TempDirectory)/cobertura 
        /opt/hostedtoolcache/dotnet/dotnet `find /home/vsts/work/_tasks/ -name CoveragePublisher.Console.dll` `find $(Agent.TempDirectory)/coverage -type f` --reportDirectory "$(Agent.TempDirectory)/cobertura" --sourceDirectory "${{ parameters.pathToSources }}"
```

**Comment by Kaloszer** [comment]
So is this task actually working now or should I not waste time trying to get it to work 🗡️? Seems that something got updated somewhere and the solution that was presented earlier no longer works.

Seems that something is broken again...

```
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 2.1.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
      
      - task: PublishCodeCoverageResults@2
        condition: eq('true', 'false') # THIS WILL NEVER RUN, TASK DECLARATION IS NEEDED TO DOWNLOAD SOURCES
        inputs:
          summaryFileLocation: '$(Build.SourcesDirectory)/output/coverage.xml'

# Run publish as bash command - task is broken - https://github.com/microsoft/azure-pipelines-tasks/issues/13257
      - task: CmdLine@2
        displayName: Publish Code Coverage
        env: { 'SYSTEM_ACCESSTOKEN': $(System.AccessToken) }
        inputs:
          script: |
            mkdir /home/vsts/work/_temp/JaCoCo 
            /opt/hostedtoolcache/dotnet/dotnet `find /home/vsts/work/_tasks/ -name CoveragePublisher.Console.dll` '$(Build.SourcesDirectory)/output/coverage.xml' --reportDirectory /home/vsts/work/_temp/JaCoCo
      
```

It's worked flawlessly for the past few months but I get a framework mismatch now ( as if it does not respect that I stated to use 2.1.x earlier...'

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/hostedtoolcache/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.30 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
```

Tried to use UseDotNet@2 ver 2.x but no dice
```
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/hostedtoolcache/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.7 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
```

And of course if you try to use 3.1.x you get:

```
Starting: Publish Code Coverage
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/8d9f79c5-0d99-47ce-9fd3-d079a8dc37d8.sh
2023-05-25T07:09:14: Loading report '/home/vsts/work/1/s/output/coverage.xml' 1/1 in memory
2023-05-25T07:09:14: Preprocessing report
2023-05-25T07:09:14:   No source directories supplied for 'JaCoCo' coverage file
2023-05-25T07:09:14: Initiating parser for JaCoCo
2023-05-25T07:09:14: Current Assembly: Source/Private
2023-05-25T07:09:15: Current Assembly: Source/Public
2023-05-25T07:09:15: Finished parsing '/home/vsts/work/1/s/output/coverage.xml' 1/1
2023-05-25T07:09:15: Parsing of 1 files completed
2023-05-25T07:09:15: Starting merging result 1
2023-05-25T07:09:15: Finished merging result 1
##[error]Error occured while generating HTML report. Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken='. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Publishing file coverage data.
Publishing code coverage HTML report.
Uploading 0 files.
File upload succeed.
Published '/home/vsts/work/_temp/JaCoCo' as artifact 'Code Coverage Report_146935'.
Finishing: Publish Code Coverage
```

I don't think I'll be only one to say that this is getting irritating...
