### ISSUE TITLE
Can not foreach object in AzurePowerShell@5 (works in @4)

### ISSUE THREAD

**Issue by timpoth** [microsoft/azure-pipelines-tasks#17775]
We have a script where we want to pull an object from azure and foreach through it. EG
```
  $endpointobj = Get-AzCdnEndpoint -ResourceGroupName $rgname -ProfileName $cdnname
  foreach($endpoint in $endpointobj)
    {  write-host "Found Name: $($endpoint.Name)"  }
```

In powershell on my pc and in AzurePowerShell@4 this will output the CDN Endpoint name EG
Found Name: ExampleEndpoint

In AzurePowerShell@5 this doesnt work, i can not pull any details out of the object in foreach.
EG
Found Name: 

if i call $endpointobj it shows all the details as expected and calling $endpointobj.name will show the name(s) for each endpoint that came back but i dont understand why the behavior changed and the inconsistency with how powershell works onside of azure pipelines. using .gettype() and | GM both dump out the expected details. 

Script is called from a YAML pipeline
```
   - task: AzurePowerShell@4
      displayName: "testscript_SP4"
      inputs:
        ConnectedServiceNameARM: "BentleyConnect Dev"
        FailOnStandardError: true
        TargetAzurePs: LatestVersion
        ScriptType: FilePath
        ScriptPath: "test.ps1"

    - task: AzurePowerShell@5
      displayName: "testscript_PS5"
      inputs:
        ConnectedServiceNameARM: "BentleyConnect Dev"
        FailOnStandardError: true
        TargetAzurePs: LatestVersion
        ScriptType: FilePath
        ScriptPath: "test.ps1"

```
