### ISSUE TITLE
Using SDK 7.0.200, DotNetCoreCLI@2 "dotnet pack" causes NETSDK1194: The "--output" option isn't supported when building a solution.

### ISSUE THREAD

**Issue by derSchtefan** [microsoft/azure-pipelines-tasks#17773]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI

## Environment
- Server - Azure Pipelines:  GF.MS.DB build 95030

## Issue Description

When using DotNetCoreCLI@2 with `pack` as command, and a project that defines 
```xml
        <Content Include="Resources\xx" Pack="true" PackagePath="contentFiles/xxxx">
            <PackageCopyToOutput>true</PackageCopyToOutput>
        </Content>
```

* Using .NET SDK `7.0.102` (via `UseDotNet@2`) the build runs as expected
* Using .NET SDK `7.0.200` (via importing 7.x, since yesterday), the build throws an error: `Microsoft.NET.Sdk.Solution.targets(36,5): 
error NETSDK1194: The "--output" option isn't supported when building a solution.`

### Task logs

```
   1:2>Target "ValidateToolsVersions" in file "/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln.metaproj" from project "/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln" (entry point):
       Task "Error" skipped, due to false condition; ('$(MSBuildToolsVersion)' == '2.0' and ('$(ProjectToolsVersion)' != '2.0' and '$(ProjectToolsVersion)' != '')) was evaluated as ('Current' == '2.0' and ('' != '2.0' and '' != '')).
   1:2>Done building target "ValidateToolsVersions" in project "GF.MS.DB.Infrastructure.sln".
   1:2>Target "ValidateProjects" in file "/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln.metaproj" from project "/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln" (entry point):
   1:2>Done building target "ValidateProjects" in project "GF.MS.DB.Infrastructure.sln".
   1:2>Target "_CheckForSolutionLevelOutputPath" in file "/opt/hostedtoolcache/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets" from project "/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln" (target "pack" depends on it):
       Using "NETSdkError" task from assembly "/opt/hostedtoolcache/dotnet/sdk/7.0.200/Sdks/Microsoft.NET.Sdk/targets/../tools/net7.0/Microsoft.NET.Build.Tasks.dll".
       Task "NETSdkError"
   1:2>/opt/hostedtoolcache/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. [/home/vsts/work/1/s/GF.MS.DB.Infrastructure.sln]
       Done executing task "NETSdkError" -- FAILED.

```

**Comment by psiservices-dbrink** [comment]
I'm seeing a similar error.  It also looks like the DotNetCoreCLI@2 task is using a prerelease version of msbuild.

The pipeline specifically installs .NET 7.0.2.

```
Tool to install: .NET Core sdk version 7.0.x.
Found version 7.0.200 in channel 7.0 for user specified version spec: 7.0.x
```

The DotNetCoreCLI@2 is run with the following config

```
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: false
              projects: $(Build.SourcesDirectory)/mypath/MyProject.sln
              arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/MyProject --runtime win-x64 --no-self-contained'
```

On MSBuild version 17.4.1 --output is supported when compiling solutions.  All tasks running with DotNetCoreCLI@2 are logging a prerelease version of MSBuild

> MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
