### ISSUE TITLE
DockerCompose@0 mangles case sensitive registry name

### ISSUE THREAD

**Issue by lakeman** [microsoft/azure-pipelines-tasks#17783]
Pushing containers to a registry with additional image tags, causes the registry name to be converted to lower case, which may then fail to authenticate.

```
- task: DockerCompose@0
  displayName: Push Images
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscription: '$(CONNECTION)'
    azureContainerRegistry: CamelCaseName.azurecr.io
    dockerComposeFile: 'docker-compose.yml'
    action: Push services
    additionalImageTags: 711cee5
    includeLatestTag: true
```
Results in output;
```
/usr/bin/docker push CamelCaseName.azurecr.io/container
...
/usr/bin/docker push camelcasename.azurecr.io/container:711cee5
...
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```
