### ISSUE TITLE
Cannot use solution name for projects argument in DotNetCoreCLI@2 publish task

### ISSUE THREAD

**Issue by koljada** [microsoft/azure-pipelines-tasks#17847]
*Type*: Bug

**Task**: DotNetCoreCLI@2

**Command**: publish

## Environment
Azure Pipelines, hosted agent

## Issue Description

When executing `publish` command it's not possible to provide solution name as `projects`.
Why solution name works fine for `restore` and `build` but not for `publish`? I tried to find anything about it in [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines) but with no avail.

In my scenario I have multiple projects organized in several solutions. So in some pipeline I want to build and publish only projects within a specific solution. And it works with building but not with publishing. I tried to use `**/*.csproj` for projects param but of course it results in error because not all projects have been built in the `build` task.

I guess I can try to list all needed projects explicitly but that is just horrible.

My build and publish task definitions:

```
- task: DotNetCoreCLI@2
  displayName: 'Build projects'
  inputs:
    command: 'build'
    vstsFeed: $(nugetFeed)
    projects: $(solution)
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: 'publish'
    #projects: $(solution)
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
```

### Task logs

[log1.txt](https://github.com/microsoft/azure-pipelines-tasks/files/10851754/log1.txt)

### Error logs

When trying to use solution name: 
Command: `C:\Program Files\dotnet\dotnet.exe" publish D:\a\1\s\HomeSafe.CI-CD.sln --no-build --configuration Release --output D:\a\1\a\s`
Error: `##[error]Dotnet command failed with non-zero exit code on the following projects : [ 'D:\\a\\1\\s\\HomeSafe.CI-CD.sln' ]`

When trying to use  `**/*.csproj`:
Command: `C:\Program Files\dotnet\dotnet.exe" publish D:\a\1\s\InitNotResponseFunction.Tests\InitNotResponseFunction.Tests.csproj --no-build --configuration Release --output D:\a\1\a\InitNotResponseFunction.Tests`(InitNotResponseFunction.Tests exists in repo but is not included in target solution)
Error: `##[error]Unhandled: ENOENT: no such file or directory, scandir 'D:\a\1\a\InitNotResponseFunction.Tests'`

**Comment by ja0b** [comment]
It got it working like this, It seems like there is an issue with the _zipAfterPublish_ 👍 

```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

....
....
....

- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration) --property:PublishDir="$(Build.ArtifactStagingDirectory)" --no-restore --no-build'
    modifyOutputPath: false
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: 'Zip Artifact'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/trololo.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    ArtifactName: 'drop_trololo'
    publishLocation: 'Container'
```
