### ISSUE TITLE
HelmDeploy@0 Azure DevOps Task uninstall not working

### ISSUE THREAD

**Issue by PassionateDeveloper86** [microsoft/azure-pipelines-tasks#17861]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0

## Environment
- Server - Azure Pipelines or TFS on-premises? 
Version Azure DevOps Server 2022 (AzureDevOpsServer_20221122.1)

- Agent - Hosted or Private: 
Self Hosted - Windows

## Issue Description

I try to uninstall a helm chart with my azure devops pipeline with this task:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines

Sadly it is not working as documented.

My error is:

##[error]Error: "helm uninstall" requires at least 1 argument
Usage:  helm uninstall RELEASE_NAME [...] [flags]
helm.go:84: [debug] "helm uninstall" requires at least 1 argument

My input is:

       - task: HelmDeploy@0
         displayName: Helm Chart deinstallieren, wenn vorhanden
          inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: Azure Resource Manager
        azureResourceGroup: MyRG
        kubernetesCluster: MyAKS
        command: uninstall

So what i tried allready is using CharType and ChartName and ReleaseName - but still the same.

Installation is working fine with:

        - task: HelmDeploy@0
      displayName: Helm Chart installieren
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: Azure Resource Manager
        azureResourceGroup: MyRG
        kubernetesCluster: MyAKS
        command: install
        chartType: FilePath
        chartPath: infrastructure/helm/${{parameters.chart}}/${{parameters.version}}

**Comment by mvcampenhout** [comment]
I'm having the same issue unfortunately.

There seems to be a workaround though, you can specify the argument directly using the `arguments` property:
```
      - task: HelmDeploy@0
        displayName: "Helm uninstall ${{ parameters.chart }}"
        inputs:
          arguments: >
            ${{ parameters.chart }}
          command: uninstall
          namespace: ...
          (...)
```
