### ISSUE TITLE
AzureRmWebAppDeploymentV4: No package found with specified pattern: *.deploy.cmd

### ISSUE THREAD

**Issue by a510** [microsoft/azure-pipelines-tasks#17865]
*Type*: Question
**Enter Task Name**: AzureRmWebAppDeploymentV4

## Environment
- Server: Azure Pipelines
- Agent: Hosted

## Issue Description

I'm using this yaml to deploy an ASPNET Core WebAPI project to an Azure App Service.
``` yml
trigger:
- feature/new-template

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/My.Web.API.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/My.Web.API.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/my-app-service-name - Web Deploy.pubxml'
    appType: apiApp
    DeploymentType: webDeploy
    WebAppName: my-app-service-name
    packageForLinux: '$(Build.ArtifactStagingDirectory)'
    PublishProfilePassword: 'S1Yqfg...'
```
And I get this error:

`##[error]Error: No package found with specified pattern: D:\a\1\*.deploy.cmd<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job.`

![image](https://user-images.githubusercontent.com/17875291/222967541-2c648384-5154-41f1-8832-8a0b53532152.png)
