### ISSUE TITLE
[enhancement]: Clarify file input names for AzureResourceManagerTemplateDeployment task

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/azure-pipelines-tasks#17877]
### Task name

AzureResourceManagerTemplateDeployment

### Describe your feature request here

The inputs that don't have Link appended to the end go with `templateLocation: Linked artifact`. That is confusing. I think the word Link in the input names should be replaced with Url, as they pertain to `templateLocation: URL of the file`.

So I propose the [Syntax template found here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines#syntax), look like this:
```yaml
# ARM template deployment v3
# Deploy an Azure Resource Manager (ARM) template to all the deployment scopes.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
  # Template
    templateLocation: 'Linked artifact' # 'Linked artifact' | 'URL of the file'. Required. Template location. Default: Linked artifact.
    #csmFile: # string. Required when templateLocation = Linked artifact. Template. 
    #csmParametersFile: # string. Optional. Use when templateLocation = Linked artifact. Template parameters. 
    #csmFileUrl: # string. Required when templateLocation = URL of the file. Template link. 
    #csmParametersFileUrl: # string. Optional. Use when templateLocation = URL of the file. Template parameters link. 
    #overrideParameters: # string. Override template parameters. 
    deploymentMode: 'Incremental' # 'Incremental' | 'Complete' | 'Validation'. Required. Deployment mode. Default: Incremental.
```

I do wonder why these inputs are split. I'd imagine the code itself can treat `csmFile` as an URL when it's an URL, and as a file, when it is a file path.
