### ISSUE TITLE
[enhancement]: AzureFunctionApp package directory ignores the .funcignore values

### ISSUE THREAD

**Issue by mikejonestechno** [microsoft/azure-pipelines-tasks#17882]
### Task name

AzureFunctionApp

### Describe your feature request here

The task packages a directory but ignores the `.funcignore` file. If this file exists in the package directory, exclude those files similar to the azure core tools func cli command.

## Expected behaviour
When specifying a package directory, and the directory contains a `.funcignore` file then the package should exclude the file patterns specified in the `.funcignore` file (behave the same way as azure core tools `func publish` cli command).

## Actual
When specifying a package directory, the task packages and deploys all files in the directory, and does not respect the `.funcignore` file in the directory.

```
            - task: AzureFunctionApp@1
              inputs:
                azureSubscription: ${{ parameters.azureSubscriptionServiceConnection }} 
                appType: functionAppLinux
                appName: ${{ parameters.functionAppName }}
                package: '$(System.DefaultWorkingDirectory)'
                deploymentMethod: 'auto'
```
