### ISSUE TITLE
[Question]: Project file(s) matching the specified pattern were not found

### ISSUE THREAD

**Issue by samuelguesnier** [microsoft/azure-pipelines-tasks#18067]
### Task name

DotNetCoreCLI@2

### Task version

2.0.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Question

Here is my yaml:

```
    trigger:
    - main
    
    pool:
      vmImage: 'windows-latest'
    
    variables:
      solution: '**/WebApplication1.sln'
      project: '**/WebApplication1.csproj'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    
    steps:
    
    - task: NuGetToolInstaller@1
      name: 'NuGetToolInstaller'
      displayName: 'NuGet tool installer'
    
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '${solution}'
        feedsToUse: 'select'
        vstsFeed: '518d385e-cce7-4d9b-a805-fd5ec2b4f108'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '${solution}'
        arguments: '--configuration ${BuildConfiguration}' 
```

When the pipeline runs, I get a warning 

> Project file(s) matching the specified pattern were not found.

Here is my project structure:

[![project structure][1]][1]

  [1]: https://i.stack.imgur.com/n3wpz.png
