### ISSUE TITLE
[BUG]: PipAuthenticate@1 on private DevOps artifact feed uses old endpoint <org-name>.pkgs.visualstudio.com/...

### ISSUE THREAD

**Issue by GuillermoGarciaF** [microsoft/azure-pipelines-tasks#18076]
### Task name

PipAuthenticate@1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04.6

### Task log

```shell
- task: PipAuthenticate@1
    displayName: Authenticate <My-PyPI-Name>
    inputs:
      artifactFeeds: <My-PyPI-Name>
  - script: |
      echo "##[debug] $PIP_INDEX_URL"
    displayName: Setup poetry
```

### Relevant log output

```shell
Starting: Authenticate <My-PyPI-Name>
==============================================================================
Task         : Python pip authenticate
Description  : Authentication task for the pip client used for installing Python distributions
Version      : 1.218.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/pip-authenticate
==============================================================================
Successfully added auth for 1 internal feeds and 0 external endpoint.
Finishing: Authenticate <My-PyPI-Name>



Starting: Setup poetry
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[debug] https://build:***@<org-name>.pkgs.visualstudio.com/_packaging/<My-PyPI-Name>/pypi/simple
```

### Aditional info

```shell
The task PipAuthenticate@1 uses the old Azure DevOps Artifacts endpoint.
For pypi repositories:
- https://build:***@<org-name>.pkgs.visualstudio.com/_packaging/<My-PyPI-Name>/pypi/simple

where <org-name>, <My-PyPI-Name> correspond to the organization name and private package feed name.
As a consequence, PIP_INDEX_URL cannot be used in downstream tasks that assume the new Azure DevOps Artifacts endpoint, i.e.
- https://pkgs.dev.azure.com/<org-name>/_packaging/<My-PyPI-Name>/pypi/simple/


To be more specific: we use [poetry](https://python-poetry.org/) to manage and install python packages from a private Azure DevOps python package feed. It is configured to use the new Azure DevOps Artifacts endpoint and thus fails to authenticate against the private package feed causing 401 unauthorized error.

Please update the PipAuthenticate@1 to use the latest endpoint or provide an alternative.
Thank you
```

**Comment by GuillermoGarciaF** [comment]
Hello all, any updates on this topic?
Thank you very much!

**Comment by Garett601** [comment]
Hi @GuillermoGarciaF ,

Here is how we worked around this issue, it now works as expected:
(we also use poetry to manage dependancies and load a private package from Azure DevOps Artifacts Feed, so this should work...)
[partial yaml file contents]
```YAML
- task: PipAuthenticate@1
  displayName: 'Pip Authentication'
  inputs: 
    artifactFeeds: '<project_name_or_numbers>/<feed_name>'
    onlyAddExtraIndex: True

- script: |
    curl -sSL https://install.python-poetry.org | python3 -
    export PATH=$PATH:$HOME/.poetry/bin
    export PAT=$(echo "$PIP_EXTRA_INDEX_URL" | sed -n 's/.*build:\([^@]*\)@.*/\1/p')
    poetry config http-basic.<package_name_as_in_pyproject.toml> $PAT ""
    poetry install --no-root
  displayName: 'Install dependencies'
```
The `sed -n 's/.*build:\([^@]*\)@.*/\1/p'` command now only extracts the token, which fixed the issue with the updated expected format.

Hope this helps! It almost drove me insane!
