### ISSUE TITLE
[enhancement]: Use managed identity to deploy Function App instead of SasUrl

### ISSUE THREAD

**Issue by nicolasbailly1** [microsoft/azure-pipelines-tasks#18105]
### Task name

AzureFunctionApp

### Describe your feature request here

When an Azure Function App is connected to a storage account using identity, then "AzureWebJobsStorage__accountName" property is set up instead of "AzureWebJobsStorage".
When we try to deploy using the following YAML:
````
- task: AzureFunctionApp@2
            inputs:
              azureSubscription: 'SC-Data-Core-Test'
              appType: 'functionAppLinux'
              appName: '${{ variables.functionName }}'
              package: '$(Pipeline.Workspace)/resourceBuild/${{ variables.artifactName }}/Function$(resources.pipeline.resourceBuild.runID).zip'
````
Then we have the following error : Unable to find the storage account associated with the function app.
It's because "AzureWebJobsStorage" is necessary for the deployment.

According the documentation it's possible to deploy using "WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID": https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package
In this case, "AzureWebJobsStorage" wouldn't be necessary anymore.

Maybe with a dedicated property in this task, we would have the possibility to deploy with identity:
 ````
- task: AzureFunctionApp@2
            inputs:
              azureSubscription: 'SC-Data-Core-Test'
              appType: 'functionAppLinux'
              appName: '${{ variables.functionName }}'
              package: '$(Pipeline.Workspace)/resourceBuild/${{ variables.artifactName }}/Function$(resources.pipeline.resourceBuild.runID).zip'
              packageMode: identity # 'identity' | 'sasUrl'
````
