### ISSUE TITLE
[BUG]: Deployment strategy: 'Canary' is not supported for Environment scoped target.

### ISSUE THREAD

**Issue by m3talstorm** [microsoft/azure-pipelines-tasks#18354]
### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Unknown

### Task log

```shell
Deployment strategy: 'Canary' is not supported for Environment scoped target.
```

### Relevant log output

```shell
Deployment strategy: 'Canary' is not supported for Environment scoped target.
```

### Aditional info

```shell
Run the code from https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables

- deployment: A
  pool:
    vmImage: 'ubuntu-latest'
  environment: staging
  strategy:                  
    canary:      
      increments: [10,20]  # Creates multiple jobs, one for each increment. Output variable can be referenced with this.
      deploy:
        steps:
        - bash: echo "test"

```
```

**Comment by ivanduplenskikh** [comment]
Hi @m3talstorm thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by m3talstorm** [comment]
@ivanduplenskikh Is there a workaround/alternative that you know of? Or is it just having a task per increment and doing it 'manually'?

**Comment by boylec** [comment]
+1 (we are also on VMSS)

**Comment by JaydenMaalouf** [comment]
Also facing this bug. Tried without an environment but it complains that an environment is required for a deployment job type. Really not sure how to work around this.

None of the examples in documentation work. Tried MS hosted and self hosted agents too. Also tried deploying to a specific resource in the environment to no avail. 

Any help would be appreciated.

**Comment by ivanduplenskikh** [comment]
@m3talstorm @boylec @JaydenMaalouf sorry for the late response.
I have checked the canary strategy.
Here is a working example:
```yaml
jobs:
- deployment: 
  environment:
    name: A
    resourceType: kubernetes
  pool: 
    vmImage: 'ubuntu-latest'
  strategy:
    canary:
      increments: [10,20]  
      preDeploy:
        steps:
        - script: echo "initialize, cleanup...."
      deploy:
        steps:
        - script: echo "echo deploy updates..."
      on:
        failure: 
          steps: 
          - script: echo "clean-up, rollback..."
        success: 
          steps: 
          - script: echo "checks passed, notify..." 
```

If you have any questions about AzureDevOps or deployment strategies you can create a topic on [developercommunity](https://developercommunity.visualstudio.com/AzureDevOps) since this question does not apply to the task or agent repository.
