### ISSUE TITLE
[Question]:  Maven@4 task; how to override location where jacoco.xml is looked for?

### ISSUE THREAD

**Issue by djangofan** [microsoft/azure-pipelines-tasks#18563]
### Task name

Maven@4

### Task version

4.222.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

Current agent version: '3.220.5'  ????

### Operation system

Ubuntu    (version probably 17)

### Question

```shell
[Question]:  Maven@4 task; how to override location where `jacoco.xml` is looked for?

Here is the error at the end of my build:


Reading code coverage summary from '/agent/_work/1/s/target/site/jacoco/jacoco.xml'
##[warning]No coverage data found. Check the build errors/warnings for more details.
```

Ubuntu
Downloading task: SonarQubePrepare (5.15.0)
Downloading task: Maven (4.222.0)
Downloading task: PublishCodeCoverageResults (1.219.0)

My task is configured like so:

```
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          codeCoverageToolOption: 'JaCoCo'
          codeCoverageClassFilter: '+:com'
          codeCoverageClassFilesDirectories: 'target/classes,target/test-classes'
          codeCoverageSourceDirectories: 'src/main/java,src/test/java'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: default
          jdkArchitectureOption: x64
          mavenOptions: '-Xmx2048m $(MAVEN_OPTS) -DFN_APP_NAME=$(Build.Repository.Name)'
          mavenVersionOption: Default
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sqAnalysisEnabled: true
          #isJacocoCoverageReportXML: true
          sqMavenPluginVersionChoice: 'latest'
          goals: package
        displayName: 'Maven Build With SonarQube Scan'
```

My normal Maven build, outside of the pipeline , places the JaCoCo report at:

target/coverage-reports/jacoco/jacoco.xml

SO, how do I override in the Maven@4 task?   Do I need to bend the knee and change my pom.xml to place the report how IT wants it?

Just trying to publish JaCoCo results up to SonarQube:  that is my end goal.
```
