### ISSUE TITLE
[BUG]: Secure file variable cannot be consumed in downstream hooks

### ISSUE THREAD

**Issue by samolesen** [microsoft/azure-pipelines-tasks#18655]
### Task name

DownloadSecureFile

### Task version

1.200.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230418.1)

### Operation system

Windows 10

### Task log

```shell
Starting: Download secure file - test-secure-file
==============================================================================
Task         : Download secure file
Description  : Download a secure file to the agent machine
Version      : 1.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-secure-file
==============================================================================
Finishing: Download secure file - test-secure-file
```

### Relevant log output

```shell
/azp/_work/_temp/65e337e6-8a70-4d1e-893a-263f784ab1c9.sh: line 3: testSecureFile.secureFilePath: command not found
```

### Aditional info

A secure file is defined in a `preDeploy` hook is not available in any downstream life-cycle hooks, e.g. `deploy`.

The following example will fail because `testSecureFile.secureFilePath` isn't visible in `deploy`:

```YAML
strategy:
  runOnce:
    preDeploy:
      steps:
      - task: DownloadSecureFile@1
        displayName: 'Download secure file - test-secure-file'
        name: testSecureFile
        inputs:
          secureFile: 'test-secure-file.txt'
    deploy:
      steps:
      - task: CmdLine@2
        displayName: 'Use secure file'
        inputs:
          script: echo $(testSecureFile.secureFilePath)
```

Note that this is *technically* within specs, as the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-secure-file-v1?view=azure-pipelines) doesn't explicitly include life-cycle hooks:

> This task defines the following output variables, which you can consume in downstream **steps, jobs, and stages**.

I find the current behavior counter-intuitive, because variables can be consumed in downstream jobs but not across the downstream hooks *inside* a job.
