### ISSUE TITLE
[BUG]: AzureContainerApps@1 Ignoring Location option

### ISSUE THREAD

**Issue by dombarnes** [microsoft/azure-pipelines-tasks#18680]
### Task name

AzureContainerApps@1

### Task version

1.225.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04.2 LTS

### Task log

```shell
Starting: AzureContainerApps
==============================================================================
Task         : Azure Container Apps Deploy
Description  : An Azure DevOps Task to build and deploy Azure Container Apps.
Version      : 1.225.0
Author       : Microsoft Corporation
Help         : [Learn more about this task](http://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureContainerAppsV1/README.md)
==============================================================================
/usr/bin/az login --service-principal -u *** --password=*** --tenant XXXXXXX --allow-no-subscriptions
/usr/bin/az account set --subscription XXXXXXXX
/usr/bin/az config set extension.use_dynamic_install=yes_without_prompt
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
/usr/bin/az containerapp show -n <container-app-name> -g <resource-group> -o none
WARNING: The command requires the extension containerapp. It will be installed first.
WARNING: The installed extension 'containerapp' is in preview.
/usr/bin/az containerapp up -n <container-app-name> -g <resource-group> -i myacr.azurecr.io/myimage:dev --ingress external
ERROR: Location 'uk-west' is not currently supported. To get list of supported locations, run `az provider show -n Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations"`
```

### Relevant log output

```shell
ERROR: Location 'uk-west' is not currently supported. To get list of supported locations, run `az provider show -n Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations"`


Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az710-733'
Current agent version: '3.220.5'
Operating System
Ubuntu
22.04.2
LTS
Runner Image
Image: ubuntu-22.04
Version: 20230716.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230716.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230716.1
Runner Image Provisioner
2.0.238.1
Current image version: '20230716.1.0'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: AzureContainerApps (1.225.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```

### Aditional info

I am running this as part of a step in my CI template. However, it seems to be ignoring the location option, and as a result, giving me an error that it can't be run in UK West.
The command runs as expected when run on my local development machine adding the `-l uksouth` argument to the same command line:
`az containerapp up -n my-app-name -g my-resource-group -i myacr.azurecr.io/myimage:dev --ingress external -l uksouth`

azure-pipelines.yml
```
steps:
  - checkout: none
  - ${{ each site in parameters.containerAppNames }}:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'my-service-connection'
        imageToDeploy: 'my-acr.azurecr.io/$(dockerAppName):$(buildName)'
        location: 'uksouth'
        containerAppName: ${{ site }}  
        resourceGroup: 'my-resource-group'
        ingress: 'external'
        containerAppEnvironment: 'ttv-cae-01'
```
