### ISSUE TITLE
[BUG]: AzurePowerShell not disconnected at the end for future jobs

### ISSUE THREAD

**Issue by Mikebeem** [microsoft/azure-pipelines-tasks#18697]
### Task name

AzurePowerShell

### Task version

5.225.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022, Windows Server 2019 and Ubuntu 22.04

### Task log

```shell
Set-AzContext System.Collections.Hashtable
Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
*** Name     1ab*****-****-****-****-*********y9z AzureCloud 

....

##[debug]Importing function 'Update-PSModulePathForHostedAgentWithLatestModule'.
##[debug]Trying to disconnect from Azure and clear context at process scope
Finishing: AzurePowerShell
```

### Relevant log output

```shell
Log from next regular PowerShell task (task: PowerShell@2):

Get-AzContext
Id                    : 2cd*****-****-****-****-*********w8x
Type                  : ServicePrincipal
Tenants               : {1ab*****-****-****-****-*********y9z}
AccessToken           : 
Credential            : 
TenantMap             : {}
CertificateThumbprint :

Where Id equals the Service Principal Id from the Service Connection used in the previous task.
```

### Aditional info

When we use the AzurePowerShell task, the task tries to disconnect at the end of the task. If we run a future job on the same agent, the connection from the previous AzurePowerShell task can be reused.

We also had the following confusing situation: Team A used the AzurePowerShell task. Team B used an AzureCLI task in combination with scriptType: pscore. Because the AzureCLI task requires a Service Connection, we would expect this task always runs in that context. But if you use commands from the Azure Powershell modules, it still uses the available connection from the previous AzurePowerShell task. So AzureCLI commands are from the correct Service Connection, but Azure PowerShell commands don't.

You can use the following pipeline to reproduce.
You need to provide a valid Self-Hosted pool (replace PoolName) and a Service Connection to Azure (replace AzureServiceConnection). Make sure all jobs run on the same agent in the Agent Pool, this can be achieved with demands or if you have only 1 available agent: 
```YAML
pool:
  name: MyPool
  demands:
  - Agent.Name -equals {Name of an agent}
```

Pipeline to reproduce: 

```YAML
trigger: none

variables:
  - name: system.debug
    value: true

jobs:
- job: UseAzureSubscription
  pool: PoolName
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureServiceConnection'
      ScriptType: 'InlineScript'
      Inline: |
        "Run Get-AzContext"
        (Get-AzContext).Account
      azurePowerShellVersion: 'LatestVersion'
- job: GetAZContextFromPowerShell
  pool: PoolName
  dependsOn: UseAzureSubscription
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if((Get-InstalledModule -Name "Az.Accounts" -ErrorAction "SilentlyContinue").Count -eq 0){
          "Run Install-Module:"
          Install-Module Az.Accounts -Scope CurrentUser -Force
        }
        
        "Run Get-AzContext"
        (Get-AzContext).Account

- job: DisconnectAzAccount
  dependsOn: GetAZContextFromPowerShell
  pool: PoolName
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if((Get-InstalledModule -Name "Az.Accounts" -ErrorAction "SilentlyContinue").Count -eq 0){
          "Run Install-Module:"
          Install-Module Az.Accounts -Scope CurrentUser -Force
        }
        
        "Disconnect-AzAccount -ErrorAction Stop"
        Disconnect-AzAccount -ErrorAction Stop

        # After Disconnect we get the outcome we would expect in a regular Powershell task:
        "Run Get-AzContext"
        (Get-AzContext).Account

```
