### ISSUE TITLE
[Question]: I cant seem to access an stage variable that was extracted from a dependency stage into a DisplayName

### ISSUE THREAD

**Issue by ValKiriann** [microsoft/azure-pipelines-tasks#18753]
### Task name

AzureCLI@2

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Question

Hi, I have one pipeline that obtains the details of the project (projectName and projectVersion) in an early stage. 
Then, in another one, we import the value of the output of the task that obtains these variables to be used in the stage. 

If I use this value in a displayName parameter of a task, it resolves empty. However, then in the task I use it and it works. Is there something about the scopes that I am not fully understanding here? I am posting snippets of code to explain better the incident:

01-build.yaml
```shell
stages:
  - stage: build
    pool: $(poolName)
    displayName: Build
    jobs:
      - job: code_analysis
        displayName: Run code analysis
        continueOnError: false
        timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
        cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}
        steps:
          - checkout: self
            clean: false
          - template: /obtain-project-from-package-json.yaml
```
obtain-project-from-package-json.yaml
```
parameters:
- name: workingDirectory
  type: string
  default:

steps:
  - task: Bash@3
    displayName: 'Get project info from package.json'
    name: project_details
    inputs:
      targetType: 'inline'
      failOnStderr: true
      workingDirectory: ${{ parameters.workingDirectory }}
      script: |
        projectName=$(jq -r ".name" package.json)
        projectVersion=$(jq -r ".version" package.json)
        echo "projectName=${projectName}"
        echo "projectVersion=${projectVersion}"
        echo "##vso[task.setvariable variable=projectName;isOutput=false]$projectName"
        echo "##vso[task.setvariable variable=projectName;isOutput=true]$projectName"
        echo "##vso[task.setvariable variable=projectVersion;isOutput=false]$projectVersion"
        echo "##vso[task.setvariable variable=projectVersion;isOutput=true]$projectVersion"
    target:
      settableVariables:
        - projectName
        - projectVersion

```
04-deploy-snapshot.yaml (the template that contains the stage that uses the variables
```
stages:
  - stage: deploy
    pool: $(poolName)
    displayName: Deploy
    dependsOn:
      - build
    variables:
      projectName: $[stageDependencies.build.code_analysis.outputs['project_details.projectName']]
      projectVersion: $[stageDependencies.build.code_analysis.outputs['project_details.projectVersion']]
    condition: or(eq(dependencies.test.result, 'Canceled'), succeeded())
    jobs:
      - deployment: ${{ parameters.environment }}_deploy
        displayName: Deploy to ${{ parameters.environment }}
        environment: ${{ parameters.environment }}-app
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none # To prevent using an auto-download of build artifact: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts
                - checkout: none
                - template: /deploy-to-blob.yaml
                  parameters:
                    projectName: $(projectName)
                    projectVersion: $(projectVersion)
```
deploy-to-blob.yaml
```
parameters:
  - name: projectName
    type: string
    default: $(projectName)
  - name: projectVersion
    type: string
steps:
  - task: AzureCLI@2
    displayName: '${{ parameters.projectName }} - Deploy info dashboard file'
    continueOnError: false
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      failOnStderr: true
      inlineScript: |
        set -e

        echo "[DEBUG]: projectName: ${{ parameters.projectName }}"
        echo "[DEBUG]: projectName: ${{ parameters.projectVersion }}"
```

As a result, the displayName does not show the project name but the task print perfectly de echoes.
<img width="281" alt="Captura de pantalla 2023-08-02 a las 9 28 09" src="https://github.com/microsoft/azure-pipelines-tasks/assets/17276837/a18c0455-538d-453a-baf1-21f194950188">
<img width="225" alt="Captura de pantalla 2023-08-02 a las 9 28 24" src="https://github.com/microsoft/azure-pipelines-tasks/assets/17276837/fdead343-8b01-4edf-85e5-0bd2120f0d1d">
