### ISSUE TITLE
Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by RobBowman** [microsoft/azure-pipelines-tasks#18851]
### Task name

SqlAzureDacpacDeployment

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Question

```shell
I have the following devops task in my pipeline:


- task: SqlAzureDacpacDeployment@1
        inputs:
          azureSubscription: 'azureappsharedresources-tfssc-nonprod-dev-001'
          ServerName: $(sqlServerName).database.windows.net
          DatabaseName: 'sqldb-sms-router-dev-001'
          AuthenticationType: 'aadAuthenticationIntegrated'
          deployType: SqlTask
          SqlFile: './deploy/azure-pipelines/addContainedUsers.sql'
          SqlAdditionalArguments: '-UserName func-sms-router-dev-001 -DatabaseName sqldb-sms-router-dev-001'
```

The content of the addContainedUsers.sql file is:
```
:setvar UserName "func-sms-router-dev-001"
:setvar DatabaseName "sqldb-sms-router-dev-001"

USE [$(DatabaseName)];
GO
CREATE USER [$(UserName)] FROM EXTERNAL PROVIDER;
GO
EXEC sp_addrolemember 'db_datareader', '$(UserName)';
EXEC sp_addrolemember 'db_datawriter', '$(UserName)';
GO
```

When the pipeline runs, I get the following output:

```
Starting: SqlAzureDacpacDeployment
==============================================================================
Task         : Azure SQL Database deployment
Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
Version      : 1.225.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
==============================================================================
Added TLS 1.2 in session.
Temporary inline SQL file: C:\Users\VssAdministrator\AppData\Local\Temp\tmp631B.tmp
Invoke-Sqlcmd -connectionString "**********"  -Inputfile "C:\Users\VssAdministrator\AppData\Local\Temp\tmp631B.tmp" 
Sql file: D:\a\1\s\deploy\azure-pipelines\addContainedUsers.sql
Invoke-Sqlcmd -connectionString "**********"  -Inputfile "D:\a\1\s\deploy\azure-pipelines\addContainedUsers.sql" -UserName func-sms-router-dev-001 -DatabaseName sqldb-sms-router-dev-001
##[error]Parameter set cannot be resolved using the specified named parameters.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
Finishing: SqlAzureDacpacDeployment
```

I guess I have the format of the variables wrong?
```

**Comment by RobBowman** [comment]
I eventually got this to work. See below for 4 attempts, last on worked:

```
- task: SqlAzureDacpacDeployment@1
        inputs:
          azureSubscription: 'azureappsharedresources-tfssc-nonprod-dev-001'
          ServerName: $(sqlServerName).database.windows.net
          DatabaseName: 'sqldb-sms-router-dev-001'
          AuthenticationType: 'aadAuthenticationIntegrated'
          deployType: SqlTask
          SqlFile: './deploy/azure-pipelines/addContainedUsers.sql'
          # SqlAdditionalArguments: '-UserName func-sms-router-dev-001 -DatabaseName sqldb-sms-router-dev-001'
          # SqlAdditionalArguments: '/v:UserName=func-sms-router-dev-001 /v:DatabaseName=sqldb-sms-router-dev-001'
          # SqlAdditionalArguments: 'UserName=func-sms-router-dev-001 DatabaseName=sqldb-sms-router-dev-001'
          SqlAdditionalArguments: '-Variable UserName=func-sms-router-dev-001, DatabaseName=sqldb-sms-router-dev-001'
```
