### ISSUE TITLE
[BUG]: KubernetesManifest@0: Not supplying an action returns an unclear error message

### ISSUE THREAD

**Issue by LFSb** [microsoft/azure-pipelines-tasks#18914]
### Task name

KubernetesManifest

### Task version

0.226.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Task log

```shell
Starting: Patch deployment for nginx
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.226.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-k8s-manifest-tsg
==============================================================================
==============================================================================
			Kubectl Client Version: v1.28.0
			Kubectl Server Version: v1.25.6
==============================================================================
##[error]EISDIR: illegal operation on a directory, read
Finishing: Patch deployment for nginx
```

### Relevant log output

```shell
##[error]EISDIR: illegal operation on a directory, read
```

### Aditional info

When a user does not supply an 'action' as an input to this task, instead of receiving a clear error message of what the user is doing wrong, in some cases an unclear error message relating to file operations is returned instead. 

I'm guessing this has to do with the default action of this task being 'deploy', and the error probably relates to the manifest that it's trying to look up in the filesystem of the agent, which is not provided (in the case where a user wanted to patch a resource, for example).

Example pipeline that will cause this to fail:

```yaml
---
name: kubernetes-manifest-bug-report
trigger:
  branches:
    include:
      - master

variables:
  - name: K8SSERVICECONNECTION
    value: REDACTED
  - name: NAMESPACE
    value: REDACTED

jobs:
  - job: deployManifest
    displayName: "Deploy the manifest to the default namespace"
    steps:
    - task: KubernetesManifest@0
      displayName: "Create deployment for nginx"
      inputs:
        action: deploy
        kubernetesServiceConnection: $(K8SSERVICECONNECTION)
        manifests: ./k8s/deployment.yml # https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/controllers/nginx-deployment.yaml
        namespace: $(NAMESPACE)
    - task: KubernetesManifest@0
      displayName: "Patch deployment for nginx"
      inputs:
        actions: patch # action is not supplied correctly here 
        kubernetesServiceConnection: $(K8SSERVICECONNECTION)
        kind: deployment
        resourceToPatch: name
        name: 'nginx-deployment'
        namespace: $(NAMESPACE)
        mergeStrategy: strategic
        patch: '{"spec": {"replicas": 2 }}'
    - task: KubernetesManifest@0
      displayName: "Delete deployment"
      inputs:
        action: 'delete'
        kubernetesServiceConnection: $(K8SSERVICECONNECTION)
        arguments: 'deployment nginx-deployment'
        namespace: $(NAMESPACE)

```

Not a huge issue, but it can lead you down quite a rabbithole if you don't know where to look.
```
