### ISSUE TITLE
[enhancement]: showing block/branch coverage % in azure code coverage summary

### ISSUE THREAD

**Issue by offtopic** [microsoft/azure-pipelines-tasks#18938]
### Task name

PublishCodeCoverageResults@2

### Describe your feature request here

In Visual Studio we have block coverage besides the line coverage (the line coverage is not very valueable, because lambda expressions are covered, even if they are not executed - coverage is way too high)

Here a short test for line vs block coverage:
<img width="1503" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/3337241/e149d610-b53c-4511-a6cb-acace9f9b484">

Is it possible to include the block coverage also in the build summery as shown below?
<img width="461" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/3337241/5db8f72d-8468-4b1a-a755-ac4e5e8fef8b">

We use following task to create the report:
```
task: PublishCodeCoverageResults@2
    displayName: Publish coverage per file
    #condition: and(succeeded(), eq('${{ parameters.perModule }}', 'false'))
    inputs:
      pathToSources: '$(Build.Repository.LocalPath)\src'
      summaryFileLocation: |
        $(targetFolder)\..\config\CodeCoverage.xml
```

The CodeCoverager.xml is manually created for integration tests executed against an iisexpress instance:

There is a branch-rate in the Coverage.xml (is this equal to block-coverage?)
`<coverage line-rate="***" branch-rate="***" complexity="***" version="1.9" timestamp="1694407373" lines-covered="***" lines-valid="***" branches-covered="***" branches-valid="***">`

dotnet coverage collect "c:\Program Files\IIS Express\iisexpress.exe" /site:"IntegrationTests" /apppool:"Clr4IntegratedAppPool" /config:"****\applicationhost.config" --output .\CodeCoverage.xml --output-format cobertura --settings ".\CodeCoverage.config" --log-level Info --log-file .\coverage.log

coverage.config does not inculde any special settings besides

```
<UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
<AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
<CollectFromChildProcesses>True</CollectFromChildProcesses>
<CollectAspDotNet>True</CollectAspDotNet>

```
^^ Also not quite sure if this is required (but not related to my question :)
