### ISSUE TITLE
[Question]: DotNetCoreCLI@2 test command cannot find dotnet framework installed by UseDotNet@2 task

### ISSUE THREAD

**Issue by mslukebo** [microsoft/azure-pipelines-tasks#18945]
### Task name

DotNetCoreCLI@2

### Task version

2.221.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Question

My pipeline contains the following YAML:

```yaml
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: $(Build.DotNetCoreVersion)
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '(PATH_TO_MY_SLN)'
    verbosityRestore: $(Debug.NuGetVerbosityRestore)
    includeNugetOrg: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '(PATH_TO_MY_SLN)'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '(PATH_TO_MY_SLN)'
    arguments: '-c Release'
    noBuild: true
```

We specify a `Build.DotNetCoreVersion` pipeline variable for when we need to build servicing branches that used an older version of .NET.

When I specify `Build.DotNetCoreVersion` as `3.1.x`, I observe:

1. .NET SDK version `3.1.426` correctly installs
2. The restore and build tasks succeed
3. The test task fails due to missing dotnet framework

Logs for `UseDotNet@2` task:

```
Starting: Use DotNet
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.228.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 3.1.x.
Found version 3.1.426 in channel 3.1 for user specified version spec: 3.1.x
Version 3.1.426 was not found in cache.
Getting URL to download .NET Core sdk version: 3.1.426.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/18f0e7dd-c821-49b5-9fb1-f161611b7712/5b96d5b15f5f0565adeb42e52667bd08/dotnet-sdk-3.1.426-win-x64.zip
Extracting downloaded package D:\a\_temp\3bc4c152-3f38-4dce-af45-1313d4e8726b.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\3bc4c152-3f38-4dce-af45-1313d4e8726b', 'D:\a\_temp\aa12')"
Successfully installed .NET Core sdk version 3.1.426.
Creating global tool path and pre-pending to PATH.
Finishing: Use DotNet
```

Relevant logs from when trying to run tests:

```
Testhost process for source(s) '[REDACTED]' exited with error: You must install or update .NET to run this application.
App: C:\Users\VssAdministrator\.nuget\packages\microsoft.testplatform.testhost\16.5.0\lib\netcoreapp2.1\testhost.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
.NET location: C:\Program Files\dotnet\
The following frameworks were found:
  6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.21 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.
```

**Comment by agabet** [comment]
Hi,

I had a similar issue for launching tests with .net core 3.1, using the `installationPath `parameter solved it.

```YAML
  - task: UseDotNet@2
    displayName: ".NET Core 3.1.x"
    inputs:
      version: "3.1.x"
      performMultiLevelLookup: true
      installationPath: 'C:\Program Files\dotnet\'
```
