### ISSUE TITLE
[Question]: How to specify both a parameter file and filelink in AzureRmWebAppDeployment@4

### ISSUE THREAD

**Issue by bartvdbraak** [microsoft/azure-pipelines-tasks#18969]
### Task name

AzureRmWebAppDeployment@4

### Task version

4.0.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Question

Hello everyone,

I hope you're doing well. I'm currently facing a challenge with the AzureRmWebAppDeployment@4 task and could use some assistance.

### Objective:
I aim to deploy a bicep template by combining a parameter file from the locally checked out repository and another sourced from a URL.

### CLI Approach:
I've successfully done this via the Azure Command Line Interface, as shown below:

```YAML
- task: AzureCLI@2
  inputs:
    azureResourceManagerConnection: "$(azureServiceConnectionId)"
    azureSubscription: "$(subscriptionId)"
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      az deployment group create \
        --name "$(deploymentName)" \
        --resource-group "$(resourceGroup)"
        --location "$(location)" \
        --template-file "main.bicep" \
        --parameters "main.params.json" \
        --parameters "https://example.blob.core.windows.net/extra.params.json"
```

### Challenge with AzureResourceManagerTemplateDeployment@4:

However, when I try to replicate this using the AzureResourceManagerTemplateDeployment@4 task as below, it doesn't provide the expected outcome.

```yaml
- task: AzureResourceManagerTemplateDeployment@4
  inputs:
    azureResourceManagerConnection: "$(azureServiceConnectionId)"
    subscriptionId: "$(subscriptionId)"
    deploymentName: "$(deploymentName)"
    resourceGroupName: "$(resourceGroup)"
    location: "$(location)"
    csmFile: "main.bicep"
    csmParametersFile: "main.params.json"
    csmParametersFileLink: "https://example.blob.core.windows.net/extra.params.json"
```

Has anyone encountered a similar issue or have any insights into how I can achieve my desired functionality using `AzureResourceManagerTemplateDeployment@4`?

Thank you in advance for your help and time!
