### ISSUE TITLE
[enhancement]: Consider caching `.azure-devops` cache folder

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#19007]
### Task name

AzureCLI

### Describe your feature request here

Whenever Azure CLI invokes and `az devops` task, it retrieves the `OPTIONS /_api/` and `GET /_api/ResourceAreas` and then caches it. The time to fetch these varies greatly.

The AzureCLI task could cache the data in most cases, since the resource areas and supported APIs rarely change in any meaningful way.

Adding:

```
- task: Cache@2
      inputs:
        key: '".az-devops"'
        path: 'C:\Users\VssAdministrator\.azure-devops'

    - pwsh: |
        (dir C:\Users\VssAdministrator\.azure-devops\python-sdk\cache\*.json) | %{$_.LastWriteTime = Get-Date} 
```

to the pipeline shaves off a couple of precious seconds.

Consider calling `HEAD` instead to see when the data was last updated instead of relying on the age of the files on disk.
