### ISSUE TITLE
[enhancement]: Bun Task

### ISSUE THREAD

**Issue by Jarred-Sumner** [microsoft/azure-pipelines-tasks#19073]
### Task name

Bun

### Describe your feature request here

People are asking for a [Bun](https://bun.sh) Task for Azure DevOps/Azure Pipelines: https://github.com/oven-sh/bun/issues/5917.

Is that something you would be interested in? I imagine it would work similarly to the Node one (though Linux only initially)

**Comment by v-mohithgc** [comment]
Hi @Jarred-Sumner , it is suggested to implement a task extension and publish it on the marketplace. 
Here is the doc that provides basic info about the development process for tasks and extensions - https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

Also, this doc that explains extension manifests - https://learn.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops
And also here is the tfs-cli repo and extensions readme which is also required for development and testing process: https://github.com/microsoft/tfs-cli

**Comment by NateRadebaugh** [comment]
@v-mohithgc  did this get implemented? I don't see this in the docs or marketplace anywhere.

Right now the best I've seen is to manually install bun via bash/curl but I don't love this for security reasons, and I also end up needing to use absolute path to bun since it doesn't seem to be included in the PATH with the install this way.

```yml
- task: Bash@3
  displayName: "Install bun.js"
  inputs:
    targetType: 'inline'
    script: 'curl -fsSL https://bun.sh/install | bash'
```

```yml
- task: Bash@3
  displayName: "Output bun.js version"
  inputs:
    targetType: 'inline'
    script: '~/.bun/bin/bun --version'
```
