### ISSUE TITLE
[enhancement]: suppress/format output for HelmDeploy@0

### ISSUE THREAD

**Issue by TobyTheHutt** [microsoft/azure-pipelines-tasks#19107]
### Task name

Add outputFormat option to HelmDeploy@0 

### Describe your feature request here

Before I execute my Helm charts, I want to be able to run them in a dry-run with the additional `--dry-run` argument. 

My Task looks something like this:
``` yaml
- task: HelmDeploy@0
  name: 'DryRunDeploysomeapp'
  displayName: 'Dry-Run someapp'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'fooEndpoint'
    kubernetesCluster: 'fooCluster'
    command: 'upgrade'
    chartType: FilePath
    chartPath: helm-charts/someapp
    releaseName: someapp
    namespace: someproject-test
    install: true
    arguments: --dry-run
```

However, this outputs all my Kubernetes objects, including sensitive configurations. This is a currently known issue in the Helm project:  https://github.com/helm/helm/issues/7275 

### Request
What I'd like would be something similar as was already implemented in the `Kubernetes@1` task with the `outputFormat` option, so I can suppress the output of my dry-run altogether.
The option could also be combined with similar output formats as the `Kubernetes@1` task, which would enhance its usability.
