### ISSUE TITLE
[BUG]: Unable to deploy to an App Service with an Azure Service Connection bound to Management Group

### ISSUE THREAD

**Issue by mgrosperrin** [microsoft/azure-pipelines-tasks#19112]
### Task name

AzureRmWebAppDeployment

### Task version

4

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

N/A

### Task log

```shell
Starting: Deploy the web application
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.229.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
Got service connection details for Azure App Service:'***'
##[error]Error: 'subscriptionId' cannot be null.
Finishing: Deploy the web application
```

### Relevant log output

```shell
##[error]Error: 'subscriptionId' cannot be null.
```

### Aditional info

```shell
When using an Azure service connection linked to a Management Group, we could specify an optional subscription Id to avoid this error
```

**Comment by mgrosperrin** [comment]
Hi,
Any news on this?

**Comment by mgrosperrin** [comment]
Hi,
I know there is no activity for a long time on this bug, but it is not a reason to close: it should be a reason to work on it...

**Comment by mgrosperrin** [comment]
Hi,
I know there is no activity for a long time on this bug, but it is not a reason to close: it should be a reason to work on it...

**Comment by mgrosperrin** [comment]
Hi,
I know there is no activity for a long time on this bug, but it is not a reason to close: it should be a reason to work on it...

**Comment by mgrosperrin** [comment]
Hi,
I know there is no activity for a long time on this bug, but it is not a reason to close: it should be a reason to work on it...

**Comment by Tni04** [comment]
For those facing this error recently: the root cause is that Management Group-scoped service connections do not natively provide a subscriptionId to the task library, which many official tasks (like AzureWebApp@1) strictly require.

While we wait for a native fix from Microsoft, you can unblock your pipeline by manually injecting the missing metadata into the task's environment. The task library looks for a specific environment variable pattern: ENDPOINT_DATA_<CONNECTION_GUID>_SUBSCRIPTIONID.

The Workaround:

Add the env: block to your task as shown below:

```YAML
- task: AzureWebApp@1 # Or AzureFunctionApp@1, etc.
  inputs:
    azureSubscription: 'Your-MG-Connection-Name'
    appName: 'your-app'
    # ... other inputs
  env:
    # Manual injection of the subscription ID
    # Replace <GUID> with your Service Connection ID (found in the URL)
    ENDPOINT_DATA_00000000-0000-0000-0000-000000000000_SUBSCRIPTIONID: 'your-target-subscription-id'
How to get the IDs:
```

Service Connection GUID: Go to your Service Connection settings in Azure DevOps. The ID is the GUID at the end of the URL (e.g., resourceId=...).

I've posted a full technical deep-dive and source code analysis on why this happens (referencing the azure-pipelines-task-lib source) in this comment: https://github.com/microsoft/azure-pipelines-tasks/issues/13779#issuecomment-4080480560.

Hopefully, this helps anyone stuck on this in 2026!
