### ISSUE TITLE
Support recent JDK versions in Gradle tasks

### ISSUE THREAD

**Issue by donalmurtagh** [microsoft/azure-pipelines-tasks#19125]
### Task names

Gradle@2, Gradle@3

### Describe your feature request here

According to the docs for [Gradle@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/gradle-v2?view=azure-pipelines) and [Gradle@3](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/gradle-v3?view=azure-pipelines), the most recent JDK version that is supported is v17. To confirm this, I tried changing my task's `jdkVersionOption` to 1.21, but it failed with the following error message

> Error: Failed to find the specified JDK version. Please ensure the specified JDK version is installed on the agent and the environment variable 'JAVA_HOME_21_X64' exists and is set to the location of a corresponding JDK or use the [Java Tool Installer](https://go.microsoft.com/fwlink/?linkid=875287) task to install the desired JDK.

```yaml
  - task: Gradle@2
    displayName: 'Run checks and tests'
    inputs:
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      tasks: 'check jacocoTestCoverageVerification jacocoTestReport'
```

I also tried using using `Gradle@3` instead of `Gradle@2` but it failed with the same error message

**Comment by donalmurtagh** [comment]
I was able to use JDK 21 by adding some steps (before the Gradle task) to install it myself

```yaml
  - bash: 'wget https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse -O jdk-21_linux-x64_bin.tar.gz'
    displayName: 'Download JDK 21'

  - task: JavaToolInstaller@0
    displayName: 'Install JDK 21'
    inputs:
      versionSpec: 21
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: '$(build.sourcesdirectory)/jdk-21_linux-x64_bin.tar.gz'
      jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk21'

  - task: Gradle@3
    displayName: 'Run checks and tests'
    inputs:
      jdkVersionOption: '1.21'
      tasks: 'check jacocoTestCoverageVerification jacocoTestReport'
      options: '--stacktrace --info'
```

To use the Oracle JDK instead of OpenJDK, see [this StackOverflow answer](https://stackoverflow.com/a/77305812/2648).
