### ISSUE TITLE
[Question]: Several tasks prepend values in PATH, which causing me issues (Kubernetes and Python)

### ISSUE THREAD

**Issue by SylvainLem** [microsoft/azure-pipelines-tasks#19182]
### Task name

Kubernetes & UsePythonVersion

### Task version

1.227.0 (Kube) & 0.229.0 (Python)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Question

Hello,

I have a pipeline that does some tasks in Python, then connect to an Azure Kubernetes Service, then interact with it through an other Python script.
But both tasks `Kubernetes@1` and `UsePythonVersion@0` prepend values into %PATH%, which causing me issues

If I'm using `UsePythonVersion@0` first then `Kubernetes@1 (login)`, I end up with my python messed up because `Kubernetes@1` prepends `/usr/bin/` to `%PATH%` and unfortunately, there is a python in that folder...

I could reshuffle the tasks in my pipeline, but it feels like a patch. What do you recommend?

Here is a minimal example to reproduce the issue:
```
trigger:
- None

pool:
  vmImage: ubuntu-latest

steps:
  
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    versionSpec: 3.9

- bash: |
    which python
    python --version
  displayName: 'Python path'

- task: Kubernetes@1
  displayName: 'Kubectl login'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'some_subscription_endpoint'
    azureResourceGroup: 'some_resource_group'
    kubernetesCluster: 'some_cluster_name'
    command: login

- bash: |
    which python
    python --version
  displayName: 'Python path'
```

 My output from bash commands are :
- /opt/hostedtoolcache/Python/3.9.18/x64/bin/python 
  Python 3.9.18
- /usr/bin/python
  Python 3.10.12
