### ISSUE TITLE
[BUG]: [UsePythonVersion] fails when it needs to install a python version which is not already on tools cache

### ISSUE THREAD

**Issue by poojashahms** [microsoft/azure-pipelines-tasks#19255]
### Task name

UsePythonVersion@0

### Task version

0

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

1. Ubuntu linux 5.15.0-1045-azure
2. MAC mini 14.1 Darwin ARM64

### Task log

```shell
Starting: [NEW] Use Python 3.11
==============================================================================
Task         : Use Python version
Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
Version      : 0.230.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
##[warning]You should provide GitHub token if you want to download a python release. Otherwise you may hit the GitHub anonymous download limit.
Downloading: https://github.com/actions/python-versions/releases/download/3.11.6-6388688740/python-3.11.6-linux-20.04-x64.tar.gz
Extracting archive
/usr/bin/tar xC /mnt/vss/_work/_temp/a6a7bfd8-8b72-483e-8e18-4fe23960b389 -f /mnt/vss/_work/_temp/python-3.11.6-linux-20.04-x64.tar.gz
/usr/bin/bash ./setup.sh
Check if Python hostedtoolcache folder exist...
Creating Python hostedtoolcache folder...
Create Python 3.11.6 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
./python: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory
##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: The process '/usr/bin/bash' failed with exit code 127
##[error]Version spec 3.11 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /mnt/vss/_work/_tool:
```

2. And similarly it's trying to use "sudo" for installing on `Darwin MAC mini` and hence failing. 
<img width="1164" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/125377350/0f049c44-5f3f-439b-952e-540125f15127">

### Relevant log output

shell
Python 3.11 should be installed and used.
As per https://stackoverflow.com/a/56296998 `libpython3.x-dev` as well needs to be installed or added on the path, after the unzip/untar step or as part of setup.sh execution

Both of these are remote machine in CI and the task fails within itself, what prevention or setup at the time of retry we can do to fix our side until this is fixed at the task level itself?

### Aditional info
If this is because of these agent's are self-hosted then as per the [wiki](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines#prerequisites), even download should not have worked if so. 

Also even after the task fails, I can see the ToolsCache has got the folder structure as mentioned in the [doc](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines#how-can-i-configure-a-self-hosted-agent-to-use-this-task)
Still, the task retry denies with not found in toolsCache 
so how do I make it work for a self-hosted agent? 
<img width="845" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/125377350/3fdfeddf-4e56-4fa1-a581-b0b0b3799489">
<img width="452" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/125377350/84caf48d-dcbc-45aa-9599-b63db74f9a53">

We are seeing successfull download but failure during installation. 

_No response_

**Comment by Alaeeala** [comment]
Hi! I am having the same problem. any idea how long such a change normally take (or could take)? 1 year? one month? one week? Thanks a lot!

**Comment by vmapetr** [comment]
Hi @poojashahms, thank you for reporting!

As mentioned in the documentation, the `UsePythonVersion` is guaranteed to work out of the box only on hosted agents, however, it can also work on self-hosted machines in case the agent architecture matches with specific binary on `arch` and `platform` fields from the [versions-manifest](https://github.com/actions/python-versions/blob/main/versions-manifest.json).
The task detects the platform version using the `lsb_release` or tries to check the content of `VERSION_ID` from `/etc/os-release` if the previous option is unavailable on Linux systems, uses `sw_vers -productVersion` to get the platform version on Darwin platforms, that's why the download is working on `Ubuntu linux 5.15.0-1045-azure` - the task detect the system as `Ubuntu-20.04`, and tries to use the published [Python 3.11.6](https://github.com/actions/python-versions/blob/e642abaef814f4d4a6bfe1741f814e08dbbc2484/versions-manifest.json#L745C3-L745C3)
```
      {
        "filename": "python-3.11.6-linux-20.04-x64.tar.gz",
        "arch": "x64",
        "platform": "linux",
        "platform_version": "20.04",
        "download_url": "https://github.com/actions/python-versions/releases/download/3.11.6-6388688740/python-3.11.6-linux-20.04-x64.tar.gz"
      },
```
The problem is that published binaries were built on hosted `Ubuntu-20.04` specifically for hosted `Ubuntu-20.04` machines and the main difference here is the path to Python shared libs. 

The Linux error mentioned in the description:
```
./python: error while loading shared libraries: libpython3.11.so.1.0
```
is happening while executing the latest stages of `setup.sh` from the downloaded package
```
./python -m ensurepip
./python -m pip install --ignore-installed pip --disable-pip-version-check --no-warn-script-location --root-user-action=ignore
```
most likely caused because Python try to use the shared libraries from the incorrect location. The binaries were built using the `/opt/hostedtoolcache/Python/$VERSION/$ARCH` as the default location, so they will try to use the shared libs from the same path.

**Just to be sure - could you please confirm that you set up the custom `AGENT_TOOLSDIRECTORY` environment variable, and what path did you use?**

In case the path differs from the default path used on the Hosted machines (`/opt/hostedtoolcache/*` for Linux, and `/Users/runner/hostedtoolcache/*` for MacOS) additional tweaks may be required:

Could you please try to update the `LD_LIBRARY_PATH` environment variable on your self-hosted machine so it will point to the location where the installed Python lib will be located, like `Python/3.11.6/x64/lib/`
You can use the following bash script, before the execution of the `UsePythonVersion` task:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/vss/_work/_tool/Python/3.11.6/x64/lib/
```

**Comment by vmapetr** [comment]
Hi @Alaeeala! The problem here is related to the Python Toolcache specifics on the self-hosted machines, and in this repo, we only maintain tasks that use the packages from the Toolcache - the task itself is working as expected, but the failure happens during the package installer execution - https://github.com/actions/python-versions/blob/main/installers/nix-setup-template.sh. We can provide a workaround, but unfortunately, we cannot provide an ETA for the updates in the mentioned repo (https://github.com/actions/python-versions), since this is outside of our area.
You can open a ticket on the https://github.com/actions/runner-images repo, in case you believe that current toolcache behavior on self-hosted machines should be reworked.

**Comment by Alaeeala** [comment]
@vmapetr , very fast, direct and clear answers. Awesome, I will try the work around and set the LD_LIBRARY_PATH. Thanks a lot!

**Comment by vmapetr** [comment]
@Alaeeala glad that I can help!

You can simply set the pipeline environment variable named `LD_LIBRARY_PATH` in the UI editor with the following value
```
:{TOOLCACHE_PATH}/Python/{VERSION}/x64/lib/
```
Or add the following bash task in your YAML template:
```
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:{TOOLCACHE_PATH}/Python/{VERSION}/x64/lib/"
```
Where the `TOOLCACHE_PATH` is the custom toolcache path, and `VERSION` is the required Python version used in the `UsePythonVersion` task. The complete path should look like this `:/mnt/vss/_work/_tool/Python/3.11.6/x64/lib/` for example.

**Comment by vmapetr** [comment]
@poojashahms could you please use the mentioned workaround?

**Comment by vmapetr** [comment]
I'm going to close this issue, since the Toolcache packages behavior is outside of our area, please use the mentioned workaround to resolve the Python issue, and free to reopen the ticket if you have additional questions.

**Comment by francbartoli** [comment]
Sorry @vmapetr, I'm facing this specific issue with Azure DevOps even after I applied the workaround in the YAML template of the pipeline

**Comment by FrancescoSaverioZuppichini** [comment]
> Sorry @vmapetr, I'm facing this specific issue with Azure DevOps even after I applied the workaround in the YAML template of the pipeline

Same here, this is my yml

```yml
      - job: deploy_function_app
        displayName: Deploy Function App
        pool:
          name: ccoe-aks-linux-agent
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:{TOOLCACHE_PATH}/Python/{VERSION}/x64/lib/"
          - task: UsePythonVersion@0
            displayName: "Set Python version to 3.11"
            inputs:
              versionSpec: "3.11.8"
              githubToken: <MY_TOKEN>
              architecture: "x64"
          - bash: |
              if [ -f extensions.csproj ]
              then
                  dotnet build extensions.csproj --output ./bin
              fi
              pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
            workingDirectory: $(functionAppWorkingDirectory)
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(functionAppWorkingDirectory)"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
              artifactName: "drop"
          - task: AzureFunctionApp@2
            inputs:
              azureSubscription: app-ai-devops-knowledgebot-dev-001
              appType: functionAppLinux
              appName: $(functionAppName)
              package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
              deploymentMethod: "auto"
```
Output from the self hosted agent

![Screenshot 2024-03-28 at 11 25 16](https://github.com/microsoft/azure-pipelines-tasks/assets/15908060/5a5eacb1-8396-4e54-b94e-b8b0b0a8488e)

Thanks a lot

**Comment by sardilal** [comment]
> > Sorry @vmapetr, I'm facing this specific issue with Azure DevOps even after I applied the workaround in the YAML template of the pipeline
> 
> Same here, this is my yml
> 
> ```yaml
>       - job: deploy_function_app
>         displayName: Deploy Function App
>         pool:
>           name: ccoe-aks-linux-agent
>         steps:
>           - task: Bash@3
>             inputs:
>               targetType: "inline"
>               script: |
>                 echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:{TOOLCACHE_PATH}/Python/{VERSION}/x64/lib/"
>           - task: UsePythonVersion@0
>             displayName: "Set Python version to 3.11"
>             inputs:
>               versionSpec: "3.11.8"
>               githubToken: <MY_TOKEN>
>               architecture: "x64"
>           - bash: |
>               if [ -f extensions.csproj ]
>               then
>                   dotnet build extensions.csproj --output ./bin
>               fi
>               pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
>             workingDirectory: $(functionAppWorkingDirectory)
>           - task: ArchiveFiles@2
>             displayName: "Archive files"
>             inputs:
>               rootFolderOrFile: "$(functionAppWorkingDirectory)"
>               includeRootFolder: false
>               archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
>           - task: PublishBuildArtifacts@1
>             inputs:
>               PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
>               artifactName: "drop"
>           - task: AzureFunctionApp@2
>             inputs:
>               azureSubscription: app-ai-devops-knowledgebot-dev-001
>               appType: functionAppLinux
>               appName: $(functionAppName)
>               package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
>               deploymentMethod: "auto"
> ```
> 
> Output from the self hosted agent
> 
> ![Screenshot 2024-03-28 at 11 25 16](https://private-user-images.githubusercontent.com/15908060/317690106-5a5eacb1-8396-4e54-b94e-b8b0b0a8488e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NjE0ODEsIm5iZiI6MTcxMTY2MTE4MSwicGF0aCI6Ii8xNTkwODA2MC8zMTc2OTAxMDYtNWE1ZWFjYjEtODM5Ni00ZTU0LWI5NGUtYjhiMGIwYTg0ODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDIxMjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMzJlYTgyY2M3YTNmMjlmNzQ0ZGVjZmFkMGQxNTNlNTljYzBiMWI2M2EwNzE0NGNkMjI3NWFjNjQxNjE3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PeRpSeLoK9jLIgEOs1JUwtaWjpY0NVNxgv-TXFjFM0)
> 
> Thanks a lot

You need to specify your toolcache path. In your case, it should be `azp/_work/_tool `
Thus, your Bash task's yaml should look like this:

```yaml
- task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:azp/_work/_tool/Python/3.11.8/x64/lib/"
```
