### ISSUE TITLE
[BUG]: Azure Web App deploy task changed behavior, does not work

### ISSUE THREAD

**Issue by solita-jhaakana** [microsoft/azure-pipelines-tasks#19279]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureWebApp

### Task version

1.230.1

### Issue Description

Task changed behavior between versions 1.227.0 -> 1.230.1.

I have the following definition;

```
- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureServiceConnection)
    appType: 'webAppLinux'
    appName: $(webAppName)
    package: 'backend/AppBackend/bin/Release/net7.0/linux-x64/publish'
  displayName: 'Deploy backend'
  retryCountOnTaskFailure: 40

```
Before 15.11.2023 (version 1.227.0) this has worked well with the following log:

```
Got service connection details for Azure App Service:'wapp-redacted-dev'
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at https://wapp-redacted-dev.scm.azurewebsites.net/api/deployments/e596f984-8693-47de-953d-8fa86ce44a40/log
Successfully deployed web package to App Service.

```
After automatic update to 1.230.1, the task started to try to deploy from a commit (not ZIP) and fails:
```

Got service connection details for Azure App Service:'wapp-redacted-dev'
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id 'fad9daca-a'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
...
Error: EACCES: permission denied, write
An error has occurred during web site deployment.

```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Linux

### Relevant log output

```shell
Got service connection details for Azure App Service:'wapp-redacted-dev'
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id 'fad9daca-a'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
...
Error: EACCES: permission denied, write
An error has occurred during web site deployment.

```
```


### Full task logs with system.debug enabled

No

### Repro steps

_No response_
