### ISSUE TITLE
[Question]: CACHE_RESTORED value when running Cache@2

### ISSUE THREAD

**Issue by markwalsh-liverpool** [microsoft/azure-pipelines-tasks#19290]
### Task name

Cache

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-22.04

### Question

I am currently a Cache@2 task to attempt to cache my Nuget packages so I don't have to run a DotnetRestore command.  The CACHE_RESTORED property is being set to "inexact" is there any documentation around this? Currently I am always restoring even though my lock files do not change at all:

```
      - task: Cache@2
        displayName: Cache
        inputs:
          key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
          restoreKeys: |
            nuget | "$(Agent.OS)"
            nuget
          path: '$(NUGET_PACKAGES)'
          cacheHitVar: 'CACHE_RESTORED'
      - powershell: |
          $MyVariable = "$(CACHE_RESTORED)"
          Write-Host "Contents of CACHE_RESTORED: $MyVariable"
        displayName: 'Display Variable Contents'
      - task: DotNetCoreCLI@2
        condition: ne(variables.CACHE_RESTORED, 'true')
        displayName: 'DotNet Restore'
        inputs:
          command: restore
          restoreArguments: -r $(runtimeIdentifier)
          projects: $(solution)
          feedsToUse: 'config'
          nugetConfigPath: 'src/nuget.config'
          verbosityRestore: Normal
```
