### ISSUE TITLE
runtimeStack NODE and npm dependencies succeeds silently with no trace, when node_modules are missing resulting in a failed deployment

### ISSUE THREAD

**Issue by noontz** [microsoft/azure-pipelines-tasks#19313]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Task version

@1 and @2

### Issue Description

Hi

I had an issue when upgrading from azure-functions v3 to v4 node.js programming model, where my AzureFunctionApp tasks succeeded with no clue on anything wrong, _but all functions where suddenly missing on the running function app on Azure_, as in a breaking change. It took me some time, before I realized that I was missing an (sudo) npm install command in the pipeline to deploy the @azure/functions dependency needed for v4. My project has no other external dependencies, hence working with v3 without the npm install command in the pipeline.

**It should be trivial for the AzureFunctionApp task to check package.json for dependencies, fail the task and log the error if the node_modules folder is missing ( when needed as per package.json )**

Cheers

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

```shell
The problem is that there is no error message ;)..
```

### Full task logs with system.debug enabled

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/7408674/ca9109d8-9a80-4ce7-9de0-5b339898a4aa)

### Repro steps

```yml
Create an azure functions node project with external dependencies
Create a yml pipeline for deployment without the (sudo) npm install command
Use AzureFunctionApp task for deployment

 - task: AzureFunctionApp@2
    displayName: 'Deploying to api to proxy on production'
    condition: eq(variables['Build.SourceBranchName'], 'main')
    inputs:
      azureSubscription: ##
      resourceGroupName: ##
      appName: ##    
      appType: functionApp    
      package: $(Agent.BuildDirectory)/src/functions
      deploymentMethod: runFromPackage
      runtimeStack: 'NODE|18'
```
