### ISSUE TITLE
[BUG]: AndroidSigning@2 default args does not seem to work and should be changed

### ISSUE THREAD

**Issue by markitovtr1** [microsoft/azure-pipelines-tasks#19384]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AndroidSigning

### Task version

2

### Issue Description

I created a build pipeline for my react native app and everything seemed to work fine. After publishing my signed aab to pipeline, trying to upload it to Play Console with Google generated key resulted in an wrong signature error. After talking with Google support, I tried verifying signed file with jarsigner and it resulted in an error:

```sh
jarsigner -verify -certs -verbose app-release.aab
```
> jarsigner: java.lang.SecurityException: invalid SHA-256 signature file digest for base/res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png

I tried verification with jarsigner from OpenJDK 17 and 21. I installed JDK 17 in my pipeline with `JavaToolInstaller@0` to sign.

How I set my task in my YAML pipeline:
```yaml
      - task: AndroidSigning@2
        displayName: Sign App Bundle
        inputs:
          apkFiles: android/app/build/outputs/bundle/release/app-release.aab
          jarsignerKeyPassword: $(androidKeyStorePassword)
          jarsignerKeystoreFile: ${{ parameters.keyStoreFile }}
          jarsignerKeystorePassword: $(androidKeyStorePassword)
          jarsignerKeystoreAlias: app
          zipalign: true
```

Settings `jarsignerArguments: '-verbose -sigalg SHA256withRSA -digestalg SHA-256'` made jarsigner verification work.

I suggest changing default arguments to something that works out of the box, as this seems a misconfiguration bug

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-22.04

### Relevant log output

```shell
Sign task finishes successfully
```

### Full task logs with system.debug enabled

Sign task finishes successfully

### Repro steps

```yml
Just use default task and then try verifying signed file with jarsigner -verify
```
