### ISSUE TITLE
[BUG]: KubernetesManifest@v0 and v1 do not update container image when registry/repository do not match

### ISSUE THREAD

**Issue by cristianrgreco** [microsoft/azure-pipelines-tasks#19393]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

KubernetesManifest

### Task version

v0 and v1

### Issue Description

I have the following example Kubernetes manifest:

```yaml
      containers:
          image: registry1.azurecr.io/repository1:latest
```

I have configured this DevOps task to update the container image:

```yaml
      - task: KubernetesManifest@0
        inputs:
          action: deploy
          containers: |
            registry2.azurecr.io/repository2:${{parameters.version}}
          manifests: |
            $(System.DefaultWorkingDirectory)/manifest.yaml
```

**Expected**: The container image is updated to `registry2.azurecr.io/repository2:${{parameters.version}}`.

**Actual**: The container image is not updated. No warnings or errors logged.

I've found the code which is responsible, it's here: https://github.com/microsoft/azure-pipelines-tasks/blob/v232/Tasks/KubernetesManifestV1/src/utils/KubernetesObjectUtility.ts#L339-L363

See that it will only update the image if the registry/repository match. I don't know what the reasoning is (we assume it's because the manifests/containers are both lists and could not be in-order), but if it's expected, please update the `containers` part of the task documentation to say this. 

This took several hours to figure out why the container image was not updating.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Relevant log output

```shell
N/A
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
