### ISSUE TITLE
[BUG]: TwineAuthenticateV1 produces incorrect path for windows

### ISSUE THREAD

**Issue by aeb-dev** [microsoft/azure-pipelines-tasks#19425]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

TwineAuthenticateV1

### Task version

V1

### Issue Description

TwineAuthenticateV1 produces incorrect path for windows. It is missing \ on the hard drive part

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
for echo the following is printed `D:a_temptwineAuthenticateIDxXp3.pypirc`
for cat the following error is printed: `cat: 'D:a_temptwineAuthenticateIDxXp3.pypirc': No such file or directory
```

### Repro steps

```yml
strategy:
  matrix:
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: Theorem/Theorem_Feed
    displayName: "Twine Authenticate"
  - bash: |
      echo $(PYPIRC_PATH)
      cat $(PYPIRC_PATH)
    displayName: "Cat PYPIRC"
```
