### ISSUE TITLE
[enhancement]: dynamically retrieving template files

### ISSUE THREAD

**Issue by basvandriel** [microsoft/azure-pipelines-tasks#19480]
### Describe your feature request here

Hi,

I have a use case where it is needed to first create a certain pipeline and only then refer to it in a template expression. My question is, is this already supported or isn't this something that would work?

Take the following code example.

```yaml
stages:
  - stage: A
    jobs:
    - job: Tryout
      steps:
      - task: AzureCLI@2
        displayName: '...'
        inputs:
          azureSubscription: ...
          failOnStandardError: false
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            cat > ./pipeline.yml <<EOF
            steps:
              - script: echo hi
            EOF    
      - publish: ./pipeline.yml
        artifact: pipeline
  - stage: B
    dependsOn: A
    jobs:
    - job: Tryout
      steps:
      - download: current
        artifact: pipeline
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Output "##vso[task.setvariable variable=filePath]\"$(Pipeline.Workspace)\pipeline\pipeline.yml\""
      - template: $(variables.filePath)
``` 

I would expect that when `$(Pipeline.Workspace)\pipeline\pipeline.yml` is created, it would run the template.
