### ISSUE TITLE
[BUG]: AzureFileCopy@5 cleanup fails in GetJobResults with "failed to parse user input due to error: cannot use wildcards in the path section of the URL..."

### ISSUE THREAD

**Issue by fowie** [microsoft/azure-pipelines-tasks#19522]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Task version

 5.234.0

### Issue Description

The task began to fail today with the error message:
failed to parse user input due to error: 
`cannot use wildcards in the path section of the URL except in trailing "/*". If you wish to use * in your URL, manually encode it to %2A`
We only have a trailing slash in SourcePath in the command definition, but from my inspection, it looks like it's failing because the blob storage URL has 5 asterisks appended to the end.  Those asterisks are not something I've input into the task, and they aren't part of the UUID, as you can see from earlier in the log

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Relevant log output

```shell
2024-02-08T20:33:01.1792738Z ##[debug][Azure Call]Creating container: 99c69625-ee4a-45f7-86a0-11bcfc92588b in storage account: 3dtmbinarystorage
2024-02-08T20:33:02.7981716Z ##[debug][Azure Call]Created container: 99c69625-ee4a-45f7-86a0-11bcfc92588b successfully in storage account: 3dtmbinarystorage
...
contact me directly @microsoft for full log if necessary
...
2024-02-08T20:33:28.4016542Z VERBOSE: Exporting function 'New-PSWorkflowSession'.
2024-02-08T20:33:28.4033884Z VERBOSE: Exporting alias 'nwsn'.
2024-02-08T20:33:29.0328279Z ##[debug]JobId: '2', JobState: 'running', ComputerName: '$(WSUSVMFQDN)'
2024-02-08T20:33:29.0352474Z ================================================ $(WSUSVMFQDN) ================================================
2024-02-08T20:33:29.1798996Z ##[command]& 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoLogo -NoProfile -NonInteractive 
2024-02-08T20:33:29.1800960Z -ExecutionPolicy Unrestricted -Command ". 'C:\Users\3DTM\AppData\Local\Temp\564badbc-2273-449c-b27a-c207ee9d8467.ps1'"
2024-02-08T20:33:29.1801744Z 
2024-02-08T20:33:34.2738043Z ##[debug]JobId: '2', JobState: 'completed', ComputerName: '$(WSUSVMFQDN)'
2024-02-08T20:33:34.2762788Z ================================================ wsus-3dtm.uksouth.cloudapp.azure.com ================================================
2024-02-08T20:33:34.2825861Z VERBOSE: Using default AzCopy arguments for dowloading to VM
2024-02-08T20:33:34.2829285Z 
2024-02-08T20:33:34.3144160Z VERBOSE: ##[command] & azcopy copy 
2024-02-08T20:33:34.3147566Z 
2024-02-08T20:33:34.3635588Z "https://$(StorageResourceURL)/99c69625-ee4a-45f7-86a0-11bcfc92588b*****" 
2024-02-08T20:33:34.3638378Z 
2024-02-08T20:33:34.3925065Z "E:\MSUS\WsusContent\TRANSFER" --recursive --log-level=INFO
2024-02-08T20:33:34.3928494Z 
2024-02-08T20:33:34.4195491Z 
2024-02-08T20:33:34.4199248Z 
2024-02-08T20:33:34.4472492Z failed to parse user input due to error: cannot use wildcards in the path section of the URL except in trailing "/*". If you wish to use * in your URL, manually encode it to %2A
2024-02-08T20:33:34.4475185Z 
2024-02-08T20:33:34.4752474Z ##[debug][3DTM-Glasgow-WS]LASTEXITCODE is 1
2024-02-08T20:33:34.4754589Z 
2024-02-08T20:33:34.4902948Z ##[debug]Leaving Get-JobResults.
2024-02-08T20:33:34.4992830Z ##[debug]Leaving Run-RemoteScriptJobs.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
steps:
- task: AzureFileCopy@5
  displayName: 'Copy 3DTM Launcher Service to WSUS'
  inputs:
    SourcePath: '"C:\Telemedicine3DOneDrive\OneDrive\FullSystemDeploy\$(Build.SourceBranchName)\3DTMLauncherService.*"'
    azureSubscription: 'Peabody Pipeline upload'
    Destination: AzureVMs
    storage: 3dtmbinarystorage
    resourceGroup: 3DTELEMEDECINE
    MachineNames: '$(WSUSVMName)'
    vmsAdminUserName: '$(WSUSAdminUsername)'
    vmsAdminPassword: '$(WSUSAdminPassword)'
    TargetPath: '$(WSUSDestinationFolder)'
```

**Comment by jiggybyte** [comment]
Same error...how are we expected to use the V5 task to remove dependencies on AzureRM if V5 is broken?  Classic MS.

**Comment by jiggybyte** [comment]
I’m working around this by downloading the SXS version of this task…fixed the bad syntax in the power shell file…the azcopy command for copying from the storage account to the VM needed a question mark character between the container and the SAS params.

we shouldn’t have to work around these sorts of bugs all the time.

**Comment by TomasMalecek** [comment]
The code of AzureFileCopy@3 differs a lot, but it is impacted the same way. Getting this error, which seems to be from AzCopy.exe itself:
```
[ERROR] The syntax of the command is incorrect. Invalid SAS token in parameter "SourceSAS".
```

**Comment by fowie** [comment]
> I’m working around this by downloading the SXS version of this task…fixed the bad syntax in the power shell file…the azcopy command for copying from the storage account to the VM needed a question mark character between the container and the SAS params.
> 
> we shouldn’t have to work around these sorts of bugs all the time.

I've never done a custom SXS version, can you point me to some details on how to get this working?

**Comment by jiggybyte** [comment]
https://github.com/jessehouwing/azure-pipelines-tasks-zips/releases/tag/m236-tasks

You can download all of the packages here...the side by side (SXS) packages are there as well.  I had to extract the "broken" file from their archive and then fix it and add it back in...then you can upload that file to your onprem TFS or Azure Devops and use it alongside the normal task.

There's a command line tool called tfx you likely have installed locally, you can login to that and use it to add/remove tasks to your onprem tfs.  I think azure devops has a way to just do that in the web gui.

This powershell script was also handy:
https://github.com/jessehouwing/azure-pipelines-tasks-zips/blob/main/scripts/install-task.ps1

**Comment by haf76348g78** [comment]
> I’m working around this by downloading the SXS version of this task…fixed the bad syntax in the power shell file…the azcopy command for copying from the storage account to the VM needed a question mark character between the container and the SAS params.

Experiencing the same problem today, but was working yesterday and before.  Same root cause (missing question mark).  Don't understand how this could suddenly start happening today?

**Comment by marcusrichards** [comment]
Same error in FileCopy 4 and 5 - massive impact on our deployments. Urgent fix needed

**Comment by haf76348g78** [comment]
If it helps, I worked around it like this:

1. Change the Destination Type of the Azure File Copy task to Azure Blob
2. Put something in Container Name like "foo"
3. Check the Clean Target checkbox
4. Under Output Variables, put something in Reference Name like "bar"
5. Add a PowerShell on Target Machines task
6. Enter the server name of your target machine and login credentials
7. Add the following as an Inline Script: azcopy copy "https://<your storage>/<foo>/*?$(<bar>.StorageContainerSasToken)" "<your destination>" --recursive --log-level=INFO

The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.

**Comment by marcusrichards** [comment]
> If it helps, I worked around it like this:
> 
> 1. Change the Destination Type of the Azure File Copy task to Azure Blob
> 2. Put something in Container Name like "foo"
> 3. Check the Clean Target checkbox
> 4. Under Output Variables, put something in Reference Name like "bar"
> 5. Add a PowerShell on Target Machines task
> 6. Enter the server name of your target machine and login credentials
> 7. Add the following as an Inline Script: azcopy copy "https:////*?$(.StorageContainerSasToken)" "" --recursive --log-level=INFO
> 
> The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.

Thanks, couple of questions - is the output variable "bar" used anywhere? is the StorageContainerSasToken automatically set to the correct value?

**Comment by haf76348g78** [comment]
> > If it helps, I worked around it like this:
> > 
> > 1. Change the Destination Type of the Azure File Copy task to Azure Blob
> > 2. Put something in Container Name like "foo"
> > 3. Check the Clean Target checkbox
> > 4. Under Output Variables, put something in Reference Name like "bar"
> > 5. Add a PowerShell on Target Machines task
> > 6. Enter the server name of your target machine and login credentials
> > 7. Add the following as an Inline Script: azcopy copy "https:////*?$(.StorageContainerSasToken)" "" --recursive --log-level=INFO
> > 
> > The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.
> 
> Thanks, couple of questions - is the output variable "bar" used anywhere - is that how the azcopy knows which storage container to copy? is the StorageContainerSasToken automatically set to the correct value?

Sorry, updated my original comment.  I forgot to escape the angle brackets.

**Comment by volaru77** [comment]
Same here, started happening today with AzureFileCopy@4.

Looking at the logs, yesterday:
...
Version      : 4.236.1
...
Import-Module -Name C:\Modules\az_9.3.0\Az.Accounts\2.16.0\Az.Accounts.psd1 -Global

And today:
...
Version      : 4.237.1
...
Import-Module -Name C:\Modules\az_11.3.1\Az.Accounts\2.16.0\Az.Accounts.psd1 -Global

Is there a way to specify the version / module in the task parameters?

**Comment by marcusrichards** [comment]
> > > If it helps, I worked around it like this:
> > > 
> > > 1. Change the Destination Type of the Azure File Copy task to Azure Blob
> > > 2. Put something in Container Name like "foo"
> > > 3. Check the Clean Target checkbox
> > > 4. Under Output Variables, put something in Reference Name like "bar"
> > > 5. Add a PowerShell on Target Machines task
> > > 6. Enter the server name of your target machine and login credentials
> > > 7. Add the following as an Inline Script: azcopy copy "https:////*?$(.StorageContainerSasToken)" "" --recursive --log-level=INFO
> > > 
> > > The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.
> > 
> > 
> > Thanks, couple of questions - is the output variable "bar" used anywhere - is that how the azcopy knows which storage container to copy? is the StorageContainerSasToken automatically set to the correct value?
> 
> Sorry, updated my original comment. I forgot to escape the angle brackets.

This worked perfectly - thank you :) Do you have a quick way to install the WinRMCustomScriptExtension? I am using File Copy to do that still, then let it fail, then use your azcopy to pick up the pieces. But would be nice to do the WinRM install manually outside the File Copy.

**Comment by alundgren** [comment]
> I’m working around this by downloading the SXS version of this task…fixed the bad syntax in the power shell file…the azcopy command for copying from the storage account to the VM needed a question mark character between the container and the SAS params.
> 
> we shouldn’t have to work around these sorts of bugs all the time.

Having the same issue here but I dont quite understand what you changed. Is this the line you edited?

`$scriptBlockArgs = " -containerURL '$containerURL' -targetPath '$targetPath' -containerSasToken '$containerSasToken' -additionalArguments '$additionalArguments'"`

If so, could you share the edited version with a poor newbie? :)

**Comment by Griffa87** [comment]
> aine

Can confirm this works. Thank you so much! saved me a lot of headache this morning.

**Comment by gusAntonis** [comment]
> > > > > If it helps, I worked around it like this:
> > > > > 
> > > > > 1. Change the Destination Type of the Azure File Copy task to Azure Blob
> > > > > 2. Put something in Container Name like "foo"
> > > > > 3. Check the Clean Target checkbox
> > > > > 4. Under Output Variables, put something in Reference Name like "bar"
> > > > > 5. Add a PowerShell on Target Machines task
> > > > > 6. Enter the server name of your target machine and login credentials
> > > > > 7. Add the following as an Inline Script: azcopy copy "https:////*?$(.StorageContainerSasToken)" "" --recursive --log-level=INFO
> > > > > 
> > > > > The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.
> > > > 
> > > > 
> > > > Thanks, couple of questions - is the output variable "bar" used anywhere - is that how the azcopy knows which storage container to copy? is the StorageContainerSasToken automatically set to the correct value?
> > > 
> > > 
> > > Sorry, updated my original comment. I forgot to escape the angle brackets.
> > 
> > 
> > This worked perfectly - thank you @haf76348g78 :) Do you have a quick way to install the WinRMCustomScriptExtension? I am using File Copy to do that still, then let it fail, then use your azcopy to pick up the pieces. But would be nice to do the WinRM install manually outside the File Copy.
> 
> Can confirm this works. Thank you so much! saved me a lot of headache this morning.

Can you guys provide some more detailed reference on the changes applicable,
Little confused on the usage of the output variables and the powershell task
@Griffa87 @marcusrichards

**Comment by gusAntonis** [comment]
> If it helps, I worked around it like this:
> 
> 1. Change the Destination Type of the Azure File Copy task to Azure Blob
> 2. Put something in Container Name like "foo"
> 3. Check the Clean Target checkbox
> 4. Under Output Variables, put something in Reference Name like "bar"
> 5. Add a PowerShell on Target Machines task
> 6. Enter the server name of your target machine and login credentials
> 7. Add the following as an Inline Script: `azcopy copy "https://<your storage>/<foo>/*?$(<bar>.StorageContainerSasToken)" "<your destination>" --recursive --log-level=INFO`
> 
> The reconfigured Azure File Copy task will do the "copy to blob" bit, and the new task will do the "copy from blob to target" bit.

@haf76348g78 i am still facing issues with the powershell task used for copying the file from blob to the VM,
can you share the reference for the tasks to be modified, a sample yaml would really help a lot

**Comment by gusAntonis** [comment]
> We have implemented the workaround and this was working last week but has started failing this week. I'm in the process of investigating the problem.
> 
> There is obviously a bug that has been introduced in the AzureFileCopy task with the missing ? between the url and access token; can this please be fixed as a priority as it is impacting our releases?!?

So the copy to blob and then copy to VM started failing for you as well.

**Comment by AndrewBates666** [comment]
Yes, the copy to the blob is working but the copying to the VM has started to fail this week. As I say looking into it now to understand why. We ideally need the bug fixing though as this isn't the first time AzureFileCopy has been broken.

**Comment by gusAntonis** [comment]
> Yes, the copy to the blob is working but the copying to the VM has started to fail this week. As I say looking into it now to understand why. We ideally need the bug fixing though as this isn't the first time AzureFileCopy has been broken.

So i also implemented the solution today, we are also able to copy to the blob but when we try to copy to the VM,
We don't get any errors, rather just the transfer fails, we are using the az-copy for copying the files from blob to VM

**Comment by AndrewBates666** [comment]
Seems that azcopy.exe isn't available on the Azure Hosted Build agents which is causing the copy from blob to the VM to fail... We're using the windows-2022 vmImage.

azcopy : The term 'azcopy' is not recognized as the name of a cmdlet, function, script file, or...

**Comment by gusAntonis** [comment]
Hey @AndrewBates666  did you found any resolution for the same,
For the reference this is our tasks yml file,

```
parameters:
  - name: sourcePath
    type: string
  - name: storage
    type: string
  - name: resourceGroup
    type: string
  - name: machineNames
    type: string
  - name: vmsAdminUserName
    type: string
  - name: vmsAdminPassword
    type: string
  - name: targetPath
    type: string
  - name: enableCopyPrerequisites
    type: boolean
    default: false
  - name: cleanTarget
    type: boolean
    default: true
  - name: displayName
    type: string

steps:
- task: AzureFileCopy@4
  displayName: ${{ parameters.displayName }}
  name: fileCopy
  inputs:
    SourcePath: ${{ parameters.sourcePath }}
    azureSubscription: $(azureSubscription)
    Destination: AzureBlob
    storage: ${{ parameters.storage }}
    containerName: filecopyblob
    BlobPrefix: ''  # Empty or specific path within blob
    resourceGroup: ${{ parameters.resourceGroup }}
    enableCopyPrerequisites: ${{ parameters.enableCopyPrerequisites }}
    CleanTargetBeforeCopy: ${{ parameters.cleanTarget }}
    copyFilesInParallel: true

- task: AzurePowerShell@5
  displayName: 'Copy Files from Blob to VM'
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'InlineScript'
    Inline: |
      $vmName = '${{ parameters.machineNames }}'
      $vmUser = '${{ parameters.vmsAdminUserName }}'
      $vmPass = '${{ parameters.vmsAdminPassword }}'
      $sasToken = "$(fileCopy.StorageContainerSasToken)"  # Use the output variables from the fileCopy task
      $containerUri = "https://${{ parameters.storage }}.blob.core.windows.net/filecopyblob"  # Adjusted for correct storage and container naming
      if (-not $sasToken.StartsWith('?')) {
        $sasToken = "?$sasToken"  # Ensure the SAS token starts with '?'
      }
      $azCopyCommand = "azcopy copy `"$containerUri/*$sasToken`" `"${{ parameters.targetPath }}`" --recursive --log-level=INFO"
      Write-Host "Running azcopy command: $azCopyCommand"
      Invoke-Expression $azCopyCommand
    azurePowerShellVersion: '9.3.0'

```
