### ISSUE TITLE
[enhancement]: HelmInstaller task need the complete version to install Helm. It would be great if we can skip patch version while specifying helm version. 

### ISSUE THREAD

**Issue by jikuma** [microsoft/azure-pipelines-tasks#19540]
### Task name

HelmInstaller

### Describe your feature request here

Currently my task looks like

```
 - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 3.14.0
```

I want to specify

```
 - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 3.14
```

The task can pick the latest patch version.
