### ISSUE TITLE
[REGRESSION]: VSTest@3 does not use narrower pattern

### ISSUE THREAD

**Issue by nohwnd** [microsoft/azure-pipelines-tasks#19555]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

VSTest@2

### Breaking task version

3

### Last working task version

2

### Regression Description

The new task does not use the narrower test pattern implemented in #17135. This breaks our users, because they end up resolving additional dlls in obj and bin.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

all

### Relevant log output

```shell
I don't have logs, this is caused by the task configuration.
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: VSTest@2

- task: VSTest@3


Put this in interactive pipeline editor on AzDO. 
click settings above VSTest@2 and you will see the new filter:
**\bin\**\*test.dll
**\bin\**\*tests.dll

click settings above VSTest@2 and you will see old filter:
**\*test*.dll
!**\*TestAdapter.dll
!**\obj\**
```
