### ISSUE TITLE
[BUG]: sqlpackage not found on a Linux self hosted agent

### ISSUE THREAD

**Issue by vanmash** [microsoft/azure-pipelines-tasks#19584]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

SqlAzureDacpacDeploymentV1

### Task version

V1

### Issue Description

A bug happened! 
##[error]No agent found in pool Default satisfies both of the following demands: agent.os, sqlpackage. All demands: agent.os -equals Linux, sqlpackage, Agent.Version -gtVersion 2.164.1

my note:
might be connected to https://github.com/microsoft/azure-pipelines-tasks/issues/18913

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.4

### Relevant log output

```shell
##[error]No agent found in pool Default satisfies both of the following demands: agent.os, sqlpackage. All demands: agent.os -equals Linux, sqlpackage, Agent.Version -gtVersion 2.164.1
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: SqlAzureDacpacDeployment@1
                  retryCountOnTaskFailure: 1
                  inputs:
                    azureSubscription: $(servicePrincipal)
                    AuthenticationType: 'servicePrincipal'
                    ServerName: 'sql-$(TF_VAR_PRODUCT)-$(TF_VAR_ENV).database.windows.net'
                    DatabaseName: 'sqldb-$(TF_VAR_PRODUCT)-$(TF_VAR_ENV)'
                    deployType: 'InlineSqlTask'
                    SqlInline: |
                      <SQL script>
                    IpDetectionMethod: 'AutoDetect'
```
