### ISSUE TITLE
Bug: Docker@2 task does not support arguments when command is buildAndPush

### ISSUE THREAD

**Issue by nikneem** [microsoft/azure-pipelines-tasks#19602]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Docker@2

### Task version

2.231.0

### Issue Description

I have a private package repository (NuGet) and I want to restore packages using that private feed. Therefore I login to the package feed and pass the credentials to the docker build task using arguments. These arguments are then used in my docker file where I execute the `dotnet restore` task.

Now after the container has been build, I want to push the container to a registry. The fast way is to change the command from `build`, to `buildAndPush`. However, the `buildAndPush` command does not accept the arguments that I use to create the task in my Azure DevOps pipeline.

I think the `buildAndPush` task should also aways accept arguments:

Current situation (in this pipeline, the build fails because the NuGet packages could not be restored (because of a package feed authentication error). I think this would be a desired way of working.

```yaml
- task: NuGetAuthenticate@1
  displayName: Authenticate with NuGet Feeds

- task: Docker@2
  displayName: "Build Container"
  inputs:
    command: "buildAndPush"
    dockerfile: "src/Dockerfile"
    containerRegistry: "ServiceConnectionName"
    repository: "path/in/repository"
    arguments: "--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)"
    tags: "$(VERSION)"
```

A work-around is as follows, in this case, the command of the first docker task is changed to `build` instead of `buildAndPush`. The build task _does_ accept the arguments and therefore restoring NuGet packages will succeed. The following docker task is a publish only task resulting in the container being pushed to the registry.

```yaml
- task: NuGetAuthenticate@1
  displayName: Authenticate with NuGet Feeds

- task: Docker@2
  displayName: "Build Container"
  inputs:
    command: "build"
    dockerfile: "src/Dockerfile"
    containerRegistry: "ServiceConnectionName"
    repository: "path/in/repository"
    arguments: "--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)"
    tags: "$(VERSION)"

- task: Docker@2
  displayName: "Push Container"
  inputs:
    command: "push"
    repository: "path/in/repository"
    containerRegistry: "ServiceConnectionName"
    tags: "$(VERSION)"
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu-latest

### Relevant log output

```shell
> [build 34/37] RUN dotnet restore "./Xxxx.Yyyy.Api/./Xxxx.Yyyy.Api.csproj":
124.4 /src/Xxxx.Yyyy.Charts.Svg/Xxxx.Yyyy.Charts.Svg.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
124.4 /src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json.
124.4 /src/Xxxx.Yyyy.Charts/Xxxx.Yyyy.Charts.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
130.0 /src/Xxxx.Yyyy.Charts.Svg/Xxxx.Yyyy.Charts.Svg.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
130.0 /src/Xxxx.Yyyy.Charts/Xxxx.Yyyy.Charts.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
130.0 /src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json.
130.0 /src/Xxxx.Yyyy.Charts.CosmosDb/Xxxx.Yyyy.Charts.CosmosDb.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
135.7 /src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json.
135.7 /src/Xxxx.Yyyy.Charts.Pdf/Xxxx.Yyyy.Charts.Pdf.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/Xxxxdevops/Yyyy_SaaS/_packaging/YyyyNuGet/nuget/v3/index.json. [/src/Xxxx.Yyyy.Api/Xxxx.Yyyy.Api.csproj]
135.7   Failed to restore /src/Xxxx.Yyyy.Charts.Pdf/Xxxx.Yyyy.Charts.Pdf.csproj (in 1.33 min).


Dockerfile:45
--------------------
  43 |     COPY ["xxxxxx/xxxxxx.csproj", "xxxxxx/xxxxxx"]
  44 |     COPY ["xxxxxx/xxxxxx.csproj", "xxxxxx/"]
  45 | >>> RUN dotnet restore "./xxxxxx/xxxxxx.csproj"
  46 |     COPY . .
  47 |     WORKDIR "/src/xxxxxx"
--------------------
```

### Repro steps

```yml
- task: NuGetAuthenticate@1
  displayName: Authenticate with NuGet Feeds

- task: Docker@2
  displayName: "Build Container"
  inputs:
    command: "buildAndPush"
    dockerfile: "src/Dockerfile"
    containerRegistry: "ServiceConnectionName"
    repository: "path/in/repository"
    arguments: "--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)"
    tags: "$(VERSION)"
```
