### ISSUE TITLE
[REGRESSION]: PublishCodeCoverageResultsV2 not generating branch coverage information

### ISSUE THREAD

**Issue by david-vankampen** [microsoft/azure-pipelines-tasks#19669]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishCodeCoverageResults

### Breaking task version

1.236.1

### Last working task version

1.231.0

### Regression Description

When combined with the BuildQualityChecks@7 downstream, previously one would be able to enforce both line coverage AND branch coverage.  Now, it reports 0% branch coverage.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
[WARNING] Coverage data does not include the requested coverage of type 'branches'. Please ensure that your coverage tool is able to report this type of coverage data!
##[warning]Coverage data does not include the requested coverage of type 'branches'. Please ensure that your coverage tool is able to report this type of coverage data!
Total branches: 0
Covered branches: 0
Code Coverage (%): 0
[ERROR] The code coverage value (0%, 0 branches) is lower than the minimum value (70%)!
##[error]The code coverage value (0%, 0 branches) is lower than the minimum value (70%)!
```
```


### Full task logs with system.debug enabled

_No response_

### Repro steps

_No response_

**Comment by billzhang3046** [comment]
We are seeing the same issue today after we moved to PublishCodeCoverageResults@2. In the task log, there was no branch results:

> Publishing coverage summary data.
> line- 124 of 124 covered.
> Publishing file coverage data.

The v1 published both line and branch results:

> Publishing coverage summary data to TFS server.
>  Lines- 124 of 124 covered.
>  Branches- 28 of 28 covered.
> Modifying Cobertura Index file
> Publishing code coverage files to TFS server.
> Uploading 7 files

**Comment by moikot** [comment]
I'm getting the following warning in every build:

```
##[warning]New V2 version of task publishing code coverage results is available to all our customers now. We highly recommend to stop using the V1 version and migrate to V2 version (https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2). For more details, see - https://devblogs.microsoft.com/devops/new-pccr-task.
```

But how I suppose to switch to the new version if it doesn't work properly?

**Comment by Lucas3oo** [comment]
Same for me and also with V1 I cloud check which methods that have coverage and see the source code also.

**Comment by jeffyoung** [comment]
What do we need to do to get this _actually_ on the product backlog? I've already rolled back to v1 which implores you to upgrade to v2. If you've moved on to GitHub actions, fine. But at least address regressions.

**Comment by atahanceylan** [comment]
we are having the same issue. when I migrate v2 no branch coverage created. rolled back changes until v2 version have a branch coverage.

**Comment by cmconti** [comment]
No branch coverage, no drill down to see the uncovered lines/branches (see https://github.com/microsoft/azure-pipelines-tasks/issues/19939)

**Comment by iansalazar444** [comment]
Just wanted to jump on this to let everyone know - branch coverage is still not displayed for v2

**Comment by syre** [comment]
We are having the same issue, when in the "Code Coverage" tab drilldown into files does not work to see line/branch coverage.
However when downloading the "Code Coverage Report" from "artifacts", drilldown works just fine.

**Comment by ahsonkhan** [comment]
What @syre described is our exact same experience for us on the [Azure SDK for C++](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4140631&_a=summary&tab=ms.vss-codecoverage-web.code-coverage-details&view=codecoverage-tab) CI pipelines (from [this project](https://github.com/Azure/azure-sdk-for-cpp)).

**Comment by denravonska** [comment]
Can you at least roll back the deprecation warning until you've solved this?

**Comment by mborgeaud** [comment]
While it works for 'line' coverage, it won't work for 'branches'. Can this be fixed with priority, please? The only workaround is rolling back to V1 and ADO pipelines will show the message to upgrade to V2. Thanks.

**Comment by kjaworski** [comment]
Any news? We also suffer from this change

**Comment by ehwg** [comment]
It does not work for us, too. 
In the log I see lines coverage 

```
...
Creating summary
Writing report file '/agent/_work/_temp/af3995aa-0cd4-4eb6-a063-1964885d/index.html'
Publishing coverage summary data.
line- 105 of 111 covered.
Publishing file coverage data.
```

but nothing is published. I tried also the version: https://github.com/microsoft/azure-pipelines-tasks/issues/19547 but it did bot work for us. Coverage tab says 
Code coverage report cannot be rendered as report HTML was not found. Please verify that "Report Directory" containing an HTML report was specified when [publishing code coverage](https://go.microsoft.com/fwlink/?linkid=2081549).

**Comment by DeanGoodfynd** [comment]
Based on the comment below on the original Azure DevOps blog, I retried the `PublishCodeCoverageResults@2` task. Branch and line coverage is working again for me.

https://devblogs.microsoft.com/devops/new-pccr-task/?commentid=4652#comment-4652

If it's working for other folks, maybe this regression can be closed?

**Comment by denravonska** [comment]
> Based on the comment below on the original Azure DevOps blog, I retried the `PublishCodeCoverageResults@2` task. Branch and line coverage is working again for me.
> 
> https://devblogs.microsoft.com/devops/new-pccr-task/?commentid=4652#comment-4652
> 
> If it's working for other folks, maybe this regression can be closed?

Yup, seems to be working for me as well.

**Comment by nulltoken** [comment]
Branch coverage works also for me.

However, v2 seems to suffer from an issue when accessing detailed coverage pages (cf. #20936)

**Comment by moikot** [comment]
It looks like branch coverage is now appearing in the report on "Code Coverage" tab (which is good), but still not available for BuildQualityChecks to check. I'm seeing this:

```bash
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
[WARNING] Coverage data does not include the requested coverage of type 'branches'. Please ensure that your coverage tool is able to report this type of coverage data!
##[warning]Coverage data does not include the requested coverage of type 'branches'. Please ensure that your coverage tool is able to report this type of coverage data!
Total branches: 0
Covered branches: 0
Code Coverage (%): 0
```

**Comment by Samhitha-Microsoft** [comment]
Still not able to get the branch coverage using v2

**Comment by wyp84** [comment]
Any updates on this? BuildQualityChecks still seems not to work with v2:
##[warning]Coverage data does not include the requested coverage of type 'branches'. Please ensure that your coverage tool is able to report this type of coverage data!

**Comment by henrywilde-cs** [comment]
My current workaround is to invoke `coverage` manually after uploading:

```yaml
steps:
  ...
  - script: uv run pytest --cov --cov-branch --cov-report=xml --junitxml=TEST-results.xml
    displayName: 'Run tests with coverage'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish coverage results'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage.xml'

  - script: uv run coverage report --fail-under=100
    displayName: 'Check for 100% branch coverage'
```

**Comment by bhagatprince011** [comment]
in my case it is unable to find  ...*coverage.xml

```
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests with Code Coverage'
  inputs:
    command: 'test'
    projects: '**/DebtorGateway.ServiceTest.csproj'
    arguments: --collect:"XPlat Code Coverage"
    publishTestResults: true

- powershell: |
    # Get the short path name (8.3 format)
    $tempDir = cmd /c "for %A in ('$(Agent.TempDirectory)') do @echo %~sA"
    $coverageFile = cmd /c "for %A in ('$(Agent.TempDirectory)\SAJENKINS_*\In\*\coverage.cobertura.xml') do @echo %~sA"
    
    Write-Host "##vso[task.setvariable variable=CoverageFilePath]$coverageFile"
  displayName: 'Use Short Path Names'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(CoverageFilePath)'
    reportDirectory: '$(Agent.TempDirectory)'
```

<img width="817" height="420" alt="Image" src="https://github.com/user-attachments/assets/ec169af0-0300-4945-a6a1-20e59c5f2e86" />
