### ISSUE TITLE
[enhancement]: Add "trim", "ltrim", "rtrim" expressions

### ISSUE THREAD

**Issue by pszypowicz** [microsoft/azure-pipelines-tasks#19679]
### Describe your feature request here

Please add template expressions: "ltrim", "rtrim", "trim".

"rtrim" : trim whitespace from the string from the left side.
"ltrim": same ^ but from right side
"trim": from both sides

Just one of examples of why would that be useful:

```
parameters:
  - name: "test"
    type: string
    default: " "

variables: 
  test: ${{ trim(parameters.test }}
 ```

^ Often it happens that users do not see first whitespace in an input field and they set paremeter.test to " value", instead of just "value" (mind the white space at beginning)
