### ISSUE TITLE
[REGRESSION]: Azure CLI@2 - toolExecutionError.indexOf is not a function

### ISSUE THREAD

**Issue by ponbac** [microsoft/azure-pipelines-tasks#19726]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureCLI@2

### Regression Description

Our pipeline stopped working _April 02_ and the error message does not get logged since `toolExecutionError.indexOf is not a function` causes a crash.

This seems to have been introduced in this commit: https://github.com/microsoft/azure-pipelines-tasks/commit/9e519cb289c4da4a03928dfcd3a9bbe113696b2e by @LeftTwixWand.

The problem seems to be that you try to use `indexOf` on `toolExecutionError` which in some cases is neither a string nor an array at e.g. https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV2/azureclitask.ts#L101.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Relevant log output

```shell
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.237.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
##[error]Unhandled: toolExecutionError.indexOf is not a function
##[error]TypeError: toolExecutionError.indexOf is not a function
    at azureclitask.<anonymous> (D:\a\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.237.3\azureclitask.js:101:77)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.237.3\azureclitask.js:5:58)
```
```


### Full task logs with system.debug enabled

_No response_

### Repro steps

```yml
schedules:
  - cron: "0 19 * * *"
    displayName: At 19:00 every day
    branches:
      include:
        - main
    always: true
pr: none
trigger: none
pool:
  vmImage: "windows-2022"

stages:
  - stage: abc
    jobs:
      - job: abc
        steps:
          - task: AzureCLI@2
            displayName: Take down qa appservices and serviceplan
            inputs:
              azureSubscription: "ABC"
              scriptType: ps
              scriptLocation: scriptPath
              scriptPath: "iac/azure-pipelines/abc.ps1"
```
