### ISSUE TITLE
[BUG]: AzureResourceManagerTemplateDeployment@3.175.1 failing with: Failed to check the resource group status. Error: Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired.

### ISSUE THREAD

**Issue by AnushaGarg** [microsoft/azure-pipelines-tasks#19725]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureResourceManagerTemplateDeployment

### Task version

3.175.1

### Issue Description

After converting the service connection from "service principle" to "Workload Identity federation" connection, this task started to fail with below error.
[error]Failed to check the resource group status. Error: Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
Checking if the following resource group exists: sapsystemstatus-rg-dev.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Failed to check the resource group status. Error: Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg.
```

### Full task logs with system.debug enabled

<details>
  <pre> Starting: Create FunctionApp with Application Insights
==============================================================================
Task         : ARM template deployment
Description  : Deploy an Azure Resource Manager (ARM) template to all the deployment scopes
Version      : 3.175.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================
ARM Service Connection deployment scope - Subscription
Checking if the following resource group exists: sapsystemstatus-rg-dev.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Failed to check the resource group status. Error: Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg.
Finishing: Create FunctionApp with Application Insights
</pre>
</details>

### Repro steps

```yml
- task: AzureResourceManagerTemplateDeployment@3.175.1
        displayName: 'Create FunctionApp with Application Insights'
        condition: and(eq('${{ parameters.SkuCapacity }}', '-1'),eq('${{ parameters.AlwaysReadyInstances }}', '-1'))
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '${{ variables.Connection }}'
          subscriptionId: ${{ parameters.subscriptionId }}
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroup.name)'
          location: '$(resourceGroup.location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.Repository.LocalPath)/Deployment/FunctionApp/fapppremium.json'
          csmParametersFile: '$(Build.Repository.LocalPath)/Deployment/FunctionApp/fapppremium.parameters.json'
          overrideParameters: '-name "$(functionappname)" -storageAccountName "$(storageactname)" -location "$(resourceGroup.location)" -skuCode "$(skuCode)" -applicationInsightsLocation "$(resourceGroup.location)" -applicationInsightsName "$(applicationInsightsName)"'
          deploymentMode: 'Incremental'
```
