### ISSUE TITLE
[BUG]: SqlAzureDacpacDeployment@1 - error when using a Workload Identity federation

### ISSUE THREAD

**Issue by zoemac11** [microsoft/azure-pipelines-tasks#19721]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

SqlAzureDacpacDeployment@1

### Task version

1.237.4

### Issue Description

Getting the following error when using a Workload Identity federation service connection

`##[error]Microsoft.PowerShell.Commands.WriteErrorException: ExceptionMessage: Cannot bind argument to parameter 'vstsAccessToken' because it is an empty string. (in function: Build-MSALInstance)Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-`

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Microsoft Windows Server 2022

### Relevant log output

```shell
##[error]Microsoft.PowerShell.Commands.WriteErrorException: ExceptionMessage: Cannot bind argument to parameter 'vstsAccessToken' because it is an empty string. (in function: Build-MSALInstance)Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
```

### Full task logs with system.debug enabled

<details>
  <pre> Starting: Run migrations
==============================================================================
Task         : Azure SQL Database deployment
Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
Version      : 1.237.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
==============================================================================
Added TLS 1.2 in session.
Temporary inline SQL file: C:\Users\VssAdministrator\AppData\Local\Temp\tmp56C8.tmp
Invoke-Sqlcmd -connectionString "**********"  -Inputfile "C:\Users\VssAdministrator\AppData\Local\Temp\tmp56C8.tmp" 
##[error]Microsoft.PowerShell.Commands.WriteErrorException: ExceptionMessage: Cannot bind argument to parameter 'vstsAccessToken' because it is an empty string. (in function: Build-MSALInstance)Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
Finishing: Run migrations
 </pre>
</details>

### Repro steps

```yml
pool: 
    vmImage: 'windows-latest'

  steps:           
    - task: SqlAzureDacpacDeployment@1
      displayName: 'Run migrations'
      inputs:
        azureSubscription: '<workload-identity-service-connection>'
        AuthenticationType: connectionString
        ConnectionString: 'Server=database.database.windows.net;Database=database;User ID=user;Password=password;'
        deployType: 'SqlTask'
        SqlFile: '$(System.DefaultWorkingDirectory)/migrations/migrations.sql'
        IpDetectionMethod: 'AutoDetect'
```
