### ISSUE TITLE
[REGRESSION]: AzureFileCopy@6 no longer works with "Workload identity federation" service connection

### ISSUE THREAD

**Issue by Mikkelcv** [microsoft/azure-pipelines-tasks#19767]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Breaking task version

6.238.1

### Last working task version

6.237.5

### Regression Description

Using a WIF Service connection from Azure DevOps to Azure
Storage account in Azure.

When the task runs the copy command then earlier I would see:

> Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
>  & azcopy copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/" --log-level=INFO --recursive
> INFO: Scanning...
> INFO: Login with Powershell context succeeded
> INFO: Authenticating to destination using Azure AD

however from yesterday when the new task was live in our tenant then:

> Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
>  & "AzCopy\AzCopy.exe" copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/"  --log-level=INFO --recursive
> INFO: Scanning...
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxx to authenticate.

Then the task just blocks and fails after 1-2 minutes

**Work-a-round**,
I have now removed the AzureFileCopy task and replaced it with a AzureCLI@2 task using the same service connection and calling:

> az storage blob upload --account-name $Env:StorageAccountName -c $Env:ContainerName -f $Env:File --overwrite true --auth-mode login --only-show-errors

which is working, so I believe it is not the service connection.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Relevant log output

```shell
Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
 & "AzCopy\AzCopy.exe" copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/"  --log-level=INFO --recursive
INFO: Scanning...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxx to authenticate.
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
trigger: none

pool:
  vmImage: windows-2022

steps:
- task: ArchiveFiles@2
  displayName: "Zip Doc"
  inputs:
    rootFolderOrFile: $(Agent.BuildDirectory)/s/doc
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/doc.zip'
    replaceExistingArchive: true

- task: AzureFileCopy@6
  displayName: "Upload Doc to Blob"
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/doc.zip'
    azureSubscription: 'Az Subscription'
    Destination: 'AzureBlob'
    storage: 'storage_xyz'
    ContainerName: 'container_xyz'
    BlobPrefix: 'test'
```
