### ISSUE TITLE
[BUG]: AzureCLI@2 returns ##[error]Unhandled: toolExecutionError.indexOf is not a function when scriptPath is missing

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/azure-pipelines-tasks#19768]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureCli@2

### Task version

2.237.3

### Issue Description

If scriptPath points to a missing PS script, we get "##[error]Unhandled: toolExecutionError.indexOf" error message.
Expectation: Get a valid message.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

n/a

### Relevant log output

```shell
https://msazure.visualstudio.com/OneAgile/_build/results?buildId=91407394&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=cfd077b3-05f6-52ca-6b39-ab2d733d7103

once the missing script is added, no error

https://msazure.visualstudio.com/OneAgile/_build/results?buildId=91408290&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=cfd077b3-05f6-52ca-6b39-ab2d733d7103
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: AzureCLI@2
            inputs:
              azureSubscription: 'XXX [workload identity]'
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: '$(build.sourcesdirectory)\.scripts\MISSINGSCRIPT.ps1'
```
