### ISSUE TITLE
[BUG]: (node:1631) [DEP0005] DeprecationWarning: 

### ISSUE THREAD

**Issue by pinakighatak** [microsoft/azure-pipelines-tasks#19821]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureResourceManagerTemplateDeployment

### Task version

5

### Issue Description

Running this on ubuntu host creates the following warning:
`(node:1631) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use node --trace-deprecation ... to show where the warning was created)`

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu-latest

### Relevant log output

```shell
Starting: Provision Azure Function App from Bicep
==============================================================================
Task         : ARM template deployment
Description  : Deploy an Azure Resource Manager (ARM) template to all the deployment scopes
Version      : 3.238.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================
ARM Service Connection deployment scope - Subscription
Creating deployment parameters.
Setting active cloud to: AzureCloud
/usr/bin/az cloud set -n AzureCloud
/usr/bin/az login --service-principal -u *** --tenant xxxx --allow-no-subscriptions --federated-token ***
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "****",
    "id": "****",
    "isDefault": true,
    "managedByTenants": [
      {
        "tenantId": "****"
      }
    ],
    "name": "MCAPS-EXT-****",
    "state": "Enabled",
    "tenantId": "****",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
/usr/bin/az account set --subscription 5b2da6fd-4176-4c4b-9707-88537878a9c2
/usr/bin/az bicep build --file /home/vsts/work/1/drop/infra/main.bicep
/usr/bin/az account clear
The detected encoding for file '/home/vsts/work/1/drop/infra/main.json' is 'utf-8'
Starting template validation.
Deployment name is ***
(node:1631) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Template deployment validation was completed successfully.
Starting Deployment.
Deployment name is ****
```

### Full task logs with system.debug enabled

See above.

### Repro steps

```yml
steps:
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Provision Azure Function App from Bicep
              name: FunctionDeployStep
              inputs:
                deploymentScope: "Subscription"
                subscriptionId: "$(AZURE_SUBSCRIPTION_ID)"
                location: "$(AZURE_LOCATION)"
                azureResourceManagerConnection: "$(AZURE_SERVICE_CONNECTION)"
                action: "Create Or Update Resource Group"
                resourceGroupName: "${{parameters.AzureResourceGroup}}"
                templateLocation: "Linked artifact"
                csmFile: "$(Pipeline.Workspace)/drop/infra/main.bicep"
                overrideParameters: "-environmentName $(AZURE_RG_DEV) -location $(AZURE_LOCATION)"
                deploymentMode: "Incremental"
                deploymentName: $(DEPLOYMENT_NAME)
                deploymentOutputs: deployOutputs
```
