### ISSUE TITLE
[Question]: DockerCompose@0 executing in agent container

### ISSUE THREAD

**Issue by ncostello81** [microsoft/azure-pipelines-tasks#19839]
### Task name

DockerCompose

### Task version

0.238.1

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10 Enterprise

### Question

Hi, am just looking for some clarity around how the DockerCompose task behaves when executing inside an agent container. It's to assist me in investigating an issue, but I'm not sure it's an issue with the task just yet, so am raising as a Question.

So I'm using an agent container (debian:12.2-slim + Docker CE 26.1.0 + Docker Compose standalone 2.27.0) in an Azure Pipeline with the DockerCompose@0 (0.238.1) task, and am getting `##[error]EACCES: permission denied, open '/__a/.docker-compose.1714709922949.yml'` when executing the task.

The `docker create` from the Azure Pipes log reveals the bind mounts being used:

`/usr/bin/docker create --name REDACTEDCONTAINERNAME --label b0e97f --network vsts_network_38e8854cb85040abb90db84a25b7ddfe -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/agent/_work/6":"/__w/6" -v "/agent/_work/_temp":"/__w/_temp" -v "/agent/_work/_tasks":"/__w/_tasks" -v "/agent/_work/_tool":"/__t" -v "/agent/externals":"/__a/externals":ro -v "/agent/_work/.taskkey":"/__w/.taskkey" REDACTEDCONTAINERIMAGE "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"`

I can see there that /agent/externals is being mounted to /__a/externals inside the container as read-only, and that there's no other mount to /__a.

My step is configured like so:

```
- task: DockerCompose@0
  displayName: 'Build images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: REDACTED
    dockerComposeFile: '**/docker-compose.remote.yml'
    action: 'Build services'
    currentWorkingDirectory: ${{ parameters.configDir }}
    projectName: ${{ lower(variables['Build.Repository.Name']) }}
```
(I put an `ls` as a Pipe step to confirm `parameters.configDir` is indeed the working directory with my Compose YAMLs.)

It works just fine on a self-hosted VMSS, so my question is: why, when using an agent container, does the DockerCompose task generate (what I assume is) the final Compose YAML in /__a of all places?? (Or maybe why does the task think that the final Compose YAML is in /__a?)

(Just for clarity on Environment Type, this is Microsoft-hosted Azure DevOps with agent containers running on self-hosted VMSS pool.)
