### ISSUE TITLE
[BUG]: SqlAzureDacpacDeployment: does not server name when it contains a dot (Azure SQL Managed Instance)

### ISSUE THREAD

**Issue by RKSelvi** [microsoft/azure-pipelines-tasks#19871]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

SqlAzureDacpacDeployment@1

### Issue Description

This DevOps task SqlAzureDacpacDeployment@1 is not taking into consideration for the Azure SQL Managed Instance where the host name contains a alpha numeric in its name. For e.g. host name is
azure-smi-name.**1134rt4445556**.database.usgovcloudapi.net

Because of this when the server name is parsed, it is only taking azure-smi-name as the SQL server name whereas it is actually azure-smi-name.**1134rt4445556**

Getting this error as it has split with the first dot in the provided server name.
##[debug]System.Management.Automation.RuntimeException: System.Management.Automation.RuntimeException: No resource found with serverName azure-smi-name, serverType Microsoft.Sql/servers in subscription . Specify the correct serverName/serverType and try again.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Windows Server 2019

### Relevant log output

```shell
##[debug]System.Management.Automation.RuntimeException: System.Management.Automation.RuntimeException: No resource found with serverName azure-smi-name, serverType Microsoft.Sql/servers in subscription . Specify the correct serverName/serverType and try again.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[error]System.Management.Automation.RuntimeException: No resource found with serverName azure-smi-name, serverType Microsoft.Sql/servers in subscription . Specify the correct serverName/serverType and try again.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'DEV'
        AuthenticationType: 'servicePrincipal'
        ServerName: 'azure-smi-name.1134rt4445556.database.usgovcloudapi.net'
        DatabaseName: 'DB'
        deployType: 'DacpacTask'
        DeploymentAction: 'Publish'
        DacpacFile: 'DB.dacpac'
```
