### ISSUE TITLE
[BUG]: PublishCodeCoverageResults@2 Error during reading file 

### ISSUE THREAD

**Issue by groogiam** [microsoft/azure-pipelines-tasks#19901]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishCodeCoverageResults@2

### Task version

2.238.1

### Issue Description

I recently installed the .NET 8 SDK on my build server and now this task no longer works. Please note my projects still Target .NET 7 and compile without issue. The DotNetCoreCLI@2 tests execution runs without issue as well.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Relevant log output

```shell
2024-05-22T18:12:49: Error during reading file 'https://dev.azure.com/MyOrg/MyProject/_apis/git/repositories/my-repo/items?api-version=1.0&versionType=commit&version=sha1&path=/src/MyProject/MyFile.cs': Response status code does not indicate success: 500 (Internal Server Error).
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: DotNetCoreCLI@2
    displayName: Unit Test Sandbox
    inputs:
      command: test
      projects: '**/*[Tt]ests/*.csproj'
      arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --settings src/MyProject.Tests/ci.runsettings --blame-hang-timeout 120s --blame-hang-dump-type full --blame-crash-dump-type full --filter IgnoreCi!=true${{ parameters.additionalTestFilters }}'
  
  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage Report'
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
```
