### ISSUE TITLE
[BUG]: Task Group using IIS web app manage task

### ISSUE THREAD

**Issue by remkm01** [microsoft/azure-pipelines-tasks#19987]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

IIS web app manage

### Task version

0.*

### Issue Description

Trying to create a Task Group using the IIS web app manage task. I have the task configured type set to IIS Application Pool and filled in 2 fields with variables.

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/5065217/54659885-1cf8-4b2c-8b4e-f2afec8fbad2)

Saved the task group. 

Then, I wanted to make $(AppCmds) optional. Using the Azure DevOps API (https://dev.azure.com/{our subscription}/{my project collectdion}/_apis/distributedtask/taskgroups/{task group id}?api-version=7.1-preview.1), I updated the $(AppCmd) input parameter with "visibleRule": "AppCmds != ''" like so:

		{
			"aliases": [],
			"options": {},
			"properties": {},
			"name": "AppCmds",
			"label": "AppCmds",
			"defaultValue": "$(AppCmds)",
			"required": true,
			"type": "multiLine",
			"helpMarkDown": "",
			**"visibleRule": "AppCmds != ''",**
			"groupName": ""
		},
Posted without issues.

When viewing the Task Group after hitting the refresh button, the IIS web app manage task resets:

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/5065217/6a2f94d1-122f-4e26-ada7-6866501028b6)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

N/A

### Operation system

N/A

### Relevant log output

```shell
There are no logs.
```

### Full task logs with system.debug enabled

N/A

### Repro steps

```yml
# Not using YAML, but here is what I'm setting.
steps:
- task: IISWebAppManagementOnMachineGroup@0
  displayName: 'Manage IISApplicationPool'
  inputs:
    IISDeploymentType: IISApplicationPool
    AppPoolName: '$(AppPoolName)'
    AppCmdCommands: '$(AppCmds)'
```
