### ISSUE TITLE
[BUG]: IISWebAppManagementOnMachineGroup@0 accepts physical paths with forward slashes ('/')

### ISSUE THREAD

**Issue by pasisavolainen** [microsoft/azure-pipelines-tasks#19984]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

IISWebAppManagementOnMachineGroup

### Task version

0

### Issue Description

IISWebAppManagementOnMachineGroup should not accept physical paths with forward slashes, `/`.

They don't work correctly (at least on IIS-8.5):
 - application created correctly under 'Default Web Site'
 - application pool created correctly, starts up (seen as correct username on w3wp.exe worker in taskman)
 - all calls to website result in 404, goes into iis web core trying resolve a file from filesystem (however will not accept physical files corresponding to queries)
 - no actual visible errors anywhere in eventlog/
 - Failed Request Tracing catches the 404 but doesn't show any pathing issues
 - changing application path (Basic Settings -> Physical path) to have backslashes corrects action

### Why this is pipeline task issue?

With yml 'unclear' (= fookin murky) slash/escape situation the pressure to use forward slashes is high and this mistake is easy make. Also fat chance getting this kind of issue fixed in IIS.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Relevant log output

```shell
-
```

### Repro steps

```yml
# deploysource.path is simple identifier like 'productminimal'
# parameters.websiteName is 'Default Web Site'
- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebApplication'
    ParentWebsiteNameForApplication: ${{ parameters.websiteName }}
    VirtualPathForApplication: '/${{ deploysource.Path }}'
    # no wok:
    #WebsitePhysicalPath: 'D:/app/slab/product/${{ deploysource.Path }}/$(BuildPackageVersion)'
    # yes wok:
    WebsitePhysicalPath: 'D:\app\slab\product\${{ deploysource.Path }}\$(BuildPackageVersion)'
    PhysicalPathForApplication: 'D:\app\slab\product\${{ deploysource.Path }}\$(BuildPackageVersion)'
    CreateOrUpdateAppPoolForApplication: true
    AppPoolNameForApplication: '${{ deploysource.path }}_AppPool'
    DotNetVersionForApplication: 'No Managed Code'
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: Deploying IIS WebApp from $(Build.ArtifactStagingDirectory)/deploy/${{ deploysource.path}}
  inputs:
    WebSiteName: '${{ parameters.websiteName }}/${{ deploysource.path }}'
    Package: '$(Build.ArtifactStagingDirectory)/deploy/${{ deploysource.path}}'
```
