### ISSUE TITLE
[BUG]: HelmDeploy@0 ignores environment

### ISSUE THREAD

**Issue by PAKalucki** [microsoft/azure-pipelines-tasks#20011]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy@0 

### Task version

0.238.1

### Issue Description

I have environment with resources created and I have confirmed that it created service connection. HelmDeploy@0 ignores environment and requires kubernetesServiceEndpoint. This is inconsistent with other kubernetes related tasks like Kubernetes@1 where it automatically picks up the service connection from environment.
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/11369174/315e6474-7424-4697-b603-f1db64404b5a)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
Starting: Helm upgrade
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.238.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Input required: kubernetesServiceEndpoint
Finishing: Helm upgrade
```

### Repro steps

```yml
jobs:
  - deployment: Deploy
    displayName: Deploy to Kubernetes
    pool:
      vmImage: ubuntu-latest
    environment: 
      name: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:
              namespace: ${{ parameters.namespace }}
              command: upgrade
              chartType: filepath
              chartPath: ./charts/${{ parameters.project_name }}
              releaseName: ${{ parameters.project_name }}
              install: true
              waitForExecution: true
              valueFile: ./charts/${{ parameters.project_name }}/${{ parameters.values }}
              overrideValues: |
                image.repository=${{ parameters.repository }}
                image.tag=${{ parameters.tag }}
                env=${{ parameters.env_name }}
```
