### ISSUE TITLE
[enhancement]: Run Maven@4 task in detached mode

### ISSUE THREAD

**Issue by tomaytotomato** [microsoft/azure-pipelines-tasks#20044]
### Describe your feature request here

It would be nice to have an option to detach a maven process, so that we can start a webservice and have it running as a background task.

Usecases:

- Integration tests
- Generating OpenAPI.yml files from running webservice

In this example, I am currently using a script to start the webservice and then run the OpenApi Generate task afterwards

```yaml
  - stage: PublishOpenAPI
#    dependsOn: Build
    displayName: Publish OpenAPI Specification
    jobs:
      - job: publishOpenAPI
        displayName: Publish OpenAPI Spec
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled' # Use 'PreInstalled' or 'AzureStorage' based on availability
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(MAVEN_CACHE_FOLDER)
          - script: |
              echo "Starting Spring Boot application in the background..."
              mvn -f server/pom.xml spring-boot:run &
              SPRING_PID=$!
              echo "Waiting for the Spring Boot application to start..."
              sleep 10
          - task: Maven@4
            displayName: Generate OpenApi.yml from service
            inputs:
              mavenPomFile: 'server/pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              jdkVersionOption: $(JAVA_VERSION)
              javaHomeOption: 'JDKVersion'
              goals: 'springdoc-openapi:generate'
              options: '-B -e'
          - publish: server/target/openapi.yml
            artifact: OpenAPI
 ```
 
 
 Maybe we could have an option in inputs like
 
 `detach: true` 
 
 This would effectively just do the following
 
 ```
 mvn ${mvnOptions} ${mvnGoal} &
 ```

The `&` is Unix specific but for Windows it would do a similar thing
