### ISSUE TITLE
[Question]: Why is mvn clean enforced for code coverage? 

### ISSUE THREAD

**Issue by honnel** [microsoft/azure-pipelines-tasks#20056]
### Task name

MavenV4

### Task version

v237

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest, Azure Pipelines 3

### Question

We use MavenV4 in our azure devops pipeline in several successive tasks.
First task runs `compile` and a second one runs `verify` including code coverage. Our current approach is to reuse the result of the compile task (class Files) in the verify task without rebuilding the hole project:

```yaml
  - task: Maven@4
    displayName: 'Build'
    inputs:
      goals: compile
      ...

  - task: Maven@4
    displayName: 'Verify
    Input:
      goals: verify
      options: '-Dclean.skip=true'.
      codeCoverageToolOption: 'JaCoCo'
      ...
```

This workaround with `-Dclean.skip=true` is used because `clean` is enforced [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV4/maventask.ts#L243) 

Why is this `clean` enforced with code coverage enabled?

Perhaps @Roman-Shchukin?
