### ISSUE TITLE
[BUG]: FuncToolsInstaller@0 does not chmod +x the in-proc8/func binary

### ISSUE THREAD

**Issue by fbraam** [microsoft/azure-pipelines-tasks#20084]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

FuncToolsInstaller

### Task version

0.238.1

### Issue Description

FuncToolsInstaller@0 does not chmod +x the `in-proc8/func` binary, which causes `func start` to fail with an error:

> Failed to start the in-process model host. An error occurred trying to start process '/opt/hostedtoolcache/func/4.0.5907/x64/in-proc8/func' with working directory '/home/vsts/work/1/s/src/<snip>/bin/output'. Permission denied

See https://github.com/microsoft/azure-pipelines-tasks/blob/d940afa26c664170bf7bc1a7313eef17aa50e44b/Tasks/FuncToolsInstallerV0/src/utils.ts#L77 where only the main `func` is made executable but not the new executable for .NET 8 in-process function apps (located at `in-proc8/func`). 

See also https://github.com/Azure/azure-functions-core-tools/blob/2b6ba6e7b0941a40e2e34694db784c3450a12b11/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L493 and https://github.com/Azure/azure-functions-core-tools/issues/3713 for reference.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22

### Relevant log output

```shell
Failed to start the in-process model host. An error occurred trying to start process '/opt/hostedtoolcache/func/4.0.5907/x64/in-proc8/func' with working directory '/home/vsts/work/1/s/src/<snip>/bin/output'. Permission denied
```

### Repro steps

```yml
- task: FuncToolsInstaller@0
  displayName: Install function app tools
  inputs:
    version: "4.0.5907"

# This task is shortened to show only the relevant part where it is failing
- task: PowerShell@2
  displayName: Start the function app
  inputs:
    pwsh: true
    targetType: "inline"
    script: |
      func start
```

**Comment by ThomasBleijendaal** [comment]
Can somebody take a look at this? To work around this issue we have to pin the version and do the chmod ourselves, which isn't really future-proof:

```yaml
- task: FuncToolsInstaller@0
  displayName: Install function app tools
  inputs:
    version: "4.0.5907"
- task: PowerShell@2
  displayName: Fix file permissions
  inputs:
    targetType: "inline"
    script: |
      chmod +x /opt/hostedtoolcache/func/4.0.5907/x64/in-proc8/func
```
