### ISSUE TITLE
[BUG]: NuGetToolInstaller@1 installed nuget.exe but the next task can't find it if build agent is Ubuntu

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/azure-pipelines-tasks#20163]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task version

1.238.1

### Issue Description

I have these tasks in pipeline, firstly it install nuget and then use a PowerShell script to call nuget.exe to install package.

```yaml
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 6.*'
    inputs:
      versionSpec: '6.*'
  - task: NuGetAuthenticate@1
  - task: PowerShell@2
    displayName: 'Install package'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      targetType: filePath
      filePath: ...
      arguments: ...
 ```

It's working fine when I use a Windows build agent.
But if I changed to use Ubuntu build agent, 'install package' task threw an error, 

     | Exception calling "Start" with "0" argument(s): "An error occurred
     | trying to start process 'nuget.exe' with working directory
     | '/mnt/vss/_work/1/s'. No such file or directory"

The difference of NuGetToolInstaller log between Windows and Ubuntu build agent:
* NuGetToolInstaller log on Windows build agent

  _Downloading: https://dist.nuget.org/win-x86-commandline/v6.10.1/nuget.exe Caching tool: NuGet 6.10.1 x64
  Using version: 6.10.1
  Found tool in cache: NuGet 6.10.1 x64
  Using tool path: C:\hostedtoolcache\windows\NuGet\6.10.1\x64
  Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\NuGet\6.10.1\x64
  Finishing: Use NuGet 6.*_

* NuGetToolInstaller log on Ubuntu build agent

  _Downloading: https://dist.nuget.org/win-x86-commandline/v6.10.1/nuget.exe
  Caching tool: NuGet 6.10.1 x64
  Using version: 6.10.1
  Found tool in cache: NuGet 6.10.1 x64
  Using tool path: /opt/hostedtoolcache/NuGet/6.10.1/x64
  Prepending PATH environment variable with directory: /opt/hostedtoolcache/NuGet/6.10.1/x64
  Finishing: Use NuGet 6.*_

I suspected the problem is due to environment variable was not "refreshed" or "updated" on Ubuntu build agent.

I'm using a workaround now: 🩹
  before calling nuget.exe, have another task to find it and update permission, 
```
$nuget = (Get-Command nuget.exe).Source   
& chmod +x $nuget
```
, and in the task to install package, pass `(Get-Command nuget.exe).Source` as parameter to the PowerShell script.  

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11, Ubuntu

### Relevant log output

```shell
| Exception calling "Start" with "0" argument(s): "An error occurred
 | trying to start process 'nuget.exe' with working directory
 | '/mnt/vss/_work/1/s'. No such file or directory"
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
