### ISSUE TITLE
Facing the version not valid issue in azure pipeline.

### ISSUE THREAD

**Issue by Ranjithsyncfusion** [microsoft/azure-pipelines-tasks#20172]
### Task name

PublishToAzureServiceBus@2

### Task version

2.241.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Ubuntu-lates and windows-latest

### Question

```shell
Why I am facing the below issue while try to sent a custom messages form Azure DevOps pipeline to Azure Bus Service Queue.

issue: Job ExampleJob: Step references task 'PublishToAzureServiceBus' at version '2.241.1' which is not valid for the given job target.
```

**Comment by RobHofmann** [comment]
Same here!
```yaml
                - task: PublishToAzureServiceBus@2
                  inputs:
                    azureSubscription: myconnectionstring
                    serviceBusQueueName: myqueue
                    serviceBusNamespace: mynamespace
                    messageBody: |
                      {
                         "eventType":"Something.Something"
                      }
                    signPayload: false
                    waitForCompletion: true
                    useDataContractSerializer: true
```

Getting this error:
```
Job deployPolicyJob: Step references task 'PublishToAzureServiceBus' at version '2.241.1' which is not valid for the given job target.
```

Any fixes/workarrounds?
