### ISSUE TITLE
[Question]: Is it possible to define HTTP response code for `successCriteria`?

### ISSUE THREAD

**Issue by balcsida** [microsoft/azure-pipelines-tasks#20194]
### Task name

InvokeRESTAPI

### Task version

1.220.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container
- [x] Server

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

N/A

### Question

Hey there,
I would like to use InvokeRESTAPI to check if a resource group doesn't exist on Azure.

Here is an excerpt from my pipeline:

```
  - job: Check_If_VM_Group_Exists
    displayName: "Does ${{ variables.vm_name }} exists?"
    timeoutInMinutes: 1
    pool: server
    steps:
      - task: InvokeRESTAPI@1
        displayName: "Verify if Resource Group '${{ variables.vm_name }}' exists"
        inputs:
          method: 'GET'
          connectionType: connectedServiceNameARM
          azureServiceConnection: ${{ variables.azure_subscription_service_connection }}
          urlSuffix: 'subscriptions/${{ variables.subscriptionId }}/resourceGroups/${{ variables.vm_name }}?api-version=2021-04-01'
```

However, I don't know how to specify a `successCriteria`, so it would pass if the HTTP code is NOT 200.

Currently, I receive the following if the Resource Group doesn't exist:

```
Response Code: 0
				Response: An error was encountered while processing request. Exception: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'testrg' could not be found."}}
Exception Message: The remote server returned an error: (404) Not Found. (type WebException)
```

The reason why I don't use the AzureCLI task is as it is a lot slower compared to InvokeRESTAPI, and it also can run on the server - so if the Resource Group exists, we don't need to spin up an Agent for this simple check.

Now what I'm doing is that I have a second job which has this set:
```
    dependsOn: Check_If_VM_Group_Exists
    condition: failed()
```
This kind of works, but not really nice and it makes the whole pipeline run fail

Is it possible to define HTTP response code for `successCriteria`?
