### ISSUE TITLE
[BUG]: GithubRelease@1 does not correctly overwrite release assets

### ISSUE THREAD

**Issue by jcelerier** [microsoft/azure-pipelines-tasks#20198]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

GithubRelease

### Task version

1

### Issue Description

I have the following task:

```
          - task: GitHubRelease@1
            condition: and(succeeded(), eq(variables.isMaster, true))
            inputs:
              gitHubConnection: github.com_jcelerier
              repositoryName: ossia/score
              action: "edit"
              target: "$(Build.SourceVersion)"
              tag: "continuous"
              assets: "$(System.DefaultWorkingDirectory)/*"
              tagSource: userSpecifiedTag
              title: "Continuous build"
              assetUploadMode: "replace"
              isPreRelease: true
```

Here's an example run : 

https://dev.azure.com/ossia/libossia/_build/results?buildId=3945&view=logs&j=d3280fad-0e55-5adf-7e56-53b7a94fcec5&t=cf82947e-8334-5584-a78a-8c050ef27544

In the run it says for instance: 

```
Uploading file: '/home/vsts/work/1/s/ossia score-master-linux-amd64.AppImage'.
Duplicate asset found: /home/vsts/work/1/s/ossia score-master-linux-amd64.AppImage
Deleting duplicate asset: /home/vsts/work/1/s/ossia score-master-linux-amd64.AppImage
```

But I think it fails at deleting it: in said build, the assets generated by azure (for instance 
ossia.score-master-linux-amd64.AppImage) haven't been updated in two weeks: https://github.com/ossia/score/releases/tag/continuous 
I have some other files that come from Github Actions, which on its side is able to correctly replace the files with newer versions.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
https://dev.azure.com/ossia/libossia/_build/results?buildId=3945&view=logs&j=d3280fad-0e55-5adf-7e56-53b7a94fcec5&t=cf82947e-8334-5584-a78a-8c050ef27544
```
