### ISSUE TITLE
[BUG]: "##[warning]Can't find loc string for key: Info_GotAndMaskAuth" started appearing after Universal Packages was updated to 0.243.1

### ISSUE THREAD

**Issue by shiraze** [microsoft/azure-pipelines-tasks#20203]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Universal packages

### Task version

0.243.1

### Issue Description

I get warning like the following after Universal Packages have been updated to v`0.243.1`:

> ##[warning]Can't find loc string for key: Info_GotAndMaskAuth
Downloading: https://04pvsblobproduks120.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.350.zip?sv=2019-07-07&sr=b&sig=-REDACTED-&spr=https&se=2024-07-25T09%3A43%3A32Z&sp=r&P1=1721900312&P2=11&P3=2&P4=UVqeSQwPk1GYhKg7VZU6J35zISSLq2BpYsCBcbnFyus%3d
Caching tool: ArtifactTool 0.2.350 x64
##[warning]Can't find loc string for key: Info_GotAndMaskAuth

No changes were made to the pipeline, and these warning were not shown when using `Universal Packages` version `0.239.1`

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
##[warning]Can't find loc string for key: Info_GotAndMaskAuth
Downloading: https://04pvsblobproduks120.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.350.zip?sv=2019-07-07&sr=b&sig=-REDACTED-&spr=https&se=2024-07-25T09%3A43%3A32Z&sp=r&P1=1721900312&P2=11&P3=2&P4=UVqeSQwPk1GYhKg7VZU6J35zISSLq2BpYsCBcbnFyus%3d
Caching tool: ArtifactTool 0.2.350 x64
##[warning]Can't find loc string for key: Info_GotAndMaskAuth
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  - task: UniversalPackages@0
    displayName: Get build-tools
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)\tools'
      feedsToUse: 'internal'
      vstsFeed: '9995297e-a424-4e13-b607-d51b434e1d4c'
      vstsFeedPackage: '65f008f1-d7f6-49c4-a8d5-02b3dc76b98c'
      vstsPackageVersion: '*'


  - task: UniversalPackages@0
    inputs:
      command: "publish"
      publishDirectory: '$(Build.StagingDirectory)\package'
      feedsToUsePublish: "internal"
      vstsFeedPublish: "4969b139-6618-4f41-9089-a75c46d25e61/cf675289-cd56-4a59-ade0-a71e193f9cc8"
      vstsFeedPackagePublish: 'something'
      versionOption: "patch"
      packagePublishDescription: 'some message'
```
