### ISSUE TITLE
[BUG]: ##[warning]Resource file has already set to: /agent/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.241.5/node_modules/azure-pipelines-tasks-azure-arm-rest/module.json

### ISSUE THREAD

**Issue by iondrugalea** [microsoft/azure-pipelines-tasks#20224]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Kubernetes@1

### Task version

1

### Issue Description

A bug happened!
I use in my azure devops pipline the task Kubernetes@1 for diferent use cases. Since about 1 Month i see this warning everytime when the Kubernetes@1 is executed. I call the Kubernetes@1 multiple times and each time i see this warning. 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
##[warning]Resource file has already set to: /agent/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.241.5/node_modules/azure-pipelines-tasks-azure-arm-rest/module.json
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: Kubernetes@1
    displayName: 
    inputs:
      connectionType: "Kubernetes Service Connection"
      kubernetesServiceEndpoint: " ${{ parameters.kubernetesServiceEndpoint }}"
      command: "apply"
      useConfigurationFile: true
      configuration: 
      arguments: 
      namespace:
```
