### ISSUE TITLE
[BUG]: .artifactignore file is uploaded itself on windows build agents

### ISSUE THREAD

**Issue by devops-ninja2021** [microsoft/azure-pipelines-tasks#20266]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishPipelineArtifact@1

### Task version

1.242.0

### Issue Description

For publishing the pipeline run results, we use the task PublishPipelineArtifact@1. Before publishing we put a _.artifactignore_ into the targetPath. On windows build agents the _.artifactignore_ file itself is uploaded as a artifact with the publish task. On linux/macos build agents it doesn't happen.
There should be uploaded 2 artifacts, but it processes 3 files. See log for details.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2022

### Relevant log output

```shell
Uploading pipeline artifact from D:\a\1\a for build #34965
Using default max parallelism.
Max dedup parallelism: 192
DomainId: 0
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session XXX
Hashtype: Dedup64K
DedupManifestArtifactClient will correlate http requests with X-TFS-Session XXX
Using .artifactignore file located at: D:\a\1\a\.artifactignore for globbing
3 files processed.
Processed 3 files from D:\a\1\a successfully.
Uploading 3 files from directory D:\a\1\a.
Uploaded 84,620,454 out of 274,285,546 bytes.
Uploaded 154,613,012 out of 274,286,057 bytes
Content upload is done!

Content upload statistics:
Total Content: 548.6 MB
Physical Content Uploaded: 154.0 MB
Logical Content Uploaded: 154.6 MB
Compression Saved: 0.6 MB
Deduplication Saved: 394.0 MB
Number of Chunks Uploaded: 1,965
Total Number of Chunks: 13,641

Associated artifact 41306 with build 34965
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session XXX
Uploading pipeline artifact finished.
Finishing: Publish artifacts
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
parameters:
- name: artifactsDirectory
  type: string
  default: '$(Build.ArtifactStagingDirectory)'
- name: artifactName
  type: string
  default: drop

steps:
  - script: |
      echo **/node_modules/ >> .artifactignore
      echo **/.git/ >> .artifactignore
      echo **/.npmrc >> .artifactignore
      echo **/.artifactignore >> .artifactignore
    displayName: Ignore node_modules and .git folder during upload
    workingDirectory: ${{ parameters.artifactsDirectory }}

  - task: PublishPipelineArtifact@1
    displayName: Publish artifacts
    condition: succeeded()
    inputs:
      artifact: ${{ parameters.artifactName }}
      targetPath: ${{ parameters.artifactsDirectory }}
```
