### ISSUE TITLE
[BUG]: DockerCompose@1 failed with Version mismatch error

### ISSUE THREAD

**Issue by CharanGali** [microsoft/azure-pipelines-tasks#20275]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DockerCompose

### Task version

1.243.1

### Issue Description

A bug happened!

While using the task DockerCompose@1, received below error and failed

##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Relevant log output

```shell
While using the task DockerCompose@1, received below error and failed

##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1
```

### Full task logs with system.debug enabled

While using the task DockerCompose@1, received below error and failed

##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1

### Repro steps

```yml
While using the task DockerCompose@1, received below error and failed

##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1
```

**Comment by CharanGali** [comment]
@ivanduplenskikh

Could you please help us to sort as this occurred after latest changes done to this task

**Comment by ivanduplenskikh** [comment]
@CharanGali, since [**version** property is obsolete](https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete), the temporary fix is removing the version property from your own docker compose file if this error is blocking for you.
[The PR](https://github.com/microsoft/azure-pipelines-tasks/pull/20197) that removes the **version** property from generated YAML files has been merged and already released.

Could you please provide a minimal example with a pipeline and a docker-compose YAML file to reproduce it?

**Comment by CharanGali** [comment]
@ivanduplenskikh Thanks for your response and below is the requested information.

We have used the below task in pipeline.

   ```
 - task: DockerCompose@1
      displayName: 'Run a Docker Compose command'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: '<<Registry Name>>'
        dockerComposeFile: 'Sources\Integration Tests\Docker\docker-compose-win2022.yml'
        dockerComposePath : '$(dockerComposePath)\docker-compose.exe'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
        arguments: '-d'
```

docker-compose-win2022.yml file contents are as below
```
version: '3.9'
services:
  siteserver:    
    container_name: tests
    image: <<CustomImageName from above registry>>
    ports:
      - "1433:1433"
    volumes:
        - type: bind
          source: c:/sites
          target: c:/sitesmount

```

Also, we have tried to remove the version from above docker file - still we receive the same message.
```
##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1
```

Could you please help us ?

**Comment by CharanGali** [comment]
@ivanduplenskikh 

Also, to add on - when we remove the dockercomposepath from task. we receive error as `##[error]The process 'C:\Windows\system32\docker.exe' failed with exit code 15`

**Comment by ivanduplenskikh** [comment]
@CharanGali, you have four different errors and warnings in this case.

---
### The warning message about different version properties in YAML
The message about different version in your pipeline output indicates that you have two different versions in a generated task's YAML and your **docker-compose-win2022.yml** YAML

```bash
##[error]Version mismatch: file D:\a\1\s\Sources\Integration Tests\Docker\docker-compose-win2022.yml specifies version 3.9 but extension file C:\agents\3.242.1\.docker-compose.1723125556266.yml uses version 1
```

You can resolve this by removing the **version** property from your YAML.
Additionally, you mentioned that you use DockerCompose task v1.243.1 but this version of task doesn't include the version property in the generated YAML file. This issue was fixed in #20197.
I've tested it on my own pipeline, and didn't encounter any errors, except for the default warning message from Docker.

```bash
time="2024-08-13T13:14:13+02:00" level=warning msg="C:\\a\\_work\\1\\s\\DockerComposeV0\\docker-compose-win2022.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
```

This default Docker warning message means that you don't need to specify the version.

---
### Exit code 1
The error in your output indicates that your container terminated due to a problem with an image, an invalid reference, or a similar issue.
You can [enable the system diagnostics checkbox](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent#configure-verbose-logs) in your pipeline to obtain more detailed information about your error.
Additionally, you might want to try executing the docker compose command locally to check your environment and determine whether you can use this docker compose YAML file without errors.

```bash
##[error]The process 'C:\ProgramData\docker-compose\docker-compose.exe' failed with exit code 1
```

---
### The problem with **dockerComposePath** input

You mentioned that you removed the version from Docker file and still received the message that the compose path is not found.

```bash
##[error]Unhandled: Unable to locate executable file: 'C:\ProgramData\docker-compose\docker-compose.exe'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

The version property doesn't affect this input. This error usually appears when there are no Docker Compose instances at the specified path.
In your case you should have the Docker Compose executable located at `C:\ProgramData\docker-compose\docker-compose.exe`.

---

### Exit code 15

I see that your next step was deleting the **dockerComposePath** input, which helped you proceed with task interaction, but you encountered another error.

```bash
##[error]The process 'C:\Windows\system32\docker.exe' failed with exit code 15
```

This exit code usually appears when you have a project name that doesn't pass the [strict Docker Compose constraints for project names](https://docs.docker.com/compose/project-name/#set-a-project-name).
The default behavior for the Docker Compose utility in this task is to indicate an exit code. If you want to get a detailed information you can [enable the system diagnostics checkbox](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent#configure-verbose-logs) in your pipeline to obtain more detailed information about your error.
To avoid this situation, you may [specify projectName input](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-compose-v1?view=azure-pipelines#:~:text=projectName%20%2D%20Project%20Name) in your pipeline.

---

Here is my minimal working example based on yours. In this example Docker Compose doesn't produce any warnings or errors.

### service.yml

```yaml
services:
  service:
    image: ubuntu:latest
```

### azure-pipelines.yml

```yaml

variables:
  - name: System.Debug
    value: true

steps:
  - task: DockerCompose@1
    displayName: Run a Docker Compose command
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: './service.yml'
      action: 'Run a Docker Compose command'
      projectName: 'test'
      dockerComposeCommand: 'up'
      arguments: '-d'
```
