### ISSUE TITLE
[BUG]: AzureFunctionApp is not accepting package variable correctly

### ISSUE THREAD

**Issue by eddynaka** [microsoft/azure-pipelines-tasks#20285]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp 

### Task version

1.244.1

### Issue Description

In a build pipeline, in yml, I have the following task:
```yml
          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy: Processor'
            inputs:
              azureSubscription: '1ES-SecurityDetectionServices-Deployment-GitHub-PME'
              appType: functionApp
              appName: GitHubSecretsProcessor
              deployToSlotOrASE: true
              resourceGroupName: GitHubSecretsProcessor
              slotName: stage
              package: '$(Build.ArtifactStagingDirectory)/Zip/Publish-Function-Processor.zip'
              deploymentMethod: zipDeploy
```

When the task executed, it failed, so I enabled verbose and it showed the following:
```
##[error]Error: No package found with specified pattern: D:\a\_work\1\s\$(System.ArtifactStagingDirectory)\Zip\Publish-Function-Processor.zip<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job.
```

As you can see, it concatenated the package location with source directory.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
##[error]Error: No package found with specified pattern: D:\a\_work\1\s\$(System.ArtifactStagingDirectory)\Zip\Publish-Function-Processor.zip<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
