### ISSUE TITLE
[enhancement]: Allow Options to be passed to Compose

### ISSUE THREAD

**Issue by cnelsonakgov** [microsoft/azure-pipelines-tasks#20298]
### Task name

DockerCompose

### Describe your feature request here

Currently one can pass argument to the compose action, but not options to the compose command itself. For example, trying to pass the `--env-file` option.

One can try to use `arguments` but it puts the option in the wrong place. For instance:

```
- task: DockerCompose@1
  displayName: Run app Service
  inputs:
    action: Run a specific service
    projectName: my-app 
    serviceName: app
    dockerComposeFile: compose.yaml
    ports: 5432:5432
    arguments: --env-file .env

```
produces the following command:
`docker compose -f compose.yaml -p my-app run -d -p 5432:5432 -T app --env-file .env`

Unfortunately, this doesn't work as the command we want is actually:
`docker compose --env-file .env -f compose.yaml -p my-app run -d -p 5432:5432 -T app`
