### ISSUE TITLE
[REGRESSION]: DotNetCoreCLI - Restore with external feed does not properly authenticate anymore

### ISSUE THREAD

**Issue by Tech-Non** [microsoft/azure-pipelines-tasks#20347]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DotNetCoreCLI@2

### Breaking task version

2.244.1

### Last working task version

2.242.1

### Regression Description

I have a bit of a weird setup with a nuget feed in one Azure DevOps organization and a pipeline in another organization that needs the feed to restore a project.
about 3 hours ago this step worked fine but now it only logs the following message for these resources:

`1>/agent/_work/2/s/PROJECT.Infrastructure.Persistence/RPOJECT.Infrastructure.Persistence.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FEED_URL/nuget/v3/index.json. [/agent/_work/2/s/PROJECT.API/PROJECT.API.csproj]`

Code-wise there have been no changes and the only thing I can see has changed is the version of the task going up to 2.244.1

For reference, this is the task:
```yaml
  - task: DotNetCoreCLI@2
    displayName: 'Restore .NET dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: config
      nugetConfigPath: 'nuget.config'
    env:
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"$(nugetFeedUrl)", "username":"AzureDevOps", "password":"$(personal_access_token)"}]}'
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
`1>/agent/_work/2/s/PROJECT.Infrastructure.Persistence/RPOJECT.Infrastructure.Persistence.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FEED_URL/nuget/v3/index.json. [/agent/_work/2/s/PROJECT.API/PROJECT.API.csproj]`
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
