### ISSUE TITLE
[Question]: Azure Pipeline how to do vercel deployment? 

### ISSUE THREAD

**Issue by atalayio** [microsoft/azure-pipelines-tasks#20345]
### Task name

vercel-deployment-task@1

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Question

```shell
When I try to vercel deployment with azure pipeline it giving me this error: 

Unable to locate executable file: 'vercel'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file
```

**Comment by atalayio** [comment]
Here my yml file: 
```yml
trigger:
- main

pool: Default

steps:
- task: vercel-deployment-task@1
  inputs:
    vercelProjectId: myProjectId
    vercelOrgId: myOrgId
    vercelToken: myToken
    production: true
    ```
