### ISSUE TITLE
[BUG]: DockerCompose@1 error pulling from private repository: 401 Unauthorized 

### ISSUE THREAD

**Issue by mrlioncub** [microsoft/azure-pipelines-tasks#20406]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DockerCompose@1

### Task version

1.243.1

### Issue Description

Authentication to the private repository task does not work.

I have 2 private repositories.
Dockerfile uses an image from the first repo.
DockerCompose@1 builds with the qualityImageNames option for the second repo

Dockerfile:
`FROM private.repo1.net/alpine`

docker-compose.yaml:
```
services:
  test:
    image: test/test
    build:
      context: .
      dockerfile: Dockerfile
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

```shell
##[error]failed to solve: private.repo1.net/alpine: failed to resolve source metadata for private.repo1.net/alpine:latest: unexpected status from HEAD request to ***alpine/manifests/latest: 401 Unauthorized
##[error]The process '/usr/bin/***' failed with exit code 17
```

### Full task logs with system.debug enabled

<details>
<pre>  /usr/bin/*** compose -f /home/vsts/work/1/s/compose/***-compose.build.yml -f /home/vsts/agents/3.243.1/.***-compose.1725988929615.yml build
  #0 building with "default" instance using *** driver
  #1 [test internal] load build definition from Dockerfile
  #1 transferring ***file: 115B done
  #1 DONE 0.0s 
  #2 [test internal] load metadata for private.repo1.net/alpine:latest
  #2 ERROR: unexpected status from HEAD request to ***alpine/manifests/latest: 401 Unauthorized
  ------
   > [test internal] load metadata for private.repo1.net/alpine:latest:
  ------
  failed to solve: private.repo1.net/alpine: failed to resolve source metadata for private.repo1.net/alpine:latest: unexpected status from HEAD request to ***alpine/manifests/latest: 401 Unauthorized 
  ##[debug]Exit code 17 received from tool '/usr/bin/***'
  ##[debug]STDIO streams have closed for tool '/usr/bin/***'
  ##[error]failed to solve: private.repo1.net/alpine: failed to resolve source metadata for private.repo1.net/alpine:latest: unexpected status from HEAD request to ***alpine/manifests/latest: 401 Unauthorized
  ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=7861815f-565a-4d4f-b71b-78c567d5eb4b;]failed to solve: private.repo1.net/alpine: failed to resolve source metadata for private.repo1.net/alpine:latest: unexpected status from HEAD request to ***alpine/manifests/latest: 401 Unauthorized
  ##[debug]task result: Failed
  ##[error]The process '/usr/bin/***' failed with exit code 17
  ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=7861815f-565a-4d4f-b71b-78c567d5eb4b;]The process '/usr/bin/***' failed with exit code 17
  ##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/***' failed with exit code 17
</pre>
</details>

### Repro steps

```yml
trigger: none
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  displayName: 'private.repo1.net: login'
  inputs:
    containerRegistry: 'private.repo1.net'
    command: login
- task: DockerCompose@1
  displayName: 'docker compose build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'private.repo2.net'
    dockerComposeFile: 'docker-compose.yaml'
    action: 'Build services'
```
