### ISSUE TITLE
[Question]: How to patch a singke key-value pair in an existing ConfigMap

### ISSUE THREAD

**Issue by sdg002** [microsoft/azure-pipelines-tasks#20447]
### Task name

Kubernetes@1

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Question

```shell
I am trying to use the `Kubernetes@1` Azure Devops Task to `patch` a single name-vaue pair in an already existing `ConfigMap`


## YAML snippet

```yaml
  - task: Kubernetes@1
    displayName: 'update configmap with version'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: ${{ parameters.azserviceconnection }} # name of the Azure Service connection
      azureResourceGroup: ${{ parameters.aksresourcegroup }} # the resource group which has the AKS cluster
      kubernetesCluster: aks001-dev
      namespace: powertrading-dev
      configMapName: shared-configmap
      useConfigMapFile: false
      configMapArguments: --from-literal=key1=some_value_from_yaml
    continueOnError: false      
```

My intent is to replicate the following command:

```
kubectl --namespace powertrading-dev patch configmap shared-configmap -p  "{ \"data\" : { \"key1\" : \"some_value_from_yaml\" }}"

```

I can't get the Devops task to update a single key-value pair.   Any suggestions ?

**Comment by sdg002** [comment]
I have also tried doing a `patch` 


```yaml
  - task: Kubernetes@1
    displayName: 'update configmap with version'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: ${{ parameters.azserviceconnection }} 
      azureResourceGroup: ${{ parameters.aksresourcegroup }}
      kubernetesCluster: ${{ parameters.aksresourcename }}
      namespace: powertrading-dev
      command: patch
      arguments: "configmap shared-configmap --patch  '{\"data\": {\"key1\": \"newvalue1 from yaml\" }' "
     
```

**Comment by sdg002** [comment]
## Workaround via direct kubectl patch from PowerShell

Here is a snippet from my YAML which finally worked. 



```yaml


jobs:
- job: Deploy
  variables: 
    configpatch: '{ "data" : { "key1" : "$(Build.BuildNumber)" }}'

  - task: Kubernetes@1
    displayName: 'kubectl login'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: ${{ parameters.azserviceconnection }} # name of the Azure Service connection
      azureResourceGroup: ${{ parameters.aksresourcegroup }} # the resource group which has the AKS cluster
      kubernetesCluster: ${{ parameters.aksresourcename }} # the name of the AKS resource
      namespace: ${{ parameters.aksnamespace}}
      command: login
    continueOnError: false   

  - powershell: |
      kubectl --namespace ${{ parameters.aksnamespace}} patch configmap shared-configmap -p  '$(configpatch)'
    displayName: 'kubectl patch configmap'



```
