### ISSUE TITLE
[BUG]: Fix **Kubernetes@1** job to officially accept **command** `rollout`.

### ISSUE THREAD

**Issue by mislavmatijevic** [microsoft/azure-pipelines-tasks#20562]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Kubernetes

### Task version

1

## Description
When a command "rollout" is used with Kubernetes@1 job, the extension reports "Value is not accepted" which is completely false: job works as intended.
![Image](https://github.com/user-attachments/assets/0e150fae-143f-48e7-896f-19dfd88d1919)
_(reports "not accepted", however it does work)_

This was already reported on StackOverflow 4 years by someone else: https://stackoverflow.com/questions/64268770/azure-devops-pipeline-kubectl-task-command-rollout-unavailable

I think this misinformation really needs to get fixed. I almost ended up thinking your Kubernetes job does not accept `rollout` command and that I'd have to use "delete" on pods found via labels instead of a normal, graceful `rollout restart`.

## Actual code which needs fixing
You can see here (azure-pipelines-tasks/Tasks/KubernetesV1/task.json)(https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/task.json#L141-L154) that `rollout` is not one of the "accepted" commands, despite it being very important and working nonetheless.

I gather it'd be enough to just add the command here in the JSON object.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

MacOS

### Relevant log output

There are no logs, it's just an issue with a missing key.

### Full task logs with system.debug enabled

<details>
  <pre> N/A </pre>
</details>

**Comment by v-schhabra** [comment]
Hi @mislavmatijevic 
Could you please share your yaml pipeline by hiding the unwanted details?

**Comment by mislavmatijevic** [comment]
Hi @v-schhabra, thanks for reaching out to me!
This is my YAML pipeline file `restart-pod.yml` with unwanted details hidden:

```
parameters:
    - name: productName
      type: string
    - name: namespace
      type: string
    - name: azureSubscription 
      type: string
    - name: azureResourceGroup
      type: string
    - name: kubernetesCluster 
      type: string

steps:
    - bash: |
          #sets mock 'namespace' variable for this issue comment
          variable="${{ parameters.namespace }}-mock-for-azure-issue"
          echo "##vso[task.setvariable variable=namespace]$variable"
      displayName: Resolve namespace

    - task: Kubernetes@1
      name: RestartPod
      displayName: Restart ${{ parameters.productName }}'s pods on Kubernetes
      inputs:
          connectionType: 'Azure Resource Manager'
          useClusterAdmin: true
          azureSubscriptionEndpoint: ${{ parameters.azureSubscription }}
          azureResourceGroup: ${{ parameters.azureResourceGroup }}
          kubernetesCluster: ${{ parameters.kubernetesCluster }}
          namespace: $(namespace)
          command: rollout
          arguments: restart deployment ${{ parameters.productName }} -n $(namespace)
```
