### ISSUE TITLE
[BUG]: GitHubComment only sends one part of the variable comment

### ISSUE THREAD

**Issue by GP4cK** [microsoft/azure-pipelines-tasks#20613]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

GitHubComment

### Task version

0

### Issue Description

I have a step that parses some json with jq and stores the result in a variable. Then if the result is not empty, it should post a comment on the github PR. However, only one line is sent:

```yml
      - script: |
          jq_output=$(flutter test -r json | jq -s -r '...')
          echo "##vso[task.setVariable variable=failingTests]$jq_output"

          # if failingTests is not empty, then the tests failed
          if [ -n "$jq_output" ]; then
            echo "##vso[task.logissue type=error]Tests failed"
            echo $jq_output
            exit 1
          fi
        displayName: Run tests on Ubuntu
        workingDirectory: $(System.DefaultWorkingDirectory)
      - task: GitHubComment@0
        condition: failed()
        inputs:
          gitHubConnection: "github.com_GP4cK"
          repositoryName: "$(Build.Repository.Name)"
          comment: |
            $(failingTests)
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

In the logs of the GitHubComment step, we can see that there is only one file `test/widget_test.dart` but when I echoed the variable in the previous step, I got `test/widget_test.dart test/another_failing_test.dart`

##[debug]Endpoint scheme: OAuth
##[debug]repositoryName=GP4cK/flutter_test_az_pipeline
##[debug]id=undefined
##[debug]Build.SourceBranch=refs/heads/test
##[debug]Build.SourceBranch=refs/heads/test
##[debug]comment=test/widget_test.dart
Contents of the Comment field are empty or the PR/Issue ID is not provided
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
