### ISSUE TITLE
[REGRESSION]: FileTransform@2 v2.248.1 fails on linux machines due to an introduced new variable enabled by default

### ISSUE THREAD

**Issue by bolt-io** [microsoft/azure-pipelines-tasks#20661]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

FileTransform@2

### Breaking task version

2.248.1

### Last working task version

2.246.1

### Regression Description

A change in #20602 which included the new variable `enableXmlTransform` with `"defaultValue": true` means that all pipelines running on non-windows platforms require updating! Please implement this in a transitive way so it still works with an empty `xmlTransformationRules` value. Minor changes **should not** having breaking changes.

```json
    {
      "name": "enableXmlTransform",
      "type": "boolean",
      "label": "XML transformation",
      "required": false,
      "defaultValue": true,
      "helpMarkDown": "Config transforms will be run prior to the Variable Substitution.<br/>XML transformations are supported only for Windows platform."
    },
    {
      "name": "xmlTransformationRules",
      "type": "multiLine",
      "label": "XML Transformation rules",
      "defaultValue": "-transform **\\*.Release.config -xml **\\*.config",
      "required": false,
      "helpMarkDown": "Provide new line separated list of transformation file rules using the syntax: <br/>-transform <pathToTransformFile>  -xml <pathToSourceConfigurationFile>"
      "helpMarkDown": "Provide new line separated list of transformation file rules using the syntax: <br/>-transform <pathToTransformFile>  -xml <pathToSourceConfigurationFile>",
      "visibleRule": "enableXmlTransform == true"
    },
```

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
Starting: Update appsettings
==============================================================================
Task         : File transform
Description  : Replace tokens with variable values in XML or JSON configuration files
Version      : 2.248.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
==============================================================================
##[error]Error: Cannot perform XML transformations on a non-Windows platform.
Finishing: Update appsettings
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
Run the following task on a linux box:


      - task: FileTransform@2
        displayName: 'Update appsettings'
        inputs:
          folderPath: '$(Build.SourcesDirectory)/'
          xmlTransformationRules:
          jsonTargetFiles: '**/appsettings*.json'
```

**Comment by bolt-io** [comment]
> Hi [@bolt-io](https://github.com/bolt-io), we have overridden to the previous task version and are currently working on the fix.

Thanks for the update @EshitaD. 

Regarding overriding to the previous task version, please bear in mind that people (like myself) will have updated pipelines to the new version format of:

```yaml
      - task: FileTransform@2
        displayName: 'Update appsettings'
        inputs:
          folderPath: '$(Build.SourcesDirectory)/'
          enableXmlTransform: false
          jsonTargetFiles: '**/appsettings*.json'
```

The revert may break this task on non-windows machines as `xmlTransformationRules:` is no longer referenced and cause more friction than fix forward.

I have heard feedback that this effects only those with a null value for `xmlTransformationRules`, those explicitly specifying an empty string (`xmlTransformationRules: ''`) are not effected by the new parameter introduction.

Hope this helps.
