### ISSUE TITLE
[BUG]: HelmDeploy@1 doesn't support EntraID authentication without local accounts

### ISSUE THREAD

**Issue by avvale-sorgenia** [microsoft/azure-pipelines-tasks#20674]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy@1

### Task version

1

### Issue Description

I'm trying to use the HelmDeploy@1 task on my Azure DevOps yaml pipelines to configure my Azure Kubernetes Service.

For security reasons I am required to disable local accounts on my AKS and only use authentication with EntraID, so I have configured a Service Connection on Azure DevOps which uses a Service Principal that has been enabled on K8S as admin (we use K8S RBAC).

My HelmDeploy task looks like this:
```
          - task: KubectlInstaller@0
            displayName: 'Install kubectl'
            inputs:
              kubectlVersion: '1.30.1'

          - task: KubeloginInstaller@0
            inputs:
              kubeloginVersion: 'latest'

          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: latest

          - task: HelmDeploy@1
            displayName: 'Istio CRD Install'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(ServiceConnectionName)
              azureResourceGroup: $(ResourceGroupName)
              kubernetesCluster: $(AKSClusterName)
              command: upgrade
              chartType: 'Name'
              chartName: "istio/base"
              overrideValues: 'defaultRevision=default'
              arguments: '--create-namespace'
              namespace: 'istio-system'
              releaseName: istio-base
              install: true
              waitForExecution: false
              useClusterAdmin: false
```

Since when I disabled AKS local accounts and switched "useClusterAdmin" to false my pipeline has been failing with authentication/authorization related errors or kubelogin not found.

I think this is a bug, because I would expect the task to be able to successfully use kubectl/kubelogin to authenticate and it should not rely on local accounts being enabled on the cluster.

If it already supports this, then there is no clear documentation on how to use this task with this configuration.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 

### Relevant log output

```shell
Error: Kubernetes cluster unreachable: Get "https://CLUSTERADDRESS.hcp.westeurope.azmk8s.io:443/version": getting credentials: exec: executable kubelogin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins


kubelogin is not installed which is required to connect to AAD enabled cluster.

To learn more, please go to https://aka.ms/aks/kubelogin
```

### Repro steps

```yml

```

**Comment by bkarakashev** [comment]
@avvale-sorgenia did you manage to get this working or did you find a workaround?

**Comment by avvale-sorgenia** [comment]
Hello,
no currently the only solution I found is not using HelmDeploy task and directly use the AzCli task with:
```
az aks get-credentials ....
kubelogin
helm ....
```
This is the only way I found to make it recognize the correct authentication and authorizations when local accounts are disabled

**Comment by bkarakashev** [comment]
I actually managed to get it all working by using `connectionType: 'Azure Resource Manager'`
and disabling the `useClusterAdmin: false`.

This way the helm task executes kubelogin automatically populates the command with the necessary credentials and it all worked.

Also, I had to add the `- task: KubeloginInstaller@0` just before the helm task.

I hope this is helpful to you or anyone else who is having this problem.

**Comment by v-dko** [comment]
Issue is not reproducible and if you still facing any issue pls feel free to reopen the ticket

**Comment by v-dko** [comment]
@bkarakashev  is this issue still occurring?

**Comment by v-dko** [comment]
@avvale-sorgenia is this issue still occurring?

**Comment by v-dko** [comment]
@avvale-sorgenia  please reopen the issue if you have any queries, we are closing it as we haven't received any response

**Comment by avvale-sorgenia** [comment]
I have tested it again today. I don't know what changed but it works now with this setup:

```yaml
trigger: none

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      - group: "Dev"
  - ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
      - group: "Test"
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - group: "Prod"
  - name: AKSClusterName
    value:

stages:
  - stage: HelmInstall
    displayName: Helm Installation

    jobs:
      - job: Install
        displayName: Install
        steps:
          - task: KubectlInstaller@0
            displayName: 'Install kubectl'
            inputs:
              kubectlVersion: '1.30.1'

          - task: KubeloginInstaller@0
            inputs:
              kubeloginVersion: 'latest'

          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: latest

          - task: AzureCLI@2
            displayName: 'Get AKS Name'
            inputs:
              azureSubscription: $(ServiceConnectionName)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                AKS=$(az aks list -g $(AKSResourceGroupName) --query [0].name -o tsv)
                echo "AKS is $AKS"
                echo '##vso[task.setvariable variable=AKSClusterName]'$AKS

          - task: HelmDeploy@1
            displayName: 'Add Istio Repo'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(ServiceConnectionName)
              azureResourceGroup: $(AKSResourceGroupName)
              kubernetesCluster: $(AKSClusterName)
              command: 'repo'
              arguments: 'add istio https://istio-release.storage.googleapis.com/charts'

          - task: HelmDeploy@1
            displayName: 'Update Helm Repos'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(ServiceConnectionName)
              azureResourceGroup: $(AKSResourceGroupName)
              kubernetesCluster: $(AKSClusterName)
              command: 'repo'
              arguments: 'update'

          - task: HelmDeploy@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: '$(ServiceConnectionName)'
              azureResourceGroup: '$(AKSResourceGroupName)'
              kubernetesCluster: '$(AKSClusterName)'
              namespace: 'istio-system'
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'istio/base'
              chartVersion: '1.25.1'
              releaseName: 'istio-base'
              valueFile: '$(System.DefaultWorkingDirectory)/setup/values/istiobase.yaml'
              
```
