### ISSUE TITLE
[BUG]: Azure devops pipeline does not pass variables to stages

### ISSUE THREAD

**Issue by scholtz** [microsoft/azure-pipelines-tasks#20689]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Issue Description

We want to create variable in the build stage and use the variable in all deployment stages.

We are able to create variable in the first stage, and pass it to the dev environment. But we are not able to pass the variable from either build stage to the 3rd stage (test) nor from the deployment to dev stage to deployment to test stage.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu

### Relevant log output

```shell
2024-11-25T17:19:36.8830621Z echo "Received variable from Dev: "
```

### Full task logs with system.debug enabled

<details>
  <pre>
[build-variable.txt](https://github.com/user-attachments/files/17906739/build-variable.txt)
[deploy-to-dev.txt](https://github.com/user-attachments/files/17906740/deploy-to-dev.txt)
[deploy-to-test.txt](https://github.com/user-attachments/files/17906741/deploy-to-test.txt)
  </pre>
</details>

### Repro steps

```yml
trigger:
- none

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar;isOutput=true]Hello from Build"
      name: OutputStep

- stage: DeployDev
  displayName: Deploy Dev Stage
  dependsOn: Build
  variables:
    myVarFromBuild: $[ stageDependencies.Build.BuildJob.outputs['OutputStep.myVar'] ]
  jobs:
  - deployment: DeployJob
    displayName: Deploy to Dev
    environment: "Dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Received variable from Build: $(myVarFromBuild)"
              echo "##vso[task.setvariable variable=myVarDev;isOutput=true]$(myVarFromBuild)"
            name: SetOutputForDev

- stage: DeployTest
  displayName: Deploy Test Stage
  dependsOn: DeployDev
  variables:
    myVarFromDev: $[ stageDependencies.DeployDev.DeployJob.outputs['SetOutputForDev.myVarDev'] ]
  jobs:
  - deployment: DeployJob
    displayName: Deploy to Test
    environment: "Test"
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Received variable from Dev: $(myVarFromDev)"
```
