### ISSUE TITLE
[BUG]: DotNetCoreCLI@ Test with parameter publishTestResults=true appends additional --results-directory regardless

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#20731]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DotNetCoreCLI

### Task version

2.247.3

### Issue Description

The following YAML task:

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(RepoRoot)\src\**\*.Tests.*.csproj'
    arguments: '--no-restore --no-build --configuration ${{ parameters.configuration }} --settings "$(RepoRoot)\.runsettings" --filter TestCategory!=Integration --blame --collect:"XPlat Code Coverage" --logger trx --results-directory "$(Agent.TempDirectory)\TestResults\"'
    publishTestResults: true // <-- !
```

Fails with the following error:

```
##[error]Error: The process 'C:\__t\dotnet\dotnet.exe' failed with exit code 1
C:\__t\dotnet\dotnet.exe test C:\__w\1\s\src\MyProject.Tests.Unit.csproj --logger trx --results-directory C:\__w\_temp --no-restore --no-build --configuration Release --settings C:\__w\1\s\.runsettings --filter TestCategory!=Integration --blame "--collect:XPlat Code Coverage" --logger trx --results-directory "C:\__w\_temp\TestResults\""
Option '--results-directory' expects a single argument but 2 were provided.
```

Because the parameter `--results-directory` was passed twice:

1. Explicitly by the user: `--results-directory "C:\__w\_temp\TestResults\`
2. Implicitly by the task: `--results-directory C:\__w\_temp`

Can it be smarter and not do it if it was already passed?

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

N/A

### Operation system

Windows

### Full task logs with system.debug enabled

[Full debug logs.txt.zip](https://github.com/user-attachments/files/18141330/Full.debug.logs.txt.zip)
