### ISSUE TITLE
[BUG]: AzureRmWebAppDeployment@4: Comma in setParam argument causes incorrect encoding

### ISSUE THREAD

**Issue by dw-alexangas** [microsoft/azure-pipelines-tasks#20743]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureRmWebAppDeployment

### Task version

4.247.1

### Issue Description

After experiencing the `AzureRmWebAppDeployment@4` task being broken at least twice, we decided to lock it in our YAML pipelines to version 4.225.1. Due to the Node 10 deprecation warning, we are now attempting to update to the latest version.

We have found that when using the `AdditionalArguments` parameter and supplying MSDeploy arguments of form `-setParam:name='X',value='Y'` we are experiencing a bug. This appears to be logic that was introduced in https://github.com/microsoft/azure-pipelines-tasks/commit/88ec5139c28625ea228d3a40f662454cd2f5dd44 related to encoding.

The change in behaviour has connection strings that were previously _correctly_ encoded as:

```
Encrypt=True;TrustServerCertificate=False;Data Source=some-sql-server.database.windows.net,1433;Initial Catalog=some-database;User Id=someuser;Password=somepassword;
```

To now be _incorrectly_ encoded as:

```
'Encrypt=True;TrustServerCertificate=False;Data Source=some-sql-server.database.windows.net&quot;,1433;Initial Catalog=&quot;some-database;User Id=someuser;Password=somepassword;'
```

Please note the following breaking changes:

1. Invalid insertions of `&quot;`
2. Invalid prefix and suffix of single quote marks

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Relevant log output

```shell
There is no error, the behaviour is incorrect.
```

### Full task logs with system.debug enabled

N/A

### Repro steps

```yml
- task: AzureRmWebAppDeployment@4.225.1	# TO REPRO: Remove specific minor/patch version
    inputs:
      azureSubscription: $(AzureSubscription)
      WebAppName: '$(WebAppName)'
      ResourceGroupName: '$(ResourceGroupName)'
      packageForLinux: '$(SourcePath)/$(PackageFilename)'
      enableCustomDeployment: true
      TakeAppOfflineFlag: false
      ExcludeFilesFromAppDataFlag: false
      RenameFilesFlag: false
      AdditionalArguments: "-retryAttempts:6 -retryInterval:10000 -setParam:name='ConnectionString',value='Encrypt=True;TrustServerCertificate=False;Data Source=some-sql-server.database.windows.net,1433;Initial Catalog=some-database;User Id=someuser;Password=somepassword;'"
```
