### ISSUE TITLE
[REGRESSION]: HelmDeploy@1 and HelmDeploy@0 stopped working with environment

### ISSUE THREAD

**Issue by PAKalucki** [microsoft/azure-pipelines-tasks#20791]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy

### Breaking task version

1.250.1
0.250.1

### Last working task version

0.247.3

### Regression Description

Both HelmDeploy@1 and HelmDeploy@0 started to ignore environment https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#target-a-specific-environment-resource-from-a-deployment-job

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
Starting: Helm upgrade
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 1.250.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Input required: kubernetesCluster
Finishing: Helm upgrade
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> Starting: Helm upgrade
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.247.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
/usr/local/bin/helm upgrade --namespace test --install --wait test /home/vsts/work/1/s/test
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Mon Jan 20 11:07:46 2025
NAMESPACE: test
STATUS: deployed
REVISION: 6
TEST SUITE: None </pre>
</details>

### Repro steps

```yml
jobs:
  - deployment: Deploy
    displayName: Deploy to Kubernetes
    pool:
      vmImage: ubuntu-latest
    environment: 
      name: test
      resourceType: Kubernetes
      resourceName: test
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmDeploy@1
            displayName: Helm upgrade
            inputs:
              namespace: default
              command: upgrade
              chartType: filepath
              chartPath: test
              releaseName: test
              install: true
              waitForExecution: true
```

**Comment by Deekshitha981** [comment]
Hi @PAKalucki could you please share the successful and unsuccessful logs with debug set to true

**Comment by murphy85** [comment]
We faced the same issue with explicit connection configuration instead of environment configuration. Before we could just set the kubernetesServiceConnection attribute and it worked. Now the task asks for kubernetesCluster. Now it works like it is documented:

[HelmDeploy@0 - Package and deploy Helm charts v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines)

    #connectionType: 'Azure Resource Manager' # 'Azure Resource Manager' | 'Kubernetes Service Connection' | 'None'. Required when command != logout && command != package && command != save. Connection Type. Default: Azure Resource Manager.
    #kubernetesCluster: # string. Required when connectionType = Azure Resource Manager && command != logout && command != package && command != save. Kubernetes cluster. 

If connectionType is not specified, 'Azure Resource Manager' is default. If 'Azure Resource Manager' is set, the attribute kubernetesCluster is required.

We just added connectionType:  'Kubernetes Service Connection' to our tasks.

**Comment by DRoppelt** [comment]
same here, using HelmDeploy@0

when it worked, the underlying version was `0.247.3`, now with `0.250.1` it complains with `[error]Error: Input required: kubernetesCluster`

```
Starting: Helm dependency update
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.250.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Input required: kubernetesCluster
Finishing: Helm dependency update
```


The usage in our case. `connectionType: 'Kubernetes Service Connection'` was added to fix it.

```
- task: HelmDeploy@0
  displayName: Helm dependency update
  name: helm_dependency_update
  inputs:
    command: dependency
    #connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
    arguments: 'update $(Build.SourcesDirectory)/${{ parameters.helmChartPath }}'
```
