### ISSUE TITLE
[REGRESSION]: HelmDeploy@1 (v1.250.1) no longer works as documented with Azure DevOps environments

### ISSUE THREAD

**Issue by amithkk** [microsoft/azure-pipelines-tasks#20794]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy@1

### Breaking task version

1.250.1

### Last working task version

1.248.1

### Regression Description

In `1.248.1`, if an Azure DevOps Environment of type `kubernetes` was provided, HelmDeploy@1 would automatically pick up kubernetes cluster details. An example stage is shown below.

```yaml
- stage: DeploymentStage
  displayName: 'Deploy to Target Environment'
  dependsOn: PreviousStage
  condition: and(succeeded(), ${{ in(parameters.targetEnvironment, 'some', 'environment', 'names') }})
  jobs:
  - deployment: "TargetDeployment"
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: $(targetEnvironmentName)
      resourceType: Kubernetes
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
            displayName: 'Install Helm'
          - script: "ls -la"
          - task: HelmDeploy@1
            inputs:
              namespace: $(targetNamespace)
              command: 'upgrade'
              releaseName: $(helmReleaseName)
              chartPath: '$(chartPath)/$(chartName)'
              chartType: FilePath
              valueFile: '$(chartPath)/$(chartName)/values.target.yaml'
              overrideValues: |
                service.image.repository=$(registryUrl)/$(imageRepository)
                service.image.tag=${{ parameters.deployTag }}
              install: true
              waitForExecution: true
            displayName: 'Deploy to Target Environment'
``` 

After upgrading to `1.250.1`, the HelmDeploy task fails with the following log message:

```
##[error]Error: Input required: kubernetesCluster
```

This change in parameter requirements does not seem to be spelt out in the [release notes](https://github.com/microsoft/azure-pipelines-tasks/releases/tag/v250) or in the [Azure DevOps Documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops) for environments.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

n/a

### Relevant log output

```shell
##[error]Error: Input required: kubernetesCluster
```

### Repro steps

```yml

```
