### ISSUE TITLE
[BUG]: Powershell@2 Impossible to ignore specific warning output

### ISSUE THREAD

**Issue by arc-hbas** [microsoft/azure-pipelines-tasks#20851]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Powershell

### Task version

2

### Issue Description

When using the `PowerShell@2` task and enabling `showWarnings`, it becomes impossible to specifically ignore a single warning, even if `WarningAction` is set to `Ignore` or `SilentlyContinue`. Other "hacks", such as using redirect operator `3>`  to redirect warning output stream to file or `$null`, have not been successful to workaround this issue. This potentially causes massive log clutter when you still want to surface warning output to the pipeline summary view, but would like to disregard some of the non-important ones.

Running below example YAML pipeline, all of the warnings are still surfaced:

![Image](https://github.com/user-attachments/assets/c4ad9f2e-8cb9-4602-b9a8-0cd022008e20)

![Image](https://github.com/user-attachments/assets/ed2ba65a-6e01-4bbc-a557-c983584d1f02)

I thought surely the `3>` redirect would work, but alas it doesn't. Thus far I have been unable to find any sort of workaround. Warnings are helpful, but only when they're relevant. Sometimes we call system level or pre-built cmdlets and cannot expect them to only print out relevant warnings (from our perspective at least).

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Relevant log output

```shell
...
WARNING: a) Default: Shows = true & Expected = true
##[warning]a) Default: Shows = true & Expected = true
##[warning]b) SilentlyContinue: Shows = true & Expected = false
##[warning]c) Ignore: Shows = true & Expected = false
##[warning]d) 3> redirect $null: Shows = true & Expected = false
##[warning]e) 3> redirect file: Shows = true & Expected = false


Finishing: Test PS
```

### Repro steps

```yml
trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: PowerShell@2
  displayName: Test PS
  inputs:
    targetType: 'inline'
    showWarnings: true
    script: |      
      # Should print and does
      Write-Warning "a) Default: Shows = true & Expected = true" 

      # Should NOT print but does
      Write-Warning "b) SilentlyContinue: Shows = true & Expected = false" -WarningAction SilentlyContinue

      # Should NOT print but does
      Write-Warning "c) Ignore: Shows = true & Expected = false" -WarningAction Ignore

      # Should NOT print but does
      Write-Warning "d) 3> redirect `$null: Shows = true & Expected = false" 3> $null

      # Should NOT print but does
      Write-Warning "e) 3> redirect file: Shows = true & Expected = false" 3> out.txt
```
