### ISSUE TITLE
[BUG]: AzureWebApp@1 missing Node 22-LTS option

### ISSUE THREAD

**Issue by blendsdk** [microsoft/azure-pipelines-tasks#20864]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureWebApp@1

### Task version

1

### Issue Description

Hi,

I have been trying to deploy a very simple "Hello World" app in Azure using AzureWebApp@1.
When I deploy by app using `appType = webAppLinux` and `runtimeStack = NODE|20-lts` everything goes okay.
But `runtimeStack = NODE|22-lts` The deployment reverts back to node v16!!

Azure supports Node 22 at this moment. I might be wrong but it looks like `AzureWebApp@1` is missing Node 22 option. Please see:
https://github.com/microsoft/azure-pipelines-tasks/blob/1d12444f679e8529337c85d18b5647b868350333/Tasks/AzureWebAppV1/task.json#L131

My config:
```
- task: AzureWebApp@1
  displayName: 'Deploy $(APP_NAME) via ${{ parameters.subscription }}'
  inputs:
    azureSubscription: ${{ parameters.subscription }}
    appType: 'webAppLinux'
    appName: $(APP_NAME)
    package: $(Pipeline.Workspace)/archives/${{ parameters.component }}_$(Build.BuildNumber).zip
    deploymentMethod: zipDeploy
    # RuntimeStack: 'NODE|20-lts' # This works
    RuntimeStack: 'NODE|22-lts' # THIS DOES NOT WORK!!

```

Any thoughts?

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
No error logs!!
```

### Repro steps

```yml

```
