### ISSUE TITLE
[BUG]: AzureFunctionApp@2 deployment type option error when deployment type not included

### ISSUE THREAD

**Issue by jamie-oconnell** [microsoft/azure-pipelines-tasks#20866]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp@2

### Issue Description

With no deployment type defined in AzureFunctionApp@2 inputs the task throws an error.

```yaml
  - task: AzureFunctionApp@2
    inputs:
      azureSubscription: prod
      runtimeStack: "NODE|20"
      appType: functionAppLinux
      appName: "app1"
      package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
```

Results in `The Deployment Type option does not apply for Linux Consumption.`

Reverting to the same configuration on v1 works fine.

```yaml
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: prod
      runtimeStack: "NODE|20"
      appType: functionAppLinux
      appName: "app1"
      package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
The Deployment Type option does not apply for Linux Consumption.
```

### Repro steps

```yml

```
