### ISSUE TITLE
[BUG]: Kubernetes@1 throws 404 when downloading kubectl

### ISSUE THREAD

**Issue by devedse** [microsoft/azure-pipelines-tasks#20888]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Kubernetes@1

### Task version

1.250.1

### Issue Description

The Kubernetes@1 task throws a 404 error when downloading Kubectl.

I checked the previous runs for this morning and there it tried to download version 1.29.5 which did exist. It seems the last version (as per the link) doesn't exist on the url provided.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Azure Pipeline Linux

### Relevant log output

```shell
Starting: kubectl apply
==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.250.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-kubectl-tsg
==============================================================================
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.30.9/bin/linux/amd64/kubectl
##[error]Failed to download kubectl from location https://storage.googleapis.com/kubernetes-release/release/v1.30.9/bin/linux/amd64/kubectl. Error Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/home/vsts/work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.250.1/node_modules/azure-pipelines-tool-lib/tool.js:216:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.250.1/node_modules/azure-pipelines-tool-lib/tool.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatusCode: 404
}
Finishing: kubectl apply
```

### Repro steps

```yml
- task: Kubernetes@1
    displayName: 'kubectl apply'
    inputs:
      connectionType: 'None'
      azureSubscriptionEndpoint: '${{ parameters.azureSubscription }}'
      azureResourceGroup: '${{ parameters.azureResourceGroup }}'
      kubernetesCluster: '${{ parameters.kubernetesCluster }}'
      namespace: '${{ parameters.namespace }}'
      command: apply
      useConfigurationFile: true
      configuration: '$(Pipeline.Workspace)/${{ parameters.service }}-artifacts/deploy-${{ parameters.service }}-webapi.k8s.yml'
      versionSpec: ${{ parameters.aksVersion }}
```
