### ISSUE TITLE
[Question]: ExtractFiles@1 How to skip the ask when overwriteExistingFiles is false and have any exist file

### ISSUE THREAD

**Issue by AccMJZ** [microsoft/azure-pipelines-tasks#20902]
### Task name

ExtractFiles@1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Question

```shell
ExtractFiles@1
How to skip the ask when overwriteExistingFiles is false and have any exist file ?
```

**Comment by AccMJZ** [comment]
_Would you like to replace the existing file:
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit?_ 
I want skip all exist file
I have some production environment config, I don't want replace them

**Comment by AccMJZ** [comment]
passing the - aos parameter when overwriteExistingFiles is false may be more appropriate

**Comment by jopabe** [comment]
I second the author's suggestion. The `ExtractFiles@1` task should pass the `-aos` parameter to 7zip when `overwriteExistingFiles` is false. The current implementation causes 7zip to expect an interactive response, which makes no sense in a pipeline context.

**Comment by jopabe** [comment]
Here's our current workaround for this issue. It does require using `ExtractFiles@1` somewhere else in the same job, to ensure the task is downloaded (it can be a dummy task with a `condition` that always resolves to `false`)

```YAML
      - powershell: |
          $sevenzip = '7z.exe'
          # prefer 7z.exe in the PATH
          if (-not (Get-Command -ErrorAction Ignore $sevenzip)) {
            # fall back to the utility shipped with ExtractFiles
            $sevenzip = ls "$env:TasksDirectoryPath\ExtractFiles_*" -Recurse -Depth 2 -Include $sevenzip | select -Last 1
          }
          & $sevenzip x -aos [...]
        env:
          TasksDirectoryPath: '$(Agent.WorkFolder)\_tasks'
```

It would be preferable to be able to use the `ExtractFiles@1` task though, so fixing the `overwriteExistingFiles: false` scenario where a destination file already exists would be much appreciated.
