### ISSUE TITLE
[BUG]: dotnet restore with source mapping and private feed does not work

### ISSUE THREAD

**Issue by mortenn** [microsoft/azure-pipelines-tasks#20910]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DotNetCoreCLI

### Task version

2

### Issue Description

I am building a solution in a pipeline which uses dotnet restore to restore nugets.

After adding a private Azure DevOps feed to nuget.config, it did not work, because the task used a "temporary" nuget.config file.

Adding a vstsFeed to the task did not work, because Centralized Package Management requires source mapping.

Changing the task to use config rather than select does not work because it adds a "feed-" prefix to the feed key, which I cannot do in the source mapping or it will break for developers.

As a workaround, I added an extra DevOps-Nuget.Config where the key just "private" in the source list, but "feed-private" in the source mapping section.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

N/A

### Relevant log output

```shell
error NU1101: Unable to find package FooSys.Events. No packages exist with this id in source(s): NuGetOrg [/home/vsts/work/1/s/FooSys.sln]

error NU1507: Warning As Error: There are 2 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping

error NU1100: Unable to resolve 'FooSys.Events (>= 1.2.77-beta-gea926e2040)' for 'net9.0'. PackageSourceMapping is enabled, the following source(s) were not considered: feed-private, nuget.org. [/home/vsts/work/1/s/FooSys.sln]

error NU1100: Unable to resolve 'FooSys.Events (>= 1.2.77-beta-gea926e2040)' for 'net9.0'. PackageSourceMapping is enabled, the following source(s) were not considered: feed-feed-FooSys, nuget.org. [/home/vsts/work/1/s/FooSys.sln]
```

### Repro steps

```yml
- task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
```

**Comment by mortenn** [comment]
sample DevOps-Nuget.Config 

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="FooSysNuget" value="https://pkgs.dev.azure.com/ExampleOrg/FooSys/_packaging/FooSysNuget/nuget/v3/index.json" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="feed-FooSys">
      <package pattern="FooSys.*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

**Comment by gorkarivero28** [comment]
Hi,

I got the same error:

PackageSourceMapping is enabled, the following source(s) were not considered: NugetFoundation, DevExpress.

In my case NugetFoundation is my private nuget repository.

Is there any workarond?

**Comment by mortenn** [comment]
Yes, the workaround is detailed above;
> As a workaround, I added an extra DevOps-Nuget.Config where the key just "private" in the source list, but "feed-private" in the source mapping section.

I did not include the pipeline change to do this, though, so here you go:
```yaml
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: 'DevOps-Nuget.Config'
```

**Comment by ghost** [comment]
Also happens on self-hosted agent (Windows Server 2025, new added build agent) with this example pipeline config:

```yaml
steps:

- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@1

- task: DotNetCoreCli@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'src/devops-nuget.config'
    externalFeedCredentials: 'DevExpress Feed'
    projects: '**/Mention.Web.sln'

...
```

adding a special nuget.config just for azure pipeline agents with the `feed-` prefix for the private packagesource is a valid workaround that works

```xml
<packageSource key="feed-MentionPackages">
	<package pattern="Mention.*" />
</packageSource>
```
