### ISSUE TITLE
[enhancement]: [DotNetCoreCLIv2] dotnet nuget push "SkipDuplicate" or "arguments" options

### ISSUE THREAD

**Issue by mrlioncub** [microsoft/azure-pipelines-tasks#20981]
### Task name

[DotNetCoreCLIv2]

### Describe your feature request here

When using the DotNetCoreCLI task, command "nuget push", it is not possible to specify "SkipDuplicates" or other arguments. Nugget task is no longer supported on ubuntu 24.04.
 
Cli variant (from https://github.com/microsoft/azure-pipelines-tasks/issues/12562) dosen't support nuGetFeedType: 'external' and publishFeedCredentials from Service Connection.

**Comment by CSharpFiasco** [comment]
I also ran into this issue for the same reason: Nuget task will no longer be supported in Ubuntu 24.04

https://aka.ms/azdo-ubuntu-24.04

**Comment by Joren-Thijs-KasparSolutions** [comment]
We are also running into this issue. There is a `--skip-duplicate` argument in the dotnet core cli you could pass.
But the [DotNetCoreCli@2 task documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines) states the the `arguments` input is not used when command type is push. Causing us to setup a complete custom task. Which is rediculous.

Please fix the dotnet task and add a skip duplicates option or allow us to pass arguments when command type is push.

**Comment by ReinhardvdBerg** [comment]
We are also running into this issue now after upgrading agents to ubuntu-24.04 using Azure Artifacts.
Please add native support.

**Comment by ryan-seifi** [comment]
I've got the same issue as well. Currently using the old nuget CLI on the old ubuntu

**Comment by kumaakh** [comment]
I have the same issue. I tried alot to use "custom" option to somehow insert --skip-duplicates but to no avail. 
this option was there in the old nuget tasks but not in this new dotnet tasks.  Pls fix

**Comment by aong3-wx** [comment]
The workaround I used (from stack overflow) worked quite well:

```yml
- task: NuGetAuthenticate@1
# dotnet push does not support --skip-duplicate, so we need a custom command
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: >
      push "$(Build.ArtifactStagingDirectory)/*.nupkg"
      --source "https://pkgs.dev.azure.com/{orgName}/_packaging/{fill_this_in}/nuget/v3/index.json"
      --api-key az
      --skip-duplicate
```
