### ISSUE TITLE
[REGRESSION]: ERROR: Usage error: --container-name is required when adding or updating a container

### ISSUE THREAD

**Issue by MMouad-FM** [microsoft/azure-pipelines-tasks#20991]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureContainerApps

### Breaking task version

1.255.0

### Last working task version

1.247.1

### Regression Description

The task id no longer fomatting the AZ command correctly,

We get the error below (while using the same task params):

/usr/bin/az containerapp update -n ca-mgt-lz-t-weur-001 -g rg-mgt-lzautomation-t-weur -i cravrlzdweur001.azurecr.io/ado-task/container-app:13557.20250417.1
ERROR: Usage error: --container-name is required when adding or updating a container
##[error]Error Code: [1]
##[error]Error: Unable to update Azure Container App via 'az containerapp update' command.

Thanks.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 24.04.2 LTS (ubuntu-latest)

### Relevant log output

```shell
/usr/bin/az containerapp update -n ca-mgt-lz-t-weur-001 -g rg-mgt-lzautomation-t-weur -i cravrlzdweur001.azurecr.io/ado-task/container-app:13557.20250417.1
ERROR: Usage error: --container-name is required when adding or updating a container
##[error]Error Code: [1]
##[error]Error: Unable to update Azure Container App via 'az containerapp update' command.
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureContainerApps@1
  inputs:
    appSourcePath: '$(Build.SourcesDirectory)'
    azureSubscription: '{armServiceConnection}'
    acrName: '{acrName}'
    acrUsername: '{acrUserName}'
    acrPassword: '{acrPwd}'
    containerAppName: '{containerApp}'
    resourceGroup: '{rgName}'
    containerAppEnvironment: '{containerAppEnvName}'
    location: 'West Europe'
```
