### ISSUE TITLE
[BUG]: No way to install helm chart from azure ACR repo

### ISSUE THREAD

**Issue by johnwc** [microsoft/azure-pipelines-tasks#21019]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy@1

### Task version

1.255.0

### Issue Description

Using the following task sequence, the HelmDeploy task fails with `##[error]Error: repo darepo01 not found
`. Running the helm login command does not add the repo to the helm repo list.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
##[error]Error: repo darepo01 not found
```

### Full task logs with system.debug enabled

<details>
<pre>2025-05-11T07:57:57.0976265Z ##[section]Starting: helm upgrade
2025-05-11T07:57:57.0987608Z ==============================================================================
2025-05-11T07:57:57.0987816Z Task         : Package and deploy Helm charts
2025-05-11T07:57:57.0988107Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2025-05-11T07:57:57.0988343Z Version      : 1.255.0
2025-05-11T07:57:57.0988460Z Author       : Microsoft Corporation
2025-05-11T07:57:57.0988712Z Help         : https://aka.ms/azpipes-helm-tsg
2025-05-11T07:57:57.0988860Z ==============================================================================
2025-05-11T07:57:57.5876611Z [command]/opt/hostedtoolcache/helm/3.16.2/x64/linux-amd64/helm upgrade --namespace my-r --wait --reuse-values site darepo01/my-r-services --version 5.1.0-beta.45.g4e3afbea
2025-05-11T07:57:57.6133396Z Error: repo darepo01 not found
2025-05-11T07:57:57.6178652Z ##[error]Error: repo darepo01 not found

2025-05-11T07:57:57.6331551Z ##[section]Finishing: helm upgrade</pre>
</details>

### Repro steps

```yml
- task: KubectlInstaller@0
    displayName: 'Install Kubectl latest'

  - task: HelmInstaller@1
    displayName: 'Install Helm 3.16.2'
    inputs:
      helmVersionToInstall: 3.16.2

  - task: HelmDeploy@1
    displayName: 'helm login'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'Dev02 Cluster'
      namespace: 'my-r'
      azureSubscriptionForACR: 'Company24'
      azureResourceGroupForACR: 'USSCPMgmt'
      azureContainerRegistry: 'darepo01.azurecr.io'
      command: 'login'

  - task: HelmDeploy@1
    displayName: 'helm ls (Diagnose)'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'Dev02 Cluster'
      namespace: 'my-r'
      command: 'ls'

  - bash: |
      echo "Version: $(chartVersion)"
      helm repo list
      helm repo update
    displayName: 'helm repo update (Diagnose)'

  - task: HelmDeploy@1
    displayName: 'helm upgrade'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'Dev02 Cluster'
      namespace: 'my-r'
      command: 'upgrade'
      chartType: 'Name'
      chartName: 'darepo01/my-r-service'
      chartVersion: '$(chartVersion)'
      releaseName: 'site'
      install: false
      arguments: '--reuse-values'
```
