### ISSUE TITLE
[enhancement]: Cache@2 should support ignoring error when retrieving/storing cache

### ISSUE THREAD

**Issue by carstenhag** [microsoft/azure-pipelines-tasks#21015]
### Task name

Cache@2

### Describe your feature request here

Due to some kind of (unrelated, will report later) issue, our DevOps pipeline is always failing at the "Post-job" Cache@2 task.

We always want to run Cache@2 and the main part of the task does support conditions; also the post-job conforms to it since https://github.com/microsoft/azure-pipelines-tasks/issues/10907.  
But it is not possible to ignore an error in the main task/job or at the post-job phase. Effectively the caching step now breaks our build.

**Comment by CorneAussems** [comment]
This does not seem to work for me? 

I have a Cache like:
```
    - task: Cache@2
      displayName: Cache Dependency Check NVD Data
      inputs:
        key: '"NVD" | "$(Agent.OS)"'
        restoreKeys: |
          "NVD" | "$(Agent.OS)"
          "NVD"
        path: ${{ parameters.nvdCacheDirectory }} 
      continueOnError: true
```

```
    - task: dependency-check.dependencycheck.dependency-check-build-task.dependency-check-build-task@6
      inputs:
        projectName: ${{ parameters.projectName }}
        scanPath: ${{ parameters.scanPath }}
        format: ${{ join(',', parameters.formats) }}
        additionalArguments: > 
          --data ${{ parameters.nvdCacheDirectory }}
          ${{ parameters.additionalArguments }}
        suppressionPath: ${{ parameters.workingDirectory }}/${{ parameters.baseSuppressionFile }}
        reportsDirectory: ${{ parameters.workingDirectory }}/${{ parameters.outputDirectory }}
        enableExperimental: ${{ parameters.enableExperimental }}
        failOnCVSS: ${{ parameters.failOnCVSS }}
      displayName: OWASP Dependency Check
      continueOnError: ${{ parameters.continueOnError }}
```


This throws an genuine error:
`        failOnCVSS: ${{ parameters.failOnCVSS }}`

```
Dependency Check failed with message "CVSS threshold violation."
##[error]CVSS threshold violation.
```

We continueOnError .... 
But there is no upload on this cache (nor any of the other caches) in the post-job:

```
2025-07-22T20:09:12.6692770Z ##[section]Starting: Cache Dependency Check NVD Data
2025-07-22T20:09:12.6697481Z ==============================================================================
2025-07-22T20:09:12.6697643Z Task         : Cache
2025-07-22T20:09:12.6697744Z Description  : Cache files between runs
2025-07-22T20:09:12.6697848Z Version      : 2.198.0
2025-07-22T20:09:12.6697932Z Author       : Microsoft Corporation
2025-07-22T20:09:12.6698047Z Help         : https://aka.ms/pipeline-caching-docs
2025-07-22T20:09:12.6698160Z ==============================================================================
2025-07-22T20:09:13.0192111Z ##[section]Finishing: Cache Dependency Check NVD Data
```

I now put the cache in a separate job that only downloads the NVD Data 
and reuse that, but it sure looks like continueOnError is not working if you generate an error.

As described here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops&tabs=bundler#cache-task-how-it-works
`Once all steps in the job have run successfully, a special "Post-job: Cache" step is automatically added and triggered for each "restore cache" step that wasn't skipped. This step is responsible for saving the cache.
`

I wish it would be able to save even after an error.
