### ISSUE TITLE
[BUG]: Typo in FileTransform@2 error message: FileTranformationNotEnabled

### ISSUE THREAD

**Issue by grahamfurner** [microsoft/azure-pipelines-tasks#21020]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

FileTransform@2

### Task version

2.254.0

### Issue Description

Repro script:

    - task: FileTransform@2
      displayName: 'X'
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/SiteName/**/*.zip'
        enableXmlTransform: true
        xmlTransformationRules: '-transform **/web.Release.config -xml **/web.config'

Notice the error message:
"File Tranformation (sic) is not enabled. Please provide one of the following : XML Tranformation rules or JSON/XML target files for variable substitution."
Notice also that the JSON tag in task.json also has the same typo: Tran**s**formation 

Acceptance Criteria:
The spelling of the message and tag should be "Transformation"

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-24.04

### Relevant log output

```shell
Repro script in Description is sufficient
```

### Full task logs with system.debug enabled

Repro script in Description is sufficient

### Repro steps

```yml
- task: FileTransform@2
      displayName: 'X'
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/SiteName/**/*.zip'
        enableXmlTransform: true
        xmlTransformationRules: '-transform **/web.Release.config -xml **/web.config'
```
