### ISSUE TITLE
[BUG]: AzureFunctionApp@2 fails when deploying a flex app

### ISSUE THREAD

**Issue by ikkentim** [microsoft/azure-pipelines-tasks#21032]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Task version

2

### Issue Description

When deploying a flex app, this error is provided and the deployment fails:
```
The following list of 4 site configuration properties (Site.SiteConfig.FtpsState,Site.SiteConfig.Use32BitWorkerProcess, Site.SiteConfig.NetFrameworkVersion, Site.SiteConfig.FunctionsRuntimeScaleMonitoringEnabled) for Flex Consumption sites is invalid
```

See also comment by Michele Ariis in https://learn.microsoft.com/en-us/answers/questions/2275500/flex-consumption-plan-code-package-deployment-conf

> Hi, it's an Azure bug in West Europe Flex Consumption clusters: the patch rejects those four fields (even if null) that the AzureFunctionApp@2 extension sends. North Europe doesn't have the new validation yet, so it works there.
> 
> Workaround: use WEBSITE_RUN_FROM_PACKAGE / az CLI or publish from Core Tools, or move the app to another region until Microsoft fixes. It's not your Bicep's fault.
>
> (...)
> Until Microsoft fixes the AzureFunctionApp@2 task, leave it out of your pipeline because it still sends invalid fields and makes the deployment fail.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Relevant log output

```shell
The following list of 4 site configuration properties (Site.SiteConfig.FtpsState,Site.SiteConfig.Use32BitWorkerProcess, Site.SiteConfig.NetFrameworkVersion, Site.SiteConfig.FunctionsRuntimeScaleMonitoringEnabled) for Flex Consumption sites is invalid
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: AzureFunctionApp@2
  displayName: "Deploy Function App"
  inputs:
    connectedServiceNameARM: "mySubscription"
    appType: "functionAppLinux"
    isFlexConsumption: true
    appName: "myAppName"
    package: "$(Pipeline.Workspace)/drop/publish/*.zip"
```
