### ISSUE TITLE
[BUG]: HelmDeploy@1 throwing error log even after successful completion of Task

### ISSUE THREAD

**Issue by anumalasri** [microsoft/azure-pipelines-tasks#21046]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy@1

### Task version

1.256.0

### Issue Description

We are getting error log on every helm deploy task.  

No further logs available in Debug runs 

Expection is that:  No error logs on successful deployment of Helm Chart.   Or provide more details on what's failing from deployment perspective.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

4.255.0

### Operation system

Linux

### Relevant log output

```shell
Using HelmDeploy task to deploy helm chart onto Kubernetes cluster. 

Every run is giving the below error message 

##[error]Capturing deployment metadata failed with error: TypeError: Cannot read properties of null (reading 'kind')
```

### Full task logs with system.debug enabled

<details>
  <pre>==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 1.256.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
##[error]Capturing deployment metadata failed with error: TypeError: Cannot read properties of null (reading 'kind')
Finishing:</pre>
</details>

### Repro steps

```yml
- task: HelmDeploy@1
  displayName: "App Deployment"
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '${{ parameters.AZ_SERVICE_CONNECTION }}'
    azureResourceGroup: '$(AZ_RESOURCEGROUP)'
    kubernetesCluster: '$(AZ_CLUSTERNAME)'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: './$(HELM_CHARTNAME)'
    releaseName: '$(HELM_RELEASENAME)'
    valueFile: '$(HELM_CHARTNAME)/values.yaml'
    arguments: '-f $(HELM_CHARTNAME)/envs/$(ENV)/values.yaml --timeout $(HELM_TIMEOUT)'
    workingDirectory: '$(OPSFOLDER)'
```
