### ISSUE TITLE
[BUG]: ArchiveFiles@2.256.0 throws "TypeError: paths.flat is not a function"

### ISSUE THREAD

**Issue by mgefvert** [microsoft/azure-pipelines-tasks#21048]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

ArchiveFiles

### Task version

2.256.0

### Issue Description

Since yesterday (2025-05-21) all of our builds have been failing in the ArchiveFiles@2 stage with the mysterious error message:

##[error]TypeError: paths.flat is not a function
##[error]paths.flat is not a function

After testing a bit back and forth with various options - nothing yielding any good results - we finally investigated the task itself and pinned it to version 2.254.1, the previous version, and suddenly all of our builds are fine again.

In other words, changing the line

      - task: ArchiveFiles@2

to 

      - task: ArchiveFiles@2.254.1

made everything work. So, I'm thinking that probably an update was made to the task (seems like task-lib was updated to v5) that caused an error.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Linux (debian-bullseye)

### Relevant log output

```shell
2025-05-22T18:08:13.5165600Z ##[error]TypeError: paths.flat is not a function
```

### Full task logs with system.debug enabled

2025-05-22T18:08:13.2399277Z ##[debug]Evaluating condition for step: 'ArchiveFiles'
2025-05-22T18:08:13.2402315Z ##[debug]Evaluating: SucceededNode()
2025-05-22T18:08:13.2403176Z ##[debug]Evaluating SucceededNode:
2025-05-22T18:08:13.2404651Z ##[debug]=> True
2025-05-22T18:08:13.2405546Z ##[debug]Result: True
2025-05-22T18:08:13.2406577Z ##[section]Starting: ArchiveFiles
2025-05-22T18:08:13.2420062Z ==============================================================================
2025-05-22T18:08:13.2420586Z Task         : Archive files
2025-05-22T18:08:13.2421010Z Description  : Compress files into .7z, .tar.gz, or .zip
2025-05-22T18:08:13.2421452Z Version      : 2.256.0
2025-05-22T18:08:13.2507926Z Author       : Microsoft Corporation
2025-05-22T18:08:13.2508536Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/archive-files
2025-05-22T18:08:13.2509114Z ==============================================================================
2025-05-22T18:08:13.2764930Z ##[debug]Using node path: /azp/externals/node10/bin/node
2025-05-22T18:08:13.4402305Z ##[debug]system.debug=True
2025-05-22T18:08:13.4465120Z ##[debug]DistributedTask.Tasks.Node.SkipDebugLogsWhenDebugModeOff=True
2025-05-22T18:08:13.4778796Z ##[debug]agent.TempDirectory=/azp/_work/_temp
2025-05-22T18:08:13.4846810Z ##[debug]loading inputs and endpoints
2025-05-22T18:08:13.4954812Z ##[debug]loading INPUT_ROOTFOLDERORFILE
2025-05-22T18:08:13.4974130Z ##[debug]loading INPUT_INCLUDEROOTFOLDER
2025-05-22T18:08:13.4976259Z ##[debug]loading INPUT_ARCHIVETYPE
2025-05-22T18:08:13.4977967Z ##[debug]loading INPUT_SEVENZIPCOMPRESSION
2025-05-22T18:08:13.4979569Z ##[debug]loading INPUT_TARCOMPRESSION
2025-05-22T18:08:13.4981145Z ##[debug]loading INPUT_ARCHIVEFILE
2025-05-22T18:08:13.4983006Z ##[debug]loading INPUT_REPLACEEXISTINGARCHIVE
2025-05-22T18:08:13.4984717Z ##[debug]loading INPUT_VERBOSE
2025-05-22T18:08:13.4986186Z ##[debug]loading INPUT_QUIET
2025-05-22T18:08:13.4987752Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2025-05-22T18:08:13.4989335Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2025-05-22T18:08:13.4990925Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2025-05-22T18:08:13.4997563Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2025-05-22T18:08:13.4999343Z ##[debug]loaded 13
2025-05-22T18:08:13.5103269Z ##[debug]Agent.ProxyUrl=undefined
2025-05-22T18:08:13.5105547Z ##[debug]Agent.CAInfo=undefined
2025-05-22T18:08:13.5106915Z ##[debug]Agent.ClientCert=undefined
2025-05-22T18:08:13.5108183Z ##[debug]Agent.SkipCertValidation=undefined
2025-05-22T18:08:13.5109519Z ##[debug]System.DefaultWorkingDirectory=/azp/_work/13/ww
2025-05-22T18:08:13.5110869Z ##[debug]rootFolderOrFile=/azp/_work/13/a/Project1/publish
2025-05-22T18:08:13.5112217Z ##[debug]makeAbsolute:/azp/_work/13/a/Project1/publish
2025-05-22T18:08:13.5113533Z ##[debug]includeRootFolder=false
2025-05-22T18:08:13.5114725Z ##[debug]archiveType=zip
2025-05-22T18:08:13.5115995Z ##[debug]archiveFile=/azp/_work/13/a/Project1/publish.zip
2025-05-22T18:08:13.5117228Z ##[debug]replaceExistingArchive=true
2025-05-22T18:08:13.5118420Z ##[debug]verbose=false
2025-05-22T18:08:13.5119521Z ##[debug]quiet=false
2025-05-22T18:08:13.5120721Z ##[debug]repoRoot: /azp/_work/13/ww
2025-05-22T18:08:13.5121937Z ##[debug]win: null
2025-05-22T18:08:13.5124061Z ##[debug]check path : /azp/_work/_tasks/ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0/2.256.0/task.json
2025-05-22T18:08:13.5126051Z ##[debug]adding resource file: /azp/_work/_tasks/ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0/2.256.0/task.json
2025-05-22T18:08:13.5127763Z ##[debug]system.culture=en-US
2025-05-22T18:08:13.5129040Z ##[debug]paths.flat is not a function
2025-05-22T18:08:13.5165600Z ##[error]TypeError: paths.flat is not a function
2025-05-22T18:08:13.5177799Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]TypeError: paths.flat is not a function
2025-05-22T18:08:13.5224714Z ##[debug]task result: Failed
2025-05-22T18:08:13.5226069Z ##[error]paths.flat is not a function
2025-05-22T18:08:13.5227801Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]paths.flat is not a function
2025-05-22T18:08:13.5230364Z ##[debug]Processed: ##vso[task.complete result=Failed;]paths.flat is not a function
2025-05-22T18:08:13.5424933Z ##[section]Finishing: ArchiveFiles

### Repro steps

```yml
trigger:
  branches:
    include:
      - main
pool:
  name: $(pool)

jobs:
  - checkout: self
    clean: false
    fetchDepth: 1
    path: ww

  - job: BuildProject1
    displayName: Project1
    pool:
      name: $(pool)
    steps:
      - script: |
          cd cs/Project1
          dotnet publish -o $(Build.ArtifactStagingDirectory)/Project1/publish
        displayName: publish Project1
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Project1/publish'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/Project1/publish.zip'
          replaceExistingArchive: true
      - publish: $(Build.ArtifactStagingDirectory)/Project1/publish.zip
        displayName: 'Publish Artifact: Project1'
        artifact: Project1
```
