### ISSUE TITLE
[REGRESSION]: AndroidSigning@3 hangs when using .p12 keystore (works in @2)

### ISSUE THREAD

**Issue by maMoeve** [microsoft/azure-pipelines-tasks#21087]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AndroidSigning@3

### Breaking task version

AndroidSigning@3

### Last working task version

AndroidSigning@2

### Regression Description

The AndroidSigning@3 task does not support .p12 keystores correctly, even when setting jarsign: true and zipalign: false. My aim is to sign an .aab Android bundle, not an APK.
The task hangs at the signing step, prompting interactively for the keystore password (which is not possible in CI). The exact command being run appears to invoke apksigner, which doesn't support .p12 files.
This worked correctly in AndroidSigning@2.

**Repro Steps**
Use a .p12 keystore:
Add this YAML pipeline step:
```
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.aab'
    jarsign: true
    keystoreFile: 'keystore.p12'
    keystorePassword: '$(keyStorePass)'
    keystoreAlias: '$(keyStoreAlias)'
    keyPassword: '$(keyPass)'
    jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
    zipalign: false
```
Task hangs with this output:
```
Keystore password for signer #1:
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

vmImage: macOS-14

### Relevant log output

```shell
/Users/runner/Library/Android/sdk/build-tools/36.0.0/apksigner sign --ks /Users/runner/work/_temp/keystore.p12 --ks-key-alias *** --verbose /Users/runner/work/1/s/app/build/intermediates/intermediary_bundle/preproductionRelease/packagePreproductionReleaseBundle/intermediary-bundle.aab
Keystore password for signer #1:
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```
