### ISSUE TITLE
[BUG]: Federated access is not working (or not getting expected env variables)

### ISSUE THREAD

**Issue by oasaleh** [microsoft/azure-pipelines-tasks#21082]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzurePowerShell

### Task version

5

### Issue Description

I have two tenants: A and B. Pipeline is in tenant B, while my SQL Server is in tenant A. I have a service connection that's known to work with other resources (a Blob storage account in Tenant A that's being access by other pipelines in the same pool using the same image.)

![Image](https://github.com/user-attachments/assets/4915f779-9dd3-492b-8936-655b0d6ad592)

I am trying to run the following in my pipeline.

```yml
variables:
  labConn: "Server=tcp:my-sql-server.database.windows.net;Initial Catalog=my-db-dev;Authentication=Active Directory Default;Encrypt=True;"

steps:
  - task: AzurePowerShell@5
    displayName: "Run EF bundles - DEV - Azure PowerShell"
    inputs:
      azureSubscription: "nameOfMyServiceConnection"
      pwsh: true
      azurePowerShellVersion: "LatestVersion"
      failOnStandardError: true
      scriptType: "InlineScript"
      workingDirectory: $(Pipeline.Workspace)/ci/drop/ef-bundles
      Inline: |
        ./lab-db.exe      --connection "$(labConn)"
```

I get the following error:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.
````

I already gave the MI in Tenant A that's connected to the service connection access to the SQL DB.

When I dump env variables, I get the following:
```
AZURESUBSCRIPTION_CLIENT_ID=<MI's object ID in Tenant A>
AZURESUBSCRIPTION_SERVICE_CONNECTION_ID=<A GUID>
AZURESUBSCRIPTION_TENANT_ID=<Tenant A ID>
```

To my understanding, these are not the [expected](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.workloadidentitycredential?view=azure-dotnet#:~:text=Creates%20a%20new%20instance%20of%20the%20WorkloadIdentityCredential%20with%20the%20default%20options.%20When%20no%20options%20are%20specified%20AZURE_TENANT_ID%2C%20AZURE_CLIENT_ID%20and%20AZURE_FEDERATED_TOKEN_FILE%20must%20be%20specified%20in%20the%20environment.) names for env variables.
Also, shouldn't there be a `AZURE_FEDERATED_TOKEN_FILE` as well?

Thanks!

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Microsoft Windows Server 2022

### Relevant log output

```shell
Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```
