### ISSUE TITLE
[BUG]: ##[error]Cannot read properties of undefined (reading 'trim') - Kubelogin

### ISSUE THREAD

**Issue by validis-ad** [microsoft/azure-pipelines-tasks#21080]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

KubeloginInstaller@0

### Task version

0.255.0

### Issue Description

We are seeing this issue transiently in our pipelines. A third run worked.

This is our task, very simple:

```
- ${{ if eq(parameters.azureRBAC, true)}}:
  - task: KubeloginInstaller@0
    displayName: '(Step) Install Kubelogin'
``` 

![Image](https://github.com/user-attachments/assets/2986d50a-309b-4e5b-94da-e332cab8c6f8)

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
See screenshot.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```

**Comment by validis-ad** [comment]
Backlink: https://github.com/microsoft/azure-pipelines-tasks/issues/19097#issuecomment-2965696968

**Comment by EshitaD** [comment]
Hi @validis-ad, could you please provide logs with system.debug as true?

**Comment by validis-ad** [comment]
Hi @EshitaD, we haven't seen this again, but our suspicion was that it is related to GitHub rate limiting? If the task downloads from GitHub each time, then it will run into this issue, even though it's an MS-provided task. This should maybe be a consideration?

**Comment by EshitaD** [comment]
Hi @validis-ad, please let us know if you face this issue once again. For now we are proceeding to close this issue.

**Comment by validis-ad** [comment]
This is still an issue, even though we're applying the github token to the kubeinstaller task we're still getting rate-limited

**Comment by ffdh-mv** [comment]
Not using a custom GitHub token, still happening.

**Comment by validis-devops** [comment]
@ffdh-mv we dropped this kube task entirely and wrapped it instead:

```
steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'Github-Service-Connection'
    userRepository: 'Azure/kubelogin'
    defaultVersionType: 'latest'
    itemPattern: 'kubelogin-linux-amd64.zip'
    downloadPath: '$(Agent.TempDirectory)'
  displayName: '(Step) Download Latest Kubelogin Release'

- bash: |
    # Install kubelogin to replace the buggy KubeloginInstaller@0 task
    # See: https://github.com/microsoft/azure-pipelines-tasks/issues/19097
    
    cd $(Agent.TempDirectory)
    unzip -q kubelogin-linux-amd64.zip
    chmod +x bin/linux_amd64/kubelogin
    sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
    kubelogin --version
  displayName: '(Step) Install Kubelogin'
```
