### ISSUE TITLE
[Question]: Publish code coverage with dotnet test

### ISSUE THREAD

**Issue by scrocquesel-ml150** [microsoft/azure-pipelines-tasks#21101]
### Task name

DotNetCoreCLI

### Task version

2.257.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Question

```shell
I have a dotnet project with XunitV3 for unit testing. I have followed https://learn.microsoft.com/fr-fr/dotnet/core/testing/microsoft-testing-platform-extensions-code-coverage to enable code coverage with MTP.

Test results (.trx) are published but code coverage is not published.

The test command is configured with arguments '-- --report-xunit-trx --results-directory $(Agent.TempDirectory) --coverage'

How to publish them ?
```

**Comment by erstert3st** [comment]
Have you tried
 PublishCodeCoverageResults@1 [src](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines) or   PublishCodeCoverageResults@2  [src](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines) ?

**Comment by scrocquesel-ml150** [comment]
In my case, I'm doint this 

```
    - task: DotNetCoreCLI@2
      displayName: "Run dotnet test"
      inputs:
        command: "test"
        arguments: '--no-restore --no-build --configuration $(BuildConfiguration) -- --coverage '
        projects: |
          $(testProjects)
        publishTestResults: true
```

For this to work, you must include these two packages.

```
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
```

I also opted-in mtp v2 with

```
<PackageReference Include="xunit.v3.mtp-v2" />
```

and have these properties set

```
<PropertyGroup>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
</PropertyGroup>
```

I won't be able to tell you what is really necessary or not, but with this configuration, I have code coverage and test results appearing in the build.
