### ISSUE TITLE
[BUG]: Publishing a web project is automatically publishing nugets to custom feed

### ISSUE THREAD

**Issue by IeuanWalker** [microsoft/azure-pipelines-tasks#21100]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DotNetCoreCLI@2

### Task version

2

### Issue Description

We have the following set that publishes the web projects - 
```
    - task: DotNetCoreCLI@2
      displayName: 'Publish Web Apps'
      condition: and(succeeded(), eq(${{ parameters.ReleaseBotOnly }}, false))
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(WebAppProjects)
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
```

In our project, we have a `nuget.config`, that points to a private nuget artifact feed
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="CardiffCouncilNugets" value="https://pkgs.dev.azure.com/cardiffcouncilict/_packaging/CardiffCouncilNugets/nuget/v3/index.json"/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json"/>
  </packageSources>
</configuration>
```

When the `DotNetCoreCLI` task runs, it's publishing all the nugets to that private feed. Other than that `nuget.config`, nothing in the pipeline is telling it to publish any nugets or specifying a feed to send them to.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

window-latest

### Relevant log output

```shell
Nothing in the logs indicate its sending anything over too the feed
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```
