### ISSUE TITLE
Build: Maven with Code Coverage run tests twice

### ISSUE THREAD

**Issue by igorpaladino** [microsoft/azure-pipelines-tasks#6458]
## Environment

- Server - TFS on-premises - version 16.122.27102.1    
- Agent Private - OS Windows - version 1.98.1

## Issue Description

When using "Build: Maven" task version 1.*,
and selecting a "Code Coverage Tool": JaCoCo for example,
the build run the tests twice.

In the log screen, I can see the following commands:

[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\apache-maven-3.5.2\bin\mvn.cmd" -version"

[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\apache-maven-3.5.2\bin\mvn.cmd" -f E:\agent\_work\34\s\pom.xml help:effective-pom"

[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\apache-maven-3.5.2\bin\mvn.cmd" -f E:\agent\_work\34\s\pom.xml clean package "-Dsonar.host.url=http://mySonar:9000/" "-Dsonar.login=********" "-Dsonar.password=" "-Dsonar.projectName=myProject" "-Dsonar.projectKey=myProject" sonar:sonar checkstyle:checkstyle findbugs:findbugs pmd:pmd"

[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\apache-maven-3.5.2\bin\mvn.cmd" -f E:\agent\_work\34\s\pom.xml verify"

As I have some tests that take long time to run, running the tests twice every build make the build time really worse.

### Error logs

There is no error logs

**Comment by pjquirk** [comment]
@igorpaladino The "verify" step is only run if JaCoCo is selected as the code coverage tool because it [binds to the "verify" phase](http://www.eclemma.org/jacoco/trunk/doc/check-mojo.html).  However, I think the Maven task could be smarter by combining the "clean package" run with the "verify" run.  We'll get this enhancement on our backlog.

**Comment by afeblot** [comment]
Hi @leantk ,
is there any chance you may resolve this issue?

Thanks

**Comment by leantk** [comment]
Hi @afeblot, at the moment we don't have the bandwidth to pick-up this change unfortunately. I can circle back to it again after a couple sprints and try and get some resources on it. If you want/need it done sooner, we take contributions on the tasks since they are open source so we would gladly accept a PR. Just tag me on it and I'd review it for submission.

**Comment by tmahncke-lhind** [comment]
For anybody stumbling accross this issue here is a workaround. Not 100% sure it has no uninteded sideeffects though.

Just add the maven option: 

> -DskipTests

It leads to the tests being skipped in your own maven task and only beeing executed in the newly added verify task.

**Comment by subhaKiruba** [comment]
is the issue resolved ??
Im facing it now while working on codeCoverage

**Comment by subhaKiruba** [comment]
Can someone please help me ?

**Comment by subhaKiruba** [comment]
any update on this issue ??

**Comment by subhaKiruba** [comment]
is this issue resolved ?

**Comment by sdobrodeev** [comment]
@subhaKiruba Could you please provide more technical details about this issue (environment description, part of pipelines file, logs in debug mode)

**Comment by sdobrodeev** [comment]
@subhaKiruba I'm closing due to lack of activity, please feel free to reopen if issue is still actual for you.

**Comment by afeblot** [comment]
Closing for "lack of activity" whereas somebody pinged for an update 13 days ago?
@sdobrodeev, for sure, I'm still waiting/hoping for this to get fixed, please reopen it (I can't).

In our case, and probably as well for everyone else, the issue is exactly as described initially by @pjquirk : https://github.com/microsoft/azure-pipelines-tasks/issues/6458#issuecomment-367459714 :
The maven verify step automatically added by the task when jacoco is enabled executes the tests which were already executed as part of the main "clean install" goal the task was set with.

**Comment by ekaterina-tatanova** [comment]
Created PR: https://github.com/microsoft/azure-pipelines-tasks/pull/13558

**Comment by anatolybolshakov** [comment]
Hi @igorpaladino related changes has been rolled out - I'm closing it at the moment, please feel free to reopen it if issue appears again

**Comment by wilmol** [comment]
Such a basic functionality still broken after 3 years :/

When adding the `codeCoverageToolOption` input to Maven task it makes tests run twice. If excluded, no code coverage report is picked up. I'd expect all that input does is look for the code coverage report.

**Comment by wilmol** [comment]
While the running of tests twice is fixed, it still runs other maven phases twice, for example spotbugs or checkstyle analysis.

I expected that adding the `codeCoverageToolOption` to maven task would simply let the build agent know where to look for code coverage reports, not invoke maven a second time.

**Comment by anatolybolshakov** [comment]
@wilmol could you please create a separate issue for this and share more details?

**Comment by vkelempekis** [comment]
I still have exactly the same issue. I use maven task (v3) in a build, with goals "clean package" and Jackocko + Sonarqube analysis turned on(see below screenshots). The tests are still ran twice, so I'm wondering if there's something I need to update now that the PR with the fix has been merged, or should it just work by default now.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/5721589/118944527-ef699e80-b954-11eb-9bd2-1e5d194667ed.png">
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/5721589/118944567-f8f30680-b954-11eb-82da-fc6a98e62cf1.png">

**Comment by whiskeysierra** [comment]
To those struggling with this, as a viable workaround (or even replacement?), my team moved away from the maven task and switched towards individual tasks, i.e.:

- SonarCloudPrepare (optional)
- JavaToolInstaller
- Bash (to run [mvnw](https://github.com/takari/maven-wrapper))
- PublishTestResults
- PublishCodeCoverageResults
- SonarCloudPublish (optional)

**Comment by vkelempekis** [comment]
@whiskeysierra how do you generate your code coverage summary this way? The PublishCodeCoverageResults expects that

**Comment by whiskeysierra** [comment]
```yaml
    # foreign html is usually broken, use this one, see https://github.com/microsoft/azure-pipelines-tasks/issues/3027
    - task: PublishCodeCoverageResults@1
      displayName: "Maven: Report (JaCoCo)"
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: JaCoCo
        summaryFileLocation: 'target/site/jacoco/jacoco.xml'
        pathToSources: 'src/main/kotlin'
        additionalCodeCoverageFiles: 'target/jacoco.exec'
```

JaCoCo Maven Plugin:

```xml
           <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by vkelempekis** [comment]
@whiskeysierra Thanks for your help already! I am able to successfully publish the results of code coverage to the build itself, but can't seem to have a working setup that can be published to sonarqube. Do the Prepare analysis on SonarQube and Run Sonarqube Analysis tasks do the trick for you? and if so, how are they configured?

**Comment by whiskeysierra** [comment]
```yaml
  - task: SonarCloudPrepare@1
    displayName: 'SonarCloud: Prepare'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'myorg'
      scannerMode: Other
      configMode: ''
      projectKey: gropyus_${{ parameters.project }}_${{ parameters.repository }}
      projectName: ${{ parameters.project }}/${{ parameters.repository }}
      cliProjectKey: gropyus_${{ parameters.project }}_${{ parameters.repository }}
      cliProjectName: ${{ parameters.project }}/${{ parameters.repository }}
      cliSources: ''
      extraProperties: |
        sonar.projectKey=gropyus_${{ parameters.project }}_${{ parameters.repository }}
        sonar.projectName=${{ parameters.project }}/${{ parameters.repository }}

  - task: SonarCloudPublish@1
    displayName: 'SonarCloud: Publish'
    condition: succeededOrFailed()
    inputs:
      pollingTimeoutSec: '300'
```

Maven is being executed with:

```
-D maven.test.failure.ignore=true verify org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar
```
