### ISSUE TITLE
Feature Request: Add --Pull option to Docker run image

### ISSUE THREAD

**Issue by abergs** [microsoft/azure-pipelines-tasks#6913]
### Feature Request

Add a checkbox to add the --pull argument to the Docker task when running an image.

### Problem that this solves
Docker caches images that exist locally and our :latest tag changes a lot (test database with data/scheme updates). This would allow us to always run the newest image published to our registry,

**Comment by azooinmyluggage** [comment]
@abergs I am in the middle of planning the next set of improvements. If you use the $(Build.BuildId) as tag then will that be a blocker? I want to know why to use 'newest' image you want to use the latest tag.

**Comment by abergs** [comment]
We don't have the BuildId available as tag when we publish our docker image.

Our workflow is that another team (manually) pushes a new container to ourcontainer:latest.
Our Pipelines runs that container, "docker run ourcontainer:latest". Since we don't control the tag name (it's always latest) we can never trust our local image to be up-to-date.

**Comment by RicardoLans** [comment]
@abergs I don't know if this is still an issue for you since there has been no response in here for a month but I got this working in my **yaml** build setup as followed:

When a PR completes a merge to master a CI build is triggered which automatically creates a docker image and pushes it to azure container registry.
I use the following to build&push:

```
variables:
  azureSubscription: 'xxx'
  azureContainerRegistry: 'xxx.azurecr.io'
  dockerFile: 'xxx' 
  imageName: 'xxx'

steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    command: Build an image
    dockerFile: $(dockerFile)
    imageName: $(imageName):$(build.buildId)
    includeLatestTag: true

- task: Docker@1
  displayName: Push an image
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    command: Push an image
    imageName: $(imageName):$(build.buildId)
```

This make sure I always have a "latest" image in the ACR.

Now in my PR I need to use the "latest" image to run some automated selenium tests on it.
In that build I use the Docker@1 task with the "run" command and if you give an image name with `:latest` tag it will use latest image from the ACR.

```
- task: Docker@1
  displayName: Run image
  inputs:
    command: run
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(imageName):latest
    containerName: 'xxx'
```

Hope this works for you as well
