### ISSUE TITLE
App Center Distribute task show errors when queuing YAML build

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/azure-pipelines-tasks#7350]
I can use the task App Center Distribute successful in other build definition (and the endpoint MyAppCenter has been configured successful in VSTS):

![app center distribute task - build successful in other build definitions](https://user-images.githubusercontent.com/23092306/40823845-7690532a-65a4-11e8-9489-fc2d9f758a6a.png)

While when a create a YAML build definition and add the App Center Distribute task:

```
- task: AppCenterDistribute@1
  displayName: Deploy $(build.binariesdirectory) to Visual Studio App Center
  inputs:
    serverEndpoint: MyAppCenter
    appSlug: 'marinaliu/Myapp2'
    appFile: '$(build.binariesdirectory)'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: 'release v1.0'
```

But it fails when queuing the YAML build, shows the message as below (but the endpoint actually exist and authorized):

> Phase : Step  input serverEndpoint references endpoint MyAppCenter which could not be found. The service endpoint does not exist or has not been authorized for use.

![yaml build fails when queuing](https://user-images.githubusercontent.com/23092306/40823894-a883189a-65a4-11e8-987f-597cd3f32292.png)
