### ISSUE TITLE
PublishTestResults 

### ISSUE THREAD

**Issue by ColinLaws** [microsoft/azure-pipelines-tasks#8305]
This issue exists on AzureDevops

I am running tests in PHPUnit and logging the test to a JUnit xml file. My build pipeline is setup to publish test results using the PublishTestResults task. 

Here is my XML file generated by PHPUnit in the JUnit format:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="2" assertions="4" errors="0" failures="0" skipped="0" time="1.765531">
    <testsuite name="Unit Tests" tests="2" assertions="4" errors="0" failures="0" skipped="0" time="1.765531">
      <testsuite name="Tests\Unit\DatabaseServiceTest" file="/home/vagrant/src/Website/tests/unit/DatabaseServiceTest.php" tests="2" assertions="4" errors="0" failures="0" skipped="0" time="1.765531">
        <testcase name="a_database_team_member_can_be_added" class="Tests\Unit\DatabaseServiceTest" classname="Tests.Unit.DatabaseServiceTest" file="/home/vagrant/src/Website/tests/unit/DatabaseServiceTest.php" line="35" assertions="2" time="1.656353"/>
        <testcase name="a_database_team_member_can_be_removed" class="Tests\Unit\DatabaseServiceTest" classname="Tests.Unit.DatabaseServiceTest" file="/home/vagrant/src/Website/tests/unit/DatabaseServiceTest.php" line="57" assertions="2" time="0.109178"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

Here is my build pipeline YAML:
```yaml
# https://docs.microsoft.com/azure/devops/pipelines/languages/php
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: npm install
  displayName: 'npm install'

- script: npm run dev
  displayName: 'run mix (webpack)'

- script: phpunit --log-junit test-results.xml
  displayName: 'Run tests with phpunit'

# Publish Test Results
# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@1
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-results.xml' 
```

I receive the following error when the PublishTestResults task runs:
##[warning]Invalid results file. Make sure the result format of the file '/home/vsts/work/1/s/test-results.xml' matches 'JUnit' test results format.

**Comment by SadagopanRajaram** [comment]
Thank you for the feedback. Currently, the JUnit Parser does not support nested test suites in the XML. I am not completely familiar with php unit tests but is there a way for you not to nest test suites in the tests file?

**Comment by ColinLaws** [comment]
The PHPUnit binary accepts the --log-junit option, which outputs my test results in the nested fashion that the JUnit parser does not support. I have found a way to make this work in Azure DevOps (albeit not the best solution, but I got it working).

To make PHPUnit test results work in Azure DevOps with the current JUnit parser, I processed PHPUnit's output using an XSL transform on PHPUnit's output. 

To perform the XSL transform on my build agent in Azure DevOps, I downloaded the Java Archive (.jar) file for Saxon 9 Home Edition and included that in my project's source code. In my build pipeline, I run the XSL transform by calling the java binary and passing the saxon9he.jar file with the appropriate options for pointing it to my test results XML output by PHPUnit.

This is how my build pipeline is configured for running the Saxon 9 jar file. 
```yaml
# Navigate to the saxon folder and run the saxon jar file to transform the test results
# into a format that DevOps can consume
- script: cd saxon && java -jar saxon9he.jar -xsl:phpunit_to_junit.xsl -s:test-results.xml
  displayName: 'Perform XSL transform on test results'

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: '**/*-Test.xml' 
    searchFolder: '$(System.DefaultWorkingDirectory)'
    mergeTestResults: false

# Cleaning up the build by removing the saxon directory that contains the test
# results and the saxon 9 JAR file, as those files are not required for release.
- script: rm -r saxon
  displayName: 'Remove saxon and test results from the build'
```

This is an XSL transform file that formats PHPUnit output in a way that DevOps can parse it:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="2.0">

<xsl:output method="xml"/>

<xsl:template match="/">
<xsl:for-each select="//testsuite[@file]">
    <xsl:variable name="filename" select="concat('TEST-',@name,'-Test.xml')" />
    <xsl:result-document href="{$filename}" method="xml">
        <xsl:copy-of select="." />
    </xsl:result-document>
</xsl:for-each>
</xsl:template>

</xsl:stylesheet>
```
