### ISSUE TITLE
Error publishing code coverage report: path too long

### ISSUE THREAD

**Issue by giggio** [Microsoft/azure-pipelines-tasks#8368]
It seems that I am hitting a path too long problem, which is weird as the whole project is running on Linux.

## Environment
- Server: `VSTS`, account `ticketbr`, TP `TicketShop`, Build id: `215`
- Agent: Private: `Ubuntu 18.04`, running agent `2.140.0`

## Issue Description

When publishing code coverage report I get an error:

Task: `PublishCodeCoverageResults@1`
Log: `Fail to upload '/agent/_works/<REDACTED>/1/s/coverage/src/<REDACTED>' due to 'TF400889: The following path contains more than the allowed 259 characters: Code Coverage Report_215/src/<REDACTED>. Specify a shorter path.'.`
Yaml:
````yaml
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
        condition: succeededOrFailed()
````
