### ISSUE TITLE
ArchiveFiles: File type does not match archive type

### ISSUE THREAD

**Issue by moritzgloeckl** [microsoft/azure-pipelines-tasks#8398]
## Environment
- Azure DevOps Pipeline

- Agent: Self-hosted Windows

## Issue Description

```
- task: ArchiveFiles@2
  displayName: Archive the files
  inputs:
    rootFolderOrFile: 'folder/**/file.txt'
    archiveType: '7z'
```

When `archiveFile` is not specified it defaults to naming the file `.zip`, despite having `archiveType: '7z'`. This results in a corrupted `.zip` file unless the `.zip` file is renamed to `.7z`. `ArchiveFiles` should use the default ending for the specified `archiveType`.

Cheers
