### ISSUE TITLE
DotNetCore tool installer task should add dotnet global tool path to PATH for future tasks

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/azure-pipelines-tasks#8429]
dotnet global tools get installed at $home/.dotnet/tools (or %USERPROFILE%\.dotnet\tools for windows). See [here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-global-tool). This location is added to PATH when dotnet shell is re-opened. As this is not possible in a pipeline workflow where DotNetCore Installer task is used, should the installer task add these paths?

**Comment by cosmoKenney** [comment]
+1

**Comment by bishal-pdMSFT** [comment]
The fix has been rolled out. Please retry the task for global tools scenario.

**Comment by jchannon** [comment]
Just tried and see same issue as linked to above

**Comment by bishal-pdMSFT** [comment]
@jchannon this fix works only if you are ".Net Core too installer" task. Do you have follwoing step in your yaml:

>-task: DotNetCoreInstaller@0
>   inputs:
>     version: 2.2.103

**Comment by jchannon** [comment]
This is my yaml:

```
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#PRs trigger a build automatically

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'REDACTED:latest'

steps:
- task: AzureKeyVault@1
  displayName: 'Load secrets from Azure Key Vault'
  inputs:
    azureSubscription: 'Default' 
    keyVaultName: 'REDACTED-key-vault'
    secretsFilter: 'REDACTED'

- script: |
    dotnet tool install --global minver-cli --version 1.0.0-beta.2
    minver --help
  displayName: 'Install MinVer CLI'
  
- script: |
    export MinVerVersionOverride=$(minver)
    echo $MinVerVersionOverride
  displayName: 'Get build version'

- script: |
    dotnet test ./tests/REDACTED.Tests.Unit/ --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests'
  env:
    AUTH_SERVER__DOCKER__REGISTRY: $(AuthServerDockerRegistry)
    AUTH_SERVER__DOCKER__USERNAME: $(AuthServerDockerUsername)
    AUTH_SERVER__DOCKER__PASSWORD: $(AuthServerDockerPassword)
    Vault: $(Vault)
    ClientId: $(ClientId)
    ClientSecret: $(ClientSecret)

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: |
    docker build -t $AUTH_SERVER__DOCKER__REGISTRY/$(imageName):$(MinVerVersionOverride) --rm .
    echo $AUTH_SERVER__DOCKER__PASSWORD | docker login -u $AUTH_SERVER__DOCKER__USERNAME --password-stdin $AUTH_SERVER__DOCKER__REGISTRY
    docker push $AUTH_SERVER__DOCKER__REGISTRY/$(imageName)
  displayName: 'Build and push docker image'
  condition: and(succeeded(), eq(variables['System.PullRequest.PullRequestId'], ''))
  env:
    AUTH_SERVER__DOCKER__REGISTRY: $(AuthServerDockerRegistry)
    AUTH_SERVER__DOCKER__USERNAME: $(AuthServerDockerUsername)
    AUTH_SERVER__DOCKER__PASSWORD: $(AuthServerDockerPassword)


```
