### ISSUE TITLE
UI not updating: BashV3 doesn't output until entire script is done

### ISSUE THREAD

**Issue by Cheesebaron** [microsoft/azure-pipelines-tasks#8644]
## Environment
- Server - Azure Pipelines
- Agent - Private: macOS 10.13.6, agent 2.140.2

## Issue Description

I am running the default cake bootstrapper: [build.sh](https://github.com/cake-build/resources/blob/develop/build.sh) to build an app for Android and iOS.

I kick it off as follows:

```yaml
- task: Bash@3
  displayName: 'Run CakeBuild'
  inputs:
    targetType: 'filePath'
    filePath: 'build.sh'
```

The task takes around 12 minutes to complete. However, in those 12 minutes I only get `waiting for console output...` so I can't see what is going on until the task is entirely done.

![screen shot 2018-10-18 at 14 28 57](https://user-images.githubusercontent.com/249719/47154293-3b0dc480-d2e2-11e8-99eb-56f8a8fe6791.png)
