### ISSUE TITLE
Publish Pipeline Artifacts Preview - artifacts are not automatically downloaded in release

### ISSUE THREAD

**Issue by drch-** [Microsoft/azure-pipelines-tasks#8777]
## Environment
Azure Pipelines
Hosted Linux Preview    

## Issue Description
Build artifacts created via Publish Pipeline Artifacts (preview) are not downloaded in the release pipeline.

After I realized that this task wasn't working in my pipeline, I tried with Publish Build Artifact, which works fine.  

To compare the two, I created a build definition using both the Publish Build Artifacts and Publish Pipeline Artifacts tasks, named publish_build_artifact and publish_pipeline_artifact.  I added a task to create an out.txt file in $(Build.ArtifactStagingDirectory) as the only file in the artifact.

The build definition:
```yaml
resources:
- repo: self
queue:
  name: Hosted Linux Preview
steps:
- script: 'echo "foo" > out.txt' 
  workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Add file to artifact staging directory'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: 'publish_pipeline_artifact'
    targetPath: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: publish_build_artifact'
  inputs:
    ArtifactName: 'publish_build_artifact'
```
_note; the PathToPublish property of PublishBuildArtifacts@1 is $(Build.ArtifactStagingDirectory), but does not show up in the yaml file._

**Result:**
Only the publish_build_artifact is downloaded in the release pipeline, although all artifacts are selected in the stage.

Both artifacts are generated in the build, however there is something curious about their structure.  When I view the publish_build_artifact, it is shown as a directory containing the file:

**Artifacts list on the build summary page**
![image](https://user-images.githubusercontent.com/343322/47941508-b2507480-deee-11e8-8774-f1008d102dec.png)

**publish_build_artifact**
![image](https://user-images.githubusercontent.com/343322/47941541-d2803380-deee-11e8-9915-d440e909dd17.png)

**publish_pipeline_artifact**
![image](https://user-images.githubusercontent.com/343322/47941566-ed52a800-deee-11e8-8057-59d4d9245d60.png)

The release simply does a ls -R of working directory.  The logs shows only the publlsh_build_artifact being downloaded:
![image](https://user-images.githubusercontent.com/343322/47941830-014ad980-def0-11e8-9dce-26c1799f3acc.png)

Despite the fact that both artifacts are selected in the stage.
![image](https://user-images.githubusercontent.com/343322/47941769-c5b00f80-deef-11e8-9b3e-3ffce3c19ac5.png)
