### ISSUE TITLE
dotnet restore command creates 90K+ lines of logs

### ISSUE THREAD

**Issue by xenalite** [Microsoft/azure-pipelines-tasks#8781]
## Environment
- Server - Azure Pipelines or TFS on-premises?    
    - Azure Pipelines - rcss-willistowerswatson - AML - 57146
- Agent - Hosted or Private: 
    - Private - Windows Server 2016 - 2.141.1

## Issue Description

I have a `dotnet restore` task configured in YAML as follows:
```
### Restore NuGet packages ###
      - task: DotNetCoreCLI@2
        displayName: Restore NuGet packages
        inputs:
          command: restore
          projects: $(Sources)/**/*.csproj
          vstsFeed: b2b08bfc-02e4-4f36-bd50-092a5627099e
```

Even when no new packages need to be restored, the task always runs for at least 1+ minute.
In this time, it produces 90,000+ lines of logs without diagnostics and 137,000+ lines of logs with diagnostics.

Locally, when I run `dotnet restore` I get just a few lines of logs, and the command finishes in about 5 seconds as expected:
```
PS C:\Workspace\AML\src> dotnet restore
  Restore completed in 46.22 ms for <some_project>.csproj.
  (...)
  Restore completed in 4.25 ms for <some_project>.csproj.
```

The solution contains a mixture of .NET Standard, .NET Core and .NET Framework projects. All csproj files are using the new format with `PackageReference` element.

### Task logs

Non diagnostics logs:
[log_17_57143.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2550854/log_17_57143.zip)

Diagnostics logs:
[log_17_57146.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2550856/log_17_57146.zip)

**Comment by kuvinodms** [comment]
Currently I'm not actively working on this, will provide updates once I get back to this issue.

**Comment by kuvinodms** [comment]
Assigning it to @alexmullans who owns restore command

**Comment by xenalite** [comment]
@alexmullans Issue mitigated by modifying yaml step definition as below:
```
      ### Restore NuGet packages ###
      - task: DotNetCoreCLI@2
        displayName: Restore NuGet packages
        inputs:
          command: restore
          projects: $(Sources)/AML.sln
          vstsFeed: b2b08bfc-02e4-4f36-bd50-092a5627099e
          verbosityRestore: minimal
```

Changing the verbosing to minimal prints only 200 log entries, and the restore step finishes in 10s instead of 2 minutes. According to the docs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops), the default verbosity is `detailed`. Perhaps it could be dropped down? Otherwise I am happy to close this.
