### ISSUE TITLE
Add task to download file from URL

### ISSUE THREAD

**Issue by mikeharder** [Microsoft/azure-pipelines-tasks#8798]
Please consider adding a task to download a file from a URL.  I saw similar tasks like `DownloadBuildArtifacts` and `DownloadPackage`, but nothing to download a file from a URL.  The best cross-platform solution I've found so far is a python script:

```yaml
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: from urllib.request import urlretrieve; urlretrieve('$(url)', '$(fileName)')
```

But I'd rather use a specific task like:

```yaml
- task: DownloadFile@0
  inputs:
    source: '$(url)'
    destination: '$(fileName)'
```
