### ISSUE TITLE
Help Requested - Xcode project with multiple provisioning profiles fails archive and sign

### ISSUE THREAD

**Issue by alombard** [Microsoft/azure-pipelines-tasks#8811]
Hello @madhurig & @bryanmacfarlane,

I'm new to DevOps so please go easy on me if I've missed something basic :)

I’m using the following:
-Hosted MacOS with an Xcode Build Agent (Xcode Version 5.142.0)

I've just started trying to set up a pipeline for an Xcode based project which uses multiple provisioning profiles.  In my scenario I have profiles for the following in my app:

- Intents
- ItentsUI
- Widget
- App 

I've followed the instructions for setting up certs and provisioning profiles here **(although my project uses automatic signing)**: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=vsts&tabs=apple-install-during-build

These are being installed correctly to a hosted build agent (no errors) and the build is proceeding perfectly until signing.  

During signing it seems that the none of the targets can find their provisioning profiles (both when using 'manual' or 'default' (nothing entered) assignment).  

Here's whats run in the logs:

`[command]/usr/bin/xcodebuild -workspace /Users/vsts/agent/2.142.1/work/1/s/*MYAPP**.xcworkspace -scheme **MYAPP** archive -sdk iphoneos -configuration Release -archivePath /Users/vsts/agent/2.142.1/work/1/s/**MYAPP** CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER= | /usr/local/bin/xcpretty --no-color`

Then later when it comes to archiving the following for each scheme:

`error: "xxx Today Widget" requires a provisioning profile with the Push Notifications and App Groups features. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'xxx Today Widget')`

A few questions:

1.) Is there an updated guide for this that I can follow for my use case (can't help but wonder if I'm missing something as this seems a fairly common need).

2.) Alternatively is there a way to force which profile gets used for which scheme when archiving and signing?

3.) **Is automatic signing possibly supported (or is this in the backlog)?**  I think this is something which most of us now take as a given when building locally or using tools like Fastlane for build and distribution.

For completeness I've seen what looks like a somewhat similar issue here: https://github.com/Microsoft/azure-pipelines-tasks/issues/964 but it's been closed for more than two years.  

Thanks for taking a look guys!

Andrew

**Comment by alombard** [comment]
Hi Folks - it turns out after closer inspection the development certificate I had been using was the wrong one (there were a few on my Mac).  I swapped this for the appropriate version and the issues went away.  

I can now successfully build, archive and sign.

Hopefully this helps someone.

Andrew

**Comment by daelhoser** [comment]
Hello @alombard, I'm having a similar issue but i am using the correct certificate. I uploaded the 3 provisioning profiles using the tasks but unfortunately it only recognizes one profile.  Any help to getting the yml file completed is greatly appreciated. thanks.

**Comment by alombard** [comment]
> Hello @alombard, I'm having a similar issue but i am using the correct certificate. I uploaded the 3 provisioning profiles using the tasks but unfortunately it only recognizes one profile. Any help to getting the yml file completed is greatly appreciated. thanks.

Hey @daelhoser - one tip is to make sure you can can get Xcode to build your solution and archive it from the command line.  Xcode does a lot of magic for you when you package your app and if you can reproduce that via command line then you can troubleshoot on DevOps. 

It will look something like this (you will need an exportOptions.plist in order to include multiple profiles - this can be built or copied see here: https://blog.bitrise.io/new-export-options-plist-in-xcode-9).

In terms of DevOps Yaml see below from one of my projects:

```
- task: Xcode@5

  displayName: 'Xcode Production Build & Export (clean archive) - use exportOptions.plist for Signing'

  inputs:
    actions: 'clean archive'
    xcWorkspacePath: YourProject.xcworkspace
    scheme: 'Your Scheme'
    xcodeVersion: specifyPath
    xcodeDeveloperDir: $(xcodeDir)
    packageApp: true
    exportPath: output/Production/YourProject.ipa
    exportOptions: plist
    exportOptionsPlist: exportOptions.plist
    signingOption: default
```

Hope this helps!

Andrew
