### ISSUE TITLE
Specifying an explicit feed for NuGet restore

### ISSUE THREAD

**Issue by jaredpar** [microsoft/azure-pipelines-tasks#8850]
We are attempting to provide an explicit feed for a NuGet restore step in our build. The intent is this feed should override the other settings in our repositories (config files, build properties, etc ...). The only documentation we found on this is the following:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts

The documentation about overriding build settings refers to the UI, not the YAML settings: 

> Select this option to use NuGet.org and/or one Azure Artifacts/Package Management feed in the same organization/collection as the build.

Looking at the YAML dump at the top of the file I ended up trying this setting:

``` yaml
   #vstsFeed: # Required when feedsToUse == Select
```

That does not appear to work though. When an explicit feed is provided in the following form it is not used. The logs indicate that only the default NuGet feed is considered

``` yaml
- task: NuGetRestore@1
  inputs:
    solution: 'build\ToolsetPackages\InternalToolset.csproj'
    vstsFeed: 'https://devdiv.pkgs.visualstudio.com/'
```

Logs:

```
2018-11-15T18:51:58.0287527Z Restoring packages for E:\A\_work\94\s\build\ToolsetPackages\InternalToolset.csproj...
2018-11-15T18:51:58.0455536Z Restoring packages for .NETFramework,Version=v4.7.2...
2018-11-15T18:51:58.3806123Z   GET https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.ibcmerge/index.json
2018-11-15T18:51:58.6021140Z   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.ibcmerge/index.json 221ms
```

What do I need to specify in the YAML to get my specific feed used?

Links for more detailed info:
- Build demonstrating the error https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2208168&view=logs
- Commit with the change: https://github.com/dotnet/roslyn/commit/c6b293a14df9350d000354477915024a967283a1

**Comment by phil-hodgson** [comment]
Given a target feed with:
- Name = myfeed
- Source = https://devdiv.pkgs.visualstudio.com/_packaging/myfeed/nuget/v3/index.json
- Id = 64b8e088-a2d9-408a-a1d2-ce0fb2725952

You may want something like...

```
steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'build\ToolsetPackages\InternalToolset.csproj'
    vstsFeed: <FeedIdOrName>
    includeNuGetOrg: false
```

where `<FeedIdOrName>`:= `'64b8e088-a2d9-408a-a1d2-ce0fb2725952'` or `'myfeed'`

Hint: If you create a non-YAML build definition, add and configure the appropriate NuGet task, and set the parameters, you can then use the "View YAML" button to get the required YAML to use.
