### ISSUE TITLE
PowerShell view yaml generates invalid yaml when arguments are set

### ISSUE THREAD

**Issue by aaronpowell** [Microsoft/azure-pipelines-tasks#8871]
## Environment
- Azure DevOps Pipelines (account aaronpowell)

## Issue Description

When you create a PowerShell v2 task and set arguments to the script the YAML generated is invalid in the _View YAML_ UI.

I was generated this:

```yaml
steps:
- powershell: ./build.ps1
  arguments: '-Target Setup'

  displayName: 'Setup environment'
```

Which results in a parse error from Azure Pipelines:

```
azure-pipelines.yml (Line: 7, Col: 3): Unexpected value 'arguments'
```

[View Build](https://aaronpowell.visualstudio.com/Chauffeur/_build/results?buildId=249&view=results).

### Workaround

Updating to use the non-shorthand YAML and it works:

```yaml
- task: PowerShell@2
  displayName: 'Setup environment'
  inputs:
    filePath: ./build.ps1
    arguments: '-Target Setup'
```
