### ISSUE TITLE
VSTest@2 task seem only able to run TP v1; need to run multi-targeted test project

### ISSUE THREAD

**Issue by aggieben** [Microsoft/azure-pipelines-tasks#8911]
## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/true-myth/TrueMyth

- Agent - Hosted
    - If using Hosted agent, provide agent queue name: Unsure; I'm using separate Windows (VS2017) and Linux (ubuntu-16.04) jobs

## Issue Description
The problem I'm having is that I have a project targeting both `net461` and `netstandard2.0`, and I  need VSTest to execute my test suite for both.  My understanding is that TP v2 is required for this, but I am somehow unable to cause the `VSTest@2` task to use TP v2; it seems to only use the v1 executable and ignores the `vstestLocation` property in the YAML.

https://dev.azure.com/true-myth/TrueMyth/_build/results?buildId=20&view=results

My YAML file can be seen here: https://github.com/true-myth/true-myth-csharp/blob/next/azure-pipelines.yml

How can I ensure that I'm using TPv2, and then also, how can I make the VSTest task run the test suite for all targeted frameworks?

**Comment by aggieben** [comment]
Ok, it looks like I overlooked a property on the task.  I'm using this now:
```yaml
- task: VSTest@2
  inputs:
    testAssemblyVer2: 'test\TrueMyth.Test\TrueMyth.Test.csproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vstestLocationMethod: location
    vstestLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
```

The task now picks up the TP v2 executable as configured, but: it doesn't actually run any tests:

![image](https://user-images.githubusercontent.com/1321/49188270-c346a700-f32f-11e8-87da-903d4d2ddf22.png)

Key line (for searching):
`##[warning]No results found to publish.`
