### ISSUE TITLE
Azure File Copy build task not available on hosted Ubuntu build agent

### ISSUE THREAD

**Issue by benne** [microsoft/azure-pipelines-tasks#8920]
## Environment
- Server - Azure Pipelines
    Account name: chaosbyte
    Team project name: D Test
    Build definition name: D Test-CI
    Build number: 9

- Agent - Hosted: 
    Queue name: Not sure
    It is hosted a Ubuntu 16.04 build agent

## Issue Description
I got a project building some pulling from an external Git repository, and building it with `gcc` through a simple bash script - no problem.
However, when I attempt to use the `Azure File Copy` task to copy over the single output file to a Azure Blob Storage container, I am told that this task won't run on Linux.
Is there any plans to make `Azure File Copy` work on the hosted Ubuntu 16.04 build agent, or do you have any other suggestion on how to achieve the same result with existing tasks that will run on this hosted build server?

### Error logs
```
2018-11-27T18:03:41.7033273Z ##[section]Starting: AzureBlob File Copy
2018-11-27T18:03:41.7038323Z ==============================================================================
2018-11-27T18:03:41.7038468Z Task         : Azure File Copy
2018-11-27T18:03:41.7038567Z Description  : Copy files to Azure blob or VM(s)
2018-11-27T18:03:41.7038647Z Version      : 2.0.15
2018-11-27T18:03:41.7038738Z Author       : Microsoft Corporation
2018-11-27T18:03:41.7038823Z Help         : [More Information](https://aka.ms/azurefilecopyreadme)
2018-11-27T18:03:41.7038939Z ==============================================================================
2018-11-27T18:03:41.7244544Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2018-11-27T18:03:41.7258675Z ##[section]Finishing: AzureBlob File Copy
```

**Comment by chrisrpatterson** [comment]
@benne you could use the az cli to do the file copy and that task will work on Linux

**Comment by benne** [comment]
@chrisrpatterson `az cli` might be my best option for now, using a non-interactive service principal. I am gonna experiment a bit with this.

Still interested in if this is gonna make it to the road-map at some point. It would be nice to use the build-in build task for future projects :)

**Comment by chrisrpatterson** [comment]
@benne I will leave the roadmap for that task up to the team that owns the task.  The az cli task should work with the same service principal you would have setup for the Azure File Copy task.

**Comment by benne** [comment]
@chrisrpatterson I went with a service principal with specific permissions to contribute to a specific storage account. Combined with an `Azure CLI` build task I was able to upload the assets to the blob storage.
Success!

**Comment by kmkumaran** [comment]
@benne - Making Azure File copy xPlat is in our backlog. Adding @RoopeshNair . Until then using Azure CLI will be the right way to solve.

**Comment by RoopeshNair** [comment]
Bouncing an idea here, we are evaluating whether we can expose Azure storage as a file drive. When available you can copy the files over using SSH or Remote PS. AzCopy.

**Comment by luyseyal** [comment]
azcopy is available on Linux
https://aka.ms/downloadazcopy-v10-linux

**Comment by mounarshisantra** [comment]
if we are using the az cli to achieve the same functionality, we are not getting the same flexibility as the Azure File Copy task in terms of getting the storage uri and sastoken as output. We need to make additional cli calls to achieve the same . So, it would be great if the file copy task works xPlat.

**Comment by motowilliams** [comment]
The AzureFileCopy task and the az cli workaround is **not** at feature parity with each other. I wonder how many teams, like I just did, spent time adding the task to the pipeline, watching it fail and then searching the internet for a couple of hours.  This is how I found this issue. The docs on this are also weak.

**Comment by titimoby** [comment]
Is there any progress to this?
It is very strange that tasks like JavaToolInstaller are able to copy installer file from Azure Storage but we can't use AzureFileCopy to copy files to Azure Storage.

**Comment by minhtrieu-aemo** [comment]
Trying to migrate our pipelines to use self-hosted Linux agent and discovered that its failing due to AzureFileCopy not being supported on Linux. It would be great if this can be made to work with Linux!

**Comment by weznagwama** [comment]
Another bump for an update on this.

**Comment by alexangas** [comment]
I've written a YAML task template for Azure Pipelines that fills this gap for now. You can find it on my blog here: https://www.alexangas.com/blog/missing-azurefilecopy-azcopy-task-solved/

Feedback is very welcome! Please raise as an issue on the [repo for my blog](https://github.com/alexangas/alexangas-web) rather than polluting this thread, thanks.

**Comment by veton** [comment]
For the time being, using **windows image** as a workaround:

```
  - deployment: deploy_staging
    environment: staging
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureFileCopy@3
            inputs:
              sourcePath: $(Pipeline.Workspace)/$(artifactName)
              azureSubscription: $(azureSubscription)
              destination: azureBlob
              storage: memes
              containerName: $web
```

**Comment by rifuller** [comment]
This also left me very confused.  This obviously should work on linux hosts.

**Comment by tckb** [comment]
More than a year later, the docs are still stale. I’m in the same boat, anyone found any workarounds for this issue ?

**Comment by jamiehaywood** [comment]
is there an update on this?

**Comment by jamiehaywood** [comment]
I wanted to share my own solution to this that works with `vmImage:ubuntu-latest`:
```yml
  - task: AzureCLI@1
    displayName: Az File Copy to Storage
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload-batch \
          --destination \$web \
          --account-name "$(storageAccountName)" \
          --source "$(Agent.BuildDirectory)/$(outputDir)"
```

**Comment by sebastianrogers** [comment]
Critical thing here is that Azure File Copy will return a SAS Token allowing you to then access these files via ARM deployment.

**Comment by beauof** [comment]
Thanks for sharing your workarounds! Yet, I am still waiting for the AzureFileCopy task on Linux agents because I can't always remember this issue until I see another failed pipeline. :)

**Comment by jwbrindle** [comment]
umm, have been hoping to see some kind of update on this for over a year, what gives guys, can we get some support on this? GA opened since azcopy v10 for linux, why couldnt this be integrated?

**Comment by cee-money** [comment]
+1, it would be great to see an update on this

**Comment by ascott18** [comment]
This is a terrible experience for your customers. Why is something so basic as copying files not supported on Linux agents the same as it is supported on Windows?

**Comment by nadesu** [comment]
@vijayma pls triage

**Comment by dancooktoptal** [comment]
+1

**Comment by khenriksson** [comment]
+1

**Comment by boylec** [comment]
+1

**Comment by pstiegele** [comment]
+1

**Comment by crgarcia12** [comment]
+1

**Comment by FlorianJDF** [comment]
+1

**Comment by hacktick** [comment]
+1 (i can already see the headlines in the washington post newspaper in the year 2038 - "Microsoft has finalized file copy for linux pipelines - it is now in the testing stage and soon ready for RC stage") :-)

**Comment by benne** [comment]
Switched to Windows hosts for the specific project, but would still love to see a cross-platform solution that just works as intented :)

**Comment by alswinehartMRI** [comment]
@jamiehaywood thank you so much! Does anyone know how I can narrow down copying to a repo's subfolder? I'm trying this now with wild guesses and it's either erroring out or copying all the unnecessary files, which ends up taking over 60 minutes and erroring out anyway.

**Comment by johnynfulleffect** [comment]
+1, please allow to run on linux

**Comment by acgar** [comment]
+1

**Comment by snowjobgit** [comment]
+1

**Comment by Jaykul** [comment]
Any chance this is finally being addressed in v5? 🤣🙄

**Comment by hcoona** [comment]
Years & years later :(

**Comment by ngcdev** [comment]
I wonder if the "roadmap" is that kind of map of "where do you see yourself in 10 years"... a bunch of tasks work flawlessly in Linux hosts, but this one gets no attention

**Comment by dct2012** [comment]
+1

**Comment by michal-pawlowski** [comment]
+1

**Comment by gyermakavets** [comment]
+1

**Comment by Shaharajshaik** [comment]
+1

**Comment by n-alex-white** [comment]
Four and a half years (including a whole pandemic) and this still isn't working? Is it still on the backlog @kmkumaran ?

**Comment by ngcdev** [comment]
We changed our pipelines to use PowerShell (since now PowerShell core works in both OSes) and used `az` commands to do the copy instead. Working good so far.

**Comment by johnwc** [comment]
@starkmsu @onetocny @DmitriiBobreshev think anyone can possibly look into this issue from 2018?

**Comment by kolosovpetro** [comment]
`AzCopy` may be used directly from `AzureCLI@2` as follows
```yaml
- task: AzureCLI@2
  displayName: 'AzCopy via Azure CLI'
  inputs:
    azureSubscription: 'AzCopyARM'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $Date = (Get-Date).AddDays(1).ToString('yyyy-MM-dd')
      $key = $( az storage account keys list --resource-group $(rgName) --account-name $(storageAccount) --query [0].value -o tsv )
      $sas = $( az storage container generate-sas --name $(container) --expiry $Date --permissions "racwdli" --account-name $(storageAccount) --account-key "$key" )
      azcopy copy "./seed_images/*" "https://$(storageAccount).blob.core.windows.net/$(container)/from_az_cli?$(SAS)" --recursive=true
```

See docs:

- https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines
- https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

**Comment by basdakkenhorst** [comment]
The following seems to work to "copy" text files (or shell scripts, or ....) to a VM from a pipeline, using a pipeline variable:

Disclaimer: I must admit I scared myself by doing this. Far from clean, but at least it seems to work.

```yaml
jobs:
- job: TextCopyToVM
 
  steps: 
  
  - bash: |
      filePath="$(< path/to/some/text/file/from/git/repo.txt)"
      #
      # Replace \n with %0D%0A, so a multiline pipeline variable is possible
      #
      escapedFile=$(echo "$filePath" | sed ':a;N;$!ba;s/\n/%0D%0A/g')
      echo "##vso[task.setvariable variable=localFileEscaped]$escapedFile"

  - task: AzureCLI@2
    displayName: 'Echo var into file'
    inputs:
      azureSubscription: '<Azure Subscription Name>'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "localFileEscaped: $(localFileEscaped)"
        COPY_FILE="$(az vm run-command invoke -g <RESOURCE GROUP> -n <VM NAME> --command-id RunShellScript --scripts 'echo "$(localFileEscaped)" > /some/path/to/file/on/vm.txt')"
```
