### ISSUE TITLE
MSBuild is invoked multiple times when the clean argument is set to true

### ISSUE THREAD

**Issue by pjcollins** [microsoft/azure-pipelines-tasks#8948]
## Environment
- Server - Azure Pipelines - DevDiv - Build Definition: `CompatLab PR (blank-forms-template)` / `2242052`

## Issue Description
Looking over the relevant [MSBuild task source](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/MSBuildV1/msbuild.ts#L43-L62), `MSBuild` will always be invoked twice if `clean` is set to true, regardless of the value of any arguments or additional targets provided. The "problem" I am encountering with this design occurs when I provide my own "build" target via `msbuildArguments` and set the `clean` argument to true.

My YAML in this case task looks something like this, and is used for building a Xamarin.Android project type:
```yaml
 - task: MSBuild@1
    displayName: build $(app.project.droid)
    inputs:
      solution: $(app.project.droid)
      platform: $(platform)
      configuration: $(configuration)
      msbuildArguments: /t:SignAndroidPackage /bl:$(app.id)-$(configuration)-$(platform).binlog
      clean: true
```

When this `MSBuild` task executes, I end up with an initial `MSBuild` invocation that calls the `Clean` and `SignAndroidPackage` targets sequentially as I would expect. However, this is followed by a secondary incremental build of the `SignAndroidPackage` target, and the binary log file that I am attempting to capture (which represents a "rebuild") is overwritten by the second `MSBuild` invocation. There is also a small additional time cost incurred by performing this unnecessary second build.

I'm able to work around this by no longer setting the `clean` argument to true, and modifying my `msbuildArguments` to include `Clean` (e.g. `/t:Clean;SignAndroidPackage`). However, perhaps the `MSBuild` task could be "enhanced" slightly by one of the following changes:
* Add an explicit 'target' argument to the `MSBuild` task, and ignore this value during the initial `Clean` invocation.
* Strip any arguments which start with `/t:` from the initial `Clean` invocation.
* Don't invoke `MSBuild` twice when the `clean` arg is set to true, and ensure that the `Clean` target is appended first to the `MSBuild` invocation.
