### ISSUE TITLE
support snupkg creation in dotnet pack

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/azure-pipelines-tasks#9107]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure

    - If using TFS on-premises, provide the version: 

n/a
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://opencensus.visualstudio.com/continuous-integration/_build/results?buildId=187

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

Hosted VS2017

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I'm trying to enable [snupkg](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) for the build. It requires to pass additional argument to `dotnet` task: `dotnet pack MyPackage.csproj --include-symbols -p:SymbolPackageFormat=snupkg`. However `arguments` is not working for `pack` command. Perhaps because of this condition, I couldn't tell:

https://github.com/Microsoft/azure-pipelines-tasks/blob/72c3f2d6c6f667f6aa718edc59709456edba9912/Tasks/DotNetCoreCLIV2/task.loc.json#L117-L125

### Task logs

Updated yml to:

```
- task: DotNetCoreCLI@2
  displayName: pack solution with symbols (Release)
  inputs:
    command: "pack"
    projects: "*.sln"
    configuration: 'Release'
    packDirectory: '$(build.artifactStagingDirectory)'
    arguments: "-p:SymbolPackageFormat=snupkg"
```

But `arguments` didn't apply:

```
2018-12-17T23:53:21.2299034Z [command]C:\Windows\system32\chcp.com 65001
2018-12-17T23:53:21.2387489Z Active code page: 65001
2018-12-17T23:53:21.3965400Z [command]C:\hostedtoolcache\windows\dncs\2.2.100\x64\dotnet.exe pack D:\a\1\s\src\OpenCensus.Abstractions\OpenCensus.Abstractions.csproj --output D:\a\1\a /p:Configuration=Release --verbosity Detailed
2018-12-17T23:53:21.6345355Z Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
2018-12-17T23:53:21.6345919Z Copyright (C) Microsoft Corporation. All rights reserved.
```
