### ISSUE TITLE
CondaEnvironment task should support conda env

### ISSUE THREAD

**Issue by mtaron** [Microsoft/azure-pipelines-tasks#9120]
The CondaEnvironment build task uses the "conda create" command. It would be *much* better from my perspective if it used "conda **env** create", or at least had the option to do so.

I create an [environment.yml](https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually) for each of my projects so that teammates can just run `conda env create -f environment.yml` to get all the dependencies they need for the specific project in an isolated environment. This works in a platform agnostic way. BUT `conda create` does not work with environment.yml files! `conda create --file` takes a "requirements.txt" style file that you can create by running `conda list --export > conda_requirements.txt`. These requirement files are platform specific. Obviously, I don’t want to have an environment.yml file and a conda_requirement.txt file that I regenerate every time I change the .yml file.

To work around this in Azure Pipelines, you could do something like this:

```yml
- script: $(CONDA)/Scripts/conda.exe env create --file environment.yml --name myenv
  displayName: Create conda environment

- task: CondaEnvironment@1
  displayName: Clone and activate conda environment
  inputs:
    updateConda: false
    createCustomEnvironment: true
    environmentName: ci
    packageSpecs: '' # empty string required; defaults to python=3, which conflicts with createOptions :(
    createOptions: '--clone myenv'
```

But due to #8504 , the CondaEnvironment task can't even be used for activation. :(

Once that issue has been addressed, it would much cleaner and faster (no extra clone) if the CondaEnvironment task supported env command directly.
