### ISSUE TITLE
Copy via bash on windows hosted agent not copying as expected

### ISSUE THREAD

**Issue by psibi** [microsoft/azure-pipelines-tasks#9158]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Using Azure Pipelines. You can find the environment here: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=143

- Agent - Hosted or Private: 
    
Agent name: vs2017-win2016

## Issue Description

Something like this doesn't seem to work for Windows agent (although works fine for Linux and MacOS):

```
  - bash: |
      cp somefile $(Build.ArtifactStagingDirectory)
    displayName: Copy
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: some-artifact-name
```

The actual build pipeline replicating the issue: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=143

No build artifacts are published for the Windows environment.

You can see in the above build that the same thing works for both Linux and OSX.
