### ISSUE TITLE
Task PowerShellV2 does not validate targetType parameter

### ISSUE THREAD

**Issue by sandermvanvliet** [Microsoft/azure-pipelines-tasks#9198]
## Environment
- Server - Azure Pipelines
- Agent - Hosted VS2017

## Issue Description

The PowerShellV2 task currently only checks if the `targetType` parameter is set to `FILEPATH` to determine if it needs to run a script instead of an inline script defined in the `script` parameter. If no script parameter has been provided then it will run the default "Hello, world" script instead.

When using the visual way of configuring build pipelines this is obvious enough, the UI clearly shows the script it will run. However when using the YAML style configuration this is non-obvious.

This issue is compounded by a bug in the Azure DevOps YAML export which generates the following:
```yaml
steps:
- task: PowerShell@2
  displayName: 'Cake build'
  inputs:
    targetType: './'
    filePath: build.ps1
    arguments: '--Target Pull-Request'
```

Although syntactically correct, the result is that this block will output "Hello, world" in the build log when run.

The cause for this is that although the `targetType` has two options (`filePath` and `inline`) the task itself only checks for `filePath` and does not notify the user when there is no `script` parameter supplied if the `targetType` is either missing or not `filePath`.

I have created PR #9197 that has a proposed way of handling this, however it might (probably will) break some usage expectations so feedback is very much appreciated.
