### ISSUE TITLE
YAML: does paths:exclude: support user-defined variables?

### ISSUE THREAD

**Issue by BryanWilhite** [microsoft/azure-pipelines-tasks#9235]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines
    - the account name, team project name, build definition name/build number: https://songhay.visualstudio.com/SonghaySystem/_build?definitionId=15

- Agent - Hosted: 
    - If using Hosted agent, provide agent queue name: `Pool: Hosted VS2017 Agent: Hosted Agent`

## Issue Description

I check in files under the directories intended for exclusion (e.g. `Songhay.Dashboard.Tests/README.md`) and builds run. I assume a CI build will not be invoked when a file is pushed into an excluded folder. The YAML declarations:
![image](https://user-images.githubusercontent.com/5226627/50669901-cc551480-0f7c-11e9-8710-50741c2eef15.png)

```yaml
variables:
  BuildConfiguration: 'Release'
  RepoName: 'Songhay.Dashboard'

trigger:
  batch: false
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - /azure*.yml
    - $(RepoName).Shell.Tests/*
    - $(RepoName).Tests/*
```

https://github.com/BryanWilhite/Songhay.Dashboard/blob/master/azure-pipelines.yml

Also `/azure*.yml` is simply being ignored as well.
