### ISSUE TITLE
Searching a way to allow specific matrix entries to fail

### ISSUE THREAD

**Issue by weiznich** [microsoft/azure-pipelines-tasks#9302]
## Environment
Repo: [diesel.rs/diesel](https://github.com/diesel-rs/diesel/)

## Issue Description

We have setup azure pipelines as automatic CI service for diesel.rs. That works mostly fine.
Now it is specific to the rust ecosystem that there are several compiler version, notably a stable version, a beta version and a nightly version. The later is updated every night a may not work. To detect such broken version projects are encouraged to run their CI also with the nightly version of the rust compiler, but setup the CI in such a way that failing builds with a nightly compiler are ignored. Basically I've found no way to do this with azure pipelines.

**Comment by moswald** [comment]
This may be possible with our yaml builds. @ericsciple do you know if this can be done?

**Comment by ericsciple** [comment]
@vtbassmatt fyi

@weiznich  Unfortunately it is not allowed today. The current solution would be to model it as a separate job.

**Comment by vtbassmatt** [comment]
@ericsciple how do you prevent a task failure from bubbling up to the job (or job failure from bubbling up to the pipeline)? I could update the docs with a pattern for implementing allow-failure, but I don't actually know how to do it 😀

**Comment by ericsciple** [comment]
@vtbassmatt `continueOnError` is a task-level control and job-level control. However, when set on the job I believe it applies to all configurations.

My initial thoughts are: that behavior makes sense, especially as we think about deployment phases coming soon. If we need additional control, we might want an additional option somewhere else.

This is a similar problem to `condition`. The property actually exists at the phase-level, not on each job configuration.

A workaround would be to use templates instead of matrix.

Rather than adding additional controls, it makes me wonder whether the correct long term solution here is something like templates without actually requiring you to declare a separate file.

**Comment by chriskrycho** [comment]
This is going to end up being a serious pain point for effective adoption in both the Rust and Ember.js communities, where it's common to run against the current stable release, the current beta release, and often also the current unstable/nightly/master channel. (We're doing it against beta on ember-cli-typescript.) In that case, it's perfectly acceptable for the beta channel to fail, and it shouldn't report that the whole build failed as a result. Unfortunately, because it's at a job or task level, it's not possible to handle with matrixes as far as I can see (and as your comment suggests).

**Comment by vtbassmatt** [comment]
Thanks @chriskrycho - good to hear reinforcement of how important this is. If you want to point me at an example pipeline, I might be able to suggest a workaround. (And to be clear, it'll be a workaround, not the solution we want to deliver.)

**Comment by chriskrycho** [comment]
@vtbassmatt thanks! Here is our config for the ember-cli-typescript project:

- [top-level config lines of interest](https://github.com/typed-ember/ember-cli-typescript/blob/master/azure-pipelines.yml#L70:L84)
- [template](https://github.com/typed-ember/ember-cli-typescript/blob/master/.azure/ci-template.yml)

**Comment by vtbassmatt** [comment]
Gotcha. Here's how I'd work around the limitation. In the template, add a parameter `allowedToFail` defaulted to `false`. In the template, update the lines that run tests:
```yaml
  - ${{ if not(eq(parameters.allowedToFail, 'true')) }}:
    - script: |
        ${{ parameters.emberTestCommand }}
      displayName: ${{ parameters.emberTestDisplayName }}
  - ${{ if eq(parameters.allowedToFail, 'true') }}:
    - script: |
        ${{ parameters.emberTestCommand }}
        exit 0
      displayName: ${{ parameters.emberTestDisplayName }}
```

Then in your top-level pipeline, you'll have to have separate matrixes for the allowed-to-fail legs:
```yaml
  - job: ember_cli_versions
    displayName: 'ember-cli'
    dependsOn: linux_fixed
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        release:
          eCliVersion: latest
    steps:
      - template: .azure/ci-template.yml
        parameters:
          emberCliVersion: $(eCliVersion)
  - job: ember_cli_versions_allowed_failures
    displayName: 'ember-cli [allowed failures]'
    dependsOn: linux_fixed
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        beta:
          eCliVersion: beta
    steps:
      - template: .azure/ci-template.yml
        parameters:
          emberCliVersion: $(eCliVersion)
          allowedToFail: 'true'
```

**Comment by mike-north** [comment]
```yaml
    - script: |
        ${{ parameters.emberTestCommand }}
        exit 0
      displayName: ${{ parameters.emberTestDisplayName }}
```
With this use of `exit 0`, it seems like a reviewer would have to actually dig into the test logs of each passing pull request, in order to ascertain whether a given code change introduced a build failure on these allowed-to-fail jobs.

It's still very important to surface feedback about these failures in a first class way. 

An example implementation might involve using GitHub's [`CheckRun`](https://developer.github.com/v3/checks/runs/) feature to report failures with a "neutral" or "warning" state in the pull request "checks" page, while still marking the [`Status`](https://developer.github.com/v3/repos/statuses/) as green.

#### Example of Neutral Status
<img width="1254" alt="github_apps_checks_annotations" src="https://user-images.githubusercontent.com/558005/56338078-57899d00-615d-11e9-83a3-0a70103c0425.png">

Currently, Azure Pipelines does not make full use of this feature
#### Azure Pipeline Warnings
<img width="1090" alt="Screen Shot 2019-04-17 at 10 09 47 PM" src="https://user-images.githubusercontent.com/558005/56338133-aa635480-615d-11e9-8860-5cdc7f6be20e.png">

By adding this capability, developers could do something like

```yaml
script: <test-command> | echo "##vso[task.logissue type=warning;] Yikes!!"
```

to effectively turn failures into warnings
