### ISSUE TITLE
ApacheJMeterLoadTest@1 loses generated csv

### ISSUE THREAD

**Issue by mercer** [Microsoft/azure-pipelines-tasks#9377]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

## Issue Description

- expected behaviour: scenario jmx defines the output.csv, so I expect the csv to be generated 
- actual behaviour: no csv generated

## Task definition
```
  - task: ApacheJMeterLoadTest@1
    displayName: "Run performance tests"
    inputs:
      TestDrop: performance
      LoadTest: performance.jmx
      runDuration: 300

```
