### ISSUE TITLE
PowerShellV2 task fails when targetType inline with arguments

### ISSUE THREAD

**Issue by tspanos** [microsoft/azure-pipelines-tasks#9403]
```
#azure-pipelines.yml
trigger: none

jobs:
  - job: build_troubleshoot
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: PowerShell@2
      displayName: 'Run Inline PowerShell with Arguments'
      inputs:
        targetType: inline
        arguments: -First the_first_arg -Second the_second_arg
        script: |
            Param ([Parameter(Mandatory)][string]$First, [Parameter(Mandatory)][string]$Second)
            
            Write-Host $First
            Write-Host $Second
```

Using inline mode with arguments results in an error. Packaging the exact script that is used in inline mode into a file and using targetType: filepath works. My theory is the parser or script generator is causing the script to shift down a line and with the `Param` statement on the second line and not the first, the script fails.

This is easily reproducible by using the YAML excerpt provided above. Is this desired behavior or a bug... I can't find any documentation stating that inline targetType PowerShellV2 tasks don't support using arguments.

Example error output:
```
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.140.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
Generating script.
##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\a7ce4f95-806d-451d-8a1e-7b9af34324ec.ps1'"
Param : The term 'Param' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\a7ce4f95-806d-451d-8a1e-7b9af34324ec.ps1:2 char:1
+ Param ([Parameter(Mandatory)][string]$Major, [Parameter(Mandatory)][s ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Param:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
##[error]PowerShell exited with code '1'.
```
