### ISSUE TITLE
Azure pipeline , error at npm install. 

### ISSUE THREAD

**Issue by arashbahreini** [microsoft/azure-pipelines-tasks#9421]
## Azure DevOps Type and Version
I have below script 
```
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk' 
      version: '2.2.100' 

  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.0' 
      #checkLatest: false # Optional

  - script: 'dotnet clean $(backendDirName)/server.sln'
    displayName: Server - Clean

  - script: 'dotnet build $(backendDirName)/server.sln'
    displayName: Server - Build

  - script: 'dotnet test $(backendDirName)'
    displayName: Server - Test

  - script: 'npm --prefix ./$(frontDirName) install ./$(frontDirName)'
    displayName: Client - installation

  - script: 'npm run build --prefix $(frontDirName)'
    displayName: Client - Build 

```
## What's not working?
Please include error messages and screenshots.

I get error at point of Npm install !!!

The error is 

```
2019-01-24T08:25:15.5876529Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
2019-01-24T08:25:15.5876999Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2019-01-24T08:25:15.5878377Z 
2019-01-24T08:25:15.5913825Z npm ERR! code ELIFECYCLE
2019-01-24T08:25:15.5918430Z npm ERR! errno 1
2019-01-24T08:25:15.5921796Z npm ERR! ng-packagr@4.6.0 postinstall: `opencollective postinstall`
2019-01-24T08:25:15.5922341Z npm ERR! Exit status 1
2019-01-24T08:25:15.5923633Z npm ERR! 
2019-01-24T08:25:15.5923947Z npm ERR! Failed at the ng-packagr@4.6.0 postinstall script.
2019-01-24T08:25:15.5924162Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-01-24T08:25:15.6774873Z 
2019-01-24T08:25:15.6775578Z npm ERR! A complete log of this run can be found in:
2019-01-24T08:25:15.6775812Z npm ERR!     C:\npm\cache\_logs\2019-01-24T08_25_15_607Z-debug.
