### ISSUE TITLE
Powershell task yaml doesn't work as intended

### ISSUE THREAD

**Issue by ds-ms** [Microsoft/azure-pipelines-tasks#9429]
I've created the following YAML for executing an inline script via Powershell task
```yaml
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: PowerShell@2
  inputs:
    script: 'Write-Host "hello world"'
```
Due to logic here: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/powershell.ts#L29 

The task defaults to check for `FilePath` and fails with the following error: 
```
##[error]Invalid file path 'D:\a\1\s'. A path to a .ps1 file is required.
```

But, in the docs here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell it says that `targetType` is an optional parameter.
