### ISSUE TITLE
dotnet cli Reportgenerator custom command fails

### ISSUE THREAD

**Issue by jilpansi** [Microsoft/azure-pipelines-tasks#9472]
When i try to add a custom dotnet.exe task (reportgenerator), the command fails with the following message.

No executable found matching command "dotnet-reportgenerator"

I have tried all the combinations as mentioned here: https://github.com/Microsoft/azure-pipelines-tasks/issues/7194

Any help is appreciated.

![image](https://user-images.githubusercontent.com/37311995/52070256-6db89180-254e-11e9-81aa-3433c6f7d606.png)

**Comment by ThomasBDO** [comment]
I have the same issue. Running on Linux in dotnet core 2.1 project

From my Azure-Pipelines.yaml
```yaml
pool:
  vmImage: 'Ubuntu-16.04'

# Run unit tests
- task: DotNetCoreCLI@2
  displayName: 'Running unit tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=testresults.trx"'

# Run code coverage
- task: DotNetCoreCLI@2
  displayName: 'Running code coverage'
  inputs: 
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(System.DefaultWorkingDirectory)/TestResults/Coverage/'

# Create report
- task: DotNetCoreCLI@2
  displayName: "Generating code coverage Reports"
  inputs:
    projects: '**/*Tests/*.csproj'
    command: custom
    custom: reportgenerator
    arguments: "-reports:$(System.DefaultWorkingDirectory)/TestResults/Coverage/*.xml -targetdir:results -reporttypes:HTMLInline;HTMLChart"

```

In my .csproj for the test-project, I have:
```xml
<ItemGroup>
    <DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.0.15" />
```

**Comment by RTodorov** [comment]
Same here. Even when I try installing the tool manually:

```
- script: reportgenerator "-reports:$(Build.SourcesDirectory)/CodeCoverage/coverage.cobertura.xml" "-targetdir:CodeCoverage" "-reporttypes:HTMLInline;HTMLChart"
    displayName: Generate Code Coverage HTML Report
```

**Comment by issacnitin** [comment]
@jilpansi @ThomasBDO @RTodorov 

We're investigating the issue.
To unblock yourselves, you can use dotnet-reportgenerator-globaltool as a workaround

You can install the tool by 
```
  - task: DotNetCoreCLI@2
    displayName: Install ReportGenerator Global Tool
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-reportgenerator-globaltool -g

```

And then add a CommandLine script to the pipeline, to execute
```
reportgenerator <Arguments>
```

**Issue with Linux:**
We found a bug in Linux agent, where the PATH is not getting updating after global installation of dotnet tools. To workaround this, you need to add another CommandLine script before calling reportgenerator:
```
echo "##vso[task.prependpath]$HOME/.dotnet/tools"
```
Please note it needs to be a seperate task, before reportgenerator is used
Issue raised: https://github.com/Microsoft/azure-pipelines-image-generation/issues/798

Let me know if this doesn't work. Please be assured we'll investigate and resolve the issue with dotnet-reportgenerator-cli as soon as possible
