### ISSUE TITLE
Azure SQL Database Deployment - Print outputs not shown, even when set to verbose

### ISSUE THREAD

**Issue by timmkrause** [Microsoft/azure-pipelines-tasks#9500]
## Environment
- Server - Azure Pipelines
- Agent - Hosted VS2017

## Issue Description
- Task name - Azure SQL Database Deployment

Basically I want `PRINT` outputs from `Invoke-Sqlcmd` (which is used in case of "Inline SQL Script" and "SQL Script File") to show up in the log when [`-Verbose`](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps#examples) is provided.

Setting `system.debug` to `True` is not a real option.

### Task logs
Nothing shows up between `Invoke-Sqlcmd` and `Finishing` but many `PRINT` outputs should be shown:

2019-02-04T08:23:05.7040752Z ##[section]Starting: Execute pre-deployment script
2019-02-04T08:23:05.7047737Z ==============================================================================
2019-02-04T08:23:05.7047887Z Task         : Azure SQL Database Deployment
2019-02-04T08:23:05.7047949Z Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
2019-02-04T08:23:05.7048046Z Version      : 1.2.9
2019-02-04T08:23:05.7048095Z Author       : Microsoft Corporation
2019-02-04T08:23:05.7048153Z Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
2019-02-04T08:23:05.7048263Z ==============================================================================
2019-02-04T08:23:14.4480132Z Sql file: D:\a\r1\a\Foo\Database\PreDeployment.sql
2019-02-04T08:23:14.4481060Z Invoke-Sqlcmd -ServerInstance "foo.database.windows.net" -Database "Foo-Pre-Production" -Username "foo@bar"  -Password ******  -Inputfile "D:\a\r1\a\Foo\Database\PreDeployment.sql" -Verbose -ConnectionTimeout 120
2019-02-04T08:23:19.2047193Z ##[section]Finishing: Execute pre-deployment script

**Comment by Ajay-MS** [comment]
@timmkrause 

In order to get debug logs (output of `PRINT` statement) in SQL script using SQL Azure Dacpac deployment task, it includes two steps:
1. Enabled release debug logs ( Add release variable `system.debug` with value `true`)
2. In additional arguments of task, provide -verbose. 

E.g.
**Enable release debug logs**
![image](https://user-images.githubusercontent.com/16772764/52322719-29226f80-2a00-11e9-85ef-75ceaee99d29.png)


**Provide -verbose argument**
![image](https://user-images.githubusercontent.com/16772764/52322676-fe381b80-29ff-11e9-9ce1-0a5bfebbdf1c.png)

**Task output**
![image](https://user-images.githubusercontent.com/16772764/52322820-8b7b7000-2a00-11e9-95ae-552312032573.png)

**Comment by timmkrause** [comment]
As I just mentioned "setting `system.debug` to `True` is not a real option".
IMHO this should only be used in debugging scenarios because it makes the whole pipeline noisy.

What I want is fine-grained control over certain tasks. In these 2 scenarios:

1. When deploying a DACPAC I want to **see** the actual change script, I achieved this via `/Diagnostics:True` (Azure SQL Database Deployment task uses `sqlpackage.exe`) - This is working totally fine, `sqlpackage` forwards the additional output produced by `/Diagnostics:True` and I am able to see (besides other stuff) the change script.

2. When executing a script file (or an inline script) `Invoke-Sqlcmd` is used to achieve this task, my assumption was if I apply `-Verbose` to the Azure SQL Database Deployment task I am able to produce the same behavior as with `sqlpackage` and `/Diagnostics:True` which means that `Invoke-Sqlcmd -Verbose` logs should just be shown by the task.

At a minimum this is an inconsistent behavior if not to say a bug?

We will pretty likely move into the direction of calling `Invoke-Sqlcmd -Verbose` directly so that there is no instance in between which swallows these logs.

**Comment by Ajay-MS** [comment]
Agree with you over inconsistent behaviour for verbose logs across Dacpac deployment and Script execution. 

We will surely look into this.

**Comment by timmkrause** [comment]
Sounds great, thank you!

**Comment by lukaskolafa** [comment]
I am having the same issue. Thanks for opening and solving this ticket!

**Comment by timmkrause** [comment]
Why?

**Comment by Ajay-MS** [comment]
PR - https://github.com/Microsoft/azure-pipelines-tasks/pull/9741

**Comment by BlakesHeaven** [comment]
I'm not convinced this is resolved. I have tried a simple PRINT 'Hello World'; both inline and in a file and the only way of getting "Hello World" to appear in the release log is to set `system.debug` to "True" and as stated this is not a real option. Far too much noise.

Adding -Verbose appears to do nothing as well.
Below is the yaml
```yaml
steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: 'Deploy using : !Config_ExecuteScriptByDevOps.sql'
  inputs:
    TaskType: sqlQuery
    SqlFile: '$(System.DefaultWorkingDirectory)\OOTB.Config.Database\Deploy\Publish\!Config_ExecuteScriptByDevOps.sql'
    ServerName: '$(SqlServer)'
    DatabaseName: '$(ConfigDatabaseName)'
    AuthScheme: sqlServerAuthentication
    SqlUsername: '$(SqlUserName)'
    SqlPassword: '$(SqlUserPassword)'
    AdditionalArgumentsSql: '-Verbose'
```

If there is anything I can check, change or confirm; I'm love to know.
Thanks.

**Comment by DJSkruge** [comment]
I used sqlAdditionalArguments: '-verbose' and it worked fine for me. below is an example of what i used. 
```
            - task: SqlAzureDacpacDeployment@1
              displayName: 'test'
              inputs:
                azureSubscription: "test"
                AuthenticationType: 'servicePrincipal'
                Servername: '$(ServerName)'
                DatabaseName: '$(DatabaseName)'
                deployType: 'SqlTask'
                SqlFile: 'test.sql'
                sqlAdditionalArguments: '-verbose'
```
