### ISSUE TITLE
YAML PowerShellV2 with targetType filePath does not pass scriptArguments

### ISSUE THREAD

**Issue by ddkserv** [Microsoft/azure-pipelines-tasks#9555]
## Environment
- Server - Azure Pipelines or TFS on-premises? **Server**
    
    - If using TFS on-premises, provide the version: **N/A**
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: **Account: danfoss, team project name: cms, build definition name: Xplanation.Umbraco-PreMerge / id:75918**

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **Agent: Hosted Agent**

## Issue Description

[Include task name(s), screenshots and any other relevant details]
**Does not work:**
```yml
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: 'filePath'
    filePath: 'Source/FindLatestVersionToPublish.ps1'
    workingDirectory: Source
    scriptArguments: '-targetFolder . -destinationFolder $(build.artifactstagingdirectory)'
```
**Works:**
```yml
- task: PowerShell@1
  displayName: 'PowerShell Script'
  inputs:
    scriptName: Source/FindLatestVersionToPublish.ps1
    arguments: '-targetFolder . -destinationFolder $(build.artifactstagingdirectory)'
    workingFolder: Source
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
2019-02-12T12:13:53.5910760Z D:\a\1\s\Source\FindLatestVersionToPublish.ps1 : Cannot process command 
2019-02-12T12:13:53.5911241Z because of one or more missing mandatory parameters: targetFolder 
2019-02-12T12:13:53.5911431Z destinationFolder.

### Error logs

For yaml task PowerShell@2 (version 2) when targetType is 'filePath' then scriptArguments are not passed to script.
