### ISSUE TITLE
Using dependency variables in custom condition variable expression

### ISSUE THREAD

**Issue by ajbeaven** [microsoft/azure-pipelines-tasks#9565]
## Problem description

After setting a variable in a Powershell step using the following code:
```
Write-Host "##vso[task.setvariable variable=$(VariableName);isOutput=true]$(VariableValue)"
```

I'm trying to retrieve that variable in a subsequent job for use as a custom condition variable expression:
```
eq(dependencies.AgentJob1.outputs['SetVariable.ReadyToDeploy'], 'true')
```
Unfortunately I receive the following error when the agent attempts to start that job:
```
Exception Message: Unrecognized value: 'dependencies'. Located at position 4 within expression: eq(dependencies.AgentJob1.outputs['SetVariable.ReadyToDeploy'], 'true'). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996 (type ParseException)
Exception Stack Trace:    at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.HandleUnknownKeyword(ParseContext context) in d:\v2.0\P1\_work\7\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 278
   at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.CreateTree(ParseContext context) in d:\v2.0\P1\_work\7\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 85
   at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.CreateTree(String expression, ITraceWriter trace, IEnumerable`1 namedValues, IEnumerable`1 functions) in d:\v2.0\P1\_work\7\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 18
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.PhaseConditionEvaluator.ShouldExecutePhase(IVssRequestContext requestContext, ReleaseEnvironment releaseEnvironment, DeployPhaseSnapshot deployPhaseSnapshot, AutomationEngineInput automationEngineInput) in d:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\PhaseConditionEvaluator.cs:line 26
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in d:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 208 
```

It appears [from the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#dependencies) that this available for YAML, and I had hoped it would also be supported in the GUI. Is this not the case or is my syntax just wrong?

## Screenshots for context

![capture](https://user-images.githubusercontent.com/657201/52700597-35e52b80-2fdd-11e9-9fde-4be42b046cac.PNG)

The "SetVariable" task group is made up of the aforementioned powershell script to set the variable:

![capture](https://user-images.githubusercontent.com/657201/52700651-590fdb00-2fdd-11e9-8207-abe58dec8db3.PNG)

**Comment by luciobemquerer** [comment]
+1

**Comment by Bubeee** [comment]
Hi guys, any updates on this?

**Comment by richardgragasin** [comment]
Any updates on this? im facing similar issue :)

**Comment by teh13th** [comment]
Any updates?

**Comment by rggentil** [comment]
Same issue over here, getting the same error:
Unrecognized value: 'dependencies'. Located at position 4 within expression

Any progress?

**Comment by anouarattn** [comment]
Same issue

**Comment by vtbassmatt** [comment]
Not supported.

**Comment by djj0809** [comment]
> Not supported.

Hi @vtbassmatt, what do you mean by "Not supported"?

**Comment by vtbassmatt** [comment]
Designer-based builds don't accept output variables from other jobs. That's a feature only in YAML.

**Comment by jason-e-gross** [comment]
It doesn't work in YAML, either - and yet the documents dated 8/2020 still show it.   I'd recommend this be re-opened.

`##[error]Unrecognized value: 'dependencies'. Located at position 10 within expression: contains(dependencies.`

**Comment by vtbassmatt** [comment]
@jason-e-gross Sorry for the confusion - cross-stage dependencies need a different syntax depending on whether you're consuming them at stage level or job level.

I see that [this topic](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks) still has some outdated info, which I'll get corrected. [This doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies) is up to date with respect to the various syntaxes involved.

## Stage-level
```yaml
stages:
- stage: A
  condition: false
  jobs:
  - job: A1
    steps:
    - script: echo Job A1
- stage: B
  condition: in(dependencies.A.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
  jobs:
  - job: B1
    steps:
    - script: echo Job B1
```

## Job-level consumption
```yaml
stages:
- stage: A
  jobs:
  - job: A1
    steps:
     - bash: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"
     # or on Windows:
     # - script: echo ##vso[task.setvariable variable=shouldrun;isOutput=true]true
       name: printvar

- stage: B
  dependsOn: A
  jobs:
  - job: B1
    condition: in(stageDependencies.A.A1.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - script: echo hello from Job B1
  - job: B2
    condition: eq(stageDependencies.A.A1.outputs['printvar.shouldrun'], 'true')
    steps:
     - script: echo hello from Job B2
```

**Comment by djpugh** [comment]
@vtbassmatt - I'd suggest some clarification here on both this issue the error message that's shown is not at all helpful, and I'm not clear on how your comment resolves this for @jason-e-gross - I am getting a similar error when expanding conditions set as parameters in a template, but the syntax matches your example ```dependencies.<jobname>.outputs['stepname.outputvar']```

**Comment by nichoio** [comment]
I'm struggling with a similar issue. I wanted to combine `if` syntax with checking for the output of a previous job, but this doesn't seem to be supported unfortunately:

```
variables:
  - name: my_var
  ${{ if eq(dependencies.my_job.result, 'Succeeded') }}:
    value: true
  ${{ if in(dependencies.my_job, 'Skipped', 'Failed', 'Canceled') }}:
    value: false
```

This gives me `Unrecognized value: 'dependencies'. Located at position 4 within expression`.
I ended up with duplicating the job and its code except for changing the desired variable value.

**Comment by anotherancientalien** [comment]
eq(dependencies.xxtaskname.result, 'Succeeded') has the same error

**Comment by pablosguajardo** [comment]
any solution?
do releases have dependencies?
I have seen that this works well in the pipeline but not in the releases.

**Comment by janis-veinbergs** [comment]
Seems that `dependencies` must be applied at a `job` `condition` and not at lower level (task). I noticed documentation only features samples where dependencies are used within `condition` only under `stage` or `job` https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops

I'v tried apply it to a task condition and it failed. At `job` it doesn't fail (DevOps 2020 Server)

So this works:
```yml
  - job: PostBuild
    dependsOn: Build
    condition: |
      and(
        succeededOrFailed(),
        and(
          eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
          eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
        )
      )
    steps:
      - checkout: none
      - task: PowerShell@2
        ...
```

And this doesn't and gives said error:
```yml
  - job: PostBuild
    dependsOn: Build
    steps:
      - checkout: none
      # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
      - task: PowerShell@2
        condition: |
          and(
            succeededOrFailed(),
            and(
              eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
              eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
            )
          )
          ...
```

**Comment by JontyMC** [comment]
> Seems that `dependencies` must be applied at a `job` `condition` and not at lower level (task). I noticed documentation only features samples where dependencies are used within `condition` only under `stage` or `job` https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
> 
> I'v tried apply it to a task condition and it failed. At `job` it doesn't fail (DevOps 2020 Server)
> 
> So this works:
> 
> ```yaml
>   - job: PostBuild
>     dependsOn: Build
>     condition: |
>       and(
>         succeededOrFailed(),
>         and(
>           eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
>           eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
>         )
>       )
>     steps:
>       - checkout: none
>       - task: PowerShell@2
>         ...
> ```
> 
> And this doesn't and gives said error:
> 
> ```yaml
>   - job: PostBuild
>     dependsOn: Build
>     steps:
>       - checkout: none
>       # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
>       - task: PowerShell@2
>         condition: |
>           and(
>             succeededOrFailed(),
>             and(
>               eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
>               eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
>             )
>           )
>           ...
> ```

Workaround is to set the value as a variable:

```yaml
- job: PostBuild
  dependsOn: Build
  variables:
    npmFinished: $[dependencies.Build.outputs['npmfinished.yes']]
    cacheRestored: $[dependencies.Build.outputs['restoreNpmCache.cacheRestored']]
  steps:
    - checkout: none
    # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
    - task: PowerShell@2
      condition: |
        and(
          succeededOrFailed(),
          and(
            eq(variables.npmFinished, 'true'),
            eq(variables.cacheRestored, 'false')
          )
        )
        ...
```
This feels like a bug and I think the ticket should be reopened.

**Comment by jason-e-gross** [comment]
> > Seems that `dependencies` must be applied at a `job` `condition` and not at lower level (task). I noticed documentation only features samples where dependencies are used within `condition` only under `stage` or `job` https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
> > I'v tried apply it to a task condition and it failed. At `job` it doesn't fail (DevOps 2020 Server)
> > So this works:
> > ```yaml
> >   - job: PostBuild
> >     dependsOn: Build
> >     condition: |
> >       and(
> >         succeededOrFailed(),
> >         and(
> >           eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
> >           eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
> >         )
> >       )
> >     steps:
> >       - checkout: none
> >       - task: PowerShell@2
> >         ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And this doesn't and gives said error:
> > ```yaml
> >   - job: PostBuild
> >     dependsOn: Build
> >     steps:
> >       - checkout: none
> >       # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
> >       - task: PowerShell@2
> >         condition: |
> >           and(
> >             succeededOrFailed(),
> >             and(
> >               eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
> >               eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
> >             )
> >           )
> >           ...
> > ```
> 
> Workaround is to set the value as a variable:
> 
> ```yaml
> - job: PostBuild
>   dependsOn: Build
>   variables:
>     npmFinished: $[dependencies.Build.outputs['npmfinished.yes']]
>     cacheRestored: $[dependencies.Build.outputs['restoreNpmCache.cacheRestored']]
>   steps:
>     - checkout: none
>     # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
>     - task: PowerShell@2
>       condition: |
>         and(
>           succeededOrFailed(),
>           and(
>             eq(variables.npmFinished, 'true'),
>             eq(variables.cacheRestored, 'false')
>           )
>         )
>         ...
> ```
> 
> This feels like a bug and I think the ticket should be reopened.

Y'know, I'd be really interested in these steps you have for caching the npm packages even on failed builds, if it's something you're willing to share.

**Comment by janis-veinbergs** [comment]
> Y'know, I'd be really interested in these steps you have for caching the npm packages even on failed builds, if it's something you're willing to share.

Azure Devops Online has this working task, which is not working on self hosted on-premises server: [Pipeline Caching - Node.js/npm](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm)

For On-Premises I do it like this 🤯

```yml
jobs:
  - job: Build
  ...
      # Cache the npm cache folder https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm
    # Because npm ci deletes the node_modules folder to ensure that a consistent, repeatable set of modules is used, you should avoid caching node_modules when calling npm ci. I do use npm install - faster.
    # Cache@2 task doesn't work on prem
    - task: PowerShell@2
      name: restoreNpmCache
      displayName: Restore npm cache
      env:
        Agent_BuildDirectory: $(Agent.BuildDirectory)
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)\Pipeline\RestoreFromCache.ps1'
        arguments: '-KeyFile "$(WebResourcesPath)\package-lock.json" -TargetFolder "$(npm_config_cache)"'
        errorActionPreference: 'continue'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      
    - task: PowerShell@2
      name: restoreNodeModulesCache
      displayName: Restore node_modules cache
      env:
        Agent_BuildDirectory: $(Agent.BuildDirectory)
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)\Pipeline\RestoreFromCache.ps1'
        arguments: '-KeyFile "$(WebResourcesPath)\package-lock.json" -TargetFolder "$(WebResourcesPath)\node_modules"'
        errorActionPreference: 'continue'
        workingDirectory: '$(System.DefaultWorkingDirectory)'


    - task: Npm@1
      name: npm
      inputs:
        command: 'install'
        workingDir: $(WebResourcesPath)
    
    - task: PowerShell@2
      name: npmfinished
      inputs:
        targetType: 'inline'
        script: Write-Output "##vso[task.setvariable variable=yes;isOutput=true]true"
  ...
  - job: PostBuild
    dependsOn: Build
    condition: |
      and(
        succeededOrFailed(),
        and(
          eq(dependencies.Build.outputs['npmfinished.yes'], 'true'),
          eq(dependencies.Build.outputs['restoreNpmCache.cacheRestored'], 'false')
        )
      )
    steps:
      - checkout: none
      # Saves cache even if Build failed, but npm ci step succeeded (cacheRestored variable successfully set.).
      - task: PowerShell@2
        env:
          Agent_BuildDirectory: $(Agent.BuildDirectory)
        displayName: Cache npm
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)\Pipeline\SaveToCache.ps1'
          arguments: '-KeyFile "$(WebResourcesPath)\package-lock.json" -TargetFolder "$(npm_config_cache)"'
          errorActionPreference: 'continue'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - task: PowerShell@2
        env:
          Agent_BuildDirectory: $(Agent.BuildDirectory)
        displayName: Cache node_modules
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)\Pipeline\SaveToCache.ps1'
          arguments: '-KeyFile "$(WebResourcesPath)\package-lock.json" -TargetFolder "$(WebResourcesPath)\node_modules"'
          errorActionPreference: 'continue'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
```

SaveToCache.ps1:
```ps
param(
    [string]$KeyFile,
    [string]$TargetFolder,
    [string]$CacheRoot = "$env:Agent_BuildDirectory\azCache"
)

$CachePath = Join-Path $CacheRoot "$([System.IO.Path]::GetFileName($TargetFolder))/$((Get-FileHash $KeyFile -Algorithm SHA256).Hash)"
 
if (Test-Path $CachePath) {
    Write-Output "`"$CachePath`" exists - cache save not needed"
} else {
    Write-Output "Move-Item `"$TargetFolder\*`" -Destination `"$CachePath`""
    New-Item -ItemType Directory -Force -Path $CachePath
    Move-Item "$TargetFolder\*" -Destination $CachePath -Force
    Remove-Item "$TargetFolder"
}
```

RestoreFromCache.ps1
```ps
param(
    [string]$KeyFile,
    [string]$TargetFolder,
    [string]$CacheRoot = "$env:Agent_BuildDirectory\azCache"
)

$CachePath = Join-Path $CacheRoot "$([System.IO.Path]::GetFileName($TargetFolder))/$((Get-FileHash $KeyFile -Algorithm SHA256).Hash)"

#Cache does not exist for this key
if (!(Test-Path $CachePath -PathType Container)) {
    Write-Output("Cache Miss: `"$CachePath`"")

    #Set Pipeline Varaible
    Write-Host "##vso[task.setvariable variable=cacheRestored;isOutput=true]false"
} else{
   Write-Output("Cache Hit. `"$CachePath`"")

   If(!(test-path $TargetFolder)){
       #Create Symbolic link to cache
       New-Item -ItemType SymbolicLink -Path "$TargetFolder" -Target "$CachePath\$target_folder" -Force
   }

    #Set Pipeline Varaible
    Write-Host "##vso[task.setvariable variable=cacheRestored;isOutput=true]true"
}
```
