### ISSUE TITLE
Error: required flag(s) "filename" not set

### ISSUE THREAD

**Issue by jaganathanb** [Microsoft/azure-pipelines-tasks#9572]
## Environment
2019-02-13T12:48:18.9467078Z Task         : Deploy to Kubernetes
2019-02-13T12:48:18.9467133Z Description  : Deploy, configure, update your Kubernetes cluster in Azure Container Service by running kubectl commands.
2019-02-13T12:48:18.9467202Z Version      : 1.1.20
2019-02-13T12:48:18.9467249Z Author       : Microsoft Corporation

## Issue Description
I have used two tasks to create kubernate configmaps (create) and deploy (apply). 
![image](https://user-images.githubusercontent.com/3873744/52715136-ad0cc680-2fc1-11e9-8ee0-afbea8de74b6.png)

Though `Use configuration` is unchecked in commands section, The task is trying to use the configuration file and failed with the `filename not set`. 

***Note that i used the task to create only configmap but i could see there are two tasks executed. One is to create configmap and other one tries to create deployment with the configuration file which is not set.***

### Task logs from kubectl create configmap
2019-02-13T12:48:20.1112479Z Found tool in cache: kubectl 1.12.4 x64
2019-02-13T12:48:20.1148239Z Prepending PATH environment variable with directory: C:\BuildAgent\path\to\kubectl\1.12.4\x64
***2019-02-13T12:48:21.6754302Z [command]C:\BuildAgent\path\to\kubectl\1.12.4\x64\kubectl.exe -n somenamespace create configmap sample-config --from-file=appsettings.json=C:\BuildAgent\path\to\appsettings.json***
2019-02-13T12:48:21.9190640Z configmap/sample-config created
***2019-02-13T12:48:22.0322860Z [command]C:\BuildAgent\path\to\kubectl\1.12.4\x64\kubectl.exe create -n somenamespace -o json***
2019-02-13T12:48:22.0618218Z Error: required flag(s) "filename" not set

### Error logs
2019-02-13T12:48:22.0618218Z Error: required flag(s) "filename" not set

**Comment by ds-ms** [comment]
@jaganathanb The fix for this issue has already been fixed in: https://github.com/Microsoft/azure-pipelines-tasks/pull/9506 
The version of the task is `1.1.22`, are you still facing the issue? 
If yes, what is your organization name? Perhaps I could get you an estimate of how long it would take for the fix to reach you.

**Comment by jaganathanb** [comment]
Thanks for the update. Looks like we have to update from .20 to .22 if the fix is with .22 version. Let me verify and close the issue.

**Comment by bansalaseem** [comment]
@jaganathanb, can you please share whether it works for you or not?

**Comment by ajay-sainy** [comment]
I am also getting the same error when creating a secret. I have used a key vault task to download certificate.

2019-03-16T01:52:47.8563968Z Task         : Deploy to Kubernetes
2019-03-16T01:52:47.8564142Z Description  : Deploy, configure, update your Kubernetes cluster in Azure Container Service by running kubectl commands.
2019-03-16T01:52:47.8564334Z Version      : 1.1.27
2019-03-16T01:52:47.8564474Z Author       : Microsoft Corporation
2019-03-16T01:52:47.8564608Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=851275)
2019-03-16T01:52:47.8564788Z ==============================================================================
2019-03-16T01:52:49.0452549Z Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/windows/amd64/kubectl.exe
2019-03-16T01:52:49.6610353Z Caching tool: kubectl 1.13.2 x64
2019-03-16T01:52:49.7050429Z Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\kubectl\1.13.2\x64
2019-03-16T01:52:50.7016129Z [command]C:\hostedtoolcache\windows\kubectl\1.13.2\x64\kubectl.exe create secret generic sericerp-cert --from-file=D:\a\r1\a\MyCert.pfx
2019-03-16T01:52:50.8498273Z secret/sericerp-cert created
2019-03-16T01:52:50.8745771Z [command]C:\hostedtoolcache\windows\kubectl\1.13.2\x64\kubectl.exe create -o json
2019-03-16T01:52:50.9240901Z Error: required flag(s) "filename" not set

**Comment by AceHack** [comment]
I am having this issue as well, our org is Itron

**Comment by ds-ms** [comment]
@AceHack could you share some logs and the provided inputs (in YAML preferably) from your run?

**Comment by ds-ms** [comment]
@ajay-sainy The issue with your config was, you were calling `kubectl create` but not supplying any arguments to it. When it's trying to run this step `C:\hostedtoolcache\windows\kubectl\1.13.2\x64\kubectl.exe create -o json` it fails saying there aren't any values supplied.
Here are some [reference docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#create) for kubectl create

**Comment by AceHack** [comment]
V1 fails.
```
variables:
  KubernetesNamespace: 'kayaks'
  KubectlVersion: '1.12.2'

steps:
- task: Kubernetes@1
  displayName: 'kubectl create configmap'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-use-arch-dev'
    namespace: '$(KubernetesNamespace)'
    command: create
    configMapName: 'archsamplesapicontainers-config'
    forceUpdateConfigMap: true
    useConfigMapFile: true
    configMapFile: 'Arch.Samples.Api.Containers-CI/Deploy/deploy/config/Arch.Samples.Api.Containers/appsettings.json'
    versionSpec: '$(KubectlVersion)'
    checkLatest: true
```

V0 works:
```
variables:
  KubernetesNamespace: 'kayaks'
  KubectlVersion: '1.12.2'

steps:
- task: Kubernetes@0
  displayName: 'kubectl create configmap'
  inputs:
    kubernetesServiceConnection: 'aks-use-arch-dev'
    namespace: '$(KubernetesNamespace)'
    command: create
    configMapName: 'archsamplesapicontainers-config'
    forceUpdateConfigMap: true
    useConfigMapFile: true
    configMapFile: 'Arch.Samples.Api.Containers-CI/Deploy/deploy/config/Arch.Samples.Api.Containers/appsettings.json'
    versionSpec: '$(KubectlVersion)'
    checkLatest: true
```
