### ISSUE TITLE
InvokeRESTAPI: Dashes in Header name

### ISSUE THREAD

**Issue by koushik984** [Microsoft/azure-pipelines-tasks#9618]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines
        - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Agentless
    
## Issue Description

Using InvokeRestApi call through (YAML)[https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops] the pipeline does not execute when the header contains dashes '-'. (I have not tested with other special characters).

### Error logs
```
Exception Message: Invalid JavaScript property identifier character: -. Path '', line 1, position 8. (type JsonReaderException)
```
### Code

```
jobs: 
  # GET Data 
  - job: invoke_http_for_ase
    pool: server
    continueOnError: false
    steps:
      # Invoke REST API
      - task: InvokeRESTAPI@1
        displayName: 'GET'
        inputs:
          connectionType: connectedServiceNameARM
          azureServiceConnection: ARM - AZ SUB 01
          method: 'GET'
          #headers: '{Content-Type:application/json}'
          urlSuffix: "subscriptions/xxxx/resourceGroups/sample-rg/providers/Microsoft.Web/hostingEnvironments/ase?api-version=2016-09-01"
          waitForCompletion: 'true'
```
