### ISSUE TITLE
Azure App Service Deploy: Internal server errror 500

### ISSUE THREAD

**Issue by mrfoster** [Microsoft/azure-pipelines-tasks#9696]
## Environment

- Server: Azure Pipelines    
- Account name: techdept
- Team project name: 07722 - IngotStat
- Build definition name: Build
- Build number: 1902.26.3
- Release definition name: Release - Debug
- Release stage name: Production
- Agent: Private 
- OS: Windows 10
- Agent.Name: VSTS-BA1
- Agent.OS: Windows_NT
- Agent.OSVersion: 10.0.17134
- Agent.Version: 2.134.2

## Issue Description

Task: Azure App Service Deploy
Task Version:  4.3.20

Deploy to UAT slot is working correctly but deploy to production (no slot) is failing with the following error:
```
Failed to deploy web package to App Service.
Error: Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)
```

The UAT and production tasks appear to be set up in the same way.
UAT succeeds in under 1 minute:
```
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: '<REDACTED>'
    WebAppName: <REDACTED>
    deployToSlotOrASE: true
    ResourceGroupName: <REDACTED>
    SlotName: uat
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/<REDACTED>.zip'
    enableCustomDeployment: true
    DeploymentType: runFromZip
```

Production fails and takes nearly 4 minutes
```
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: '<REDACTED>'
    WebAppName: <REDACTED>
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/<REDACTED>.zip'
    enableCustomDeployment: true
    DeploymentType: runFromZip
```

Deployment has worked previously using version 3.* but often failed with locked files.  I am able to deploy directly using Web Deploy publish from Visual Studio.

The production Azure App has the following additional options:
- Set to Always On
- Has a LetsEncrypt certificate
- Has Application Insights monitoring

## Logs

[uat.log (Success)](https://github.com/Microsoft/azure-pipelines-tasks/files/2909703/uat.log)
[production.log (Failure)](https://github.com/Microsoft/azure-pipelines-tasks/files/2909710/production.log)
