### ISSUE TITLE
VsTestPlatformToolInstaller from Artifacts feed fails with '401 Unauthorized'

### ISSUE THREAD

**Issue by NKnusperer** [Microsoft/azure-pipelines-tasks#9757]
## Environment
- Azure DevOps Server 2019 RTW (17.143.28621.4)
- Agent v2.147.1 inside Docker Container based on `microsoft/dotnet-framework:4.7.2-runtime-20190212-windowsservercore-ltsc2019`

## Issue Description

I'am trying to use the `VisualStudioTestPlatformInstaller@1` task with the `customFeed` set to a Artifacts feed configured as a Upstream source for nuget.org (same Project Collection):
```yaml
- task: VisualStudioTestPlatformInstaller@1
  displayName: "Visual Studio Test Platform Installer"
  inputs:
    packageFeedSelector: customFeed
    customFeed: "https://srv-ados/MyCompany/_packaging/product-artifacts/nuget/v3/index.json"
    versionSelector: specificVersion
    testPlatformVersion: 15.9.1
    password: $(System.AccessToken)
```

The task is failing because of `The remote server returned an error: (401) Unauthorized.`
Using a PAT with full rights instead of `$(System.AccessToken)` also has the same result.
### Task logs

[log_8_128.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2942495/log_8_128.zip)

### Error logs
```
Attempting to gather dependency information for package 'Microsoft.TestPlatform.15.9.1' with respect to project 'C:\BuildAgent\_work\_temp\VsTest', targeting 'Any,Version=v0.0'
Unable to load the service index for source https://srv-ados/MyCompany/_packaging/product-artifacts/nuget/v3/index.json.
  An error occurred while sending the request.
  The remote server returned an error: (401) Unauthorized.
  No credentials are available in the security package
##[error]Failed to download version 15.9.1 of the test platform with error Error: C:\BuildAgent\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.1.5\nuget.exe failed with return code: 1.
```
