### ISSUE TITLE
JavaToolInstaller@0 error when using azureStorage

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-tasks#9772]
Affects Java versions 8, 9, 10, 11 and 12 on `windows-2019`, `macOs-10.13` and `ubuntu-16.04`. `JavaToolInstaller@0` fails whenever `jdkSourceOption: azureStorage` is specified. On Windows when I don't explicitly request 64-bit Java, the error is:
```
##[error]Cannot read property 'endsWith' of null
```
On Mac and Linux, or when I do explicitly request 64-bit, it is:
```
##[error]Specified JDK source file does not have a supported file extension.
```
See https://polymorpheus.visualstudio.com/BetterRandom/_build/results?buildId=7 for all other details.

**Comment by Pr0methean** [comment]
Diagnostic run: https://polymorpheus.visualstudio.com/BetterRandom/_build/results?buildId=8

**Comment by gregnorz** [comment]
Seeing this same issue on our Azure-hosted VS2017 build agents:

```
- task: JavaToolInstaller@0
    displayName: "Install JRE 8"
    inputs:
      versionSpec: '8'
      jdkArchitecture: 'x86'
      jdkSourceOption: AzureStorage
      jdkDestinationDirectory: '$(Agent.ToolsDirectory)/jdk8'
      cleanDestinationDirectory: false
```
