### ISSUE TITLE
Server jobs fail if pipeline pulls secrets from Azure key vault

### ISSUE THREAD

**Issue by mikeharder** [Microsoft/azure-pipelines-tasks#9810]
Server jobs fail if a pipeline pulls secrets from Azure key vault.  Given the following YAML:

```yaml
jobs:
  - job:
    pool: server
    steps:
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: '$(ServiceConnection)'
          headers: '{ "accept": "application/json" }'
          method: 'GET'
          urlSuffix: 'get'
```

With no secrets, the server job works as expected.  However, if the pipeline pulls secrets from Azure key vault, DevOps attempts to insert the `AzureKeyVault1` task into the server job, which fails with the following error message:

```
Task execution section of task definition for Id : 
1e244d32-2dd4-4165-96fb-b7441ca9331e is either missing or not valid.
```

A few possible fixes:

1. Don't insert the `AzureKeyVault1` task into server jobs
2. Modify the `AzureKeyVault1` task to not fail on server jobs
