### ISSUE TITLE
DownloadBuildArtifacts buildVersionToDownload option does not have any documentation.

### ISSUE THREAD

**Issue by EraYaN** [microsoft/azure-pipelines-tasks#9826]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server: Azure Pipelines 
   - Account: jellyfin-project
   - Project: jellyfin

- Agent: Hosted Ubuntu

## Issue Description
So the option does not have a doc string: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops
It says "(Required) undefined".

**And some context**
Used here: https://github.com/jellyfin/jellyfin/pull/1091
DownloadBuildArtifacts@0 does not seem to actually download the artifacts from the latest build from the given branch when the option `buildVersionToDownload` is set to `latestFromBranch`. And the build is current, which might be by design, but is undocumented.

The goal is to download a previous non-PR build that succeeds to compare the two artifacts for ABI compatibility.

Download 1 YAML:

```yaml
- task: DownloadBuildArtifacts@0
      displayName: Download the Reference Assembly Build Artifact
      inputs:
        buildType: 'current' # Options: current, specific
        buildVersionToDownload: 'latestFromBranch' # Required when buildType == Specific# Options: latest, latestFromBranch, specific
        allowPartiallySucceededBuilds: false # Optional
        branchName: '$(System.PullRequest.TargetBranch)' # Required when buildType == Specific && BuildVersionToDownload == LatestFromBranch
        downloadType: 'single' # Options: single, specific
        artifactName: '$(NugetPackageName)'# Required when downloadType == Single
        downloadPath: '$(System.ArtifactsDirectory)/current-artifacts'
```
Download 2 YAML:

```yaml
- task: DownloadBuildArtifacts@0
      displayName: Download the New Assembly Build Artifact
      inputs:
        buildType: 'current' # Options: current, specific
        allowPartiallySucceededBuilds: false # Optional
        downloadType: 'single' # Options: single, specific
        artifactName: '$(NugetPackageName)' # Required when downloadType == Single
        downloadPath: '$(System.ArtifactsDirectory)/new-artifacts'
```
### Task logs

This specific build, demonstrates the problem
https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=33

Result 1
```
Downloading artifacts for build: 33
Downloading items from container resource #/2624379/Jellyfin.Naming
Downloading artifact Jellyfin.Naming from: https://dev.azure.com/jellyfin-project//_apis/resources/Containers/2624379?itemPath=Jellyfin.Naming&isShallow=true&api-version=4.1-preview.4
Downloading Jellyfin.Naming/Emby.Naming.dll to /home/vsts/work/1/a/current-artifacts/Jellyfin.Naming/Emby.Naming.dll
Downloaded Jellyfin.Naming/Emby.Naming.dll to /home/vsts/work/1/a/current-artifacts/Jellyfin.Naming/Emby.Naming.dll
Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 1.009 secs, Download size: 23637Bytes
Successfully downloaded artifacts to /home/vsts/work/1/a/current-artifacts
```
Result 2
```
Downloading artifacts for build: 33
Downloading items from container resource #/2624379/Jellyfin.Naming
Downloading artifact Jellyfin.Naming from: https://dev.azure.com/jellyfin-project//_apis/resources/Containers/2624379?itemPath=Jellyfin.Naming&isShallow=true&api-version=4.1-preview.4
Downloading Jellyfin.Naming/Emby.Naming.dll to /home/vsts/work/1/a/new-artifacts/Jellyfin.Naming/Emby.Naming.dll
Downloaded Jellyfin.Naming/Emby.Naming.dll to /home/vsts/work/1/a/new-artifacts/Jellyfin.Naming/Emby.Naming.dll
Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 1.009 secs, Download size: 23637Bytes
Successfully downloaded artifacts to /home/vsts/work/1/a/new-artifacts
```

Newer builds also have issues with the specific build config, but that is probably purely user error. ALthough the documentation does not really give any pointers.
