### ISSUE TITLE
Docker + Elasticsearch on Azure Pipeline

### ISSUE THREAD

**Issue by saxenark** [Microsoft/azure-pipelines-tasks#9894]
Hi,

I have the following YAML definition. I am ensuring that I have Elasticsearch running on a docker which I will later on use for my tests. I am having difficulty in connecting to the Elasticsearch docker running on the agent. The curl command towards the end fails

```
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: docker pull docker.elastic.co/elasticsearch/elasticsearch:6.6.1
  displayName: Pulling Elasticsearch 6.6.1

- script: docker images
  displayName: Confirming Elasticsearch download

- script: sudo sysctl -w vm.max_map_count=262144
  displayName: Setting vm map map count

- script: docker run -d --rm -p 9200:9200 -p 9300:9300 --name elasticsearch6.6.1 docker.elastic.co/elasticsearch/elasticsearch:6.6.1
  displayName: Run Elasticsearch service in a docker and map 9200 & 9300 port to host

- script: docker container inspect --format '{{.NetworkSettings.Networks.bridge.IPAddress }}' elasticsearch6.6.1
  displayName: Getting ip address of Elasticsearch docker
  
- script: docker container ls
  displayName: Confirming running containers

- script: docker images
  displayName: Confirming installed images again...

- script: docker container inspect elasticsearch6.6.1
  displayName: Inspecting the docker container

- script: curl 'http://localhost:9200/?pretty'
  displayName: Running curl

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  enabled: false
```

The failure thrown by curl looks like so:

```
curl 'http://localhost:9200/?pretty'
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/dcac22e9-6b6f-443b-8497-c093dd6bb804.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
##[error]Bash exited with code '56'.
```
