### ISSUE TITLE
NPM - How to setup a CA for SSL self-signed

### ISSUE THREAD

**Issue by ROunofF** [Microsoft/azure-pipelines-tasks#9908]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Npm

## Environment
- Azure Pipelines: Can provide those if needed
- Agent - Hosted or Private: Private

## Issue Description
Doing config set ca "..." through the "Custom" NPM command isn't persisted so that when I try to do npm install in the next step, I'm _still_ getting a SELF_SIGNED certificate error
(How else can I pass a CA directly so npm can validate our internal CA certificate ?)

Here's an example Pipeline

```
pool:
  name: Hosted Build
  demands: npm
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'
  enabled: false

- task: Npm@1
  displayName: 'NPM Config'
  inputs:
    command: custom
    verbose: false
    customCommand: 'config set ca "..."'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
```

### Task logs

> Starting: npm install
> ==============================================================================
> Task         : npm
> Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Package Management.
> Version      : 1.148.0
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
> ==============================================================================
> SYSTEMVSSCONNECTION exists true
> SYSTEMVSSCONNECTION exists true
> [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" --version"
> 6.5.0
> [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
> ; cli configs
> metrics-registry = "https://registry.npmjs.org/"
> scope = ""
> user-agent = "npm/6.5.0 node/v11.9.0 win32 x64"
> 
> ; environment configs
> userconfig = "D:\\CI\\Agent-Bld\\_work\\1\\npm\\3731.npmrc"
> 
> ; builtin config undefined
> prefix = "C:\\Users\\USRAPP_A1_FDMTLBLD-1\\AppData\\Roaming\\npm"
> 
> ; node bin location = C:\Program Files\nodejs\node.exe
> ; cwd = D:\CI\Agent-Bld\_work\1\s
> ; HOME = C:\Users\USRAPP_A1_FDMTLBLD-1
> ; "npm config ls -l" to show all defaults.
> 
> [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"
> npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
> npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
> npm ERR! request to https://registry.npmjs.org/@types%2fbootstrap failed, reason: self signed certificate in certificate chain
> ...

### Error logs

> [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"
> npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
> npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
> npm ERR! request to https://registry.npmjs.org/@types%2fbootstrap failed, reason: self signed certificate in certificate chain
