### ISSUE TITLE
Xamarin.iOS Build Task mix features from V1 and V2 on documentation

### ISSUE THREAD

**Issue by ravero** [Microsoft/azure-pipelines-tasks#9923]
## Required Information
- **Type**: Bug
- **Task Name**: XamariniOSV2

## Environment
- Server - Azure Pipelines - general issue, not specific to account/build
- Agent - Hosted macOS

## Issue Description
The documentation provided for [Xamarin.iOS Build Task (V2)](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops#feedback) doesn't match the actual options of this build task. Worse yet is the fact that it lacks important features from the previous versions.

So I ask if the documentation is updated to provide accurate information or the task is updated to include the missing features that previously allowed signing an IPA from a file certificate/provisioning profile.

**Comment by DavidStaheli** [comment]
@ravero thanks for reporting this.  We made the documentation consistent for V2 (the changes should be live within a few days) and added a small sample for signing and provisioning a Xamarin.iOS app.  This small sample uses YAML.  Is that what you're using?  Can you please let us know if you hit any more obstacles?

### Sign and provision a Xamarin.iOS app

To sign and provision a Xamarin.iOS app, set `packageApp` to `true` and specify a signing identity and provisioning profile ID:

```yaml
- task: XamariniOS@2
    inputs:
      solutionFile: '**/*iOS.csproj'
      configuration: 'AppStore'
      packageApp: true
      signingIdentity: 'iPhone Developer: Chris Sidi (7RZ3N927YF)'
      signingProvisioningProfileID: 'iOS Team Provisioning Profile: com.hashtagchris.*'
```

See [Sign your mobile app during CI](../apps/mobile/app-signing.md) for more information about signing and provisioning your app.
