### ISSUE TITLE
Azure pipeline task (docker tasks) issues with encode of string

### ISSUE THREAD

**Issue by erudinsky** [Microsoft/azure-pipelines-tasks#9938]
Product: Azure DevOps
Agent: Hosted Ubuntu 1604
Azure pipeline task: docker build

YAML definition for the task:

```
pool:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@1
  displayName: 'Build app'
  inputs:
    azureSubscriptionEndpoint: 'proper-subscribtion-was-here'
    azureContainerRegistry: 'proper-registry-was-here'
    imageName: 'image-name-was-here:latest'
```

Dockerfile:

```
FROM ruby:2.4.1
RUN apt-get update -qq && apt-get install -y build-essential netcat-openbsd nodejs libpq-dev libpq-dev nodejs imagemagick
RUN mkdir /myapp
WORKDIR /myapp
ADD Gemfile /myapp/Gemfile
ADD Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD . /myapp
COPY docker-entrypoint.sh /usr/local/bin
ENTRYPOINT ["docker-entrypoint.sh"]
```

Failes on the second line when trying to fetch ubuntu repositories with inproperly encoded urls (see screenshot below). 

It used to work few days ago, no changes made, does not work now.

Failure screenshot:

![image](https://user-images.githubusercontent.com/9085802/55012968-24317380-4fe0-11e9-9940-4c5808b1299e.png)
