### ISSUE TITLE
Commands.md doesn't cover special characters

### ISSUE THREAD

**Issue by Pr0methean** [Microsoft/azure-pipelines-tasks#9985]
The following YAML template:
```
parameters:
  javaVersion: ''
steps:
  - bash: |
      JAVA_HOME=$(/usr/libexec/java_home -v ${javaVersion})
      echo "##vso[task.setvariable JAVA_HOME=a]'${JAVA_HOME}'"
    env:
      javaVersion: ${{ parameters.javaVersion }}
    displayName: Set Java Home
```
produces the following error:
```
##[error]Unable to process command '##vso[task.setvariable JAVA_HOME=a]'/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.
```
This happens both with the quotes and without. The slashes are necessary, since the variable is a path. How do I copy the java_home command's output, slashes and all, into the JAVA_HOME variable for the next step? (Inlining it would require me to duplicate the following step's template, which is also used in jobs that obtain JDKs in other ways.) The docuimentation should have answered that question.
