### ISSUE TITLE
NullReferenceException on xml transform

### ISSUE THREAD

**Issue by JGCreator** [microsoft/azure-pipelines-tasks#9996]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: IIS Web App Deploy (IISWebAppDeploymentOnMachineGroupV0)

## Environment
- Server - Azure Pipelines or TFS on-premises? 
Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account name: idtsynthbio
project name: syb
build number: WebSvc_CI_AbramsService_20190401.3

- Agent - Hosted or Private: 
    Private Agend (Deployment Group)

    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
[AGENT_OS] --> [Windows_NT]
[AGENT_OSARCHITECTURE] --> [X64]
[AGENT_VERSION] --> [2.149.1]

## Issue Description
On XML transform, a NullReferenceException is being thrown.

### Artifact Screenshot
![image](https://user-images.githubusercontent.com/5280734/55359988-c0ec8900-5498-11e9-9a89-2873285b0c6e.png)

### Pipeline Screenshot
![image](https://user-images.githubusercontent.com/5280734/55360087-0446f780-5499-11e9-97fa-20e620d9dca4.png)

### Pipeline _Development_ Stage Tasks Screenshot
![image](https://user-images.githubusercontent.com/5280734/55360223-5ab43600-5499-11e9-8236-dfd8d8ebeb02.png)

---
![image](https://user-images.githubusercontent.com/5280734/55360279-7ddee580-5499-11e9-9700-b1da08ac0d90.png)

---
![image](https://user-images.githubusercontent.com/5280734/55360314-98b15a00-5499-11e9-84cd-fa73b9370a13.png)

### Exported Task YAML
```
#Your build pipeline references an undefined variable named ‘Parameters.WebsiteName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  .artifactSource: '_WebSvc_AbramsService_CI'

steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: 'IIS Web App Deploy'
  inputs:
    WebSiteName: '$(Parameters.WebsiteName)'
    Package: '$(.artifactSource)\drop'
    RemoveAdditionalFilesFlag: true
    TakeAppOfflineFlag: True
    XmlTransformation: true
    XmlVariableSubstitution: True
```

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

![image](https://user-images.githubusercontent.com/5280734/55360671-b3d09980-549a-11e9-9758-ec4635d2ac80.png)

---
![image](https://user-images.githubusercontent.com/5280734/55360720-d82c7600-549a-11e9-9bcf-83995a44b3e6.png)

[tasklog.log](https://github.com/Microsoft/azure-pipelines-tasks/files/3031412/tasklog.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
